crates/hir/src/lib.rs, crates/hir_def/src/path/lower.rs, crates/hir_ty/src/diagnostics.rs, crates/hir_ty/src/diagnostics/decl_check.rs
=> minor: Move incorrect case diagnostic things into their module

crates/ide_assists/src/handlers/inline_call.rs
=> fix: wrap `inline_call` and `inline_into_callers` if it inlines into the left side of a binary expression

xtask/src/release.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10830
bors r+
=> internal: set upstream branch when promoting

xtask/src/release.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10829
bors r+
=> internal: pull website before generating new changelog

crates/ide/src/syntax_highlighting.rs, crates/ide/src/syntax_highlighting/format.rs, crates/ide/src/syntax_highlighting/inject.rs
=> fix: Disable string highlight injection for macros changing string literals

crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/completions/snippet.rs, crates/ide_completion/src/render.rs, crates/ide_completion/src/render/enum_variant.rs, crates/ide_completion/src/render/function.rs, crates/ide_completion/src/snippet.rs, crates/ide_completion/src/tests/expression.rs, crates/ide_completion/src/tests/pattern.rs, crates/ide_completion/src/tests/type_pos.rs, crates/syntax/src/display.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10316
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7531(this has already been fixed prior, from what I've seen)
bors r+
=> fix: Remove possible multiline details in completions

crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs, crates/ide_completion/src/completions/attribute.rs, crates/ide_db/src/helpers.rs
partially fixes #10666
renaming issues mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/10666#issuecomment-955671021 doesn't seem to be fixable at this moment since it's not searchable?(not recorded?) by name.
<del>I'm not sure if it's appropriate to move `parse_comma_sep_paths` function to a method in `ast/node_ext`, maybe `ide_db::helpers` also make sense.</del> put into `ide_db::` instead.
=> fix: derive attr path handling in `replace_derive_with_manual_impl`

crates/ide/src/highlight_related.rs
=> fix: Prioritize tuple fields in highlight_related

crates/hir_def/src/nameres/collector.rs
Followup to https://github.com/rust-analyzer/rust-analyzer/pull/10863, which caused a panic when analyzing diesel
bors r+
=> internal: Use the right `ItemTree` when re-resolving attr

crates/ide/src/expand_macro.rs
=> ide: fix macro expansion for 'as _'

crates/hir_def/src/item_tree.rs
=> minor: if-let-else to shorter match

crates/hir_def/src/item_tree.rs
=> minor: correct profiling name

crates/flycheck/src/lib.rs
=> minor: Don't discard flycheck error messages

crates/ide/src/inlay_hints.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/8491
bors r+
=> fix: Show parameter hints unconditionally for logical not expressions

crates/base_db/src/fixture.rs, crates/base_db/src/input.rs, crates/base_db/src/lib.rs, crates/hir/src/lib.rs, crates/ide/src/lib.rs, crates/ide/src/moniker.rs, crates/ide/src/static_index.rs, crates/project_model/src/cargo_workspace.rs, crates/project_model/src/project_json.rs, crates/project_model/src/tests.rs, crates/project_model/src/workspace.rs, crates/rust-analyzer/src/cli/lsif.rs
=> Emit moniker in lsif

editors/code/src/config.ts, editors/code/src/main.ts, editors/code/src/net.ts
Closes #10866
Currently untested.
=> Respect `http.proxyStrictSSL`

crates/ide/src/moniker.rs
Hi,
Not sure if this is the best fix for the problem, but I noticed that functions that part of a trait are not namespaced with the trait name, so this could lead to problems if you had a function and a trait-function both defined in the same module.
Thanks!
TJ
=> fix: emit trait names in moniker identifier

editors/code/src/config.ts
=> minor: Fix proxyStrictSSL check

crates/ide_assists/src/handlers/add_return_type.rs
I feel like the way I handled whitespace here isn't... Right? Maybe it should be folded into `InsertOrReplace::Insert`
Also, sorry about the commit name, I am _not_ good at writing user facing commit messages
Also sorry about the test names, could be clearer I feel
=> [first contributation] fix: `add return type` assit works when there's missing whitespace

crates/ide_assists/src/handlers/convert_while_to_loop.rs
=> feat: ide: Convert while let to loop

editors/code/package.json
Closes https://github.com/rust-analyzer/rust-analyzer/issues/10077
bors r+
=> internal: Define missing semantic token hierarchies in package.json

crates/ide_diagnostics/src/handlers/mismatched_arg_count.rs
=> minor: Shorten spans of mismatched_arg_count diag

crates/hir_def/src/item_tree/lower.rs, crates/hir_expand/src/name.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/4798
bors r+
=> minor: Update list of safe intrinsics

.github/workflows/release.yaml
=> minor: Bump Node to 14 in release workflow

editors/code/package-lock.json, editors/code/package.json, editors/code/src/net.ts
=> minor: bump the rest of the npm deps

crates/ide/src/syntax_highlighting/highlight.rs, crates/ide/src/syntax_highlighting/test_data/highlighting.html, crates/ide/src/syntax_highlighting/tests.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10575
bors r+
=> fix: Fix self keyword not being tagged as such in highlighting properly

Cargo.lock, crates/hir_expand/Cargo.toml, crates/ide_completion/Cargo.toml, crates/mbe/Cargo.toml, crates/rust-analyzer/Cargo.toml
=> minor: Clean up some unused cross-crate dependencies

editors/code/src/net.ts
=> minor: Fix HttpsProxyAgent creation and avoid deprecated call

crates/hir/src/lib.rs, crates/ide_completion/src/completions/flyimport.rs, crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/completions/unqualified_path.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/render/macro_.rs, crates/ide_completion/src/tests/attribute.rs, crates/ide_completion/src/tests/flyimport.rs
=> feat: Enable completions for attributes

crates/hir/src/source_analyzer.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10942
bors r+
=> internal: Prefer resolution of inert attributes

Cargo.lock, crates/hir_ty/Cargo.toml, crates/rust-analyzer/Cargo.toml, crates/rust-analyzer/src/bin/logger.rs
=> minor: Bump `tracing`

.gitignore, crates/ide/src/lib.rs, crates/ide/src/shuffle_crate_graph.rs, crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/lsp_ext.rs, crates/rust-analyzer/src/main_loop.rs, docs/dev/lsp-extensions.md, editors/code/package.json, editors/code/src/commands.ts, editors/code/src/lsp_ext.ts, editors/code/src/main.ts
May be useful for debugging issues like https://github.com/rust-analyzer/rust-analyzer/issues/10084
bors r+
=> internal: add "Shuffle Crate Graph" command

crates/ide_completion/src/completions/flyimport.rs, crates/ide_completion/src/completions/keyword.rs, crates/ide_completion/src/completions/pattern.rs, crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/completions/unqualified_path.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/patterns.rs, crates/ide_completion/src/render/builder_ext.rs, crates/ide_completion/src/render/macro_.rs, crates/ide_completion/src/tests/flyimport.rs
=> internal: completion: split out more PathKinds from ImmediateLocation

crates/project_model/src/workspace.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10827
bors r+
=> fix: Fix library target overriding sysroot deps

editors/code/package-lock.json, editors/code/package.json
=> minor: Bump vscode to 1.62

crates/hir_ty/src/method_resolution.rs
=> internal: Shrink TraitImpls and InherentImpls HashMaps

crates/hir/src/lib.rs, crates/hir_ty/src/method_resolution.rs, crates/hir_ty/src/traits.rs, crates/ide/src/goto_type_definition.rs, crates/ide/src/hover.rs, crates/ide_assists/src/utils/suggest_name.rs, crates/ide_completion/src/completions/pattern.rs, crates/ide_completion/src/tests/flyimport.rs, crates/ide_completion/src/tests/pattern.rs, crates/ide_db/src/helpers/import_assets.rs
=> fix: Don't show trait flyimports for impl trait and placeholders

crates/hir/src/display.rs, crates/hir/src/lib.rs, crates/hir_ty/src/autoderef.rs, crates/hir_ty/src/chalk_db.rs, crates/hir_ty/src/chalk_ext.rs, crates/hir_ty/src/diagnostics/match_check/deconstruct_pat.rs, crates/hir_ty/src/display.rs, crates/hir_ty/src/infer/coerce.rs, crates/hir_ty/src/lower.rs, crates/hir_ty/src/method_resolution.rs, crates/hir_ty/src/traits.rs, crates/hir_ty/src/utils.rs, crates/stdx/src/lib.rs
=> internal: Remove some allocations

crates/ide_db/src/helpers/import_assets.rs
=> minor: Remove unnecessary clones

crates/hir_ty/src/diagnostics/decl_check.rs, crates/ide_diagnostics/src/handlers/incorrect_case.rs
fix: #10980 (the allow/deny issue is not fully resolved though.)
=> fix: respect inner attributes for Structs and Enums

crates/ide_assists/src/handlers/generate_delegate_methods.rs, crates/ide_assists/src/lib.rs, crates/ide_assists/src/tests.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10996
bors r+
=> minor: fixup generate assist priorities

crates/proc_macro_api/src/version.rs
CC https://github.com/rust-analyzer/rust-analyzer/issues/10894#issuecomment-991993824
bors r+
=> fix: Add support for v6 macro metadata format

crates/hir_ty/src/infer/path.rs, crates/hir_ty/src/tests/method_resolution.rs, crates/ide/src/hover/tests.rs
=> Fix: Infer associated method in local scope

.github/workflows/release.yaml
=> minor: Enable workflow_dispatch for release workflow

.github/workflows/release.yaml
=> minor: Really switch XCode version

crates/ide_assists/src/handlers/move_guard.rs
Support the assist `move_arm_cond_to_match_guard` when there is an else branch.
I have two questions:
1. How to indent the first line of a match arm? `matcharm.indent()` doesn't seem to work. so I hard coded four spaces here:
https://github.com/weirane/rust-analyzer/blob/95a0de85d5d659e876e731725475f1c022719f31/crates/ide_assists/src/handlers/move_guard.rs#L162-L163
2. I find a little issue in the original implementation, this code
```rust
let y = match 92 {
x => {
if x == 0 {$0
false
}
}
_ => true,
};
```
will be transformed to
```rust
let y = match 92 {
x if x == 0 => false
_ => true,
};
```
a comma is missing after the `false`. Should I also fix that? Or this can go in a separate PR.
Closes #10997.
=> Support "move if to guard" with an else branch

crates/hir_def/src/item_tree.rs, crates/ide/src/hover.rs, crates/ide_completion/src/completions/attribute.rs, crates/ide_completion/src/tests/attribute.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11012
bors r+
=> fix: Don't duplicate attribute completions

crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
=> feat: treat fn keyword inside function pointer type as primitive

docs/user/manual.adoc, editors/code/.vscodeignore, editors/code/src/config.ts, editors/code/src/main.ts
CC #10483
This is slightly ugly, but we'll be able to clean it up after ripping the download parts (unless we decide to temporarily drop support for the nightlies).
=> internal: Prepare Code extension for bundling

docs/user/manual.adoc
cc https://github.com/rust-analyzer/rust-analyzer/pull/10261
=> minor: clarify RA_LOG env var troubleshooting

crates/ide_assists/src/handlers/unwrap_block.rs
The `unwrap_trivial_block()` removes the braces around trivial blocks (as the name suggests). This violates the precondition of `update_expr_string()` which removes the first and the last non-whitespace character and thus expects braces to still exist around all blocks.
=> fix #11049 by removing double trimming

crates/hir/src/semantics.rs, crates/hir/src/semantics/source_to_def.rs, crates/hir/src/source_analyzer.rs, crates/ide_db/src/defs.rs
We do not need inference info here so there is no point in calculating it
bors r+
=> internal: Don't kick off inference in `Semantics::descend_into_macros_impl`

crates/base_db/src/input.rs, crates/ide/src/highlight_related.rs, crates/ide/src/references.rs, crates/ide_db/src/search.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10007
bors r+
=> fix: Partially fix `ide_db::search` for crate roots

crates/rust-analyzer/src/bin/main.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10371
=> fix: Fix windows not finding the pdb file

crates/ide_assists/src/handlers/number_representation.rs
=> minor: Fix typo in reformat number assist label

crates/hir/src/semantics.rs, crates/hir/src/semantics/source_to_def.rs, crates/hir_expand/src/lib.rs
=> internal: Do less work in `hir::Semantics`

crates/ide_assists/src/handlers/inline_local_variable.rs
=> fix: Fix inline local assist not working in let stmt initializer

crates/hir/src/lib.rs, crates/ide_completion/src/completions.rs, crates/ide_completion/src/completions/lifetime.rs, crates/ide_completion/src/completions/pattern.rs, crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/completions/unqualified_path.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/render.rs, crates/ide_completion/src/render/const_.rs, crates/ide_completion/src/render/enum_variant.rs, crates/ide_completion/src/render/function.rs, crates/ide_completion/src/render/macro_.rs, crates/ide_completion/src/render/type_alias.rs, crates/ide_completion/src/tests/use_tree.rs
Removes all the helper render structs in favor of simple functions, making things a lot easier to oversee(imho)
bors r+
=> internal: Simplify completion rendering

crates/ide/src/hover/render.rs, crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/render/builder_ext.rs, crates/ide_completion/src/render/const_.rs, crates/ide_completion/src/render/enum_variant.rs, crates/ide_completion/src/render/function.rs, crates/ide_completion/src/render/type_alias.rs, crates/ide_completion/src/tests/expression.rs, crates/ide_completion/src/tests/pattern.rs, crates/ide_completion/src/tests/type_pos.rs, crates/syntax/src/display.rs
=> internal: Render more completions from hir instead of ast

crates/hir_def/src/import_map.rs, crates/hir_def/src/item_tree.rs, crates/hir_def/src/item_tree/lower.rs, crates/ide_completion/src/context.rs
=> internal: Deduplicate lower ctx hygiene field

crates/hir/src/lib.rs, crates/ide_completion/src/completions/dot.rs
=> internal: Directly use self param in completions instead of searching

crates/ide/src/hover/tests.rs, crates/ide_completion/src/completions/attribute/derive.rs, crates/ide_completion/src/completions/dot.rs, crates/ide_completion/src/completions/postfix.rs, crates/ide_completion/src/completions/record.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/render.rs, crates/ide_db/src/helpers/famous_defs.rs, crates/test_utils/src/minicore.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/5005
bors r+
=> fix: Do not complete `Drop::drop`, complete `std::mem::drop` instead

.github/workflows/release.yaml
=> Actually nightly releases to Matketplace

.github/ISSUE_TEMPLATE/bug_report.md
=> minor: Update known issues in the bug report template

Cargo.lock
=> :arrow_up: expect test

.github/actions/github-release/main.js
=> internal: Set a timeout on the Octokit client

crates/ide_db/src/helpers.rs
=> import style

crates/hir/src/semantics.rs, crates/ide_completion/src/completions/attribute.rs, crates/ide_completion/src/completions/attribute/derive.rs, crates/ide_completion/src/completions/keyword.rs, crates/ide_completion/src/context.rs
=> internal: avoid speculation when completing macros

crates/hir_def/src/macro_expansion_tests/mbe.rs, crates/hir_def/src/macro_expansion_tests/mbe/matching.rs, crates/parser/src/grammar.rs, crates/parser/src/grammar/expressions.rs, crates/parser/src/output.rs, crates/parser/src/shortcuts.rs, crates/parser/src/tests.rs, crates/parser/src/tests/entries.rs
=> internal: add tests for extra parser entry points

editors/code/src/main.ts
See https://github.com/rust-analyzer/rust-analyzer/commit/c0d0ceefb29111732cacf39dbb57fe9f3ce25ee8#commitcomment-62688259.
bors r+
=> fix: Fix server path on NixOS

crates/hir_def/src/macro_expansion_tests/mbe/matching.rs, crates/parser/src/tests/entries.rs
=> internal: add more tests for entry points

crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/reload.rs, crates/rust-analyzer/tests/slow-tests/support.rs, crates/rust-analyzer/tests/slow-tests/testdir.rs
=> feat: correctly fallback to notify if the clinet-side file watching is not supported

crates/parser/src/tests/entries.rs
=> internal: add more prefix entry point tests

crates/ide_completion/src/completions/qualified_path.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10462
bors r+
=> fix: Enable completions for `<_>::$0`

crates/hir_def/src/macro_expansion_tests/mbe.rs, crates/hir_def/src/macro_expansion_tests/mbe/tt_conversion.rs, crates/mbe/src/syntax_bridge.rs, crates/parser/src/tests.rs, crates/parser/src/tests/top_entries.rs
=> internal: more macro tests

crates/hir_def/src/macro_expansion_tests/mbe/tt_conversion.rs, crates/parser/src/grammar.rs, crates/parser/src/lib.rs, crates/parser/src/tests/top_entries.rs
=> internal: start enforcing invariants for top-level entry points

crates/hir_def/src/macro_expansion_tests/mbe/tt_conversion.rs, crates/ide/src/hover/tests.rs, crates/mbe/src/syntax_bridge.rs, crates/parser/src/grammar.rs, crates/parser/src/lib.rs, crates/parser/src/tests.rs, crates/parser/src/tests/top_entries.rs
=> internal: check top level entry point invariants

crates/hir_expand/src/db.rs, crates/mbe/src/syntax_bridge.rs, crates/stdx/src/non_empty_vec.rs
=> minor: drop dead code

crates/ide/src/syntax_highlighting/highlight.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11174
bors r+
=> fix: Fix highlighting hack for self-params

crates/ide/src/inlay_hints.rs
Passes tests as described in #10446
Works for all happy cases, there may be some cases that I forgot as I am not that familiar with Rust and r-a (yet).
=> internal: closes #10446 hide type inlay hints

crates/ide/src/syntax_highlighting.rs
=> internal: dont descend into comments

crates/mbe/src/expander/matcher.rs, crates/mbe/src/tt_iter.rs
=> minor: simplify mbe matcher

crates/hir_ty/src/diagnostics/expr.rs
=> internal: refactor: avoid separate traversal in replace filter map next with find map

crates/hir/src/semantics.rs, crates/hir/src/semantics/source_to_def.rs, crates/hir_def/src/attr.rs, crates/hir_def/src/nameres/collector.rs, crates/ide/src/goto_definition.rs, crates/ide/src/syntax_highlighting/highlight.rs, crates/ide_db/src/defs.rs, crates/ide_db/src/helpers.rs, crates/ide_db/src/helpers/import_assets.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11132
=> internal: Remove `SemanticScope::speculative_resolve_as_mac`

crates/ide/src/goto_definition.rs, crates/ide/src/highlight_related.rs, crates/ide/src/hover.rs, crates/ide/src/moniker.rs, crates/ide/src/static_index.rs, crates/ide_db/src/defs.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11129
bors r+
=> internal: Remove lossy `Definition::from_token`/`Definition::from_node` methods

crates/ide_completion/src/context.rs
Turns out we never filled the `CompletionContext` with the attribute expansion of attributed impls and traits when typing in the assoc items, as we were only considering the assoc item to have an attribute to expand.
bors r+
=> fix: Fix completions not considering ancestor items for attribute search

crates/ide_assists/src/handlers/apply_demorgan.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10963
bors r+
=> fix: Fix `apply_demorgan` assist hanging for certain binary expressions

crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
=> fix: `replace_qualified_name_with_use` does not use full item path for replacements

crates/hir_def/src/body.rs, crates/hir_def/src/child_by_source.rs, crates/hir_def/src/data.rs, crates/hir_def/src/item_tree.rs, crates/hir_def/src/lib.rs, crates/hir_def/src/nameres.rs, crates/hir_def/src/nameres/attr_resolution.rs, crates/hir_def/src/nameres/collector.rs, crates/syntax/src/ast/node_ext.rs
fixes https://github.com/rust-analyzer/rust-analyzer/issues/11104
bors r+
=> feat: expand attribute macros on impl and trait items

crates/syntax/src/ast/node_ext.rs
We now handle it correctly
bors r+
=> minor: Use`const _` instead of `mod __`

crates/rust-analyzer/src/bin/main.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/main_loop.rs, crates/rust-analyzer/tests/slow-tests/support.rs
=> feat: poke user when supplying faulty configurations

crates/hir/src/lib.rs, crates/hir/src/source_analyzer.rs, crates/hir_def/src/nameres.rs, crates/ide/src/hover/render.rs
=> internal: Support registered tools and attributes in ide layer

crates/ide_assists/src/handlers/generate_documentation_template.rs
From wrong behavior:
```rust
/// Creates a new [`MyGenericStruct<'a, T>`].
```
to correct behavior:
```rust
/// Creates a new [`MyGenericStruct<T>`].
```
But I feel like there is a better way to implement it. Do you know if there is an existing function that could do the work of `lifetimes_removed()` below?
=> fix(gen-doc-assist): remove lifetimes in description of `new`

crates/hir/src/lib.rs, crates/hir_expand/src/db.rs, crates/hir_expand/src/hygiene.rs, crates/hir_expand/src/lib.rs, crates/syntax/src/ast/node_ext.rs
Follow up to https://github.com/rust-analyzer/rust-analyzer/pull/11225#pullrequestreview-846779237
=> fix: Fix attribute stripping ignoring doc comments

crates/hir/src/semantics/source_to_def.rs, crates/hir_def/src/child_by_source.rs, crates/hir_def/src/data.rs, crates/hir_def/src/keys.rs, crates/ide/src/references.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11228
=> internal: Record attribute calls on assoc items in TraitData and ImplData

crates/rust-analyzer/src/config.rs, docs/user/generated_config.adoc
=> Fix documentation of snippet

crates/hir/src/lib.rs, crates/hir_def/src/body/lower.rs
Reports diagnostics from all block-level `DefMap`s, and adds some code to avoid adding duplicate diagnostics to the body's `SourceMap`.
bors r+
=> feat: Report `DefDiagnostic`s from inside item bodies

crates/hir_def/src/item_tree.rs, crates/hir_def/src/nameres/tests.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11249
bors r+
=> fix: fix `use super::{super::...};`

crates/ide_completion/src/completions/fn_param.rs, crates/ide_completion/src/tests/pattern.rs
=> fix: Fix don't drop param completions when fully typing out a pattern

crates/ide_completion/src/completions/postfix.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11233
bors r+
=> fix: Fix postfix completion panic

crates/syntax/src/ast/token_ext.rs
=> internal: Slightly cleanup HasFormatSpecifier::lex_format_specifier

crates/hir/src/has_source.rs, crates/hir/src/semantics.rs, crates/hir_expand/src/lib.rs, crates/ide_completion/src/completions/trait_impl.rs, crates/ide_completion/src/render/macro_.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11280
bors r+
=> fix: Properly cache files in Semantics when ascending macros

crates/ide/src/typing.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/629
bors r+
=> fix: Adjust `.` typing auto indentation

crates/hir_def/src/data.rs
`Expander` already does this, so we don't have to track the depth when collecting associated items.
bors r+
=> internal: Remove redundant recursion limit

crates/hir_def/src/data.rs
Introduce an `AssocItemCollector` instead of passing a lot of parameters around.
bors r+
=> internal: Clean up assoc item collection a bit

crates/ide/src/syntax_highlighting.rs, crates/ide/src/syntax_highlighting/format.rs, crates/ide_db/src/helpers/format_string.rs, crates/syntax/src/ast.rs, crates/syntax/src/ast/token_ext.rs
=> internal: Move format specifier lexing from syntax to ide_db

crates/ide_completion/src/completions/format_string.rs
=> fix: Temporarily disable format string completions

crates/hir_def/src/attr.rs, crates/hir_expand/src/builtin_derive_macro.rs, crates/hir_expand/src/db.rs, crates/hir_expand/src/eager.rs, crates/mbe/src/syntax_bridge.rs
=> internal: Make syntax bridge fully infallible

crates/hir_def/src/nameres/tests/macros.rs, crates/hir_expand/src/eager.rs, crates/ide_diagnostics/src/handlers/macro_error.rs
Fixes a few of the additional bugs in https://github.com/rust-analyzer/rust-analyzer/issues/10300, but not yet that issue itself.
bors r+
=> fix: More correct `$crate` handling in eager macros

crates/ide_completion/src/render.rs, crates/ide_completion/src/render/function.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10593
bors r+
=> fix: Deprioritize ops function completions for non-method calls

crates/project_model/src/cfg_flag.rs, crates/project_model/src/rustc_cfg.rs
=> minor: Add some debug traces for cfg fetching

crates/hir/src/lib.rs, crates/hir_ty/src/infer/expr.rs, crates/hir_ty/src/infer/path.rs, crates/hir_ty/src/method_resolution.rs, crates/ide_assists/src/handlers/convert_iter_for_each_to_for.rs, crates/ide_assists/src/handlers/generate_is_empty_from_len.rs, crates/ide_completion/src/completions.rs, crates/ide_completion/src/completions/attribute/derive.rs, crates/ide_completion/src/completions/dot.rs, crates/ide_completion/src/completions/flyimport.rs, crates/ide_completion/src/completions/mod_.rs, crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/completions/record.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/render/pattern.rs, crates/ide_completion/src/render/struct_literal.rs, crates/ide_completion/src/snippet.rs, crates/ide_db/src/helpers/import_assets.rs, crates/ide_ssr/src/resolving.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11372
=> fix: Complete functions and methods from block level impls

crates/ide_completion/src/completions/attribute.rs, crates/ide_completion/src/completions/format_string.rs
=> fix: Fix and re-enable format string completions

crates/ide_completion/src/completions.rs, crates/ide_completion/src/completions/dot.rs, crates/ide_completion/src/completions/extern_abi.rs, crates/ide_completion/src/lib.rs, crates/ide_completion/src/tests/expression.rs, crates/ide_completion/src/tests/record.rs
=> Sort completion calls lexicographically

crates/ide_completion/src/completions/vis.rs, crates/ide_completion/src/tests/visibility.rs
=> fix: Fix vis restriction path completions always using the parent module

docs/user/manual.adoc
=> Update install notes for bundled servers

Cargo.lock, crates/hir_def/Cargo.toml, crates/hir_def/src/intern.rs
=> Downgrade `dashmap` and bump `thread_local`

crates/rust-analyzer/src/lsp_ext.rs, docs/dev/lsp-extensions.md
=> add missing snake case attribute, update hash

crates/hir_expand/src/lib.rs
=> internal: Make `ascend_call_token` iterative instead of recursive

crates/rust-analyzer/src/global_state.rs
Fixes #11469
The description of GlobalState should be 'more than one impl'
=> correct the description of Struct GlobalState

crates/hir_ty/src/infer/pat.rs, crates/hir_ty/src/tests/patterns.rs
Fixes #11478 (feat or fix?),
I don't know much about the type-checking in RA, so maybe I did some obvious mistake.
=> Infer the array size for slice patterns

docs/user/manual.adoc
rust-analyzer/rust-analyzer.github.io#160
=> Updated the Sublime Text section

crates/ide_completion/src/completions/record.rs
Supercedes https://github.com/rust-analyzer/rust-analyzer/pull/10909
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10889
bors r+
=> fix: Fix qualfiied record literal completion triggering too eagerly

crates/hir/src/lib.rs, crates/hir_def/src/attr.rs, crates/hir_def/src/nameres/proc_macro.rs, crates/ide/src/references.rs, crates/ide_db/src/defs.rs, crates/ide_db/src/helpers.rs, crates/ide_db/src/search.rs, crates/rust-analyzer/src/handlers.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11212
=> internal: Handle proc-macro functions as the proc-macro they resolve to

crates/ide/src/annotations.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11213
bors r+
=> fix: Make code lenses work on attributed items

crates/hir_expand/src/lib.rs, crates/ide/src/expand_macro.rs, crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
=> fix: Fix expand_macro always expanding the first listed derive

docs/user/manual.adoc, editors/code/package.json
=> minor: Improve instructions for running pre-release versions

docs/user/manual.adoc
Follow-up of https://github.com/rust-analyzer/rust-analyzer.github.io/pull/181
Fixes https://github.com/rust-analyzer/rust-analyzer.github.io/pull/180
cc @lnicola
=> Add Kakoune and Helix configuration

crates/hir_def/src/nameres/collector.rs
=> internal: Reduce visibility of proc-macros to pub(crate) in nameres

crates/ide_assists/src/handlers/add_missing_match_arms.rs
Fixes #11499
Fixes #11500
This keeps track of the relevant attributes and adds in a wildcard pat at the end of the match when necessary.
I decided to do them in the same PR since they both needed the ability to add a wildcard arm, and so their changes would overlap if done separately, but I'll split them up if that seems better.
This is my first PR to rust-analyzer, so all feedback is greatly appreciated!
=> fix: Make fill_match_arms assist handle doc(hidden) and non_exhaustive

crates/ide/src/highlight_related.rs, crates/ide_db/src/helpers.rs, crates/syntax/src/lib.rs
=> 11422 highlight continue and break

crates/hir_def/src/macro_expansion_tests/builtin_fn_macro.rs, crates/hir_expand/src/builtin_fn_macro.rs, crates/hir_expand/src/name.rs
Support `concat_bytes`.
Solve #11544.
=> feat: support concat_bytes

crates/ide/src/syntax_highlighting.rs
Emitting these overwrites any syntax based highlighting that is being done in the file, causing a lot of noise if the user gave them a specific color.
bors r+
=> fix: Don't emit unresolvedReference highlight tags in unlinked files

crates/ide/src/syntax_highlighting.rs, crates/ide/src/syntax_highlighting/test_data/highlight_lifetimes.html, crates/ide/src/syntax_highlighting/tests.rs
=> fix: Fix semantic highlighting breaking for lifetimes in macros

crates/hir/src/lib.rs, crates/hir_def/src/body.rs, crates/hir_def/src/body/lower.rs, crates/ide/src/highlight_related.rs, crates/ide/src/rename.rs, crates/ide_assists/src/handlers/inline_local_variable.rs, crates/ide_db/src/rename.rs, crates/ide_db/src/search.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8860
This implements the first approach of https://github.com/rust-analyzer/rust-analyzer/issues/8860#issuecomment-845461773:
> treat every Local as having potentially many sources?
The way this is written does allow changing to a MultiLocal approach instead though, I'll investigate whether that turns out to be better or not in a follow-up.
=> feat: Support locals with multiple declaration sites

crates/hir_def/src/body/lower.rs, crates/ide/src/hover/tests.rs
Fixes #11582. Some questions below in the code review section.
=> fix: lower string literals with actual value instead of default

crates/hir_def/src/body/lower.rs, crates/hir_expand/src/lib.rs, crates/hir_ty/src/tests/macros.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11617
=> fix: Fix macro-calls expanding to items in if/while conditions

xtask/src/dist.rs
=> Fix package.json key replacement

Cargo.lock, crates/ide_assists/Cargo.toml, crates/ide_assists/src/handlers/extract_module.rs, crates/ide_assists/src/utils/suggest_name.rs, crates/ide_db/src/lib.rs
=> minor: Access parser internals through ide_db for ide crates

crates/hir/src/display.rs, crates/hir/src/lib.rs, crates/hir/src/semantics.rs, crates/hir_expand/src/builtin_attr_macro.rs, crates/hir_expand/src/db.rs, crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs, crates/ide_assists/src/handlers/remove_dbg.rs, crates/ide_completion/src/completions/attribute.rs, crates/ide_completion/src/completions/attribute/derive.rs, crates/ide_completion/src/completions/flyimport.rs, crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/completions/unqualified_path.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/lib.rs, crates/ide_completion/src/render/macro_.rs, crates/ide_completion/src/tests/attribute.rs, crates/ide_completion/src/tests/expression.rs, crates/ide_completion/src/tests/flyimport.rs, crates/ide_completion/src/tests/item.rs, crates/ide_completion/src/tests/item_list.rs, crates/ide_completion/src/tests/pattern.rs, crates/ide_completion/src/tests/predicate.rs, crates/ide_completion/src/tests/type_pos.rs, crates/ide_db/src/syntax_helpers/node_ext.rs, crates/syntax/src/display.rs
With this we now properly handle qualified path completions in derives
bors r+
=> internal: Expand into pseudo-derive attribute expansions in completions

Cargo.lock, crates/hir/src/diagnostics.rs, crates/hir/src/lib.rs, crates/hir_def/Cargo.toml, crates/hir_def/src/item_tree.rs, crates/hir_def/src/item_tree/lower.rs, crates/hir_def/src/item_tree/pretty.rs, crates/hir_def/src/nameres/collector.rs, crates/hir_def/src/nameres/diagnostics.rs, crates/hir_def/src/nameres/mod_resolution.rs, crates/ide_diagnostics/src/handlers/unresolved_module.rs, crates/rust-analyzer/tests/slow-tests/main.rs
=> fix: Show what file paths were expected for unresolved modules

crates/ide_completion/src/completions/keyword.rs, crates/ide_completion/src/completions/lifetime.rs, crates/ide_completion/src/context.rs, crates/ide_completion/src/lib.rs, crates/ide_completion/src/patterns.rs, crates/ide_completion/src/tests.rs
=> internal: Simplify CompletionContext

crates/rust-analyzer/src/to_proto.rs
=> minor: Pad type inlay hints if no colons are requested

xtask/src/metrics.rs
CC https://github.com/rust-analyzer/rust-analyzer/pull/11724#issuecomment-1069047929
=> minor: Fix metrics.json path

crates/ide/src/inlay_hints.rs, crates/ide/src/static_index.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/to_proto.rs, docs/user/generated_config.adoc, editors/code/package.json, editors/code/src/config.ts, editors/code/src/inlay_hints.ts
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11386
bors r+
=> feat: Add return type hints for closures with block bodies

Cargo.lock, crates/ide_db/Cargo.toml, crates/rust-analyzer/Cargo.toml, crates/sourcegen/Cargo.toml, xtask/Cargo.toml, xtask/src/metrics.rs
=> internal: Bump `xshell` and fix `dist`

crates/hir_ty/src/lower.rs, crates/hir_ty/src/tests/regression.rs
fix https://github.com/rust-analyzer/rust-analyzer/pull/11734#issuecomment-1070526085
=> Fix const generic panic, again

editors/code/package.json
=> minor: Remove Update GitHub API token command

crates/hir/src/lib.rs, crates/hir_def/src/data.rs, crates/hir_def/src/item_scope.rs, crates/ide/src/runnables.rs, crates/ide_db/src/defs.rs, crates/ide_db/src/helpers.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11746
bors r+
=> fix: Fix runnables trying to add doc tests in the crate root from #[macro_export] macros

crates/ide_completion/src/completions/pattern.rs, crates/ide_completion/src/tests/pattern.rs
Try close https://github.com/rust-analyzer/rust-analyzer/issues/11555
=> Complete associated consts in patterns 

crates/test_utils/src/lib.rs
=> internal: Allow explicitly specifying end of fixture annotation

crates/hir/src/lib.rs, crates/ide/src/call_info.rs, crates/ide_db/src/active_parameter.rs, crates/rust-analyzer/src/caps.rs
=> feat: Provide signature help when editing generic args

crates/ide/src/lib.rs, crates/ide/src/signature_help.rs, crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/to_proto.rs
It is no longer limited to just calls
bors r+
=> internal: Rename call info to "signature help"

crates/ide/src/inlay_hints.rs, crates/ide/src/lib.rs, crates/ide/src/static_index.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/to_proto.rs, crates/test_utils/src/lib.rs, docs/user/generated_config.adoc, editors/code/package.json
With names on:
With names off:
=> feat: Implement lifetime elision hints

crates/ide/src/inlay_hints.rs
=> fix: Fix closure hints using macro ranges

crates/ide_completion/src/completions/flyimport.rs, crates/ide_completion/src/tests/flyimport.rs, crates/ide_db/src/imports/import_assets.rs
=> fix: Fix flyimport showing functions in pattern position

crates/ide_completion/src/render/literal.rs, crates/ide_completion/src/render/pattern.rs, crates/ide_completion/src/tests/expression.rs, crates/ide_completion/src/tests/pattern.rs
=> fix: Fix tuple- and record struct completions not working with existing braces

crates/ide_completion/src/tests/flyimport.rs, crates/ide_db/src/imports/import_assets.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11506
=> fix: Correctly suggest auto importing traits from aliases

crates/hir_ty/src/autoderef.rs, crates/hir_ty/src/method_resolution.rs, crates/hir_ty/src/tests/method_resolution.rs, crates/ide/src/syntax_highlighting/tests.rs, crates/test_utils/src/minicore.rs
Fixes #10454, and some type mismatches.
=> fix: Don't try to resolve methods on unknown types

crates/ide_assists/src/handlers/generate_new.rs, crates/ide_assists/src/tests/generated.rs
CC https://github.com/rust-analyzer/rust-analyzer/pull/11737#issuecomment-1079740305
=> Revert "Emit #[must_use] in Generate new assist"

crates/hir_def/src/item_tree.rs, crates/hir_def/src/nameres/collector.rs, crates/ide/src/runnables.rs, crates/ide_completion/src/completions/qualified_path.rs, crates/ide_completion/src/tests/expression.rs
=> fix: Don't complete `Drop::drop` for qualified paths

Cargo.lock, crates/hir_ty/Cargo.toml
Pulls in https://github.com/rust-lang/chalk/pull/759.
bors r+
=> minor: Bump chalk

README.md, editors/code/README.md
No need to merge this now though
=> minor: Remove sponsors from readme files

crates/hir/src/semantics.rs, crates/hir/src/source_analyzer.rs, crates/ide/src/signature_help.rs, crates/ide_assists/src/handlers/inline_call.rs, crates/ide_db/src/defs.rs, crates/ide_db/src/path_transform.rs, crates/ide_ssr/src/resolving.rs
=> internal: Remove `PathResolution::AssocItem`

crates/ide_assists/src/handlers/generate_enum_is_method.rs, crates/ide_assists/src/handlers/generate_enum_projection_method.rs, crates/ide_assists/src/handlers/generate_from_impl_for_enum.rs
As discussed on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/generate.20_.20for.20.22an.20enum.20variant.22
=> minor: enum variant wording

crates/hir_def/src/nameres/collector.rs, crates/hir_def/src/nameres/tests.rs, crates/hir_def/src/nameres/tests/mod_resolution.rs
=> internal: Record outline child modules with missing backing file in def map

crates/ide_diagnostics/src/handlers/missing_fields.rs, crates/ide_diagnostics/src/handlers/missing_match_arms.rs, crates/syntax/src/ast/edit_in_place.rs, crates/syntax/src/ast/make.rs
=> fix: Add missing fields diagnostic fix for patterns

crates/ide_diagnostics/src/handlers/unresolved_module.rs, crates/rust-analyzer/tests/slow-tests/main.rs
=> fix: Show the path to be created in the unresolved-module fix label

crates/hir_expand/src/db.rs
This check is insufficient to ensure finite macro nesting, and so all callers already have their own recursion limit, which makes this check redundant.
...at least I hope it's redundant. Would be great if someone could double-check this.
Originally, this check was added in https://github.com/rust-analyzer/rust-analyzer/pull/3671
=> internal: Remove hir_expand macro recursion check

crates/hir_expand/src/lib.rs, crates/ide_db/src/search.rs
=> fix: Fix SearchScope using incorrect text ranges for macro-emitted inline modules

crates/ide_db/src/search.rs
=> Fix `SearchScope::reverse_dependencies` trying to search more files than necessary

crates/hir/src/source_analyzer.rs, crates/hir_ty/src/lower.rs, crates/ide/src/hover.rs
=> minor: Remove pointless rebindings

crates/ide_completion/src/completions/flyimport.rs, crates/ide_completion/src/tests/flyimport.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11918
bors r+
=> fix: flyimport: omit types when completing where-clause

Cargo.lock, crates/rust-analyzer/Cargo.toml, crates/rust-analyzer/src/dispatch.rs, crates/rust-analyzer/src/global_state.rs
=> minor: bump lsp-server version

crates/hir/src/lib.rs, crates/ide/src/rename.rs, crates/ide_assists/src/handlers/inline_call.rs
cc https://github.com/rust-analyzer/rust-analyzer/issues/11941
bors r+
=> fix: Check whether a parameter can be converted to a local

crates/base_db/src/input.rs, crates/hir/src/lib.rs, crates/ide_db/src/search.rs
=> internal: Revert #11912 as it parses all visited files

crates/ide_assists/src/handlers/extract_module.rs
Refactored `extract_module`.
Searching for usages and import resolving are done lazily.
Close #11944
=> fix: `extract_module` is too eager

docs/user/manual.adoc
=> Fix typo in the manual

crates/ide_completion/src/completions.rs, crates/ide_completion/src/completions/flyimport.rs, crates/ide_completion/src/completions/use_.rs, crates/ide_completion/src/item.rs, crates/ide_completion/src/render.rs, crates/ide_completion/src/render/function.rs, crates/ide_completion/src/render/literal.rs, crates/ide_completion/src/render/macro_.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11640
bors r+
=> feature: deprioritize already-imported names in `use` items

crates/ide_completion/src/completions/trait_impl.rs
Final item of https://github.com/rust-analyzer/rust-analyzer/issues/11860, thus closes https://github.com/rust-analyzer/rust-analyzer/issues/11860 :tada: 
bors r+
=> fix: Add trailing `;` when completing assoc const/type in trait impl

.github/workflows/ci.yaml, .github/workflows/metrics.yaml, .github/workflows/release.yaml, .github/workflows/rustdoc.yaml
=> minor: prepare CI for rust-lang move

README.md
Let's test if bors listens to me here
bors r+
=> minor: fix ide docs link

crates/hir_ty/src/infer.rs, crates/hir_ty/src/infer/expr.rs, crates/hir_ty/src/infer/pat.rs
=> internal: Remove frequent `Arc<Body>` clones in type checking

crates/hir/src/lib.rs, crates/ide_completion/src/tests/expression.rs
Follow up for #11991 
`hir`: Use `db.callable_item_signature` query more.
=> fix: Show `impl Trait` in argument positon in completion details

Cargo.lock, crates/ide/Cargo.toml, crates/ide/src/expand_macro.rs, crates/ide/src/navigation_target.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/10548
=> feat: Attempt to format `expand_macro` output with rustfmt if possible

crates/ide/src/ssr.rs, crates/ide_assists/src/assist_context.rs, crates/ide_assists/src/handlers/add_turbo_fish.rs, crates/ide_assists/src/tests.rs, crates/ide_db/src/assists.rs, crates/ide_diagnostics/src/handlers/unresolved_module.rs, crates/ide_diagnostics/src/lib.rs, crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt, crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt, crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt, crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt, crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt, crates/rust-analyzer/src/diagnostics/to_proto.rs, crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/lsp_ext.rs, crates/rust-analyzer/src/to_proto.rs, docs/dev/lsp-extensions.md, editors/code/src/commands.ts
Closes https://github.com/rust-lang/rust-analyzer/issues/12031
=> feat: display signature help when applying "Add `::<>`" assist

crates/hir_ty/src/lower.rs, crates/hir_ty/src/tests/regression.rs
=> Fix const generic panic in dyn trait

crates/rust-analyzer/src/bin/main.rs
This runs the server and proc-macro process in dedicated threads with 8 MB of stack space to paper over OS differences and fix occasional stack overflows.
This hopefully resolves https://github.com/rust-lang/rust-analyzer/issues/11669
=> fix: Spawn a new thread with a larger stack for the LSP and proc-macro server

crates/ide/src/signature_help.rs
=> fix: Fall back to parameter definitions on error types in signature help

Cargo.lock, crates/ide_completion/Cargo.toml, crates/ide_completion/src/completions/dot.rs
=> minor: Remove `either` dependency from `ide_completion`

crates/ide_assists/src/handlers/move_module_to_file.rs
Fixes #12045 
Note that I special case'd mod named `r#mod` as commented in the code. Although it's very unlikely that one would use such name, I included it in this fix for the sake of completeness.
=> fix: handle raw identifiers in move_module_to_file

crates/hir/src/diagnostics.rs, crates/hir/src/lib.rs, crates/hir_def/src/attr.rs, crates/hir_def/src/nameres/collector.rs, crates/hir_def/src/nameres/diagnostics.rs, crates/ide_diagnostics/src/handlers/unresolved_macro_call.rs
=> feat: diagnose unresolved derive macros

crates/ide_assists/src/handlers/inline_type_alias.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12109
=> feat: Make "inline type alias" work for `Self`

crates/ide_completion/src/completions/mod_.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12104
=> fix: fix outline mod completion with partial module name

Cargo.lock
CC https://github.com/notify-rs/notify/issues/401#issuecomment-1114010902
=> minor: Downgrade kqueue to fix NetBSD

crates/ide/src/signature_help.rs
Stop showing signature help after closing angle/round brackets.
Fixes #11624
=> fix: Don't show signature help after closing bracket

crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/reload.rs, docs/user/generated_config.adoc, editors/code/package.json
Fixes #11024
Not adding tests as discussed in the issue
=> Reload project on .cargo/config[.toml] changes

crates/ide-completion/src/completions.rs, crates/ide-completion/src/completions/item_list.rs, crates/ide-completion/src/completions/keyword.rs, crates/ide-completion/src/completions/pattern.rs, crates/ide-completion/src/completions/qualified_path.rs, crates/ide-completion/src/completions/snippet.rs, crates/ide-completion/src/completions/trait_impl.rs, crates/ide-completion/src/completions/unqualified_path.rs, crates/ide-completion/src/context.rs, crates/ide-completion/src/lib.rs, crates/ide-completion/src/tests/item.rs, crates/ide-completion/src/tests/item_list.rs, crates/ide-completion/src/tests/pattern.rs
cc https://github.com/rust-lang/rust-analyzer/issues/12144
=> internal: Lift out item list path completions from (un)qualified_path

crates/hir/src/lib.rs, crates/ide-completion/src/completions/dot.rs, crates/ide-completion/src/completions/expr.rs, crates/ide-completion/src/completions/flyimport.rs, crates/ide-completion/src/completions/item_list.rs, crates/ide-completion/src/completions/keyword.rs, crates/ide-completion/src/completions/snippet.rs, crates/ide-completion/src/completions/trait_impl.rs, crates/ide-completion/src/context.rs, crates/ide-completion/src/render/function.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12169
=> fix: Fix snippets triggering where they shouldn't

crates/hir-def/src/macro_expansion_tests/mbe.rs
cc https://github.com/rust-lang/rust-analyzer/issues/12216
=> internal: Add token mapping test for float literals

editors/code/src/config.ts
Closes https://github.com/rust-lang/rust-analyzer/issues/12288
=> fix: Fix incorrect config key in client config update

crates/ide-completion/src/context.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12264
=> fix: Fix incorrect expected type in completions for trailing match arms

editors/code/src/commands.ts
=> fix: Fix broken async callback in join lines

crates/ide/src/typing.rs, crates/rust-analyzer/src/caps.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/lsp_ext.rs, crates/rust-analyzer/src/main_loop.rs, docs/dev/lsp-extensions.md
I implemented my idea in #11398 in "cargo cult programming"-style without actually know what I'm doing, so feedback is welcome.  The PR is split into two commits to ease the review.  I used @unexge's original prototype, which forms the basis of the PR.
=> On typing handler for angle brackets(<) with snippets

crates/ide/src/doc_links.rs, crates/ide/src/hover/tests.rs
=> fix: special case base url of `BuiltinType` to core

.github/workflows/release.yaml
See https://github.com/microsoft/vscode/issues/149518.
=> internal: Publish universal VSIX to make VS happy

crates/rust-analyzer/src/reload.rs
Just skimmed today's changelog and came across the repetition
=> Fix typo in new `reload.rs` docs

.github/workflows/release.yaml
Reverts rust-lang/rust-analyzer#12359
=> Revert "internal: Try to publish the universal VSIX before the other ones"

.github/workflows/release.yaml
Reverts rust-lang/rust-analyzer#12349
=> Revert "internal: Publish universal VSIX to make VS happy"

crates/ide-completion/src/completions/dot.rs, crates/ide-completion/src/completions/postfix.rs, crates/ide-completion/src/context.rs, crates/ide-completion/src/render/function.rs
=> internal: Simplify DotAccess representation in completions

crates/ide-assists/src/handlers/generate_enum_variant.rs
=> Generate variant: insert code in file with enum definition

editors/code/src/ctx.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/7736
=> internal: Make use of the statusBarItem colors in VSCode

crates/ide/src/goto_declaration.rs, crates/ide/src/goto_definition.rs, crates/ide/src/goto_implementation.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/2541
=> minor: Freshen up goto feature docs

docs/dev/style.md
What matters for the changelog is having PR title/description from the user's perspective, while commits can be internal.
=> minor: Update commit/PR style guide

crates/hir-def/src/expr.rs, crates/ide/src/hover/tests.rs
=> fix: float display impl

editors/code/src/ctx.ts
=> [editors/vscode] cleaer status bar bg color / command  when server status returns to OK

crates/project-model/src/build_scripts.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/12457
=> internal: Only record build script outputs when the output has been changed

crates/rust-analyzer/src/main_loop.rs
Since we retry requests now we can actually hit this legitimately
=> minor: Don't log cancelled diagnostics

editors/code/src/config.ts
cc https://github.com/rust-lang/rust-analyzer/issues/12469#event-6743447147
=> fix: Restart the server instead of reloading the window when config changes

crates/ide-completion/src/completions/item_list/trait_impl.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12474
=> fix: Fix trait impl completions using wrong insert position

crates/project-model/src/build_scripts.rs
in `run` in `project-model/src/build_scripts.rs`
=> Remove the unneeded destructuring assignment

editors/code/package.json, editors/code/src/config.ts
Closes #12476 
I think this works quite well, but if you think it would be better to put it behind a setting I can do that.
=> Restart server automatically on settings changes

crates/ide-completion/src/completions/use_.rs, crates/ide-completion/src/tests/use_tree.rs
=> fix: complete non-std enum at the start of `use` completions

crates/ide-assists/src/handlers/add_label_to_loop.rs, crates/ide-assists/src/lib.rs, crates/ide-assists/src/tests/generated.rs
closes: #12392 
I changed `'loop` to `'l`, as `cargo check` says `'loop` is an invalid label name.
=> feat: add label to loop

crates/rust-analyzer/src/config/patch_old_style.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/12498
=> fix: Fix config patching for callable snippets

crates/rust-analyzer/src/main_loop.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12482
=> fix: Don't respond to cancelled requests when retrying them

crates/hir-ty/src/chalk_db.rs, crates/hir-ty/src/tests/traits.rs
I think the reason is same with #11815. 
add ```Sized``` bound for ```AsyncBlockTypeImplTrait```.
=> fix: #12441 False-positive type-mismatch error with generic future

editors/code/src/config.ts
These requires a window reload, as they are set before the server is being started
=> fix: Ask the user to reload the vscode window when changing server settings

crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/reload.rs, editors/code/src/ctx.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/10719
=> fix: Clear proc-macro changed flag when reloading workspace

crates/ide/src/folding_ranges.rs, crates/rust-analyzer/src/to_proto.rs
=> feat: add fold range for multi line match arm list

crates/hir-def/src/nameres/collector.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/12582
=> fix: attribute macros not being properly diagnosed

crates/hir/src/lib.rs, crates/ide-completion/src/render/variant.rs, crates/ide-completion/src/tests/special.rs
=> fix: completes non exhaustive variant within the defining crate

crates/ide-completion/src/completions/attribute.rs, crates/ide-completion/src/tests/attribute.rs
I changed the `target_feature` to match the description given in #12616.
=> Correct target_feature completion

crates/ide-completion/src/completions/flyimport.rs, crates/ide-completion/src/tests/flyimport.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12656
=> fix: Trigger flyimport completions in item lists again

crates/ide-completion/src/completions.rs, crates/ide-completion/src/completions/expr.rs, crates/ide-completion/src/completions/pattern.rs, crates/ide-completion/src/completions/use_.rs, crates/ide-completion/src/render/pattern.rs, crates/ide-completion/src/tests/fn_param.rs, crates/ide-completion/src/tests/pattern.rs, crates/ide-completion/src/tests/special.rs, crates/ide-completion/src/tests/use_tree.rs
=> fix: complete enum variants as patterns in pattern path

crates/ide-assists/src/handlers/extract_function.rs
This change fixes #10036, "Extract to function assist implements nonexistent
trait methods".
When we detect that the extraction is coming from within a trait impl, and that
a `self` param will be necessary, we adjust which `SyntaxNode` to `insert_after`,
and create a new empty `impl` block for the newly extracted function.
=> fix: Extract function from trait impl

crates/ide-assists/src/handlers/extract_function.rs
This change fixes #12705.
In `FunctionBody::analyze`, we need to search any `ClosureExpr`s we encounter
for any `NameRef`s, to ensure they aren't missed.
=> fix: Extract Function misses locals used in closures

crates/ide-completion/src/completions.rs, crates/ide-completion/src/completions/attribute.rs, crates/ide-completion/src/completions/attribute/derive.rs, crates/ide-completion/src/completions/item_list.rs, crates/ide-completion/src/completions/pattern.rs, crates/ide-completion/src/completions/use_.rs, crates/ide-completion/src/completions/vis.rs, crates/ide-completion/src/context.rs, crates/ide-completion/src/context/analysis.rs, crates/ide-completion/src/tests/attribute.rs, crates/ide-completion/src/tests/expression.rs, crates/ide-completion/src/tests/item.rs, crates/ide-completion/src/tests/item_list.rs, crates/ide-completion/src/tests/pattern.rs, crates/ide-completion/src/tests/predicate.rs, crates/ide-completion/src/tests/record.rs, crates/ide-completion/src/tests/type_pos.rs, crates/ide-completion/src/tests/use_tree.rs, crates/ide-completion/src/tests/visibility.rs
- should close #12439
- Suggest super according to the depth in tree
=> fix(completion): `super::` completion at crate root and module depth aware

crates/ide-db/src/imports/insert_use.rs, crates/ide-db/src/imports/insert_use/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12758
=> fix: Fix imports being inserted before doc comments in inline modules

crates/ide-completion/src/completions/fn_param.rs, crates/ide-completion/src/completions/item_list/trait_impl.rs, crates/ide-completion/src/context.rs, crates/ide-completion/src/context/analysis.rs, crates/ide-completion/src/render/pattern.rs, crates/ide-completion/src/tests/pattern.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/9522
=> fix: Improve self param completion applicability

crates/rust-analyzer/src/diagnostics/to_proto.rs, crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/main_loop.rs
=> fix: Work around Code bug with empty diagnostics

crates/ide-completion/src/render.rs
=> fix: Autocomplete for struct fields includes receiver

crates/ide-assists/src/utils/gen_trait_fn_body.rs
Addresses https://github.com/rust-lang/rust-analyzer/pull/12832#issuecomment-1193713473
=> Replace `debug_assert!` with `stdx::always!`

crates/rust-analyzer/src/cli/load_cargo.rs, crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12879
=> fix: Fix server panicking on project loading when proc-macros are disabled

crates/ide-completion/src/completions.rs, crates/ide-completion/src/completions/pattern.rs, crates/ide-completion/src/render/pattern.rs, crates/ide-completion/src/tests/pattern.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12852
=> fix: Fix pattern completions adding unnecessary braces

crates/ide-completion/src/completions/expr.rs, crates/ide-completion/src/render.rs, crates/ide-completion/src/tests/expression.rs, crates/ide-completion/src/tests/record.rs
cc https://github.com/rust-lang/rust-analyzer/issues/12196
=> fix: Don't complete marker traits in expression position

crates/rust-analyzer/src/reload.rs
Identity is the wrong behaviour for anything that's not an attribute here
=> Use an empty expander for ignored non-attribute proc-macros

crates/ide/src/hover.rs
=> Error Diagnostics appear in the wrong place

crates/ide/src/syntax_highlighting/tests.rs
CC https://github.com/rust-lang/rust-analyzer/pull/12903#pullrequestreview-1058906953
=> Fix `test_rainbow_highlighting` gate

editors/code/src/commands.ts
=> [code] make toggleInlayHints understand {off,on}UntilPressed

crates/base-db/src/input.rs, crates/hir-ty/src/consteval.rs, crates/ide-db/src/search.rs, crates/ide/src/goto_definition.rs, crates/ide/src/status.rs, crates/proc-macro-api/src/msg/flat.rs, crates/proc-macro-srv/src/abis/abi_1_58/proc_macro/mod.rs, crates/proc-macro-srv/src/abis/abi_1_58/ra_server.rs, crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/mod.rs, crates/proc-macro-srv/src/abis/abi_1_63/ra_server.rs, crates/proc-macro-srv/src/abis/abi_1_64/proc_macro/mod.rs, crates/proc-macro-srv/src/abis/abi_1_64/ra_server.rs, crates/proc-macro-srv/src/abis/abi_sysroot/ra_server.rs, crates/proc-macro-srv/src/dylib.rs, crates/rust-analyzer/src/diagnostics/to_proto.rs, crates/rust-analyzer/src/to_proto.rs, crates/syntax/src/fuzz.rs, lib/la-arena/src/lib.rs
=> Remove imports that are also in edition 2021's prelude

crates/hir-def/src/macro_expansion_tests/mbe.rs, crates/hir-def/src/macro_expansion_tests/mbe/regression.rs, crates/hir-def/src/macro_expansion_tests/mbe/tt_conversion.rs, crates/hir-def/src/macro_expansion_tests/proc_macros.rs, crates/hir-expand/src/builtin_fn_macro.rs, crates/hir-expand/src/fixup.rs, crates/ide-assists/src/handlers/add_missing_impl_members.rs, crates/mbe/src/syntax_bridge.rs, crates/proc-macro-srv/src/tests/mod.rs
Related:  https://github.com/rust-lang/rust-analyzer/issues/12260#issuecomment-1126957162
=> fix: Improve whitespace insertion in mbe

.github/workflows/ci.yaml, .github/workflows/release.yaml, editors/code/package-lock.json
Code is on 16 too, there's hopefully no need to keep using the old version.
=> Use Node 16 on CI and upgrade lockfile version

crates/ide-db/src/apply_change.rs
This is a rather spammy one, it shouldn't be `info`
=> minor: Change tracing event level in apply_change

crates/hir-ty/src/infer.rs, crates/hir-ty/src/tests/patterns.rs
=> fix: resolve path `Self` alone in value namespace

crates/ide-assists/src/handlers/inline_call.rs
=> feat: Improved inline_call to replace `Self`

Cargo.lock, crates/proc-macro-srv/Cargo.toml, crates/proc-macro-srv/src/lib.rs
Probably best to wait a week or two so we don't immediately give linux packagers problems again
=> Replace crossbeam with std's scoped threads

crates/ide-assists/src/handlers/inline_call.rs
=> Do not substitute `Self` when in same impl block

docs/user/manual.adoc
Part of https://github.com/rust-lang/rust-analyzer/issues/8844
=> minor: Add a short blurb about VS Code Live Share to the manual

crates/ide/src/doc_links.rs, crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html, crates/ide/src/syntax_highlighting/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13089
=> fix: Resolve doc links on impl blocks

crates/ide-assists/src/handlers/replace_turbofish_with_explicit_type.rs
And support `?` and `.await` expressions.
Fixes #13148.
The assist can still show up even if the turbofish's type is not used at all, e.g.:
```rust
fn foo<T>() {}
let v = foo::<i32>();
```
=> Prefer the type of expression in "Replace turbofish with type"

crates/parser/src/syntax_kind/generated.rs, crates/syntax/src/ast/generated/nodes.rs, crates/syntax/src/tests/sourcegen_ast.rs
Feel free to close if this is too minor.
(For context, I _have_ read the clippy policy in `dev/style.md`)
=> clippy: make generated code nice to read

crates/ide-completion/src/tests/expression.rs, crates/ide-db/src/active_parameter.rs
=> Suggest struct when completing enum

crates/hir/src/lib.rs
cc https://github.com/rust-lang/rust-analyzer/pull/12966
=> Fix diagnostics not working in enum variant bodies

crates/rust-analyzer/src/cli/load_cargo.rs
=> Use the sysroot proc-macro server for analysis-stats

lib/lsp-server/src/msg.rs
See https://github.com/microsoft/language-server-protocol/issues/1341
=> Add RequestFailed error code, as per spec 3.17

crates/ide/src/annotations.rs, crates/ide/src/annotations/fn_references.rs, crates/ide/src/lib.rs, crates/rust-analyzer/src/from_proto.rs, crates/rust-analyzer/src/to_proto.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13310
=> Fix annotations not resolving when lens location is set to whole item

crates/ide-assists/src/handlers/move_format_string_arg.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13261
=> Fix move_format_string_arg being tokentree unaware

crates/flycheck/src/lib.rs
cc https://github.com/rust-lang/rust-analyzer/issues/12936#issuecomment-1264670905
=> Prioritize restart messages in flycheck

crates/hir/src/lib.rs, crates/ide/src/highlight_related.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13352
=> Fix assertion failure in type inference (#13352)

.github/workflows/release.yaml
CC https://github.com/rust-lang/rust-analyzer/issues/11080#issuecomment-1279212120
=> internal: Set a timeout when publishing to OVSX

.github/workflows/ci.yaml, .github/workflows/release.yaml
Fixes more Node 12 deprecation warnings.
=> Bump `actions/setup-node`

crates/ide/src/lib.rs, crates/ide/src/parent_module.rs, crates/rust-analyzer/src/cargo_target_spec.rs, crates/rust-analyzer/src/global_state.rs, crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/main_loop.rs, crates/rust-analyzer/src/reload.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/13428
Fixes https://github.com/rust-lang/rust-analyzer/issues/13434
=> fix: Fix DidSaveDocument requests blocking the server on startup

crates/ide/src/static_index.rs
Just a minor clean-up I found while going through the code.
=> ide: Remove unnecessary continue.

crates/flycheck/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13477
=> fix: Fix standard flycheck command not being executed in the workspace it is being invoked for

docs/dev/architecture.md
=> internal: Clarify feature policy

editors/code/package-lock.json, editors/code/package.json
CC https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1330#note_1033611
=> minor: Bump ovsx

editors/code/package.json
=> Clarify what commands are debug commands in VSCode

crates/ide/src/references.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13407
=> minor: Deduplicate reference search results

editors/code/package.json
=> feat: Nest Cargo.lock under Cargo.toml in Code

crates/ide-completion/src/completions/item_list/trait_impl.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13586
=> fix: include generic parameter in GAT completions

crates/ide-completion/src/completions/item_list/trait_impl.rs
Previously, this was done in several places redundantly, but not for all items. It was also untested. This PR fixes that.
=> fix: Strip comments and attributes off of all trait item completions

crates/ide-assists/src/handlers/add_missing_impl_members.rs
=> Suppress "Implement default members" inside contained items

crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
=> fix: tuple to named struct inside macros

crates/hir-expand/src/name.rs, crates/hir-ty/src/infer.rs, crates/hir-ty/src/tests/patterns.rs
This PR implements the "collection" of the `va_list` type into the function parameter types list.
=> feat: Implement vararg parameter type inference

crates/ide/src/signature_help.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13672
=> fix: Fix signature help not showing up when cursor is between `))` or `>>`

crates/ide-assists/src/handlers/remove_parentheses.rs, crates/ide-assists/src/lib.rs, crates/ide-assists/src/tests/generated.rs, crates/syntax/src/ast.rs, crates/syntax/src/ast/prec.rs
Can be quite handy when refactoring :)
=> feat: Add "Remove redundant parentheses" assist

crates/ide-assists/src/handlers/unwrap_block.rs
Possible fix for #13679 
- I just added a parent case for let statements and it seems everything else was in place already, so turned out to be a small fix
=> feat: allow unwrap block in let initializers

crates/ide-completion/src/completions/postfix.rs
Possible fix for #7929
Fix the case where if a user types `&&42.o`, snippet completion was still applying &&Ok(42). Note this was fixed previously on `&&42.` but this still remained a problem for this case
Previous relevant PR: #13517
- The main problem why everything broke on adding an extra `o` was, earlier `dot_receiver` was `42.` which was a `LITERAL` but now `42.o` becomes a `FIELD_EXPR`
- Till now `include_references` was just checking for parent of `LITERAL` and if it was a `REF_EXPR`, but now we consider `FIELD_EXPR` and traverse all of them, finally to reach `REF_EXPR`. If `REF_EXPR` is not found we  just return the original `initial_element`
- We are constructing a new node during `include_references` because if we rely on `dot_receiver` solely we would get `&&42.o` to be …
=> fix: breaking snippets on typed incomplete suggestions

crates/base-db/src/fixture.rs, crates/base-db/src/input.rs, crates/hir-def/src/layout.rs, crates/hir-ty/src/db.rs, crates/hir-ty/src/layout.rs, crates/hir-ty/src/layout/adt.rs, crates/hir-ty/src/layout/target.rs, crates/hir-ty/src/layout/tests.rs, crates/hir/src/lib.rs, crates/ide/src/lib.rs, crates/ide/src/shuffle_crate_graph.rs, crates/project-model/src/lib.rs, crates/project-model/src/rustc_cfg.rs, crates/project-model/src/target_data_layout.rs, crates/project-model/src/tests.rs, crates/project-model/src/workspace.rs, crates/rust-analyzer/src/reload.rs, crates/test-utils/src/fixture.rs
This fails the tests still since those don't call into rustc yet
=> fix: Calculate the TargetDataLayout correctly for the selected target

crates/ide/src/inlay_hints.rs, crates/ide/src/inlay_hints/bind_pat.rs, crates/ide/src/inlay_hints/chaining.rs, crates/ide/src/inlay_hints/closure_ret.rs
=> internal: Pass `FamousDefs` around in inlay hints

crates/hir-ty/src/infer/path.rs, crates/hir-ty/src/method_resolution.rs, crates/hir-ty/src/tests/method_resolution.rs, crates/hir/src/lib.rs
Still lacking tests, will add those later
Fixes https://github.com/rust-lang/rust-analyzer/issues/13126
=> Fallback to invisible associated functions and constants if no visible resolutions are found

crates/ide/src/inlay_hints.rs, crates/ide/src/inlay_hints/discrimant.rs, crates/ide/src/lib.rs, crates/ide/src/static_index.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/to_proto.rs, docs/user/generated_config.adoc, editors/code/package.json
=> Enum variant discriminants hints

crates/ide-assists/src/handlers/extract_function.rs, crates/syntax/src/ast/make.rs
=> fix: keep whitespace in extract function handler

crates/ide-assists/src/handlers/qualify_method_call.rs
See https://github.com/rust-lang/rust-analyzer/pull/13825#issuecomment-1363289767
=> minor: Make `qualify_method_call` `RefactorRewrite`

crates/hir-def/src/attr.rs
=> minor: loop-that-never-loops

crates/hir-ty/src/infer/expr.rs, crates/ide-completion/src/completions/item_list/trait_impl.rs, crates/ide-db/src/line_index.rs, xtask/src/release/changelog.rs
=> minor: Iterate over arrays dirrectly, instead of going through a slice

crates/ide-assists/src/handlers/add_missing_match_arms.rs
=> fix: check orpat in missing match

crates/hir/src/semantics.rs, crates/syntax/src/ast.rs
=> minor: implement `AstNode` for `Either`

crates/ide/src/inlay_hints/adjustment.rs
I'm not sure how to make them look nicer, but it's at least something.
=> Add basic tooltips to adjustment hints

crates/rust-analyzer/src/config/patch_old_style.rs
This early return was missed in the initial PR, so if we aren't patching the `completion_addCallArgumentSnippets` `completion_addCallParenthesis` configs we won't be patching the checkOnSave ones...
=> Fix checkOnSave to check config patching not always working

crates/hir/src/lib.rs, crates/ide-assists/src/handlers/add_missing_match_arms.rs, crates/syntax/src/ast/make.rs
fixed https://github.com/rust-lang/rust-analyzer/issues/13970
=> feat: array match

crates/hir-def/src/db.rs, crates/hir-def/src/lang_item.rs, crates/hir-def/src/lib.rs, crates/hir-expand/src/name.rs, crates/hir-ty/src/autoderef.rs, crates/hir-ty/src/chalk_db.rs, crates/hir-ty/src/chalk_ext.rs, crates/hir-ty/src/diagnostics/expr.rs, crates/hir-ty/src/display.rs, crates/hir-ty/src/infer.rs, crates/hir-ty/src/infer/coerce.rs, crates/hir-ty/src/infer/expr.rs, crates/hir-ty/src/lang_items.rs, crates/hir-ty/src/lower.rs, crates/hir-ty/src/method_resolution.rs, crates/hir-ty/src/tests/traits.rs, crates/hir-ty/src/traits.rs, crates/hir-ty/src/utils.rs, crates/hir/src/display.rs, crates/hir/src/lib.rs, crates/hir/src/source_analyzer.rs, crates/ide-completion/src/tests/flyimport.rs, crates/project-model/src/sysroot.rs, crates/project-model/src/workspace.rs, crates/test-utils/src/minicore.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13395
=> Replace SmolStr usage with lang item enum for lang items

crates/ide/src/markdown_remove.rs
cc https://github.com/rust-lang/rust-analyzer/pull/13988#issuecomment-1399924205
=> Replace soft breaks in markdown with spaces

docs/user/manual.adoc
This PR adds a section for Rust support in Visual Studio IDE.
=> Adding section for Visual Studio IDE Rust development support

crates/ide-db/src/search.rs, crates/ide/src/references.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14014
=> fix: Fix assoc item search finding unrelated definitions

crates/ide-db/src/rename.rs, crates/ide/src/rename.rs
=> Don't include lifetime or label apostrophe when renaming

.github/workflows/autopublish.yaml, .github/workflows/publish-libs.yaml
https://github.com/rust-lang/rust-analyzer/issues/13912
=> internal: Try to fix auto-publishing of lib crates

crates/ide-assists/src/handlers/unwrap_block.rs
=> fix(ide-assists): unwrap block when it parent is let stmt

crates/ide/src/signature_help.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/13910
=> feat: show signature help when typing record literal

crates/base-db/src/input.rs, crates/hir-def/src/find_path.rs, crates/hir-def/src/nameres/tests.rs, crates/hir-def/src/nameres/tests/macros.rs, crates/hir-ty/src/tests/method_resolution.rs, crates/ide-completion/src/tests/special.rs, crates/project-model/src/tests.rs
=> internal: Set "current" edition to 2021

editors/code/src/ctx.ts, editors/code/src/util.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/13055
=> fix: Lazily create the trace output channel

crates/hir-ty/src/autoderef.rs, crates/hir-ty/src/method_resolution.rs, crates/hir-ty/src/tests/method_resolution.rs, crates/test-utils/src/minicore.rs
=> Unsize cast array only on pointer type

crates/ide/src/file_structure.rs
=> fix negative trait bound in outline view (#14044)

docs/user/manual.adoc
=> internal: Add a manual section for Flatpak

.github/workflows/fuzz.yml, crates/syntax/fuzz/Cargo.toml
Fixes broken Cargo.toml for fuzz tests and adds building of fuzz tests to the CI.
=> fuzz: Fixes broken Cargo.toml for fuzz tests

editors/code/language-configuration.json
=> Unify language configuration folding markers with server behaviour

Cargo.lock, crates/hir-ty/Cargo.toml, crates/hir-ty/src/layout/tests.rs, crates/project-model/src/lib.rs, crates/project-model/src/target_data_layout.rs
fix https://github.com/rust-lang/rust-analyzer/pull/14087?notification_referrer_id=NT_kwDOArGpCLM1NTEyMDQ5MjU3OjQ1MTk3NTc2#discussion_r1097850915
=> Reuse fetching target data layout from rustc function

crates/ide-completion/src/config.rs, crates/ide-completion/src/tests.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/integrated_benchmarks.rs, crates/rust-analyzer/src/to_proto.rs, docs/user/generated_config.adoc, editors/code/package.json
=> Add setting for limiting number of completions

Cargo.lock, crates/parser/Cargo.toml, crates/parser/src/lexed_str.rs, crates/syntax/Cargo.toml
Closes https://github.com/rust-lang/rust-analyzer/issues/9554
=> minor: Bump `rustc-ap-rustc_lexer`

crates/ide-completion/src/context/analysis.rs, crates/ide-completion/src/tests/item_list.rs
=> Add completion for function without body

crates/proc-macro-api/src/process.rs
These are harmless, but users tend to blame other things on them.
=> fix: Hide proc macro server version detection errors

.github/workflows/release.yaml
These have been requested a couple of times, so let's build them.
=> feat: Build `i686-pc-windows-msvc` binaries

crates/proc-macro-srv/src/abis/abi_sysroot/ra_server/token_stream.rs
=> fix: Fix proc-macro-server incorrectly stripping delimiters

crates/ide-assists/src/handlers/generate_getter.rs, crates/ide-assists/src/tests.rs
Fixes #14161.
Heya, I just added the code with some tests, but not sure if it's *the way* to do it -- I didn't refactor existing methods for the `check` test method, but added another calling layer.
=> Conditionally add snippet marker.

crates/ide-assists/src/handlers/remove_dbg.rs, crates/ide-assists/src/tests/generated.rs
=> Support removing nested `dbg!()`s in `remove_dbg`

crates/ide-assists/src/handlers/replace_if_let_with_match.rs
It currently trigger in the entirety of match which is less than ideal
=> fix: Adjust `replace_match_with_if_let` applicability range

crates/project-model/src/build_scripts.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/14282
=> minor: Fixup dylib extensions for rustc_private proc-macro loading

crates/ide-assists/src/handlers/convert_match_to_let_else.rs
=> fix multiple definition binding in match to let-else

crates/hir-expand/src/lib.rs, crates/ide-db/src/search.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/14229
=> fix: Fix search not searching bodies of attributed items

crates/hir-ty/src/mir/lower.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs
=> fix block with no termination in or patterns

crates/rust-analyzer/src/main_loop.rs
We already filtered these later on, but we might as well stop calculating them alltogether. This way we also show cargo diagnostics that occur outside of the workspace which can happen when something goes very wrong (and which usually then causes no check diagnostics to appear in the workspace at all)
=> internal: Don't attempt to calculate diagnostics in library crates

crates/hir-ty/src/consteval.rs, crates/hir-ty/src/tests/regression.rs, crates/hir-ty/src/tests/simple.rs
=> Revert #14285

crates/hir-ty/src/consteval/tests.rs, crates/hir-ty/src/mir/lower.rs, crates/hir-ty/src/mir/lower/as_place.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs
=> Fix stack overflow when derefrencing `&!`

crates/rust-analyzer/src/reload.rs
=> Fix overlap deduping infinite loop

editors/code/src/ctx.ts
And give that the most useful action for the given state.
=> internal: Allow the status bar item to be clicked again

crates/hir-def/src/body.rs, crates/hir-ty/src/infer/pat.rs, crates/hir-ty/src/mir/lower.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs
=> Add storage dead for let bindings without initializer

crates/hir-def/src/nameres.rs, crates/hir-def/src/visibility.rs, crates/ide-diagnostics/src/handlers/private_field.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14047
=> fix: Fix visibility resolution not respecting parent blocks

crates/ide-diagnostics/src/handlers/missing_unsafe.rs
=> feat: add an autofix for inserting an unsafe block to missing unsafe diagnostic

crates/project-model/src/cargo_workspace.rs, crates/project-model/src/lib.rs, crates/project-model/src/tests.rs, crates/project-model/src/workspace.rs, crates/rust-analyzer/src/cli/analysis_stats.rs, crates/rust-analyzer/src/cli/diagnostics.rs, crates/rust-analyzer/src/cli/lsif.rs, crates/rust-analyzer/src/cli/scip.rs, crates/rust-analyzer/src/cli/ssr.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/lsp_utils.rs, crates/rust-analyzer/src/main_loop.rs, crates/rust-analyzer/src/reload.rs
Also aggregates the warnings and errors so we don't discard previous ones.
cc https://github.com/rust-lang/rust-analyzer/issues/14327
=> internal: Report sysroot and rustc crate loading errors

crates/text-edit/src/lib.rs
Originally part of working on a structured snippet API (since sometimes the `$` bit of snippets would be broken off and would lead to it not being recognized), though since this is a pretty separate change, I thought it would make sense to put it into it's own PR.
The implementation is relatively straight forward and not overly optimized, though it's pretty low hanging fruit to optimize it when need be.
=> internal: Coalesce adjacent Indels

crates/hir-ty/src/mir/lower/as_place.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs
=> lower adjusts in simple index except the last one

editors/code/src/client.ts
closes https://github.com/rust-lang/rust-analyzer/issues/14480
=> fix: Fix vscode project linking popup buttons being swapped

crates/ide-assists/src/tests/sourcegen.rs, crates/ide/src/syntax_highlighting/highlight.rs, crates/sourcegen/src/lib.rs
Each FIXME fix has been split into its own commit, since they're all pretty independent changes.
(Forgot to open a PR for this a few days ago, oops)
=> minor: Fix some simple FIXMEs

crates/hir-ty/src/chalk_db.rs, crates/hir-ty/src/tests/coercion.rs, crates/hir-ty/src/tests/traits.rs, crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14443
=> fix: Fix block local impl trait solving regressions

crates/hir-ty/src/infer/closure.rs, crates/hir-ty/src/tests/regression.rs
fix https://github.com/rust-lang/rust-analyzer/pull/14470#issuecomment-1503084796
=> Fix inference in nested closures

crates/hir-def/src/layout.rs, crates/hir-ty/src/infer.rs, crates/hir-ty/src/layout.rs, crates/hir-ty/src/layout/tests.rs, crates/test-utils/src/minicore.rs
fix https://github.com/rust-lang/rust-analyzer/issues/14474#issuecomment-1501235394
=> Infer types of nested RPITs

crates/ide-completion/src/completions/flyimport.rs
Followup to #14549
Fixes https://github.com/rust-lang/rust-analyzer/pull/14549#discussion_r1163128814 and https://github.com/rust-lang/rust-analyzer/pull/14549#discussion_r1163132104
=> Fix faulty variable extraction

crates/rust-analyzer/src/from_proto.rs, crates/rust-analyzer/src/handlers.rs, crates/rust-analyzer/src/lsp_ext.rs, crates/rust-analyzer/src/to_proto.rs, docs/dev/lsp-extensions.md
Closes https://github.com/rust-lang/rust-analyzer/issues/12718
=> internal: Skip code lens resolution for mismatched document versions

editors/code/package.json, editors/code/src/commands.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/14457
=> fix: Fix view crate graph being broken due to webworker usage

crates/rust-analyzer/src/from_proto.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14568
=> fix: Fix inverted code lens resolve file version check

crates/hir-def/src/db.rs, crates/ide-db/src/lib.rs
Should fix the memory increase
=> fix: Bring back LRU limit for macro_expand query

crates/hir-ty/src/infer/closure.rs, crates/hir-ty/src/layout/tests/closure.rs, crates/hir-ty/src/mir/lower.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs
=> Fix need-mut large span in closures and a false positive

crates/ide/src/status.rs, crates/profile/src/memory_usage.rs
We should be able to use this infra to get a better grasp about what we might want to LRU
=> internal: Add some additional status ouput

crates/hir-ty/src/mir.rs, crates/hir-ty/src/mir/eval.rs, crates/hir-ty/src/mir/lower.rs, crates/hir-ty/src/mir/lower/pattern_matching.rs, crates/hir-ty/src/mir/pretty.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs
=> Fix panic in const eval and parameter destructing

crates/hir-expand/src/db.rs, crates/hir-expand/src/eager.rs, crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14571
=> fix: Fix vscode workspaces not working properly

crates/ide-assists/src/handlers/unwrap_result_return_type.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14496
=> Handle nested types in `unwrap_result_return_type` assist

crates/rust-analyzer/src/global_state.rs
Should fix https://github.com/rust-lang/rust-analyzer/issues/14791
=> fix: Fix process-changes duplicating change events

crates/hir-ty/src/consteval/tests.rs, crates/hir-ty/src/mir/lower.rs, crates/rust-analyzer/src/cli/analysis_stats.rs, crates/rust-analyzer/src/cli/flags.rs
=> Add metrics for unevaluated constants, failed mir bodies, and failed data layouts

crates/ide/src/inlay_hints.rs, crates/ide/src/inlay_hints/adjustment.rs, crates/ide/src/inlay_hints/bind_pat.rs, crates/ide/src/inlay_hints/binding_mode.rs, crates/ide/src/inlay_hints/chaining.rs, crates/ide/src/inlay_hints/closing_brace.rs, crates/ide/src/inlay_hints/closure_captures.rs, crates/ide/src/inlay_hints/closure_ret.rs, crates/ide/src/inlay_hints/discriminant.rs, crates/ide/src/inlay_hints/fn_lifetime_fn.rs, crates/ide/src/inlay_hints/implicit_static.rs, crates/ide/src/inlay_hints/param_name.rs, crates/ide/src/lib.rs, crates/rust-analyzer/src/handlers/request.rs, crates/rust-analyzer/src/to_proto.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/14595
=> Restructure InlayHint, no longer derive properties from its kind

crates/hir-ty/src/infer/closure.rs, crates/hir/src/lib.rs, crates/ide/src/highlight_related.rs, crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
Also special cases closures for ranged type hover to render the closure hover instead
=> feat: Render hover actions for closure captures and sig

crates/ide-assists/src/handlers/extract_function.rs
Fixes #14687
2 fixes for `extract_function` assist (related closely enough that I squashed into one commit):
- Locals in macro expressions have been analyzed only when they are in the top-level token tree the macro call wraps. We should consider all descendant tokens.
- `self` in macro expressions haven't been analyzed.
=> fix: consider all tokens in macro expr when analyzing locals

crates/hir-def/src/body.rs, crates/hir-ty/src/infer/closure.rs, crates/hir-ty/src/layout/tests/closure.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs
Fix `need-mut` false positive on self.
=> Fix `need-mut` false positive in closure capture of match scrutinee

crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/global_state.rs, crates/rust-analyzer/src/handlers/notification.rs, crates/rust-analyzer/src/main_loop.rs, crates/rust-analyzer/src/reload.rs
cc https://github.com/rust-lang/rust-analyzer/issues/14193
=> internal: Move flycheck and config errors to status notification

crates/hir-ty/src/infer/unify.rs, crates/hir-ty/src/tests/regression.rs, crates/hir-ty/src/traits.rs, crates/hir-ty/src/utils.rs
=> Evaluate `UnevalutedConst` before trait solving

crates/ide-assists/src/handlers/generate_delegate_methods.rs, crates/ide-assists/src/handlers/generate_function.rs, crates/syntax/src/ast/make.rs
Add `ty_alias` and make `impl_trait` , `fn` and `impl_` have more coverage.
=> Improve ast::make

crates/hir-def/src/body/lower.rs, crates/ide-diagnostics/src/handlers/undeclared_label.rs
fix https://github.com/rust-lang/rust-analyzer/pull/14892#discussion_r1213091393
=> fix bug in labeled for loop desugaring

crates/hir-ty/src/infer/closure.rs, crates/hir-ty/src/mir/lower.rs, crates/hir-ty/src/mir/lower/pattern_matching.rs, crates/hir-ty/src/utils.rs
I hope this reduces MIR memory usage.
=> Remove unnecessary `StorageDead`

Cargo.lock, crates/rust-analyzer/Cargo.toml
Hope this doesn't break #14984 again.
=> internal: Fix dependency warning

crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
Follow-up to #14989 :man_facepalming:
=> minor: remove commented out conflicts

crates/ide-completion/src/completions/dot.rs
Follow-up to #15026
A tuple struct may dereference to a primitive tuple (though unusual, which is why I previously overlooked this case). We should not show the same tuple index in completion in such cases.
Deduplication of indices among multiple tuple structs is already handled in the previous PR.
=> Deduplicate tuple indices for completion

crates/hir-ty/src/consteval/tests/intrinsics.rs, crates/hir-ty/src/mir/eval.rs, crates/hir-ty/src/mir/eval/shim.rs, crates/hir-ty/src/mir/eval/shim/simd.rs, crates/ide/src/inlay_hints/chaining.rs, crates/test-utils/src/minicore.rs
Increases passed tests on self from 49 to 52
=> Support more intrinsics in mir interpreter

editors/code/package.json
=> delete matching brace key binding

docs/user/manual.adoc, editors/code/package.json, editors/code/src/config.ts, editors/code/src/debug.ts, editors/code/src/run.ts
=> 13583 rename runnable env to runnables extra env

crates/rust-analyzer/src/handlers/request.rs
🤞 that CI is happy with this, edited this via github
=> Fix panic in `handle_code_action`

docs/user/manual.adoc
fixes #14882 . I don't think that this is the correct wording to express this but I at least wanted to take the initiative :)
=> Remind user to check $PATH after installation.

docs/user/manual.adoc
=> minor: Remove old section about downloading the server from the manual

crates/load-cargo/Cargo.toml
https://github.com/rust-lang/rust-analyzer/actions/runs/5506737360/jobs/10035802204
=> minor: Fix publishing of load-cargo crate

lib/lsp-server/Cargo.toml
=> Enable derive feature for serde in lsp-server

crates/hir-ty/src/mir.rs
Reverts rust-lang/rust-analyzer#15288
=> Revert "Handle TyAlias in projected_ty"

Cargo.toml, xtask/Cargo.toml
CC https://github.com/rust-lang/rust-analyzer/issues/15279
=> minor: Bump rust-version to 1.70 and use the workspace one in xtask

docs/user/manual.adoc
=> docs: Add example on how to change configuration options in Kate

crates/hir-expand/src/eager.rs
Some logic changed so this path can be hit now with a missing token tree.
=> fix: Fix bad unwrap in `eager_macro_recur`

crates/base-db/src/fixture.rs, crates/base-db/src/input.rs, crates/hir-ty/src/consteval/tests.rs, crates/hir-ty/src/mir/eval.rs, crates/hir-ty/src/mir/eval/shim.rs, crates/hir-ty/src/mir/eval/tests.rs, crates/hir-ty/src/mir/lower.rs
And some other changes in mir eval
=> Add mir lower support for tuple destructing assignment

crates/hir-def/src/data.rs, crates/hir-def/src/find_path.rs, crates/hir-def/src/lib.rs, crates/hir-def/src/nameres.rs, crates/hir-def/src/nameres/collector.rs, crates/hir-def/src/nameres/path_resolution.rs, crates/hir-def/src/resolver.rs
cc https://github.com/rust-lang/rust-analyzer/issues/14079
=> internal: Record import source IDs

crates/ide-assists/src/handlers/remove_unused_imports.rs
=> minor : Deunwrap remove_unused_imports

crates/ide-assists/src/handlers/convert_to_guarded_return.rs
=> minor : Deunwrap convert_to_guarded_return

crates/ide-assists/src/handlers/generate_delegate_methods.rs
=> minor : Deunwrap generate_delegate_methods

.github/workflows/ci.yaml, crates/hir-def/src/nameres/collector.rs, crates/hir-expand/src/builtin_fn_macro.rs, crates/hir-expand/src/hygiene.rs, crates/hir-ty/src/consteval/tests/intrinsics.rs, crates/hir-ty/src/infer/cast.rs, crates/hir-ty/src/layout.rs, crates/hir-ty/src/mir/eval/shim.rs, crates/hir-ty/src/mir/eval/shim/simd.rs, crates/hir-ty/src/mir/lower.rs
=> Update offset intrinsic to match 1.72

.github/workflows/metrics.yaml, xtask/src/flags.rs, xtask/src/metrics.rs
should give us a bit of async stuff
=> Add hyper-0.14.18 to metrics

crates/ide-assists/src/handlers/wrap_return_type_in_result.rs
=> minor : Deunwrap wrap_return_type_in_result

crates/rust-analyzer/src/handlers/notification.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15562
=> Clear native diagnostics on file closing

editors/code/package.json
=> Improve useRustcErrorCode description

crates/ide-assists/src/handlers/into_to_qualified_from.rs, crates/ide-assists/src/tests/generated.rs
=> fix: preceding QualifiedPathType for into_to_from assist

.github/workflows/metrics.yaml
I think this should be correct
=> fix: Fix metrics workflow to use deploy key

.github/workflows/autopublish.yaml
=> internal: Free up some disk space on auto-publish

crates/rust-analyzer/src/bin/main.rs
Addresses https://github.com/rust-lang/rust-analyzer/discussions/15784.
=> fix: Fix VS Code detection for Insiders version

crates/hir-ty/src/consteval/tests.rs, crates/hir-ty/src/diagnostics/match_check.rs, crates/hir-ty/src/infer.rs, crates/hir-ty/src/infer/closure.rs, crates/hir-ty/src/infer/pat.rs, crates/hir-ty/src/mir/lower/pattern_matching.rs, crates/hir/src/source_analyzer.rs, crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
=> Store binding mode for each instance of a binding independently

docs/dev/guide.md
This PR fixes two URLs in the guide.md file.
=> chore: fix urls in guide.md

.github/workflows/release.yaml
https://code.visualstudio.com/updates/v1_84#_windows-32bit-support-ends
=> internal: Disable win32-ia32 VSIX builds

editors/code/tsconfig.json
CC https://github.com/rust-lang/rust-analyzer/pull/15904
=> minor: Tweak tsconfig.json

crates/hir-def/src/nameres/path_resolution.rs
=> internal: Remove debugging code in path resolution

Cargo.toml
I suspect this wasn't intentional, right?
=> minor: Disable debuginfo again

editors/code/src/toolchain.ts
=> fix: Fix runnable cwd on Windows

Cargo.lock, Cargo.toml, crates/base-db/Cargo.toml, crates/hir-ty/src/consteval.rs, crates/hir-ty/src/layout.rs, crates/hir-ty/src/layout/adt.rs, crates/hir-ty/src/lower.rs, crates/hir-ty/src/mir/lower.rs, crates/hir-ty/src/mir/monomorphization.rs
Might f ix https://github.com/rust-lang/rust-analyzer/issues/15008, haven't tested
=> internal: Bump salsa

crates/hir-expand/src/lib.rs, crates/hir/src/semantics.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16050
=> fix: Fix token downmapping being quadratic

crates/hir-def/src/child_by_source.rs, crates/hir-expand/src/db.rs, crates/hir-expand/src/lib.rs, crates/hir/src/semantics.rs, crates/ide-diagnostics/src/handlers/unresolved_extern_crate.rs, crates/ide-diagnostics/src/handlers/unresolved_macro_call.rs, crates/syntax/src/ast/traits.rs
I didn't understand why the one in the semantics is different. Please tell me if it needs special action.
r? @Veykril
=> Replace `doc_comments_and_attrs` with `collect_attrs`, 2nd round

crates/hir/src/symbols.rs, crates/ide-completion/src/item.rs, crates/ide-completion/src/snippet.rs, crates/ide-completion/src/tests/flyimport.rs, crates/ide-db/src/imports/import_assets.rs, crates/ide-db/src/items_locator.rs, crates/ide-db/src/symbol_index.rs, crates/ide-db/src/test_data/test_doc_alias.txt, crates/ide-db/src/test_data/test_symbol_index_collection.txt, crates/syntax/src/ast/node_ext.rs, crates/syntax/src/utils.rs
And bump the query limit from 40 to 100
=> internal: Improve import asset perf a bit

Cargo.lock, Cargo.toml
Let's try out that sweet SIMD code path!
=> internal: Bump line-index

crates/hir-def/src/attr/builtin.rs
Fix #16105
r? @lnicola since you did this last time.
=> Update builtin attrs from rustc

crates/base-db/src/span.rs
cc https://github.com/rust-lang/rust-analyzer/issues/16118
=> minor: Add messages to some asserts for better debugging

.github/workflows/metrics.yaml, Cargo.lock, crates/ide-diagnostics/src/lib.rs, crates/ide/src/lib.rs, crates/rust-analyzer/Cargo.toml, crates/rust-analyzer/src/bin/main.rs, crates/rust-analyzer/src/cli.rs, crates/rust-analyzer/src/cli/flags.rs, crates/rust-analyzer/src/cli/rustc_tests.rs, xtask/src/flags.rs, xtask/src/metrics.rs
=> Run rust-analyzer on rustc tests in metrics

crates/sourcegen/Cargo.toml
=> minor: Don't auto-publish sourcegen

crates/ide/src/markdown_remove.rs
=> fix: Dont assume ascii in remove_markdown

crates/rust-analyzer/src/lsp/utils.rs
While reading through the code base, I stumbled across a piece of code that I found hard to read despite its simple purpose. This is my attempt at making the code easier to understand for future readers.
I won't be offended if this is too minor and not worth your time.
=> internal: Simplify implementation of apply_document_changes

crates/hir-expand/src/hygiene.rs
Follow up to https://github.com/rust-lang/rust-analyzer/issues/16200, there was another logical bug there.
=> fix: Fix SyntaxContextID using incorrect self IDs

crates/ide-assists/src/handlers/introduce_named_generic.rs
Fix #15734.
- Find params in `ancestors` instead of just `parent`
- Added tests (`replace_impl_with_mut` and `replace_impl_inside`)
=> fix: no code action 'introduce_named_generic' for impl inside types

crates/ide-db/src/defs.rs, crates/ide/src/hover/render.rs, crates/ide/src/lib.rs, crates/ide/src/moniker.rs, crates/ide/src/static_index.rs, crates/rust-analyzer/src/cli/scip.rs
=> SCIP: populate new SymbolInformation fields

docs/dev/guide.md
Updates dev guide based on 2024-01-01 release
=> internal: update docs/dev/guide.md based on 2024-01-01 release

crates/hir-def/src/data/adt.rs, crates/hir-ty/src/layout/tests.rs
=> fix: Fix panic on unaligned packed attribute

crates/ide-assists/src/handlers/merge_nested_if.rs, crates/ide-assists/src/lib.rs, crates/ide-assists/src/tests/generated.rs
=> feat: assist to merge nested if

crates/ide/src/hover.rs, crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/16374
=> feat: Goto type actions for notable trait hovers

crates/ide-db/src/imports/insert_use/tests.rs, crates/ide-db/src/imports/merge_imports.rs
Follow up to #16352 to properly order raw identifiers.
=> internal: properly order raw idents when ordering use trees

crates/ide/src/doc_links.rs, crates/ide/src/doc_links/tests.rs
=> Fix intra doc links

crates/parser/src/grammar/items.rs
https://github.com/rust-lang/rust-analyzer/pull/16314#discussion_r1457324734
=> Refactor `macro_call` to be consistent with other functions

Cargo.lock, Cargo.toml, crates/parser/src/lexed_str.rs, crates/syntax/src/validation.rs
This also reverts the earlier revert.
=> minor: Bump rustc crates

crates/ide/src/lib.rs, crates/ide/src/navigation_target.rs
Currently there is no proper way to get a target FileRange for a given Definition.
=> internal: Make TryToNav trait public

Cargo.lock, crates/rust-analyzer/Cargo.toml, crates/rust-analyzer/src/cli/scip.rs
=> internal: Bump scip

editors/code/src/main.ts
related to https://github.com/rust-lang/rust-analyzer/issues/16392
=> internal: VS Code: report conflict with `panicbit.cargo`

editors/code/src/main.ts
=> minor: polish warning msg

crates/parser/src/grammar/expressions.rs, crates/parser/test_data/parser/inline/err/0028_method_call_missing_argument_list.rast, crates/parser/test_data/parser/inline/err/0028_method_call_missing_argument_list.rs
close https://github.com/rust-lang/rust-analyzer/issues/16362
=> fix: emit parser error for missing argument list

.github/workflows/ci.yaml
CC https://github.com/rust-lang/rust-analyzer/pull/16413#issuecomment-1927592897
=> internal: run Clippy on Windows

.github/workflows/ci.yaml
=> minor: bump `paths-filter`

crates/ide-assists/src/handlers/flip_trait_bound.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/16522.
=> minor: test that flip_trait_bound works with trait objects

.github/workflows/release.yaml
=> internal: Also downgrade node to 16

.github/workflows/ci.yaml, crates/hir/src/term_search/tactics.rs, crates/ide-completion/src/item.rs, crates/rust-analyzer/tests/slow-tests/support.rs, crates/salsa/src/lib.rs, crates/salsa/src/lru.rs
I see some typos at lastest master :(
=> fix: checkout repo before run typos

crates/hir-ty/src/infer.rs, crates/hir-ty/src/infer/expr.rs, crates/hir/src/diagnostics.rs, crates/ide-diagnostics/src/handlers/inactive_code.rs, crates/ide-diagnostics/src/handlers/incorrect_case.rs, crates/ide-diagnostics/src/handlers/missing_fields.rs, crates/ide-diagnostics/src/handlers/missing_match_arms.rs, crates/ide-diagnostics/src/handlers/mutability_errors.rs, crates/ide-diagnostics/src/handlers/remove_trailing_return.rs, crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs, crates/ide-diagnostics/src/handlers/type_mismatch.rs, crates/ide-diagnostics/src/handlers/undeclared_label.rs, crates/ide-diagnostics/src/handlers/unresolved_field.rs, crates/ide-diagnostics/src/handlers/unresolved_ident.rs, crates/ide-diagnostics/src/handlers/unresolved_method.rs, crates/ide-diagnostics/src/lib.rs, crates/ide-diagnostics/src/tests.rs
This should cover missing local variables and missing unit structs and the like. It's conservatively marked experimental
=> feat: add unresolved-ident diagnostic

crates/hir-def/src/body/pretty.rs, crates/hir-def/src/import_map.rs, crates/hir-def/src/item_tree.rs, crates/hir-def/src/item_tree/lower.rs, crates/hir-def/src/item_tree/pretty.rs, crates/hir-def/src/nameres.rs, crates/hir-def/src/nameres/collector.rs, crates/hir-def/src/nameres/tests/macros.rs, crates/hir-ty/src/diagnostics/match_check/pat_util.rs, crates/hir-ty/src/mir/eval/shim.rs, crates/hir-ty/src/mir/eval/shim/simd.rs, crates/hir-ty/src/mir/lower.rs, crates/hir-ty/src/mir/lower/pattern_matching.rs, crates/ide-assists/src/handlers/generate_delegate_methods.rs, crates/ide-completion/src/completions/item_list/trait_impl.rs, crates/ide-db/src/imports/insert_use/tests.rs, crates/ide-db/src/symbol_index.rs, crates/ide/src/join_lines.rs, crates/load-cargo/src/lib.rs, crates/project-model/src/workspace.rs, crates/rust-analyzer/src/cargo_target_spec.rs, crates/rust-analyzer/src/cli/lsif.rs, crates/rust-analyzer/src/cli/rustc_tests.rs, crates/rust-analyzer/src/cli/scip.rs, crates/salsa/salsa-macros/src/query_group.rs, crates/salsa/src/debug.rs, crates/salsa/src/derived.rs, crates/salsa/src/input.rs, crates/salsa/src/interned.rs
My changes broke the rustc test runs since we use detached files for that, this should fix that. Also addresses some new nightly warnings wrt to unnecessary imports
=> internal: Fetch toolchain and datalayout for DetachedFiles

crates/ide-diagnostics/src/handlers/useless_braces.rs, crates/ide-diagnostics/src/lib.rs, crates/rust-analyzer/src/cli/rustc_tests.rs
Looks like some new test is stuck, this might help with figuring that out, though it unfortunately won't if its a chalk hang (which is the most likely)
=> internal: Attempt to add a timeout to rustc-tests

.github/workflows/metrics.yaml
The CI job for them frequently gets stuck and I am unsure why
=> internal: Disable rustc test metrics

crates/ide-completion/src/completions/format_string.rs
Hi! This PR adds autocompletion for constants (including statics) inside format strings and closes #16608.
I'm not sure about adding the `constants` field to the `CompletionContext`. It kinda makes sense, since it's in line with the `locals` field, and this way everything looks a bit cleaner, but at the same time does it really need to be there?
Anyway, let me know if anything should/can be changed. :)
=> fix: autocomplete constants inside format strings

crates/parser/src/grammar.rs, crates/parser/src/grammar/expressions.rs, crates/parser/src/grammar/expressions/atom.rs, crates/parser/src/grammar/generic_params.rs, crates/parser/src/grammar/items.rs, crates/parser/src/grammar/items/traits.rs, crates/parser/src/grammar/params.rs, crates/parser/src/grammar/patterns.rs, crates/parser/src/grammar/types.rs, crates/parser/src/parser.rs
The code is basically equivalent to the previous version, but it improves the readability by making it much more simpler and concise.
=> internal: Improve readability of the parser code

crates/hir-def/src/child_by_source.rs, crates/hir-def/src/item_scope.rs, crates/hir-def/src/src.rs, crates/hir-ty/src/method_resolution.rs, crates/hir-ty/src/tests/method_resolution.rs, crates/hir/src/lib.rs, crates/hir/src/symbols.rs, crates/ide/src/navigation_target.rs
The latest version of it no longer emits these
=> internal: Remove synstructure const hack support

crates/hir-def/src/body.rs, crates/hir-def/src/body/lower.rs, crates/hir-def/src/body/pretty.rs, crates/hir-def/src/body/scope.rs, crates/hir-ty/src/infer.rs, crates/hir-ty/src/layout.rs, crates/hir-ty/src/mir.rs, crates/hir-ty/src/mir/eval.rs, crates/hir-ty/src/mir/lower.rs, crates/hir-ty/src/mir/lower/pattern_matching.rs, crates/hir-ty/src/tests.rs, crates/hir-ty/src/tests/simple.rs, crates/hir/src/diagnostics.rs, crates/hir/src/lib.rs, crates/hir/src/semantics/source_to_def.rs, crates/hir/src/source_analyzer.rs, crates/ide/src/inlay_hints/implicit_drop.rs, crates/rust-analyzer/src/main_loop.rs
Small experiment to see if this simplifies things
=> internal: Don't desugar self param into a pattern

crates/ide-diagnostics/src/handlers/mutability_errors.rs, crates/ide-diagnostics/src/handlers/unused_variables.rs
add a leading underscore for unused variable
=> feat: add fix for unused_variables

crates/hir-def/src/data.rs, crates/hir-def/src/lib.rs, crates/hir-def/src/nameres/attr_resolution.rs, crates/hir-def/src/nameres/collector.rs, crates/hir-expand/src/builtin_attr_macro.rs, crates/hir-expand/src/db.rs, crates/hir-expand/src/eager.rs, crates/hir-expand/src/lib.rs
=> internal: Shrink MacroCallLoc

crates/ide/src/test_explorer.rs, crates/rust-analyzer/src/lsp/to_proto.rs
=> Distinguish integration tests from crates in test explorer

.github/workflows/release.yaml
=> internal: Build releases on Ubuntu 20.04

crates/rust-analyzer/src/global_state.rs, crates/rust-analyzer/src/reload.rs, crates/vfs/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/8623
=> internal: Don't eagerly try to read crate root file contents before VFS

editors/code/src/debug.ts
=> fix: Revert debug extension priorities

crates/project-model/src/workspace.rs
The condition was inverted accidentally..
=> fix: Fix `patch_cfg_if` not applying with stitched sysroot

crates/flycheck/src/command.rs, crates/flycheck/src/lib.rs, crates/flycheck/src/test_runner.rs, crates/rust-analyzer/src/global_state.rs, crates/rust-analyzer/src/handlers/request.rs, crates/rust-analyzer/src/main_loop.rs
=> Run cargo test per workspace in the test explorer

Cargo.lock, Cargo.toml, crates/hir-ty/src/display.rs, crates/hir-ty/src/lib.rs, crates/hir-ty/src/lower.rs, crates/hir-ty/src/tests/display_source_code.rs, crates/hir-ty/src/tests/patterns.rs, crates/hir-ty/src/tests/regression.rs, crates/hir-ty/src/tests/simple.rs, crates/hir-ty/src/tests/traits.rs, crates/ide-assists/src/handlers/extract_function.rs, crates/ide-assists/src/handlers/inline_call.rs, crates/ide-assists/src/tests/generated.rs, crates/ide-completion/src/tests/predicate.rs, crates/ide-completion/src/tests/type_pos.rs
And make use of the new error lifetime
=> internal: Bump chalk

editors/code/src/client.ts
Not gonna look into this until the next release, so I'd rather disable it for the time being
=> Temporarily disable unlinked file popup

crates/hir-ty/src/method_resolution.rs
=> minor: Fix `rustc_skip_array_during_method_dispatch` edition check

crates/ide-assists/src/handlers/wrap_unwrap_cfg_attr.rs, crates/ide-assists/src/lib.rs, crates/ide-assists/src/tests/generated.rs
https://github.com/rust-lang/rust-analyzer/assets/11785959/f5f1bb71-22e7-438b-9a22-65ebab1b362d
https://github.com/rust-lang/rust-analyzer/assets/11785959/36933a4e-0000-455a-abe3-af774cd854d0
Closes #13965
=> Wrap/Unwrap cfg_attr

Cargo.toml, crates/hir-ty/src/display.rs, crates/hir-ty/src/lib.rs, crates/hir-ty/src/tests/display_source_code.rs, crates/hir/src/lib.rs, crates/ide-assists/src/handlers/promote_local_to_const.rs, crates/ide-completion/src/completions/type.rs, crates/ide-db/src/label.rs, crates/ide-diagnostics/src/handlers/unresolved_field.rs, crates/ide-diagnostics/src/handlers/unused_variables.rs, crates/ide/src/hover/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15646
=> fix: Fix `impl Trait<Self>` causing stackoverflows

crates/ide-diagnostics/src/handlers/unused_variables.rs
Changes Unused Variable diagnostic to just look at the variable name, not the entire syntax range. 
Also added a test for an unused variable in an array destructure. 
Closes #17053
=> fix: Replace Just the variable name in Unused Variable Diagnostic Fix

Cargo.lock, crates/load-cargo/src/lib.rs, crates/project-model/src/workspace.rs, crates/rust-analyzer/src/global_state.rs, crates/rust-analyzer/src/main_loop.rs, crates/vfs/Cargo.toml, crates/vfs/src/lib.rs
I wanted to see what's happening during project loading and if it could be parallelized. I'm thinking maybe, but it's not this PR :)
=> chore: add some `tracing` to project loading

crates/hir-def/src/data.rs, crates/hir-def/src/find_path.rs, crates/hir-def/src/generics.rs, crates/hir-def/src/item_tree.rs, crates/hir-def/src/item_tree/lower.rs, crates/hir-def/src/item_tree/pretty.rs, crates/hir-def/src/item_tree/tests.rs, crates/hir-def/src/nameres/collector.rs, crates/hir-ty/src/lower.rs, crates/hir-ty/src/tests/regression.rs, crates/hir-ty/src/tests/traits.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16141
=> fix: Fix attributes on generic parameters colliding in item tree

crates/hir-def/src/item_tree.rs, crates/load-cargo/src/lib.rs, crates/rust-analyzer/src/global_state.rs, crates/stdx/src/lib.rs, crates/vfs/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16580
=> fix: Hash file contents to verify whether file actually changed

.github/workflows/metrics.yaml
The install won't persist across jobs
=> Fix metrics workflow not actually updating the toolchain

crates/hir/src/semantics.rs, crates/ide-completion/src/context/analysis.rs
=> feat: Enable completions within derive helper attributes

crates/rust-analyzer/src/lsp/from_proto.rs
cc https://github.com/rust-lang/rust-analyzer/issues/17289
=> minor: Add debug info to invalid offset error

crates/ide/src/rename.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17318
=> fix: Fix renaming imports of foreign items touching foreign sources

crates/ide-diagnostics/src/lib.rs, crates/rust-analyzer/src/caps.rs, crates/rust-analyzer/src/cli/analysis_stats.rs, crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/integrated_benchmarks.rs
=> internal: Expose snippet capability to diagnostic quickfixes

crates/hir-def/src/body/pretty.rs, crates/hir-def/src/body/tests.rs
=> internal: better print style for hir

crates/hir-ty/src/display.rs, crates/ide/src/inlay_hints/adjustment.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/10932
=> fix: Fix `HirDisplay` stackoverflow for parameter Self defaults

crates/hir-def/src/macro_expansion_tests/mbe.rs, crates/parser/src/grammar/patterns.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17441
=> fix: Fix pat fragment parsers choking on <eoi>

crates/syntax/src/lib.rs
Update of comment in api walkthrough
=> minor: Update lib.rs

crates/flycheck/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17445
=> fix: Fix flycheck panicking when cancelled

xtask/src/publish.rs
=> minor: Remove Changelog: XXX title from Github release notes

crates/ide-completion/src/completions/fn_param.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17550
=> fix: Fix parameter completions using macro expanded source ranges

crates/ide/src/call_hierarchy.rs, crates/rust-analyzer/src/handlers/request.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14839
=> fix: Fix callHierarchy LSP violation

xtask/src/flags.rs
CC https://github.com/rust-lang/rust-analyzer/pull/17559#issuecomment-2234052939
=> minor: Make xtask install work again

crates/hir-expand/src/builtin_fn_macro.rs, crates/mbe/src/to_parser_input.rs, crates/parser/src/grammar/paths.rs, crates/parser/src/grammar/types.rs, crates/parser/src/parser.rs, crates/parser/src/shortcuts.rs, crates/parser/src/tests.rs, crates/parser/src/tests/prefix_entries.rs, crates/parser/test_data/generated/runner.rs, crates/parser/test_data/parser/inline/ok/dyn_trait_type_weak.rast, crates/parser/test_data/parser/inline/ok/dyn_trait_type_weak.rs, crates/rust-analyzer/src/cli/diagnostics.rs, crates/syntax/src/parsing.rs, crates/syntax/src/parsing/reparsing.rs, xtask/src/metrics.rs
Turns out this is more important than I thought it would be given the metrics :)
=> Parse contextual dyn keyword properly in edition 2015

crates/parser/src/grammar/paths.rs, crates/parser/src/grammar/types.rs, crates/parser/test_data/parser/inline/ok/dyn_trait_type_weak.rast, crates/parser/test_data/parser/inline/ok/dyn_trait_type_weak.rs
There were a few more special cases to consider here -> https://github.com/rust-lang/reference/pull/1538
=> Add missing dyn parse special cases in 2015 edition

crates/ide-diagnostics/src/handlers/unresolved_field.rs
=> fix: early exit if unresolved field is an index

xtask/src/metrics.rs
=> minor: Fix metrics not running

crates/ide-assists/src/handlers/add_missing_impl_members.rs, crates/ide-db/src/path_transform.rs
=> fix: Panic in path transform with default type parameters

crates/project-model/src/sysroot.rs
=> minor: log error when sysroot can't be discovered

crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
=> fix: Trailing excess comma in "Convert to named struct" assist

crates/ide-assists/src/handlers/convert_while_to_loop.rs
=> fix: keep comments in convert_while_to_loop

crates/rust-analyzer/src/reload.rs
Priming caches is a performance win, but it takes a lock on the salsa database and prevents rust-analyzer from responding to e.g. go-to-def requests.
This causes confusion for users, who see the spinner next to rust-analyzer in the VS Code footer stop, so they start attempting to navigate their code.
Instead, set the `quiescent` status in LSP to false during cache priming, so the VS Code spinner persists until we can respond to any LSP request.
=> internal: ServerStatusParams should consider 'prime caches' in quiescent status

crates/hir-ty/src/consteval/tests.rs, crates/hir-ty/src/mir/eval.rs
=> Implement floating point casts in const eval

crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/flycheck.rs, crates/rust-analyzer/src/test_runner.rs
@HKalbasi I thought I included this in #17470 but it appears not so I have created a new issue #17959 for this fix.
=> fix: add extra_test_bin_args to test explorer test runner

LICENSE-APACHE, crates/salsa/LICENSE-APACHE
Closes #14586
Similar to https://github.com/rust-lang/rust/pull/67734
=> internal: Drop Apache license appendices

crates/ide-assists/src/handlers/toggle_macro_delimiter.rs, crates/ide-assists/src/lib.rs, crates/ide-assists/src/tests/generated.rs
=> assist: Add new assist toggle_macro_delimiter

crates/project-model/src/env.rs, crates/project-model/src/tests.rs
=> minor: Fix cwd used for proc macro expansion

crates/hir-def/src/nameres/collector.rs, crates/ide/src/goto_definition.rs, crates/test-utils/src/minicore.rs
=> fix: Fix name resolution of shadowed builtin macro

crates/ide-assists/src/handlers/generate_impl.rs
This makes the generated impl's indentation match the ADT it targets, improving formatting when using nested modules inside of the same file or when defining types inside of a function. See the added tests for an example.
At first I tried to call some of the convenient helpers that delegate to `IndentLevel::increase_indent` on the generated impl, but as the comment on that function notes it does not indent the first token, making it inapplicable here. I hope the solution in this PR is acceptable, please let me know if I missed something :)
=> fix: consider indentation in the "Generate impl" and "Generate trait impl" assists

xtask/src/codegen.rs
7d9e4fcc07e5de94e37b73436147cdbbaa35dbdc broke this on rustup toolchains, the `cmd` command is trying to be too smart here
=> fix: do not assume rustup is installed in xtask codegen take 2

crates/base-db/src/input.rs, crates/project-model/src/workspace.rs
As the issue here is no longer workable for us and this appearing for some repos due to package cycles which can cause we should downgrade it as some people tend to think this breaks r-a when it doesn't
=> minor: Downgrade cyclic deps error to warning

crates/ide-db/src/syntax_helpers/suggest_name.rs
fix #17631.
Better name suggestions for fn-calls / method-calls in the form of `from()`, `from_xxx()`, `into()`, etc.
=> feat: better name suggestions for fn

crates/ide-assists/src/handlers/replace_qualified_name_with_use.rs
This change helps a bit with the discoverability of `replace_qualified_name_with_use`. Specifically, it ensures that a cursor on the first path segment (e.g., `$0std::fmt::Debug`, where `$0` is the cursor) would result in an import along the lines of `use std::fmt;` and `fmt::Debug;` at the usage sites.
=> assist: ensure `replace_qualified_name_with_use` applies to the first path segment

crates/hir-def/src/body/lower/asm.rs, crates/ide-diagnostics/src/handlers/typed_hole.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18103
=> fix: Don't report typed hole error in asm! out ops

crates/ide-assists/src/handlers/generate_delegate_trait.rs
=> fix: Immutable tree panic in `generate_delegate_trait`

crates/ide-assists/src/handlers/extract_type_alias.rs, crates/ide-db/src/source_change.rs
Part of #15710
Adds additional `SourceChangeBuilder` methods to make it easier to migrate assists to `SyntaxEditor`.
As `SyntaxEditor`s are composable before they're completed, each created `SyntaxEditor` can represent logical groups of changes (e.g. independently performing renames of uses in a file from inserting the new item). Once a group of changes is considered "done", `SourceChangeBuilder::add_file_edits` is used to submit a set of changes to be part of the source change.
`SyntaxAnnotation`s are used to indicate where snippets are attached to, and using `SyntaxAnnotation`s also means that we can attach snippets at any time, rather than being required to be after all edits.
=> internal: Extend SourceChangeBuilder to make make working with `SyntaxEditor`s easier

crates/ide-completion/src/completions/attribute.rs, crates/ide-completion/src/tests/attribute.rs, crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
=> fix: Support expect in attribute completion and hover

crates/hir-ty/src/object_safety.rs, crates/hir-ty/src/object_safety/tests.rs
=> fix: Consider lifetime GATs object unsafe

editors/code/src/bootstrap.ts
=> fix: Fix bootstrap error message being incorrect

crates/ide-diagnostics/src/handlers/type_mismatch.rs
fix #18298.
We should insert `Ok(())` or `Some(())` instead of wrapping `return` with variants.
=> fix: incorrect autofix for missing wrapped unit in return expr

Cargo.lock, editors/code/package-lock.json, editors/code/package.json
I bumped Typescript and vsce; was a little tired of the warnings when running `vsce`.
=> vscode: update some dependencies

crates/hir-def/src/visibility.rs, crates/ide-completion/src/tests/pattern.rs
=> fix: private items are shown in completions for modules in fn body

.gitignore, crates/rust-analyzer/src/bin/main.rs, crates/rust-analyzer/src/cli/lsif.rs, crates/rust-analyzer/tests/slow-tests/cli.rs, crates/rust-analyzer/tests/slow-tests/main.rs, crates/rust-analyzer/tests/slow-tests/support.rs
Closes https://github.com/rust-lang/rust-analyzer/pull/18309
=> tests: Add `lsif_contains_generated_constant` test

.github/workflows/ci.yaml
Should be merged with coordination from an infra-admin.
=> Switch CI from bors to merge queues

crates/ide/src/inlay_hints.rs, crates/ide/src/inlay_hints/adjustment.rs, crates/ide/src/inlay_hints/binding_mode.rs, crates/ide/src/inlay_hints/closure_captures.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18346
=> internal: Merge separate inlay hints targeting same range

crates/ide/src/inlay_hints.rs, crates/ide/src/inlay_hints/adjustment.rs, crates/ide/src/inlay_hints/binding_mode.rs, crates/ide/src/inlay_hints/discriminant.rs, crates/ide/src/inlay_hints/implicit_static.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/18340
=> feat: Add text edits to more inlay hints

crates/rust-analyzer/src/lsp/capabilities.rs, crates/rust-analyzer/src/main_loop.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18424
=> fix: Fix the server not honoring diagnostic refresh support

crates/proc-macro-api/src/process.rs
Hi! This is my first time contributing to the `rust-analyzer`. This PR close #18443
=> Improve error message for too new proc-macro server

crates/hir-ty/src/chalk_db.rs, crates/hir-ty/src/dyn_compatibility.rs, crates/hir-ty/src/dyn_compatibility/tests.rs, crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
=> minor: Rename `dyn compatible` to `dyn-compatible`

Cargo.lock
=> minor: Bump xshell

crates/project-model/src/sysroot.rs
=> internal: Fix missing `rust-src` message

crates/hir-expand/src/fixup.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18545
=> fix: Fix syntax fixup inserting unnecessary semicolons

crates/intern/src/symbol.rs
Since the `ManuallyDrop` it returns can be safely used to consume the `Arc`, which is can cause UB if done incorrectly. See #18499.
Fixes #18499.
=> minor: Improve soundness a bit by making `TaggedArcPtr::try_as_arc_owned()` unsafe

crates/hir-def/src/resolver.rs, crates/hir/src/semantics.rs, crates/hir/src/source_analyzer.rs, crates/ide-db/src/defs.rs, crates/ide/src/rename.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18617
=> fix: Resolve generic parameters within use captures

crates/parser/src/grammar/expressions/atom.rs, crates/parser/test_data/generated/runner.rs, crates/parser/test_data/parser/inline/err/bad_asm_expr.rast, crates/parser/test_data/parser/inline/err/bad_asm_expr.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18623
=> fix: Fix parser getting stuck for bad asm expressions

crates/test-utils/src/minicore.rs
CC https://github.com/rust-lang/rust-analyzer/pull/18594#discussion_r1873240249
=> minor: Remove unstable attributes in minicore

crates/base-db/src/input.rs, crates/project-model/src/workspace.rs
Now that the sysroot can be loaded as a cargo project we no longer need it
=> Remove patch sysroot cfg-if hack

crates/ide-db/src/syntax_helpers/suggest_name.rs
=> minor: enhance name suggestion for `Arc<T>` and `Rc<T>`

docs/user/manual.adoc
This link was broken by #14026.
=> Fix publish workflow link in manual

crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
close #10171 
This PR enable derive conversion for structs with members evne if smippet text edit is disabled.
=> fix: Generate implementation with items even if snippet text edit is disabled

crates/ide-assists/src/handlers/extract_variable.rs
=> feat: Use string literal contents as a name when extracting into variable

crates/rust-analyzer/src/handlers/request.rs
cc https://github.com/rust-lang/rust-analyzer/issues/18709
=> internal: Set `result_id` for pull diagnostics

crates/ide-assists/src/handlers/unnecessary_async.rs, crates/ide-assists/src/tests/generated.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/18725
=> fix: Reduce applicability of unnecessary_async assist

crates/rust-analyzer/src/config.rs, crates/rust-analyzer/src/handlers/notification.rs, crates/rust-analyzer/src/main_loop.rs, docs/user/generated_config.adoc, editors/code/package.json
Closes https://github.com/rust-lang/rust-analyzer/issues/18141
=> fix: Properly check if workspace flychecking is allowed

crates/rust-analyzer/src/global_state.rs, crates/rust-analyzer/src/main_loop.rs, crates/rust-analyzer/src/reload.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/18736
=> fix: Delay initial flycheck until after build scripts

crates/rust-analyzer/src/handlers/notification.rs
Followup to https://github.com/rust-lang/rust-analyzer/pull/18738, https://github.com/rust-lang/rust-analyzer/pull/18563, cc https://github.com/rust-lang/rust-analyzer/issues/18141
=> fix: Fix flycheck workspace when requested but package was found

crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
=> fix missing name enum when hovering on fields in variants

crates/rust-analyzer/src/flycheck.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18811
=> fix: Fix flycheck cancellations leaving stale errors

crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
Continuation of #18795, as per comments in that PR
=> Fix no space insert before and after if value is only spaces

crates/rust-analyzer/src/flycheck.rs
https://github.com/rust-lang/rust-analyzer/pull/18729 was supposed to do this but we were still batching the clear command til the end
=> fix: Clear flycheck diagnostics per package properly

crates/rust-analyzer/src/config.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/18296
=> minor: Honor `CARGO_TARGET_DIR` for cargo target dir config

crates/edition/Cargo.toml
https://github.com/rust-lang/rust-analyzer/actions/runs/12347775610/job/34455437638
=> minor: Add description field to edition manifest

.github/workflows/metrics.yaml
We stack overflow there, its obvious that running this on CI is not viable as they break too easily
=> Disable rustc_test metrics again

crates/ide-completion/src/completions/expr.rs, crates/ide-completion/src/context.rs, crates/ide-completion/src/tests/expression.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15626#issuecomment-2569578860
=> Hide synthetic locals from completions

crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs, crates/hir-def/src/macro_expansion_tests/mod.rs, crates/hir-expand/src/builtin/derive_macro.rs, crates/ide-assists/src/handlers/move_bounds.rs, crates/ide/src/expand_macro.rs, crates/intern/src/symbol/symbols.rs, crates/syntax/src/ast/make.rs, crates/test-utils/src/minicore.rs
=> feat: Support the new `CoercePointee` derive

crates/project-model/src/env.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/18807
=> fix: Fix relative .cargo env vars not working

crates/base-db/src/lib.rs, crates/ide/src/lib.rs
=> minor: Fix grammar in doc comments

crates/ide/src/inlay_hints/binding_mode.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/11934, we've added them to all hints where it makes sense I think
=> fix: Fix `ref` text edit for binding mode hints

crates/ide/src/inlay_hints.rs, crates/ide/src/inlay_hints/adjustment.rs, crates/ide/src/inlay_hints/bind_pat.rs, crates/ide/src/inlay_hints/binding_mode.rs, crates/ide/src/inlay_hints/closure_ret.rs, crates/ide/src/inlay_hints/discriminant.rs, crates/ide/src/inlay_hints/extern_block.rs, crates/ide/src/inlay_hints/implicit_static.rs, crates/rust-analyzer/src/lsp/to_proto.rs
Doing it for this field is trivial, the other ones not so much
cc https://github.com/rust-lang/rust-analyzer/issues/13812
=> internal: Compute inlay hint text edits lazily

Cargo.lock, crates/profile/Cargo.toml, crates/rust-analyzer/Cargo.toml, crates/stdx/Cargo.toml
CC https://github.com/rust-lang/rust-analyzer/pull/18963#issuecomment-2599032407
=> minor: Bump `windows-sys`

lib/lsp-server/src/msg.rs, lib/lsp-server/src/socket.rs, lib/lsp-server/src/stdio.rs
=> lsp-server: Drop outgoing messages on background thread

crates/ide-assists/src/assist_context.rs, crates/ide-assists/src/handlers/extract_variable.rs
This one always gets in my way because it is so trigger happy in patterns.
=> Extract variable assist triggers less eagerly

crates/ide-completion/src/completions/item_list/trait_impl.rs, crates/ide-completion/src/context/analysis.rs
=> fix: Fix missing upmapping in trait impls completion

docs/dev/README.md
We never adjusted this post-org move 😅
=> Update outdated permissions section in the README.md

crates/ide/src/inlay_hints/adjustment.rs, crates/syntax/src/ast/prec.rs
We only ever need to consider parenthesis placement for pre and postfix operators, and that is by far a simpler problem to deal with then the general one.
=> Remove mutable syntax tree shenanigans from adjustment hints

crates/hir-ty/src/consteval.rs
=> minor: Add a FIXME for feature(adt_const_params)

Cargo.lock, xtask/Cargo.toml, xtask/src/codegen/grammar.rs
https://github.com/dtolnay/proc-macro2/issues/470
=> Bump proc-macro2 in xtask

crates/ide/src/inlay_hints/implicit_drop.rs
oh I miss other pattern 
follow up https://github.com/rust-lang/rust-analyzer/pull/19117 cc @ChayimFriedman2
=> minor: don't show drop hints for other pattern

crates/hir-ty/src/chalk_db.rs, crates/hir-ty/src/tests/coercion.rs, crates/hir-ty/src/tests/traits.rs
Reverts rust-lang/rust-analyzer#19122
=> Revert "pass struct fields to chalk"

crates/project-model/src/sysroot.rs
=> minor: Switch back to RUST_SRC_PATH

.github/workflows/release.yaml
=> internal: Downgrade to ubuntu-22.04 for aarch64 and arm builds

Cargo.toml
cc https://github.com/rust-lang/rust/issues/137351
I do not know what intention behind this was, the introducing PR doesn't state why
=> Disable incremental on release builds

Cargo.lock, crates/rust-analyzer/Cargo.toml, crates/stdx/Cargo.toml, crates/stdx/src/assert.rs, crates/stdx/src/lib.rs
Closes https://github.com/rust-lang/rust-analyzer/pull/19193
=> Vendor `always-assert` into `stdx`

docs/book/src/contributing/setup.md
There are some minor nits in setup.md that needs to be cleaned up.
=> doc: remove nit from setup.md

crates/profile/Cargo.toml, crates/profile/src/stop_watch.rs
cc https://github.com/rust-lang/rust/pull/137011
=> Cofigurate out ohos target to avoid compilation crashes

crates/rust-analyzer/src/lib.rs
Closes #19272
r? @Veykril not sure whether you want to look into this
=> Bump minimum supported toolchain to 1.82

.github/workflows/ci.yaml
=> Twiddle with the `rustup` invocation on CI

editors/code/src/ctx.ts, editors/code/src/run.ts, editors/code/src/util.ts
=> fix: Make RustAnalyzer:Run available in manifest file

crates/ide-assists/src/tests.rs, crates/ide-completion/src/render.rs, crates/ide-db/src/rename.rs, crates/ide-db/src/text_edit.rs, crates/ide/src/rename.rs, crates/ide/src/ssr.rs, crates/rust-analyzer/src/lsp/to_proto.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/19079
=> Make change annotations per text-edit

editors/code/package.json
Noticed this:
See the sidebar icon
[Screencast from 03-11-2025 08:38:12 PM.webm](https://github.com/user-attachments/assets/a8070f43-678c-46d8-af12-f64bfc260f17)
=> Add icons to views

.github/workflows/ci.yaml
=> minor: Use cargo nextest on CI

crates/ide/src/inlay_hints/closure_ret.rs
=> fix: Fix closure return inlayhints using macro ranges

crates/ide-assists/src/handlers/replace_let_with_if_let.rs
=> fix(ide-assists): `let else` to `if let else`

.github/workflows/ci.yaml, Cargo.lock, crates/base-db/src/input.rs, crates/hir-def/src/macro_expansion_tests/mod.rs, crates/hir-def/src/nameres/tests/incremental.rs, crates/hir-expand/src/proc_macro.rs, crates/ide/src/lib.rs, crates/load-cargo/src/lib.rs, crates/proc-macro-api/src/lib.rs, crates/project-model/src/workspace.rs, crates/project-model/test_data/output/cargo_hello_world_project_model.txt, crates/project-model/test_data/output/cargo_hello_world_project_model_with_selective_overrides.txt, crates/project-model/test_data/output/cargo_hello_world_project_model_with_wildcard_overrides.txt, crates/project-model/test_data/output/rust_project_cfg_groups.txt, crates/project-model/test_data/output/rust_project_hello_world_project_model.txt, crates/test-fixture/Cargo.toml, crates/test-fixture/src/lib.rs
Quite the ugly change, but its a fast one to fix the issue and also prevent it from recurring
Fixes https://github.com/rust-lang/rust-analyzer/issues/19404
=> fix: Fix, clarify and require a value for `proc_macro_cwd` of `CrateData`

editors/code/src/debug.ts
=> Fix debug sourceFileMap when using cppvsdbg

crates/hir/src/attrs.rs, crates/hir/src/lib.rs, crates/ide-assists/src/handlers/extract_function.rs, crates/ide-db/src/syntax_helpers/node_ext.rs, crates/ide/src/inlay_hints/generic_param.rs, crates/ide/src/inlay_hints/param_name.rs, crates/syntax/src/ast/node_ext.rs
Closes https://github.com/rust-lang/rust-analyzer/pull/19039
=> fix: Cleanup param name inlay hint filtering

.github/workflows/ci.yaml
It doesn't actually work with merge groups ... [#t-infra > Help with rust-analyzer's CI](https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/Help.20with.20rust-analyzer's.20CI/with/509202957)
=> chore: Disable rust-cache in CI

crates/mbe/src/expander/transcriber.rs, crates/syntax/src/syntax_editor.rs, xtask/src/codegen/grammar.rs, xtask/src/tidy.rs
Not much here, just some cleanup.
=> chore: clean up some FIXMEs

editors/code/src/config.ts, editors/code/src/debug.ts, editors/code/src/util.ts
fixes rust-lang/rust-analyzer#19414
=> add normalizeDriveLetter

.github/workflows/ci.yaml
Fixes: https://github.com/rust-lang/rust-analyzer/issues/19599
=> Pin rustc used for the `proc-macro-src` CI job

crates/ide-assists/src/handlers/extract_function.rs
fix: rust-lang/rust-analyzer#19547
Extract the format arguments in macro string.
```rs
fn foo() {
let x = 10;
let y = 20;
fun_name(x, y);
}
fn fun_name(x: i32, y: i32) {
format!("{x} {}", y + 1);
}
```
=> fix: `Extract into` function include inline variable in fmt macro

crates/ide/src/highlight_related.rs
fix rust-lang/rust-analyzer#19138.
This PR adds highlighting for tail expressions of labeled blocks.
=> fix: highlighting for tail expr in labelled blocks

crates/rust-analyzer/src/config.rs
Fixes rust-lang/rust-analyzer#19641.
=> fix: Two config code changes

crates/ide/src/hover/render.rs, crates/ide/src/hover/tests.rs
Changes:  
1. Remove duplicate code.  
2. Add backticks to improve rendering.
=> minor: simplify and enhance notable traits rendering

crates/ide-diagnostics/src/handlers/incorrect_generics_len.rs
cc https://github.com/rust-lang/rust-analyzer/issues/19668 https://github.com/rust-lang/rust-analyzer/issues/19669
=> minor: Mark `incorrect_generics_len` diagnostic as experimental

Cargo.toml
Fixes a panic within our panic handler leading to an abort
=> Bump salsa

crates/ide-completion/src/completions/expr.rs, crates/ide-completion/src/completions/keyword.rs
Improve the `let` and `letm` snippets
Make it work more like a postfix snippets
=> Improve the let code snippet

crates/hir-def/src/nameres/path_resolution.rs, crates/mbe/src/tests.rs
cc https://github.com/rust-lang/rust-analyzer/pull/19371
=> minor: Add a mbe test for parsing negative literals

crates/hir-expand/src/builtin/derive_macro.rs, crates/ide-assists/src/handlers/move_bounds.rs, crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs, crates/proc-macro-srv/src/server_impl/token_id.rs, crates/proc-macro-srv/src/server_impl/token_stream.rs, crates/proc-macro-srv/src/tests/mod.rs, crates/syntax/src/ast/edit_in_place.rs, crates/syntax/src/ast/make.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19681
=> fix: Fix `move_bounds` assists not working for lifetimes

crates/hir-def/src/db.rs, crates/hir-def/src/nameres/assoc.rs, crates/hir-def/src/resolver.rs, crates/hir-expand/src/lib.rs, crates/hir/src/semantics.rs, crates/hir/src/semantics/child_by_source.rs, crates/hir/src/source_analyzer.rs, crates/ide/src/expand_macro.rs, crates/rust-analyzer/src/cli/analysis_stats.rs
Closes (for the most part) https://github.com/rust-lang/rust-analyzer/issues/19873
=> fix: Fix IDE layer not resolving some macro calls

crates/hir/src/semantics.rs, crates/hir/src/semantics/child_by_source.rs, crates/hir/src/semantics/source_to_def.rs, crates/ide/src/expand_macro.rs
cc https://github.com/rust-lang/rust-analyzer/issues/19931
=> fix: Record macro calls in signatures in `ChildBySource` impls

crates/hir-ty/src/tests/incremental.rs
I think this is mostly what we want for testing the changes in https://github.com/rust-lang/rust-analyzer/pull/19837, as rebasing this commit atop of Chayim's changes causes the second assertion to fail.
=> hir-ty: test incremental trait solving

crates/hir-def/src/macro_expansion_tests/mod.rs, crates/hir-expand/src/proc_macro.rs, crates/load-cargo/src/lib.rs, crates/test-fixture/src/lib.rs
Comparing the TypeId is not enough, they also contain data.
=> fix: Fix comparison of proc macros

crates/rust-analyzer/src/test_runner.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/20030
=> Add --color=always to test explorer command

.github/workflows/ci.yaml, .github/workflows/release.yaml, crates/hir-ty/src/mir/eval.rs
We seem to panic analysis-stats on stable now because of a mir panic
=> ci: Fix up release workflow

crates/ide-assists/src/handlers/promote_local_to_const.rs
=> Migrate `promote_local_to_const` Assist to `SyntaxEditor`

crates/base-db/src/input.rs, crates/base-db/src/lib.rs, crates/hir-expand/src/lib.rs, crates/hir-expand/src/prettify_macro_expansion_.rs, crates/hir-expand/src/proc_macro.rs, crates/hir/src/diagnostics.rs, crates/ide-assists/src/handlers/expand_rest_pattern.rs, crates/ide-assists/src/utils.rs, crates/load-cargo/src/lib.rs, crates/project-model/src/workspace.rs, crates/rust-analyzer/src/reload.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/20130
=> Restructure proc-macro loading erros, differentiate hard error property on kind 

crates/hir-expand/src/name.rs, crates/hir-ty/src/db.rs, crates/hir-ty/src/variance.rs
=> Re-enable fixpoint iteration for variance computation

crates/project-model/src/build_dependencies.rs, crates/rust-analyzer/src/flycheck.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/19952
=> Improve flycheck and build script progress reporting

crates/ide-assists/src/handlers/generate_new.rs
Closes: https://github.com/rust-lang/rust-analyzer/issues/20071
I will generate `fn new` for tuple structs just like struct with named fields.
For tuple structs, I use the element index of tuple instead of a field name. 
```rs
struct S<T>(String, PhantomData<T>, u32);
impl<T> S<T> {
fn new(_0: String, _2: u32) -> Self {
Self(_0, PhantomData, _2)
}
}
```
```rs
struct S<T> {
text: String,
_marker: PhantomData<T>,
value: u32,
}
impl<T> S<T> {
fn new(text: String, value: u32) -> Self {
Self { text, _marker: PhantomData, value }
}
}
```
=> feat: Generate `new` for tuple struct

Cargo.toml
=> Update MSRV to 1.88.0

crates/ide-assists/src/handlers/convert_match_to_let_else.rs
=> Migrate `convert_match_to_let_else` assist to use `SyntaxEditor`

crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
rust-lang/rust-analyzer#20214
CC @Hmikihiro
=> minor: Revert "remove `if-let` chains"

crates/ide-assists/src/handlers/generate_impl.rs
=> Migrate `generate_impl` assist to use `SyntaxEditor`

Cargo.lock
Fallout from rust-lang/rust-analyzer#20233
=> minor: Update lockfile

crates/ide/src/folding_ranges.rs
sorry I forgot to remove unused var in https://github.com/rust-lang/rust-analyzer/pull/20054
=> minor: remove unused var

crates/ide-assists/src/handlers/generate_mut_trait_impl.rs
Assist in writing custom `DerefMut` implement
```rust
//- minicore: deref
struct Foo([i32; 16]);
impl core::ops::Deref$0 for Foo {
type Target = i32;
fn deref(&self) -> &Self::Target {
&self.0[0]
}
}
```
->
```rust
struct Foo([i32; 16]);
$0impl core::ops::DerefMut for Foo {
fn deref_mut(&mut self) -> &mut Self::Target {
&mut self.0[0]
}
}
impl core::ops::Deref for Foo {
type Target = i32;
fn deref(&self) -> &Self::Target {
&self.0[0]
}
}
```
=> Add Deref -> DerefMut for generate_mut_trait_impl

crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
=> Migrate `extract_expressions_from_format_string` assist to use `SyntaxEditor`

crates/ide/src/folding_ranges.rs
close https://github.com/rust-lang/rust-analyzer/issues/20240
=> fix fold doc comment for multiline param list fn

crates/project-model/src/build_dependencies.rs
Introduced in https://github.com/rust-lang/rust-analyzer/pull/20315 by accident
=> fix: Fix incorrect build script version check

crates/ide-assists/src/handlers/replace_named_generic_with_impl.rs
=> remove `ted` from replace_named_generic_with_impl.rs

crates/ide-completion/src/context/analysis.rs, crates/ide-completion/src/context/tests.rs
Fixes rust-lang/rust-analyzer#20361
=> Add assignment type analysis for ide-completion

crates/hir-ty/src/db.rs, xtask/src/metrics.rs
These shouldn't be recursive so
=> minor: Print fields of interned IDs in hir-ty instead of just the ID

crates/hir-ty/src/layout.rs, crates/hir-ty/src/next_solver/interner.rs, crates/hir-ty/src/tests.rs, crates/hir-ty/src/tests/opaque_types.rs
should fix the metrics issue for hyper, unless there's also another issue here :thinking:
=> next-solver fun time

crates/ide-db/src/symbol_index.rs
It seems it was forgotten in https://github.com/rust-lang/rust-analyzer/pull/20470.
=> Attach the DB in symbol queries

crates/ide/src/lib.rs
=> Attach the DB when mapping the result of `world_symbols()`

crates/ide-diagnostics/src/handlers/unresolved_field.rs
Examples
---
```rust
mod indent {
struct Foo {}
fn foo() {
let foo = Foo{};
foo.bar$0;
}
}
```
```rust
mod indent {
struct Foo {        bar: ()
}
fn foo() {
let foo = Foo{};
foo.bar;
}
}
```
```rust
mod indent {
struct Foo {
bar: ()
}
fn foo() {
let foo = Foo{};
foo.bar;
}
}
```
---
New field list add newline
```rust
mod indent {
struct Foo;
fn foo() {
Foo.bar$0;
}
}
```
```rust
mod indent {
struct Foo{ bar: () }
fn foo() {
Foo.bar;
}
}
```
```rust
mod indent {
struct Foo {
bar: (),
}
fn foo() {
Foo.bar;
}
}
```
=> Fix indent for unresolved_field fixes

crates/hir-ty/src/tests/regression/new_solver.rs, crates/test-utils/src/minicore.rs
That were fixed by the migration.
Start the cleanup!
Fixes https://github.com/rust-lang/rust-analyzer/issues/19971, fixes https://github.com/rust-lang/rust-analyzer/issues/20365, fixes https://github.com/rust-lang/rust-analyzer/issues/19752.
=> minor: Add regression tests to some S-blocked-on-new-solver issues

crates/hir-ty/src/next_solver/consts.rs, crates/hir-ty/src/next_solver/predicate.rs, crates/hir-ty/src/next_solver/ty.rs
=> minor: Set `WithCachedTypeInfo::stable_hash` when in-tree

crates/ide-assists/src/handlers/extract_variable.rs
Example
---
```rust
fn main() {
if $0let$0 Some(x) = Some(2+2) {}
}
```
```rust
fn main() {
let $0var_name = let Some(x) = Some(2+2);
if var_name {}
}
```
```rust
fn main() {
let $0var_name = Some(2+2);
if let Some(x) = var_name {}
}
```
=> Fix extract_variable on LetExpr

crates/ide-assists/src/handlers/remove_dbg.rs
`remove_dbg` not applicable for whitespaces after trailing comma
Example
---
```rust
fn foo() {
dbg!(
bar(),
);
}
```
Assist not applicable
```rust
fn foo() {
bar();
}
```
=> Fix not applicable on trailing comma for remove_dbg

crates/hir-ty/src/tests/regression/new_solver.rs
Closes rust-lang/rust-analyzer#19637.
=> minor: Another regression test for next solver fixed bug
