- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/extract_function.rs
This change attempts to resolve issue #7636: Extract into Function does not
create a generic function with constraints when extracting generic code.
In `FunctionBody::analyze_container`, we now traverse the `ancestors` in search
of `AnyHasGenericParams`, and attach any `GenericParamList`s and `WhereClause`s
we find to the `ContainerInfo`.
Later, in `format_function`, we collect all the `GenericParam`s and
`WherePred`s from the container, and filter them to keep only types matching
`TypeParam`s used within the newly extracted function body or param list. We
can then include the new `GenericParamList` and `WhereClause` in the new
function definition.
This change only impacts `TypeParam`s. `LifetimeParam`s and `ConstParam`s are
out of scope for this change.
I've never contributed to this …
> fix: Support generics in extract_function assist

- .github/workflows/ci.yaml
- .github/workflows/metrics.yaml
- .github/workflows/publish.yml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
https://old.reddit.com/r/rust/comments/vyx4oj/actionsrs_organization_became_unmaintained/
Looking at this holistically, I don't fully understand *why* we need an
action here? Seems like we can just use rustup? nowadays github runners
come with rustup pre-installed.
> Remove deprecate action

- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/tests/special.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_crate_root.html
- crates/ide/src/syntax_highlighting/test_data/highlight_general.html
- crates/ide/src/syntax_highlighting/test_data/highlight_keywords.html
Fixes https://github.com/rust-lang/rust-analyzer/issues/12703
> fix: Don't show qualified path completions for private items

- .github/workflows/ci.yaml
- .github/workflows/metrics.yaml
- .github/workflows/publish.yml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
It seems like it may be related to self-update? Anyways, I think we
should be disabling self-update on CI
> try fixing spurious CI failures on windows

- crates/hir-expand/src/db.rs
- crates/hir-expand/src/fixup.rs
- crates/mbe/src/syntax_bridge.rs
- allow appending tokens after a token, not just a node
- allow inserting delimiters (and remove them again)
- fix up `if {}` and `if` without anything following
> fix: Improve syntax fixup a bit, handle incomplete `if`

- crates/ide-db/src/rename.rs
- crates/ide/src/rename.rs
close #12684 . I just ignore renames for crate root in `rename_mod` func.
> fix: ignore renames for crate root

- crates/ide-assists/src/handlers/generate_new.rs
- crates/ide-db/src/lib.rs
- crates/ide-db/src/use_trivial_contructor.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
As proposed in #12535 this PR changes the "Generate new" and "Fill struct fields" assist/diagnostic to instanciate structs with no fields and enums with a single empty variant.
For example:
```rust
pub enum Bar {
Bar {},
}
struct Foo<T> {
a: usize,
bar: Bar,
_phantom: std::marker::PhantomData<T>,
}
impl<T> Foo<T> {
/* generate new */
fn random() -> Self {
Self { /* Fill struct fields */ }
}
}
```
was previously:
```rust
impl<T> Foo<T> {
fn new(a: usize, bar: Bar, _phantom: std::marker::PhantomData<T>) -> Self {
Self { a, bar, _phantom }
}
fn random() -> Self {
Self {
a: todo!(),
bar: todo!(),
_phantom: todo!(),
}
}
}
```
and is now:
```rust
impl<T> Foo<T> {
fn new(a: usize) -> Self {
Self {
a,
bar: Bar::Bar {},
_phantom: std::marker::PhantomData
}
}
fn random() -> Self {
Self {
a: …
```
> Automatically instaciate trivially instaciable structs in "Generate new" and "Fill struct fields"

- crates/hir-def/src/child_by_source.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/resolver.rs
- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_macros.html
- crates/ide/src/syntax_highlighting/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12100
Doesn't resolve the shadowing issues though, fixing those is gonna be really tricky I believe unless we can come up with a nice scheme to "order" item tree items (using syntax ranges and file ids would be a pain and also a bad idea since that'll require us to potentially reparse files in collection).
> internal: Record all macro definitions in ItemScope

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
- crates/ide-completion/src/completions/dot.rs
This fixes `generic_predicates_for_param_query` comparing local IDs that belong to different definitions.
As the query is used in multiple places this fix affects various r-a features when an associated type shorthand and `impl Trait` involved. Notably inference, goto, completion, hover.
Fixes #12484
> fix: Stack overflows and wrong type inference of associated type shorthands

- crates/hir-def/src/type_ref.rs
Sorry, but I missed these from #12778 @flodiebold
> fix: un-inline `ConstScalarOrPath::from_expr_opt`

- crates/ide-assists/src/handlers/generate_constant.rs
fix #12022 
add abilities to generate constant with prefix path, even these mods in path are not exist.
https://user-images.githubusercontent.com/10148927/168710096-59d5c594-0e4a-4ba7-bfb3-21c4b99409ea.mov
https://user-images.githubusercontent.com/10148927/168710111-cd6d3df4-58eb-4358-ae9e-791bfc408efa.mov
https://user-images.githubusercontent.com/10148927/168710115-601923b7-2164-4b9a-85a9-fbb4b29796a1.mov
https://user-images.githubusercontent.com/10148927/168710118-3d4bc9c1-758b-4e6f-9709-568fa920937d.mov
> fix: “Generate constant” ignores the path prefix of the identifier

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- editors/code/package.json
Fixes https://github.com/rust-lang/rust-analyzer/issues/12794
Also renames "notify" to "server", since that's clearer ("notify" is still accepted for compatibility).
> fix: make file watcher config a drop-down (and clarify the options)

- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/to_proto.rs
Supercedes https://github.com/rust-lang/rust-analyzer/pull/9891, this doesn't yet fix the linked issue since there is a lot of fancy things we can do there now.
This doesn't yet really implement anything new, it just adds the scaffolding for the protocol conversion
> Add simple support for completion item details

- crates/ide-diagnostics/src/handlers/type_mismatch.rs
`ToString` is implemented by many different types than `&str`, and represents a serialization into string data. The fact that said data is returned as owned, is an implementation detail resulting from the lack of a parameter for a pre-allocated buffer.
If merely copying borrowed string data to owned string data is all that is desired, `ToOwned` is a much better choice, because if the user later refactors the code such that the input is no longer an `&str`, then they will get a compiler error instead of a mysterious runtime-behavioral change.
> chore: change str_ref_to_string to str_ref_to_owned

- .cargo/config.toml
- Cargo.lock
- crates/cfg/Cargo.toml
- crates/hir-def/Cargo.toml
- crates/hir-expand/Cargo.toml
- crates/hir-ty/Cargo.toml
- crates/ide-assists/Cargo.toml
- crates/ide-completion/Cargo.toml
- crates/ide-db/Cargo.toml
- crates/ide-diagnostics/Cargo.toml
- crates/ide-ssr/Cargo.toml
- crates/ide/Cargo.toml
- crates/parser/Cargo.toml
- crates/proc-macro-srv/Cargo.toml
- crates/project-model/Cargo.toml
- crates/rust-analyzer/Cargo.toml
- crates/syntax/Cargo.toml
This should make ra's test suite runnable from within `rust-analyzer/rust`.
@cuviper ran into that when trying to run RA tests from rust CI: https://github.com/rust-lang/rust/pull/99444#issuecomment-1188844202
> Upgrade to expect-test@1.4.0, add CARGO_WORKSPACE_DIR env var

- crates/ide-assists/src/handlers/remove_unused_param.rs
Instead of calling `builder.delete` for every text range we find with
`process_usage`, we now ensure that the ranges do not overlap before removing
them. If a range is fully contained by a prior one, it is dropped.
fixes #12784
> fix: Prevent panic in Remove Unused Parameter assist

- crates/ide-completion/src/render.rs
part of https://github.com/rust-lang/rust-analyzer/issues/12717
> Find original as node before compute ref match

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
- crates/test-utils/src/minicore.rs
Fixes #12779 
For the `Generate default members` assist on the `PartialEq` trait, the assist will now give the default implementation instead of generating a function.
> fix: Correctly generate default `PartialEq::ne`

- crates/ide-assists/src/handlers/extract_module.rs
Fixes #12790 
Original behavior was to insert `pub(crate)` at the `first_child_or_token`, which for an item with a comment or attribute macro, would put the visibility marker before the comment or macro, instead of after.
This merge request alters the call to find the node with appropriate `SyntaxKind` in the `children_or_tokens`. It also adds a test case to the module to verify the behavior. Test case verifies function, module, records, enum, impl, trait, and type cases.
> fix: Insert `pub(crate)` after doc comments and attribute macros

- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/completions/postfix/format_like.rs
- crates/ide-completion/src/snippet.rs
This PR fixes #11897 by escaping '\\' and '$' in the text of the receiver position expression. See [here](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#snippet_syntax) for the specification of the snippet syntax (especially [this section](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#grammar) discusses escaping).
Although not all occurrences of '\\' and '$' have to be replaced, I chose to replace all as that's simpler and easier to understand. There *are* more clever ways to implement it, but I thought they were premature optimization for the time being (maybe I should put FIXME notes?).
> fix: escape receiver texts in completion

- crates/hir-ty/src/tests/traits.rs
- crates/proc-macro-srv/src/abis/abi_1_58/mod.rs
- crates/proc-macro-srv/src/abis/abi_1_58/ra_server.rs
- crates/proc-macro-srv/src/abis/abi_1_63/mod.rs
- crates/proc-macro-srv/src/abis/abi_1_63/ra_server.rs
- crates/proc-macro-srv/src/abis/abi_1_64/mod.rs
- crates/proc-macro-srv/src/abis/abi_1_64/ra_server.rs
Related to:
This is mostly a courtesy PR for the sake of rustc maintainers. When they looked at `proc-macro-srv`, they noticed the server was named `Rustc` — probably because of historical copy-paste. Only rustc's proc macro server should be named `Rustc`, ra's can be named `RustAnalyzer`.
Maintainer impact: There's no semantic changes in this PR, only naming. One test snapshot was updated since "proc macro server types" were used to test traits somewhere else and I renamed those too, why not.
> Rename proc macro server from 'Rustc' to 'RustAnalyzer'

- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/tests/slow-tests/tidy.rs
Due to the way "git subtree" works, the `check_merge_commits` test _will_ find merge commits and fail, so we simply skip it.
This changed is tracked in:
Maintainer impact: none
> Remove `check_merge_commits` test

- crates/proc-macro-test/build.rs
Building it in-place fails in rust CI because the source directory is read-only. This changes `proc-macro-test`'s build script to first
copy `imp` under `OUT_DIR` (which is read-write).
It also prints stdout/stderr for the nested cargo invocation, should it fail. (I've seen failures in rust CI that I couldn't explain, and
when they take 25 minutes to reproduce, you want to have that info)
This change is tracked in:
Maintainer impact: none.
> Build proc-macro-test-impl out-of-tree

- crates/proc-macro-srv/src/tests/mod.rs
- crates/proc-macro-test/imp/src/lib.rs
This exercises some of the upcoming proc_macro bridge changes. It should also pass for all supported ABIs, with the older-style bridge.
This changed is tracked in:
> Add proc-macro-srv integration test that clones literals

- crates/proc-macro-test/build.rs
This allows overriding the toolchain used to run `proc-macro-srv` tests.
---
Sample usage.
Testing the current ABI (variable unset/empty):
```shell
amos@tails ~/bearcove/rust-analyzer/crates/proc-macro-srv proc-macro-test-toolchain*
❯ PROC_MACRO_TEST_TOOLCHAIN="" cargo test --quiet
running 16 tests
................
test result: ok. 16 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```
Testing an older ABI:
```shell
amos@tails ~/bearcove/rust-analyzer/crates/proc-macro-srv proc-macro-test-toolchain*
❯ PROC_MACRO_TEST_TOOLCHAIN="1.58" cargo test --quiet
running 16 tests
................
test result: ok. 16 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s
```
Testing current nightly ABI:
```shell
❯ rustc +nightly --version
rustc …
```
> Add PROC_MACRO_TEST_TOOLCHAIN environment variable

- crates/hir-ty/src/db.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/method_resolution.rs
Fixes the inlay hint performance regression introdcuced by https://github.com/rust-analyzer/rust-analyzer/issues/12549
> fix: Fix `trait_impls_in_deps_query` being called directly instead of as a query

- Cargo.lock
- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-api/src/version.rs
- crates/proc-macro-srv/Cargo.toml
- crates/proc-macro-srv/build.rs
- crates/proc-macro-srv/src/abis/abi_sysroot/mod.rs
- crates/proc-macro-srv/src/abis/abi_sysroot/ra_server.rs
- crates/proc-macro-srv/src/abis/abi_sysroot/ra_server/symbol.rs
- crates/proc-macro-srv/src/abis/abi_sysroot/ra_server/token_stream.rs
- crates/proc-macro-srv/src/abis/mod.rs
- crates/proc-macro-srv/src/dylib.rs
- crates/proc-macro-srv/src/lib.rs
- crates/proc-macro-srv/src/tests/mod.rs
- crates/proc-macro-test/imp/src/lib.rs
- crates/rust-analyzer/Cargo.toml
Still a WIP.
This change is tracked by:
> Introduce proc-macro-srv/sysroot-abi

- crates/hir/src/semantics.rs
- crates/ide/src/syntax_highlighting.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12842
> fix: Improve syntax highlighting in attributes

- crates/hir-def/src/adt.rs
- crates/hir-def/src/attr.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
Less parsing = very good, should speed up lang item collection as that basically probes attributes of all enum variants which currently triggers parsing
Not fond of how this is searching for the correct index, ideally we'd map between HIR and item tree Id here but I am not sure how, storing the item tree ids in the HIR version doesn't work due to the usage of `Trace`...
> internal: Use ItemTree for variant, field and module attribute collection in attrs_query

- crates/ide-assists/src/handlers/generate_new.rs
Looks like this got copied from `generate_impl` without adjusting the description.
> fix generate_new doc

- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
fixes #12823
Is this what you were thinking of here, @Veykril ? I haven't done any work on completions before, so I could definitely be misunderstanding the issue.
> fix: Don't add braces to 'if' completion in match guard position

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
cc #12779, #12821
addresses https://github.com/rust-lang/rust-analyzer/pull/12821#issuecomment-1190157506
`gen_trait_fn_body()` only attempts to implement required trait member functions, so we shouldn't call it for `Implement default members` assist.
This patch also documents the precondition of `gen_trait_fn_body()` and inserts `debug_assert!`, but I'm not entirely sure if the assertions are appropriate.
> fix: don't replace default members' body

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/expr.rs
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/infer/expr.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
Fixes #12838 
When checking if the record literal in question is an assignee expression or not, the new fn `is_assignee_record_literal` iterates over its ancestors until it is sure. This isn't super efficient, as we don't cache anything and does the iteration for every record literal during missing fields check. Alternatively, we may want to have a field like `assignee` on `hir_def::Expr::{RecordLit, Array, Tuple, Call}` to tell if it's an assignee expression, which would be O(1) when checking later but have some memory overhead for the field.
> Fix missing fields check on destructuring assignment

- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/reload.rs
cc https://github.com/rust-lang/rust-analyzer/issues/12855
The idea is to have each server be spawned with the appropriate toolchain, that way workspaces with differing toolchains shouldn't suffer from proc-macro abi mismatches.
> feat: Spawn a proc-macro-srv instance per workspace

- Cargo.lock
- crates/proc-macro-api/src/process.rs
- crates/proc-macro-srv-cli/Cargo.toml
- crates/proc-macro-srv-cli/src/main.rs
- crates/project-model/src/project_json.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/reload.rs
This adds a `bin` crate which simply runs `proc_macro_srv::cli::run()` (it does no CLI argument parsing, nothing).
The intent is to build that crate in Rust CI as part of the `dist::Rustc` component, then ship it in the sysroot: it would probably land in something like `~/.rustup/toolchains/nightly-2022-07-23-x86_64-unknown-linux-gnu/libexec/proc-macro-srv-cli`.
This makes https://github.com/rust-lang/rustup/pull/3022 less pressing. (Instead of teaching RA about rustup components, we simply teach it to look in the sysroot via `rustc --print sysroot`. If it can't find `proc-macro-srv-cli`, it falls back to its own `proc-macro` subcommand).
This is closely related to https://github.com/rust-lang/rust-analyzer/issues/12803 (but doesn't close it yet).
Things to address now:
Things to address …
> Add `rust-analyzer-proc-macro-srv` binary, use it if found in sysroot

- crates/hir-def/src/data.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/resolver.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-completion/src/item.rs
- crates/ide-db/src/defs.rs
- crates/ide-db/src/lib.rs
- crates/ide-db/src/path_transform.rs
- crates/ide-db/src/rename.rs
- crates/ide-db/src/search.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/navigation_target.rs
- crates/ide/src/signature_help.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/inject.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
Also downmaps tokens inside deriver helpers to the derive expansion
This does not handle the case where multiple derives make use of the same helper name though, unsure how to tackle that yet.
Partially addresses https://github.com/rust-lang/rust-analyzer/issues/10935
> feat: Resolve derive helper attributes in IDE layer

- crates/rust-analyzer/src/reload.rs
I forgot that executables end with `.exe` on Windows in:
* https://github.com/rust-lang/rust-analyzer/pull/12858
> Find standalone proc-macro-srv on windows too

- crates/ide-assists/src/handlers/inline_call.rs
(partially) fixes #12860.
This PR (only) addresses the whitespace issue when inlining functions defined in macros.
Additionally, the indentation/spacing is not ideal, but works, e.g.
```rs
macro_rules! define_function {
() => { fn test_function_macro() {
if let Some(3) = 3i32.checked_add(0) {
println!("3 + 0 == 3");
}
} };
}
define_function!();
fn main() {
test_function_macro();
}
// previously became
// ...
fn main() {
ifletSome(3)=3i32.checked_add(0){println!("3 + 0 == 3");};
}
// now becomes
// ...
fn main() {
if let Some(3) = 3i32.checked_add(0){
println!("3 + 0 == 3");
};
}
```
The `self` -> `this` problem[^this] is (probably?) a separate problem that I am also looking into.
[^this]: As mentioned in [my comment on the above issue](https://github.com/rust-lang/rust-analyzer/issues/1286 …
> fix: Insert spaces when inlining a function defined in a macro.

- crates/hir-ty/src/chalk_ext.rs
- crates/hir/src/lib.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/context/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/8357
> fix: Honor ref expressions for compute_ref_match completions

- crates/ide-completion/src/render/function.rs
ref https://github.com/rust-lang/rust-analyzer/issues/12717
> Find original ast node before compute ref match

- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
- crates/syntax/src/tests/sourcegen_ast.rs
cc https://github.com/rust-lang/rust-analyzer/pull/12880#issuecomment-1195567103
It sounds good on paper, so let's try it
> internal: Assume condition/iterable is missing if there is only a BlockExpr

- crates/proc-macro-srv/src/lib.rs
I have verified that this fixes #12884 for me.
Hat tip to @bjorn3 for identifying the cause of the issue.
> Use large stack on expander thread

- crates/hir/src/semantics.rs
- crates/ide-completion/src/completions/attribute.rs
- crates/ide-completion/src/completions/attribute/derive.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/completions/item_list.rs
- crates/ide-completion/src/completions/pattern.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/completions/use_.rs
- crates/ide-completion/src/completions/vis.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/special.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12892
> fix: Calculate completions after type anchors

- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/context/analysis.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12566
Not too happy with the duplication needed for this, but it is what it is. Completions in path qualifiers will have to be filtered properly still, but its better to show too many completions for this than too few for now.
> fix: Do completions in path qualifier position

- .github/workflows/publish.yml
> publish: Use cargo ws rename to rename crates

- crates/ide-completion/src/tests.rs
We return every built-in type here, but only have `u32` in the tests, so let's look for that one to make tests more reliable across platforms.
> internal: Be more explicit when filtering built-in completions

- crates/hir-def/src/attr.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/inject.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_module_docs_inline.html
- crates/ide/src/syntax_highlighting/test_data/highlight_module_docs_outline.html
- crates/ide/src/syntax_highlighting/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12912
> fix: Fix ast-id up when merging raw attributes

- docs/dev/README.md
- xtask/src/release.rs
Update `xtask` for the subtree workflow. This doesn't explain how to do a `rust -> RA`  sync, since that's definitely more involved, but will probably only happen rarely.
> internal: Update `xtask promote` and release instructions

- crates/ide/src/runnables.rs
When rustdoc runs doctests, it removes whitespaces from the tests' path ([code](https://github.com/rust-lang/rust/blob/25bb1c13bd472b75ceebee3b8dcf4dcbc431a8be/src/librustdoc/doctest.rs#L951)). See https://github.com/rust-lang/rust/pull/89422 for details.
Interestingly enough, "Run doctest" has been working without much problem even though rust-analyzer hasn't followed the change. This is because cargo passes the test name to rustdoc via `--test-args` option, and then rustdoc [splits it by whitespace](https://github.com/rust-lang/rust/blob/25bb1c13bd472b75ceebee3b8dcf4dcbc431a8be/src/librustdoc/config.rs#L513-L514); the last element of the split test name **always** matches the test name that rustdoc generates.
However, it may run other tests unexpectedly (to be precise, this has long …
> fix: remove whitespaces from doctest names

- .github/ISSUE_TEMPLATE/bug_report.md
- README.md
- crates/hir-def/src/item_tree.rs
- crates/ide-db/src/apply_change.rs
- crates/ide-ssr/src/lib.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/join_lines.rs
- crates/ide/src/matching_brace.rs
- crates/ide/src/move_item.rs
- crates/ide/src/parent_module.rs
- crates/ide/src/runnables.rs
- crates/ide/src/shuffle_crate_graph.rs
- crates/ide/src/status.rs
- crates/ide/src/syntax_tree.rs
- crates/ide/src/view_crate_graph.rs
- crates/ide/src/view_hir.rs
- crates/ide/src/view_item_tree.rs
- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-srv/src/abis/mod.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/syntax/src/lib.rs
- docs/dev/README.md
- docs/dev/architecture.md
- docs/dev/guide.md
- docs/user/manual.adoc
- editors/code/package.json
User-facing change: All commands are now rendered as "rust-analyzer: Command" rather than "Rust Analyzer: Command".
Alternative to https://github.com/rust-lang/rust-analyzer/pull/12910
Potentially controversial, since other extensions don't do this, so I won't self-approve.
> fix: Fix r-a spelling in some places

- crates/hir-expand/src/fixup.rs
Part of https://github.com/rust-lang/rust-analyzer/issues/12777
This is a first iteration to gather some feedback. In particular I'm not sure if the curly braces should be added here, but I couldn't get the test to work without them. Any hints welcome!
> Add syntax fixup for while loops

- crates/ide-assists/src/handlers/generate_enum_variant.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
This change adds support for associated values to the "Generate Enum Variant" assist.
I've split the implementation out into 4 steps to make code review easier:
- Add "add_variant" support to the structural ast editing system in `edit_in_place`
- Migrate `generate_enum_variant` to use structural ast editing instead of string manipulation
- Support tuple fields
- Support record fields
Please let me know if I should leave the commits as-is, or squash before merging.
Fixes #12797
> feat: support associated values in "Generate Enum Variant" assist

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/main.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/12928
> Add a setting to disable comment continuation in VSCode

- crates/flycheck/src/lib.rs
- crates/paths/src/lib.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
Supercedes https://github.com/rust-lang/rust-analyzer/pull/11038
There is still the problem that all the diagnostics are cleared, only clearing diagnostics of the relevant workspace isn't easily doable though I think, will have to dig into that
> feat: Only flycheck workspace that belongs to saved file

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
- crates/vfs-notify/src/lib.rs
When r-a starts up, it starts switching the workspace before all vfs
events have been processed which causes us to switch workspace multiple
times until all vfs changes have been processed. This scales with the
size of the project and its dependencies. If workspace files from
dependencies as well as the sysroot get loaded, we shouldn't switch
the workspace as those have no impact on the project workspace.
> Don't switch workspace on vfs file changes from libraries

- lib/la-arena/src/lib.rs
- lib/la-arena/src/map.rs
`la-arena` on crates.io is quite helpful when just a thin wrapper for Vec with u32 indices is needed.
But the current API is not ergonomic enough.
This PR
- Adds `ArenaMap::new`. Not sure why only `Arena` has it now.
- Adds `Arena{,Map}::with_capacity` for known-size storage.
- Adds entry-API for `ArenaMap` for easier `.entry(idx).or_default().push(value)` or `.entry(idx).or_insert(...)` operations.
> Add more constructors and entry-APIs for la-arena

- crates/rust-analyzer/tests/slow-tests/tidy.rs
- crates/sourcegen/src/lib.rs
`cargo test -p ide-assists` fails on Windows/x64/nightly:
```shell
> rustup self update
info: checking for self-updates
rustup unchanged - 1.25.1
> rustup update
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
info: checking for self-updates
stable-x86_64-pc-windows-msvc unchanged - rustc 1.62.1 (e092d0b6b 2022-07-16)
nightly-x86_64-pc-windows-msvc unchanged - rustc 1.64.0-nightly (affe0d3a0 2022-08-05)
info: cleaning up downloads & tmp directories
> rustup show
Default host: x86_64-pc-windows-msvc
rustup home:  C:\Users\stanc\.rustup
installed toolchains
--------------------
stable-x86_64-pc-windows-msvc
nightly-x86_64-pc-windows-msvc (default)
active toolchain
---------------- …
```
> Run stable `fmt` & `cargo` through `rustup`

- crates/hir-def/src/generics.rs
- crates/hir-def/src/visibility.rs
- crates/hir-ty/src/lower.rs
- lib/la-arena/src/map.rs
Continue of #12931. Seems that I forgot some methods in the previous PR :(
I also changed `ArenaMap::insert` to return the old value, to match the map-like collection API of std. **So this is a breaking change.**
r? @lnicola
> More methods and traits for `la_arena::ArenaMap`

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-expand/src/quote.rs
Fixes #12921
- I avoided making `unquote_str()` take char literals as well because it's depended on by another function `parse_string()` that's only supposed to take strings.
- Even with this patch, we don't output `\0` as `\u{0}` which #12921 pointed out ~~, but we're not actually responsible for serializing it but rowan is~~. They are functionally equivalent and I don't think it'd cause any confusion, but we *could* try escaping them before serialization (for reference, `rustc -Zunpretty=expanded`, which `cargo expand` uses under the hood, [makes use of `str::escape_default()`](https://github.com/rust-lang/rust/blob/3830ecaa8db798d2727cbdfa4ddf314ff938f268/compiler/rustc_ast/src/util/literal.rs#L161).
> fix: make `concat!` work with char

- crates/hir-expand/src/fixup.rs
Partially implements https://github.com/rust-lang/rust-analyzer/issues/12777. 
Added support for for loops and match statements.
I couldn't do paths like `crate::foo::` as I wasn't able to add `SyntheticTokens` to the end of `foo::`, they always ended up after `crate::`
This is my first contribution so please don't be shy about letting me know if I've done anything wrong!
> Add fixups for incomplete in proc-macros

- Cargo.lock
- crates/hir/src/diagnostics.rs
- crates/ide-assists/src/assist_context.rs
- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ide-assists/src/handlers/generate_deref.rs
- crates/ide-assists/src/handlers/introduce_named_lifetime.rs
- crates/ide-assists/src/handlers/remove_unused_param.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/utils.rs
- crates/ide-db/src/source_change.rs
- crates/ide-diagnostics/Cargo.toml
- crates/ide-diagnostics/src/handlers/inactive_code.rs
- crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
- crates/ide-diagnostics/src/handlers/macro_error.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide-diagnostics/src/tests.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/config.rs
fix #10118
Should this be a diagnostic? I made it a diagnostic because of issue label.
> Generate rust type from json

- crates/syntax/src/ast/operators.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12971 where `Display` impl for assignment operators does `=+` instead of `+=`
> Corrected order of printing op and `=`

- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/tests/patterns.rs
Fixes #12630
c.f. [rustc_typeck](https://github.com/rust-lang/rust/blob/1603a70f82240ba2d27f72f964e36614d7620ad3/compiler/rustc_typeck/src/check/pat.rs#L388-L404)
> fix: infer byte string pattern as `&[u8]` when matched against slices

- crates/project-model/src/build_scripts.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/reload.rs
See https://github.com/rust-lang/rust-analyzer/issues/12973#issuecomment-1209159426
> Use `--keep-going` cargo flag when building build scripts

- crates/hir-def/src/nameres/mod_resolution.rs
- crates/hir-def/src/nameres/tests/mod_resolution.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-expand/src/name.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/const_.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-completion/src/render/literal.rs
- crates/ide-completion/src/render/macro_.rs
- crates/ide-completion/src/render/pattern.rs
- crates/ide-completion/src/render/type_alias.rs
- crates/ide-completion/src/render/union_literal.rs
- crates/ide-completion/src/render/variant.rs
- crates/ide/src/runnables.rs
Resolves #12787 
Resolves rust-lang/rust#99361
This PR effectively swaps `Name` and `EscapedName` in hir. In other words, it makes `Name` hold and print escaped raw identifiers and introduces another struct `UnescapedName` for cases where you need to print names without "r#" prefix.
My rationale is that it makes it easier for us to format an escaped name into string, which is what we want when we serialize names in general. This is because we format a name into string usually when we are presenting it to the users and arguably they expect its escaped form as that's what they see and write in the source code.
I split the change for `Name` into 3 commits to make it easier to follow but it also made some tests fail in the intermediate commits. I can squash them into a commit after the review …
> Make `Name` hold escaped name

- crates/rust-analyzer/src/bin/rustc_wrapper.rs
rust-analyzer's RUSTC_WRAPPER unconditionally succeeds `cargo check`
invocations tripping up build scripts using `cargo check` to probe for
successful compilations. To prevent this from happening the RUSTC_WRAPPER
now checks if it's run from a build script by looking for the
`CARGO_CFG_TARGET_ARCH` env var that cargo sets only when running build
scripts.
> Do not unconditionally succeed RUSTC_WRAPPER checks when run by build scripts

- editors/code/src/client.ts
Follw up to https://github.com/rust-lang/rust-analyzer/pull/13016
> Pad empty diagnostic messages in relatedInformation as well

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/builtin_type.rs
- crates/hir-def/src/expr.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/item_tree/tests.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/pretty.rs
- crates/hir-def/src/type_ref.rs
- crates/hir/src/lib.rs
- crates/ide/src/view_hir.rs
- editors/code/src/commands.ts
This improves the "View HIR" command by pretty-printing the HIR to make it much more readable.
Example function:
```rust
fn newline(&mut self) {
match self.buf.chars().rev().skip_while(|ch| *ch == ' ').next() {
Some('\n') | None => {}
_ => writeln!(self).unwrap(),
}
}
```
Previous output:
```
HIR expressions in the body of `newline`:
Idx::<Expr>(0): Path(Path { type_anchor: None, mod_path: ModPath { kind: Super(0), segments: [] }, generic_args: [] })
Idx::<Expr>(1): Field { expr: Idx::<Expr>(0), name: Name(Text("buf")) }
Idx::<Expr>(2): MethodCall { receiver: Idx::<Expr>(1), method_name: Name(Text("chars")), args: [], generic_args: None }
Idx::<Expr>(3): MethodCall { receiver: Idx::<Expr>(2), method_name: Name(Text("rev")), args: [], generic_args: None }
Idx::<Expr>(4): Path(Path { …
```
> internal: Add an HIR pretty-printer

- crates/hir-def/src/body/lower.rs
- crates/hir-ty/src/tests/regression.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12940
This is a bit of a hack, ideally `MacroStmts` would not exist at all after HIR lowering, but that requires changing how the lowering code works.
> fix: Fix incorrect type mismatch with `cfg_if!` and other macros in expression position

- crates/ide-completion/src/completions/record.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/literal.rs
- crates/ide-completion/src/render/pattern.rs
- crates/ide-completion/src/render/union_literal.rs
- crates/ide-completion/src/render/variant.rs
- crates/ide-completion/src/tests/pattern.rs
> fix: record completion filtering

- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This adds `rust-analyzer.hover.documentation.keywords.enable`, which defaults to `true` and can be turned off to disable the keyword documentation hover popups, which can be somewhat distracting when triggered by accident, and offer relatively little value if you're already familiar with the language.
Fixes https://github.com/rust-lang/rust-analyzer/issues/12950
> feat: Add a setting for keyword hover popups

- crates/rust-analyzer/src/global_state.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/13029
> Revert #12947, trigger workspace switches on all structure changes again

- crates/hir-expand/src/name.rs
- crates/ide-db/src/search.rs
Fixes #13030 
There are keywords in Rust 2018+ that you can use as names without escaping when your crate is in Rust 2015 e.g. "try". We need to be consistent on how to keep track of the names regardless of how they are actually written in each crate. This patch attempts at it by taking such names into account and storing them uniformly in their escaped form.
> fix: escape keywords used as names in earlier editions

- crates/flycheck/src/lib.rs
- crates/hir-def/src/nameres/proc_macro.rs
- crates/hir-expand/src/lib.rs
- crates/ide-assists/src/handlers/extract_module.rs
- crates/ide-assists/src/handlers/replace_turbofish_with_explicit_type.rs
- crates/ide-assists/src/utils/suggest_name.rs
- crates/ide-completion/src/completions/postfix/format_like.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/rename.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
- crates/mbe/src/expander/matcher.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/bin/logger.rs
- crates/syntax/src/hacks.rs
- crates/vfs/src/lib.rs
- docs/dev/architecture.md
- editors/code/src/commands.ts
- editors/code/src/toolchain.ts
This PR will fix some typos detected by [typos].
There are also some other typos in the function names, variable names, and file
names, which I leave as they are. I'm more certain that typos in comments
should be fixed.
[typos]: https://github.com/crate-ci/typos
> fix: a bunch of typos

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
Fixes #13031
We've been dropping the associated type bindings of trait object types that were written without the `dyn` keyword. This patch reuses the lowering logic for `TypeRef::DynTrait` so the associated type bindings are properly lowered.
> fix: resolve associated types of bare dyn types

- crates/rust-analyzer/src/handlers.rs
The "Run" feature of rust-analyzer is super useful, especially for running
individual tests or test-modules during development.
One common pattern in rust development is to develop tests in the same file as
production code, inside a module (usually called `test` or `tests`) marked with
`#[cfg(test)]`.  Unforunately, this pattern is not well supported by r-a today,
as a test module won't show up as a runnable unless the cursor is inside it.
In my experience, it is quite common to want to run the tests associated with
some production code immediately after editing it, not only after editing the
tests themselves. As such it would be better if test modules were available
from the "Run" menu even when the cursor is outside the test module.
This change updates the filtration logic for runnables …
> feat: Run test mod from anywhere in parent file

- crates/ide-assists/src/handlers/inline_type_alias.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
`inline_type_alias_uses` assist tries to inline all selected type alias occurrences.
Type alias used in `PathType` position are inlined.
- Removing type alias declaration if all uses are inlined.
- Removing redundant imports after inlining all uses in the file.
- Type alias not in `PathType` position, such as:
- `A::new()`
- `let x = A {}`
- `let bits = A::BITS`
- etc.
Partially fixes #10881
> feat: Add an assist for inlining all type alias uses

- editors/code/src/config.ts
I was debugging an unrelated issue in rust-analyzer, but came across this unused code and figured that it's fine to send a fully red PR :)
> chore: remove unused `currentExtensionIsNightly()` in `config.ts`

- crates/flycheck/src/lib.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/4828
> Implement lsp extension for cancelling running flychecks

- crates/rust-analyzer/src/handlers.rs
We unconditionally pass an edition parameter to rustfmt, for some crates
this might fail rustfmt so instead of swallowing the error, at least Log
it on a level that is logged by default so users won't be completely
confused about it.
See for context https://github.com/rust-lang/rust-analyzer/issues/10209
Closes https://github.com/rust-lang/rust-analyzer/issues/10209
> Log rustfmt parsing errors as warnings

- crates/ide-assists/src/handlers/generate_function.rs
This change improves the `generate_function` assist to support generating static methods/associated functions using the `Self::assoc()` syntax. Previously, one could generate a static method, but only when specifying the type name directly (like `Foo::assoc()`). After this change, `Self` is supported as well as the type name.
Fixes #13012
> feat: Generate static method using Self::assoc() syntax

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Cc https://github.com/rust-lang/rust-analyzer/issues/10793
r? @Veykril
> document interaction of checkOnSave.overrideCommand and multiple linked projects

- .github/workflows/release.yaml
Ubuntu 18.04 is still available until December 1st, but will start failing from time to time, which is not something we want when building nightlies.
> internal: Build release binaries on `ubuntu-20.04`

- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
There are three type-related things we should consider in method resolution: `Self` type, receiver type, and impl bounds. While we check the first two and impl bounds on trait impls, we've been ignoring the impl bounds on inherent impls. With this patch rust-analyzer now takes them into account and is able to select the appropriate inherent method.
Resolves #5441 
Resolves #12308
> Consider bounds on inherent impl in method resolution

- crates/hir-def/src/data.rs
- crates/hir-def/src/db.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/inactive_code.rs
> feat: make trait assoc items become inactive due to cfg 

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir-ty/src/utils.rs
This workaround avoids constant crashing of rust analyzer when using GATs with const generics,
even when the const generics are only on the `impl` block.
The workaround treats GATs as non-existing if either itself or the parent has const generics and
removes relevant panicking code-paths.
Fixes #11989, fixes #12193
> fix: Fix panics on GATs involving const generics

- Cargo.lock
- crates/ide/src/lib.rs
- crates/ide/src/moniker.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/scip.rs
hi rust-analyzer team
I'm one of the engineers at Sourcegraph (and have done a few small changes related to the LSIF work done in rust-analyzer). Recently, we've moved to a new protocol as the primary way to interact with Sourcegraph (LSIF is still possible to upload, so existing jobs will not stop working any time soon). This new protocol is SCIP (I linked a blog post below with more information). 
I've implemented SCIP support (based largely on the existing LSIF support). In addition to supporting the existing features that `rust-analyzer`'s LSIF support does, this PR adds the ability to move between crates on sourcegraph.com. So if both your project and a dependency are indexed, you would be able to hop to the particular version and view the source code. I'd be happy to record a demo …
> feat: emit SCIP from rust-analyzer

- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-completion/src/render/literal.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13035
> fix: Fix reference autocompletions using incorrect offsets in macro inputs

- crates/rust-analyzer/src/semantic_tokens.rs
Followup to https://github.com/rust-lang/rust-analyzer/pull/13084
> fix: Register decorator token type to avoid panic

- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
Should help in preventing future occurences of #13099 by having all token types and mods come through the same place
> internal: Re-export standard semantic token types and mods

- Cargo.lock
- crates/base-db/src/input.rs
- crates/base-db/src/lib.rs
- crates/hir-def/src/test_db.rs
- crates/hir-ty/src/test_db.rs
- crates/ide-db/src/lib.rs
- crates/ide-db/src/line_index.rs
- crates/ide-db/src/search.rs
- crates/ide-db/src/source_change.rs
- crates/ide-ssr/Cargo.toml
- crates/ide-ssr/src/lib.rs
- crates/ide/src/prime_caches.rs
- crates/ide/src/references.rs
- crates/ide/src/view_crate_graph.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/global_state.rs
- crates/stdx/src/hash.rs
- crates/stdx/src/lib.rs
- crates/vfs/Cargo.toml
- crates/vfs/src/file_set.rs
- crates/vfs/src/lib.rs
Both of these are mere integers so there is nothing to hash here.
Ideally we would use this for `la_arena::Idx` too, but that doesn't work due to the orphan rule, and `la_arena` is unfortunately a public library so we can't really do much here... Unless we remove the trait restriction but I'd like not to
> Make use of NoHash hashing for FileId and CrateId

- crates/ide-assists/src/handlers/extract_type_alias.rs
> fix: make "Extract type as type alias" assist work with const generics in array

- editors/code/src/main.ts
cc https://github.com/rust-lang/rust-analyzer/issues/8844
Not sure if there's a better way to do this, feedback appreciated!
> fix: Avoid error popup when using in Live Share

- crates/rust-analyzer/src/main_loop.rs
- editors/code/src/client.ts
This only touches on the diagnostics in one place instead of multiple as was previously done, since all published diagnostics will go through this code path anyways.
Closes https://github.com/rust-lang/rust-analyzer/issues/13130
> Move empty diagnostics workaround back into the server

- crates/ide-assists/src/handlers/unmerge_match_arm.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Fixes #13072.
The way I implemented it it leaves the `OrPat` in place even if there is only one pattern now but I don't think something will break because of that, and when more code will be typed we'll parse it again anyway. Removing it (but keeping the child pattern) is hard, I don't know how to do that.
> feat: Add a "Unmerge match arm" assist to split or-patterns inside match expressions

- crates/hir-ty/src/lower.rs
The change in https://github.com/rust-lang/rust-analyzer/pull/13123
actually re-uses the RefMut borrow instead of dropping it so we need to
drop it manually where required.
Fixes https://github.com/rust-lang/rust-analyzer/issues/13153
> Drop the expander borrow in all control flow paths

- crates/hir-def/src/nameres/mod_resolution.rs
- crates/hir-def/src/nameres/tests/mod_resolution.rs
> fix: unescape all occurrences of module name in module resolution

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
- crates/ide/src/inlay_hints.rs
Fixes #12739
Chalk solver doesn't sort and deduplicate auto traits in trait object types, so we need to handle them ourselves in the lowering phase, just like [`rustc`](https://github.com/rust-lang/rust/blob/880416180b0a9ee1141c07d4d17667edb77daebd/compiler/rustc_typeck/src/astconv/mod.rs#L1487-L1488) and [`chalk-integration`](https://github.com/rust-lang/chalk/blob/master/chalk-integration/src/lowering.rs#L575) do.
Quoting from [the Chalk book](https://rust-lang.github.io/chalk/book/types/rust_types.html#dyn-types):
> Note that -- for this purpose -- ordering of bounds is significant. That means that if you create a `dyn Foo + Send` and a `dyn Send + Foo`, chalk would consider them distinct types. The assumption is that bounds are ordered in some canonical fashion somewhere else.
Also, …
> fix: sort and deduplicate auto traits in trait object types

- crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
Motivating example:
```rs
#[derive(Debug, thiserror::Error)]
enum Error {
/// Some explanation for this error
#[error("message")]
$0Woops {
code: u32
}
}
```
now becomes
```rs
/// Some explanation for this error
#[derive(Debug, thiserror::Error)]
struct Woops{
code: u32
}
#[derive(Debug, thiserror::Error)]
enum Error {
#[error("message")]
Woops(Woops)
}
```
(the `thiserror::Error` derive being copied and the struct formatting aren't ideal, though those are issues for another day)
> fix: Only move comments when extracting a struct from an enum variant

- crates/ide-assists/src/handlers/convert_two_arm_bool_match_to_matches_macro.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Resolves #12510 
This PR adds an assist, which convert 2-arm match that evaluates to a boolean into the equivalent matches! invocation.
> feature: Assist to turn match into matches! invocation

- crates/ide-assists/src/handlers/replace_or_with_or_else.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
> turn `unwrap_or` into `unwrap_or_else` and vice versa

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/reload.rs
Usually when loading up a project, once loading is done we start answering highlight requests while proc-macros haven't always been loaded yet, so we start out with showing a lot of unresolved name-refs. After this PR, we'll use syntax based highlighting for those unresolved namerefs until the proc-macros have been loaded.
> Highlight namerefs by syntax until proc-macros have been loaded

- .github/workflows/ci.yaml
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/break_outside_of_loop.rs
We now diagnose invalid `continue` expressions and properly handle things like `async` blocks which prevent labels from resolving further. Cleaned this up since `label_break_value` is on the way to stabilization in rust (🎉 finally) and we weren't handling breaks for blocks properly yet.
> Properly handle break resolution inside non-breakable expressions

- crates/syntax/src/ast/token_ext.rs
Fixes #13155 (the problem was the `PI` is defined with `_f64` suffix). `PI` is still truncated, though, because `f64` cannot represent the value with full precision.
> fix: Lower float literals with underscores

- crates/parser/src/grammar/paths.rs
- crates/parser/test_data/parser/inline/ok/0202_typepathfn_with_coloncolon.rast
- crates/parser/test_data/parser/inline/ok/0202_typepathfn_with_coloncolon.rs
e.g. `impl Fn::() -> ()`.
Fixes #13157. This was the problem, not that the path was not at the end.
I could unify the parsing of `::` of TypePathFn with that of generic arg list, but some code relies on the `::` of generic arg list to be inside it.
> fix: Parse TypePathFn with preceding `::`

- .github/workflows/release.yaml
This has been failing for a while
https://github.com/rust-lang/rust-analyzer/runs/8147683225?check_suite_focus=true#step:24:19
> internal: ignore failures when publishing to ovsx

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
They are ZSTs which we can just create on missing access instead.
> Don't store SyntheticSyntax in the reverse maps in BodySourceMap

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/autoderef.rs
- lib/la-arena/src/lib.rs
A Resolver *always* has a module scope at the end of its scope stack,
instead of encoding this as an invariant we can just lift this scope
out into a field, allowing us to skip going through the scope vec
indirection entirely.
> Lift out the module scope into a field in the Resolver

- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/tests/expression.rs
It seems that we've accidentally deleted the tests here couple of years
ago, and then fairly recently made a typo during refactor as well.
Reinstall tests, with coverage marks this time :-)
> fix: correct broken logic for return complition

- crates/ide-db/src/syntax_helpers/insert_whitespace_into_node.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
Partially fixes #13143.
To resolve the other part we need to expand macros in unevaluated static & const bodies, and I'm not sure we want to. If for example it includes a call to `assert!()`, expanding it will lead to worse hover.
> fix: Insert whitespaces into static & const bodies if they are expanded from macro on hover

- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
Fixes #13181
#12793 allowed different ordering of trait bounds in trait object types but failed to account for the ordering of projection bounds. I opted for sorting all the bounds at once rather than splitting them into `SmallVec`s so it's easier to do the same thing for other bounds when we have them.
> fix: sort all bounds on trait object types

- crates/rust-analyzer/src/reload.rs
This was discussed [on zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/.60sysroot.60.20vs.20.60sysroot_src.60.20for.20.60rust-project.2Ejson.60.3F/near/293023920), basically in `rust-project.json` workspaces RA doesn't respect the `sysroot` setting when picking which `proc-macro-srv` to launch, and this causes abi mismatches in practice.
This is the simple fix that @Veykril suggested, and I've verified that it works on Fuchsia by inspecting the cmdline with `pgrep rust-analyzer | xargs ps -fp` to check that it's using the `proc-macro-srv` from our prebuilts which matches the `sysroot` specified in our `rust-project.json`.
Can this be merged as is, or do we need to add tests that exercise this?
> Use proc-macro-srv from sysroot in rust-project.json workspaces

- .github/workflows/release.yaml
When GitHub [deprecated Ubuntu 18.04](https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/) runners, rust-analyzer was forced to bump runners to 20.04 which includes an updated Glib. This renders RA incompatible with the still popular Ubuntu 18.04 and other slightly older distro versions.
Until a deprecation plan is announced on RA's side, I propose binaries shall be built against older glibc to maintain compatibility.
This PR changes the Release CI workflow to build the `linux-x64/x86_64-unknown-linux-gnu` release in an Ubuntu 18.04 container.  
Fixes #13081 and #13085
> Build release artifact against older Glibc

- crates/hir-ty/src/infer.rs
Hi! I was looking for a "good first issue" and saw this one: https://github.com/rust-lang/rust-analyzer/issues/7542. I like searching for performance improvements, so I wanted to try to find something useful there.
There are two tests in integrated_benchmarks.rs, I looked at 'integrated_highlighting_benchmark' (not the one discussed in the issue above).
Profile from that test looks like this:
```
$ RUN_SLOW_BENCHES=1 cargo test --release --package rust-analyzer --lib -- integrated_benchmarks::integrated_highlighting_benchmark --exact --nocapture
Finished release [optimized] target(s) in 0.06s
Running unittests src/lib.rs (target/release/deps/rust_analyzer-a80ca6bb8f877458)
running 1 test
workspace loading: 358.45ms
initial: 9.60s
change: 13.96µs
cpu profiling is disabled, uncomment …
```
> Remove redundant 'resolve_obligations_as_possible' call

- crates/ide/src/annotations.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> Filter imports on find-all-references 

- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
Fixes #10677
When resolving methods for trait object types and placeholder types that are bounded by traits, we need to count the methods of the trait and its super traits as inherent methods. This matters because these trait methods have higher priority than the other traits' methods.
Relevant code in rustc: [`assemble_inherent_candidates_from_object()`](https://github.com/rust-lang/rust/blob/0631ea5d73f4a3199c776687b12c20c50a91f0d2/compiler/rustc_typeck/src/check/method/probe.rs#L783-L792) for trait object types, [`assemble_inherent_candidates_from_param()`](https://github.com/rust-lang/rust/blob/0631ea5d73f4a3199c776687b12c20c50a91f0d2/compiler/rustc_typeck/src/check/method/probe.rs#L838-L847) for placeholder types. Notice the second arg of `push_candidate()` is `is_inherent`.
> fix: handle trait methods as inherent methods for trait-related types

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/main.ts
Inlay hints are no longer something specifc to r-a as it has been upstreamed into the LSP, we don't have a reason to give the config for this feature special treatment in regards to toggling. There are plenty of other options out there in the VSCode marketplace to create toggle commands/hotkeys for configurations in general which I believe we should nudge people towards instead.
> Remove the toggleInlayHints command from VSCode

- crates/hir-ty/src/db.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/traits.rs
- crates/hir/src/lib.rs
- crates/ide/src/inlay_hints.rs
Fixes #12674
The problem is that we've been skipping the binders of normalized projections assuming they should be empty, but the assumption is unfortunately wrong. We may get back lifetime variables and should handle them before returning them as normalized projections. For those who are curious why we get those even though we treat all lifetimes as 'static, [this comment in chalk](https://github.com/rust-lang/chalk/blob/d875af0ff196dd6430b5f5fd87a640fa5ab59d1e/chalk-solve/src/infer/unify.rs#L888-L908) may be interesting.
I thought using `InferenceTable` would be cleaner than the other ways as it already has the methods for canonicalization, normalizing projection, and resolving variables, so moved goal building and trait solving logic to a new `HirDatabase` query. I made it transparent …
> fix: handle lifetime variables in projection normalization

- crates/ide-db/src/search.rs
- crates/ide/src/annotations.rs
- crates/ide/src/highlight_related.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/13186
> Move reference imports filtering into to_proto layer

- crates/hir-ty/src/db.rs
- crates/hir-ty/src/traits.rs
- crates/hir/src/lib.rs
Fixup for #13223, two things:
- `normalize_projection_query()` (and consequently `HirDatabase::normalize_projection()`) never returns `None` (well, it used to when I first wrote it...), so just return `Ty` instead of `Option<Ty>`
- When chalk cannot normalize projection uniquely, `normalize_trait_assoc_type()` used to return `None` before #13223, but not anymore because of the first point. I restored the behavior so its callers work as before.
> fixup: remove unnecessary `Option`

- crates/mbe/src/expander/matcher.rs
I had a look at the MBE code because of #7857. I found some easy readability wins, that might also _marginally_ improve perf.
> Refactor macro-by-example code

- crates/hir-def/src/nameres/collector.rs
Fixes the regression of unknown types introduced in https://github.com/rust-lang/rust-analyzer/pull/13175
> Fix prelude injection

- Cargo.lock
- crates/ide-db/Cargo.toml
- crates/ide-db/src/search.rs
We already have this dependency, so there is no reason not to use it as it is generally faster than std in our use case.
> Use memmem when searching for usages in ide-db

- crates/ide-diagnostics/src/handlers/type_mismatch.rs
Before we were using the range of the corresponding expression node in the macro expanded file, which is obviously incorrect as we are setting the text in the original source.
For some reason, the test I added is failing and I haven't found a way to fix it. Does anyone know why `check_fix` wouldn't work with macros? Getting this error:
```text
thread 'handlers::type_mismatch::tests::test_add_reference_to_macro_call' panicked at 'no diagnostics', crates/ide-diagnostics/src/handlers/type_mismatch.rs:317:9
```
closes #13219
> Fix add reference action on macros.

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/flycheck/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/rustc_cfg.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
It can be extremely useful to be able to set environment variables when rust-analyzer is running various cargo or rustc commands (such as `cargo check`, `cargo --print cfg` or `cargo metadata`): users may want to set custom `RUSTFLAGS`, change `PATH` to use a custom toolchain or set a different `CARGO_HOME`.
There is the existing `server.extraEnv` setting that allows env vars to be set when the rust-analyzer server is launched, but using this as the recommended mechanism to also configure cargo/rust has some drawbacks:
- It convolutes configuring the rust-analyzer server with configuring cargo/rustc (one may want to change the `PATH` for cargo/rustc without affecting the rust-analyzer server).
- The name `server.extraEnv` doesn't indicate that cargo/rustc will be affected but renaming it …
> Add a new configuration settings to set env vars when running cargo, rustc, etc. commands: cargo.extraEnv and checkOnSave.extraEnv

- crates/hir-ty/src/method_resolution.rs
Reverts rust-lang/rust-analyzer#13147
https://github.com/rust-lang/rust-analyzer/actions/runs/3041499441/jobs/4898678721#step:18:62
> fix: Fix a crash introduced in #13147

- crates/ide/src/inlay_hints.rs
This simply removes the reference to the `Toggle inlay hints` action after its removal in https://github.com/rust-lang/rust-analyzer/pull/13215.
In fact, this reference is still visible [in the User Manual here](https://rust-analyzer.github.io/manual.html#inlay-hints).
> Remove reference to Toggle inlay hints

- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
One would expect `TyKind::DynTy` to have at least one trait bound, but we may produce a dyn type with no trait bounds at all. This patch prevents it by returning `TyKind::Error` in such cases.
An "empty" dyn type would have caused panic during method resolution without #13257. Although already fixed, I think an invariant to never produce such types would help prevent similar problems in the future.
> Ensure at least one trait bound in `TyKind::DynTy`

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests.rs
- crates/hir/src/from_id.rs
- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
- crates/ide-db/src/search.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
fixes #12955 
This PR adds const eval support for enums, as well as showing their value on hover, just as consts currently have.
I developed these two things at the same time, but I've realized now that they are separate. However since the hover is just a 10 line change (not including tests), I figured I may as well put them in the same PR. Though if you want them split up into "enum const eval support"  and "show enum variant value on hover", I think that's reasonable too.
Since this adds const eval support for enums this also allows consts that reference enums to have their values computed now too.
The const evaluation itself is quite rudimentary, it doesn't keep track of the actual type of the enum, but it turns out that Rust doesn't actually either, and `E::A as u8` is valid …
> feat: Display the value of enum variant on hover

- crates/hir-def/src/adt.rs
- crates/hir-def/src/lib.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests.rs
- crates/hir-ty/src/tests/simple.rs
- crates/hir/src/lib.rs
Follow up for https://github.com/rust-lang/rust-analyzer/pull/12966, fixes some type inference problems which would cause type mismatches otherwise
> Properly set the enum variant body type from the repr attribute

- crates/proc-macro-srv/src/abis/abi_sysroot/mod.rs
- crates/proc-macro-srv/src/abis/mod.rs
- crates/proc-macro-srv/src/lib.rs
- crates/proc-macro-srv/src/tests/mod.rs
- crates/proc-macro-srv/src/tests/utils.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
proc-macro ABI breakage still affects the tests when a new stable version releases. Ideally we'd still be able to run the tests on the rust-analyzer repo without having to update the proc-macro ABI, but for now just to unblock CI we will ignore them here, as they are still run in upstream.
> Don't run proc-macro-srv tests on the rust-analyzer repo

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/expr.rs
- crates/hir-ty/src/builder.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/mapping.rs
- crates/hir-ty/src/tests/coercion.rs
- crates/hir-ty/src/tests/simple.rs
- crates/test-utils/src/minicore.rs
This PR implements basic type inference for generator and yield expressions.
Things not included in this PR:
- Generator upvars and generator witnesses are not implemented. They are only used to determine auto trait impls, so basic type inference should be fine without them, but method resolutions with auto trait bounds may not be resolved correctly.
Open questions:
- I haven't (yet) implemented `HirDisplay` for `TyKind::Generator`, so generator types are just shown as "{{generator}}" (in tests, inlay hints, hovers, etc.), which is not really nice. How should we show them?
- I added moderate amount of stuffs to minicore. I especially didn't want to add `impl<T> Deref for &T` and `impl<T> Deref for &mut T` exclusively for tests for generators; should I move them into the test fixtures or …
> feat: type inference for generators

- crates/ide-assists/src/handlers/unwrap_tuple.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
> Implement #12923 for only tuples.
> 
> Does not implement unwrapping for structs, as mentioned in the issue.
Add assist to unwrap tuples declarations to separate declarations.
```rust
fn main() {
$0let (foo, bar, baz) = (1.0, "example", String::new())
}
```
becomes:
```rust
fn main() {
let foo = 1.0;
let bar = "example";
let baz = String::new();
}
```
- Added assist to unwrap tuple declarations.
> Feature: Add assist to unwrap tuple declarations

- crates/base-db/src/fixture.rs
- crates/base-db/src/input.rs
- crates/ide/src/lib.rs
- crates/ide/src/moniker.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
The `PackageInformation` type from the LSIF PR used the _crate_ name instead of the _package_ name. This caused issues when looking up crates by this name on the Sourcegraph backend, where we sync crate contents, for crates such as actix-web and many of its components (actix-files, actix-http etc etc), see screenshot 1 for the observed symptom. 
This PR hasnt been tested on other entry points besides cargo (such as project json).
See screenshot 2 for the change in behaviour via SCIP snapshot comparison.
<details>
<summary>Screenshot 1</summary>
</details>
<details>
<summary>Screenshot 2</summary>
</details>
Follow-up PR to my question over at the [rust-lang Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/canonical.20crate.20name.20confusion.20f …
> Fix PackageInformation having the crate name instead of package name

- crates/rust-analyzer/tests/slow-tests/main.rs
cc https://github.com/rust-lang/rust-analyzer/pull/13286
> Use cfg(any()) instead of cfg(FALSE) for disabling proc-macro test

- crates/rust-analyzer/src/global_state.rs
When receiving multiple change events for a single file id where the last change is a delete the server panics, as it tries to access the file contents of a deleted file. This occurs due to the VFS changes and the in memory file contents being updated immediately, while `process_changes` processes the events afterwards in sequence which no longer works as it will only observe the final file contents. By folding these events together, we will no longer try to process these intermediate changes, as they aren't relevant anyways.
Potentially fixes https://github.com/rust-lang/rust-analyzer/issues/13236
> Amalgamate file changes for the same file ids in process_changes

- crates/hir-expand/src/name.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/traits.rs
- crates/ide/src/inlay_hints.rs
Part of #13299
We've been inferring the type of the yielded values in for-loop as `<T as IntoIterator>::Item`. We infer the correct type most of the time when we normalize the projection type, but it turns out not always. We should infer the type as `<<T as IntoIterator>::IntoIter as Iterator>::Item`.
When one specifies `IntoIter` assoc type of `IntoIterator` but not `Item` in generic bounds, we fail to normalize `<T as IntoIterator>::Item` (even though `IntoIter` is defined like so: `type IntoIter: Iterator<Item = Self::Item>` - rustc does *not* normalize projections based on other projection's bound I believe; see [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e88e19385094cb98fadbf647b4c2082e)).
Note that this doesn't fully fix # 13299 - given …
> fix: infer for-loop item type with `IntoIterator` and `Iterator`

- crates/hir-expand/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13323
> Fix trait impl item completions using macro file text ranges

- crates/project-model/src/workspace.rs
1. This panics since it indexes into the wrong thing, so fixes https://github.com/rust-lang/rust-analyzer/issues/13340
2. This didn't fix what I thought it would either
Reverts rust-lang/rust-analyzer#13328
> Revert "Add proc-macro dependency to rustc crates"

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
Fixup for #13335, addresses https://github.com/rust-lang/rust-analyzer/pull/13339#issuecomment-1266654607
Before the change in generic parameter order, `BoundVar`s for trait reference didn't change whether you are in an impl's scope or in an associated item's scope. Now that item's generic params come before its parent's, we need to shift their indices when we are in an associated item's scope.
> fix: use `BoundVar`s from current generic scope

- crates/ide/src/goto_definition.rs
Add a check in go-to-def feature, so that we don't assume any macro named `include`/`include_str`/`include_bytes` is the builtin one.
> minor: Fix go-to-def for shadowed `include*!`

- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
See the added test, go-to-def on `#[doc = include_str!("path$0")]` should navigate to `path`.
> fix: Make go-to-def work for `#[doc = include_str!("path")]`

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/flags.rs
- xtask/Cargo.toml
- xtask/src/flags.rs
- xtask/src/main.rs
The main change here should be that flags are not inhereted, so
$ rust-analyzer analysis-stats . -v -v
would do what it should do
We also no longer Don\'t
> internal: :arrow_up: xflags

- crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
Also fixes `generate_impl` not removing the default const param value, though it seems that no one has encountered or reported that issue yet 😅
This initially started out as refactoring `utils::generate_impl_text_inner` to understand it better (which was the reason for adding `{TypeParam,ConstParam}::remove_default`), but ended up also finding another place that needed `GenericParamList::to_generic_args`, hence its addition in here.
> internal: Add `GenericParamList::to_generic_args` and `{TypeParam,ConstParam}::remove_default` APIs

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
VS Code problem matcher are restricted to be static "regexes". You can't create a problem matcher dynamically, and you can't use custom code in lieu of problem matcher.
This creates a problem for rust/cargo compiler errors. They use paths relative to the root of the Cargo workspace, but VS Code doesn't necessary know where that root is.
Luckily, there's a way out: our current problem matcher is defined like this:
"fileLocation": [ "autoDetect", "${workspaceRoot}" ],
That means that relative pahts would be resoleved relative to workspace root. VS Code allows to specify a command inside `${}`. So we can plug custom logic there to fetch Cargo's workspace root!
And that's exactly what this PR is doing!
> fix: in VSCode, correctly resolve relative paths to errors

- crates/ide-assists/src/handlers/convert_named_struct_to_tuple_struct.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests.rs
- crates/ide-assists/src/tests/generated.rs
Closes #11643, since the assist for converting in the other direction is already there (I based most of the implementation and all of the tests on it).
> Add convert_named_struct_to_tuple_struct assist

- crates/ide-assists/src/handlers/generate_function.rs
> fix(generate_method): correct method indentation inside generated impl and change gen loc

- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/parser.rs
Currently we expand unmatched fragments by not replacing them at all, leaving us with `$ident`. This trips up the parser or subsequent macro calls. Instead it makes more sense to replace these with some reasonable default depending on the fragment kind which should make more recursive macro calls work better for completions.
> Expand unmatched mbe fragments to reasonable default token trees

- crates/project-model/src/build_scripts.rs
Seems somewhat confusing to me, given `metadata` is already the step we do for workspace loading
> Don't report build-scripts and proc-macros as metadata progress

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-ty/src/tests/patterns.rs
- crates/ide-completion/src/context.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/13375
> Honor cfg attributes on params when lowering their patterns

- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
Depends on https://github.com/rust-lang/rust-analyzer/pull/13384
Diff is unfortunately massive as I changed the functions in the analysis module from associated ones to standalone (unfortunately without an extra commit)
> Refactor completions expansion

- crates/hir-expand/src/db.rs
Should improve completions in proc-macros in some cases
> Prefer similar tokens when expanding macros speculatively

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
This should be closer to the expected output and gets rid of a few type mismatches in rustc/library
> minor: Use `$crate` instead of std for panic `builtin_fn_macro`

- crates/hir-ty/src/display.rs
- crates/hir-ty/src/tests/display_source_code.rs
Fixes #13368
#13192 changed the order of dyn bounds, violating the [contract](https://github.com/rust-lang/rust-analyzer/blob/3a69435af7a1e6273744085cb251adb2b9c30a03/crates/hir-ty/src/display.rs#L896-L901) with `write_bounds_like_dyn_trait()` on render. The projection bounds are expected to come right after the trait bound they are accompanied with.
Although the reordering procedure can be made a bit more efficient, I opted for relying only on the [invariants](https://github.com/rust-lang/rust-analyzer/blob/3a69435af7a1e6273744085cb251adb2b9c30a03/crates/hir-ty/src/lower.rs#L995-L998) currently documented in `lower_dyn_trait()`. It's not the hottest path and dyn bounds tend to be short so I believe it shouldn't hurt performance noticeably.
> fix: reorder dyn bounds on render

- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/env_vars.rs
- crates/ide-completion/src/lib.rs
- crates/ide-db/src/syntax_helpers/format_string.rs
- crates/ide-db/src/syntax_helpers/node_ext.rs
Closes #12448
Important to know:
- Variables are taken from https://doc.rust-lang.org/cargo/reference/environment-variables.html and hardcoded as a const array.
- For the sake of simplicity I didn't include the autocompletion of `CARGO_BIN_EXE_<name>` and `OUT_DIR` since it would require information about build.rs and binary name. If somebody knows an easy way of obtaining them I can add those vars as well :)
> feat: Autocomplete Cargo-defined env vars in `env!` and `option_env!` (#12448) 

- .github/workflows/ci.yaml
- crates/syntax/src/ast/make.rs
We might want to run `analysis-stats` on PRs, and this makes it less unbearable.
> internal: Run `analysis-stats` on CI, with `opt-level = 1`

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
Reverts rust-lang/rust-analyzer#13367
I didn't manage to figure out what exactly is the issue, so reverting this to fix https://github.com/rust-lang/rust-analyzer/issues/13404 before monday.
> Revert "fix: in VSCode, correctly resolve relative paths to errors"

- crates/ide-assists/src/handlers/auto_import.rs
Fixes #13105; before & after
https://user-images.githubusercontent.com/29666622/195999489-0474c93a-b2bf-41c4-b7da-a4242a8082d8.mov
https://user-images.githubusercontent.com/29666622/195999571-605ee09c-bc6f-4ee5-bfe4-73e37254c647.mov
> fix: Ignore auto-import assist on parameter names

- editors/code/src/config.ts
fix #13390 
An alternative approach could be raising an error if there is non string values.
> Cast runnableEnv items to string

- crates/hir-expand/src/mod_path.rs
- crates/hir-expand/src/name.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/traits.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/incorrect_try_expr.rs
- crates/ide-diagnostics/src/handlers/not_implemented.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide/src/hover/tests.rs
- crates/test-utils/src/minicore.rs
Trying to figure out how the type stuff in r-a works some more, I think I am doing this correct here but I am not quite sure :)
> feat: Diagnose some incorrect usages of the question mark operator

- crates/ide-assists/src/handlers/generate_constant.rs
- crates/ide-assists/src/handlers/generate_default_from_enum_variant.rs
- crates/ide-assists/src/handlers/generate_default_from_new.rs
- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_deref.rs
- crates/ide-assists/src/handlers/generate_documentation_template.rs
- crates/ide-assists/src/handlers/generate_enum_is_method.rs
- crates/ide-assists/src/handlers/generate_enum_projection_method.rs
- crates/ide-assists/src/handlers/generate_from_impl_for_enum.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/generate_getter.rs
- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/handlers/generate_new.rs
- crates/ide-assists/src/handlers/generate_setter.rs
Continuation of #13379
Migrates:
- `generate_constant`
- `generate_default_from_enum_variant`
- `generate_default_from_new`
- `generate_delegate_methods`
- `generate_deref`
- `generate_documentation_template`
- `generate_enum_is_method`
- `generate_enum_projection_method`
- `generate_from_impl_for_enum`
- `generate_function`
- `generate_getter`
- `generate_impl`
- `generate_new`
- `generate_setter`
> Migrate assists to format args captures, part 2

- editors/code/src/client.ts
- editors/code/src/config.ts
cc https://github.com/rust-lang/rust-analyzer/issues/13405
> Substitute some VSCode variables in the VSCode client

- .github/workflows/publish.yml
I believe this should *just* work? With this cargo-workspaces should not consider them
> minor: Don't auto-publish lib crates

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/ast_inspector.ts
- editors/code/src/bootstrap.ts
- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
- editors/code/src/run.ts
Follow up to https://github.com/rust-lang/rust-analyzer/pull/12847 (turns out they fixed parts of the problem)
The PR will attempt to allow us to dispose more resources at will, so that we can implement restarts for the server properly instead of restating the entire extension as well as allowing us to implement a stop command.
Closes https://github.com/rust-lang/rust-analyzer/issues/12936
Closes https://github.com/rust-lang/rust-analyzer/issues/4697
> Refactor language client handling

- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
In clients that support this (like VSCode), the clients will now render a cancel button on the notification message which can be clicked to cancel the flycheck instead.
Closes https://github.com/rust-lang/rust-analyzer/issues/6895
> feat: Make flycheck workdone progress reports cancellable

- crates/flycheck/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fixes https://github.com/rust-lang/rust-analyzer/issues/10793
This allows to change how we run build scripts (and `checkOnSave`), exposing two configs:
- `once`: run the specified command once in the project root (the working dir of the server)
- `per_workspace`: run the specified command per workspace in the corresponding workspace
This also applies to `checkOnSave` likewise, though `once_in_root` is useless there currently, due to https://github.com/rust-lang/cargo/issues/11007
> Implement invocation strategy config

- editors/code/src/main.ts
We are are rethrowing and showing errors higher up in the call stack already. This just ate the error hiding the stacktrace unnecessarily.
> fix: Don't catch the server activation error

- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_enum_is_method.rs
- crates/ide-assists/src/handlers/generate_enum_projection_method.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/generate_getter.rs
- crates/ide-assists/src/handlers/generate_new.rs
- crates/ide-assists/src/handlers/generate_setter.rs
- crates/ide-assists/src/utils.rs
This commit adds two modes to generate_getter action.
First, the plain old working on single fields.
Second, working on a selected range of fields.
Should partially solve #13246 
If this gets approved will create a separate PR for setters version of the same
- `generate_getter_from_record_info` contains code which is mostly taken from assist before refactor
- Same goes for `parse_record_fields`
- There are changes in other assists, as one of the methods in utils named `find_struct_impl` is changed, before it used to accept a single `fn_name`, now it takes a list of function names to check against. All old impls are updated to create a small list to pass their single element.
- If any of the fields have an implementation, the action will quit.
> feat: add multiple getters mode in `generate_getter`

- editors/code/src/config.ts
Fixes #13442
`String.replaceAll` and `String.replace` behave the same when given a (/g-flagged) Regex, so fix is very simple.
> Workaround the python vscode extension's polyfill

- crates/rust-analyzer/src/cli/scip.rs
Avoids a couple redundant hash map lookups and so.
> scip: minor clean-ups

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
Fixes #13121
We have been treating every generic parameter as type parameter during builtin derive macro expansion. This patch adds support for const generics in such expansions.
> Support const generics for builtin derive macro

- crates/flycheck/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This allows setting the working directory for build-scripts on flycheck
Complements https://github.com/rust-lang/rust-analyzer/pull/13128
This will be followed up by one more PR that adds a few simple interpolation vars for `overrideCommand`, with that we should cover the needs for most build systems I believe.
> Implement invocation location config

- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_definition.rs
Addresses https://github.com/rust-lang/rust-analyzer/pull/13463#issuecomment-1287816680
When finding matching impl for a trait method, we've been testing the unifiability of self type. However, there can be multiple impl of a trait for the same type with different generic arguments for the trait. This patch takes it into account and tests the unifiability of all type arguments for the trait (the first being the self type) thus enables rust-analyzer to find the correct impl even in such cases.
> fix: Test all generic args for trait when finding matching impl

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/line_index.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- lib/lsp-server/Cargo.toml
Closes #13481
This drops support for the custom extension, but that's probably fine.
Draft because it's not tested yet.
> Switch to upstream `positionEncoding`

- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/path.rs
- crates/hir-def/src/path/lower.rs
- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/display_source_code.rs
- crates/hir-ty/src/tests/traits.rs
- crates/hir-ty/src/tls.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
This PR implements type inference for generic associated types. Basically, this PR lowers generic arguments for associated types in valid places and creates `Substitution`s for them.
I focused on the inference for correct Rust programs, so there are cases where we *accidentally* manage to infer things that are actually invalid (which would then be reported by flycheck so I deem them non-fatal). See the following tests and FIXME notes on them: `gats_with_dyn`, `gats_with_impl_trait`.
The added tests are rather arbitrary. Let me know if there are cases I'm missing or I should add.
Closes #9673
> feat: type inference for generic associated types

- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/tests/traits.rs
This is a follow-up PR for #13494.
- addresses https://github.com/rust-lang/rust-analyzer/pull/13494#discussion_r1006774897
- documents the ordering constraint on `Binders` and `Substitution` (which is not really follow-up for the previous PR, but it was introduced to support GATs and I strongly feel it's worth it)
> Clean up tests and add documentation for GATs related stuff

- docs/dev/guide.md
Hi, I Just fixed some broken links in `guide.md`.
In most cases, it is not connected by an old version (expecially `guide-2019-01`) of the link, so I made some modifications.
Thanks for your time :)
> fix) update broken links in guide.md

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/coercion.rs
Fixes #13522
As [the comment](https://github.com/rust-lang/rust-analyzer/blob/8142d1f606dc2e52b1d2b8992671e2bd73379f28/crates/hir-ty/src/infer.rs#L1087-L1090) on `Expectation::adjust_for_branches` explains:
> If the expected type is just a type variable, then don't use an expected type. Otherwise, we might write parts of the type when checking the 'then' block which are incompatible with the 'else' branch.
Note that we already use it in match expressions. I've added tests for them too nevertheless.
> fix: disregard type variable expectation for if expressions

- crates/ide-assists/src/handlers/unnecessary_async.rs
Fix https://github.com/rust-lang/rust-analyzer/issues/13492
> fix: async trait method for `unnecessary_async`

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/lib.rs
- crates/hir/src/lib.rs
- crates/ide/src/signature_help.rs
This queries chalk for the `FnOnce` impl of callees and takes argument and return types from there, making generic `Callable`s available to the IDE. This makes signature help work for them, and potentially allows other features to take generic callables into account in the future.
> feat: show signature help when calling generic types implementing `FnOnce`

- crates/ide-completion/src/completions/postfix.rs
Possible fix of #7929
While reviewing the postfix completion code I saw that while calling `add_custom_postfix_completions` we were doing it under the part where reference was not taken into consideration, but as we are only adding postfix completions with `Expr` scope ( [source](https://github.com/rust-lang/rust-analyzer/blob/ba28e19b7838e3ad4223ae82d074dc3950ef1548/crates/ide-completion/src/completions/postfix.rs#L272) )
I shifted the `add_custom_postfix_completions` call to part where references are considered
I am not sure if this is the correct fix or I am understanding the problem exactly but this small move seemed to have fixed the issue :)
> fix: make custom expr prefix completions to understand refs

- crates/ide-assists/src/assist_config.rs
- crates/ide-assists/src/handlers/generate_enum_projection_method.rs
- crates/ide-assists/src/tests.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Should fix #13312 
Didn't add a test because I was not sure on how to add test for a specific configuration option, tried to look for the usages for other `AssistConfig` variants but couldn't find any in `tests`. If there is a way to test this, do point me towards it.
I tried to extract the formatting string as a common `template_string` and only have if-else for that, but it didn't compile :(
Also it seems these tests are failing:
```
test config::tests::generate_config_documentation ... FAILED
test config::tests::generate_package_json_config ... FAILED
```
Can you also point me to how to correct these 😅  ( I guess there is some command to automatically generate these? )
> feat: add config for inserting must_use in `generate_enum_as_method`

- crates/ide-assists/src/handlers/convert_to_guarded_return.rs
- crates/syntax/src/ast/make.rs
Follow up for https://github.com/rust-lang/rust-analyzer/pull/13516, addresses remaining part of https://github.com/rust-lang/rust-analyzer/issues/13254#issuecomment-1250408527
> Use let-else statements in `Convert to guarded return` assist

- crates/ide/src/moniker.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
Consider something like:
```
// a.rs
pub struct Foo { .. } // Foo is "local 1"
fn something() {
crate::b::Bar::new() // Bar is "local 1", but of "b.rs"
}
// b.rs
pub struct Bar { .. } // "local 1"
```
Without this there's no way to disambiguate whether "local 1" references "Bar" or "Foo".
> scip: Generate symbols for local crates.

- triagebot.toml
It makes rustbot add `S-waiting-on-review` to every new PR, and `@rustbot author` and `@rustbot review` commands working.
> Add rustbot features related to PR state labels

- crates/ide-assists/src/handlers/inline_call.rs
fix https://github.com/rust-lang/rust-analyzer/issues/12536
> Fixed local shadowing the caller's argument issue

- crates/ide-db/src/search.rs
- crates/ide/src/rename.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13498
> fix: Fix reference searching only accounting substrings instead of whole identifiers

- crates/ide-assists/src/handlers/add_explicit_type.rs
- crates/ide-assists/src/handlers/add_return_type.rs
- crates/ide-assists/src/handlers/add_turbo_fish.rs
- crates/ide-assists/src/handlers/apply_demorgan.rs
- crates/ide-assists/src/handlers/auto_import.rs
- crates/ide-assists/src/handlers/convert_comment_block.rs
- crates/ide-assists/src/handlers/convert_integer_literal.rs
- crates/ide-assists/src/handlers/convert_into_to_from.rs
- crates/ide-assists/src/handlers/convert_iter_for_each_to_for.rs
- crates/ide-assists/src/handlers/convert_let_else_to_match.rs
- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
- crates/ide-assists/src/handlers/convert_two_arm_bool_match_to_matches_macro.rs
- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/extract_module.rs
- crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ide-assists/src/handlers/extract_type_alias.rs
- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/fix_visibility.rs
- crates/ide-assists/src/utils.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
This not only serves as making future migration to mutable syntax trees easier, it also finds out what needs to be migrated in the first place.
~~Aside from the first commit, subsequent commits are structured to only deal with one file/handler at a time.~~
This is the first of 3 PRs, migrating:
Utils:
- `gen_trait_fn_body`
- `render_snippet`
- `ReferenceConversion`
- `convert_type`
- `getter`
Handlers:
- `add_explicit_type`
- `add_return_type`
- `add_turbo_fish`
- `apply_demorgan`
- `auto_import`
- `convert_comment_block`
- `convert_integer_literal`
- `convert_into_to_from`
- `convert_iter_for_each_to_for`
- `convert_let_else_to_match`
- `convert_tuple_struct_to_named_struct`
- `convert_two_arm_bool_match_to_matches_macro`
- `destructure_tuple_binding`
- `extract_function`
- …
> internal: Migrate `ide_assists::utils` and `ide_assists::handlers` to use format arg captures (part 1)

- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-assists/src/handlers/inline_local_variable.rs
- crates/ide-assists/src/handlers/introduce_named_lifetime.rs
- crates/ide-assists/src/handlers/merge_match_arms.rs
- crates/ide-assists/src/handlers/move_from_mod_rs.rs
- crates/ide-assists/src/handlers/move_guard.rs
- crates/ide-assists/src/handlers/move_module_to_file.rs
- crates/ide-assists/src/handlers/move_to_mod_rs.rs
- crates/ide-assists/src/handlers/number_representation.rs
- crates/ide-assists/src/handlers/qualify_method_call.rs
- crates/ide-assists/src/handlers/qualify_path.rs
- crates/ide-assists/src/handlers/raw_string.rs
- crates/ide-assists/src/handlers/remove_dbg.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/handlers/replace_or_with_or_else.rs
- crates/ide-assists/src/handlers/replace_turbofish_with_explicit_type.rs
- crates/ide-assists/src/handlers/unwrap_tuple.rs
- crates/ide-assists/src/handlers/wrap_return_type_in_result.rs
Continuation of https://github.com/rust-lang/rust-analyzer/pull/13379
Migrates:
- `inline_call`
- `inline_local_variable`
- `introduce_named_lifetime`
- `merge_match_arms`
- `move_from_mod_rs`
- `move_guard`
- `move_module_to_file`
- `move_to_mod_rs`
- `number_representation`
- `qualify_method_call`
- `qualify_path`
- `raw_string`
- `remove_dbg`
- `replace_derive_with_manual_impl`
- `replace_or_with_or_else`
- `replace_turbofish_with_explicit_type`
- `unwrap_tuple`
- `wrap_return_type_in_result`
> Migrate assists to format args captures, part 3

- docs/user/manual.adoc
closes #13533
Added a section to the user manual, to make it easier for users to find the correct crate.
> docs: add crates section to the manual

- docs/user/manual.adoc
Correct #13536 with adoc link syntax
> docs: fix adoc links

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/flycheck/src/lib.rs
Should fix https://github.com/rust-lang/rust-analyzer/issues/13348
> internal: Use a process group for flycheck

- crates/ide-db/src/line_index.rs
- crates/rust-analyzer/src/line_index.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
cc https://github.com/rust-lang/rust-analyzer/issues/13538
> internal: Optimize `apply_document_changes` a bit

- crates/ide-assists/src/handlers/extract_function.rs
**Before**
https://user-images.githubusercontent.com/1759192/183872883-3b0eafd2-d1dc-440e-9e66-38e3372f8b64.mp4 
**After**
https://user-images.githubusercontent.com/1759192/183875769-87f34c7d-52f0-4dfc-9766-f591ee738ebb.mp4
Previously, when triggering a method extraction from within an impl trait block, then this would always create a new impl block for
the struct, even if there already is one. Now, if there is already an existing trait-less impl block, then it'll put the extracted method in there.
**Caveats**:
- It currently requires the target impl block to be non-empty. This limitation is because the current architecture takes a `node_to_insert_after` as reference for where to insert the extracted function. An empty impl block doesn't have such a reference node, since it's empty. It …
> Feat: extracted method from trait impl is placed in existing impl

- crates/syntax/src/ast/token_ext.rs
This is a fix for the problem I reported earlier: "the length of byte strings containing escaped newlines is displayed two bytes longer when the first escaped character is a newline".
I would appreciate it if you could review the fix.
Many thanks.
Closes #13567
> Fix the length displayed for byte string literals with escaped newlines

- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/item_list.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13578
> fix: Fix item completions not working properly after unit structs and outline modules

- crates/hir-ty/src/lib.rs
- crates/hir/src/lib.rs
- crates/ide/src/signature_help.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13579
> fix: fix panic when computing signature of generic `FnOnce` callable

- crates/rust-analyzer/src/reload.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/5829
> fix: Send status notification if there are no found workspaces

- crates/hir-def/src/macro_expansion_tests/mbe/matching.rs
- crates/hir-def/src/macro_expansion_tests/proc_macros.rs
- crates/hir-expand/src/fixup.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/syntax_bridge/tests.rs
Fixes #13499
We currently set a `tt::Punct`'s spacing to `Spacing::Joint` unless its next token is a trivia (i.e. whitespaces or comment). As I understand it, rustc only [sets `Spacing::Joint` if the next token is an operator](https://github.com/rust-lang/rust/blob/5b3e9090757da9a95b22f589fe39b6a4b5455b96/compiler/rustc_parse/src/lexer/tokentrees.rs#L77-L78) and we should follow it to guarantee the consistent behavior of proc macros.
> Fix `tt::Punct`'s spacing calculation

- crates/hir-def/src/data.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
We already parse them, but the grammar was never updated to reflect that
> fix: Add trait alias grammar to rust.ungram

- crates/proc-macro-srv/src/abis/mod.rs
- crates/proc-macro-srv/src/dylib.rs
- crates/proc-macro-srv/src/lib.rs
cc https://github.com/rust-lang/rust-analyzer/issues/13589#issuecomment-1311824473
> internal: Add version info to unsupported proc macro abi error

- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/regression.rs
> fix: resolve inference variable before applying adjustments

- crates/proc-macro-srv/src/tests/mod.rs
Should have been included in #13548, but I didn't notice as those tests aren't run in our CI.
cc rust-lang/rust#104454
> internal: Update proc-macro-srv tests

- crates/ide-assists/src/handlers/remove_dbg.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12114
> feat: Make "Remove dbg!()" assist work on selections

- crates/rust-analyzer/src/diagnostics/to_proto.rs
- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
Also adds a VSCode only config that replaces the split diagnostic message with the first relevant part of the diagnostic output
This only affects diagnostics generated by primary spans and has no effect on other clients than VSCode.
Fixes https://github.com/rust-lang/rust-analyzer/issues/13574
> feat: Allow viewing the full compiler diagnostic in a readonly textview

- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13589
Feels like something we should just have on our side given the issue discussion
> fix: Fix proc-macro-srv search paths for Arch Linux

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/utils.rs
Fixed https://github.com/rust-lang/rust-analyzer/issues/13292
> fix(assists): remove `item_const` which had default value when implement missing members

- crates/ide-assists/src/handlers/move_format_string_arg.rs
- crates/ide-db/src/syntax_helpers/format_string_exprs.rs
- Handle positional arguments with formatting options (i.e. `{:b}`). Previously copied `:b` as an argument, producing broken code.
- Handle indexed positional arguments (`{0}`) ([reference](https://doc.rust-lang.org/std/fmt/#positional-parameters)). Previously copied over `0` as an argument.
Note: the assist also breaks when named arguments are used (`"{name}$0", name = 2 + 2` is converted to `"{}"$0, name`. I'm working on fix for that as well.
> fix: format expression parsing edge-cases

- crates/flycheck/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This PR adds support for the ability to pass multiple `--target` flags when using
`cargo` 1.64.0+.
I needed to change the type of two configurations options, but I did not plurialize the names to
avoid too much churn, should I ?
https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Issue.2013282.20.28supporting.20multiple.20targets.20with.201.2E64.2B.29
To see it working, on a macOS machine:
```sh
$ cd /tmp
$ cargo new cargo-multiple-targets-support-ra-test
$ cd !$
$ mkdir .cargo
$ echo '
[build]
target = [
"aarch64-apple-darwin",
"x86_64-apple-darwin",
]
' > .cargo/config.toml
$ echo '
fn main() {
#[cfg(all(target_arch = "aarch64", target_os = "macos"))]
{
let a = std::fs::read_to_string("/tmp/test-read");
}
#[cfg(all(target_arch = "x86_64", target_os = …
```
> Support multiple targets for checkOnSave (in conjunction with cargo 1.64.0+)

- docs/dev/architecture.md
Corrects a few grammar mistakes I found while reading the documentation 😄
> Improve grammar of architecture.md

- docs/user/manual.adoc
https://rust-analyzer.github.io/manual.html#_configuration lands you at
the start of the page, while
https://rust-analyzer.github.io/manual.html#configuration correctly puts
you at the correct anchor
> Fix typo on 'configuration' anchor

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This fixes a regression introduced by #13290, in which failing to set `checkOnSave/target` (or `checkOnSave/targets`) would lead to an invalid config.
[Fixes #13660]
> Fix: Handle empty `checkOnSave/target` values

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
expanding `compile_error!` would not properly unquote strings, leading to quite ugly diagnostic messages:
this fixes it, using the conveniently placed `unquote_str` function, which now makes errors look like:
additionally, using `unquote_str` has the cool side-effect of *also* handling raw strings, so this fixes a fixme too!
> hir-expand: fix compile_error! expansion not unquoting strings

- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
Hovering on the "rest" pattern in struct destructuring,
```rust
struct Baz {
a: u32,
b: u32,
c: u32,
d: u32
}
let Baz { a, b, ..$0} = Baz { a: 1, b: 2, c: 3, d: 4 };
```
shows:
```
.., c: u32, d: u32
```
Currently only works with struct patterns.
> feat: adds hover hint to ".." in record pattern

- crates/ide/src/goto_declaration.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/13599
- goto decl now goes to assoc items of trait declarations over the items of trait implementations
- goto decl now goes to the field declaration (opposed to goto def which shows both the field decl and binding created/local being used)
- also adds back the goto definition fallback that seems to have been dropped at some point.
> Improve goto declaration

- crates/hir-expand/src/db.rs
- crates/hir-expand/src/hygiene.rs
- crates/hir-expand/src/lib.rs
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
This saves 10mb on `self` analysis, while this does limit us to 2billion real files and 2 billion macro expansions, I doubt we will ever hit that limit :) `HirFileId` is used a lot, so going from 8 bytes to 4 is a decent win.
> internal: Reduce the size of `HirFileId` from 8 to 4 bytes

- crates/ide-completion/src/context.rs
- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/ide-completion/src/tests/special.rs
- crates/rust-analyzer/src/handlers.rs
close #13597
related: #10173
This PR also happens to fix two extra issues:
1. The test case in https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/tests/attribute.rs#L778-L801 was never triggered in previous behavior.
after:
https://user-images.githubusercontent.com/26110087/201476995-56adf955-0fa7-4f75-ab32-28a8e6cb9504.mp4
<del>
2. completions were triggered even in invalid paths, like
```rust
fn main() {
core:::::$0
}
```
```rust
#[:::::$0]
struct X;
```
</del>
only `:::` is excluded as discussed in https://github.com/rust-lang/rust-analyzer/pull/13611#discussion_r1031845205
> fix: filter unnecessary completions after colon

- crates/ide-assists/src/handlers/extract_function.rs
Fixes #13620
When extracting expressions with control flows into a function, we can avoid wrapping tail expressions in `Option` or `Result` when they are also tail expressions of the container we're extracting from (see #7840, #9773). This is controlled by `ContainerInfo::is_in_tail`, but we've been computing it by checking if the tail expression of the range to extract is contained in the container's syntactically last expression, which may be a block that contains both tail and non-tail expressions (e.g. in #13620, the range to be extracted is not a tail expression but we set the flag to true).
This PR tries to compute the flag as precise as possible by utilizing `for_each_tail_expr()` (and also moves the flag to `Function` struct as it's more of a property of the function to be …
> fix: check tail expressions more precisely in `extract_function`

- crates/rust-analyzer/src/to_proto.rs
- editors/code/src/main.ts
Addresses #13664. For now I'm just disabling runnable code lenses since the ones that display the number of references and implementations do work correctly with external code.
Also made a tiny TypeScript change to use the typed `sendNotification` overload.
> Don't show runnable code lenses in libraries outside of the workspace

- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
cc https://github.com/rust-lang/rust-analyzer/issues/13657
cc https://github.com/rust-lang/rust-analyzer/issues/13372
cc https://github.com/rust-lang/rust-analyzer/issues/13170
This will make us log an error and return the unmodified inlay hints when the client attempts to resolve inlay hints in a file that has since been modified.
> internal: Version the inlay hint resolve data

- crates/ide/src/call_hierarchy.rs
Fixes that implementing methods are shown in call hierarchy https://github.com/rust-lang/rust-analyzer/issues/13712
> check reference is a NameRef (and not Name)

- crates/ide-assists/src/handlers/move_const_to_impl.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-assists/src/utils.rs
Closes #13277
For the initial implementation, this assist:
- only applies to inherent impl. Much as we can *technically* provide this assist for default impl in trait definitions, it'd be complicated to get it right.
- may break code when the const's name collides with an item of a trait the self type implements.
Comments in the code explain those caveats in a bit more detail.
> Add `move_const_to_impl` assist

- crates/proc-macro-srv/src/abis/abi_1_58/ra_server.rs
- crates/proc-macro-srv/src/abis/abi_1_63/ra_server.rs
- crates/proc-macro-srv/src/abis/abi_sysroot/ra_server.rs
- crates/proc-macro-srv/src/tests/mod.rs
- crates/tt/src/lib.rs
Fixes #13706
When proc macros create `proc_macro::Ident`s, they pass an identifier text without "r#" prefix and a flag `is_raw` to proc macro server. Our `tt::Ident` currently stores the text *with* "r#" so we need to adjust them somewhere.
Rather than following rustc and adding `is_raw` field to our `tt::Ident`, I opted for adjusting the representation of identifiers in proc macro server, because we don't need the field outside it.
It's hard to write regression test for this, but at least I:
- ran `cargo +nightly t --features sysroot-abi` and all the tests passed
- built proc macro server with `cargo +nightly b -r --bin rust-analyzer-proc-macro-srv --features sysroot-abi` and made sure #13706 resolved
- For the record, the nightly versions used are `rustc 1.67.0-nightly (32e613bba …
> Handle raw identifiers in proc macro server

- crates/hir-def/src/adt.rs
- crates/hir-def/src/data.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/test-utils/src/minicore.rs
Fixes us not resolving `<dyn Error>::downcast` now that `Error` moved to core, while that assoc function is declared in `alloc`.
> Support `rustc_has_incoherent_inherent_impls`

- Cargo.lock
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/traits.rs
This Chalk release introduces fuel for the recursive solver ([chalk#774](https://github.com/rust-lang/chalk/pull/774)).
I'm not sure how often it calls `should_continue` compared to the other solver, so we might want to increase `CHALK_SOLVER_FUEL`, the current default value of 100 might be too low.
This should fix a lot of hangs and crashes, for example this solves the hang in #12897.
> Update to Chalk 88

- crates/hir-def/src/data.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/proc_macro.rs
- crates/hir-def/src/nameres/tests/macros.rs
- crates/hir/src/lib.rs
- crates/test-utils/src/minicore.rs
Closes #13244 
It's a bit wasteful for `Macro2Data` to have `helpers` field currently just for `Default` derive macro, but I tend to think it's okay for the time being given how rare macro2's are used.
> Support builtin derive macro helper attributes

- editors/code/package.json
Now that https://github.com/SchemaStore/schemastore/pull/2628 has been merged, adding the `jsonValidation` contribution to the VS Code extension for better editor support when modifying `rust-project.json` files.
Related issue: #13714
> Add VS Code schema validation for `rust-project.json`

- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/layout/adt.rs
- crates/hir-ty/src/layout/target.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
Small addition to https://github.com/rust-lang/rust-analyzer/pull/13490
> Show type info on hover of enum variant fields

- crates/ide/src/inlay_hints.rs
Before:
After:
----
I want to improve adjustment hints, this is the first step :)
> fix: Don't show duplicated adjustment hints for blocks, ifs and matches

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
Fixes #13734
There are some free functions `TyLoweringContext` methods call, which do not know anything about current binders in scope. We need to shift in the `BoundVar`s in substitutions that we get from them (#4952), but not those we get from `TyLoweringContext` methods.
> fix: only shift `BoundVar`s that come from outside lowering context

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/traits.rs
Fixes #13307
When we lower the return type of a function, it may contain free `BoundVar`s in `OpaqueType`'s substitution, which would cause panic during canonicalization as part of projection normalization. Those `BoundVar`s are irrelevant in this context and will be discarded, and we should defer projection normalization until then.
> fix: normalize projection after discarding free `BoundVar`s in RPIT

- crates/hir-ty/src/infer.rs
- crates/ide/src/hover/tests.rs
I think this fixes '#13773, ~but still haven't found repro. I'll try finding one so we can have a regression test~.
We should resolve every inference variable in `InferenceResult` after inference is done. We started recording `Substitution`s for each resolved associated items in #13725, but failed to do so which causes crash when analyzing source in IDE layer.
> fix: resolve all inference vars in `InferenceResult::assoc_resolutions`

- xtask/src/release/changelog.rs
This PR sets the `experimental` AsciiDoc document attribute to generated draft changelog.
That attribute is required by the keyboard macro (`kbd:[...]`).
This change of the draft will prevent issues like https://github.com/rust-analyzer/rust-analyzer.github.io/pull/191 .
> minor: Set the `experimental` AsciiDoc document attribute to generated draft changelog

- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
Closes https://github.com/rust-lang/rust-analyzer/issues/13125
> Add command for manually running flychecks

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
And document the flycheck notifications
> Add a command to clear flycheck diagnostics

- crates/parser/src/parser.rs
The parser step count is incremented every time the parser inspects a token. It's purpose is to ensure the parser doesn't get stuck in infinite loops. But since `self.pos` grows monotonically when parsing source code, it gives a better idea for whether the parser is stuck or not: if `self.pos` is changed, we know that the parser cannot be stuck, so it is safe to reset the step count to 0. This makes the limit check scale with the size of the file, and so should fix https://github.com/rust-lang/rust-analyzer/issues/13788.
> fix: fix "parser seems stuck" panic when parsing colossal files

- crates/rust-analyzer/src/handlers.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13790
Don't go through the Cargo workspace info, since that doesn't contain path dependencies. Instead, query the crate graph via `Analysis::crate_edition`.
> fix: Use the correct edition when formatting code in path dependencies

- crates/hir-def/src/macro_expansion_tests/mbe/matching.rs
- crates/mbe/src/expander/matcher.rs
Fixes #11729
`expr` fragment in mbe should not match let expressions and inline consts for backwards compatibility. See rust-lang/rust#86730 for details.
This patch is porting [this logic in rustc](https://github.com/rust-lang/rust/blob/f0c4da49983aa699f715caf681e3154b445fb60b/compiler/rustc_parse/src/parser/nonterminal.rs#L28-L34) (which is called [here in rustc's mbe engine](https://github.com/rust-lang/rust/blob/f0c4da49983aa699f715caf681e3154b445fb60b/compiler/rustc_expand/src/mbe/macro_parser.rs#L576)) to our mbe engine.
> fix: don't let mbe expr fragments match let exprs and inline consts

- crates/ide-completion/src/completions/record.rs
- crates/ide-completion/src/render/literal.rs
- crates/ide-completion/src/render/pattern.rs
- crates/ide-completion/src/render/union_literal.rs
- crates/ide-completion/src/render/variant.rs
This handles the portion of #13767 that bothered me, but I can try to work on the other parts we discussed if needed.
> Complete enum variants without parens when snippets are disabled

- crates/ide-assists/src/handlers/remove_parentheses.rs
- crates/syntax/src/ast/prec.rs
This is quite a bunch of code and some hacks, but I _think_ this time it's correct.
I've added a lot of tests, most of which fail with the assist impl from #13733 :')
> fix: Correctly check for parentheses redundancy in `remove_parentheses` assist

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide/src/inlay_hints/adjustment.rs
Supersedes https://github.com/rust-lang/rust-analyzer/pull/13765
> fix: Skip adjustment hints if the adjustment is identity (`T` -> `T`)

- crates/hir-ty/src/display.rs
- crates/hir/src/lib.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/inlay_hints/closing_brace.rs
- crates/ide/src/inlay_hints/closure_ret.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
fix #11701 
This actually doesn't work due a problem in vscode: https://github.com/microsoft/vscode/issues/167564
changelog note: The vscode issue is now fixed, but won't land until the january release, so the feature is disabled serverside for VSCode until then
> Implement location link for type inlay hints

- crates/hir-def/src/nameres/collector.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-assists/src/handlers/replace_or_with_or_else.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/const_.rs
- crates/ide-completion/src/render/literal.rs
- crates/ide-completion/src/render/type_alias.rs
- crates/ide-completion/src/tests.rs
- crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/closure_ret.rs
- crates/parser/src/lexed_str.rs
- crates/proc-macro-srv/src/abis/mod.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
I am not certain if this will improve performance, but it seems having a .clone() without any need should be removed.
This was done with clippy, and manually reviewed:
```
cargo clippy --fix -- -A clippy::all -D clippy::redundant_clone
```
> Remove non-needed clones

- crates/base-db/src/input.rs
- crates/base-db/src/lib.rs
- crates/hir-def/src/body.rs
- crates/hir-def/src/body/scope.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-db/src/lib.rs
- crates/ide-diagnostics/src/tests.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/proc-macro-srv/src/abis/abi_1_58/proc_macro/bridge/client.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/client.rs
- crates/profile/src/hprof.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/manifest_path.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/stdx/src/panic_context.rs
- crates/tt/src/buffer.rs
Seems like these can be safely fixed. With one, I was particularly surprised -- `Some(pats) => &**pats,` in body.rs?
```
cargo clippy --fix -- -A clippy::all -D clippy::explicit_auto_deref
```
> Clippy-fix explicit auto-deref

- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/tests/item_list.rs
Fixed https://github.com/rust-lang/rust-analyzer/issues/13819
> fix(completion): remove bound insert of type in trait

- crates/proc-macro-test/build.rs
- crates/vfs/src/file_set.rs
- crates/vfs/src/path_interner.rs
- xtask/src/release/changelog.rs
* use default derive
* use `strip_prefix` where possible to avoid dup work
> Minor manual cleanup

- crates/hir-ty/src/lib.rs
- crates/ide/src/syntax_highlighting/tests.rs
Fixes #13838 
The problem is similar to #13223: we've been skipping non-empty binders, letting lifetime bound variables escape.
I ended up refactoring `hir_ty::callable_sig_from_fnonce()`. Like #13223, I chose to make use of `InferenceTable` which is capable of handling variables (I feel we should always use it when we solve trait-related stuff instead of manually building obligations/queries).
I couldn't make up a test that crashes without this patch (since the function I'm fixing is only used *outside* `hir-ty`, simple `hir-ty` test wouldn't cause crash), but at least I tested with my local build and made sure it doesn't crash with the code in the original issue. I'd appreciate any help to find a regression test.
> fix: handle lifetime variables in `CallableSig` query

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/simple.rs
- crates/ide-diagnostics/src/handlers/break_outside_of_loop.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/11843
> fix: Type check unstable `try{}` blocks

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/expr.rs
- crates/hir-ty/src/infer/expr.rs
- crates/ide-db/src/syntax_helpers/node_ext.rs
- crates/ide/src/signature_help.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/src/parser.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/parser/test_data/parser/inline/ok/0204_yeet_expr.rast
- crates/parser/test_data/parser/inline/ok/0204_yeet_expr.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/prec.rs
- crates/syntax/src/tests/ast_src.rs
See tracking issue: https://github.com/rust-lang/rust/issues/96373
Before:
After:
> feat: Implement yeeting

- crates/vfs/src/lib.rs
clippy doesn't like that `PartialEq` is derived, and `Hash` is manually implemented. This PR resolves that by deriving the `Hash` implementation.
> derive 'Hash'

- crates/hir-def/src/builtin_attr.rs
- crates/hir-ty/src/utils.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
Instead of maintaining a list that is poorly kept in sync we can just use the attribute.
This will make new RA versions unusable with old toolchains that don't have the attribute yet. Should we keep maintaining the list as a fallback or just don't care?
> Use `rustc_safe_intrinsic` attribute to check for intrinsic safety

- Cargo.lock
- crates/ide-assists/Cargo.toml
- crates/ide-assists/src/handlers/extract_module.rs
Fixes #13791
In `check_intersection_and_push()`, there may exist two ranges we should merge with the new one. We've been assuming there should be only one range that intersects, which lead to [this assertion](https://github.com/rust-lang/rust-analyzer/blob/da15d92a3204da419bad70cbfceb2676bfe0b528/crates/text-edit/src/lib.rs#L192) to fail under specific circumstances.
> fix: merge multiple intersecting ranges

- crates/hir-def/src/find_path.rs
Fixes #13873
When we assemble path for prelude items whose name collides with other item in scope, we should always prefix it with module paths.
> fix: prefix prelude items whose name collides in current scope

- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/config.ts
fixes #13823 by adding a vscode setting that will keeping the existing diagnostic code and use it as a link to the full compiler error message.
While I was there I also fixed `index` to fallback to `rendered.length` to make the previewRustcOutput feature work.
> Use diagnostic code as link to full message

- crates/hir-ty/src/infer/expr.rs
- crates/ide-assists/src/handlers/add_explicit_type.rs
- crates/ide-assists/src/handlers/extract_type_alias.rs
- crates/ide-db/src/syntax_helpers/node_ext.rs
- crates/ide/src/inlay_hints/fn_lifetime_fn.rs
These currently don't work correctly, so it's better to not render them at all there
> Skip lifetime elision on fn pointers and fn trait types

- editors/code/src/client.ts
Turns out VSCode still has this issue for native hints as well, cc https://github.com/rust-lang/rust-analyzer/pull/6236
> Use ZWNJ to prevent VSCode from forming ligatures between hints and code

- crates/rust-analyzer/src/diagnostics/to_proto.rs
If they aren't machine applicable, then they might not be what the user wants, disrupting the workflow.
Example being:
Prior to the PR this the diagnostic quickfix was at the top, but usually isn't what the user wants.
> Only set machine-applicable rustc diagnostics as preferred

- crates/ide-completion/src/completions/record.rs
- crates/ide-completion/src/render/variant.rs
I didn't realize I only handled this for tuple variants in #13805. This is the same change but for record variants.
> Complete record enum variants without parens when snippets are disabled

- Cargo.lock
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/tests/traits.rs
Fixes #13249
Fixes #13518
We've been applying fallback to type variables independently even when there are some unresolved obligations that associate them. This PR applies fallback to unresolved scalar type variables before the final attempt of resolving obligations, which enables us to infer more.
Unlike rustc, which has separate storages for each kind of type variables, we currently don't have a way to retrieve only integer/float type variables without folding/visiting every single type we've inferred. I've repurposed `TypeVariableData` as bitflags that also hold the kind of the type variable it's referring to so that we can "reconstruct" scalar type variables from their indices.
This PR increases the number of ??ty for rust-analyzer repo not because we regress and fail to infer the …
> Apply fallback before final obligation resolution

- Cargo.lock
- crates/rust-analyzer/tests/slow-tests/tidy.rs
- xtask/Cargo.toml
- xtask/src/dist.rs
Closes #13872
Closes #7747
CC #10371
This allows us to ship a format that's easier to handle on Windows. As a bonus, we can also include the PDB, to get useful stack traces. Unfortunately, it adds a couple of dependencies to `xtask`, increasing the debug build times from 1.28 to 1.58 s (release from 1.60s to 2.20s) on my system.
> feat: Package Windows release artifacts as ZIP and add symbols file

- crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/completions/postfix/format_like.rs
- crates/ide-db/src/syntax_helpers/format_string_exprs.rs
closes #13640
- rename to `extract_expressions_from_format_string`
- leave identifier from format string 
- but this is from rustc version 1.65.0
- Should I add flag or something?
Note: the assist behaves below cases for now. I'll create an issue for these.
```rs
let var = 1 + 1;
// ok
format!("{var} {1+1}");   // → format!("{var} {}", 1+1);
format!("{var:?} {1+1}"); // → format!("{var:?} {}", 1 + 1);
format!("{var} {var} {1+1}"); // → format!("{var} {var} {}", 1 + 1);
// breaks (need to handle minimum width by postfix`$`)
format!("{var:width$} {1+1}"); // → format!("{var:width\$} {}", 1+1);
format!("{var:.prec$} {1+1}"); // → format!("{var:.prec\$} {}", 1+1);
format!("Hello {:1$}! {1+1}", "x" 5); // → format("Hello {:1\$}! {}", "x", 1+1);
format!("Hello {:width$}! {1+1}", "x", width = …
```
> feat: extract_expressions_from_format_string

- crates/ide-assists/src/handlers/generate_from_impl_for_enum.rs
- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/make.rs
Potentially fixes #13727.
Continuing with the work in #13732, this fix tries to add correct type bounds in the generated `impl` block:
```diff
enum Either<T, U> {
Left(T),
Right(U),
}
- impl<T, U> PartialEq for Either<T, U> {
+ impl<T: PartialEq, U: PartialEq> PartialEq for Either<T, U> {
fn eq(&self, other: &Self) -> bool {
match (self, other) {
(Self::Left(l0), Self::Left(r0)) => l0 == r0,
(Self::Right(l0), Self::Right(r0)) => l0 == r0,
_ => false,
}
}
}
```
> fix: add generic `TypeBoundList` in generated derivable impl

- crates/ide-assists/src/handlers/generate_delegate_methods.rs
Fixes a bug where the generated async method doesn't await the result before returning it.
This is an example of what the output looked like:
```rust
struct Age<T>(T);
impl<T> Age<T> {
pub(crate) async fn age<J, 'a>(&'a mut self, ty: T, arg: J) -> T {
self.0
}
}
struct Person<T> {
age: Age<T>,
}
impl<T> Person<T> {
pub(crate) async fn age<J, 'a>(&'a mut self, ty: T, arg: J) -> T {
self.age.age(ty, arg) // .await is missing
}
}
```
The `.await` is missing, so the return type is `impl Future<Output = T>` instead of `T`
> fix: generate async delegate methods

- crates/ide-assists/src/handlers/inline_macro.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
This commit adds a new r-a method, `expandMacroInline`, which expands the macro that's currently selected. See  #13598 for the most applicable issue; though I suspect it'll resolve part of #5949 and make #11888 significantly easier). 
The macro works like this:
I have 2 questions before this PR can be merged:
1. **Should we rustfmt the output?** The advantage of doing this is neater code. The disadvantages are we'd have to format the whole expr/stmt/block (since there's no point just formatting one part, especially over multiple lines), and maybe it moves the code around more in weird ways. My suggestion here is to start off by not doing any formatting; and if it appears useful we can decide to do formatting in a later release.
2.   **Is it worth solving the `$crate` hygiene issue now?** …
> Add action to expand a declarative macro once, inline. Fixes #13598

- crates/ide-assists/src/handlers/convert_ufcs_to_method.rs
- crates/ide-assists/src/handlers/unqualify_method_call.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
...which is the inverse of `qualify_method_call` assist.
Optional future work:
- import the trait if needed
- remove excess references when auto-ref is possible
> feat: Add `unqualify_method_call` assist

- crates/syntax/src/ast/token_ext.rs
suppresses a false positive clippy lint
> minor: suppress 'clippy::approx_constant' lint in test case

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/config/patch_old_style.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Now that flychecks can be triggered without saving the setting name doesn't make that much sense anymore. This PR renames it to just `check`, but keeps `checkOnSave` as the enabling setting.
> Rename `checkOnSave` settings to `check`

- editors/code/src/client.ts
Doesn't actually seem to fix the bug, it seems to be theme dependent and I am not sure what causes it
Reverts rust-lang/rust-analyzer#13886
> Revert "Use ZWNJ to prevent VSCode from forming ligatures between hints and code"

- crates/hir-ty/src/method_resolution.rs
- crates/ide/src/goto_definition.rs
fix https://github.com/rust-lang/rust-analyzer/issues/13895
> fix(ty): should query impls in nearest block

- crates/hir-def/src/nameres/mod_resolution.rs
with the 'tracking' feature enabled, `limit::Limit` is interior mutable, so the `const` `hir_def::nameres::mod_resolution::MOD_DEPTH_LIMIT` is probably meant to be `static` rather than `const`.
with `const` you get a new copy of it everywhere it's used, instead of the shared, global value that seems to be the intent.
This fix brought to you by the catchily-named `clippy::declare_interior_mutable_const` lint.
> interior-mutable types should be 'static' rather than 'const

- crates/hir-expand/src/lib.rs
- crates/ide-diagnostics/src/handlers/unlinked_file.rs
- crates/ide/src/goto_declaration.rs
- crates/vfs/src/vfs_path.rs
Finally got myself to fix this, bothered me quite a bit that this never worked
(Just gotta fix up the indentation still)
> feat: Make unlinked_file diagnostic quickfixes work for inline modules

- crates/ide-assists/src/handlers/convert_match_to_let_else.rs
Hi, first PR here!
I've noticed my IDE sometimes briefly becoming pretty slow to respond while writing Rust. When checking the logs I found reams of this same error repeating itself.
```
thread 'Worker' panicked at 'called `Option::unwrap()` on a `None` value'
crates/ide-assists/src/handlers/convert_match_to_let_else.rs:90:46
```
RA seemed to have been panicking on virtually every keystroke I made whenever I was part way through writing/refactoring a match statement of relevance to this assist.
The fix in this PR should be self-explanatory.
> Fix panicking Option unwraping in match arm analysis

- crates/hir-expand/src/db.rs
Fixes #13738
[The swc project](https://swc.rs) has lots of type definitions, and the current limit is too low for the ECMAScript/CSS visitors.
[rustdoc](https://rustdoc.swc.rs/swc_ecma_visit)
---
With this fix, the rust-analyzer shows trait-related actions.
> fix: Increase token limit of proc macro

- crates/proc-macro-srv/src/abis/abi_1_58/proc_macro/mod.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/mod.rs
closes #13920
@lnicola is this the solution you were looking for?
having explicitly unimplemented methods seems preferable to apparently implemented methods that can't be called
> remove recursive 'Display' implementations

- Cargo.lock
- crates/ide/Cargo.toml
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/adjustment.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/binding_mode.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/inlay_hints/closing_brace.rs
- crates/ide/src/inlay_hints/closure_ret.rs
- crates/ide/src/inlay_hints/discriminant.rs
- crates/ide/src/inlay_hints/fn_lifetime_fn.rs
- crates/ide/src/inlay_hints/implicit_static.rs
- crates/ide/src/inlay_hints/param_name.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
Turns out we re-implemented what clients can already figure out through the use of location-links. We might want lazy resolves tooltips later on still, but for now this simplifies things again.
> Remove hover inlay tooltips, replace them with location links

- Cargo.lock
- crates/flycheck/Cargo.toml
With #13552 the depencency of on the command-group crate was introduced, which also introduced a dependency on nix. That version of nix does not build on Haiku. This change introduces a newer version of command-group, which also updates nix from 0.22.3 to 0.26.1, which is compatible on Haiku.
> Update command-group from 1.0.8 to 2.0.1

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/inlay_hints/closing_brace.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
While the goto functionality still doesn't work in VSCode, the hover part actually does. Also the way this was gated before, one only had to update their config while r-a was running to have the links enabled automatically due to the check only living in the startup code.
> Unconditionally enable location links in inlay hints again

- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/traits.rs
While inferring binary operator expressions, Rust puts some extra constraints on the types of the operands for better inference. Relevant part in rustc is [this](https://github.com/rust-lang/rust/blob/159ba8a92c9e2fa4121f106176309521f4af87e9/compiler/rustc_hir_typeck/src/op.rs#L128-L152).
There are two things we currently fail to consider:
- we should enforce them only when both lhs and rhs type are builtin types that are applicable to the binop
- lhs and rhs types may be single reference to applicable builtin types
This PR basically ports [`enforce_builtin_binop_types()`](https://github.com/rust-lang/rust/blob/159ba8a92c9e2fa4121f106176309521f4af87e9/compiler/rustc_hir_typeck/src/op.rs#L159) and [`is_builtin_binop()`](https://github.com/rust-lang/rust/blob/159ba8a92c9e2fa4121f106176309521 …
> fix: more precise binop inference

- crates/rust-analyzer/src/main_loop.rs
The main reason people disable it is because they don't want the expensive checks to occur automatically, so we shouldn't trigger them at the start up either if this is disabled.
> Don't run flycheck on startup unless checkOnSave is enabled

- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/test_data/parser/inline/ok/0205_const_closure.rast
- crates/parser/test_data/parser/inline/ok/0205_const_closure.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
Enables parsing of the syntax for `#![features(const_closures)]` introduced in [this PR](https://github.com/rust-lang/rust/pull/106004)
> Parse const_closures syntax.

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
Initially this was done to prevent frequent inlay hint flickering, but this causes a lot of problems for a bunch of clients. We can (and already kind of have) move this into the semantic token request handlers instead.
Fixes https://github.com/rust-lang/rust-analyzer/issues/10910
> Don't respond with a ContentModified while loading the workspace

- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/markdown_remove.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/10028
> Fix markdown removal in hover handling whitespace weirdly

- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
The fallback is usually more annoying than useful at this point (it messes with the range of diagnostic popups a lot), we now have a ranged hover to check the type of something which works a lot better.
Closes https://github.com/rust-lang/rust-analyzer/issues/11602
> internal: Remove hover fallback in favor of ranged hover

- editors/code/src/bootstrap.ts
From comment by @Veykril in https://github.com/rust-lang/rust-analyzer/issues/13939#issuecomment-1398187320:
> Yep, we pull the server path first, then substitute the configs, that's the wrong order.
https://github.com/rust-lang/rust-analyzer/blob/6e52c64031825920983515b9e975e93232739f7f/editors/code/src/ctx.ts#L155-L161
Fixes #13939
> fix: substitute vscode variables in `config.serverPath`

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/lsp_utils.rs
- docs/dev/lsp-extensions.md
- editors/code/src/client.ts
- editors/code/src/ctx.ts
- editors/code/src/lsp_ext.ts
Closes https://github.com/rust-lang/rust-analyzer/issues/13995#issuecomment-1399669561
> Add a 'open server logs' button to the error notification

- crates/ide-assists/src/handlers/move_const_to_impl.rs
- crates/ide-assists/src/utils.rs
I was misunderstanding that we're always sending snippets as response to assist request. For assists that never return snippets like `move_const_to_impl` we don't need to escape, and I don't think `utils::escape_non_snippet()` is useful at the moment since we guarantee that only a single edit will have `InsertTextFormat.Snippet` and we have `utils::render_snippet()` for that.
> Don't escape non-snippets in assist

- editors/code/src/config.ts
Closes https://github.com/rust-lang/rust-analyzer/issues/14022
Not sure how a function can appear there, but there is also no reason for us to care about it anyways.
> fix: config substitution failing extension activation

- docs/user/manual.adoc
Emacs has now two LSP clients, the more minimalistic and lightweight [Eglot](https://joaotavora.github.io/eglot) and the extensive though a bit bloated [LSP Mode](https://github.com/emacs-lsp/lsp-mode). Eglot will soon be shipped with Emacs29. Both have rust-analyzer enabled by default and require no further setup other then being installed and enabled. `lsp-rust.el` is not required anymore.
The base-installation for each of those modes is so easy now that I don't think an enumerated list is necessary, both packages can be installed via the standard `M-x package-install` and the installation is a one-liner that I provide.
Configuration is only necessary for supporting the rust-analyzer extensions to the LSP protocol, which are built into LSP mode and require an …
> internal: Update documentation for emacs and split it for LSP-mode and Eglot

- crates/proc-macro-api/src/lib.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
- crates/vfs/src/lib.rs
probably fixes https://github.com/rust-lang/rust-analyzer/issues/12873 (will close it with this nevertheless as its not really reproducible)
> fix: Fix process-changes not deduplicating changes correctly

- crates/ide-assists/src/handlers/convert_match_to_let_else.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/13540
Handles complex `let` patterns (rather than just idents), and diverging block expressions have their `{`/`}` stripped to create nicer code.
> feat: Improve "match to let else" assist

- crates/rust-analyzer/src/global_state.rs
CC https://github.com/rust-lang/rust-analyzer/pull/14025#discussion_r1087946555.
> internal: Tweak change collapsing

- crates/hir-def/src/lib.rs
- crates/hir-def/src/macro_expansion_tests.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/lib.rs
We don't use it for anything yet but it might become part of hygiene
> Parse macros `allow_internal_unsafe` attribute

- lib/lsp-server/src/stdio.rs
(this is what `socket` one does)
> minor: Simplify `is_exit` check in `lsp-server`

- Cargo.lock
- crates/proc-macro-api/src/lib.rs
- crates/profile/src/lib.rs
- xtask/Cargo.toml
- xtask/src/dist.rs
This fixes the compile time regression in #13876 and sneaks in two typo fixes spotted by @cuishuang (sorry for not preserving the commit attribution, but it's a little hard to manage it across repositories).
> minor: Bump `zip` to avoid `time-macros`

- docs/user/manual.adoc
A recent PR (#14012) by @parthopdas added mention of rust-analyzer.vs, his extension for Visual Studio 2022.  I am submitting this PR to request that our extension (SourceGear Rust) be mentioned in that section as well, and also, for completeness, the VS_RustAnalyzer extension, by @cchharris.
Our extension is closed source, so I have clearly disclosed that.  For consistency, I included brief mention of the licenses for the other two options as well.  Also for the sake of consistency, I added marketplace and GitHub links for all 3.
The previously added paragraph by @parthopdas about his extension has been left intact.
> Expand docs section on Visual Studio to mention all three available extensions

- crates/hir-ty/src/lib.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-db/src/path_transform.rs
- crates/syntax/src/ast/make.rs
Part of #3639
This PR adds support for generic function generation in `generate_function` assist. Now the assist looks for generic parameters and trait bounds in scope, filters out irrelevant ones, and generates new function with them.
See `fn_generic_params()` for the outline of the procedure, and see comments on `filter_unnecessary_bounds()` for criteria for filtering. I think it's good criteria for most cases, but I'm open to opinions and suggestions.
The diff is pretty big, but it should run in linear time w.r.t. the number of nodes we operate on and should be fast enough.
Some notes:
- When we generate function in an existing impl, generic parameters may cause name conflict. While we can detect the conflict and rename conflicting params, I didn't find it worthwhile mainly because …
> Support generic function in `generate_function` assist

- crates/hir-ty/src/diagnostics/decl_check/case_conv.rs
- crates/stdx/src/lib.rs
Fixes #13521 (the attribute problem is tracked in another issue, as commented)
Note that other functions like `to_camel_case()` and `is_lower_snake_case()` already handle non-ascii characters.
> fix: support non-ascii characters in case conversion

- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-api/src/msg.rs
- crates/proc-macro-api/src/process.rs
- crates/proc-macro-srv/src/cli.rs
So as it stands, we can't really change the proc-macro-api protocol at all without breaking all proc-macro servers again. To somewhat alleviate this we can move the supported ABI mess over to the proc-macro-api now by supporting multiple versions there (versions defined by us at least, not by rustc). Since the proc-macro-api protocol has no versioning scheme at the moment though, the best we can do here is add a new request to query the version from a server. Due to how the server currently works though, if it encounters an unknown request it will exit, meaning we can check if it is a server without support by checking if it exited after our version check request, that way we can support the current circulating server as well.
We need this since our span type will change from `TokenId` to …
> Implement proc-macro-api versioning

- crates/base-db/src/fixture.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/proc_macros.rs
Fixes #13836
When we check if the offset of fake ident token is out of bounds in the "actual expansion" (i.e. expansion without the fake ident token), we should take relative offset to it into account to match [how we'd get token after expansion](https://github.com/rust-lang/rust-analyzer/blob/f1b257f4eb4fef74b42fd7135d1cf3884e8b51c9/crates/ide-completion/src/context/analysis.rs#L53-L54).
> fix: consider relative offset to fake ident token in expansion for completion

- crates/ide/src/inlay_hints/adjustment.rs
These should be unreachable, but apparently with broken enough syntax trees (I assume mismatched parens), we do reach these unreachable calls. Haven't quite figured out when this happens though.
> fix: Don't panic on broken syntax trees in adjustment inlay hints

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
With this you can now specify `cargo.sysrootSrc`. This is required for the rust workspace such that the `library` folder inside the workspace can be used as the sysroot library sources. We now also recognize if these sources are inside the workspace, tagging the as workspace members.
This does duplicate the sysroot crates still, but I don't think that causes too many problems.
> Support sysroot library source being defined inside the workspace

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/layout/tests.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
And some refactoring to make code more type safe.
> Support computing layout of RPIT

- crates/ide-assists/src/handlers/add_braces.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
This assist adds support for adding braces where it may be appropriate (e.g. lambda expressions)
> feat: add braces assist

- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/hir-def/src/macro_expansion_tests/proc_macros.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/to_parser_input.rs
- crates/mbe/src/tt_iter.rs
- crates/parser/src/event.rs
- crates/parser/src/grammar/expressions.rs
- crates/parser/src/lib.rs
- crates/parser/src/output.rs
- crates/parser/src/parser.rs
- crates/parser/src/shortcuts.rs
- crates/parser/src/tests/prefix_entries.rs
- crates/parser/test_data/parser/inline/ok/0011_field_expr.rast
- crates/parser/test_data/parser/inline/ok/0011_field_expr.rs
- crates/parser/test_data/parser/inline/ok/0107_method_call_expr.rast
- crates/parser/test_data/parser/inline/ok/0107_method_call_expr.rs
- crates/parser/test_data/parser/inline/ok/0137_await_expr.rast
- crates/parser/test_data/parser/inline/ok/0137_await_expr.rs
- crates/tt/src/buffer.rs
This is absolutely terrible but seems to work. Macro fragment parsing comes next.
> fix: Fix parsing of nested tuple field accesses in a cursed way

- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
This PR enables the `WorkspaceFoldersServerCapabilities` capability for rust-analyzer and implemented support for the associated [`DidChangeWorkspaceFolders`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeWorkspaceFolders) notification to allow clients to update the list of `workspaceFolders` sent during initialization.
This allows clients which lazily autodiscover their workspace roots (like the [helix editor](https://github.com/helix-editor/helix) once [my PR](https://github.com/helix-editor/helix/pull/5748) lands) avoid spawning multiple instances of RA. Right now such clients are forced to either:
* greedily discover all LSP roots in the workspace (precludes the ability to respond to new workspace roots)
* spawn multiple …
> Support DidChangeWorkspaceFolders notifications

- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/rust-analyzer/src/cli/ssr.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/10516
> internal: Allow specifying what proc-macro server to run in rust_analyzer::load_cargo API

- crates/ide/src/typing.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/11005
> fix: Don't insert a semicolon when typing = if parse errors are encountered

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/simple.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/11571
> fix: Implement Expactation::Castable and add a test case for it

- editors/code/package.json
This is the default, but its always better to be explicit here + we can add a small note as to why.
> minor: Explicitly disable the rust-analyzer extension in untrusted workspaces

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/tests/simple.rs
Unfixes https://github.com/rust-lang/rust-analyzer/issues/11571, the PR for that introduced some regressions (tried fixing them but doing what rustc does there specifically does not help, probably because something else affects it as well there)
> internal: Revert castable expectation and simplify

- editors/code/src/config.ts
(spurred on by <https://github.com/rust-lang/rust-analyzer/issues/4182#issuecomment-671275652>)
Caveat that this doesn't work for after tail expressions, although there shouldn't be anything after those anyways.
This also complicates when to reload the language configuration by nature of now always having a language configuration applicable.
Examples of indentation fixes:
```rs
fn main() {
println!("Hello!"); // < enter here!
// ... indents down here
fs::read_to_string("soup") // < enter here!
// ... still indents down here :(
.map(|_| ())
.map(|_| ()) // < enter here!
// ... still indents down here :D
.map_err(|_| ())
.unwrap(); // < enter here!
// ... indents down here :D
// ... and subsequent enters stay at the same indent
0.0f64
.to_radians()
.to_radians()
.to_radians() // force semi …
```
> fix: Suppress extra indent after the end of field and function chains

- crates/ide/src/inlay_hints/bind_pat.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14124
> fix: Fix bind pat inlay hints rendering for constant patterns

- xtask/src/publish.rs
- xtask/src/release/changelog.rs
Closes #13967
This isn't great because we need to fill it in manually, but getting the version number from GitHub Actions is a bit annoying.
> minor: Add version placeholder to changelog template

- docs/user/manual.adoc
Closes #14132
I don't think this is supposed to be under `Diagnostics`, but it does make sense in a way :shrug: (it's probably where someone might look).
> feat: Add clippy configuration section to the manual and update some old keys

- crates/hir-expand/src/name.rs
- crates/ide-db/src/rename.rs
- crates/ide/src/rename.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/utils.rs
Fixes #14131 
In addition to fix for #14131, this PR adds raw ident validity checks in rename functionality that we've been missing.
> fix: don't include `r#` prefix in filesystem changes

- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/context/analysis.rs
> fix: Don't trigger postfix completion in `if` block which has an `else` block

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/tests.rs
- crates/hir-expand/src/lib.rs
This patch fixes 2 bugs:
- In `Expander::enter_expand_id()` (and in code paths it's called), we never check whether we've reached the recursion limit. Although it hasn't been reported as far as I'm aware, this may cause hangs or stack overflows if some malformed attribute macro is used on associated items.
- We keep expansion even when recursion limit is reached. Take the following for example:
```rust
macro_rules! foo { () => {{ foo!(); foo!(); }} }
fn main() { foo!(); }
```
We keep expanding the first `foo!()` in each expansion and would reach the limit at some point, *after which* we would try expanding the second `foo!()` in each expansion until it hits the limit again. This will (by default) lead to ~2^128 expansions.
This is essentially what's happening in #14074. Unlike rustc, we …
> fix: Don't expand macros in the same expansion tree after overflow

- Cargo.lock
- crates/ide-db/Cargo.toml
- crates/ide-db/src/line_index.rs
- crates/ide/src/lib.rs
- crates/ide/src/shuffle_crate_graph.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/line_index.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/stdx/src/lib.rs
- crates/stdx/src/rand.rs
- docs/dev/lsp-extensions.md
Looks like this is a native encoding for Emacs at least!
> Support UTF-32 position encoding

- crates/ide-db/src/search.rs
- crates/ide/src/references.rs
- crates/ide/src/rename.rs
When we find references/usages of a raw identifier, we should disregard `r#` prefix because there are keywords one can use without the prefix in earlier editions (see #13034; this bug is actually fallout from the PR). `name`, the text we're searching for, has already been stripped of the prefix, but the text of nodes we compare it to hasn't been.
The second commit is strictly refactoring, I can remove it if it's not much of value.
> fix: Search raw identifiers without prefix

- crates/hir-def/src/path.rs
- crates/hir-def/src/path/lower.rs
> internal: Don't allocate the generic_args vec in `hir_def::Path` if it consists only of `None` args

- crates/proc-macro-api/src/version.rs
Paired to https://github.com/rust-lang/rust/pull/101550
> Add v7 metadata support to rust-analyzer

- crates/hir-def/src/adt.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/item.rs
- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests.rs
- crates/rust-analyzer/src/to_proto.rs
cc https://github.com/rust-lang/rust-analyzer/issues/12571
> internal: Don't reconstruct ref match completion in to_proto manually

- crates/ide-completion/src/item.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests.rs
- crates/rust-analyzer/src/to_proto.rs
This saves a bunch of allocations when transforming from out CompletionItem to lsp's.
> internal: Make CompletionItem more POD-like

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> minor: Try to improve the `rustfmt.overrideCommand` docs

- crates/ide/src/doc_links.rs
- crates/ide/src/runnables.rs
- editors/code/package.json
This adds the `openDocs` command to the VS Code context menu. I believe there are probably many user who are unaware of this command existing in the rust analyzer extension, and that this should enhance the discoverability of the command. Additionally, even if people are aware of this capability, it's helpful to have this in the context menu anyway; for example, one might forget the name of the command, or the keybinding they have assigned to it. I think that opening docs is a common enough action to warrant the extra line added to the context menu.
This makes a few other small changes as well. There are two minor style changes to increase style consistency. First, it changes the titles of the two commands that the rust analyzer extension will contribute to the context menu to title case. …
> add openDocs command to context menu in VS Code extension

- Cargo.lock
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/utils.rs
- crates/syntax/Cargo.toml
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/traits.rs
This is a clean-up patch to replace `use itertools::Either` with `use either::Either` for the sake of consistency.
> minor: import `Either` from `either`

- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/parser/src/grammar/paths.rs
- crates/parser/test_data/parser/inline/err/0016_angled_path_without_qual.rast
- crates/parser/test_data/parser/inline/err/0016_angled_path_without_qual.rs
`type A = <()>;` is parsed just fine by rust-analyzer, but then rejected by rustc:
```
error: expected `::`, found `;`
--> x.rs:7:14
|
7 | type A = <()>;
|              ^ expected `::`
```
Fixed by adding a lookahead for the `::` token after fully-qualified path segments.
> fix: Add check for extra path segments after a fully qualified one

- crates/toolchain/src/lib.rs
- editors/code/src/toolchain.ts
Some people set `$CARGO_HOME` to a location other than `~/.cargo` (`$XDG_DATA_DIR/cargo`,  in my case), and I'd be a little nicer if the rust-analyzer extension and server respect that value when looking up toolchains, instead of having us configure all of `$CARGO`, `$RUSTC` ... manually.
The new implementation still defaults to `~/.cargo` if `$CARGO_HOME` is unset, pretty much like cargo itself does (as documented in https://doc.rust-lang.org/cargo/guide/cargo-home.html), so the change is backwards compatible for most people except those who has configured `$CARGO_HOME` explicitly.
I considered using https://crates.io/crates/home as suggested by https://doc.rust-lang.org/cargo/guide/cargo-home.html, but decided to put int on hold because i) we need mirror impl in node, ii) I thought the …
> Respect $CARGO_HOME when looking up toolchains.

- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_definition.rs
fix #14030 The variable type is being determined incorrectly
This PR fixed a problem in which `go to definition` is jumping to the incorrect position because it was failing to resolve the type in case it defined in the module when resolving hir.
In addition, I added a test for this issue and refactored the related code.
This is my first PR and I am using a translation tool to write this text. Let me know if you have any problems.
> fix:add a case in which remainig is None in resolveing types when resolving hir path. 

- crates/hir/src/lib.rs
There doesn't seem to be an API to fetch the type of `raw_ptr`, which is helpful for a project I work on.
Notes:
- I am unsure about the function name, do let me know if I should use something else.
- Also unsure about where to add tests, for hir changes. Will fix it as needed.
> add: clean api to get `raw_ptr` type

- crates/flycheck/src/lib.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
Fixes flycheck not working for the rustc workspace when using `linkedProjects`
> internal: Deduplicate source roots that have overlapping include paths

- crates/hir-ty/src/display.rs
- crates/ide/src/hover/tests.rs
> Add tuple to render_const_scalar

- crates/project-model/src/workspace.rs
Turns out the rustc workspace has tools that rely on the external crates themselves so this check is faulty
> Don't drop rustc crates in the rustc workspace

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
We have too many false mismatches at the moment for these to be enabled
cc https://github.com/rust-lang/rust-analyzer/pull/14222
> Disable pattern type mismatches again

- crates/ide-completion/src/context.rs
- crates/ide-completion/src/render/macro_.rs
Fixes #14246
rust-analyzer used the token at the cursor after macro expansion to decide whether to replace the token at the cursor before macro expansion. In most cases these two are the same but in some cases these can mismatch which can lead to incorrect replacements.
For example if an ident/expr macro argument is missing rust-analyzer generates a "missing" identifier as a placeholder, there is only a brace at the cursor. Therefore, rust-analyzer will incorrectly replace the macro brace with the completion in that case leading to #14246.
Using the expanded token type was intentional. However, this doesn't seem to ever be desirable (this is supported by the fact that there were no tests that relied on this behavior) since the type of edit to perform should always be determined by the …
> generate correct completion edits for missing macro arguments

- crates/rust-analyzer/src/cli/analysis_stats.rs
```
❯ cargo run --release -p rust-analyzer -q analysis-stats --memory-usage .
Database loaded:     2.09s, 218mb (metadata 275.07ms, 21mb; build 1.29s, 504kb)
crates: 44, mods: 916, decls: 19582, fns: 14631
Item Collection:     14.33s, 472mb
exprs: 420422, ??ty: 68 (0%), ?ty: 141 (0%), !ty: 1
pats: 82968, ??ty: 11 (0%), ?ty: 10 (0%), !ty: 178
Inference:           47.84s, 745mb
Total:               62.16s, 1217mb
```
We currently have 178 mismatches on r-a itself
> internal: Report type metrics for patterns

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/hover/tests.rs
Confusing PR title tbf but this makes it so `bar` in `foo.bar()` resolves to the field if it exists and no method with the same name exists. Improves UX slightly when incorrectly calling a field.
> internal: Handle fields called as method calls as the fields they resolve to

- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/tests.rs
This reduced inference time on my local build by roughly ~1 sec (out of like 60)
> internal: Re-use the resolver in `InferenceContext` instead of rebuilding it whenever needed

- crates/ide-diagnostics/src/handlers/expected_function.rs
- crates/ide-diagnostics/src/handlers/unresolved_field.rs
- crates/ide-diagnostics/src/handlers/unresolved_method.rs
Our type checking is still not good enough for us to have these diagnostics be enabled by default it seems so let's mark them as experimental for now. 
cc https://github.com/rust-lang/rust-analyzer/issues/14259
> internal: Mark unresolved field, unresolved method and expected function diagnostics experimental

- crates/parser/src/grammar.rs
- crates/parser/src/grammar/attributes.rs
- crates/parser/src/grammar/expressions.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/test_data/parser/err/0049_let_else_right_curly_brace_for.rast
- crates/parser/test_data/parser/err/0049_let_else_right_curly_brace_for.rs
- crates/parser/test_data/parser/err/0050_let_else_right_curly_brace_loop.rast
- crates/parser/test_data/parser/err/0050_let_else_right_curly_brace_loop.rs
- crates/parser/test_data/parser/err/0051_let_else_right_curly_brace_match.rast
- crates/parser/test_data/parser/err/0051_let_else_right_curly_brace_match.rs
- crates/parser/test_data/parser/err/0052_let_else_right_curly_brace_while.rast
- crates/parser/test_data/parser/err/0052_let_else_right_curly_brace_while.rs
- crates/parser/test_data/parser/err/0053_let_else_right_curly_brace_if.rast
- crates/parser/test_data/parser/err/0053_let_else_right_curly_brace_if.rs
- crates/parser/test_data/parser/inline/err/0017_let_else_right_curly_brace.rast
- crates/parser/test_data/parser/inline/err/0017_let_else_right_curly_brace.rs
fix #14221 
My thinking is to check if the `expr` after `=` is block like when parse `let ... lese` , and if so, emit error.
> fix: show diagnostic for } token followed by else in let else statement

- crates/project-model/src/build_scripts.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13591
Verified that this makes things work in the clippy repo (like resolving `sym` things for example)
> fix: Load proc-macros for rustc_private crates

- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
If the client support our server status notification there is no need to show the pop up for workspace fetching failures since that's already going to be shown in the status.
cc https://github.com/rust-lang/rust-analyzer/issues/14193
> Load proc-macros for rustc_private crates

- crates/hir/src/semantics.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_attributes.html
- crates/ide/src/syntax_highlighting/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/11350
> fix: Highlight unresolved derives as being unresolved

- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/tests/simple.rs
> fix: Evaluate consts in `path_to_const`

- crates/hir-def/src/body/tests/block.rs
- crates/hir-def/src/item_tree/lower.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14263
> fix: Fix block defmap not looking into tail expressions for macro calls

- crates/flycheck/src/lib.rs
Fixes #14217
This isn't great because it un-mixes the messages from the two streams, but maybe it's not such a big problem?
> fix: Watch both stdout and stderr in flycheck

- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- editors/code/src/commands.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
cc https://github.com/rust-lang/rust-analyzer/issues/14193 closes https://github.com/rust-lang/rust-analyzer/issues/9909
> feat: Add fancy buttons to the vscode status message

- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
`hir::diagnostics::MissingMatchArms.match_expr` had confusing name: it is pointing to scrutinee expression. Renamed to `scrutinee_expr` and used better fitting type for it.
Also small refactorings/cleanup.
> internal: Rename `hir::diagnostics::MissingMatchArms.match_expr` field

- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Closes #14315
Not sure if we want to do it like this or to add an extra config key, though.
> fix: Pass flycheck extra args when running build scripts

- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/handlers.rs
Hi folks! Just a quick addition to the status output. There are some colleagues of mine who use a mix of Buck and Cargo. A person spent a bit of time this past week trying to figure out there the `rust-project.json` was coming from and pointed out that `rust-analyzer: Status` could be a good place to put this information. rust-analyzer doesn't seem to record the full path of the `Cargo.toml` or the `rust-project.json`, just the root directory. While not perfect, this should be enough for people to unblock themselves on. Here's an example of `rust-analyzer: Status` on the rust-analyzer repo:
```
Workspaces:
Loaded 192 packages across 1 workspace.
Workspace roots: [AbsPath("/Users/dbarsky/Developer/rust-analyzer")]
Analysis:
57mb of files
0b of index symbols (0)
2514 trees, 128 preserved …
```
> Add path of workspace root folders to status output

- crates/hir/src/lib.rs
Some useful functions we didn't have on `Type` (were present on `BuiltinType`).
Also, I am considering exposing `TyKind` with `get_kind`, let me know if that's a better idea than implementing these API extensions incrementally.
> feat: add `is_float` & `is_char` to `hir::Type`

- crates/hir/src/lib.rs
~`remove_slice`~ `as_slice` is same as `remove_ref` but for slices.
Though there is `as_array` which I believe was named such because it also gets the length of the array, maybe. I am still shaky on the names feel free to suggest corrections.
> internal: add `as_slice` to `hir::Type`

- crates/project-model/src/build_scripts.rs
- crates/project-model/src/workspace.rs
Also addresses https://github.com/rust-lang/rust-analyzer/issues/13591#issuecomment-1466966952
> fix: Fix rustc proc-macro handling being broken on the rustc workspace itself

- crates/ide/src/inlay_hints/adjustment.rs
- crates/syntax/src/ast/expr_ext.rs
cc https://github.com/rust-lang/rust-analyzer/pull/13749
> fix: Only skip adjustment hints for block, if and match expressions for reborrows

- crates/project-model/src/workspace.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14327
Better error reporting I'll do in a follow up
> fix: Don't pass feature flags to rustc private crates metadata invocation

- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/main_loop.rs
Should close https://github.com/rust-lang/rust-analyzer/issues/13372, retrying the way its currently implemented is not ideal as we do not adjust offsets in the requests, but doing that is a major PITA, so this should at least work around one of the more annoying issues stemming from it.
> fix: Do not retry inlay hint requests

- crates/hir-expand/src/fixup.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/node_ext.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14360
> fix: Fix `ast::IfExpr` child accessors

- Cargo.lock
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/tests/regression.rs
This release fixes a problem around GATs (rust-lang/chalk#790). While a regression test is added in chalk's own test suite, I also added one in ours so that we can catch regressions when we move away from chalk.
Fixes #14164
> internal: Bump chalk

- crates/project-model/src/workspace.rs
cc https://github.com/rust-lang/rust-analyzer/pull/14168
> internal: Reject symlinks in project-json

- crates/proc-macro-api/src/lib.rs
- crates/rust-analyzer/src/reload.rs
The server already verifies versions due to ABI picking now so there shouldn't be a need for the client side check anymore
> Remove client side proc-macro version check

- crates/base-db/src/change.rs
- crates/base-db/src/fixture.rs
- crates/base-db/src/input.rs
- crates/base-db/src/lib.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/proc_macro.rs
- crates/ide-db/src/apply_change.rs
- crates/ide-db/src/lib.rs
- crates/ide/src/lib.rs
- crates/ide/src/shuffle_crate_graph.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- docs/dev/lsp-extensions.md
- editors/code/src/commands.ts
- editors/code/src/ctx.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
Closes https://github.com/rust-lang/rust-analyzer/issues/8646
> feat: Load proc-macros asynchronously

- crates/hir-expand/src/lib.rs
- crates/ide-db/src/rename.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14379
> fix: Fix renames of locals being broken in macro calls

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/expr.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
We only used `BlockId` for the block defmap, so this is wasted memory. Lowering for non item declaring blocks is also cheaper now as we no longer have to fully lower a block that defines not items.
> internal: Only intern blocks that declare items

- editors/code/src/lsp_ext.ts
I was trying out #14409, but noticed that actually _running_ that command resulted in VS Code raising an error. This allows me to successfully run `rust-analyzer/rebuildProcMacros`.
> finish renaming `rust-analyzer/reloadProcMacros` to `rust-analyzer/rebuildProcMacros`

- crates/rust-analyzer/src/markdown.rs
> fix(rustdoc): don't escape double hashes outside of Rust code blocks

- crates/hir-def/src/db.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/traits.rs
- crates/hir-ty/src/traits.rs
- crates/hir/src/lib.rs
Before we only handled trait impls that came from the block of either the trait or the target type, we now handle them correctly by tracking the block we are currently inferring from, then walking that up to collect all block trait impls.
> fix: Properly handle local trait impls

- crates/ide-diagnostics/src/lib.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/ctx.ts
cc https://github.com/rust-lang/rust-analyzer/issues/13226 https://github.com/rust-lang/rust-analyzer/issues/9661
> feat: Pop a notification prompting the user to add a Cargo.toml of unlinked file to the linkedProjects

- crates/hir-ty/src/inhabitedness.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
> fix stack overflow in `is_ty_uninhabited_from`

- crates/base-db/src/input.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/reload.rs
As detailed in https://github.com/rust-lang/rust-analyzer/issues/14417#issuecomment-1485336174, `rust-project.json` workspaces added after the initial `rust-project.json`-based workspace was already indexed by rust-analyzer would not receive procedural macro expansion despite `config.expand_proc_macros` returning true. To fix this issue:
1. I changed `reload.rs` to check which workspaces are newly added.
2. Spawned new procedural macro expansion servers based on the _new_ workspaces.
1. This is to prevent spawning duplicate procedural macro expansion servers for already existing workspaces. While the overall memory usage of duplicate procedural macro servers is minimal, this is more about the _principle_ of not leaking processes 😅.
3. Launched procedural macro expansion if any workspaces …
> fix: allow new, subsequent `rust-project.json`-based workspaces to get proc macro expansion

- editors/code/src/debug.ts
- editors/code/src/toolchain.ts
Fix bug in Rust Analyzer VSCode where runnable debugging did not pass
environment variable from configuration to child process of Cargo on binary build stage
There is a missing env passing along to `cargo` in debug target which give an in-consistent result from debug and run target
For example
```json
{
"rust-analyzer.runnableEnv": {
"OUT_DIR": "/test/path2"
}
}
```
compiling binary is failed. Missing env
> Missing runnable env on debug target

- Cargo.lock
Should slightly improve compile times by it now not depending on serde (rowan and syntax in turn not either)
> minor: Bump smol_str

- crates/hir-def/src/data.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/regression.rs
fix #14456
At some point we should probably go further and completely desugar async fn in hir lowering.
> Use async block in async fn type inference

- crates/hir-def/src/path/lower.rs
- crates/parser/src/grammar/generic_args.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/parser/test_data/parser/inline/ok/0206_return_type_arg.rast
- crates/parser/test_data/parser/inline/ok/0206_return_type_arg.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/tests/ast_src.rs
Experimental RTN bound support was recently merged into rustc (https://github.com/rust-lang/rust/issues/109417), the goal of this PR is to allow experimentation without syntax errors everywhere.
The parsing implemented currently aligns with the state of the tracking issue, it only supports the form `T<foo(..): Bounds>`. The parser always checks for the presence of `..` to disambiguate from `Fn*()` types, this is not ideal but I didn't want to spend too much time as it is an experimental feature.
> Limited syntax support for return type notations (RTN)

- crates/ide/src/expand_macro.rs
- editors/code/src/commands.ts
When we run `Expand Macro Recursively`, we prepend a comment "Recursive expansion of foo! macro" to the expansion result. I've noticed we unconditionally render the macro name with "!" and, while super subtle, I feel a bit awkward when the macro is either a derive or attribute macro.
> Expand Macro Recursively: don't append "!" to non-bang macro name

- editors/code/src/client.ts
This should hopefully fix the other errors with paths people seem to be getting
> fix: Fix relative path creation using the wrong path accessor

- crates/ide-assists/src/handlers/generate_delegate_methods.rs
> assist: autoderef in generate delegate methods

- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
Part of #14393 
When we resolve paths in expressions (either path expressions or paths in struct expressions), there's a need of projection normalization, which `TyLoweringContext` cannot do on its own. We've been properly applying normalization for paths in struct expressions without type anchor, but not for others:
```rust
enum E {
S { v: i32 }
Empty,
}
impl Foo for Bar {
type Assoc = E;
fn foo() {
let _ = Self::Assoc::S { v: 42 };   // path in struct expr without type anchor; we already support this
let _ = <Self>::Assoc::S { v: 42 }; // path in struct expr with type anchor; resolves with this PR
let _ = Self::Assoc::Empty;         // path expr; resolves with this PR
}
}
```
With this PR we correctly resolve the whole path, but we need some more tweaks in HIR and/or IDE layers to …
> Normalize associated types in paths in expressions

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/simple.rs
> Desugar async fn completely

- crates/ide-assists/src/handlers/introduce_named_generic.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-db/src/source_change.rs
Fixes #11638 (including moving the cursor before the generated type parameter)
Adds `add_tabstop_{before,after}` for inserting tabstop snippets before & after nodes, and `add_placeholder_snippet` for wrapping nodes inside placeholder nodes.
Currently, the snippets are inserted into the syntax tree in `SourceChange::commit` so that snippet bits won't interfere with syntax lookups before completing a `SourceChange`.
It would be preferable if snippet rendering was deferred to after so that rendering can work directly with text ranges, but have left that for a future PR (it would also make it easier to finely specify which text edits have snippets in them).
Another possible snippet variation to support would be a group of placeholders (i.e. placeholders with the same tabstop number) so that a …
> internal: Implement Structured API for snippets

- crates/ide-assists/src/handlers/convert_nested_function_to_closure.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Continuation of / closes #13467.
Resolves #13230.
r? @Veykril
> feat: Convert nested function to closure assist

- crates/hir-ty/src/tests/regression.rs
#10989 seems to have been fixed. This patch merely adds a regression test.
Closes #10989
> Add regression test for #10989

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/expr.rs
- crates/hir-expand/src/name.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/break_outside_of_loop.rs
- crates/ide-diagnostics/src/handlers/undeclared_label.rs
- crates/ide-diagnostics/src/handlers/unreachable_label.rs
- crates/ide-diagnostics/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14503#issuecomment-1498951837
> internal: Resolve labels in body lowering

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/patterns.rs
- crates/hir-ty/src/tests/regression.rs
Fixes #14506
#14506 turned out to be a regression in type inference. `infer_expr_coerce_never()` added in #14251 allows never-to-any coercion but should also perform ordinary type unification in other cases.
> fix: unify types in `infer_expr_coerce_never()`

- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/ide/src/inlay_hints/adjustment.rs
> Always reborrow mutable reference receiver in methods

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/ide/src/expand_macro.rs
> Add bounds for fields in derive macro

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/ide/src/expand_macro.rs
Reverts rust-lang/rust-analyzer#14521 as it introduces too many mismatches
> Revert "Add bounds for fields in derive macro"

- crates/ide-diagnostics/src/handlers/unlinked_file.rs
- editors/code/src/client.ts
should fix https://github.com/rust-lang/rust-analyzer/issues/14523
> fix: Fix project linking popup appearing for modules that can be linked to a crate

- crates/ide-assists/src/handlers/reorder_impl_items.rs
- crates/ide-assists/src/tests/generated.rs
This PR should complete the need for restricting the applicable range of `reorder-impl-trait-items`.
When the cursor is in the associated items of the `impl` range, the assist will be disabled.
Fix: #14515 
Note: If there is any available `code-action` (`ide-assist`) available, a lightbulb icon from `lspsaga` will show in the left.
- cursor in `impl` headers
Code action is available. And it is reordering impl items.
- cursor in `impl` associated items
https://user-images.githubusercontent.com/44747719/230756906-bee7784e-bd9d-49b2-801b-743c94b4af54.png)
> fix: restrict applicable range of `reorder-impl-trait-items`

- crates/ide-assists/src/handlers/extract_function.rs
Fix allow extracting function when selecting either `{` or `}`
Fix #14514
> Fix allow extracting function from single brace of block expression

- crates/base-db/src/fixture.rs
- crates/hir-def/src/attr.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/completions/use_.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/tests.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-completion/src/tests/item_list.rs
- crates/ide-completion/src/tests/pattern.rs
- crates/ide-completion/src/tests/predicate.rs
- crates/ide-completion/src/tests/type_pos.rs
- crates/ide-completion/src/tests/use_tree.rs
- crates/ide/src/doc_links/tests.rs
- crates/ide/src/hover/tests.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- crates/test-utils/src/fixture.rs
- crates/test-utils/src/lib.rs
Closes #3020
This PR implements stability check in `ide-completion` so that unstable items are only suggested if you're on nightly toolchain.
It's a bit unfortunate `CompletionContext::check_stability()` is spammed all over the crate, but we should call it before building `CompletionItem` as you cannot get attributes on the item it's completing from that struct. I looked up every callsite of `Builder::add_to()`, `Completions::add[_opt]()`, and`Completions::add_all()` and inserted the check wherever necessary.
The tests are admittedly incomplete in that I didn't add tests for every kind of item as I thought that would be too big and not worthwhile. I copy-pasted some existing basic tests in every test module and adjusted them.
> Don't suggest unstable items on stable toolchain

- crates/hir-ty/src/display.rs
- crates/hir-ty/src/tests.rs
- crates/ide-assists/src/handlers/add_explicit_type.rs
- crates/ide-assists/src/handlers/add_return_type.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/generate_constant.rs
- crates/ide-assists/src/handlers/generate_enum_variant.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/promote_local_to_const.rs
- crates/ide-assists/src/handlers/replace_turbofish_with_explicit_type.rs
- crates/ide-completion/src/completions/fn_param.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-db/src/path_transform.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/ide-diagnostics/src/handlers/no_such_field.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/adjustment.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/binding_mode.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/inlay_hints/closing_brace.rs
- crates/ide/src/inlay_hints/closure_ret.rs
- crates/ide/src/inlay_hints/discriminant.rs
- crates/ide/src/inlay_hints/fn_lifetime_fn.rs
- crates/ide/src/inlay_hints/implicit_static.rs
- crates/ide/src/inlay_hints/param_name.rs
- crates/rust-analyzer/src/to_proto.rs
Part of #13812
This PR implements text edit for inlay hints. When an inlay hint contain text edit, user can "accept" it (e.g. by double-clicking in VS Code) to make the hint actual code (effectively deprecating the hint itself).
This PR does not implement auto import despite the original request; text edits only insert qualified types along with necessary punctuation. I feel there are some missing pieces to implement efficient auto import (in particular, type traversal function with early exit) so left it for future work. Even without it, user can use `replace_qualified_name_with_use` assist after accepting the edit to achieve the same result.
I implemented for the following inlay hints:
- top-level identifier pattern in let statements
- top-level identifier pattern in closure parameters …
> feat: make inlay hints insertable

- crates/project-model/src/sysroot.rs
- crates/rust-analyzer/src/reload.rs
Should help a bit more with user experience, before we only logged this now we show it in the status
Closes https://github.com/rust-lang/rust-analyzer/issues/11606
> internal: Warn when loading sysroot fails to find the core library

- Cargo.lock
0.5.7 is yanked because of https://github.com/crossbeam-rs/crossbeam/issues/971, let's upgrade to 0.5.8.
> minor: Bump crossbeam-channel

- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-api/src/msg.rs
- crates/proc-macro-api/src/msg/flat.rs
- crates/proc-macro-api/src/process.rs
- crates/proc-macro-srv/src/lib.rs
Mainly serves as a test for the api versioning, as I don't think we make use of the closing span yet.
> internal: Encode closing delimiter span in FlatTrees

- crates/hir-def/src/attr.rs
- crates/hir-def/src/db.rs
- crates/hir-expand/src/attrs.rs
- crates/hir/src/attrs.rs
We call this for pretty much every item, so this is unnecessary wasted memory
> internal: Put Attrs behind a query instead of AttsWithOwner

- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/layout/tests/closure.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
fix the `need-mut` part of #14562
Perhaps surprisingly, it wasn't unique immutable borrow. The code still doesn't emit any of them, and I think those won't happen in edition 2021 (which is currently the only thing implemented), since we always capture `&mut *x` instead of `&mut x`. But I'm not very sure about it.
> Fix explicit deref problems in closure capture

- crates/hir-def/src/body.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/diagnostics.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/eager.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/macro_error.rs
- crates/ide-diagnostics/src/lib.rs
We still report them on the call site as well for the time being, and the diagnostic doesn't know where the error in the definition comes from, but that can be done later on
> internal: Report macro definition errors on the definition

- crates/ide-assists/src/handlers/sort_items.rs
This restricts the "sort items alphabetically" assist when the selection is inside a `Impl` or `Trait` node & intersects with one of the associated items.
It re-orders the conditional checks of AST nodes in the `sort_items` function to check for more specific nodes first before checking `Trait` or `Impl` nodes. The `AssistContext` is passed into the `add_sort_methods_assist` function to check if the selection intersects with any inner items, e.g. associated const or type alias, function. In this case the assist does not apply.
Fixes: #14516
> internal: Restrict "sort items" assist for traits & impls

- crates/base-db/src/input.rs
- crates/ide-completion/src/tests/use_tree.rs
- crates/project-model/src/workspace.rs
- crates/test-utils/src/fixture.rs
We detect toolchain's release channel by looking at pre-release identifier of cargo/rustc's version string. It's empty for stable, "beta" or "beta.x" for beta, and "nightly" for nightly.
See rust-lang/rust's [bootstrap code] for how the version string is determined.
[bootstrap code]: https://github.com/rust-lang/rust/blob/e49122fb1ca87a6c3e3c22abb315fc75cfe8daed/src/bootstrap/lib.rs#L1244
> Fix release channel detection

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14571
With this we should be supporting vscode workspaces properly
> fix: Deduplicate passed workspaces by top level cargo workspace they belong to

- crates/ide-diagnostics/src/tests.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/test-utils/src/fixture.rs
- crates/test-utils/src/minicore.rs
> internal: Add minicore smoke test

- editors/code/package.json
- editors/code/src/commands.ts
#13472
When accepting a suggestion, the parameter hints would always trigger automatically. This PR provides the ability for users to toggle this functionality off by specifying the new "rust-analyzer.autoTriggerParameterHints" option in `settings.json`. Possible options are `true` and `false`. It's `true` by default.
> fix: `editor.parameterHints.enabled` not always being respected

- crates/base-db/src/input.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
cc #7637 
It is currently in a proof of concept stage, and it doesn't generates a copy. You need to provide your own sysroot copy in `/tmp/ra-sysroot-hack` in a way that `/tmp/ra-sysroot-hack/library/std/lib.rs` exists and `/tmp/ra-sysroot-hack/Cargo.toml` is [the one from this comment](https://github.com/rust-lang/rust-analyzer/issues/7637#issuecomment-1495008329). I will add the symlink code if we decide that this approach is not a dead end.
It seems to somehow work on my system. Go to definition into std dependencies works, type checking can look through fields if I make them public and `cfg_if` appears to work (I tested it by hovering both sides and seeing that the correct one is enabled). Though finding layout of `HashMap` didn't work.
Please try it and let me know if I should go …
> internal: Add RA_UNSTABLE_SYSROOT_HACK 

- crates/syntax/src/ast/make.rs
This is my first PR in this project. I made this PR because I needed this function to work properly for the main PR I am working on  (#14386). This is a small amendment to what it was before. We still need to improve this in order for it to fully comply with its syntactic definition as  stated [here](https://doc.rust-lang.org/reference/items/implementations.html).
> Simple fix for make::impl_trait

- crates/ide/src/goto_definition.rs
- crates/mbe/src/syntax_bridge.rs
fixes #14611 
when creating token trees for the converted doc comment, we should use the correct span in all places, rather than allowing some to remain unspecified. otherwise, things behave incorrectly.
> mbe: fix token conversion for doc comments

- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests/macros.rs
- crates/hir-expand/src/attrs.rs
Paths in derive meta item list may contain any kind of paths, including those that start with `$crate` generated by macros. We need to take hygiene into account when we lower paths in the list.
This issue was identified while investigating #14607, though this patch doesn't fix the broken trait resolution.
> fix: Resolve `$crate` in derive paths

- crates/syntax/src/ast/make.rs
There was until now no function that returns TypeAlias. This commit introduces a func that is fully compliant with the Rust Reference. I had problems working with Ident so for now the function uses simple string manipulation until ast_from_text function is called. I am however open to any ideas that could replace ident param in such a way that it accepts syntax::ast::Ident
> Add syntax::make::ty_alias

- crates/hir-def/src/data/adt.rs
- crates/hir-ty/src/lang_items.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/test-utils/src/minicore.rs
And a question: what is the benefit of storing things like `IS_BOX` in struct flags over using `lang_attr`?
> fix: Fix some typos in `StructFlags`

- .github/workflows/release.yaml
According to https://code.visualstudio.com/api/working-with-extensions/publishing-extension#prerelease-extensions, when publishing pre-release versions, `--pre-release` must also be passed in the publish step.
Currently the behavior with and without the flag seems to be the same, but since it's documented to be required, don't rely on this staying that way.
This flag was previously removed in #13020, so this partially reverts that change.
> Specify `--pre-release` when publishing vsce nightly

- crates/project-model/src/target_data_layout.rs
Two extra "rustc"s were accidentally introduced [here](https://github.com/rust-lang/rust-analyzer/commit/33591cd3f47b14961ed07a99ac23deece704243c#diff-53e4b6b2c1ff2465d8abd50db160753199426fd788ddcad925752e0838e28de2R156-R169). (I guess because `cmd` is sometimes initialized with a `cargo` under the hood, sometimes `rustc`, thus error-prone?)
One of them has been fixed [here](https://github.com/rust-lang/rust-analyzer/commit/384fa4b84ae881f402933e105c5c92b8b471036a#diff-35c78d76dfccbcece2c917b1e5b9a8e0951d5e340cf579e5ce4951142e2077d3R32). This patch fixes the other.
> fix: remove extra argument "rustc"

- Cargo.lock
- crates/base-db/Cargo.toml
- crates/base-db/src/input.rs
- crates/base-db/src/lib.rs
- crates/hir-def/src/test_db.rs
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/test_db.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide-db/src/lib.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/project-model/test_data/cargo_dev_dependencies-crate-graph.txt
- crates/project-model/test_data/complex-with-dev-deps.json
cc https://github.com/rust-lang/rust-analyzer/issues/14167
This should fix cycles errors mostly (it fixes the one on rome/tools at least, but not on rustc. Though  there it might just be because of rustc workspace being rustc workspace). Unfortunately this will effectively duplicate all crates currently, since if we want to be completely correct we'd need to set the test cfg for all dev dependencies and the transitive dependencies of those, something I worry we should try to avoid.
> Handle dev-dependency cycles

- crates/project-model/src/cargo_workspace.rs
> minor: Use `CargoConfig.extra_args` for fetching metadata

- crates/rust-analyzer/src/bin/main.rs
Should fix https://github.com/rust-lang/rust-analyzer/issues/14683
cc @jyn514
> fix: Force InitializeParams windows path drives to uppercase

- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/utils.rs
> fix: generate delegate methods filters out functions that already exist on the struct's impls

- crates/hir-def/src/body/lower.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/eval.rs
- crates/ide-diagnostics/src/handlers/break_outside_of_loop.rs
> Fix some mir related bugs

- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
- crates/ide-db/src/defs.rs
- crates/ide-db/src/items_locator.rs
- crates/ide-db/src/lib.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/lib.rs
- crates/ide/src/navigation_target.rs
- crates/ide/src/references.rs
- crates/ide/src/runnables.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/14677
instead of eagerly fetching the source data in symbol index we do it lazily now, this shouldn't make it much more expensive as we had to parse the source most of the time anyways even after fetching.
> Refactor symbol index

- crates/ide/src/doc_links.rs
- crates/ide/src/doc_links/tests.rs
- crates/ide/src/lib.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp_ext.rs
- docs/dev/lsp-extensions.md
This pull request addresses issue #12867, which requested the ability to provide links to locally built documentation when using the "Open docs for symbol" feature. Previously, rust-analyzer always used docs.rs for this purpose. With these changes, the feature will provide both web (docs.rs) and local documentation links without verifying their existence.
Changes in this PR:
- Added support for local documentation links alongside web documentation links.
- Added `target_dir` path argument for external_docs and other related methods.
- Added `sysroot` argument for external_docs.
- Added `target_directory` path to `CargoWorkspace`.
API Changes:
- Added an experimental client capability `{ "localDocs": boolean }`. If this capability is set, the `Open External Documentation` request returned …
>  Provide links to locally built documentation for `experimental/externalDocs`

- crates/hir-ty/src/diagnostics/match_check.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/tests.rs
- crates/hir-ty/src/tests/simple.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-assists/src/handlers/merge_match_arms.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/binding_mode.rs
Reduces pattern type mismatches on self to 4
> Fix pattern type mismatch in tuples

- crates/parser/src/grammar/generic_args.rs
- crates/parser/src/grammar/types.rs
- crates/parser/test_data/parser/inline/ok/0208_bare_dyn_types_with_leading_lifetime.rast
- crates/parser/test_data/parser/inline/ok/0208_bare_dyn_types_with_leading_lifetime.rs
TIL types may start with a lifetime identifier e.g. `type A = 'static + Trait;`. When parsing types, leading lifetime followed by a plus sign should be parsed as a bare dyn type rather than a generic lifetime argument or error type (which is what we produce today).
Although it's no longer accepted since Rust 2021, it wouldn't hurt to support this obsolete syntax.
> Parse bare dyn types with leading lifetime

- editors/code/src/dependencies_provider.ts
Sorts alphabetically based on dependency name. Fixes #14729
> Sort rust dependencies in vscode tree view

- editors/code/package.json
- editors/code/src/tasks.ts
Now in VS Code "go to next error" (`F8`) will bring you to the source of a panic.
> feat: define problem matcher for panics in VS Code

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/never_type.rs
Fixes #12247
Fixes #14279
Currently core has two blanket impls for `From`: `impl<T> From<T> for T` and `impl<T> From<!> for T`. These are conflicting and thus chalk cannot uniquely solve `S: From<?0>` for any type `S`.
The latter impl is actually a reservation impl and should not be considered during trait selection. More generally, impls attributed with perma-unstable `#[rustc_reservation_impl]` attribute should be disregarded except for coherence checks. See rust-lang/rust#64631 and rust-lang/rust#64715 for details.
I chose to entirely ignore them in hir-ty because we don't do coherence checks.
> fix: ignore impls with `#[rustc_reservation_impl]`

- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
This PR expands on #13490 to allow displaying layout data on hover for type aliases.
> Show type alias layout

- .github/workflows/publish-libs.yaml
- lib/README.md
line-index didn't actually get published from #14733, probably because the branch filter was for main but the main branch is called master here. This fixes the workflow file.
I also tweaked the libs readme mostly just so the paths filter would pick up the changes.
> Fix libs publish branch filter

- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Requested in https://github.com/rust-lang/rust-analyzer/pull/14748#issuecomment-1537190252
> Add config for disabling hover memory layout data

- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/layout/tests.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/simple.rs
> Lazy evaluate consts in `path_to_const`

- editors/code/package.json
> minor: Hide deps panel outside of Rust projects and set missing category

- lib/la-arena/src/lib.rs
```rust
impl<T> ExactSizeIterator for IdxRange<T>;
impl<T> Arena<T> {
pub fn alloc_many<II: IntoIterator<Item = T>>(&mut self, iter: II) -> IdxRange<T>;
}
```
1. There are no currently ways to get `IdxRange` without manually offseting `Idx`. Providing a method for multiple-allocation simplifies this process and makes it less error-prone.
2. `IdxRange: ExactSizeIterator` makes `iter.zip(range).rev()` possible. Since `Zip: DoubleEndedIterator` requires all its arguments to be `ExactSizeIterator`. It also ease the usage for, eg. `len()`.
3. Fixed a typo.
I noticed that `IdxRange::end` may be invalid. Is it good to return `Idx` instead of `RawIdx`?
> More APIs for `la_arena::IdxRange`

- crates/ide/src/syntax_highlighting.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/user/generated_config.adoc
- editors/code/package.json
cc #12783
Closes https://github.com/rust-lang/rust-analyzer/issues/13066
> Add basic support for `augmentsSyntaxTokens` and non-standard semantic token config

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
- crates/test-utils/src/minicore.rs
> Use double reference in debug derive

- crates/paths/src/lib.rs
- crates/project-model/src/manifest_path.rs
- crates/project-model/src/project_json.rs
- crates/project-model/src/workspace.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/14728
cc https://github.com/rust-lang/rust-analyzer/pull/14430
- Removes canonicalization (and forbids it from being used in a sense, clippy could help here again with its lint in the future)
- Normalizes all paths in rust-project.json which we weren't doing in some cases
> internal: Forbid canonicalization of paths and normalize all rust-project.json paths

- crates/hir/src/symbols.rs
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
- crates/ide/src/navigation_target.rs
Should fix the regressions introduced by https://github.com/rust-lang/rust-analyzer/pull/14715 by partially rolling back the PR
> fix: Fix perf regression from symbol index refactor

- crates/rust-analyzer/src/bin/main.rs
As it shouldn't be there to begin with (per discussion in #14689).
> Remove root component from patched Windows UNC path prefix

- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/nameres/tests/macros.rs
Addresses https://github.com/rust-lang/rust-analyzer/pull/14781#issuecomment-1546201022
I believe this (almost) brings the number of unresolved names back to pre-#14781:
|r-a version|`analysis-stats compiler/rustc` (rust-lang/rust@69fef92ab2f287f072b66fb7b4f62c8bb4acba43) |
|---|---|
|pre-#14781 (b069eb720bec6ce40ab224f57d271687b19b5a07) | exprs: 2747778, ??ty: 122236 (4%), ?ty: 107826 (3%), !ty: 728 |
| #14781 (a7944a93a1520b96f079bbbcd841d6aec9e4ba5d) | exprs: 2713080, ??ty: 139651 (5%), ?ty: 114444 (4%), !ty: 730 |
| with this fix | exprs: 2747871, ??ty: 122237 (4%), ?ty: 108171 (3%), !ty: 676 |
(I haven't investigated on the increase in some numbers but hopefully not too much of a problem)
This is only a temporary solution. The core problem is that we haven't fully implemented the …
> Expand more single ident macro calls upon item collection

- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/tests/special.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
> feat: add #[doc(alias(..))]-based method completions

- crates/rust-analyzer/src/cli/analysis_stats.rs
2023-05-15 rust-analyzer suffers from
```
thread 'main' panicked at 'attempt to divide by zero', crates/rust-analyzer/src/cli/analysis_stats.rs:230:56 
```
This commit <https://github.com/rust-lang/rust-analyzer/pull/14808/commits/51e8b8ff14de3507d5e21d80b750577da52b6fdd> might be the culprit.
This PR uses `percentage` function to avoid the classic “division by zero” bug.
```console
cargo new ra-test
pushd ra-test
echo "pub type Foo = u32;" >> src/lib.rs
rust-analyzer analysis-stats .
```
> fix(analysis-stats): divided by zero error

- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/chaining.rs
> fix: place type inlay hints after the item and without left-padding

- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/expr.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
Could definitely deserve more polished diagnostics, but this at least brings the message across for now.
> fix: Diagnose non-value return and break type mismatches

- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/mir/eval.rs
fix #14704
Unary operators was missed from #14705
> Fix evaluating negative for floating point types

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/resolver.rs
- crates/ide-completion/src/tests/flyimport.rs
> fix: process `macro_use` prelude in semantic scope resolver

- editors/code/src/client.ts
The default textmate grammar for rust in VSCode is pretty brittle, quite often coloring things very differently than we'd like to so we force full semantic highlighting by disabling that config.
> fix: Force disable augmentsSyntaxTokens capability on VSCode

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/mir/borrowck.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide-diagnostics/src/tests.rs
- crates/test-utils/src/minicore.rs
This is marked as experimental, since spans are terrible, there are some false positives due #14754, and it doesn't play well with unknown types. But I hope we can soon lift it.
> Add `moved-out-of-ref` diagnostic

- crates/hir/src/lib.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
The size of enum variant is what rustdoc shows (https://github.com/rust-lang/rust/pull/86263). I also added layout info for locals since it helps finding size of unnameable types like closures inside other structs or impl traits.
> Add layout info for enum variant and locals

- crates/hir-def/src/body.rs
- crates/hir-ty/src/diagnostics/match_check.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/layout/tests/closure.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
- crates/ide/src/hover/tests.rs
> Handle match scrutinee in closure captures

- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/method_resolution.rs
- crates/ide/src/goto_definition.rs
> Consider block impls in `lookup_impl_assoc_item_for_trait_ref`

- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/tests/patterns.rs
Fixes #14840
When we infer the type of ref patterns, its expected type may not be reference type: 1) expected type is an unresolved inference variable, or 2) expected type is erroneously other kind of type. In either case, we should produce a reference type with a new type variable rather than an error type so that we can continue inferring the inner patterns without further errors because of the (possible) type mismatch of this pattern.
> fix: introduce new type var when expectation for ref pat is not ref

- crates/flycheck/src/lib.rs
- crates/hir-def/src/body/pretty.rs
- crates/parser/src/grammar/expressions.rs
- crates/parser/src/grammar/items.rs
- crates/parser/src/parser.rs
- crates/parser/src/shortcuts.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/make.rs
- crates/vfs/src/lib.rs
- lib/la-arena/src/map.rs
- fix(todo): implement IntoIterator for ArenaMap<IDX, V>
- chore: remove unused method
- fix: remove useless `return`s
- fix: various clippy lints
- fix: simplify boolean test to a single negation
> Fix: a TODO and some clippy fixes

- editors/code/package.json
- editors/code/rustdoc.markdown.injection.tmGrammar.json
_This is a continuation of https://github.com/microsoft/vscode/pull/169956 and https://github.com/dustypomerleau/rust-syntax/pull/37 (that repo is no longer maintained: https://github.com/dustypomerleau/rust-syntax/issues/39#issuecomment-1427339029). The VS Code team seemed to prefer this being inside of an extension._
This adds Markdown highlighting to doc comment lines and blocks. Currently it is thus regarded both as a comment and as Markdown which leads to normally foreground text being in the colour of the comment and the rest highlighted like Markdown or its own embedded languages in code blocks.
Block comments are supported, but currently not when there is a `*` at the start of the line:
I'm not entirely sure if I can easily fix this, I'd need to find a way to make the content …
> [editors/code] add markdown syntax highlighting to doc comments

- crates/hir-def/src/attr.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/attrs.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/14769
> expand: Change how `#![cfg(FALSE)]` behaves on crate root

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/generate_derive.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/edit_in_place.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14674
These are _ad hoc_ patches for a number of assists that can produce incorrectly indented code, namely:
- generate_derive
- add_missing_impl_members
- add_missing_default_members
Some general solution is required in future, as the same problem arises in many other assists, e.g.
- replace_derive_with...
- generate_default_from_enum...
- generate_default_from_new
- generate_delegate_methods
(the list is incomplete)
> fix: assists no longer break indentation

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-ty/src/tests/macros.rs
> use `::core` instead of `$crate` in `option_env!`

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/tests/regression.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
> Evaluate `UnevaluatedConst` in unify

- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/scip.rs
Previously, rust-analyzer would write to the file index.scip unconditionally.
> Allow users to override the .scip output file path

- crates/ide/src/goto_type_definition.rs
When we're requested `Go to Type Definition`, we first downmap the token in question to tokens in every macro call expansion involved, and then determine the type of those mapped tokens by looking for the nearest ancestor node that is either expression or pattern (or a few others). This procedure has one flaw: When the downmapped token is inside another macro call, the nearest ancestor node to retrieve the type of is *that* macro call. That's not what we should return in general and therefore we should disregard it.
Notably, now that we expand built-in `format_arg!` and its family macros, we're always returning [`Arguments`] when one `Go to Type Definition` at `dbg!(variable$0)` along with the actual type of `variable` without this patch.
[`Arguments`]: …
> fix: don't try determining type of token inside macro calls

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/regression.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
> Insert type vars in function arguments

- crates/hir/src/symbols.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide-db/src/test_data/test_doc_alias.txt
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
- crates/ide/src/goto_definition.rs
- crates/ide/src/lib.rs
- crates/ide/src/navigation_target.rs
- crates/ide/src/runnables.rs
- crates/rust-analyzer/src/handlers/request.rs
Doc aliases are now visible among symbols and can be used for searching. 
fixes #14557
> feat: using doc aliases to search workspace symbols

- crates/ide-assists/src/handlers/replace_named_generic_with_impl.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
This adds a new assist named "Replace named generic with impl". It is the inverse operation to the existing "Replace impl trait with generic" assist.
It allows to refactor the following statement:
```rust
//      👇 cursor
fn new<T$0: ToString>(input: T) -> Self {}
```
to be transformed into:
```rust
fn new(input: impl ToString) -> Self {}
```
* adds new helper function `impl_trait_type` to create AST node
* add method to remove an existing generic param type from param list
Closes #14626
> feat: Assist to replace generic with impl trait

- crates/hir-ty/src/layout.rs
- crates/hir/src/lib.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/test-utils/src/minicore.rs
Arguably, these values are usually almost always viewed in hex format so I think we should do the same here
> Render size, align and offset hover values in hex

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/flycheck/src/lib.rs
- crates/ide/src/prime_caches.rs
- crates/proc-macro-srv/Cargo.toml
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/task_pool.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- crates/stdx/Cargo.toml
- crates/stdx/src/lib.rs
- crates/stdx/src/thread.rs
- crates/vfs-notify/Cargo.toml
- crates/vfs-notify/src/lib.rs
<details>
<summary>Some background (in case you haven’t heard of QoS before)</summary>
Heterogenous multi-core CPUs are increasingly found in laptops and desktops (e.g. Alder Lake, Snapdragon 8cx Gen 3, M1). To maximize efficiency on this kind of hardware, it is important to provide the operating system with more information so threads can be scheduled on different core types appropriately.
The approach that XNU (the kernel of macOS, iOS, etc) and Windows have taken is to provide a high-level semantic API – quality of service, or QoS – which informs the OS of the program’s intent. For instance, you might specify that a thread is running a render loop for a game. This makes the OS provide this thread with as large a share of the system’s resources as possible. Specifying a thread is …
> Specify thread types using Quality of Service API

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/ctx.ts
For common uses of non-Cargo build systems with rust-analyzer, the dependency view isn't particularly helpful because there isn't a Cargo.toml present for dependencies or the dependencies are part of the current workspace.
Speaking from the perspective of a user of `rust-project.json`, I'd prefer to have this feature disabled until I can add a field to `Crate` that defines the location of a build file (e.g., a `BUCK`) file, which would allow for removing the "search for a Cargo.toml in parent directories of a crate root" behavior that exists in a few places (I've opened [an issue](https://github.com/rust-lang/cargo/issues/12187) on Cargo to request this data from `cargo-metadata`).
> fix: add a toggle to disable the dependency explorer

- .github/workflows/ci.yaml
- Cargo.lock
- crates/project-model/Cargo.toml
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/11836
> Filter out unused cargo features from config

- docs/user/manual.adoc
While going through the process of installing rust-analyzer to use with Neovim, I noticed that the instructions for installing with rustup are incorrect now that [issue #2411](https://github.com/rust-lang/rustup/issues/2411) has been closed. Now when rust-analyzer is installed using rustup, it is installed in ~/.cargo/bin and a symlink or some other workaround is no longer needed. I have updated the documentation accordingly.
> Fix rustup installation description

- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/hir-def/src/macro_expansion_tests/mbe/metavar_expr.rs
- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/tt_iter.rs
This PR implements `${count()}` metavariable expression for MBE as described in [RFC 3086][rfc]. See [this section][sec-count] of the RFC for its semantics.
Additionally, this PR changes the type of depth parameter of `${index()}` from u32 to usize so as to match how [rustc parses it][index-usize].
Part of #11952
Fixes #14871
[rfc]: https://github.com/rust-lang/rfcs/pull/3086
[sec-count]: https://github.com/rust-lang/rfcs/blob/master/text/3086-macro-metavar-expr.md#count
[index-usize]:https://github.com/rust-lang/rust/blob/ddad0576caf8d0515ed453e04b468977c7d3dfc1/compiler/rustc_expand/src/mbe/metavar_expr.rs#L22
> Implement `${count()}` metavariable expression

- crates/ide-assists/src/handlers/convert_named_struct_to_tuple_struct.rs
Two fixes:
- When replacing syntax nodes, macro files weren't taken into account. Edits were simply made for `node.syntax().text_range()`, which would be wrong range when `node` is inside a macro file.
- We do ancestor node traversal for every struct name reference to find record expressions/patterns to edit, but we didn't verify that expressions/patterns do actually refer to the struct we're operating on.
Best reviewed one commit at a time.
Fixes #13780
Fixes #14927
> Fix edits for `convert_named_struct_to_tuple_struct`

- crates/cfg/src/lib.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fixes https://github.com/rust-lang/rust-analyzer/issues/14365
> Allow setting cfgs

- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/name.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/handlers/request.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14155
> Don't add --all-targets to runnables for no-std crates

- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/convert_named_struct_to_tuple_struct.rs
- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
- crates/ide-assists/src/tests.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/lib.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Closes https://github.com/rust-lang/rust-analyzer/issues/14918
> Add render configs for memory layout hovers

- Cargo.lock
- crates/flycheck/src/lib.rs
- crates/ide/src/prime_caches.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/src/task_pool.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- crates/stdx/Cargo.toml
- crates/stdx/src/thread.rs
- crates/stdx/src/thread/intent.rs
- crates/stdx/src/thread/pool.rs
- crates/vfs-notify/src/lib.rs
To this end I’ve introduced a new custom thread pool type which can spawn threads using each QoS class. This way we can run latency-sensitive requests under one QoS class and everything else under another QoS class. The implementation is very similar to that of the `threadpool` crate (which is currently used by rust-analyzer) but with unused functionality stripped out.
I’ll have to rebase on master once #14859 is merged but I think everything else is alright :D
> Prioritize threads affected by user typing

- crates/ide-assists/src/handlers/replace_named_generic_with_impl.rs
This is a follow-up PR to fix the assist "replace named generic type with impl trait" described in #14626 to filter invalid param types. It integrates the feedback given in PR #14816 .
The change updates the logic to determine when a function parameter is safe to replace a type param with its trait implementation. Some parameter definitions are invalid & should not be replaced by their traits, therefore skipping the assist completely.
First, all usages of the generic type under the cursor are determined. These usage references are checked to see if they occur outside the function parameter list. If an outside reference is found, e.g. in body, return type or where clause, the assist is skipped. All remaining usages need to appear only in the function param list. For each usage the param …
> Fix Assist "replace named generic type with impl trait"

- crates/parser/src/grammar/expressions.rs
- crates/parser/test_data/parser/ok/0028_operator_binding_power.rast
- crates/parser/test_data/parser/ok/0028_operator_binding_power.rs
- crates/parser/test_data/parser/ok/0072_destructuring_assignment.rast
- crates/parser/test_data/parser/ok/0072_destructuring_assignment.rs
Fixes #14944
Assignment operators, be they simple or complex, are right associative in Rust ([reference]). We need to consider that fact when computing [binding power][bp] of infix operators.
The changes in `0072_destructuring_assignment.{rs,rast}` are unexpected, but I'm pretty sure it's a typo and fixed the `.rs` file accordingly.
[reference]: https://doc.rust-lang.org/reference/expressions.html#expression-precedence
[bp]: https://matklad.github.io/2020/04/13/simple-but-powerful-pratt-parsing.html
> fix: assignment operators are right associative

- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/tests.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
- crates/test-utils/src/minicore.rs
Fix false positives of `need-mut` emerged from #14955 
There are still 5 `need-mut` false positives on self, all related to `izip!` macro hygenic issue. I will try to do something about that before monday release.
> Fix drop scopes problems in mir

- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/src/task_pool.rs
the diagnostics task is panicking I think, but without this you can't really tell because the stack trace ends in a generic iterator fold call instead of something specific.
> Add mandatory panic contexts to all threadpool tasks

- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/src/task_pool.rs
Reverts rust-lang/rust-analyzer#14965
This won't quite work actually given the use of `catch_unwind` in some of these
> Revert "Add mandatory panic contexts to all threadpool tasks"

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/hir.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
Fix the `need-mut` false positive for `izip!`
> Detect "bound more than once" error and suppress `need-mut` for it.

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/mir/eval/tests.rs
- crates/hir-ty/src/mir/monomorphization.rs
Fixes #14966
Basically, the crash is caused by us producing a broken type and passing it to chalk: `&dyn for<type> [for<> Implemented(^1.0: A<^0.0>)]` (notice the innermost bound var `^0.0` has no corresponding binder). It's created in `CapturedItemWithoutTy::with_ty()`, which didn't consider outer binders when folding types to replace placeholders with bound variables.
The fix is one-liner, but I've also refactored the surrounding code a little.
> fix: consider outer binders when folding captured items' type

- crates/hir-ty/src/display.rs
- crates/hir-ty/src/tests/patterns.rs
- crates/hir-ty/src/tests/regression.rs
- crates/ide-assists/src/handlers/extract_function.rs
This makes the generated code not linted by `rust_2018_idioms` lint. But that is an allow by default lint, so should we do this? Maybe we should only do this for `DisplayTarget::SourceCode`?
> Emit `'_` for lifetime generics in `HirDisplay`

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
https://github.com/rust-lang/rust/pull/112305
> internal: Bring back sysroot-abi feature

- .github/workflows/ci.yaml
Was wondering why this wasn't running on the subtree sync ...
> fix: Fix ci never running on nightly when proc-macro things change

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/hir-ty/src/tests/traits.rs
Given the following definitions:
```rust
trait Trait {
type A;
type B;
type C;
}
#[derive(Clone)]
struct S<T: Trait>
where
T::A: Send,
{
qualified: <T as Trait>::B,
shorthand: T::C,
}
```
we currently expand the derive macro to:
```rust
impl<T> Clone for S<T>
where
T: Trait + Clone,
T::A: Clone,
T::B: Clone,
T::C: Clone,
{ /* ... */ }
```
This does not match how rustc expands it. Specifically, `Clone` bounds for `T::A` and `T::B` should not be generated.
The criteria for associated types to get bound seem to be 1) the associated type appears as part of field types AND 2) it's written in the shorthand form. I have no idea why rustc doesn't consider qualified associated types (there's even a comment that suggests they should be considered; see rust-lang/rust#50730), but it's important to …
> fix: only generate trait bound for associated types in field types

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
> Fix unwrap on None in expanding format args

- crates/ide-assists/src/handlers/generate_function.rs
Part of #10122
In `generate_function` assist, when we infer the return type of async function we're generating, we should retrieve the type of parent await expression rather than the call expression itself.
> Infer return type for async function in `generate_function`

- docs/user/manual.adoc
rust-analyzer supports both `sysroot` and `sysroot_src` in `rust-project.json`. Document `sysroot` and show example values for both fields.
> Document the sysroot field in JsonProject

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/extract_type_alias.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/make.rs
- `add_missing_impl_members`
- `extract_type_alias`
As an additional requirement, these assists are also migrated to use the mutable AST API, since otherwise there would be overlapping `Indel` spans
> internal: Migrate some assists to use the structured snippet API

- crates/hir-ty/src/display.rs
- crates/hir-ty/src/mir/eval.rs
- crates/ide/src/hover/tests.rs
I hope this fixes the panic on recent nightly stdlib, but I didn't test it locally.
> Fix panic in displaying const trait objects

- crates/proc-macro-srv/src/server.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/flags.rs
This appears to fix #14959, but I've never contributed to rust-analyzer before and there were some things that confused me:
- I had to add the `fn byte_range` method to get it to build. This was added to rust in [April](https://github.com/rust-lang/rust/pull/109002), so I don't understand why it wasn't needed until now
- When testing, I ran into the fact that rust recently updated its `METADATA_VERSION`, so I had to test this with nightly-2023-05-20. But then I noticed that rust has its own copy of `rust-analyzer`, and the metadata version bump has already been [handled there](https://github.com/rust-lang/rust/commit/60e95e76d059e3bbeb19d819914df3bcf7684a82). So I guess I don't really understand the relationship between the code there and the code here.
> Add span to group.

- .github/workflows/autopublish.yaml
The workflow is currently failing because it's trying to publish 0.0.16, while the last version published was 0.0.149.
> autopublish: Offset version number

- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-db/src/path_transform.rs
A part of https://github.com/rust-lang/rust-analyzer/issues/13363
I expect to implement transformation of const params in a separate PR
Other assists and a completion affected:
- `generate_function` currently just ignores lifetimes and, consequently, is not affected
- `inline_call` and `replace_derive_with...` don't seem to need lifetime transformation
- `trait_impl` (a completion) is fixed and tested
> fix: implemeted lifetime transformation fot assits

- crates/rust-analyzer/src/to_proto.rs
Properly formats function documentation instead of returning it raw when responding to `SignatureHelpRequest`s.
I added a test in `crates/rust-analyzer/tests/slow-tests/main.rs` -- not sure if this is the best location given the relevant code is in `crates/rust-analyzer` or if it's possible to test in a less heavyweight manner.
Closes #14958
> Properly format documentation for `SignatureHelpRequest`s

- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/utils.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
Fixes #14534
When we use `PathTransform` for associated items of a trait, we have been feeding `SemanticsScope` for the trait definition to it as source scope. `PathTransform` uses the source scope to resolve paths in associated items to find which path to transform. In the course of path resolution, the scope is responsible for lowering `ast::MacroType`s (because they can be written within a path) using `AstIdMap` for the scope's `HirFileId`.
The problem here is that when an associated item is generated by a macro, the scope for the trait is different from the scope for that associated item. The former can only resolve the top-level macros within the trait definition but not the macro calls generated by those top-level macros. We need the latter to resolve such nested macros.
This PR …
> fix: derive source scope from syntax node to be transformed

- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/main_loop.rs
Some light testing suggests that this fixes the waiting on formatting popup in vscode when the project is still building (which is usually the way for me to encounter it, as r-a is either waiting or getting little resources causing the tasks to block formatting)
> internal: Give rustfmt jobs a separate thread

- editors/code/.vscodeignore
Enables Markdown injection introduced in #14866 but wasn't included in release due to the grammar file being ignored by `.vscodeignore`. I verified the fix by doing `vsce package` and installing it manually:
> fix: exclude Markdown injection grammar from .vscodeignore.

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
> fix: Use a more obscure hasher name in derive expansion

- crates/hir-ty/src/mir/borrowck.rs
> Add more log in "terminator is none" assert

- Cargo.lock
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/tests/simple.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/test-utils/src/fixture.rs
- crates/test-utils/src/minicore.rs
> Support `Pointee` trait

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-db/src/path_transform.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/13363
> fix: implement missing members doesn't transform const params and default types

- crates/hir-def/src/attr.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/db.rs
- crates/hir-def/src/dyn_map/keys.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/attrs.rs
Looking a bit into supporting use aliases and attributes better
> internal: Intern use and extern crate items like other items

- crates/ide-assists/src/handlers/inline_call.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
> Correctly handle inlining of async fn

- crates/vfs/src/vfs_path.rs
fix https://github.com/rust-lang/rust-analyzer/pull/15087#discussion_r1234544484
r? @matklad
> Fix VfsPath Display and Debug impls

- Cargo.lock
- Cargo.toml
- lib/README.md
See lib/README.md for justification
> Use lib crates from crates.io

- editors/code/package.json
- editors/code/rustdoc.markdown.injection.tmGrammar.json
Closes https://github.com/rust-lang/rust-analyzer/issues/15091
I tried making it work but it doesn't seem possible, as the `*` of the closing `*/` sequence gets eaten by the markdown grammar no matter what.
> Remove markdown injection for block comments

- crates/vfs/src/vfs_path.rs
Fixes https://github.com/rust-lang/rust-analyzer/pull/15097#discussion_r1236169290
> internal: Simplify `VfsPath` `fmt` impls

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15099
We probabnly need to look into this in a more general manner in the future now that we desugar more things
> Skip mutable diagnostics on synthetic bindings

- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
This PR ( fixes #14386 ) introduces a new IDE assist that generates a trait impl for a struct that delegates a field. This is a draft because the current `ide_db::path_transform::PathTransform` produces some unwanted results when it deals with extern crates, an example of which I attach as a GIF.
GIFs :  
1. A general case 
2. A case where `ide_db::path_transform::PathTransform` fails to correctly resolve a property ( take `Allocator` as an example ) to its full path, thus causing an error to occur. ( Not to even mention that resolving this causes another error `use of unstable library feature 'allocator_api'` to occur
> feature : assist delegate impl

- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/mir/eval.rs
- crates/ide/src/hover/tests.rs
The last byte in Little-Endian representation of negative integers start at 128 (Ox80) till 255 (OxFF). The comparison before the fix didn't check for 128 which made is_negative variable as false.
Potentially fixes #15096
> Change comparsion for checking if number is negative to include 128

- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/shim.rs
Increases passed tests from 48 to 49 :)
> Support manual impl of fn traits in mir interpreter

- crates/hir/src/has_source.rs
Fix https://github.com/rust-lang/rust-analyzer/issues/15088
> Add the comment why `HasSource::source()` returns `Option`

- editors/code/package.json
By documents, VSCode v1.74 or later activates the extension automatically according to other configurations.
See:
- https://code.visualstudio.com/api/references/activation-events#onLanguage
- https://code.visualstudio.com/docs/languages/identifiers
- https://code.visualstudio.com/api/references/activation-events#onCommand
- https://code.visualstudio.com/api/references/contribution-points#contributes.commands
> Clean up `activationEvents` field in vscode extension's package.json

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/tsconfig.json
Motivation
-----------
This change aims to make it easier to manage tsconfig by [`@tsconfig/strictest`](https://www.npmjs.com/package/@tsconfig/strictest) and intend to leave to create "ideal" rules about TypeScript's type checking.
Implementation
---------------
This change removes some duplicated rules defined in `@tsconfig/strictest` and add disabing some strict rules that fails with the current codebase.
> editor/code: Use `@tsconfig/strictest` to define type checking rules

- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
> Check Workspace Edit ResourceOps

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/tests/traits.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/test-utils/src/minicore.rs
rust-lang/rust#100386 changed the trait solver so that `Sized` is treated as coinductive trait, just like auto traits. This is now controlled by the perma-unstable `#[rustc_coinductive]` attribute (rust-lang/rust#108033), which this PR adds support for.
In practice, I don't think this matters much if at all. Currently we don't give chalk enough information so chalk cannot precisely (dis)prove `Sized` bounds.
> internal: support `#[rustc_coinductive]`

- crates/hir-def/src/body/tests.rs
- crates/hir-def/src/body/tests/block.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir/src/lib.rs
This PR fixes `self` and `super` path resolution with block modules involved.
Previously, we were just going up the module tree count-of-`super` times without considering block modules in the way, and then if we ended up in a block `DefMap`, we adjust "to the containing crate-rooted module". While this seems to work in most real-world cases, we failed to resolve them within peculiar module structures.
`self` and `super` should actually be resolved to the nearest non-block module, and the paths don't necessarily resolve to a crate-rooted module. This PR makes sure every `self` and `super` segment in paths are resolved to a non-block module.
> Fix `self` and `super` path resolution in block modules

- .github/workflows/metrics.yaml
- xtask/src/flags.rs
- xtask/src/metrics.rs
> ci(metrics): Run measurement functions in parallel

- crates/base-db/src/fixture.rs
- crates/base-db/src/input.rs
- crates/ide/src/moniker.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/test-utils/src/fixture.rs
Currently, there is no way to specify `CrateOrigin` of a file fixture ([this] might be a bug?). This PR adds `library` meta to explicitly specify the fixture to be `CrateOrigin::Library` and also makes sure crates that belong to a library source root are set `CrateOrigin::Library`.
(`library` isn't really the best name. It essentially means that the crate is outside workspace but `non_workspace_member` feels a bit too long. Suggestions for the better name would be appreciated)
Additionally:
- documents the fixture meta syntax as thoroughly as possible
- refactors relevant code
[this]: https://github.com/rust-lang/rust-analyzer/blob/4b06d3c595a75fd84bfce2b7f2861a913ed6e530/crates/base-db/src/fixture.rs#L450
> internal: add `library` fixture meta

- crates/hir-def/src/attr.rs
- crates/ide/src/runnables.rs
fix #15141
It is hacky, and it wouldn't work for e.g. this case:
```Rust
use ::core::prelude;
#[prelude::v1::test]
fn foo() {
}
```
But it works for the tokio case. We should use the name resolution here somehow, and after that we should probably also get rid of the ast based `test_related_attribute` function.
> Fix runnable detection for `#[tokio::test]`

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_attr_macro.rs
- crates/hir-expand/src/name.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/test-utils/src/minicore.rs
This is a nightly feature used in the standard library.
> Support #[derive_const(Trait)]

- editors/code/package-lock.json
- editors/code/package.json
This follows up https://github.com/rust-lang/rust-analyzer/pull/15151
`vsce` was renamed to `@vscode/vsce`. We should switch to it now.
- https://code.visualstudio.com/updates/v1_74#_extension-authoring
- https://www.npmjs.com/package/@vscode/vsce
> editor/code: Switch to `@vscode/vsce`

- crates/rust-analyzer/src/handlers/request.rs
Removes unnecessary unwraps that I have overlooked in #15101 ( fixes #15176 )
> Purge of unwraps

- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-expand/src/lib.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-expand/src/name.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/mutability.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/traits.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/pull_assignment_up.rs
- crates/ide-db/src/path_transform.rs
- crates/ide-db/src/search.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide-ssr/src/search.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tt_iter.rs
- crates/parser/src/shortcuts.rs
- crates/profile/src/tree.rs
- crates/rust-analyzer/src/bin/logger.rs
- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- crates/tt/src/buffer.rs
Because anonymous lifetimes are *super* cool.
More seriously, I believe anonymous lifetimes, especially those in impl headers, reduce cognitive load to a certain extent because they usually signify that they are not relevant in the signature of the methods within (or that we can apply the usual lifetime elision rules even if they are relevant).
> Use anonymous lifetime where possible

- crates/hir-ty/src/mir/eval.rs
> Disable mir interpreter for targets with different pointer size from host

- Cargo.toml
proc-macro-test is only used as a dev-dependency and isn't published to crates.io, so a version doesn't make sense. Having a version also breaks automatic publishing.
> Don't specify proc-macro-test version

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/tests/traits.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/test-utils/src/minicore.rs
Reverts #15125, addresses https://github.com/rust-lang/rust-analyzer/pull/15125#issuecomment-1615517893
I'll add the support again once I figure out the problem.
> Revert "Support `#[rustc_coinductive]`"

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
To re-enable this, use
"rust-analyzer.runnables.problemMatcher": [
"$rustc",
"$rust-panic"
],
setting.
closes: #14977
> feat: don't add panics to error jump list by default

- crates/hir-expand/src/db.rs
Removes some unnecessary extra work we are doing in proc-macro expansion, and more importantly `Arc` the result of the proc_macro_expand query, that way we can reuse the instance for the `macro_expand` query's result
> Shuffle some proc_macro_expand query things around

- crates/ide-diagnostics/src/lib.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/config.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/15131
Running this on r-a showed an 86mb memory increase, but that was without running it on the deps, will try that later when I don't need to use my pc.
> internal: Add analysis-stats flag to trigger some IDE features

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/import_map.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-completion/src/lib.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/items_locator.rs
There are several things in `hir_def::import_map` that are never used. This PR removes them and restructures the code. Namely:
- Removes `Query::name_only`, because it's *always* true.
- Because of this, we never took advantage of storing items' full path. This PR removes `ImportPath` and changes `ImportInfo` to only store items' name, which should reduce the memory consumption to some extent.
- Removes `SearchMode::Contains` for `Query` because it's never used.
- Merges `Query::assoc_items_only` and `Query::exclude_import_kinds` into `Query::assoc_mode`, because the latter is never used besides filtering associated items out.
Best reviewed one commit at a time. I made sure each commit passes full test suite. I can squash the first three commits if needed.
> Clean up `ImportMap`

- crates/hir-ty/src/autoderef.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
Fixes #15083
I believe this stopped working after https://github.com/alexkirsz/rust-analyzer/commit/e79747965197e362b375a7019571331b5be2394e
> Follow raw pointers in autoderef chain when resolving methods with custom receiver

- crates/hir-def/src/data/adt.rs
- crates/hir-def/src/expander.rs
We no longer need this since the introduction of the `ItemTree`
> internal: Remove `CfgExpander`

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/tests/traits.rs
Chalk has a dedicated IR for bounds on trait associated type: `rust_ir::InlineBound`. We have been failing to convert GATs inside those bounds from our IR to chalk IR. This PR provides an easy fix for it: properly take GATs into account during the conversion.
> Support GATs in bounds for associated types

- crates/parser/src/grammar/generic_args.rs
- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/parser/inline/err/0021_recover_from_missing_assoc_item_binding.rast
- crates/parser/test_data/parser/inline/err/0021_recover_from_missing_assoc_item_binding.rs
- crates/parser/test_data/parser/inline/err/0022_recover_from_missing_const_default.rast
- crates/parser/test_data/parser/inline/err/0022_recover_from_missing_const_default.rs
> Recover from missing associated items and generic const defaults

- crates/ide-diagnostics/src/handlers/useless_braces.rs
Disable `remove unnecessary braces` diagnostic if the there is a `self` inside the bracketed `use`
Fix #15191
> Disable remove unnecessary braces diagnotics for self imports

- crates/ide-assists/src/handlers/generate_trait_from_impl.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
fixes #14987 . As the name suggests this assist is used to generate traits from inherent impls while adapting the original impl to fit to the newly generated trait. I made some decisions regarding when the assist should be applicable. These are surely open to discussion. I looking forward to any feedback.
> assist : generate trait from impl

- editors/code/src/ast_inspector.ts
- editors/code/src/bootstrap.ts
- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/config.ts
- editors/code/src/debug.ts
- editors/code/src/dependencies_provider.ts
- editors/code/src/diagnostics.ts
- editors/code/src/nullable.ts
- editors/code/src/run.ts
- editors/code/src/snippets.ts
- editors/code/src/tasks.ts
- editors/code/src/toolchain.ts
- editors/code/src/undefinable.ts
- editors/code/tests/unit/settings.test.ts
- editors/code/tsconfig.json
This enables typescript's these option:
- [`--noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess)
- This checks whether indexed access is not `null` (or `undefined`) strictly just as like checking by `std::option::Option::unwrap()`.
- [`--noPropertyAccessFromIndexSignature`](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature)
- This disallows `bar.foo` access if the `bar` type is `{ [key: string]: someType; }`.
----
Additionally, to enable `--noUncheckedIndexedAccess` easily, this pull request introduces [option-t](https://www.npmjs.com/package/option-t) as a dependency instead of defining a function in this repository like `unwrapUndefinable()` .
I'll remove it and define them byself if our dependency management policy is …
> editor/code: Enable `--noUncheckedIndexedAccess` & `--noPropertyAccessFromIndexSignature` ts option

- crates/hir-expand/src/name.rs
- crates/hir-ty/src/infer/expr.rs
- crates/ide-diagnostics/src/handlers/unresolved_field.rs
I don't think reporting ``"no field `[missing name]` on type `SomeType`"`` makes much sense because it's a syntax error rather than a semantic error. We already report a syntax error for it and I find it sufficient.
> Don't show `unresolved-field` diagnostic for missing names

- editors/code/src/config.ts
Regressed after https://github.com/rust-lang/rust-analyzer/pull/13975 (whoops).
> fix: Indent after pressing enter on a blank line

- crates/ide-assists/src/handlers/expand_glob_import.rs
> assist : add enum to glob_import_expand

- crates/hir-def/src/db.rs
- crates/hir-def/src/lang_item.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/shim.rs
- crates/hir-ty/src/mir/eval/shim/simd.rs
- crates/hir-ty/src/mir/eval/tests.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir/src/lib.rs
- crates/hir/src/source_analyzer.rs
This enables interpreting functions with deep stack + profiling. I also applied some changes to make it faster based on the profiling result.
> Implement recursion in mir interpreter without recursion

- crates/hir-ty/src/display.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir/src/lib.rs
> Use debug impl in rendering const eval result

- crates/ide-assists/src/handlers/extract_function.rs
Extracting a match arm value that has type unit into a function, when a
comma already follows the match arm value, results in an invalid (syntax
error) semicolon added between the newly generated function's generated
call and the comma.
Running this extraction
```rust
fn main() {
match () {
_ => $0()$0,
};
}
```
would lead to
```rust
fn main() {
match () {
_ => fun_name();,
};
}
fn fun_name() {
}
```
This happens because when there is no comma, rust-analyzer would simply
add the comma and wouldn't even try to evaluate whether it needs to add
a semicolon. But when the comma is there, it proceeds to evaluate
whether it needs to add a semicolon and it looks like the evaluation
logic erroneously ignores the possibility that we're in a match arm.
IIUC it never makes sense to add a semicolon …
> Stop inserting semicolon when extracting match arm

- crates/ide-db/src/helpers.rs
- crates/ide/src/lib.rs
- crates/ide/src/static_index.rs
- crates/ide/src/view_memory_layout.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
**Motivation**: rustc by default doesn't enforce a particular memory layout, however it can be useful to see what it is doing under the hood, or if using a particular repr ensure it is behaving how you want it to. This command provides a way to visually explore memory layouts of structures.
**Example**:
this structure:
```rust
struct X {
x: i32,
y: u8,
z: Vec<bool>,
w: usize,
}
```
produces this output:
**Work yet to be done**:
- tests (see below)
- html is mildly janky (see below)
- enums and unions are viewed flatly, how should they be represented?
- should niches be marked somehow?
This was written for my own use, and the jank is fine for me, but in its current state it is probably not ready to merge mostly because it is missing tests, and also because the code quality is not great. …
> Feature: Add a memory layout viewer

- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
> Fix missing terminator in pattern matching of consts

- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_derive.rs
- crates/ide-assists/src/handlers/wrap_return_type_in_result.rs
- crates/ide-db/src/source_change.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
Continuing from #14979
- `generate_derive`
- `wrap_return_type_in_result`
- `generate_delegate_methods`
As a bonus, `generate_delegate_methods` now generates the function and impl block at the correct indentation 🎉.
> internal: Migrate more assists to use the structured snippet API

- editors/code/src/commands.ts
- editors/code/src/util.ts
- editors/code/tests/unit/index.ts
- editors/code/tsconfig.json
This enables TypeScript's [`--useUnknownInCatchVariables`](https://www.typescriptlang.org/tsconfig#useUnknownInCatchVariables).
> editor/code: Enable TypeScript's `--useUnknownInCatchVariables` option 

- Cargo.lock
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/shim.rs
- crates/hir-ty/src/mir/eval/shim/simd.rs
- crates/hir-ty/src/mir/eval/tests.rs
And fix some simd intrinsic bugs and add a memory limit to prevent huge allocations from breaking the main process.
> Support getrandom syscall

- lib/lsp-server/src/msg.rs
this is a trivial PR meant to address issue #15197: the 'Content-Length' header field should probably be treated as case-insensitive
> [lsp-server] Ignore 'Content-Length' case

- editors/code/.eslintrc.js
- editors/code/src/ast_inspector.ts
- editors/code/src/bootstrap.ts
- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/debug.ts
- editors/code/src/dependencies_provider.ts
- editors/code/src/diagnostics.ts
- editors/code/src/main.ts
- editors/code/src/persistent_state.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
- editors/code/src/util.ts
- editors/code/tests/unit/launch_config.test.ts
- editors/code/tests/unit/runnable_env.test.ts
- editors/code/tests/unit/settings.test.ts
This pull requests enables new lint rule to sorts the style to import types/symbols.
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md
- https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-import-type-side-effects.md
> editor/code: Sort the style to import types

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
- crates/ide-assists/src/handlers/fix_visibility.rs
- crates/ide-assists/src/handlers/promote_local_to_const.rs
- crates/syntax/src/ast/edit_in_place.rs
Continuing from #15231
- `add_missing_match_arms`
- `fix_visibility`
- `promote_local_to_const`
The `add_missing_match_arms` changes are best reviewed commit-by-commit since they're relatively big changes compared to the rest of the commits.
> internal: Migrate assists to the structured snippet API, part 3

- .editorconfig
We uses `indent_size = 4` for almost files in this repository. This sorts the config to it.
> Set .editorconfig default indent size to `4`

- crates/hir-ty/src/consteval/tests.rs
The test for MIR execution limit accounts for ~2/3 of total execution time of non-slow hir-ty tests. It significantly slows down edit-and-run-test type of workflow. Can we mark it as a slow test?
> Mark test for MIR execution limit as slow test

- crates/hir-ty/src/mir.rs
When trying to use the RA crate, I am unable to access the fields in `hir_def::mir::Terminator`.
I don't see any reason, why these should be private, especially as the fields of `hir_def::mir::Statement` are `pub`.
I am not sure if the fields in `hir_def::mir::SwitchTargets` should be made `pub` too, but at least they are read-accessible via some public methods..
Sorry if I missed something, this is my first PR.
> Make fields of mir::Terminator public

- .github/workflows/metrics.yaml
Metrics CI is failing because of a function that was stabilized in 1.70. So for some reason, it's trying to use an older toolchain i seems though I don't understand why it randomly started complaining about that.
Also reformatted the file.
> Default to stable toolchain for metrics workflow

- crates/hir-ty/src/mir.rs
First of all I still have no idea how MIR works but #15143 has been an issue that constantly made RA crash so I have been looking for a way to make RA stop panicking. I have zero claims that what I want to merge has any sense or is correct :smile:  but there isn't any more panicking. Even if it is wrong may this be at least a step towards resolving this issue.   
As is customary this PR fixes #15143
> Handle TyAlias in projected_ty

- crates/rust-analyzer/src/cli/flags.rs
It's missing a `>`, so
```
> rust-analyzer ssr '''$a.foo($b) ==> bar($a, $b)'''
can't parse `rule`, Parse error: Cannot find delimiter `==>>`
```
happens.
> Fix rust-analzyer ssr help message

- crates/hir-ty/src/mir.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
> Normalize type alias in projected_ty

- crates/proc-macro-api/src/version.rs
rust-lang/rust#113695 makes the dylib metadata uncompressed for perf reasons. This commit allows reading both the current compressed and future uncompressed dylib metadata.
> internal: Support reading uncompressed proc macro metadata

- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
In https://github.com/rust-lang/rust-analyzer/pull/15118, I enabled following raw pointer derefs when considering self type candidates. However, I also inadvertently enabled it for receiver type candidates, which is invalid and causes false positives (see new test).
> Don't follow raw pointer derefs when considering method receiver candidates

- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/layout/adt.rs
- crates/hir-ty/src/layout/tests.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/tests.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/lib.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
We need to do either this or get rid of trait environment in `normalize_ty`. Let's go with this for now.
> Pass `TraitEnvironment` into `layout_ty` and `const_eval`

- editors/code/src/debug.ts
This PR improves DX (developer experience) when installing the VS Code extension for the first time. When doing so and trying to debug a Rust file, we get an error notification that either CodeLLDB or C++ extension/debugger should be installed (see image below).
<div align="center">
</div>
The PR enhances the links in the given notification and upon clicking instead of opening the Web page of the extension it installs the extension immediately, without the need to leave the editor.
Note: the feature needs to be refined, maybe an "install in progress" message or something similar, I left that for you guys to decide and implement. I think it also possible to first open the sidebar, open the Extensions tab, then run the extension installation command which would make it more user-friendly. …
> editor/code: [DX] Use notification command links for debugger installation

- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
Fixes #15319
Although we have been collecting the diagnostics for inner items within function bodies, we were discarding them and never reported to the users. This PR makes sure that they are all reported and additionally collects the diagnostics for inner items within const bodies, static bodies, and enum variant bodies.
> Report `incorrect-ident-case` for inner items

- crates/project-model/src/cargo_workspace.rs
We don't need to allocate a `Vec`, nor do we need sorting.
> internal: optimize `DepKindInfo` -> `DepKind` conversion

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/traits.rs
fix #15321 
I'm not sure if we should do this, or add a normalize in the beginning of `infer_expr_inner`, or somewhere else. r? @lowr
> Normalize expected ty in call arguments

- crates/ide-assists/src/handlers/change_visibility.rs
this pr limits the `change_visibility` assist to applicable items. top level items in this context means items that are not nested within `fn`s or `trait`s.
now
```rs
fn foo {
// assists on this `struct` keyword won't include `change_visibility`
struct Bar {} 
}
trait Foo {
// same with the `fn` here
fn bar();
}
```
> limit `change_visibility` assist to applicable items

- .github/workflows/ci.yaml
- editors/code/package.json
This do the thing I mentioned in https://github.com/rust-lang/rust-analyzer/pull/15265#issuecomment-1634424385
This aims to improve CI status check more readable.
I tried to use [`jobs.<job_id>.if`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) to make the configuration
more shortly once.
But it could not fire the `end-success` or `end-failure` status if some jobs in the workflow were skipped. This causes an integration problem with bors.
By their reasons, this patch still uses `jobs.<job_id>.steps[*].if`.
---
To do this change, we reorganize npm-script.
| previous           | after                                  |
|--------------------|----------------------------------------|
| `npm run lint`     | `npm run lint && npm run …
> editor/code: Break down CI steps to know what is failing easily

- editors/code/package-lock.json
- editors/code/package.json
I previously mentioned [in a comment](https://github.com/rust-lang/rust-analyzer/pull/15265#issuecomment-1633240290) that folks at my employer are on 1.78, but I was incorrect: people are on 1.75. I know this is outside the standard version support policy, but I haven't seen any of the new features in VS Code be used in rust-analyzer. The most applicable feature in those three versions of VS Code that I can find [is lazily resolving code actions](https://code.visualstudio.com/updates/v1_78#_resolve-code-action-commands-in-resolvecodeaction), but it doesn't seem like rust-analyzer is making use of that feature.
(I'll be posting a PR that adds support for `$saved_file` within the next day, so feel free to bump the minimum VS Code version back to 1.78 if/when that PR lands. This just makes …
> vscode: change minimum VS Code version to 1.75 from 1.78

- docs/user/manual.adoc
- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/run.ts
This PR adds an option to specify runnables `env` per platform (win32, linux, etc.):
```
{
"rust-analyzer.runnables.extraEnv": [
{
"platform": "win32",
"env": {
"SCITER_BIN_FOLDER": "C:\\Projects\\3rd\\sciter-js-sdk\\bin\\windows\\x64",
}
},
{
"platform":["linux","darwin"],
"env": {
"SCITER_BIN_FOLDER": "/home/vit/Projects/sciter/sciter-js-sdk/bin/linux/x64",
}
}
]
}
```
> Runnable env per platform

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/cast.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir-ty/src/tests/simple.rs
This PR reenables `Expectation::Castable` (previous attempt at #14104, reverted by #14120) and implements type cast checks, which enable us to infer a bit more.
Castable expectations are relatively weak -- they only influence the inference if we cannot infer the types by other means. Therefore, we need to defer possible type unification with the casted type until we type check all expressions of the body. This PR adds a struct and slots in `InferenceContext` for the deferred cast checks (c.f. [`CastCheck`] in `rustc_hir_typeck`).
I only implemented the bits that affect the inference result. It should be possible to return type adjustments for well-formed casts and report diagnostics for invalid casts, but I'm leaving them for future work for now.
Fixes #11571
Fixes #15246
[`CastCheck`]: …
> Properly infer types with type casts

- crates/hir-ty/src/display.rs
- crates/hir-ty/src/tests/display_source_code.rs
- crates/ide-assists/src/handlers/generate_function.rs
Fixes #15346
The second commit is an unrelated change. I can remove it if not desired.
> Show anonymous fn def type as a fn pointer in source code

- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/shim.rs
- crates/hir-ty/src/mir/lower.rs
And some other minor changes.
Clone for tuple is not implemented in the std and it is magically implemented by the compiler, so we need this.
> Add manual implementation of clone for tuples in mir interpreter

- crates/hir-def/src/lib.rs
- crates/hir-expand/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15327
> fix: Do not create fn macro calls with non-fn expanders

- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/mbe/src/expander.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/tt/src/lib.rs
Fixes #14367
There are roughly two types of paths: paths in expression context, where a separator `::` between an identifier and its following generic argument list is mandatory, and paths in type context, where `::` can be omitted.
Unlike rustc, we need to transform the parsed fragments back into tokens during transcription. When the matched path fragment is a type-context path and is transcribed as an expression-context path, verbatim transcription would cause a syntax error.
This PR fixes up path fragments by inserting `::` to make sure they are syntactically correct in all contexts. Note that this works because expression-context paths are a strict superset of type-context paths.
> Fixup path fragments upon MBE transcription

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/db.rs
- crates/ide-diagnostics/src/handlers/macro_error.rs
- crates/parser/src/grammar.rs
- crates/parser/src/lib.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/lib.rs
- crates/syntax/src/tests/ast_src.rs
Prior to this, we were just parsing it as an expression which works fine for `()` and `[]` calls as those are tuple and array expressions respectively, but if tails for `{}` calls which with my recent changes reported errors for such eager macro invocations.
> fix: Expand eager macros to delimited comma separated expression list

- crates/hir-expand/src/eager.rs
Like the other ones, this also results in a panic when writing out `include!`  due to the missing tt
> fix: Remove another faulty unwrap (expect)

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/utils.rs
fixes  #14957 . I have two questions :
1.  I am definitely looking for a more idiomatic way for the things I added in `crates/ide-assists/src/utils.rs`. See `FIXME` in that file.
2. Would it be actually better to change `DefaultMethods` to something like
```rust
enum DefaultMethods {
Only( IgnoreHidden ( bool ) ) ,
None
}
```
instead of adding a boolean to every function that calls `crates/ide-assists/src/utils.rs::filter_assoc_items`
> bugfix :  skip doc(hidden) default members

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
- crates/proc-macro-srv/src/server.rs
- crates/tt/src/lib.rs
Fixes #15310
We shouldn't provide the assist when we fail to find the original match arm list.
Note that this PR will temporarily make the assist not applicable when attribute macro operates on the match expression in question, just like the case in #15310, for most of the current stable toolchain users. This is because the sysroot-abi proc-macro-srv on the current stable [discards] spans for `Group` delimiters in some code paths, which the popular `proc-macro2` crate almost always calls, and it makes the identity of match arm list's brackets lost, leading to the upmapping failure. This has been fixed by #14960, which will land in the next stable, 1.71.
[discards]: https://github.com/rust-lang/rust/blob/8ede3aae28fe6e4d52b38157d7bfe0d3bceef225/src/tools/rust-analyzer/crates/proc-macro-srv/ …
> Don't provide `add_missing_match_arms` assist when upmapping match arm list failed

- crates/ide-assists/src/tests.rs
- crates/ide-db/src/source_change.rs
- crates/ide-diagnostics/src/tests.rs
- crates/ide/src/lib.rs
- crates/ide/src/rename.rs
- crates/ide/src/ssr.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/to_proto.rs
Since we know exactly where snippets are, we can transparently escape snippet bits to the exact text edits that need it, and not have to do it for anything other text edits.
Also will eventually fix #11006 once all assists are migrated. This comes as a side-effect of text edits that don't have snippets get marked as having no insert formatting at all.
> internal: Defer structured snippet rendering to allow escaping snippet bits

- triagebot.toml
cc https://github.com/rust-lang/triagebot/pull/1704 https://github.com/rust-lang/rust/pull/114157
> Add triagebot no-merges config

- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-assists/src/handlers/expand_glob_import.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/extract_module.rs
- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-assists/src/handlers/move_const_to_impl.rs
- crates/ide-assists/src/handlers/remove_unused_imports.rs
- crates/ide-assists/src/handlers/replace_named_generic_with_impl.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-db/src/search.rs
- crates/ide-ssr/src/search.rs
- crates/ide/src/highlight_related.rs
- crates/ide/src/references.rs
- crates/ide/src/runnables.rs
- crates/syntax/src/ast/edit_in_place.rs
This resolves the most important part of #5131. I needed to make a couple of cosmetic changes to the search infrastructure to do this.
A few open questions:
* Should imports that don't resolve to anything be considered unused? I figured probably not, but it would be a trivial change to make if we want it.
* Is there a cleaner way to make the edits to the use list?
* Is there a cleaner way to get the list of uses that intersect the current selection?
* Is the performance acceptable? When testing this on itself, it takes a good couple seconds to perform the assist.
* Is there a way to hide the rustc diagnostics that overlap with this functionality?
> Added remove unused imports assist

- crates/hir-def/src/attr.rs
- crates/hir-def/src/child_by_source.rs
- crates/hir-def/src/db.rs
- crates/hir-def/src/dyn_map/keys.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/diagnostics.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/attrs.rs
- crates/hir/src/semantics/source_to_def.rs
cc https://github.com/rust-lang/rust-analyzer/issues/14079
> Name change Import to Use in hir-def, add unused placeholder variants for UseId

- editors/code/src/ctx.ts
Previously, clicking 'rust-analyzer' would stop the server entirely. This was easy to do accidentally, and then the user has to wait for the server to start up again.
> Set the default status bar action to openLogs

- crates/ide/src/moniker.rs
- crates/rust-analyzer/src/cli/scip.rs
SCIP requires symbols to be unique, but multiple functions may have a parameter with the same name. Qualify parameters according to the containing function.
> SCIP: Qualify parameters by the containing function

- crates/ide-assists/src/handlers/generate_delegate_trait.rs
Fixes #15388
This is untested and purely mechanical, maybe some of those `unwrap`s actually made sense, but it probably doesn't hurt to avoid them.
> fix: Remove unwraps from "Generate delegate trait"

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/expander.rs
- crates/ide-assists/src/handlers/inline_macro.rs
- crates/parser/src/grammar/items.rs
Reduces the amount of type related errors one gets when proc macro expansion is disabled.
> internal: Turn unresolved proc macro expansions into missing expressions

- crates/ide-assists/src/handlers/generate_default_from_new.rs
- crates/ide-assists/src/tests/generated.rs
Also don't provide the assist when the `Default` trait can't be found.
Part of #15398
> Don't provide `generate_default_from_new` when impl self ty is missing

- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/mbe/src/syntax_bridge.rs
- crates/parser/src/shortcuts.rs
- crates/syntax/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15403
> fix: Fix float parser hack creating empty NameRef tokens

- crates/hir-def/src/generics.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/item_tree/tests.rs
- crates/ide/src/hover/tests.rs
Records attributes on generic parameters in the item tree and filters out generic parameters disabled by `#[cfg]`s in `generic_params_query`.
Closes #11756
> Handle `#[cfg]`s on generic parameters

- lib/lsp-server/src/stdio.rs
Remove an unsafe unwrap that can cause crashes if the value is a `SendError`.
This is my first PR on this repo, please let me know if there is anything I can improve or details I can provide.
> internal: convert unwrap to except and add a debug log 

- crates/ide-assists/src/handlers/extract_function.rs
> fix: don't use control flow when extracted fn contains tail expr of original fn

- crates/hir-def/src/resolver.rs
- crates/hir/src/attrs.rs
- crates/hir/src/lib.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/doc_links/tests.rs
Fixes #15331
Also removes `Resolver::resolve_module_path_in_trait_assoc_items()` and reimplements it in hir with other `Resolver` methods to decouple things a bit.
> Support doc links that resolve to fields

- crates/hir-ty/src/display.rs
- crates/ide/src/hover/tests.rs
Currently they are formatted in the internal `Trait<Self = Type>::Assoc` forms where `hir_ty::TypeRef` is formatted, like hover.
There is no test of `TypeRef::hir_fmt` in crate `hir-ty` (verified by replacing it with a `panic!()`), most tests are about inference and printing the real `Ty` instead of `TypeRef`. So I added the test in `ide::hover`.
> Display fully qualified associated types correctly

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> add check.ignore to list cargo check diagnostics to ignore (dead_code, unused_imports, ...)

- crates/hir-ty/src/builder.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir/src/lib.rs
I firmly believe that we should generally use `cast()` instead of interning `GenericArgData` to construct `GenericArg` because it's less verbose and more readable.
> internal: use `Cast::cast()` instead of explicit interning

- crates/ide-assists/src/handlers/convert_named_struct_to_tuple_struct.rs
Replaces `unwrap`s with `?` for the mentioned assist.
> internal : Deunwrap convert_named_struct_to_tuple_struct

- crates/hir-def/src/item_tree.rs
- crates/rust-analyzer/Cargo.toml
lsp-types published a new patch version that breaks semver with the proposed feature set (this is intended and documented), we unfortunately forgot to specify the patch version for the pinned version so this breaks us.
> Fix pinned version of lsp-types

- crates/hir-ty/src/infer/unify.rs
This saves ~20ms in the highlihting bench on my machine
```
284ms - highlight
150ms - infer:wait @ per_query_memory_usage
150ms - infer_query
0   - PerNs::filter_visibility (436 calls)
0   - crate_def_map:wait (336 calls)
2ms - deref_by_trait (909 calls)
0   - generic_params_query (1 calls)
0   - inherent_impls_in_block_query (1 calls)
107ms - resolve_obligations_as_possible (17013 calls)
0   - trait_solve::wait (1017 calls)
0   - PerNs::filter_visibility (13 calls)
17ms - Semantics::analyze_impl (19 calls)
0   - SourceBinder::to_module_def (30 calls)
0   - attrs_query (6 calls)
0   - classify_lifetime (1 calls)
0   - classify_lifetime_ref (4 calls)
35ms - classify_name (28 calls)
54ms - classify_name_ref (452 calls)
0   - crate_def_map:wait (375 calls)
7ms - descend_into_macros (776 …
```
> Preserve `resolve_obligations_as_possible` temporary allocation across calls

- crates/ide-db/src/symbol_index.rs
- crates/ide/src/navigation_target.rs
It is a bit confusing that this apparently did not filter every trait out though...
Closes https://github.com/rust-lang/rust-analyzer/issues/15444
Closes https://github.com/rust-lang/rust-analyzer/issues/15200
> fix: Fix `only_types` config filtering out traits from world symbols

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/parser/src/grammar.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15437
> fix: Fix parser being stuck in eager macro inputs

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/ide-ssr/src/matching.rs
- crates/ide/src/signature_help.rs
Currently the receiver type is copied from AST instead re-formatting through `HirDisplay`. Macro generated functions seem to have no spaces and their signature help are rendered like `fn foo(&'amutself)` instead of `fn foo(&'a mut self)`.
> Fix signature help of methods from macros

- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/type_pos.rs
When determining completions for generic arguments, suggest only types or only constants if the corresponding generic parameter is a type parameter or constant parameter.
Closes #12568
> Suggest type completions for type arguments and constant completions for constant arguments

- crates/ide-assists/src/handlers/apply_demorgan.rs
- crates/syntax/src/ast/make.rs
fixes #15239 , #15240 . This PR is a rewrite of the DeMorgan assist that essentially rids of all the string manipulation and modifies syntax trees to apply demorgan on a binary expr. The main reason for the rewrite is that I wanted to use `Expr::needs_parens_in` method to see if the expr on which the assist is applied would still need the parens it had once the parent expression's operator had equal precedence with that of the expression. I used `.clone_(subtree|for_update)` left and right and probably more than I should have, so I would also be happy to hear how I could have prevented redundant cloning.
> internal : rewrite DeMorgan assist

- crates/hir-def/src/generics.rs
- crates/hir-def/src/hir/type_ref.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/path_transform.rs
- crates/ide-db/src/use_trivial_constructor.rs
- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/parser/inline/err/0022_recover_from_missing_const_default.rast
- crates/parser/test_data/parser/inline/ok/0188_const_param_default_path.rast
- crates/parser/test_data/parser/inline/ok/0199_const_param_default_expression.rast
- crates/parser/test_data/parser/inline/ok/0200_const_param_default_literal.rast
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/make.rs
To achieve this, I've made `hir::ConstParamData` store the default values
> the "add missing members" assists: implemented substitution of default values of const params

- editors/code/package.json
- editors/code/src/bootstrap.ts
- editors/code/src/commands.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
- editors/code/src/util.ts
Closes https://github.com/rust-lang/rust-analyzer/issues/15440
cc https://github.com/rust-lang/rust-analyzer/issues/13208
> Add status bar button to toggle check on save state
