- editors/code/src/util.ts
The default value for maxBuffer is 1 MiB[1]. If the discover project command returns stdout or stderr that is greater than 1 MiB, the extension would error with "RangeError: stderr maxBuffer length exceeded".
Set the default value for maxBuffer to 10 MiB for project discovery.
[1] https://nodejs.org/api/child_process.html#child_processexeccommand-options-callback
> Increase the buffer size for discover project command

- crates/hir/src/display.rs
- crates/ide/src/hover/tests.rs
It's just a kind of a postscriptum for [my last PR](https://github.com/rust-lang/rust-analyzer/pull/15179) adding default values of const generics to `hir::ConstParamData`. Here I patch other pieces of code which used to ignore const default values and which I managed to find (you're welcome to show me more)
> fix: start hovering default values of generic constants

- crates/hir-expand/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-db/src/helpers.rs
- crates/ide-db/src/search.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/extend_selection.rs
- crates/ide/src/goto_declaration.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/goto_type_definition.rs
- crates/ide/src/highlight_related.rs
- crates/ide/src/hover.rs
- crates/ide/src/lib.rs
- crates/ide/src/moniker.rs
- crates/ide/src/references.rs
- crates/ide/src/signature_help.rs
- crates/ide/src/syntax_highlighting.rs
The offset is unused for now as we can't map by spans yet but it will be required for https://github.com/rust-lang/rust-analyzer/issues/11260 to work once the token map has been changed to record spans
> internal: Add offset param to token descending API

- crates/hir-def/src/body/tests/block.rs
- crates/hir-def/src/find_path.rs
- crates/hir-def/src/import_map.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/macro_expansion_tests/mod.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/nameres/tests.rs
- crates/hir-def/src/nameres/tests/globs.rs
- crates/hir-def/src/nameres/tests/incremental.rs
- crates/hir-def/src/nameres/tests/macros.rs
- crates/hir-def/src/nameres/tests/mod_resolution.rs
- crates/hir-def/src/nameres/tests/primitives.rs
- crates/hir-def/src/per_ns.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-db/src/lib.rs
This records the import items definitions come from in the module scope (as well as what an import resolves to in an ItemScope). It does ignore glob imports as thats a lot more work for little to no gain, glob imports act as if the importing items are "inlined" into the scope which suffices for almost all use cases I believe (to my knowledge, attributes on them have little effect).
There is still a lot of work needed to make this available to the IDE layer, but this lays out the ground work for havin IDE layer support.
cc https://github.com/rust-lang/rust-analyzer/issues/14079
> internal: Record import origins in ItemScope and PerNS

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/import_map.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/per_ns.rs
- crates/hir/src/attrs.rs
- crates/ide-completion/src/tests/flyimport.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/9197 and https://github.com/rust-lang/rust-analyzer/issues/9911
Turns out while https://github.com/rust-lang/rust-analyzer/pull/15472 didn't give access to the import stuff to the IDE layer, these can be fixed already since they use the import map which works in the hir-def crate 🎉
> fix: Fix auto-import (and completions) importing `#[doc(hidden)]` items

- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/per_ns.rs
- crates/hir-def/src/src.rs
- crates/hir/src/attrs.rs
- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
Fixes https://github.com/rust-lang/rust-analyzer/issues/7938
> feat: Record import aliases in symbol index

- crates/ide-assists/src/handlers/generate_derive.rs
#15398 subtask 1. Since the editing closure has arms, I did something *experimental* ( in this case just a clever term for bad code ) to bypass creating an `Option` but I am ready to change this.
> internal: Deunwrap generate_derive

- Cargo.lock
- Cargo.toml
- lib/lsp-server/Cargo.toml
serde 1.0.172 and up rely on opaque non-reproducible binary blobs to function, explicitly not providing a library-level opt-out.
This is problematic for two reasons:
- directly, unauditable binary blobs are a security issue.
- indirectly, it becomes much harder to predict future behaviors of the crate.
As such, I am willing to go on a limb here and forbid building rust-analyzer with those versions of serde. Normally, my philosophy is to defer the choice to the end user, but it's also a design constraint of rust-analyzer that we don't run random binaries downloaded from the internet without explicit user's concent.
Concretely, this upper-bounds serde for both rust-analyzer workspace, as well as the lsp-server lib.
See https://github.com/serde-rs/serde/issues/2538 for wider context.
> fix: avoid problematic serde release

- crates/hir-def/src/resolver.rs
- crates/hir/src/semantics.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/extern_crate.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
Hi, this is a draft PR for #13002. 
I have basic completion working as well as a filter for existing extern crate imports in the same file. This is based on the tests, I have not actually tried this in an editor. Before going further I think this is a good point to stop and get feedback on the
structure and approach I have taken so far. Let me know what you think :)
I will make sure to add more tests, rebase commits and align with the code style guidelines before submitting a final version.
A few specific questions :
1. Is there a better way to check for matching suggestions? right now I just test if an extern crate name starts with the current 
user input.
2. Am I creating the `CompletionItem` correctly? I noticed that `use_.rs` invokes a builder where as I do not.
3. When checking for …
> feat: Implement extern crate completion

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
I highly doubt that `check.invocationLocation` only has an effect if `cargo.buildScripts.overrideCommand` is set -- looks like a copy-paste mistake from `buildScripts.invocationLocation` to me.
> fix help text for rust-analyzer.check.invocation{Strategy,Location}

- Cargo.lock
- Cargo.toml
- lib/lsp-server/Cargo.toml
Serde no longer uses blobs as of
https://github.com/serde-rs/serde/pull/2590
As such, there's no longer need for us to pin it.
Note that this doesn't upgrade serde version we use: I am fairly confident that the blobs are already there are fine, and now I am fairly confident that all future versions of serde will be fine as well.
> internal: unpin serde

- crates/rust-analyzer/src/cli/scip.rs
Previously this was hard coded to "0.1". The SCIP protocol allows this to be an arbitrary string:
```
message ToolInfo {
// Name of the indexer that produced this index.
string name = 1;
// Version of the indexer that produced this index.
string version = 2;
// Command-line arguments that were used to invoke this indexer.
repeated string arguments = 3;
}
```
so use the same string reported by `rust-analyzer --version`.
> SCIP: Report the correct version of rust-analyzer in the metadata

- crates/proc-macro-test/build.rs
When cross compiling macos → dragonfly the dist build fails in the proc-maro-test-impl crate with the following error:
`ld: unknown option: -z\nclang: error: linker command failed with exit code 1 (use -v to see invocation)`
This appears to be a wart stemming from using an Apple host for cross compiling.  Passing the target along to cargo allows it to pick up a linker that it understands and DTRT.
> proc-macro-test: Pass target to cargo invocation

- crates/hir-def/src/body/lower.rs
- crates/ide-diagnostics/src/handlers/undeclared_label.rs
> fix: diagnostics for 'while let' loop with label in condition

- crates/ide-diagnostics/src/handlers/mutability_errors.rs
- crates/ide-diagnostics/src/handlers/useless_braces.rs
> Respect `#[allow(unused_braces)]`

- crates/flycheck/src/lib.rs
This PR has two commits, so it's probably easier to review them separately:
(1) Rename `CargoHandle` to `CommandHandle`, as the command may not be a cargo command.
(2) Logging should format the current command, rather than calling `check_command()` again. This ensures that any later configuration changes don't cause us to log incorrect information.
> Fix cargo handle logging in flycheck

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/main_loop.rs
The main thread is still occasionally blocking on something and I am unsure what the cause might be. This will hopefully help somewhat
> Shuffle some locking around

- crates/hir-ty/src/mir/borrowck.rs
- crates/hir/src/lib.rs
Judging from a profile sent by a friend, the borrowck query took up a significant amount of time in their project which might be the cause for some unresponsiveness as nothing in the mir stack currently unwinds on cancellation
> Add a few more `db.unwind_if_cancelled()` calls

- .github/workflows/metrics.yaml
- xtask/src/flags.rs
- xtask/src/metrics.rs
The previous versions were removed hence the updates. The metric results for the changed ones are disconnected now as to not muddle things up.
I think it's worth it for us to occasionally bump the `rustc-perf` checkout, as it allows us to include more interesting new targets.
Notably, the newer diesel is 3 times as fast to analyze as the one of the current checkout.
> Bump `rustc-perf` checkout for metrics, replace webrender, diesel and ripgrep with newer versions

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/tests/slow-tests/tidy.rs
- crates/vfs-notify/Cargo.toml
Unlike version 6.0.1, this does not pull windows-sys 0.45.0 as observed in #15077.
```
$ cargo tree --target=x86_64-pc-windows-gnu --charset=ascii | grep windows-sys
|           |   `-- windows-sys v0.42.0
|   |   |   |   |   |       `-- windows-sys v0.42.0 (*)
|       `-- windows-sys v0.48.0
|   |   `-- windows-sys v0.48.0 (*)
|   `-- windows-sys v0.48.0 (*)
|   `-- windows-sys v0.48.0 (*)
|   `-- windows-sys v0.42.0 (*)
```
> minor: Update notify to 6.1.1

- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/from_proto.rs
Resolves https://github.com/rust-lang/rust-analyzer/issues/15540. I moved the `chdir` functionality outside of the `match` to ensure that this functionality wouldn’t fall through again. As part of this PR, I also changed `from_proto::file_range` to accept a `TextDocumentIdentifier` by reference instead of by value, but I can undo this change if desired.
I added a `rustfmt.toml` will the contents below at `crates/rust-analyzer/rustfmt.toml`: 
```toml
reorder_modules = false
use_small_heuristics = "Max"
tab_spaces = 8
```
In addition, I've also added `"rust-analyzer.rustfmt.overrideCommand": ["rustfmt"]` to my VS Code configuration.
With the above changes, saving `crates/rust-analyzer/src/handlers/request.rs` results in 8-space indentation. Meanwhile, saving `crates/toolchain/src/lib.rs` …
> internal: use current folder's `rustfmt.toml` with all rustfmt configurations

- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/mir/eval/shim.rs
Required for getting `write!`ing to work again. we fail with an odd type mimsatch eval error after this change though
> Implement `write_via_move` intrinsic for mir-eval

- crates/ide/src/typing.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/handlers/request.rs
If I understand right, `()` can surround pretty much the same `{}` can, so add another on type formatting pair for convenience: sometimes it's not that pleasant to write parenthesis in `Some(2).map(|i| (i, i+1))` cases and I would prefer r-a to do that for me.
One note: currently, https://github.com/rust-lang/rust-analyzer/blob/b06503b6ec98c9ed44698870cbf3302b8560b442/crates/rust-analyzer/src/handlers/request.rs#L357 fires always.
Should we remove the assertion entirely now, since apparently things work in release despite that check?
> On type format '(', by adding closing ')' automatically

- crates/ide-assists/src/handlers/into_to_qualified_from.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
fixes #15539. This assist converts an `.into()` call into an explicit fully qualified `from()` call.
> assist : `into_to_qualified_from`

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/util.ts
I think it's time to remove this functionality from the `rust-analyzer` and move it into a dedicated extension responsible for this. Selfishly, this changes makes it tenable to do progress reporting to the editor and potentially do some more complicated things around managing _which_ workspaces are being used.
> code: remove `rust-analyzer.discoverProjectCommand` in favor of a companion extension

- crates/ide-assists/src/handlers/bind_unused_param.rs
- crates/ide-assists/src/handlers/remove_unused_param.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
This PR introduces a new **Bind unused parameter assistant**.
While we do have a QuickFix from `rustc` (prefixing the parameter with an underscore), it's sometimes more convenient to suppress the warning using the following approach:
```rust
fn some_function(unused: i32) {}
```
->
```rust
fn some_function(unused: i32) {
let _ = unused;
}
```
> Bind unused parameter assistant

- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/borrowck.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir-ty/src/mir/pretty.rs
I hope this reduces mir memory usage.
> Intern projections in mir place

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
See https://github.com/rust-lang/rust-analyzer/issues/13369#issuecomment-1695306870
Editor itself is able to invalidate hints after edits, and /refresh was sent after editor reports changes to the language server. This forces the editor to either query & invalidate the hints twice after every edit, or wait for /refresh to come before querying the hints.
Both options are rather useless, so instead, send a request on server startup only: client editors do not know when the server actually starts up, this will help to query the initial hints after editor was open and the server was still starting up.
> Do not send inlay hint refresh requests on file edits

- crates/base-db/src/fixture.rs
- crates/cfg/src/lib.rs
- crates/ide-completion/src/completions/attribute/cfg.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/ide-db/src/search.rs
- crates/project-model/src/workspace.rs
- crates/project-model/test_data/output/cargo_hello_world_project_model.txt
- crates/project-model/test_data/output/cargo_hello_world_project_model_with_selective_overrides.txt
- crates/project-model/test_data/output/cargo_hello_world_project_model_with_wildcard_overrides.txt
- crates/project-model/test_data/output/rust_project_hello_world_project_model.txt
This allows one to have r-a skip analysis/replace macros that work not well with r-a at all by gating them behind this cfg (an example being the `quote` macro which r-a struggles with in terms of performance).
> Enable `rust_analyzer` for cfgs when code is being analyzed by rust-analyzer

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/adjustment.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/binding_mode.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/inlay_hints/closing_brace.rs
- crates/ide/src/inlay_hints/closure_captures.rs
- crates/ide/src/inlay_hints/closure_ret.rs
- crates/ide/src/inlay_hints/discriminant.rs
- crates/ide/src/inlay_hints/fn_lifetime_fn.rs
- crates/ide/src/inlay_hints/implicit_static.rs
- crates/ide/src/inlay_hints/param_name.rs
- crates/ide/src/lib.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/vfs/src/lib.rs
- docs/dev/lsp-extensions.md
Part of https://github.com/rust-lang/rust-analyzer/issues/13962
Support https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHint_resolve better, by omitting all inlay hint fields specified in the client hint resolve capabilities.
Current list of all capabilities possible to resolve later:
```
"textEdits"
"tooltip"
"label.tooltip"
"label.location"
"label.command"
```
and every one specified in the client capabilities is now resolved by r-a, being omitted in the initial response.
--------------
When editing `inlay_hints.rs` file around line `457` with no resolve capabilities, I get 
<details>
<summary>resolved json, 10803 characters</summary>
```json
{"jsonrpc":"2.0","id":55,"result":[{"position":{"line":477,"character":1},"label":[{"value":"fn …
```
> Resolve inlay hint data

- crates/project-model/src/rustc_cfg.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
At the moment, rust-analyzer discovers `rustc` via the `$PATH` even if the `sysroot` field is defined in a `rust-project.json`. However, this does not work for users who do not have rustup installed, resulting in any `cfg`-based inference in rust-analzyer not working correctly. In my (decently naive!) opinion, it makes more sense to rely on the `sysroot` field in the `rust-project.json`.
One might ask "why not add `rustc` to the `$PATH`?" That is a reasonable question, but that doesn't work for my use case:
- The path to the sysroot in my employer's monorepo changes depending on which platform a user is on. For example, if they're on Linux, they'd want to use the sysroot defined at path `a`, whereas if they're on macOS, they'd want to use the sysroot at path `b` (I wrote the sysroot …
> project-model: when using `rust-project.json`, prefer the sysroot-defined rustc over discovery in `$PATH`

- crates/ide-db/src/rename.rs
- crates/ide/src/rename.rs
fixes #14850 . This makes me wonder , why stop at structs and not do the same for other ADTs? Would be happy to add them too if nothing speaks against it.
> ide : Disallow renaming of non-local items

- crates/ide-assists/src/handlers/extract_function.rs
> minor : Deunwrap extract_function

- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/lib.rs
"Fixes https://github.com/rust-lang/rust-analyzer/issues/15344"
> fix: Temporarily skip decl check in derive expansions

- crates/ide-db/src/search.rs
- crates/ide/src/annotations.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15602
> fix: Fix lens location "above_whole_item" breaking lenses

- crates/hir/src/semantics.rs
See https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Semantics.20vs.20SemanticsImpl/near/390795952
> internal: Remove most of the duplication from `Semantics{,Impl}` via deref

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/import_map.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15610
> Prefer stable paths over unstable ones in import path calculation

- crates/ide-assists/src/handlers/promote_local_to_const.rs
Currently, running `promote_local_to_const` on the following:
```rust
struct Foo {
bar: usize,
}
fn main() {
let $0bar = 0;
let foo = Foo { bar };
}
```
Results in:
```rust
struct Foo {
bar: usize,
}
fn main() {
const BAR: usize = 0;
let foo = Foo { BAR };
}
```
But instead should be something like:
```rust
struct Foo {
bar: usize,
}
fn main() {
const BAR: usize = 0;
let foo = Foo { bar: BAR };
}
```
> Field shorthand overwritten in promote local to const assist

- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/layout/tests/closure.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
As I understand that `return` was left there by accident. It caused capture analysis to skip the rest of the block after a let-else, and then missed captures caused incorrect results in borrowck, closure hints, layout calculation, etc.
Fixes #15623
I didn't understand why I using the example from #15623 as-is doesn't work - I don't get the warnings unless I remove the `call_me()` call, even on the same commit as my own RA version which does show those warnings.
> fix: Don't skip closure captures after let-else

- crates/rust-analyzer/src/cli/scip.rs
This honors the build script config, and is also simpler.
> scip: Use load_workspace_at.

- Cargo.lock
- Cargo.toml
- crates/hir-def/Cargo.toml
- crates/hir-def/src/data/adt.rs
- crates/hir-def/src/hir/format_args.rs
- crates/hir-def/src/lib.rs
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/layout.rs
- crates/parser/Cargo.toml
- crates/parser/src/lexed_str.rs
- crates/parser/src/lib.rs
- crates/rust-analyzer/Cargo.toml
- crates/rustc-dependencies/Cargo.toml
- crates/rustc-dependencies/src/lib.rs
- crates/syntax/Cargo.toml
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/lib.rs
- crates/syntax/src/validation.rs
We can use this flag to detect and prevent breakages in rustc CI. (see #14846 and #15569)
~The `IN_RUSTC_REPOSITORY` is just a placeholder. Is there any existing cfg flag that rustc CI sets?~
> Switch to in-tree rustc dependencies with a cfg flag

- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/15604
VSCode behaves strangely, allowing to navigate into label location, but not allowing to apply hint's text edit, after hint is resolved. See https://github.com/microsoft/vscode/issues/193124 for details.
For now, stub hint resolution for VSCode specifically.
> Do not resolve inlayHint.textEdit for VSCode client

- Cargo.lock
- crates/hir-ty/Cargo.toml
This only pulls in one commit in Chalk, which is an improvement to inference for rust-analyzer: https://github.com/rust-lang/chalk/pull/800
> Update chalk version

- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-assists/src/handlers/inline_local_variable.rs
Previously, closures were not properly wrapped in parentheses for the `inline_local_variable` and `inline_call` assists, leading to the usages being incorrectly called:
```rust
fn main() {
let $0f = || 2;
let _ = f();
}
```
Now produces:
```rust
fn main() {
let _ = (|| 2)();
}
```
Instead of:
```rust
fn main() {
let _ = || 2();
}
```
Closes #15639
> fix: Fix inlining closures from local variables and functions

- crates/ide-assists/src/handlers/inline_call.rs
#15398 subtask 4. There is still one instance of unwrap, which I found pretty hard to change.
> minor : Deunwrap inline call

- crates/ide-db/src/imports/insert_use/tests.rs
- crates/ide-db/src/imports/merge_imports.rs
Potentially fixes #15128 
There are two cases of imports:
1. With simple path
2. With use tree list (or say complex path).
On deeper inspection, the [`recursive_merge`](https://github.com/rust-lang/rust-analyzer/blob/994df3d6a31d39f11600f30a6df0b744b13937c1/crates/ide-db/src/imports/merge_imports.rs#L87) function (called by [`try_merge_trees_mut`)](https://github.com/rust-lang/rust-analyzer/blob/994df3d6a31d39f11600f30a6df0b744b13937c1/crates/ide-db/src/imports/merge_imports.rs#L69) is meaningful only in the case of complex path (i.e when the UseTree contains a UseTreeList). 
The [`recursive_merge`](https://github.com/rust-lang/rust-analyzer/blob/994df3d6a31d39f11600f30a6df0b744b13937c1/crates/ide-db/src/imports/merge_imports.rs#L87) function has [match with `Ok` …
> Fix autoimport does nothing when importing trait that is as _ imports

- triagebot.toml
https://github.com/rust-lang/triagebot/pull/1720
> triagebot exclude_labels -> exclude_titles

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
> Deunwrap add_missing_match_arms

- crates/ide-assists/src/handlers/convert_comment_block.rs
- crates/ide-assists/src/handlers/desugar_doc_comment.rs
Closes subtask 13 of #15398 . I still don't know a more idiomatic way for the for loops I added, any suggestion would make me happy.
> minor : Deunwrap convert_comment_block and desugar_doc_comment

- crates/ide-completion/src/config.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-completion/src/tests.rs
- crates/ide-completion/src/tests/special.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- docs/user/generated_config.adoc
- editors/code/package.json
implements #15538 
with `"rust-analyzer.completion.fullFunctionSignatures.enable": false`:
with `"rust-analyzer.completion.fullFunctionSignatures.enable": true`:
> add option to show full function signatures in completion docs

- crates/base-db/src/input.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/hover.rs
A minor refactor of `hover_simple` opportunity I noticed while skimming through the code.
- `if let`s -> `match`
- `iter::once(x).cycle` -> `iter::repeat`
- `classify_token` -> `classify_node`
> minor: hover_simple refactor

- crates/ide-assists/src/handlers/generate_function.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15398#issuecomment-1733462185
cc @Inicola
> internal: De-`unwrap` `generate_function.rs`

- Cargo.lock
This update is a follow-up for [#112374](https://github.com/rust-lang/rust/pull/112374).
The command that does this update:
`cargo update -p libc`
> minor: update libc to 0.2.148

- crates/ide-assists/src/handlers/unwrap_result_return_type.rs
- crates/ide-assists/src/handlers/wrap_return_type_in_result.rs
With the `wrap_return_type_in_result` assist, the following code results in a panic (note the lack of a semicolon):
```rust
fn foo(num: i32) -> $0i32 {
return num
}
=> 
thread 'handlers::wrap_return_type_in_result::tests::wrap_return_in_tail_position' panicked at crates/syntax/src/ted.rs:137:41:
called `Option::unwrap()` on a `None` value
```
I think this is because it first walks the body expression to change any `return` expressions and then walks all tail expressions, resulting in the `return num` being changed twice since it is both a `return` and in tail position. This can also happen when a `match` is in tail position and `return` is used in a branch for example. Not really sure how big of an issue this is in practice though since this seems to be the only case that is impacted and …
> fix: panic with wrapping/unwrapping result return type assists

- crates/hir-def/src/data.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-expand/src/ast_id_map.rs
Since these can have attributes attached to them, we'll need this sooner or later (sooner being me tinkering with the token map right now)
> Allocate ast ids for parameters

- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/rust-analyzer/src/config.rs
Re-use the LSP config json for simplicity.
> scip: Allow customizing cargo config.

- crates/ide-assists/src/handlers/bool_to_enum.rs
- crates/ide-assists/src/tests/generated.rs
This pr makes the `bool_to_enum` assist create the `enum` at the next closest module block or at top-level, which fixes a few tricky cases such as with an associated `const` in a trait or module:
```rust
trait Foo {
const $0BOOL: bool;
}
impl Foo for usize {
const BOOL: bool = true;
}
fn main() {
if <usize as Foo>::BOOL {
println!("foo");
}
}
```
Which now properly produces:
```rust
#[derive(PartialEq, Eq)]
enum Bool { True, False }
trait Foo {
const BOOL: Bool;
}
impl Foo for usize {
const BOOL: Bool = Bool::True;
}
fn main() {
if <usize as Foo>::BOOL == Bool::True {
println!("foo");
}
}
```
I also think it's a bit nicer, especially for local variables, but didn't really know to do it in the first PR :)
> fix: make bool_to_enum assist create enum at top-level

- .github/workflows/ci.yaml
There is little gain from running them on all platforms, they should almost never fail if the linux one pass and if they do, bors will catch it still.
> Only run tests on linux in pull requests

- crates/ide-completion/src/item.rs
- crates/ide-db/src/generated/lints.rs
- crates/ide-db/src/tests/sourcegen_lints.rs
- crates/ide/src/hover/tests.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
Looks like this hasn't been run in a while
> internal: re-generate lints.rs

- crates/hir-ty/src/layout/adt.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/15687
> Make rustc_layout_scalar_valid_range attributes work for non-decimal literals

- crates/ide-diagnostics/src/handlers/unused_variables.rs
I feel problems like #15679 are common.
> Downgrade `unused_variables` to experimental

- crates/hir-ty/src/layout/adt.rs
CC https://github.com/rust-lang/rust-analyzer/pull/15688/files#r1342311078
> fix: strip base prefix in `layout_scalar_valid_range`

- crates/ide-assists/src/handlers/convert_to_guarded_return.rs
Removes the checks that require the pattern to be a tuple struct with exactly 1 field that is unqualified and has an identifier pattern in it. I'm not sure if there should be more checks in place but they seem unnecessary now?
Closes #15695
> fix: allow more kinds of if let patterns in guarded return assist

- crates/ide-assists/src/handlers/apply_demorgan.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
This PR adds an assist for transforming expressions of the form `!iter.any(|x| predicate(x))` into `iter.all(|x| !predicate(x))` and vice versa.
[IteratorDeMorgans.webm](https://github.com/rust-lang/rust-analyzer/assets/52933714/aad1a299-6620-432b-9106-aafd2a7fa9f5)
Closes #15694
> feat: add assist for applying De Morgan's law to `Iterator::all` and `Iterator::any`

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/ctx.ts
Fixes #15441 
Please suggest any changes if necessary.
> Add configuration for the default action of the status bar click action in VSCode

- editors/code/language-configuration.json
Makes backticks always complete as a pair and also surround the current selection, similar to double quotes. This is useful primarily in the context of markdown doc comments, but is applied globally for simplicity.
Closes https://github.com/rust-lang/rust-analyzer/issues/11381
> feat: add backtick to surrounding and auto-closing pairs

- crates/hir-ty/src/mir/eval/shim.rs
Fix names of intrinsics in error messages from exec_intrinsic
(moved from rust-lang/rust#116478)
> Fix typos exec_intrinsic

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/tests.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/ide-diagnostics/src/handlers/no_such_field.rs
- crates/ide-diagnostics/src/handlers/private_assoc_item.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/syntax/src/ptr.rs
Will have neglible perf results I imagine, but it cleans up some code
> Shrink PatPtr by swapping its AstPtr and Either wrap order

- crates/rust-analyzer/src/handlers/request.rs
(Hopefully) resolves https://github.com/rust-lang/rust-analyzer/issues/15595. This change kinda approaches canonicalization—which I am not a fan of—but only in service of making `./`-configured commands run correctly.
Longer-term, I feel like this code should be removed once `rustfmt` supports recursive searches of configuration files or interpolation of values like `${workspace_folder}` lands in rust-analyzer.
I cloned `rustc`, setup rust-analyzer as suggested in the [`rustc` dev guide](https://rustc-dev-guide.rust-lang.org/building/suggested.html#configuring-rust-analyzer-for-rustc), saved and formatted files in `src/tools/miri` and `compiler`, and saw `rustfmt` (seemingly) correctly.
> fix: ensure `rustfmt` runs when configured with `./`

- crates/ide-db/src/generated/lints.rs
- crates/ide-db/src/tests/sourcegen_lints.rs
Missed in #15680: the output of `-Whelp` changed since the last run so it generated some bad rustdoc lints entries.
Also preemptively fix a `-Whelp` breakage that might get merged in rust-lang/rust#116412
> internal: fix automatic rustc/rustdoc lint generation

- crates/flycheck/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Adds a Rust Analyzer configuration option to set a custom target directory for builds. This is a workaround for Rust Analyzer blocking debug builds while running `cargo check`. This change should close #6007.
This is my first time contributing to this project, so any feedback regarding best practices that I'm not aware of are greatly appreciated! Thanks to all the maintainers for their hard work on this project and reviewing contributions.
> Add config option to use `rust-analyzer` specific target dir

- crates/hir-def/src/import_map.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/items_locator.rs
- crates/ide-db/src/symbol_index.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15711
> Do flyimport completions by prefix search for short paths

- crates/hir-ty/src/diagnostics/decl_check/case_conv.rs
- crates/ide-assists/src/handlers/convert_tuple_return_type_to_struct.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/stdx/src/lib.rs
This PR implements the `convert_tuple_return_type_to_struct` assist, for converting the return type of a function or method from a tuple to a tuple struct. Additionally, it moves the `to_camel_case` and `char_has_case` functions from `case_conv` to `stdx` so that they can be used similar to `to_lower_snake_case`.
[tuple_return_type_to_tuple_struct.webm](https://github.com/rust-lang/rust-analyzer/assets/52933714/2803ff58-fde3-4144-9495-7c7c7e139075)
Currently, the assist puts the struct definition above the function, or above the nearest `impl` or `trait` if applicable and only rewrites literal tuples that are returned in the body of the function. Additionally, it only attempts to rewrite simple tuple pattern usages with the corresponding tuple struct pattern but does so across files and …
> feat: implement tuple return type to tuple struct assist

- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
This PR implements the VS code support for opening local documentation (server side support was already implemented in #14662).
[local_docs.webm](https://github.com/rust-lang/rust-analyzer/assets/9659253/715b84dd-4f14-4ba0-a904-749b847eb3d5)
Displaying local instead of web docs can have many benefits:
- the web version may have different features enabled than locally selected
- the standard library may be a different version than is available online
- the user may not be online and therefore cannot access the web documentation
- the documentation may not be available online at all, for example because it is for a new feature in a library the user is currently developing
If the documentation is not available locally, the extension still falls back to the web version.
Closes #12867.
----- …
> feat: vscode: Support opening local documentation if available

- crates/ide-assists/src/handlers/replace_is_some_with_if_let_some.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
This is a basic impl, if it is ok, `if my_result.is_ok()`-> `if let Ok(_x) = my_result ​`will be add next.
close https://github.com/rust-lang/rust-analyzer/issues/12977
> add replace_is_some_with_if_let_some assist

- crates/mbe/src/lib.rs
fix typo in mbe/lib.rs comment
> fix typo in mbe/lib.rs comment

- crates/hir-ty/src/mir.rs
When using RA as a crate the `mir::Place` `projection` is accessible, however there is no way to translate the `ProjectionId` to a `&[PlaceElem]`, as the `ProjectionId::lookup` is private.
Personally, I would only need the `ProjectionId::lookup`-fn to be `pub`, but I don't see any reason why the others should be kept private.. am I missing something @HKalbasi ?
Relates to: https://github.com/rust-lang/rust-analyzer/pull/15575
> make mir::ProjectionStore-impls pub-accessible

- crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
- crates/ide-assists/src/tests/generated.rs
Here make cursor select at `_tmp` atuomatically after the assist apply. Refer to [vscode snippet placeholder](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_placeholders).
following https://github.com/rust-lang/rust-analyzer/pull/15752
> fix: make cursor select at _tmp

- Cargo.lock
- crates/hir-def/src/data/adt.rs
- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/layout/adt.rs
- crates/hir/src/lib.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/view_memory_layout.rs
- crates/rustc-dependencies/Cargo.toml
- crates/rustc-dependencies/src/lib.rs
cc https://github.com/rust-lang/rust/pull/116269
> Update rustc_abi dependency

- docs/user/manual.adoc
Emacs 29 is now released, and include an example of enabling clippy.
> Expand Emacs documentation

- crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
- crates/ide-assists/src/tests/generated.rs
change generated variable name in `replace_is_some_with_if_let_some` assist
close https://github.com/rust-lang/rust-analyzer/issues/15765
> refactor: change generated variable name

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
opening URI in a remote env causes vscode to ask the OS to handle `vscode-remote` URIs as there is no handler registered for such a scheme. This attempts to instruct vscode to handle those.
This is untested, as I can't figure out how to open a debug session on WSL rn.
> Add command for only opening external docs and attempt to fix vscode-remote issue

- crates/hir-def/src/lib.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
Adds diagnostics for checking both inline and file module names are snake case.
Closes #15678
> fix: add incorrect case diagnostics for module names

- crates/ide-db/src/generated/lints.rs
- crates/ide-db/src/tests/sourcegen_lints.rs
Most unstable features don't have their own chapter in the unstable book, so a rustc helper tool (`src/tools/unstable-book-gen`) generates shims to fill the gaps.
Run this tool to generate the full unstable-book source before parsing it.
> feat: generate descriptors for all unstable features

- crates/ide-assists/src/handlers/unqualify_method_call.rs
- crates/ide-assists/src/tests/generated.rs
before:
after:
follow up https://github.com/rust-lang/rust-analyzer/pull/13825
> fix: import trait if needed for `unqualify_method_call` assist

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/cli/scip.rs
While the git repo has been updated constantly, crates.io has only now been updated after more than a year of activity.
> internal: scip: update crate to version 0.3.1.

- crates/ide-assists/src/handlers/extract_variable.rs
close https://github.com/rust-lang/rust-analyzer/issues/15796
> feat: make extract_variable assist in place

- crates/ide-assists/src/handlers/auto_import.rs
- crates/ide-db/src/imports/insert_use.rs
cc @Veykril
close https://github.com/rust-lang/rust-analyzer/issues/15684
> feat: import trait with alias

- crates/hir-expand/src/db.rs
> feat: skip checking token tree count for include! macro call

- editors/code/package.json
If you invoke cmd+p `Format Document` without rust-analyzer installed in the workspace, VSCode suggests you "install a formatter" which triggers a search for `category:formatters rust`. Sadly rust-analyzer extension is not suggested.
Tweak VSCode Extension Metadata so rust-analyzer shows up in 'category:formatters rust' search.
You can see the valid values for categories in the [extension manifest: field reference](https://code.visualstudio.com/api/references/extension-manifest#fields) docs.
> VSCode metadata. category:formatters

- crates/ide/src/doc_links.rs
Fixes #15831.
Not sure about `attr`, I don't think those are documented anyway. And many macros don't work because we pick the wrong path.
> fix: Fix docs path for derive macros

- crates/ide-assists/src/handlers/generate_mut_trait_impl.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-db/src/famous_defs.rs
- crates/syntax/src/ast/make.rs
Generate proper `index_mut` method body refer to `index` method body may impossible due to the unpredicable case (#15581).
Here just leave the `index_mut` method body be same as `index` method body, user can modify it manually to meet their need.
> feat: add generate_mut_trait_impl assist

- Cargo.lock
- crates/hir-def/src/data/adt.rs
- crates/rustc-dependencies/Cargo.toml
Except `rustc_parse_format` that was broken by upstream.
> Update rustc dependencies

- crates/hir/src/display.rs
- crates/ide/src/hover/tests.rs
> feat: preview adt field when hover

- crates/parser/src/event.rs
`TokenSource` and `TreeSink` has been refactored as part of #10765, they no longer exist in code repo. This pr tries to remove them from event module level comment to prevent confusion.
> Try to update parser/event doc

- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/infer/closure.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
fix https://github.com/rust-lang/rust-analyzer/issues/15670#issuecomment-1804070623
> Truncate closure capture place for raw pointer

- crates/ide-db/src/search.rs
- crates/ide/src/references.rs
took a lot of time to debug to find the problem, here should compare the actual `Adt` type
close https://github.com/rust-lang/rust-analyzer/issues/12693
> fix: find `Self` reference

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/utils.rs
> fix: Ignore doc(hidden) attr if no body is present

- crates/hir-expand/src/db.rs
https://github.com/rust-lang/rust-analyzer/pull/15819#pullrequestreview-1724883108
> Improve check for include macro

- crates/ide/src/expand_macro.rs
- editors/code/package.json
Closes [#15856](https://github.com/rust-lang/rust-analyzer/issues/15856).
I opted for "caret", since it's the better term (cursor is the mouse), but I'm not sure how popular it is these days.
> minor: Make "Expand macro" command title more explicit

- crates/load-cargo/src/lib.rs
> internal: Include toml files in the vfs

- docs/dev/lsp-extensions.md
Explicitly[^1] allow a single `TextDocumentEdit` to have multiple `SnippetTextEdit`s. This allows things like renaming extracted variables and functions without having to go through a separate rename step. For an example of what this looks like, see the video in [this comment](https://github.com/microsoft/vscode/issues/145374#issuecomment-1177341711).
The behavior described here lines up with [what VSCode does](https://github.com/microsoft/vscode/blob/bdc113ffe148a92d0e1a8ec34b12c44ea0b73f29/src/vscode-dts/vscode.d.ts#L3728-L3731), and presumably what the eventual LSP behavior will be.
[^1]: This was technically the case before #15269, a single `TextDocumentEdit` always had multiple edits which were `InsertTextFormat.Snippet` as all of the edits were marked as being snippets, even if …
> minor: Allow multiple snippet edits in a `TextDocumentEdit`

- docs/user/manual.adoc
Fix invalid JSONC examples (missing double quotes) in VS Code's `settings.json` .
Thank you.
> docs: fix VS Code setting samples

- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
close https://github.com/rust-lang/rust-analyzer/issues/15778
> fix `PathSegment` grammar

- crates/ide-assists/src/handlers/add_turbo_fish.rs
- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-assists/src/tests.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
Continuing from #15260
- `add_turbo_fish`
- `add_type_ascription`
- `destructure_tuple_binding`
- `destructure_tuple_binding_in_subpattern`
I did this a while ago, but forgot to make a PR for the changes until now. 😅
> internal: Migrate assists to the structured snippet API, part 4

- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
Turns out we only calculated def diagnostics for these before (was wondering why I wasn't getting any type mismatches)
> fix: Diagnose everything in nested items, not just def diagnostics

- editors/code/package-lock.json
- editors/code/package.json
Undoes https://github.com/rust-lang/rust-analyzer/pull/15333.
> editor/code: bump minimum version of VS Code to 1.78

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
This (mostly red) PR does three things:
- Exposes two methods to companion extensions (`setWorkspaces` and `notifyRustAnalyzer`). 
- `setWorkspaces` is needed to update `linkedProjects` _without_ writing workspace/global configuration.
- `notifyRustAnalyzer` to get the server to pull the new configuration.
- Makes `Ctx` implement `RustAnalyzerExtensionApi` to prevent accidental regressions.
- Remove `rust-analyzer.addProject`, as that will live in a buck2 companion extension. No need for that to be in rust-analyzer!
I can see the utility of combining `notifyRustAnalyzer` and `setWorkspaces` into a single method (`updateWorkspacesAndNotify()`?), but I don't feel strongly about this. My feeling is that this API could be easily changed in the future.
> code: expose workspaces to other extensions; remove `addProject` command

- crates/ide/src/highlight_related.rs
While reading the user manual, I noticed a random tick, so I went ahead and fixed it. The `await` keyword should be properly rendered as inline code.
> Fix typo in highlight_related.rs

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/trait_impl_missing_assoc_item.rs
A patch of https://github.com/rust-lang/rust-analyzer/pull/15895, close https://github.com/rust-lang/rust-analyzer/issues/15909
cc @Veykril
> fix: handle default constant values in `trait_impl_missing_assoc_item` diagnostic

- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
This is a bugfix for an issue I fould while working on helix. Rust-analyzer currently always sends any filesystem edits (rename/file creation) before any other edits. When renaming a file that is also being edited that would mean that the edit would be discarded and therefore an incomplete/incorrect refactor (or even cause the creation of a new file in helix altough that  is probably a pub on our side).
Example:
* create a module: `mod foo` containing a `pub sturct Bar;`
* reexport the struct uneder a different name in the `foo` module using a *fully qualified path*: `pub use crate::foo::Bar as Bar2`.
* rename the `foo` module to `foo2` using rust-analyzer
* obsereve that the path is not correctly updated (rust-analyer first sends a rename `foo.rs` to `foo2.rs` and then edits `foo.rs` …
> ensure renames happen after edit

- docs/user/manual.adoc
> Update Arch Linux package URL in manual.adoc

- crates/ide-assists/src/handlers/unqualify_method_call.rs
add use case for `PathSegment::qualifying_trait`, which introduced in https://github.com/rust-lang/rust-analyzer/pull/15875
> chore: add use case for `PathSegment::qualifying_trait`

- Cargo.lock
- lib/lsp-server/Cargo.toml
- lib/lsp-server/src/lib.rs
This commit provides additional initialization methods to Connection in order to support CTRL + C sigterm handling.
In the process of adding LSP to Nushell (see https://github.com/nushell/nushell/pull/10941) this gap has been identified.
> Cancelable Initialization

- crates/ide-completion/src/item.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
This PR improves completion label details display by separating trait and alias info from the `label` LSP field to an additional existing `label_detail` field. Changes look like the following:
_All existing tests are passed without any changes in test themselves logic._
> Improve completion label details display

- editors/code/package.json
- editors/code/src/base_client.ts
- editors/code/src/client.ts
- editors/code/src/lang_client.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/14193
- Added the `rust-analyzer.showRequestFailedErrorNotification` configuration option, which defaults to `true`
- If `rust-analyzer.showRequestFailedErrorNotification` is set to `true`, the current behavior is preserved.
- If `rust-analyzer.showRequestFailedErrorNotification` is set to `false`, no error toasts will be displayed for any of the failed requests caused by panics in r-a. This _only_ applies to events that are triggered "implicitly", such as `textDocument/hover`.
To test this, you can manually introduce a panic in one of the language server LSP handlers for non-command events. I added an explicit `panic!()` in the `textDocument/hover` event handler:
[2023-11-07 …
> editor/code: add option to suppress internal error notifications

- crates/ide-assists/src/handlers/toggle_ignore.rs
- crates/ide/src/extend_selection.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
Extracted from https://github.com/rust-lang/rust/pull/118253.
> Replace `option.map(cond) == Some(true)` with `option.is_some_and(cond)`

- crates/ide-completion/src/item.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
This PR adds a fallback to a previous implementation in a case when the label detail field isn't supported by LSP client and the support isn't reported by the LSP initialize request. In this case additional info about trait and aliases would be merged into the label field as it was before the #15956 PR.
> fix: add fallback for completion label details

- Cargo.lock
- crates/hir-ty/Cargo.toml
- crates/rustc-dependencies/Cargo.toml
This finally upgrades `ra-ap-rustc_parse_format` (even though it's probably a no-op?).
> minor: Bump rustc deps and chalk

- Cargo.lock
- crates/base-db/Cargo.toml
This gets rid of `syn` 1, among others.
> internal: Switch to our own `salsa` fork

- crates/rust-analyzer/src/reload.rs
Refactoring the duplicate removal process for `workspaces` in `fetch_workspaces`.
Replaced `[].iter().enumerate().skip(...).filter_map(...)` with a more concise `[i+1..].positions(...)` provided by `itertools`, which enhances clarity without changing functionality
This change aims to enhance the duplicate removal process for `workspaces`. This change has been tested on my machine.
Please review and provide feedback. Thanks!
> internal: simplify the removal of dulicate workspaces.

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/patterns.rs
- crates/ide-completion/src/tests/pattern.rs
> fix variant resolve for type alias

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
before 
after
close https://github.com/rust-lang/rust-analyzer/issues/15954
> fix: don't make `MissingMatchArms` diagnostic for empty match body

- editors/code/src/debug.ts
- editors/code/src/toolchain.ts
> Debug use cargo workspace root as `cwd`

- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
This PR removes an unused `PhantomData` in `FileItemTreeId`.
*Note:* I am not sure how this should be implemented, maybe as a type instead of a wrapper struct? I'd be happy to do so if needed 👍
> chore: remove unused `PhantomData`

- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/pretty.rs
- crates/hir/src/lib.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/implicit_drop.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- crates/test-utils/src/minicore.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> Initial support for implicit drop inlay hint

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/render.rs
Fixes #14656 
PR is opened with basic changes. It could be improved by having a new `SymbolKind` for the callable fields and implementing a separate render function similar to the `render_method` for the new `SymbolKind`.
It could also be done without any changes to the `SymbolKind` of course, have the new function called based on the type of field. 
I prefer the former method.
Please give any thoughts or changes you think is appropriate for this method. I could start working on that in this same PR.
> Implement completion for the callable fields.

- crates/ide-completion/src/completions/record.rs
- crates/ide-completion/src/render.rs
Fixes #16014.
Sorry I missed it in previous PR. I've added a test as level to prevent regressions again. 
Give any suggestions to improve the test if anything.
> fix: Insert fn call parens only if the parens inserted around field name

- crates/hir-def/src/macro_expansion_tests/mod.rs
- crates/hir-def/src/nameres/mod_resolution.rs
- crates/hir-expand/src/files.rs
- crates/hir-expand/src/lib.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir/src/symbols.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-diagnostics/src/handlers/field_shorthand.rs
- crates/ide-diagnostics/src/handlers/inactive_code.rs
- crates/ide-diagnostics/src/handlers/invalid_derive_target.rs
- crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
- crates/ide-diagnostics/src/handlers/macro_error.rs
- crates/ide-diagnostics/src/handlers/malformed_derive.rs
- crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
- crates/ide-diagnostics/src/handlers/typed_hole.rs
- crates/ide-diagnostics/src/handlers/unlinked_file.rs
- crates/ide-diagnostics/src/handlers/unresolved_module.rs
- crates/ide-diagnostics/src/handlers/useless_braces.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide-diagnostics/src/tests.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/runnables.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/rust-analyzer/src/diagnostics.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/14968
> fix: Fix diagnostics panicking when resolving to different files due to macros

- crates/hir-ty/src/lib.rs
In `hir-ty`, the `TyLoweringContext` has functions `pub fn with_impl_trait_mode` and `pub fn with_type_param_mode`, which can be used to fine-tune certain lowering properties.
Each of these takes one enum (either `pub enum ImplTraitLoweringMode`, or `pub enum ParamLoweringMode`), which encodes the possible configuration options.
To then make this usable for other crates, `TyLoweringContext` and `ImplTraitLoweringMode` are exported. Unfortuntely, `ParamLoweringMode` is not. This means that while the method can be called, there are no useful values to call it with.
Presumably this is an oversight. It would be great if this was made actually public.
> make ParamLoweringMode accessible

- crates/ide-assists/src/handlers/extract_function.rs
There is a little bug in extract_function: It appends `use path::to::ControlFlow;` if the function created contains string "ControlFlow".
A case below (also in the test named `does_not_import_control_flow` which will fail in the original code)
Now I have changed the condition determining whether adding import statement. Only when the new function body contains ControlFlow::Break or ControlFlow::Continue can the import statement be added.
Last related PR: https://github.com/rust-lang/rust-analyzer/pull/10309
> fix: bug in extract_function.rs

- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/tests/regression.rs
I was working on #15947 and found out that we panic on this test:
```
fn main() {
let x = [(); &(&'static: loop { |x| {}; }) as *const _ as usize]
}
```
This PR fixes the panic. Closures in array len are still broken, but closure in const eval is not stable anyway.
> Fix panic with closure inside array len

- editors/code/src/run.ts
This PR fixes a UI annoyance in the VS Code extension when working in large codebases where rust-analyzer can take a few moments to interact with the server. Scenario:
1. Invoke "rust-analyzer: Run" from the command palette or hotkey
2. Quickly start typing to filter the list (or press Enter to accept the last runnable)
We often do this quickly from muscle memory without waiting to see the picker. The picker often takes several seconds to come up, causing us to type garbage into the currently open editor. 
Fix:
Show a placeholder item before we call out to the server. 
Selecting this item does nothing so if the user accidentally hits Enter nothing happens.
The list is populated and the placeholder dismissed when the actual runnables are retrieved. From here the behavior is the same as …
> Show placeholder while run command gets runnables from server

- crates/ide-assists/src/handlers/flip_binexpr.rs
Closes #15508 
From the original PR, flip binexpr assist is not meant to preserve equivalence, so I went with the simplest solution here.
I can add some extra checks to keep equivalence, but I think they should go in different specific assists (eg. flip arith op / flip logic op / etc), otherwise this one will get out of hand pretty quickly.
> Check if lhs is also a binexpr and use its rhs in flip binexpr assist

- crates/hir-def/src/item_tree/tests.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/visibility.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/tests/special.rs
Prior to this, the item tree lowered `pub(self)` visibility to `pub()`
Fix #15134 - tested with a unit test and 
a manual end-to-end test of building rust-analyzer from my branch and opening the reproduction repository
> fix: Fix item tree lowering pub(self) to pub()

- crates/hir-def/src/resolver.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-db/src/path_transform.rs
This PR makes the delegate method assist resolve any `Self` type references in the parameters or return type. It also works across macros such as the `uint_impl!` macro used for `saturating_mul` in the issue example.
Closes #14485
> fix: resolve Self type references in delegate method assist

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/unresolved_extern_crate.rs
fix #16063 
I looked at the other usages of `doc_comments_and_attrs` and it seems all of them are prone to ignoring inner attributes. @Veykril should I replace all of those with `collect_attrs` and remove `doc_comments_and_attrs` (or even `HasDocComments`) entirely?
> Replace `doc_comments_and_attrs` with `collect_attrs`

- crates/ide/src/interpret_function.rs
- crates/ide/src/view_hir.rs
- crates/ide/src/view_mir.rs
I broke the view ones completely by inverting the macro check by accident a few days ago but we don't talk about that.
> fix: Fix view mir, hir and eval function not working when cursor is inside macros

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/trait_impl_missing_assoc_item.rs
Negative impls can't have items, so there is no reason for this diagnostic.
LMK if I should add a test somewhere. Also LMK if that's not how we usually check multiple things in an if in r-a.
> fix: Don't emit "missing items" diagnostic for negative impls

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers/request.rs
This way, parameter hints will be found for resolution and https://github.com/rust-lang/rust-analyzer/pull/15522#issuecomment-1835896335 will be fixed
Hopefully that also helps with whatever else (lifetimes', etc.) hints in 
https://github.com/rust-lang/rust-analyzer/issues/13962
> hints are resolved by querying for textDocument/inlayHint with hint's position turned into a [position-1, position+1] range (instead of the original, much wider document range).
>
> This might lead to issues in the future, with e.g. lifetime hints (currently there's nothing to resolve for them and it's fine) that belong to a certain position, but need to have textDocument/inlayHint query for much bigger range than their position+/-1
> Query for nearest parent block around the hint to resolve

- crates/hir-def/src/import_map.rs
- crates/ide-db/src/items_locator.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
No test case as creating one is kind of tricky... Ideally the code should be restructured such that this collision wouldn't matter in the first place, its kind of a mess.
Fixes https://github.com/rust-lang/rust-analyzer/issues/16074
Fixes https://github.com/rust-lang/rust-analyzer/issues/16080
Fixes https://github.com/rust-lang/rust-analyzer/issues/15845
> fix: Fix `import_map::search_dependencies` getting confused by assoc and non assoc items with the same name

- crates/hir-expand/src/span.rs
- crates/mbe/src/syntax_bridge.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16097
Fixes https://github.com/rust-lang/rust-analyzer/issues/16103
> fix: Fix syntax bridge assigning invalid span to lifetime tokens

- crates/hir-def/src/import_map.rs
- crates/ide-db/src/items_locator.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
https://github.com/rust-lang/rust-analyzer/pull/16101 has severe perf regressions unfortunately, so this reverts the part that fixed the issues for now.
> internal: Partially revert #16101

- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/mbe/src/tt_iter.rs
Notably, this caused some completions in the `vec!` macro to no longer work. Fixes https://github.com/rust-lang/rust-analyzer/issues/15016
> fix: Fix fragment parser replacing matches with dummies on incomplete parses

- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
Fixes #15630.
Complements #13647 (same assist but missed this one), #14920 (inverse action assist).
> Fix incorrectly replacing references in macro invocation in "Convert to named struct" assist

- crates/base-db/src/span.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/fixup.rs
- crates/rust-analyzer/src/config.rs
- crates/vfs/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16118
> fix: Syntax fixup now removes subtrees with fake spans

- crates/hir-def/src/generics.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/resolver.rs
- crates/hir-expand/src/eager.rs
- crates/hir-expand/src/lib.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/incremental.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
It only exists due to the IDE layer, but we can encode this temporary hack more cleanly
> internal: Remove `ModuleId` from `TypeOwnerId`

- xtask/src/release/changelog.rs
> internal: Don't fail changelog generation on missing PRs

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/patterns.rs
> fix: resolve alias before resolve variant

- crates/base-db/src/input.rs
- crates/hir-def/src/nameres/collector.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/project_json.rs
> internal: Add minimal support for the 2024 edition

- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/mbe/src/syntax_bridge.rs
Fixes #16110.
The way rust desugars doc comments when expanding macros is rendering it as raw strings delimited with hashes. Rust-analyzer wasn't aware of this, so the desugared doc comments wouldn't match correctly when on the LHS of macro declarations.
This PR fixes this by porting the code used by rustc:
https://github.com/rust-lang/rust/blob/59096cdad0e527ce4d254b55aca58539f726d3d6/compiler/rustc_ast/src/tokenstream.rs#L662-L671
> fix(mbe): desugar doc correctly for mbe

- crates/ide/src/markdown_remove.rs
After markdown syntax removal the length of the text is roughly the same so we can reserve memory beforehand
> minor: Use reserve when removing markdown from text

- crates/hir-expand/src/files.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/generate_enum_variant.rs
- crates/ide-db/src/rename.rs
- crates/ide/src/annotations.rs
- crates/ide/src/goto_implementation.rs
- crates/span/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16157
> fix: Deduplicate annotations

- editors/code/package-lock.json
- editors/code/package.json
> minor: Bump `@vscode/test-electron`

- editors/code/src/debug.ts
Hello,
This pull request introduces a modest performance improvement by executing asynchronous tasks using `Promise.all`, thereby enhancing the efficient utilization of hardware resources.
Thank you for considering this enhancement.
Ref-: https://github.com/rust-lang/rust/pull/119108
> minor: Optimizing Performance with `Promise.all` 🏎

- crates/ide-assists/src/handlers/remove_unused_imports.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/node_ext.rs
> fix: auto remove unnecessary braces after remove unused imports

- crates/hir-def/src/attr.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/db.rs
- crates/hir-def/src/expander.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/macro_expansion_tests/mod.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/attr_resolution.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/ast_id_map.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/eager.rs
- crates/hir-expand/src/lib.rs
- crates/hir-expand/src/span_map.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir/src/symbols.rs
This slows down analysis by 2-3s on self for me unfortunately (~2.5% slowdown)
Noisy diff due to two simple refactoring in the first 2 commits. Relevant changes are [7d762d1](https://github.com/rust-lang/rust-analyzer/pull/16175/commits/7d762d18edb1b05343c7725af54f15ce81cd12de) and [1e1113c](https://github.com/rust-lang/rust-analyzer/pull/16175/commits/1e1113cf5f7318cae702bc31ab5155c24fade6f4) which introduce def site spans and correct marking for proc-macros respectively.
> fix: Correctly set and mark the proc-macro spans

- crates/ide-completion/src/completions/attribute.rs
- crates/ide-completion/src/completions/attribute/macro_use.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/ide/src/goto_definition.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/15657.
Originally added a test case for incomplete input:
```rust
#[test]
fn completes_incomplete_syntax() {
check(
r#"
//- /dep.rs crate:dep
#[macro_export]
macro_rules! foo {
() => {};
}
//- /main.rs crate:main deps:dep
#[macro_use($0
extern crate dep;
"#,
expect![[r#"
ma foo
"#]],
)
}
```
but couldn't make it pass and removed it 😅 Our current recovering logic doesn't work for token trees and for this code:
```rust
#[macro_use(
extern crate lazy_static;
fn main() {}
```
we ended up with this syntax tree:
```
SOURCE_FILE@0..53
ATTR@0..52
POUND@0..1 "#"
L_BRACK@1..2 "["
META@2..52
PATH@2..11
PATH_SEGMENT@2..11
NAME_REF@2..11
IDENT@2..11 "macro_use"
TOKEN_TREE@11..52
L_PAREN@11..12 "("
WHITESPACE@12..13 "\n"
EXTERN_KW@13..19 "extern" …
```
> Complete exported macros in `#[macro_use($0)]`

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- docs/dev/lsp-extensions.md
- lib/lsp-server/Cargo.toml
Prior to this, the symbol search would always jump to the defining macro call, not it jumps to the name in the macro call input if possible. This is a large improvement for assoc items in an attribute impl or trait.
> internal: Update world symbols request definiton, prefer focus range for macros

- crates/ide-completion/src/context/analysis.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16161
> fix: Fix completions analysis not caching all nodes in Semantics

- crates/ide-assists/src/handlers/remove_unused_imports.rs
- crates/syntax/src/ast/node_ext.rs
follow up https://github.com/rust-lang/rust-analyzer/pull/16066, close https://github.com/rust-lang/rust-analyzer/issues/16181
> fix: remove wrong comma after remove unnecessary braces

- crates/ide-diagnostics/src/handlers/trait_impl_redundant_assoc_item.rs
add a small test case to ensure that we don't emit `trait_impl_redundant_assoc_item` diagnostic for negative impl trait
> add test case for negative impl

- editors/code/package.json
Corrected the `rust-panic` task problem matcher for the VSCode Extension to match the new panic message pattern.
From:
```
thread 'main' panicked at 'PANIC_MESSAGE', src/main.rs:L:C
```
To:
```
thread 'main' panicked at src/main.rs:L:C:
PANIC_MESSAGE
```
> fix: update VSCode rust-panic problem matcher

- crates/hir-expand/src/hygiene.rs
Fixes #16200
I don't fully understand these changes, I just applied and tested the changes suggested in #16200 and they seem to fix the issue on both the repro and my original project.
> fix: Fix out-of-bounds panic in some macros due to unhandled self_ref

- Cargo.lock
- Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- lib/lsp-server/Cargo.toml
- lib/lsp-server/examples/goto_def.rs
- lib/lsp-server/src/error.rs
- lib/lsp-server/src/lib.rs
- lib/lsp-server/src/msg.rs
- lib/lsp-server/src/stdio.rs
Not the best way to expose this, but this should allow us to give somewhat better errors when the initialization request is malformed, as currently that just results in a channel disconnected error instead of the deserialization error. cc https://github.com/rust-lang/rust-analyzer/issues/15859
> internal: Expose whether a channel has been dropped in lsp-server errors

- crates/ide-assists/src/handlers/bool_to_enum.rs
- crates/ide-assists/src/handlers/promote_local_to_const.rs
- crates/ide-assists/src/utils.rs
When we try to make a syntax node mutable inside a macro to edit it, it seems like the edits aren't properly reflected and will cause a panic when trying to make another syntax node mutable. 
This PR changes `bool_to_enum` and `promote_local_to_const` to use the original syntax range instead to edit the original file instead of the macro file. I'm not sure how to do it for `inline_call` with the example I mentioned in the issue, so I've left it out for now.
Fixes #15807
> fix: assists panic when trying to edit usage inside macro

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Related: #15033
I need some advice on how to test it.
> feat: add proc-macro rebuild on save option

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
When reading the manual, I noticed that the documentation referenced configurations that have since been renamed. This PR updates those references to their new names.
> fix: Correct references from `rust-analyzer.cargo.check` to `rust-analyzer.check`

- crates/ide-completion/src/completions/dot.rs
Follow up PR for #15879 
Fixes the callable field completion appearing in the method access with no parens case.
> fix: make callable fields not complete in method access no parens case

- crates/ide-db/src/documentation.rs
Don't trim trailing whitespace from doc comments as multiple trailing spaces indicates a hard line break in Markdown.
I'd have liked to add a unit test for `docs_from_attrs`, but couldn't find a reasonable way to get an `&Attrs` object for use in the test.
Fixes #15877.
> Don't trim trailing whitespace from doc comments

- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
- crates/ide-assists/src/tests.rs
Continuing from #15874
- `extract_variable`
- `generate_function`
- `replace_is_some_with_if_let_some`
- `replace_is_ok_with_if_let_ok`
> internal: Migrate assists to the structured snippet API, part 5

- crates/ide-assists/src/handlers/inline_call.rs
Fix #16113, fix #16091
The problem described in this issue actually involves three bugs.
Firstly, when using `ted` to modify the syntax tree, the offset of nodes on the tree changes, which causes the syntax range information from `hir` to become invalid. Therefore, we need to edit the AST after the last usage for `usages_for_locals`.
The second issue is that when inserting nodes, it's necessary to use `clone_subtree` for duplication because the `ted::replace` operation essentially moves a node.
The third issue is that we should use `ancestors_with_macros` instead of `ancestors` to handle impl definition in macros.
I have fixed the three bugs mentioned above and added unit tests.
> fix: self type replacement in inline-function

- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-assists/src/utils/suggest_name.rs
- crates/ide-db/src/path_transform.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/node_ext.rs
I've made substantial enhancements to the "generate delegate trait" code action in rust-analyzer. Here's a summary of the changes:
Fix #15804, fix #15968, fix #15108
The issue stemmed from an incorrect application of PathTransform in the original code. Previously, a new 'impl' was generated first and then transformed, causing PathTransform to fail in locating the correct AST node, resulting in an error. I rectified this by performing the transformation before generating the new 'impl' (using make::impl_trait), ensuring a step-by-step transformation of associated items.
`generate_delegate_trait` is unable to properly handle trait with `Self` type.
Let's take the following code as an example:
```rust
trait Trait {
fn f() -> Self;
}
struct B {}
impl Trait for B {
fn f() -> B { B{} }
}
struct …
```
> fix: rewrite code_action `generate_delegate_trait`

- crates/hir/src/lib.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
This commit changes how the expected type is calculated when
working with Fn pointers, making the parenthesis stop vanishing
when completing the function name.
I've been bugged by the behavior of parenthesis completion for
a long while now. R-a assumes that the `LetStmt` type is the same
as the function type I've just written. Worse is that all parenthesis
vanish, even from functions that have completely different signatures.
It will now verify if the signature is the same.
While working on this, I noticed that record fields behave the same,
so I also made it prioritize the field type instead of the current
expression when possible, but I'm unsure if this is OK, so input is
appreciated.
ImplTraits as return types will still behave weirdly because lowering
is disallowed at the time it …
> fix(completion): make the expected type a tad smarter with `Fn`s

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/unresolved_method.rs
close https://github.com/rust-lang/rust-analyzer/issues/13247
EDIT: I think add a demo gif would be helpful to @lnicola when he make a release change log :)
> feat: add assoc func quickfix for `unresolved_method` diagnostic

- crates/hir/src/symbols.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
> Make functions in impl have a container name

- crates/hir-expand/src/lib.rs
- crates/ide/src/navigation_target.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16229
> fix: Fix focus range being discarded in attributes/derives when upmapping

- docs/user/manual.adoc
No need to install the guru overlay to install rust-analyzer. This is now installed based on use flag settings for dev-lang/rust and dev-lang/rust-bin. This pull request changes the instructions in the user manual.
Note: rust-analyzer is not available in the guru repository, so the old instructions no longer work.
> Updated instructions for installing rust-analyzer under Gentoo.

- docs/user/manual.adoc
CC https://github.com/rust-lang/rust-analyzer/pull/15922#discussion_r1398224723
> Tweak Gentoo instructions

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/hir.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/mutability.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir-ty/src/tests/traits.rs
Closes #15842.
This issue arises because `K` is ambiguous if only inferred from `Index` trait, but is unique if inferred from `IndexMut`, but r-a doesn't use this info.
> fix: try obligation of `IndexMut` when infer

- crates/hir/src/attrs.rs
- crates/hir/src/lib.rs
- crates/ide/src/doc_links/tests.rs
This partially fixes #9694.
Supported:
- Trait methods and constants.
* Due to resolution differences pointed out during the review of the PR, trait associated types are _not_ supported.
- Inherent methods, constants and associated types.
* Inherent associated types are a [nightly feature](https://github.com/rust-lang/rust/issues/8995), and are supported with no additional work in this PR.
Screenshot of VS Code running with the change:
You can see that the items are resolved (excl. trait associated types) since they are semantically highlighted in the doc comment.
> feat: resolve inherent and implemented associated items in docs

- crates/span/Cargo.toml
CC https://github.com/rust-lang/rust-analyzer/actions/runs/7408827766/job/20157836624
> minor: Add description to span crate manifest

- crates/ide/src/rename.rs
This PR switches from `assert_debug_eq` to `assert_eq` and only compares parts of the result and not the whole. The aim is to only compare parts which are relevant to the test and also make it more readable.
Part of #14268.
I assume I cannot because of: https://github.com/rust-lang/rust-analyzer/blob/c3a00b5468576de4e39adc8fa5ceae35a0024e49/docs/dev/architecture.md?plain=1#L413
```
file_id 1:
source_file_edits: 
- Indel { insert: "foo2", delete: 4..7 }
file_id 2:
file_system_edits:
MoveFile AnchoredPathBuf { anchor: FileId(2), path: "foo2.rs", }
```
> internal: Switch to `expected.assert_eq` for `ide` tests

- crates/project-model/src/sysroot.rs
Somehow r-a believed that my sysroot was something weird with no rustc. Probably a me issue, but it was impossible to diagnose since r-a just gave me a plain "No such file or directory". Adding this error makes it clear what happened and allows diagnosing the problem.
> Give a userful error when rustc cannot be found in explicit sysroot

- crates/hir-def/src/import_map.rs
- crates/stdx/src/lib.rs
Second attempt, this time with a lot of perf improvements
Fixes https://github.com/rust-lang/rust-analyzer/issues/16080
Fixes https://github.com/rust-lang/rust-analyzer/issues/16074
Fixes https://github.com/rust-lang/rust-analyzer/issues/15845
The main bottleneck for flyimport completions are now import path calculation and completion item rendering.
> internal: Rewrite `ImportMap::search_dependencies`

- crates/ide-diagnostics/src/handlers/unresolved_module.rs
- crates/ide-diagnostics/src/tests.rs
Part of https://github.com/rust-lang/rust-analyzer/issues/14268.
> internal: Replace only occurence of `check_expect` with `check_diagnostics`

- crates/hir-def/src/import_map.rs
- crates/hir/src/symbols.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-completion/src/lib.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/items_locator.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide/src/lib.rs
- crates/ide/src/navigation_target.rs
- crates/rust-analyzer/src/handlers/request.rs
Prior we calculated up to `limit` entries from a query, then filtered from that leaving us with less entries than the limit in some cases (which might give odd completion behavior due to items disappearing). This changes it so we filter before checking the limit.
> internal: Move query limits to the caller

- docs/user/manual.adoc
Based on feedback from the Gentoo repository maintainer, addition of the possibility to install rust-analyzer via rustup.
> Further tuning of the Gentoo installation instructions.

- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16075
The < 3 char limit never applied to methods and the amount of completions generated due this is not absolutely massive as not all traits in a project are ever applicable so there is little reason to employ the limit here. Especially as it limits the number of traits we consider, not items (after my changes yesterday), and the number of traits is not the slowing factor here. Tested this in r-a where we have ~800 traits project wide and even when ~260 are applicable there was no noticable slow down from it.
> Remove completion limit for trait importing method completions

- crates/ide-assists/src/handlers/auto_import.rs
- crates/ide-assists/src/handlers/qualify_path.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
Pushes the sorting to the caller, meaning additional filtering can be done pre-sorting. Similarly a collect call was pushed to the caller for allowing some other filters to run pre-collecting.
> internal: Speed up import searching some more

- crates/ide-diagnostics/src/handlers/trait_impl_redundant_assoc_item.rs
Happy New Year 😊
follow up https://github.com/rust-lang/rust-analyzer/pull/15990, now it's time to close https://github.com/rust-lang/rust-analyzer/issues/15958, closes https://github.com/rust-lang/rust-analyzer/issues/16269
EDIT: add a demo.git would be more illustrated when making release change log.
> feat: add quickfix for redundant_assoc_item diagnostic

- crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
close https://github.com/rust-lang/rust-analyzer/issues/16197
> fix: `extract_struct_from_enum_variant` assist should resolve Self generic arg

- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
Continue from #16112
This PR primarily involves some cleanup and simple refactoring work, including:
- Adding numerous comments to layer the code and explain the behavior of each step.
- Renaming some variables to make them more sensible.
- Simplify certain operations using a more elegant approach.
The goal is to make this intricate implementation clearer and facilitate future maintenance.
In addition to this, the PR also removes redundant `path_transform` operations for `type_gen_args`.
Taking the example of `impl Trait<T1> for S<S1>`, where `S1` is considered. The struct `S` must be in the file where the user triggers code actions, so there's no need for the `path_transform`. Furthermore, before performing the transform, we've already renamed `S1`, ensuring it won't clash with existing …
> internal: clean and enhance readability for `generate_delegate_trait`

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/runnables.rs
This PR limits the data being compared. Therefore the tests should be more readable, as well as being more robust to changes to the data structure.
Part of https://github.com/rust-lang/rust-analyzer/issues/14268.
> internal: Only compare relevant parts in  `ide::{runnables,inlay_hints}` tests

- crates/hir-def/src/body/lower.rs
- crates/ide-assists/src/handlers/convert_let_else_to_match.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/range_exclusive.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/node_ext.rs
- crates/syntax/src/ast/prec.rs
- crates/syntax/src/validation.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Adds an inlay hint containing a '<' character to exclusive range expressions and patterns that specify an upper bound.
Inspired by [this comment](https://github.com/rust-lang/rust/issues/37854#issuecomment-1865124907) noting that IntelliJ Rust has this feature.
> feat: Add inlay hint for exclusive ranges

- lib/line-index/README.md
> line-index: Create README.md

- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/mem_docs.rs
- crates/rust-analyzer/src/reload.rs
- crates/vfs/src/lib.rs
Turns out there is no need to keep the files around. We either upload them to salsa once processed, or we need to keep them around for the `DidChangeTextDocumentNotification`, but that notification is only valid for opened documents, so instead we can just keep the files around in the `MemDocs`!
Fixes https://github.com/rust-lang/rust-analyzer/issues/16301
> internal: VFS no longer stores all source files in memory

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-expand/src/quote.rs
- crates/hir-ty/src/tests/macros.rs
- crates/ide/src/expand_macro.rs
- crates/test-utils/src/minicore.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/16295
> Builtin derives are hygienic

- docs/dev/syntax.md
While reading through the docs I came across these two small typos.
> minor: Remove newline and add dot in syntax docs

- crates/load-cargo/src/lib.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/loader.rs
Kind of fixes https://github.com/rust-lang/rust-analyzer/issues/14730 in a pretty bad way. We need to rethink the vfs-notify layer entirely. For a decent fix.
> fix: Differentiate between vfs config load and file changed events

- crates/ide-assists/src/handlers/generate_constant.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/syntax/src/ast/node_ext.rs
calling `ast::Path::segments` on a qualifier currently returns all the segments of the top path instead of just the segments of the qualifier.
The issue can be summarized by the simple failing test below:
```rust
#[test]
fn path_segments() {
//use ra_ap_syntax::ast;
let path: ast::Path = ...; // e.g. `ast::Path` for "foo::bar::item".
let path_segments: Vec<_> = path.segments().collect();
let qualifier_segments: Vec<_> = path.qualifier().unwrap().segments().collect();
assert_eq!(path_segments.len(), qualifier_segments.len() + 1); // Fails because `LHS = RHS`.
}
```
This PR:
- Fixes the implementation of `ast::Path::segments`
- Fixes `ast::Path::segments` callers that either implicitly relied on behavior of previous implementation or exhibited other "wrong" behavior directly related to the …
> fix: Fix `ast::Path::segments` implementation

- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-db/src/path_transform.rs
Fixes #16276
This PR addresses two issues:
1. When using `PathTransform`, it searches for the node corresponding to the `path` in the `source_scope` during `make::fn_`. Therefore, we need to perform the transform before `make::fn_` (similar to the problem in issue #15804). Otherwise, even though the tokens are the same, their offsets (i.e., `span`) differ, resulting in the error "Can't find CONST_ARG@xxx."
2. As mentioned in the first point, `PathTransform` searches for the node corresponding to the `path` in the `source_scope`. Thus, when transforming paths, we should update nodes from right to left (i.e., use **reverse of preorder** (right -> left -> root) instead of **postorder** (left -> right -> root)). Reasons are as follows:
In the red-green tree (rowan), we do not store absolute …
> Resolve panic in `generate_delegate_methods`

- crates/ide-assists/src/handlers/extract_function.rs
Fix #14371 
Preserve comments for extracted block expression in 'extract_function'.
In the original implementation, `block.statements()` was used to construct a new function, removing the comments within the block. In the updated implementation, we use manual traversal of nodes and `hacky_block_expr` to generate a new block, thereby preserving the comments.
> Preserve comments for extracted block expression in 'extract_function'

- crates/proc-macro-srv/Cargo.toml
- crates/proc-macro-srv/proc-macro-test/Cargo.toml
- crates/proc-macro-srv/proc-macro-test/build.rs
- crates/proc-macro-srv/proc-macro-test/imp/Cargo.toml
- crates/proc-macro-srv/proc-macro-test/imp/src/lib.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/16194
> Remove sysroot-abi feature flag from proc-macro-test

- crates/ide-diagnostics/src/handlers/unresolved_assoc_item.rs
- crates/ide-diagnostics/src/lib.rs
Per #16327 unresolved associated item has false positives.  Mark the diagnostic as experimental until this is more dependable.
> minor: Mark unresolved associated item diagnostic as experimental

- crates/base-db/src/lib.rs
- crates/hir-def/src/test_db.rs
- crates/hir-ty/src/test_db.rs
- crates/hir/src/symbols.rs
- crates/ide-db/src/lib.rs
We only iterate over the result, and its pretty small in general so no point for the `HashSet` (additionally this way we get a more defined iteration order).
> Replace SourceRootCrates hashset output with slice for deterministic order

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/visibility.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-ty/src/display.rs
- crates/ide-assists/src/handlers/auto_import.rs
- crates/ide-db/src/search.rs
rust-analyzer has logic that discounts suggesting `use`s for private imports, but that logic is unnecessarily strict - for instance given this code:
```rust
mod foo {
pub struct Foo;
}
pub(crate) use self::foo::*;
mod bar {
fn main() {
Foo$0;
}
}
```
... RA will suggest to add `use crate::foo::Foo;`, which not only makes the code overly verbose (especially in larger code bases), but also is disjoint with what rustc itself suggests.
This commit adjusts the logic, so that `pub(crate)` imports are taken into account when generating the suggestions; considering rustc's behavior, I think this change doesn't warrant any extra configuration flag.
Note that this is my first commit to RA, so I guess the approach taken here might be suboptimal - certainly feels somewhat hacky, maybe there's some …
> fix: Acknowledge `pub(crate)` imports in import suggestions

- crates/base-db/src/lib.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/child_by_source.rs
- crates/hir-def/src/find_path.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/resolver.rs
- crates/hir-def/src/visibility.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
Builds on top of https://github.com/rust-lang/rust-analyzer/pull/16265 to make things a bit more general, now we consider all explicit private imports.
> internal: Consider all kinds of explicit private imports in find_path

- crates/hir-def/src/nameres/tests/macros.rs
- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-expand/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16109
> fix: Fix nested includes resolving from the wrong base file

- docs/user/manual.adoc
Helpful for https://github.com/rust-lang/www.rust-lang.org/pull/1915 so we have a persistent place to link as "Visual Studio" from the Rust website.
Syntax reference: https://docs.asciidoctor.org/asciidoc/latest/sections/custom-ids/#assign-auxiliary-ids
> Add a stable #visual-studio anchor to the Manual

- crates/base-db/src/input.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/project-model/test_data/output/rust_project_hello_world_project_model.txt
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
cc https://github.com/rust-lang/rust-analyzer/issues/7637
This takes the approach of having `cargo metadata` generate a lock file that we then delete again, hence why this is behind a flag. If people need this for their workflow they can just enable it, if not, they are probably better off keeping it disabled. [example](https://dreampuf.github.io/GraphvizOnline/#digraph%20rust_analyzer_crate_graph%20%7B%0A%20%20%20%20_0%5Blabel%3D%22core%22%5D%5Bshape%3D%22box%22%5D%3B%0A%20%20%20%20_17%5Blabel%3D%22ra_playground%22%5D%5Bshape%3D%22box%22%5D%3B%0A%20%20%20%20_14%5Blabel%3D%22getopts%22%5D%5Bshape%3D%22box%22%5D%3B%0A%20%20%20%20_11%5Blabel%3D%22std_detect%22%5D%5Bshape%3D%22box%22%5D%3B%0A%20%20%20%20_8%5Blabel%3D%22unwind%22%5D%5Bshape%3D%22box%22%5D%3B%0A%20%20%20%20_5%5Blabel%3D%22hashb …
> internal: Add unstable config for loading the sysroot sources via `cargo metadata`

- Cargo.lock
- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/hir.rs
- crates/hir-def/src/lang_item.rs
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/builder.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/mapping.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/borrowck.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/monomorphization.rs
- crates/hir-ty/src/tests/coercion.rs
- crates/hir-ty/src/tests/simple.rs
- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/generate_enum_is_method.rs
- crates/ide-db/src/apply_change.rs
- crates/ide-db/src/generated/lints.rs
- crates/ide-db/src/lib.rs
- crates/test-utils/src/minicore.rs
Follow the rename in nightly (see https://blog.rust-lang.org/inside-rust/2023/10/23/coroutines.html)
This makes it much easier to test code with the nightly compiler.
> Rename generator to coroutine

- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/loader.rs
This changes the `Roots Scanned` message to include the directory being scanned.
Before: `Roots Scanned 206/210 (98%)`
After: `Roots Scanned 206/210: .direnv (98%)`
This makes it a lot easier to tell that `rust-analyzer` isn't crashed, it's just trying to scan a huge directory.
See: #12613
> Show which roots are being scanned in progress messages

- crates/ide-assists/src/handlers/bool_to_enum.rs
- crates/ide-assists/src/handlers/merge_imports.rs
- crates/ide-assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ide-db/src/imports/insert_use.rs
- crates/ide-db/src/imports/insert_use/tests.rs
- crates/ide-db/src/imports/merge_imports.rs
- crates/stdx/src/lib.rs
Updates use tree ordering and merging utilities to follow rustfmt's algorithm for ordering imports.
The [rustfmt implementation](https://github.com/rust-lang/rustfmt/blob/6356fca675bd756d71f5c123cd053d17b16c573e/src/imports.rs) was used as reference.
> internal: Follow rustfmt's algorithm for ordering imports when ordering and merging use trees

- crates/ide-assists/src/handlers/inline_call.rs
- crates/syntax/src/ast/make.rs
fix #15470.
The current `inline_call` directly translates `&self` into `let ref this = ...;` and `&mut self` into `let ref mut this = ...;`. However, it does not handle some complex scenarios.
This PR addresses the following transformations (assuming the receiving object is `obj`):
- `self`: `let this = obj`
- `mut self`: `let mut this = obj`
- `&self`: `let this = &obj`
- `&mut self`
+ If `obj` is `let mut obj = ...`, use a mutable reference: `let this = &mut obj`
+ If `obj` is `let obj = &mut ...;`, perform a reborrow: `let this = &mut *obj`
> fix: better handling of SelfParam in assist 'inline_call'

- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/loader.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16382
> fix: Fix progress reporting getting stuck

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/line_index.rs
See https://github.com/rust-lang/rust-analyzer/issues/13538
> internal: speedup LineEndings calculation using 'memchr'

- crates/ide-db/src/rename.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide/src/lib.rs
- crates/ide/src/rename.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- docs/user/generated_config.adoc
- editors/code/package.json
With #15656 we started disallowing renaming of non-local items. Although this makes sense there are some false positives that impacted users' workflows. So this config aims to mitigate this by giving users the liberty to disable this feature.
The reason why this is a draft is that I saw one of the tests fail and I am not sure if the "got" result even syntactically makes sense 
Test case is :
```rust
check(
"Baz",
r#"
//- /lib.rs crate:lib new_source_root:library
pub struct S;
//- /main.rs crate:main deps:lib new_source_root:local
use lib::S$0;
"#,
"use lib::Baz;"
);
```
```
Left:
use lib::Baz;
Right:
use lib::Baz;Baz
Diff:
use lib::Baz;Baz
```
> Add a new config to allow renaming of non-local defs

- crates/ide-assists/src/handlers/auto_import.rs
- crates/ide-assists/src/handlers/merge_imports.rs
- crates/ide-assists/src/tests.rs
- crates/ide-db/src/imports/insert_use.rs
- crates/ide-db/src/imports/insert_use/tests.rs
- crates/ide-db/src/imports/merge_imports.rs
- crates/rust-analyzer/src/config.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/node_ext.rs
- editors/code/package.json
Adds a new import granularity option "One" that merges all imports into a single use statement as long as they have the same visibility and attributes.
This is similar to [rustfmt's `imports_granularity = "One"`](https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=import#imports_granularity).
Fixes: #11361
> feat: Add "One" import granularity

- crates/ide-db/src/rename.rs
- crates/ide/src/rename.rs
Even though we changed the name of the config I forgot to update the warning message that referenced it.
> Update bail message referencing config

- crates/ide-assists/src/handlers/extract_struct_from_enum_variant.rs
it panic at `builder.make_mut(segment)`, where segment is from macro expand. And the usage reference in orginal macro call isn't a `PathSegment` so we can't update it in `apply_references`, I can't find a way to deal with it properly so here just filter out the reference in macro. LMK if there are better way to fix this
try to close https://github.com/rust-lang/rust-analyzer/issues/16328
> fix panic with reference in macro

- .editorconfig
This helps with setting proper visual guides/rulers for the right margin in some editors/IDEs (e.g. CLion)
> internal: add `max_line_length` to `.editorconfig`

- crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
For detailed description - see related issue.
Fixes: #16407
> Replaced adjusted_display_range with adjusted_display_range_new in mismatched_arg_count

- crates/hir-def/src/body/lower.rs
- crates/ide-diagnostics/src/handlers/no_such_field.rs
we should filter out field with disabled cfg when lowering ast `RecordPat` to hir.
close https://github.com/rust-lang/rust-analyzer/issues/16169
> fix: filter out cfg disabled filed when lowering `RecordPat`

- crates/ide-completion/src/completions/postfix.rs
Adds a postfix completion for let else syntax, similar to the if let postfix.
> Add postfix completion for let else

- .github/workflows/ci.yaml
- crates/hir-expand/src/attrs.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir/src/attrs.rs
- crates/proc-macro-srv/proc-macro-test/build.rs
> internal: Add `clippy` to CI

- editors/code/language-configuration.json
I changed this thinking the `#` could be considered part of the bracket but on second though I don't think that's quite right in general.
Fixes https://github.com/rust-lang/rust-analyzer/issues/16449
> internal: Undo special bracket classification for attributes in vscode config

- crates/hir-expand/src/db.rs
- crates/hir-expand/src/files.rs
- crates/hir-expand/src/lib.rs
- crates/hir-expand/src/span_map.rs
- crates/hir/src/semantics.rs
- crates/ide-db/src/search.rs
- crates/ide/src/goto_definition.rs
And some follow up simplifications to https://github.com/rust-lang/rust-analyzer/pull/16439
> internal: Remove unnecessary usages of ExpansionInfo

- crates/hir-def/src/hir/format_args.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/utils.rs
- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/generate_mut_trait_impl.rs
- crates/ide-assists/src/handlers/generate_trait_from_impl.rs
- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-db/src/documentation.rs
- crates/ide-diagnostics/src/tests.rs
- crates/ide/src/inlay_hints/implicit_drop.rs
- crates/mbe/src/expander/transcriber.rs
- crates/proc-macro-srv/src/server/rust_analyzer_span.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/node_ext.rs
- docs/dev/syntax.md
- lib/lsp-server/src/error.rs
I use [crate-ci/typos](https://github.com/crate-ci/typos) to check typos in codebase, if it's ok with you, I'd like to add a typo check CI using [typos](https://github.com/crate-ci/typos) (with Apache-2.0, MIT licenses).
BTW, we can add a [_typos.toml](https://github.com/crate-ci/typos/blob/master/docs/reference.md) as white list for some intentional typos
> minor: correct typos

- crates/hir-ty/src/lib.rs
- crates/ide-completion/src/completions/extern_abi.rs
- crates/ide-db/src/generated/lints.rs
This feature was removed in https://github.com/rust-lang/rust/pull/120495
> internal: Remove `abi_amdgpu_kernel` references

- .github/workflows/ci.yaml
- .typos.toml
- crates/hir-def/src/find_path.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/visibility.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/tests/traits.rs
- crates/ide-assists/src/handlers/generate_default_from_new.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/into_to_qualified_from.rs
- crates/ide-db/src/generated/lints.rs
- crates/ide/src/folding_ranges.rs
- crates/mbe/src/syntax_bridge.rs
- crates/proc-macro-api/src/version.rs
- docs/dev/lsp-extensions.md
- docs/dev/style.md
follow up https://github.com/rust-lang/rust-analyzer/pull/16448
> internal: add typos check CI (part 2)

- .github/workflows/release.yaml
> internal: Use MacOS 12 runners for releases

- crates/tt/src/lib.rs
Completely unused, nothing else even shows up when searching for `visit_ids`.
> Remove unused Subtree::visit_ids function

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/visibility.rs
- crates/hir-ty/src/autoderef.rs
- crates/hir-ty/src/builder.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir/src/lib.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
As part of profiling completions, I added some additional spans and moved `TyBuilder::subst_for_def` closer to its usage site (the latter had a small impact on completion performance. Thanks for the tip, Lukas!)
> internal: even more `tracing`

- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/attrs.rs
- crates/hir-expand/src/builtin_attr_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/fixup.rs
- crates/hir-expand/src/lib.rs
- crates/hir-expand/src/quote.rs
- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tt_iter.rs
- crates/proc-macro-api/src/msg.rs
- crates/proc-macro-api/src/msg/flat.rs
- crates/proc-macro-srv/src/server/rust_analyzer_span.rs
- crates/proc-macro-srv/src/server/token_id.rs
- crates/proc-macro-srv/src/server/token_stream.rs
- crates/test-fixture/src/lib.rs
- crates/tt/src/buffer.rs
- crates/tt/src/lib.rs
Performs one of the optimizations suggested in #16325, but a little bit more. Boxed slices guarantee `shrink_to_fit` aswell as saving a pointer width as no capacity has to be stored.  
Most of the diff is:
- Changing `vec![]` to `Box::new([])`
- Changing initialize -> fill into fill -> into_boxed_slice
- Working around the lack of an owned iterator or automatic iteration over a `Box<[T]>`
I would like to use my own crate, [small-fixed-array](https://lib.rs/small-fixed-array), although I understand if it isn't mature enough for this. If I'm given the go ahead, I can rework this PR to use it instead.
> Swap Subtree::token_trees from Vec to boxed slice

- Cargo.lock
- Cargo.toml
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
Just bumping the dependency, as I've been making API changes over on the rustc side. More API changes incoming in the coming weeks.
One benefit of this: we no longer abort in the `DeconstructedPat: Debug` impl, which means we can use `tracing` to investigate issues.
> internal: Update rustc_pattern_analysis dependency

- crates/salsa/salsa-macros/src/query_group.rs
- crates/salsa/src/input.rs
- crates/salsa/src/plumbing.rs
There is no point in having a hashmap and extra lock for this, it is always only a single value. This might speed up some things by a tiny bit for our crate graph query.
> Optimize input queries that take no arguments

- crates/hir-def/src/attr/builtin.rs
- crates/ide-db/src/generated/lints.rs
This feature has just been [removed](https://github.com/rust-lang/rust/pull/120502)
> minor: Remove `ffi_returns_twice` references

- crates/hir/src/display.rs
- crates/ide/src/hover/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16508
> fix: Fix tuple structs not rendering visibility in their fields

- crates/ide-db/src/generated/lints.rs
I was directed to make the fix here by this comment https://github.com/rust-lang/rust/pull/118960#issuecomment-1857888974.
> fix: waker_getters tracking issue from 87021 for 96992.

- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/ide-diagnostics/src/handlers/unresolved_proc_macro.rs
- crates/rust-analyzer/src/reload.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/16331
> Better error message for when proc-macros have not yet been built

- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir/src/diagnostics.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
- crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide-diagnostics/src/tests.rs
> feat: Add "unnecessary else" diagnostic and fix

- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
- crates/ide-diagnostics/src/tests.rs
Updates incorrect case diagnostic to:
- Check traits and their associated items
- Ignore trait implementations except for patterns in associated function bodies
Also cleans up `hir-ty::diagnostics::decl_check` a bit (mostly to make it a bit more DRY and easier to maintain)
Also fixes: #8675 and fixes: #8225
> feat: Add incorrect case diagnostics for traits and their associated items

- crates/ide-assists/src/handlers/generate_getter_or_setter.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-assists/src/utils.rs
> Remove unnecessary `.as_ref()` in generate getter assist

- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/task_pool.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- docs/dev/lsp-extensions.md
- docs/user/generated_config.adoc
- editors/code/package.json
- editors/code/src/ctx.ts
- editors/code/src/lsp_ext.ts
(Note that this branch contains commits from https://github.com/rust-lang/rust-analyzer/pull/15830, which I'll rebase atop of as needed.)
Based on the discussion in https://github.com/rust-lang/rust-analyzer/issues/15837, I've added a notification and off-by-default toggle to send that notification from `handle_did_open_text_document`. I'm happy to rename/tweak this as needed.
I've been using this for a little bit, and it does seem to cause a little bit more indexing/work in rust-analyzer, but it's something that I'll profile as needed, I think.
> feature: Create `UnindexedProject` notification to be sent to the client

- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/generate_getter_or_setter.rs
- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/handlers/generate_new.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/tests.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
Continuing from #16082
- `extract_function`
- `generate_getter_or_setter`
- `generate_impl`
- `generate_new`
- `replace_derive_with_manual_impl`
Would've been the final PR in the structured snippet migration series, but I didn't notice that `generate_trait_from_impl` started to use `{insert,replace}_snippet` when I first started the migration 😅. This appears to be a pretty self-contained change, so I'll leave that for a separate future PR.
This also removes the last usages of `render_snippet`, which was a follow up goal of #11638. 🎉
> internal: Migrate assists to the structured snippet API, part 6/7

- crates/ide-assists/src/handlers/generate_function.rs
@Wilfred reported a crash here shortly after reporting https://github.com/rust-lang/rust-analyzer/issues/16516, which makes us think that the blast radius of ambiguities in Chalk can be larger than expected. This PR tries to be a bit more defensive as a result.
(The 20th frame is the salient frame in the backtrace below.)
<details>
<summary>Backtrace of the crash</summary>
```
request handler panicked: no entry found for key
backtrace:
0: stdx::panic_context::PanicContext::init::{{closure}}::{{closure}}::{{closure}}
at /data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/third-party/rust-analyzer/master/crates/stdx/src/panic_context.rs:32:43
1: stdx::panic_context::with_backtrace::{{closure}}
at /data/sandcastle/boxes/eden-trunk-hg-fbcode-fbsource/third-party/rust-analyzer/master/crates/st …
```
> internal: fix crash inside `filter_unnecessary_bounds` for a missing generic param

- crates/ide-assists/src/handlers/convert_to_guarded_return.rs
I've tried to implement the assist that #16390 talked about
If there are any improvements that I can make in implementation, please suggest them.
> implement convert to guarded return assist for `let` statement with type that implements `std::ops::Try`

- Cargo.toml
- crates/hir-def/src/generics.rs
- crates/hir-def/src/lib.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide/src/inlay_hints/implicit_drop.rs
- crates/ide/src/inlay_hints/range_exclusive.rs
This enables these lints:
- borrowed_box
- derived_hash_with_manual_eq
- forget_non_drop
- needless_doctest_main
> internal: Enable some minor lints that we should tackles (take2)

- crates/hir-def/src/attr.rs
- crates/hir-def/src/child_by_source.rs
- crates/hir-def/src/generics.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/src.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/lower.rs
- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/convert_bool_then.rs
- crates/ide-assists/src/handlers/generate_documentation_template.rs
- crates/ide-assists/src/handlers/into_to_qualified_from.rs
- crates/ide-assists/src/handlers/qualify_path.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/const_.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-completion/src/render/type_alias.rs
- crates/ide-db/src/defs.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/traits.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_declaration.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/runnables.rs
- crates/ide/src/syntax_highlighting/highlight.rs
Allows reducing some code duplication by using functions generic over said structs. The diff isn't negative due to me adding some additional impls for completeness.
> Abstract more over ItemTreeLoc-like structs

- Cargo.lock
- Cargo.toml
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
Here I go again. Two improvements this time.
1. I've removed the need for an arena for patterns. Turns out this wasn't gaining any performance on the rustc side so may as well allocate normally.
2. I've added a clean error path when types don't match, so rustc_pattern_analysis should never panic except internal logic errors. For now `cx.bug()` calls `never!()` but I'm not sure what `never!()` does. Does it display anything to the user? Otherwise a `debug!()` should be sufficient.
Point 2 should fix https://github.com/rust-lang/rust-analyzer/issues/15883 but I haven't tested it because I'm not sure how to reproduce. Could someone give me pointers as to how to write a test for the pattern code?
> Update to latest `rustc_pattern_analysis`

- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/syntax_bridge.rs
- crates/tt/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16529
> fix: Fix macro transcriber emitting incorrect lifetime tokens

- crates/base-db/src/input.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/macro_expansion_tests/mod.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/diagnostics.rs
- crates/hir-expand/src/lib.rs
- crates/hir-expand/src/proc_macro.rs
- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- crates/test-fixture/src/lib.rs
Supersedes #15117, I was having some conflicts after a rebase and since I didn't remember much of it I started clean instead.
The end result is pretty much the same as the linked PR, but instead of proc macro lookups, I marked the expanders that explicitly cannot be expanded and we shouldn't even attempt to do so.
> feat: ignored and disabled macro expansion

- crates/project-model/src/rustc_cfg.rs
- crates/project-model/src/target_data_layout.rs
https://github.com/rust-lang/rust-analyzer/pull/16537 broke this, as `cargo rustc` cannot run against a virtual workspace, so it will always fail in such projects (like rust-analyzer itself). This brings back the plain rustc fallback,
> fix: Fix target layout fetching

- crates/ide-assists/src/lib.rs
- crates/ide/src/lib.rs
- crates/syntax/src/lib.rs
`stdx::eprintln!` was remove in #16465
> minor: remove eprintln! macro

- Cargo.lock
- crates/proc-macro-srv/Cargo.toml
- crates/proc-macro-srv/src/server.rs
- crates/proc-macro-srv/src/server/rust_analyzer_span.rs
- crates/proc-macro-srv/src/server/token_id.rs
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/lib.rs
Closes #16233
Todos and unanswered questions:
> Implement `literal_from_str` for proc macro server

- Cargo.lock
- crates/proc-macro-srv/Cargo.toml
- crates/proc-macro-srv/src/lib.rs
- crates/proc-macro-srv/src/server.rs
- crates/proc-macro-srv/src/server/rust_analyzer_span.rs
- crates/proc-macro-srv/src/server/token_id.rs
- crates/proc-macro-srv/src/tests/mod.rs
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/lib.rs
cc https://github.com/rust-lang/rust-analyzer/pull/16446
meant to only get rid of some string allocs but then I noticed we can just implement this with the bare lexer.
> fix: Validate literals in proc-macro-srv FreeFunctions::literal_from_str

- crates/ide-completion/src/item.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
When typing `MyType::` the completion items' order could be re-ordered based on how likely we want to select those:
* Constructors: `new` like functions to be able to create the type,
* Constructors that take args: Any other function that creates `Self`,
* Builder Methods: any builder methods available,
* Regular methods & associated functions (no change there)
In this photo, the order is:
* `new` constructor is first
* `new_builder` second is a builder method
* `aaaanew` is a constructor that takes arguments, is third  and is irrespective of its alphabetical order among names.
---
Another Example using actix `HttpServer` shows preferring constructor without `self` arg first (the `new` method)
I've dropped my previous idea of highlighting these functions in the rustdoc …
> feat: completion list suggests constructor like & builder methods first

- editors/code/package.json
I believe there is an issue with how rust-analyzer is activated from within a VS Code project.
IIUC, the intent is that when you open a rust project with a top level `Cargo.toml`, then rust-analyzer should just start right up due to a VS Code activation event. This is not currently the case. i.e. run something like `cargo new ~/Desktop/hithere`, then open that folder in VS Code:
https://github.com/rust-lang/rust-analyzer/assets/19150088/1608b985-fd88-4174-a22a-5b3dd0fad84b
It is not until you actually open a Rust file that the extension starts up.
It looks like this was introduced in https://github.com/rust-lang/rust-analyzer/pull/10442. I do agree that recursive searching with `**/` is likely overkill, but I'm not sure `*/Cargo.toml` is working as expected in this comment …
> Activate on top level `Cargo.toml` and `rust-project.json` files

- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-completion/src/tests/type_pos.rs
This is prerequisite PR for adding the assist mentioned in #12500 
P.S: If wanted, I will add the implementation of the assist in this PR as well.
> Add completions to show only traits in trait `impl` statement

- editors/code/src/rust_project.ts
These were documented in #15014 in the manual, but this definition wasn't updated to match.
> Update JsonProject to include optional fields

- crates/project-model/src/sysroot.rs
- xtask/src/metrics.rs
This is pretty hard to discover, and makes the setting useless, we should probably enable it for now.
CC #16486
> internal: Set channel override when querying the sysroot metadata

- crates/flycheck/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/rustc_cfg.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/target_data_layout.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/reload.rs
cc https://github.com/rust-lang/rust-analyzer/pull/16537 should fix https://github.com/rust-lang/rust-analyzer/issues/16561
> fix: Set `RUSTUP_TOOLCHAIN` and invoke the proxies instead of directly invoking sysroot binaries

- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/lib.rs
- crates/hir-expand/src/proc_macro.rs
- crates/ide/src/parent_module.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Also makes proc-macro changed flag setting async, we don't wanna block `process_changes` on the database as that is on the main thread!
> fix: Fix build scripts not being rebuilt in some occasions

- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/scip.rs
Previously, the documentation field was the same as the text shown to users when they hover over that symbol. The documentation should really just be the doc comment, and as of #16179 the signature is already stored in the signatureDocumentation field.
> Set documentation field in SCIP from doc comment

- crates/rust-analyzer/src/lsp/to_proto.rs
> fix: Place snippets correctly in multi-edit assists

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/hir.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/mutability.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide-diagnostics/src/handlers/remove_trailing_return.rs
> fix: Fix "needless return" diagnostic for trailing item declarations

- crates/ide-assists/src/handlers/fix_visibility.rs
- crates/ide-assists/src/handlers/generate_trait_from_impl.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-db/src/source_change.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
Continuing from #16467
- `generate_trait_from_impl`
This adds `add_placeholder_snippet_group`, which adds a group of placeholder snippets which are linked together and allows for renaming generated items without going through a separate rename step.
This also removes the last usages of `SourceChangeBuilder::{insert,replace}_snippet`, as all assists have finally been migrated to the structured snippet versions of those methods.
> internal: Migrate assists to the structured snippet API, part 7/7

- lib/lsp-server/LICENSE-APACHE
- lib/lsp-server/LICENSE-MIT
The `lsp-server` crate is currently published without license files, which is needed when packaging in Linux distributions.
Symlink the files from the repository root so they are kept in sync.
Test showing the files get picked up by `cargo package`:
```
michel in rust-analyzer/lib/lsp-server on  add-lsp-server-license [+] is 📦 v0.7.6 via 🐍 v3.12.1 (.venv311) via 🦀 v1.76.0
⬢ [fedora:39] ❯ cargo package --allow-dirty --no-verify
Updating crates.io index
Packaging lsp-server v0.7.6 (/home/michel/src/github/rust-lang/rust-analyzer/lib/lsp-server)
Updating crates.io index
Packaged 12 files, 59.6KiB (16.3KiB compressed)
michel in rust-analyzer/lib/lsp-server on  add-lsp-server-license [+] is 📦 v0.7.6 via 🐍 v3.12.1 (.venv311) via 🦀 v1.76.0
⬢ [fedora:39] ❯ tar tf …
```
> lsp-server: add license files

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/hir.rs
- crates/hir-expand/src/mod_path.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16572
> fix: Respect textual length of paths in find-path

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/diagnostics.rs
- crates/hir-ty/src/tests/simple.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15704
Basically we zip the two types, inspecting their substitutions if the constructors are the same, if we encounter a zip step with an `{unknown}` on one side and a non-`{unknown}` on the other we error out and discard the diagnostic. Otherwise we keep it.
> fix: Don't show type mismatches for `{unknown}` to non-`{unknown}` mismatches

- .github/workflows/autopublish.yaml
- .github/workflows/ci.yaml
- .github/workflows/fuzz.yml
- .github/workflows/metrics.yaml
- .github/workflows/publish-libs.yaml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
Silences more Node version warnings.
> internal: bump `actions/checkout` to v4

- .github/workflows/ci.yaml
- .github/workflows/metrics.yaml
- .github/workflows/release.yaml
Use newer versions of actions; Node 16 -> 18
Fix several warnings in the actions tab regarding usage of the EOL Node 16
> ci: Update GitHub Actions and Node version

- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/parser/inline/ok/0211_async_trait_bound.rast
- crates/parser/test_data/parser/inline/ok/0211_async_trait_bound.rs
- crates/parser/test_data/parser/inline/ok/0212_const_trait_bound.rast
- crates/parser/test_data/parser/inline/ok/0212_const_trait_bound.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
Both of these bound modifiers were added recently:
* `const` trait bounds: https://github.com/rust-lang/rust/pull/119099
* `async` trait bounds: https://github.com/rust-lang/rust/pull/120392
The latter will certainly will not do the right thing; namely, `async Fn` needs to be mapped to the `AsyncFn` trait. IDK how to do that, so advice would be appreciated, though perhaps we could land this first so the parser isn't complaining about these bounds?
> internal: Parse (nightly) `const` and `async` trait bounds

- crates/rust-analyzer/src/lsp/to_proto.rs
Snippet bits were being escaped before placing snippets, shifting snippets leftwards. Snippets were also being shifted leftwards on files with CRLF line endings since they were placed done after the Unix -> DOS line ending conversion.
Hoping this fixes all of the little bugs related to snippet rendering 😅
> fix: Fix snippets being placed leftwards of where they should be

- editors/code/src/commands.ts
- editors/code/src/snippets.ts
Uses the native VSCode support for `SnippetTextEdit`s. Fixes #13229 and fixes #8531.
https://github.com/rust-lang/rust-analyzer/assets/13354275/a2d2c033-bb30-4f34-92ca-bf3f4f744cdc
This is done in a slightly hacky way, as `vscode-languageclient` can't convert RA's `SnippetTextEdit`s into vscode `SnippetTextEdit`s and will appear to use a [different format](https://github.com/microsoft/vscode-languageserver-node/blob/295aaa393fda8ecce110c38880a00466b9320e63/types/src/main.ts#L1501-L1516) in the future.
---
~~Marked as draft since as-is, this will cause completions to double-indent any multi-line code generated.~~
**Update:** This also fixes up edits so that any multi-line code won't be double-indented.
> feat: Support multiple tab stops for completions in VSCode

- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/stdx/src/lib.rs
EDIT: I wonder if this is a regression, I'll try to investigate.
Commit 6a06f6f72 (Deduplicate reference search results, 2022-11-07)
deduplicates references within each definition.
Apparently our descend_into_macros() stanza returns
one definition for each time a name is used in a macro.
Each of those definitions has the same set of references.
We return them all, leading to many redundant references.
Work around this by deduplicating definitions as well.  Perhaps there
is a better fix to not produce duplicate definitions in the first
place.
I discovered this working with the "bitflags" macro from the crate
of the same name.
Fixes #16357
> Deduplicate references when some of them are in macro expansions

- crates/ide/src/rename.rs
Closes #15858
Implemented:
Future possibilities:
1. Also support `extern crate <name>` syntax.
2. Allow aliasing `self` when it is inside an `UseTreeList`.
~3. If import path already has an alias, "rename" the alias.~
~[4. Create alias even if path is not the last path segment.](https://github.com/rust-lang/rust-analyzer/pull/16489#issuecomment-1930541697)~
> feat!: create alias when renaming an import.

- crates/hir-ty/src/diagnostics/expr.rs
- crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
Completes https://github.com/rust-lang/rust-analyzer/pull/16567 by @ShoyuVanilla (see https://github.com/rust-lang/rust-analyzer/pull/16567#discussion_r1492700667)
Fixes #16556
> fix: Fix false positives for "unnecessary else" diagnostic

- crates/hir-def/src/data/adt.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/tests/coercion.rs
- crates/hir-ty/src/tests/traits.rs
- crates/hir/src/lib.rs
- crates/ide-db/src/apply_change.rs
- crates/ide-db/src/lib.rs
This patch updates some of the partially-implemented functions of `ChalkContext as RustIrDatabase`, namely `adt_datum()` and `impl_provided_for()`. With those, we can now correctly work with auto trait bounds and distinguish methods based on them.
Resolves #7856 (the second code; the first one is resolved by #13074)
**IMPORTANT**: I don't think we want to merge this until #7637 is resolved. Currently this patch introduces A LOT of unknown types and type mismtaches as shown below. This is because we cannot resolve items like `hashbrown::HashMap` in `std` modules, leading to auto trait bounds on them and their dependents unprovable.
|crate (from `rustc-perf@c52ee6` except for r-a)|e3dc5a588f07d6f1d3a0f33051d4af26190abe9e|HEAD of this branch|
|---|---|---|
|rust-analyzer @ …
> Setup infra for handling auto trait bounds disabled due to perf problems

- crates/hir/src/lib.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/16603
> internal: Render assoc item owner in hover for items other than functions

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lsp/utils.rs
- crates/rust-analyzer/src/reload.rs
This should fix https://github.com/rust-lang/rust-analyzer/issues/16614, can't say for certain since it might be not 100% reproducible... We really need to replace the current workspace fetching logic, it is completely unreadable and incredibly difficult to follow. I don't really understand how the server even got to hang here honestly (I would expect it to loop re-fetching build scripts, but not hang).
> fix: server hanging up on build script task

- crates/proc-macro-api/src/process.rs
- crates/proc-macro-srv/src/proc_macros.rs
- crates/proc-macro-srv/src/server.rs
- crates/proc-macro-srv/src/server/rust_analyzer_span.rs
- crates/proc-macro-srv/src/server/token_id.rs
- crates/proc-macro-srv/src/server/token_stream.rs
- crates/proc-macro-srv/src/tests/mod.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16622
Note that this is a bug a in the proc-macro server, so this won't be fixed until the next subtree sync
> fix: Fix proc-macro server not accounting for string delimiters correctly

- crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16614
> fix: Fix deadlock in `recreate_crate_graph` <-> `file_line_index`

- Cargo.lock
- crates/ide-db/src/apply_change.rs
- crates/salsa/Cargo.toml
- crates/salsa/salsa-macros/src/database_storage.rs
- crates/salsa/salsa-macros/src/query_group.rs
- crates/salsa/src/derived.rs
- crates/salsa/src/derived/slot.rs
- crates/salsa/src/durability.rs
- crates/salsa/src/input.rs
- crates/salsa/src/interned.rs
- crates/salsa/src/lib.rs
- crates/salsa/src/plumbing.rs
- crates/salsa/src/revision.rs
- crates/salsa/src/runtime.rs
- crates/salsa/src/runtime/local_state.rs
- crates/salsa/tests/incremental/memoized_volatile.rs
- crates/salsa/tests/on_demand_inputs.rs
- crates/salsa/tests/storage_varieties/tests.rs
Reduces memory on self by ~20mb for me, there is a few more mb to save here if we made LRU caching opt-in, as currently every entry in a memoized query will store an `AtomicUsize` for the LRU.
> internal: Optimize salsa memory usage

- crates/project-model/src/build_scripts.rs
- crates/project-model/src/target_data_layout.rs
Some packages (e.g. thiserror) force a recompile if the value of the `RUSTC_BOOTSTRAP` env var changes. RA sets the variable to 1 in order to enable rustc / cargo unstable options. This causes flapping recompiles when building outside of RA.
Fixes #15057
> fix: Recompiles due to RUSTC_BOOTSTRAP

- crates/salsa/src/derived.rs
This fixes a deadlock introduced by #16643 ([backtrace](https://gist.github.com/davidbarsky/00f17598f5496a9c41aff31fec1c42d6)). `maybe_changed_after` calls back into other queries, so the cloning here is unfortunately inevitable.
(Zulip conversation: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Fixing.20proc-macro.20dirtying.20with.20unindexed.20projects)
> internal: fix deadlock introduced by #16643

- crates/rust-analyzer/src/cli/flags.rs
Minor change to add the `-V` short flag to `rust-analyzer` to bring it in-line with other rust tooling such as:
> rustc -V
```bash
rustc 1.76.0 (07dca489a 2024-02-04)
```
> rustup -V
```bash
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.76.0 (07dca489a 2024-02-04)`
```
> cargo -V
```bash
cargo 1.76.0 (c84b36747 2024-01-18)
```
> Add short flag -V for consistency with other rust tooling

- docs/user/manual.adoc
It took me a few hours to figure out how to enable inlay type hints on Nvim 0.10 with `lspconfig`. `rustaceanvim` has already dropped support for them (https://github.com/mrcjkb/rustaceanvim/discussions/46#discussioncomment-7518669) and most other plugins, like `rust-tools`, are depreciated in favor of `rustaceanvim`.
This PR documents how to enable the inlay hints on Neovim 0.10 and later. I've tested this and changing the `on_attach` function is the only step that is required.
> Document nvim 0.10 `inlay_hint`

- crates/toolchain/src/lib.rs
`get_path_for_executable` will now first check `$CARGO_HOME` before falling back to searching `$PATH`.
`rustup` is the recommended way to manage rust toolchains, therefore should be picked before the system toolchain.
Closes #16661
> Prioritise rustup sysroots over system ones

- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/borrowck.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir-ty/src/mir/pretty.rs
- crates/hir/src/lib.rs
> Merge `BorrowKind::Unique` into `BorrowKind::Mut`

- crates/hir-ty/src/diagnostics/expr.rs
- crates/ide-diagnostics/src/handlers/replace_filter_map_next_with_find_map.rs
close https://github.com/rust-lang/rust-analyzer/issues/16596
> fix: replace_filter_map_next_with_find_map shouldn't work for dyn trait

- .typos.toml
- remove ignored files
- check dotfiles
- reorder config sections: files, regexp, words, IDs
- remove non-existent ignores
> Narrow down typos ignores

- crates/ide-assists/src/handlers/inline_call.rs
Close #16660, #12429, #10695.
When `inline_into_callers` encounters callsites in macros parameters, it can lead to panics. Since there is no perfect way to handle macros, this PR directly filters out these cases.
> fix: panic when inlining callsites inside macros' parameters

- crates/hir/src/diagnostics.rs
- crates/ide-diagnostics/src/handlers/unresolved_ident.rs
Temporary fix for https://github.com/rust-lang/rust-analyzer/issues/16682
We ought to rethink how we attach diagnostics to things, as IDs don't work for `format_args` like that!
> fix: Don't panic on synthetic syntax in inference diagnostics

- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/traits.rs
- crates/hir/src/lib.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
(Continues https://github.com/rust-lang/rust-analyzer/pull/16498)
This PR speeds up method completions by doing two things without regressing `analysis-stats`[^1]:
- Filter candidate traits prior to calling `iterate_path_candidates` by relying on orphan rules (see below for a slightly more in-depth explanation). When generating completions [on `slog::Logger`](https://github.com/oxidecomputer/omicron/blob/5e9e59c312cd787ba50cf6776f220951917dfa14/common/src/ledger.rs#L78) in `oxidecomputer/omicron` as a test, this PR halved my completion times—it's now 454ms cold and 281ms warm. Before this PR, it was 808ms cold and 579ms warm.
- Inline some of the method candidate checks into `is_valid_method_candidate` and remove some unnecessary visibility checks. This was suggested by @Veykril in [this …
> performance: Speed up Method Completions By Taking Advantage of Orphan Rules

- Cargo.toml
- crates/hir-ty/src/method_resolution.rs
- crates/hir/src/semantics.rs
- crates/ide-completion/src/context/analysis.rs
- xtask/src/flags.rs
- xtask/src/install.rs
Unable to figure out a test case for this but managed to run into it in r-a reproducably.
Fixes https://github.com/rust-lang/rust-analyzer/issues/16266 Fixes https://github.com/rust-lang/rust-analyzer/issues/13255
> fix: Fix completions panicking with certain macro setups

- crates/ide-assists/src/handlers/fill_record_pattern_fields.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
I'm not sure if the tests cover the most cases, I'll add more if suggested.
> Add assist for filling fields by replacing ellipsis in record syntax

- crates/hir/src/lib.rs
- crates/hir/src/term_search.rs
- crates/hir/src/term_search/expr.rs
- crates/hir/src/term_search/tactics.rs
- crates/ide-assists/src/handlers/term_search.rs
- crates/ide-completion/src/render.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/16092
Now term search also supports tuples.
```rust
let a: i32 = 1;
let b: f64 = 0.0;
let c: (i32, (f64, i32)) = todo!(); // Finds (a, (b, a))
```
In addition to new tactic that handles tuples I changed how the generics are handled.
Previously it tried all possible options from types we had in scope but now it only tries useful ones that help us directly towards the goal or at least towards calling some other function.
This changes O(2^n) to O(n^2) where n is amount of rounds which in practice allows using types that take generics for multiple rounds (previously limited to 1). Average case that also used to be exponential is now roughly linear.
This means that deeply nested generics also work.
````rust
// Finds all valid combos, …
```
> feat: Add "make tuple" tactic to term search

- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_definition.rs
Fixes #16520
https://github.com/rust-lang/rust-analyzer/blob/a3236be9d7a8179ac4a997858138a4d6c260a451/crates/hir/src/source_analyzer.rs#L375-L393
As we can see from the above, current implementation routes all dereferencing prefix operations to `Deref::deref` implementation, not regarding mutabilities.
https://github.com/rust-lang/rust-analyzer/blob/a3236be9d7a8179ac4a997858138a4d6c260a451/crates/hir-ty/src/infer/mutability.rs#L134-L151
Since we are resolving them already in mutability inferences, we can use those results for proper `deref` / `deref_mut` routing.
> fix: Goto definition for `deref_mut`

- crates/paths/src/lib.rs
There seems to be no ergonomic way to obtain a `RelPathBuf` from a corresponding `&RelPath` at the moment, making the latter sort of a dead end.
The `AbsPath` type provides the following:
```rust
impl AbsPath {
// ...
/// Equivalent of [`Path::to_path_buf`] for `AbsPath`.
pub fn to_path_buf(&self) -> AbsPathBuf {
AbsPathBuf::try_from(self.0.to_path_buf()).unwrap()
}
// ...
}
```
So I took the liberty of adding a corresponding equivalent for `RelPath:
```rust
impl RelPath {
// ...
/// Equivalent of [`Path::to_path_buf`] for `RelPath`.
pub fn to_path_buf(&self) -> RelPathBuf {
RelPathBuf::try_from(self.0.to_path_buf()).unwrap()
}
// ...
}
```
(the change is motivated by an outside use of the `ra_ap_paths` crate that would benefit from being able to use `RelPath` and `AbsPath` over `Path`)
> Add `to_path_buf()` method for `RelPath`

- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_definition.rs
Mostly same with #16696.
https://github.com/rust-lang/rust-analyzer/blob/0ac05c05271f31c43d31017cbd288e8737a0edb0/crates/hir-ty/src/infer/mutability.rs#L103-L133
Thankfully, we are doing similar method resolutions so we can use them like the mentioned PR.
As there are only three `LangItem`s having `Mut` in there names; `FnMut`, `DerefMut` and `IndexMut`, I think that this is the last one 😄
> fix: Goto definition for `index_mut`

- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
- crates/ide-assists/src/handlers/destructure_struct_binding.rs
- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-assists/src/handlers/fill_record_pattern_fields.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-assists/src/utils.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
- crates/ide-assists/src/utils/ref_field_expr.rs
- crates/syntax/src/ast/make.rs
Adds an assist for destructuring a struct in a binding (#8673). I saw that #13997 has been abandoned for a while, so I thought I'd give it a go.
```rust
let foo = Foo { bar: 1, baz: 2 };
let bar2 = foo.bar;
let baz2 = foo.baz;
let foo2 = foo;
let fizz = Fizz(1, 2);
let buzz = fizz.0;
```
becomes
```rust
let Foo { bar, baz } = Foo { bar: 1, baz: 2 };
let bar2 = bar;
let baz2 = baz;
let foo2 = todo!();
let Fizz(_0, _1) = Fizz(1, 2);
let buzz = _0;
```
More examples in the tests.
- `let foo = Foo { bar: 1 }; foo;` currently results in `let Foo { bar } = Foo { bar: 1 }; todo!();` instead of reassembling the struct. This requires user intervention.
- Unused fields are not currently omitted. I thought that this is more ergonomic, as there already is a quick fix action for adding `: _` to unused …
> feature: Add `destructure_struct_binding`

- crates/hir/src/lib.rs
Since `hir::SelfParam`, as well as all members of `hir::Param` already implement `PartialEq`, `Eq` & `Hash` it seems reasonable to also make `hir::Param` implement those.
(the change is motivated by an outside use of the `ra_ap_hir` crate that would benefit from being able to collect params in a `HashSet`)
> Derive `PartialEq`, `Eq` & `Hash` for `hir::Param`

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
(the PR is motivated by an outside use of the `ra_ap_hir` crate that would benefit from being able to walk a `hir::Function`'s AST, resolving callable exprs within to their HIR equivalents)
> Add public function for resolving callable AST exprs to their HIR equivalents

- crates/hir/src/lib.rs
The `SemanticsImpl` type is already de-facto exposed via `<Semantics as Deref>::Target`.
By not being part of the public crate interface it however doesn't get included in the documentation, resulting in a massive blind spot when it comes to `ra_ap_hir`'s type resolution APIs.
> Export `SemanticsImpl` from `ra_ap_hir` crate, since it's already exposed via `Semantics.deref()`

- crates/hir-expand/src/name.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/16734
> minor: Remove outdated comment about static SmolStrs

- editors/code/src/debug.ts
Native Debug doesn't work very well and passing command-line arguments is nasty (https://github.com/rust-lang/rust-analyzer/issues/9815), but I guess it's a start.
Closes #9815
> fix: Add basic support for Native Debug

- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-assists/src/handlers/inline_macro.rs
- crates/ide-db/src/syntax_helpers/insert_whitespace_into_node.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/hover/tests.rs
Partial fix for #16471.
In the previous code, the indentation produced by macro expansion was set to 2 spaces. This PR modifies it to 4 spaces for the sake of consistency.
> fix: use 4 spaces for indentation in macro expansion

- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/move_from_mod_rs.rs
- crates/ide-assists/src/handlers/move_to_mod_rs.rs
- crates/ide-db/src/helpers.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide/src/parent_module.rs
- crates/ide/src/rename.rs
- crates/ide/src/runnables.rs
- crates/ide/src/syntax_highlighting.rs
In order to be able to add these methods with consistent naming I had to also rename two existing methods that would otherwise be conflicting/confusing:
`Semantics::to_module_def(&self, file: FileId) -> Option<Module>` (before)
`Semantics::file_to_module_def(&self, file: FileId) -> Option<Module>` (after)
`Semantics::to_module_defs(&self, file: FileId) -> impl Iterator<Item = Module>` (before)
`Semantics::file_to_module_defs(&self, file: FileId) -> impl Iterator<Item = Module>` (after)
(the PR is motivated by an outside use of the `ra_ap_hir` crate that would benefit from being able to walk a `hir::Function`'s AST, resolving its exprs/stmts/items to their HIR equivalents)
> Add more methods for resolving definitions from AST to their corresponding HIR types

- crates/hir-def/src/data.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/diagnostics.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/files.rs
- crates/ide-diagnostics/src/lib.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/rust-analyzer/src/tracing/hprof.rs
- crates/syntax/src/lib.rs
- crates/syntax/src/tests.rs
- crates/syntax/src/validation.rs
The LRU cache causes us to re-parse trees quite often, yet we don't use the validation errors at all. With this we push calculating them off to the caller who is interested in them.
> internal: Compute syntax validation errors on demand

- crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
cc https://github.com/rust-lang/rust-analyzer/issues/16566#issuecomment-1976492762 https://github.com/rust-lang/rust-analyzer/issues/16628
There seem to be some leftover issues with this, additionally its a style lint so it's not too nice to see for some people. We should flesh out our diagnostics stuff before adding more style lints I think
> minor: Mark remove_unnecessary_else as experimental

- crates/hir-ty/src/display.rs
- crates/hir/src/display.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This PR enable preview assoc items when hover on `trait`
inspired by https://github.com/rust-lang/rust-analyzer/pull/15847
> feat: add hover display for trait assoc items

- crates/hir-ty/src/display.rs
- crates/hir/src/display.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
https://github.com/rust-lang/rust-analyzer/pull/15938 (minor turned major wrt diff because of test changes)
> internal: Adjust a few things for trait assoc item hovers

- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/lib.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fixes https://github.com/rust-lang/rust-analyzer/issues/16542
Fixes https://github.com/rust-lang/rust-analyzer/issues/16725
cc https://github.com/rust-lang/rust-analyzer/issues/16628
Our diagnostic infra is not yet setup for those kinds of diagnostics
> fix: Put style lints behind disabled-by-default config

- .typos.toml
> minor: remove `ignore-hidden = false`

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/hir.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide/src/goto_definition.rs
Fix #15653.
This PR addresses the issue where it was not possible to navigate to constants in range patterns, specifically including two major changes:
1. Previously, both the `start` and `end` fields in `Pat::Range` were of type `LiteralOrConst`. When performing `goto-definition` on constants inside range patterns, r-a would use `resolve_bind_pat_to_const` to find their definitions. However, because the content of a `Const` is not `Pat` but `Path`, it was not stored in the `source_map`, so `resolve_bind_pat_to_const` would returns `None`. This PR changes them to `Const(PatId)`, so that during the lowering process, they are considered as a `pat`, allowing their definitions to be found later through `resolve_bind_pat_to_const`.
2. The process related to range patterns in MIR-lowering has …
> fix: goto-definition for constants inside range pattern

- crates/hir/src/lib.rs
(the PR is motivated by an outside use of the `ra_ap_hir` crate that would benefit from being able to access a `hir::Param`'s/`hir::SelfParam`'s index and parent function)
> Add `fn index()` and `fn parent_fn()` accessors for `hir::Param`/`hir::SelfParam`

- Cargo.toml
- crates/flycheck/src/command.rs
- crates/flycheck/src/lib.rs
- crates/flycheck/src/test_runner.rs
- crates/ide/src/lib.rs
- crates/ide/src/test_explorer.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/hack_recover_crate_name.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/stdx/src/process.rs
- docs/dev/lsp-extensions.md
- editors/code/src/ctx.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/test_explorer.ts
This PR implements the vscode testing api similar to #14589, this time using a set of lsp extensions in order to make it useful for clients other than vscode, and make the vscode client side logic simpler (its now around ~100 line of TS code)
Fix #3601
> Add test explorer

- crates/ide-assists/src/handlers/generate_delegate_trait.rs
fix #15198.
This PR address the issue that `impl` generated by `generate_delegate_trait` doesn't keep attributes.
> fix: keep attributes in assist 'generate_delegate_trait'

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
> fix: Function argument type inference with associated type impl trait

- Cargo.lock
- crates/ide/src/expand_macro.rs
- crates/proc-macro-srv/proc-macro-test/Cargo.toml
- crates/proc-macro-srv/proc-macro-test/build.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/rustc_cfg.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/target_data_layout.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/toolchain/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16754
> For toolchain binaries use the full path found in $PATH

- crates/parser/src/shortcuts.rs
- crates/parser/test_data/parser/err/0054_float_split_scientific_notation.rast
- crates/parser/test_data/parser/err/0054_float_split_scientific_notation.rs
Fix #16278.
This PR fixes the panic caused by using floating-point numbers without a dot (such as `1e2`) in chain calls.
-------------
Although this syntax is very odd 🤣, r-a should not panic.
> fix: panic when using float numbers without dots in chain calls

- crates/hir-expand/src/builtin_derive_macro.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/span_map.rs
Turns out my idea from https://github.com/rust-lang/rust-analyzer/pull/15251 causes all builtin derive expansions to obviously rely on the main parse, meaning the entire `macro_arg` layer becomes kind of pointless. So this reverts that PR again.
> fix: Remove accidental dependency between `parse_macro_expansion` and `parse`

- crates/hir-def/src/data/adt.rs
- crates/hir-def/src/expander.rs
- crates/hir-def/src/find_path.rs
- crates/hir-def/src/hir/type_ref.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/lower.rs
- crates/hir-def/src/visibility.rs
- crates/hir-expand/src/attrs.rs
- crates/hir-expand/src/eager.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-ty/src/display.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/span/src/ast_id.rs
This can cause extra invalidations as like direct `AstIdMap` dependencies
> fix: Don't force draw a dependency edge to the real_span_map query

- crates/hir-def/src/body/lower.rs
- crates/hir-expand/src/name.rs
The hack remains until we get hygiene, but with this the generated names are stable across bodies
> fix: Don't invalid body query results when generating desugared names

- Cargo.lock
- Cargo.toml
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/hir-ty/src/layout.rs
There was an important API change in 0.41.0, and (hopefully) a fix for https://github.com/rust-lang/rust-analyzer/issues/16774 in 0.42.0.
> Update `rustc_pattern_analysis` to 0.42.0

- crates/hir-ty/src/diagnostics/expr.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
CC https://github.com/rust-lang/rust-analyzer/issues/16746#issuecomment-1981071008
> minor: Skip match diagnostics for partially unknown types

- crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
- crates/ide-db/src/syntax_helpers/format_string_exprs.rs
> fix: Don't escape `\` and `$` in "Extract format expressions" assist

- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/completions/postfix/format_like.rs
- crates/ide-db/src/syntax_helpers/format_string_exprs.rs
`parse_format_exprs` doesn't escape these two as of #16781, so they have to be escaped as a separate step.
> fix: Preserve $ and \ in postfix format completions

- crates/parser/src/grammar.rs
We removed support `crate` visibility keyword, but forgot to remove it from the recovery token list.
> internal: Remove unused keyword from visibility recovery

- crates/parser/src/grammar/items.rs
Since `macro_rules` is a contextual keyword, it is an `IDENT` token and thus `is_path_start` already identifies it correctly. You can tell the previous check is unnecessary because the relevant tests still pass.
> Remove unncessary check for macro call

- crates/rust-analyzer/src/cli/lsif.rs
Detected by #121752, see https://github.com/rust-lang/rust/pull/121752#issuecomment-1986378328
> remove unused struct Snap in lsif

- crates/flycheck/src/test_runner.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/src/lsp_ext.ts
- editors/code/src/test_explorer.ts
followup #16662 
cc @nemethf @ShuiRuTian
> Some minor changes in the test explorer lsp extension

- crates/ide-diagnostics/src/handlers/unresolved_field.rs
Adds an AssistKind::QuickFix for unresolved field. 
Currently, Snippets are not available for Diagnostics. So the type defaults to the Unit type if the type is not able to be inferred. 
https://github.com/rust-lang/rust-analyzer/assets/11785959/bd4c67bd-f8cb-4254-9a87-641ae80a7a28
Closes https://github.com/rust-lang/rust-analyzer/issues/4563
> Added QuickFix for unresolved field.

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
Send less json over the wire.
After https://github.com/microsoft/vscode/issues/193124 was fixed, this change is not needed anymore.
VSCode 1.86.0 now supports double click for unresolved hint data too.
> Stop eagerly resolving inlay hint text edits for VSCode

- Cargo.lock
- crates/base-db/Cargo.toml
- crates/base-db/src/change.rs
- crates/base-db/src/lib.rs
- crates/hir-def/src/nameres/tests/incremental.rs
- crates/hir-expand/src/change.rs
- crates/hir-ty/src/tests.rs
- crates/hir-ty/src/tests/incremental.rs
- crates/ide-db/src/apply_change.rs
- crates/ide-db/src/lib.rs
- crates/ide/src/lib.rs
- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/test-fixture/src/lib.rs
I haven't tested properly, but this roughly looks like:
```
1246 MB
59mb   4899 FileTextQuery
1008 MB
20mb   4899 CompressedFileTextQuery
555kb   1790 FileTextQuery
```
We might want to test on something more interesting, like `bevy`.
> internal: Compress file text using LZ4

- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/method_resolution.rs
- crates/ide-diagnostics/src/handlers/unresolved_field.rs
Accidental change in https://github.com/rust-lang/rust-analyzer/pull/16749 presumably caused some type mismatches in webrender
> fix: Fix method resolution snapshotting receiver_ty too early

- editors/code/language-configuration.json
> fix: Don't auto-close block comments in strings

- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
PR #16366 moved layout information to a separate line, so the leading whitespace is no longer necessary.
> minor: Fix unwanted leading whitespace in hover text

- crates/hir-expand/src/span_map.rs
- crates/ide-db/src/defs.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/syntax/src/ast/node_ext.rs
This reduces the amount of macro call invalidations a bit
> internal: Use assoc items as anchors for spans

- crates/hir-def/src/data.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/item_tree/tests.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/macro_expansion_tests/mbe/matching.rs
- crates/hir-def/src/macro_expansion_tests/mbe/tt_conversion.rs
- crates/hir-def/src/nameres/attr_resolution.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/attrs.rs
- crates/hir-expand/src/builtin_attr_macro.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/declarative.rs
- crates/hir-expand/src/eager.rs
- crates/hir-expand/src/fixup.rs
- crates/hir-expand/src/hygiene.rs
- crates/hir-expand/src/lib.rs
- crates/hir/src/semantics.rs
- crates/mbe/src/benchmark.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/syntax_bridge/tests.rs
- crates/span/src/lib.rs
This makes these a lot more stable again
> internal: Replace `Span` with `SyntaxContextId` in `MacroCallLoc`

- crates/flycheck/src/test_runner.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/src/lsp_ext.ts
- editors/code/src/test_explorer.ts
> Show compilation progress in test explorer

- crates/hir/src/display.rs
- crates/ide/src/hover/tests.rs
We were not accounting for proper newline indentation in some places making the hover look weird (or just straight up wrong for type aliases)
> fix: Fix wrong where clause rendering on hover

- crates/ide-assists/src/handlers/extract_module.rs
fix #16826
This PR includes the following changes:
1. Simplify the implementation partially, removing many unnecessary loops and `clone()`.
2. When it is found that the top level of the selection contains a `use` statement, a copy of the `use` will be reinserted before extraction. (#16826)
3. Fixed an issue during `extract_module`, where if the top level of the selected part contains `A` and `use A::B`, it caused a duplication of `use A`.
> fix: incorrect handling of `use` and panic issue in `extract_module`.

- crates/ide-diagnostics/src/handlers/mutability_errors.rs
- crates/ide-diagnostics/src/handlers/remove_trailing_return.rs
- crates/ide-diagnostics/src/handlers/remove_unnecessary_else.rs
- crates/ide-diagnostics/src/handlers/unused_variables.rs
- crates/ide-diagnostics/src/lib.rs
These tend to be annoying noise as we can't handle `allow`s for them properly for the time being.
> fix: Ignore some warnings if they originate from within macro expansions

- crates/ide/src/typing.rs
fix #16848.
When inserting a `{`, if it is identified that the front part of `expr` is `attr`, we consider it as inserting `{}` around the entire `expr` (excluding the attr part).
> fix: handle attributes when typing curly bracket

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
Not sure if this is the correct fix, but the tests are green :')
Fixes #16823
> Fix panic with impl trait associated types in where clause

- editors/code/src/run.ts
- editors/code/src/tasks.ts
Currently, the extension assumes that all runnables invoke cargo. Arguments are sometimes full CLI arguments, and sometimes arguments passed to a cargo subcommand.
Refactor the extension so that tasks are just a `program` and a list of strings `args`, and rename `CargoTask` to `RustTask` to make it generic.
(This was factored out of #16135 and tidied.)
> Refactor extension to support arbitrary shell command runnables

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/mir/monomorphization.rs
- crates/hir-ty/src/tests/traits.rs
Resolves #16584
Note: This implementation only works for ATPIT, not for TAIT.
The main hinderence that blocks the later is the defining sites of TAIT can be inner blocks like in;
```rust
type X = impl Default;
mod foo {
fn bar() -> super::X {
()
}
}
```
So, to figure out we are defining it or not, we should recursively probe for nested modules and bodies.
For ATPIT, we can just look into current body because `error[E0401]: can't use 'Self' from outer item` prevent such nested structures;
```rust
trait Foo {
type Item;
fn foo() -> Self::Item;
}
struct Bar;
impl Foo for Bar {
type Item = impl Default;
fn foo() -> Self::Item {
fn bar() -> Self::Item {
^^^^^^^^^^
|
use of `Self` from outer item
refer to the type directly here instead
5
}
bar()
}
}
```
But this implementation does not checks …
> feat: Implement ATPIT

- crates/project-model/src/workspace.rs
Implements a workaround for https://github.com/rust-lang/rust-analyzer/issues/14167, notably it does not implement the ideas surfaced in the issue, but takes a simpler to implement approach (and one that is more consistent).
Effectively, all this does is discard dev-dependency edges that go from a workspace library target to another workspace library target. This means, using a dev-dependency to another workspace member inside unit tests will always fail to resolve for r-a now, (instead of being order dependent and causing problems elsewhere) while things will work out fine in integration tests, benches, examples etc. This effectively acknowledges package cycles to be okay, but crate graph cycles to be invalid:
Quoting https://github.com/rust-lang/rust-analyzer/issues/14167#issuecomment-18 …
> fix: Skip problematic cyclic dev-dependencies

- crates/flycheck/src/test_runner.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/main_loop.rs
- editors/code/src/test_explorer.ts
This PR contains:
* Using `--workspace` in `cargo test` command, to running all tests even when there is a crate in the root of a workspace
* Using `--no-fail-fast` to run all requested tests
* Excluding bench in the test explorer
* Fixing a bug in the `hack_recover_crate_name`
fix #16874
> Use `--workspace` and `--no-fail-fast` in test explorer

- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
Also fixes https://github.com/rust-lang/rust-analyzer/issues/16828
> minor: Do progress reporting for crate-graph construction

- crates/project-model/src/workspace.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/16871
With this we should prefer non-dev deps if they do form a cycle, https://github.com/rust-lang/rust-analyzer/issues/14167
> internal: Delay drawing of workspace dev-dependency edges

- crates/hir/src/lib.rs
- crates/ide/src/goto_implementation.rs
> fix: Goto implementation to impls inside blocks

- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
Exhaustiveness checking is NP-hard hence can take extremely long to check some specific matches. This PR makes ehxaustiveness bail after a set number of steps. I chose a bound that takes ~100ms on my machine, which should be more than enough for normal matches.
I'd like someone with less recent hardware to run the test to see if that limit is low enough for them. Also curious if the r-a team thinks this is a good ballpark or if we should go lower/higher. I don't have much data on how complex real-life matches get, but we can definitely go lower than `500 000` steps.
The second commit is a drive-by soundness fix which doesn't matter much today but will matter once `min_exhaustive_patterns` is stabilized.
Fixes https://github.com/rust-lang/rust-analyzer/issues/9528 cc @matklad
> Add fuel to match checking 

- .github/workflows/ci.yaml
Fixes a Node 16 deprecation warning and also pulls in https://github.com/Swatinem/rust-cache/pull/147, which sounds interesting.
> internal: Bump rust-cache action

- crates/project-model/src/workspace.rs
If loading the root fails, we'll hang up in this loop as we never inserted the entry that asserts we already visited a package. This fixes that
Fixes https://github.com/rust-lang/rust-analyzer/issues/16902
> fix: Fix projects depending on `rustc_private` hanging

- crates/hir-def/src/nameres/attr_resolution.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/cfg_process.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/lib.rs
- crates/hir/src/lib.rs
The goal of this PR is to stop creating a token tree for each derive proc macro. 
This is done by giving the derive proc macros an id to its parent derive element. 
From running the analysis stat on the rust analyzer project I did see a small memory decrease.
```
Inference:           42.80s, 362ginstr, 591mb
MIR lowering:        8.67s, 67ginstr, 291mb
Mir failed bodies: 18 (0%)
Data layouts:        85.81ms, 609minstr, 8mb
Failed data layouts: 135 (6%)
Const evaluation:    440.57ms, 5235minstr, 13mb
Failed const evals: 1 (0%)
Total:               64.16s, 552ginstr, 1731mb
```
After Change
```
Inference:           40.32s, 340ginstr, 593mb
MIR lowering:        7.95s, 62ginstr, 292mb
Mir failed bodies: 18 (0%)
Data layouts:        87.97ms, 591minstr, 8mb
Failed data layouts: 135 (6%)
Const …
```
> Have Derive Attribute share a token tree with it's proc macros.

- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/reload.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/lib.rs
- crates/vfs/src/loader.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/15554, additionally it seems that client side file watching was broken on windows this entire time, this PR switches `DidChangeWatchedFilesRegistrationOptions` to use relative glob patterns which do work on windows in VSCode.
> fix: Some file watching related vfs fixes

- crates/paths/src/lib.rs
- crates/project-model/src/cargo_workspace.rs
- crates/vfs-notify/src/lib.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/16914
> fix: Don't assert paths being utf8 when filtering them in the watcher

- crates/hir-expand/src/mod_path.rs
> fix: handle self::super when lowering UseTree

- crates/proc-macro-api/src/lib.rs
Should fix #16926. Please check the issue for more information.
> fix: Rename `func_like` to `FuncLike`

- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/mir/eval.rs
In the evaluation of const values of recursive types certain declarations could cause an endless call-loop within the interpreter (hir-ty’s create_memory_map), which would lead to a stack overflow.
This commit adds a check that prevents values that contain an address in their value (such as TyKind::Ref) from being allocated at the address they contain.
The commit also adds a test for this edge case.
> fix: Prevent stack overflow in recursive const types

- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/shim.rs
- crates/ide/src/hover/tests.rs
Instead of using `core::fmt::format` to format panic messages, which may in turn panic too and cause recursive panics and other messy things, redirect `panic_fmt` to `const_panic_fmt` like CTFE, which in turn goes to `panic_display` and does the things normally. See the tests for the full call stack.
The tests don't work yet, I probably missed something in minicore.
fixes #16907 in my local testing, I also need to add a test for it
> Handle panicking like rustc CTFE does

- crates/hir-ty/src/lib.rs
The API hasn't fully settled yet, and there's an extra wrinkle with `IdxContainer` which blocked the [subtree update](https://github.com/rust-lang/rust/pull/122981). Let's just keep using the crates.io version for a bit longer.
r? @lnicola
> Revert to the crates.io version of rustc_pattern_analysis

- crates/hir/src/display.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
follow up https://github.com/rust-lang/rust-analyzer/pull/15847, https://github.com/rust-lang/rust-analyzer/pull/15938
> feat: limit struct hover display nums

- crates/hir-ty/src/utils.rs
Hope I got this right @dfireBird.
> minor: Update comment on provenance_split

- editors/code/src/debug.ts
See https://github.com/rust-lang/rust-analyzer/issues/16901#issuecomment-2024486941
This PR resolves the issue of being unable to debug using the C++ extension on macOS. By using special configurations for the `MIMode` on macOS, it enables the C++ extension to connect to lldb when debugging (without affecting other platforms).
> fix: use lldb when debugging with C++ extension on MacOS

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
> fix: check for client support of relative glob patterns before using them

- crates/hir/src/lib.rs
- crates/ide/src/hover/tests.rs
I feel like test doesn't do much. Please suggest if I should improve it?
Fixes #16963
> fix: ADT hover considering only type or const len not lifetimes

- crates/ide/src/lib.rs
- crates/ide/src/test_explorer.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/src/lsp_ext.ts
- editors/code/src/test_explorer.ts
> Resolve tests per file instead of per crate in test explorer

- .github/ISSUE_TEMPLATE/bug_report.md
When attempting to reproduce issues, I encounter difficulties due to differences in versions of LSP clients and editors (such as #16985, #16867, and more)
This sometimes consumes a lot of efforts from contributors to communicate the details about LSP client information. Therefore, I believe adding editor/extension information to the issue template would be helpful for problem reproduction.
> update: add editor/extension information to bug report template

- editors/code/src/run.ts
- editors/code/src/tasks.ts
#16839 refactored the representation of tasks inside the VS Code extension. However, this data type is exposed to users, who can define their own tasks in the same format in `tasks.json` or `.code-workspace`.
Revert the data type to have a `command` field rather than a `program` field, and document the different fields. This code is also a little complex, so split out a `cargoToExecution` to handle the Task to Execution conversion logic.
After this change, any tasks.json with a `command` field works again. For example, the following tasks.json works as expected:
```
{
"version": "2.0.0",
"tasks": [
{
"type": "cargo",
"command": "build",
"problemMatcher": [
"$rustc"
],
"group": "build",
"label": "my example cargo build task"
}
]
}
```
Fixes #16943 #16949
> Fix tasks in tasks.json

- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Closes #16859
Should this be a setting for build scripts only ? All the other `--all-targets` I found where already covered by `checkOnSave.allTargets`
> feat: Add `rust-analyzer.cargo.allTargets` to configure passing `--all-targets` to cargo invocations

- crates/project-model/src/project_json.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/handlers/notification.rs
Previously, we assumed that the crate numbers in a `rust-project.json` always matched the `CrateId` values in the crate graph. This isn't true when there are multiple workspaces, because the crate graphs are merged and the `CrateId` values in the merged graph are different.
This broke flycheck (see first commit), because we were unable to find the workspace when a file changed, so we every single flycheck, producing duplicate compilation errors.
Instead, use the crate root module path to look up the relevant flycheck. This makes `ProjectWorkspace::Json` consistenet with `ProjectWorkspace::Cargo`.
Also, define a separate JSON crate number type, to prevent bugs like this happening again.
> Fix crate IDs when multiple workspaces are loaded

- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
The main blocker to using the in-tree version of the `pattern_analysis` crate is that rustc requires enum indices to be contiguous because it uses `IndexVec`/`BitSet` for performance. Currently we swap these out for `FxHashMap`/`FxHashSet` when the `rustc` feature is off, but we can't do that if we use the in-tree crate.
This PR solves the problem by using contiguous indices on the r-a side too.
> pattern analysis: Use contiguous indices for enum variants

- crates/hir-ty/src/builder.rs
- crates/hir/src/lib.rs
- crates/ide/src/hover/tests.rs
- crates/proc-macro-api/src/lib.rs
For one, this brings back layout information for lifetime generic ADTs (which "regressed" when we started adding lifetimes to chalks-ir), but it also allows layout calculation to work for definitions that don't actually use the generics (where its only used in a `PhantomData` for example)
> internal: Consider ADT generic parameter defaults for unsubstituted layout calculations

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/cfg_process.rs
- crates/hir-expand/src/db.rs
- crates/ide-completion/src/completions/postfix.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16947
> fix: Fix some cfg censoring bugs

- crates/rust-analyzer/src/diagnostics/to_proto.rs
On this file,
```rust
fn main() {
let 된장 = 1;
}
```
when using `"positionEncodings":["utf-16"]` I get an "unused variable" diagnostic on the variable
name (codepoint offset range `8..10`). So far so good.
When using `positionEncodings":["utf-8"]`, I expect to get the equivalent range in bytes (LSP:
"Character offsets count UTF-8 code units (e.g bytes)."), which is `8..14`, because both
characters are 3 bytes in UTF-8.  However I actually get `10..14`.
Looks like this is because we accidentally treat a 1-based index as an offset value: when
converting from our internal char-indices to LSP byte offsets, we look at one character to many.
This causes wrong results if the extra character is a multi-byte one, such as when computing
the start coordinate of 된장.
Fix that by actually passing an …
> Fix off-by-one error converting to LSP UTF8 offsets with multi-byte char

- crates/hir-def/src/attr.rs
- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/toggle_ignore.rs
- crates/ide-assists/src/utils.rs
- crates/ide/src/annotations/fn_references.rs
- crates/ide/src/runnables.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17011
> fix: Consider `exported_name="main"` functions in test modules as tests

- .github/workflows/release.yaml
> internal: Use jemalloc in releases

- crates/flycheck/src/lib.rs
- crates/flycheck/src/test_runner.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
> Apply cargo flags in test explorer

- .github/workflows/release.yaml
This reverts commit 692c41e5937d821a30045990c11573ddb66bbccd: https://github.com/rust-lang/rust-analyzer/actions/runs/8592641551/job/23542950551.
> Revert "Use jemalloc for releases"

- crates/flycheck/src/lib.rs
Resolves #16969
The non-cargo messages are appended to the error strings here;
https://github.com/rust-lang/rust-analyzer/blob/7a8374c162c64c17e865b98aad282d16b16e96d6/crates/flycheck/src/lib.rs#L460-L482
that one is formatted into `Err` here;
https://github.com/rust-lang/rust-analyzer/blob/7a8374c162c64c17e865b98aad282d16b16e96d6/crates/flycheck/src/command.rs#L144-L155
and finally, this PR appends it at the end of existing Flycheck error message
> Log flycheck errors

- crates/ide-assists/src/handlers/generate_function.rs
I am working on #17050.
In the process, I noticed a place in the code that could be refactored.
Currently, the `function builder` creates the `ast` through the `function template` , but those two processes can be combined into one function.
I thought I should work on this first and created a PR.
> internal: make function builder create ast directly

- .github/workflows/ci.yaml
Previously PRs would only do a build on Windows, which confusingly meant that PRs got a green tick for Windows despite not testing them.
See discussion in #17019.
> Run Windows tests on PRs too

- editors/code/language-configuration.json
It might fix #16051, see https://github.com/rust-lang/rust-analyzer/issues/16051#issuecomment-2042606030
> fix: support auto-closing for triple backticks

- crates/ide-completion/src/completions/postfix.rs
This reverts commit c5686c89413b3c6eead7b39637381ee353f8c05c.
Fix #17036. See https://github.com/rust-lang/rust-analyzer/issues/17036#issuecomment-2050185641
> Revert "fix: set the right postfix snippets competion source range"

- crates/vfs/src/file_set.rs
- crates/vfs/src/file_set/tests.rs
Previously, the VFS would assign paths to the source root that had the longest string prefix match. This would break when we had source roots in subdirectories:
```
/foo
/foo/bar
```
Given a file `/foo/bar_baz.rs`, we would attribute it to the `/foo/bar` source root, which is wrong.
As a result, we would attribute paths to the wrong crate when a crate was in a subdirectory of another one. This is more common in larger monorepos, but could occur in any Rust project.
Fix this in the VFS, and add a test.
> fix: VFS should not confuse paths with source roots that have the same prefix

- crates/ide/src/inlay_hints.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- docs/dev/lsp-extensions.md
So, things broke because we now store a hash (u64) in the resolution payload, but javascript and hence JSON only support integers of up to 53 bits (anything beyond gets truncated in various ways) which caused almost all hashes to always differ when resolving them. This masks the hash to 53 bits to work around that.
Fixes https://github.com/rust-lang/rust-analyzer/issues/16962
> fix: Fix inlay hint resolution being broken

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/completions/postfix/format_like.rs
Better inline preview for postfix completion, a proper implementation of c5686c89413b3c6eead7b39637381ee353f8c05c.
Here editors may filter completion item with the text within `delete_range`, so we need to include the `receiver text` in the `lookup` (aka `FilterText` in LSP spec) for editors to find the completion item. (See https://github.com/rust-lang/rust-analyzer/issues/17036#issuecomment-2056614180, Thanks to [pascalkuthe](https://github.com/pascalkuthe))
> Better inline preview for postfix completion

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/completions/postfix/format_like.rs
See discussion on https://github.com/rust-lang/rust-analyzer/issues/17077, but I strongly suspect that the changes to the `TextEdit` ranges caused VS Code's autocomplete to prefer the snippets over method completions. I explain why I think that [here](https://github.com/rust-lang/rust-analyzer/issues/17077#issuecomment-2057908447).
> Revert #17073: Better inline preview for postfix completion

- crates/ide-assists/src/handlers/auto_import.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/parser/src/token_set.rs
- xtask/src/codegen/grammar/ast_src.rs
The current `TokenSet` type represents "A bit-set of `SyntaxKind`s" as a newtype `u128`.
Internally, the flag for each `SyntaxKind` variant in the bit-set is set as the n-th LSB (least significant bit) via a bit-wise left shift operation, where n is the discriminant. 
Edit: This is problematic because there's currently ~121 token `SyntaxKind`s, so adding new token kinds for missing reserved keywords increases the number of token `SyntaxKind`s above 128, thus making this ["mask"](https://github.com/rust-lang/rust-analyzer/blob/7a8374c162c64c17e865b98aad282d16b16e96d6/crates/parser/src/token_set.rs#L31-L33) operation overflow.
~~This is problematic because there's currently 266 SyntaxKinds, so this ["mask"](https://github.com/rust-lang/rust-analyzer/blob/7a8374c162c64c17e865b98aad282d16b16e9 …
> internal: improve `TokenSet` implementation and add reserved keywords

- Cargo.lock
- crates/base-db/src/input.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/lib.rs
- crates/project-model/src/cfg_flag.rs
- crates/project-model/src/project_json.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
This PR aims to cover the infrastructural requirements for the `rust-analyzer.toml` ( #13529 ) issue. This means, that
1. We no longer have a single config base. The once single `ConfigData` has been divided into 4 : A tree of `.ratoml` files, a set of configs coming from the client ( this is what was called before the `CrateData` except that now values do not default to anything when they are not defined) , a set of configs that will reflect what the contents of a `ratoml` file defined in user's config directory ( e.g `~/.config/rust-analyzer/.rust-analyzer.toml` and finally a tree root that is populated by default values only.
2. Configs have also been divided into 3 different blocks : `global` , `local` , `client`. The current status of a config may change until #13529 got merged.
Once …
> internal : redesign rust-analyzer::config 

- Cargo.lock
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/remove_unused_imports.rs
- crates/ide-db/Cargo.toml
- crates/ide-db/src/search.rs
- crates/ide/src/highlight_related.rs
- crates/ide/src/references.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
It is bitset semantically --- many categorical things can be true about a reference at the same time.
In parciular, a reference can be a "test" and a "write" at the same time.
> ide: improve ReferenceCategoryType

- crates/vfs-notify/src/lib.rs
As of #6246, rust-analyzer follows symlinks. This can introduce an infinite loop if symlinks point to parent directories.
Considering that #6246 was added in 2020 without many bug reports, this is clearly a rare occurrence. However, I am observing rust-analyzer hang on projects that have symlinks of the form:
```
test/a_symlink -> ../../
```
Ignore symlinks that only point to the parent directories, as this is more robust but still allows typical symlink usage patterns.
> fix: VFS should not walk circular symlinks

- crates/hir-expand/src/db.rs
- crates/hir-expand/src/declarative.rs
- crates/hir/src/semantics.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander.rs
- crates/mbe/src/lib.rs
- crates/span/src/map.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/4028, its a different take on the idea. I don't like go to being changed here simply because we can't point the focus range on the name anymore as we usually do, and some editors might use this feature (and the focus range) for certain other things. We could instead add a new hover action for this to move to the arm directly (or maybe make `go to implementation` jump to the arm?)
> Render matched macro arm on hover of macro calls

- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- docs/user/generated_config.adoc
- editors/code/package.json
* Added config `runnables.extraTestBinaryArgs` to control the args.
* The default is `--show-output` rather than `--nocapture` to prevent unreadable output when 2 or more tests fail or print output at once.
* Renamed variables in `CargoTargetSpec::runnable_args()` for clarity.
Fixes #12737.
Suggested changelog info:
> New Features
>
> * add `rust-analyzer.runnables.extraTestBinaryArgs` to configure test harness options when running tests; replaces a previously hard-coded `--nocapture` option.
I'm not sure I made the right choices in vocabulary, between “binary”, “executable”, and “runnable”, and “launch” vs. “execute”, so let me know if I missed something to be consistent with in the naming and documentation.
> Make test harness arguments configurable and not `--nocapture`.

- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
cc https://github.com/rust-lang/rust-analyzer/issues/16538
> internal: Remove rustc core test cfg hacks

- crates/ide-assists/src/handlers/convert_from_to_tryfrom.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Adds a new code assist to convert a `From` impl into a `TryFrom` impl.
This is useful in situations where it turns out after or halfway through writing a `From` implementation that the conversion is actually fallible.
https://github.com/rust-lang/rust-analyzer/assets/26360861/872ec7c4-c9ff-451c-9453-4baaaad47326
> feat: Add convert From to TryFrom assist

- crates/hir-def/src/attr.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/attrs.rs
- crates/ide-db/src/documentation.rs
- crates/syntax/src/lib.rs
fix #16980.
For `ast::LiteralKind::String`, store the original string value.
> fix: handle escaped chars in doc comments

- crates/load-cargo/src/lib.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
Based on https://github.com/rust-lang/rust-analyzer/pull/15456,
As the original PR stated, detached files are still horrendous to work with.
> Cargo script mvp

- crates/hir-def/Cargo.toml
- crates/hir-expand/Cargo.toml
- crates/hir-expand/src/lib.rs
- crates/hir-ty/Cargo.toml
- crates/hir/Cargo.toml
- crates/load-cargo/Cargo.toml
- crates/rust-analyzer/Cargo.toml
CC https://github.com/rust-lang/rust/pull/124199#issuecomment-2067701168
> minor: Add in-rust-tree feature to hir-expand

- crates/base-db/src/lib.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide-db/src/prime_caches.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/manifest_path.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/progress_report.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/crate_graph.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- docs/user/generated_config.adoc
- editors/code/package.json
With this, script files become more usable as the user can at least add them manually to the linked projects, allowing them to be used "on the (manual) fly" without having to open a separate vscode window that only has files open and no folder.
Also makes build scripts work for them (though no proc-macros, for some reason the dylib field is not populated in the output)
> feat: Allow rust files to be used linkedProjects

- crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
I just found out about rust-analyzer json converter, but I think it would be more convenient, if names were more useful, like using the names of the keys.
Let's look at some realistic arbitrary json:
```json
{
"user": {
"address": {
"street": "Main St",
"house": 3
},
"email": "example@example.com"
}
}
```
I think, new generated code is much easier to read and to edit, than the old:
```rust
// Old
struct Struct1{ house: i64, street: String }
struct Struct2{ address: Struct1, email: String }
struct Struct3{ user: Struct2 }
// New
struct Address1{ house: i64, street: String }
struct User1{ address: Address1, email: String }
struct Root1{ user: User1 }
```
Ideally, if we drop the numbers, I can see it being usable just as is (may be rename root)
```rust
struct Address{ house: i64, street: …
```
> Try to generate more meaningful names in json converter

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir/src/diagnostics.rs
- crates/ide-diagnostics/src/handlers/no_such_field.rs
fix #17107 
Pass variant information down to diagnostic, so that we can get different error code based on variant type.
After fix:
- structure
- enum's structure variant
> different error code of "no such field" error based on variant type

- crates/hir/src/display.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fix #17009
1. Currently, r-a supports limiting the number of struct fields displayed when hovering. This PR extends it to support enum variants and union fields. Since the display of these three (ADTs) is similar, this PR extends 'hover_show_structFields' to 'hover_show_adtFieldsOrVariants'.
2. This PR also resolved the problem that the layout of ADT was not restricted by display limitations when hovering on the Self type.
3. Additionally, this PR changes the default value of display limitations to `10` (instead of the original `null`), which helps users discover this feature.
> Support hovering limits for adts

- crates/rust-analyzer/src/global_state.rs
(should) fix https://github.com/rust-lang/rust-analyzer/issues/17071 and fix https://github.com/rust-lang/rust-analyzer/issues/17079
> fix: Fix source roots not always being created when necessary

- crates/cfg/src/tests.rs
- crates/hir-def/src/attr/tests.rs
- crates/hir-def/src/macro_expansion_tests/proc_macros.rs
- crates/hir-expand/src/attrs.rs
- crates/hir-expand/src/builtin_derive_macro.rs
- crates/hir-expand/src/db.rs
- crates/hir-expand/src/declarative.rs
- crates/hir-expand/src/eager.rs
- crates/hir-expand/src/fixup.rs
- crates/mbe/src/benchmark.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/syntax_bridge/tests.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16259
> fix: Fix doc comment desugaring for proc-macros

- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/from_proto.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
Fixes https://github.com/rust-lang/rust-analyzer/issues/15907
Fixes https://github.com/rust-lang/rust-analyzer/issues/14839
Fixes https://github.com/rust-lang/rust-analyzer/issues/16536
> fix: Don't retry position relient requests and version resolve data

- docs/user/manual.adoc
The manual has been linking to the repo
https://github.com/rust-analyzer/rust-project.json-example/tree/master
This repo does not contain a rust-project.json, does not appear to have _ever_ contained a rust-project.json, and my bug report about this has gone untouched: https://github.com/rust-analyzer/rust-project.json-example/issues/4
Since I can't figure out an example, this commit removes the link pending better documentation.
> manual: remove suggestion of rust-project.json example

- crates/vfs-notify/src/lib.rs
> fix: discard path when the path is invalid

- crates/hir-def/src/generics.rs
- crates/hir-def/src/lower.rs
- crates/hir-def/src/path/lower.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
> Implement creating generics for impl traits in associated types

- crates/base-db/src/change.rs
- crates/base-db/src/lib.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/literal.rs
- crates/ide-completion/src/render/macro_.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/imports/insert_use.rs
- crates/ide-db/src/prime_caches.rs
- crates/ide/src/inlay_hints.rs
- crates/load-cargo/src/lib.rs
- crates/proc-macro-api/src/lib.rs
- crates/rust-analyzer/src/cli/parse.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
When viewing traces, it's slightly confusing when the span name doesn't match the function name. Ensure the names are consistent.
(It might be worth moving most of these to use `#[tracing::instrument]` so the name can never go stale. @davidbarsky suggested that is marginally slower, so I've just done the simple change here.)
> fix: Tracing span names should match function names

- Cargo.lock
- crates/profile/Cargo.toml
- crates/profile/src/memory_usage.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/main_loop.rs
- crates/stdx/Cargo.toml
- crates/stdx/src/process.rs
I noticed that the `rust-analyzer` project already depends on `windows-sys`. This update merely replaces the remaining direct dependencies on the older `winapi` crate with `windows-sys` dependencies.
Originally posted here: https://github.com/rust-lang/rust/pull/124578
> Update `rust-analyzer` to use `windows-sys` crate

- crates/base-db/src/input.rs
- crates/hir-def/src/nameres/collector.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
- crates/project-model/test_data/output/cargo_hello_world_project_model.txt
- crates/project-model/test_data/output/cargo_hello_world_project_model_with_selective_overrides.txt
- crates/project-model/test_data/output/cargo_hello_world_project_model_with_wildcard_overrides.txt
- crates/project-model/test_data/output/rust_project_hello_world_project_model.txt
- crates/test-fixture/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17169, my previous change missed the fact that the sysroot itself depends on its own crates explicitly
> fix: Correctly handle `no_core`/`no_std` for preludes

- crates/hir-def/src/generics.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17173
> fix: Fix implicit ty args being lowered where they shouldn't

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
Fixes the other thing in https://github.com/rust-lang/rust-analyzer/issues/17173, this just rolls back a change from https://github.com/rust-lang/rust-analyzer/pull/17175 and adds a comment as to what it does
> Fix impl trait params not being counted properly

- crates/rust-analyzer/src/config.rs
I have disabled Rust Analyzer lenses in my VSCode settings, but noticed that the `Run` lens still showed. This surprised me, as the docs for `lens.run.enable` [state that it only applies when `lens.enable` is set](https://github.com/rust-lang/rust-analyzer/blob/25f59be62f6b915b44a4c2ec2defca56a5f766c1/crates/rust-analyzer/src/config.rs#L353-L355). I then found that where we set `LensConfig::run`, we don't check `lens_enable` like for the other settings. [We did this previously](https://github.com/rust-lang/rust-analyzer/blob/eab385e1f64f8e3b861effe91432785f8030191b/crates/rust-analyzer/src/config.rs#L1649), so this seems like a regression from refactoring. This PR tries to fix that.
> Fix Run lens showing when lenses are disabled

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/traits.rs
Surely fixes #17182
I have tried running the analysis-stats in some of the repos mentioned in #17080. No panic in almost all of them.
> Fix: Lifetime's Bound Var Debrujin Index in Dyn Traits

- crates/ide-completion/src/context.rs
- crates/ide-completion/src/render.rs
fix #17179.
Previously r-a use `TextRange::empty(self.position.offset)` as `source_range` for `INT_NUMBER`, so the `text_edit` would always be an insertion, which results in #17179.
This PR changed it by using `text_range` of `original_token` (same as `IDENT`).
> Fix source_range for INT_NUMBER in completion

- lib/lsp-server/src/msg.rs
Previously we did not use invalid_data for serde errors, making it harder to understand errors when the client sends malformed data to the server.
> fix: Report all LSP protocol errors with invalid_data

- crates/rust-analyzer/src/bin/main.rs
If rust-analyzer receives a malformed LSP request, the IO thread terminates with a meaningful error, but then closes the channel.
Once the channel has closed, the main_loop also terminates, but it only has RecvError and can't show a meaningful error. As a result, rust-analyzer would incorrectly claim that the client forgot to shutdown.
```
$ buggy_lsp_client | rust-analyzer
Error: client exited without proper shutdown sequence
```
Instead, include both error messages when the server shuts down.
> fix: Report both IO errors and main_loop errors

- crates/ide-assists/src/handlers/apply_demorgan.rs
fix #17185
Additionally, this PR simplifies some code in `apply_demorgan`.
> fix: keep parentheses when the precedence of inner expr is lower than the outer one

- crates/hir/src/term_search.rs
- crates/hir/src/term_search/expr.rs
- crates/hir/src/term_search/tactics.rs
- crates/ide-assists/src/assist_config.rs
- crates/ide-assists/src/handlers/term_search.rs
- crates/ide-assists/src/tests.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/config.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests.rs
- crates/ide-diagnostics/src/handlers/typed_hole.rs
- crates/ide-diagnostics/src/lib.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- docs/user/generated_config.adoc
- editors/code/package.json
The issue came from multi Cartesian product for exprs with many (25+) arguments, each having multiple options.
The solution is two fold:
**Before the logic was:**
1. Find expressions for each argument/param - there may be many
2. Take the Cartesian product (which blows up in some cases)
4. If there are more than 2 options throw them away by squashing them to `Many` 
**Now the logic is:**
1. Find expressions for each argument/param and squash them to `Many` if there are more than 2 as otherwise we are guaranteed to also have more than 2 after taking the product which means squashing them anyway.
2. Take the Cartesian product on iterator
3. Start consuming it one by one
4. If there are more than 2 options throw them away by squashing them to `Many`  (same as before)
This is also why I had …
> Fix OOM caused by term search

- crates/ide/src/runnables.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17223
> internal: Sort computed runnables

- crates/ide-assists/src/handlers/move_module_to_file.rs
close https://github.com/rust-lang/rust-analyzer/issues/17181
> fix: extract mod to file should respect path attribute

- crates/project-model/src/build_scripts.rs
- crates/project-model/src/workspace.rs
Might be the cause for https://github.com/rust-lang/rust-analyzer/issues/17231
> fix: Don't emit --keep-going for custom build script commands

- .github/workflows/ci.yaml
- .github/workflows/metrics.yaml
Current metrics caching uses a base cache action, whereas I think the one we use for general ci works here as well. Saw this while noticing that our metrics CI is broken as it for some reason uses an outdated rust stable? (unsure why that is)
> internal: Use Swatinem/rust-cache for metrics CI

- crates/ide-assists/src/handlers/convert_named_struct_to_tuple_struct.rs
- crates/ide-db/src/search.rs
- crates/profile/src/lib.rs
- crates/rust-analyzer/src/task_pool.rs
- crates/salsa/src/lib.rs
https://github.com/rust-lang/rust/pull/124948
> In RA we gladly take typo fixes, but for now we definitely want them in the upstream repository.
> Chore: Fix some typos

- docs/user/manual.adoc
This change is what I had to do to make inlay hints work on Neovim 0.10.  The current example produces errors about wrong argument type to `.enable()`.
> internal: Correct Neovim 0.10 inlay hints config example

- crates/hir-def/src/attr/builtin.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/attr_resolution.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/traits.rs
- crates/hir/src/lib.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-assists/src/handlers/replace_method_eager_lazy.rs
- crates/ide-assists/src/utils/suggest_name.rs
- crates/ide-db/src/active_parameter.rs
- crates/ide-db/src/syntax_helpers/format_string.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/inlay_hints/param_name.rs
- crates/ide/src/signature_help.rs
- crates/ide/src/syntax_highlighting/escape.rs
- crates/syntax/src/ast/token_ext.rs
With this PR we retain more info about callables other than functions, allowing for closure parameter type inlay hints to be linkable as well as better signature help around closures and `Fn*` implementors.
> feat: More callable info

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
Closes #15934 
This adds a flag inside the global state which controls when old diagnostics are cleared. Now, old diagnostics should be cleared only after at least one new diagnostic is available.
> Clear diagnostics only after new ones were received

- crates/hir-def/src/body/tests/block.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
fix https://github.com/rust-lang/rust-analyzer/issues/17057, https://github.com/rust-lang/rust-analyzer/issues/17032.
We should use `ModuleOrigin` to check if the current module is a pseudo-module introduced by blocks (where names might be shadowed), rather than checking `block_def_map`.
> fix: resolve extern prelude for local mods in block modules

- crates/hir/src/lib.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
closes: #16989 
rust-analyzer needs to consider implied bounds from associated types in order to get all methods suggestions people expect. A pretty easy way to do that is to keep the `candidate_trait_id`'s receiver if it matches `TyFingerprint::Unnameable`.  When benchmarking this change, I didn't notice a meaningful difference in autocomplete latency.
(`TyFingerprint::Unnameable` corresponds to `TyKind::AssociatedType`, `TyKind::OpaqueType`, `TyKind::FnDef`, `TyKind::Closure`, `TyKind::Coroutine`, and `TyKind::CoroutineWitness`.)
> fix: ensure implied bounds from associated types are considered in autocomplete

- crates/ide-assists/src/handlers/remove_unused_imports.rs
- crates/syntax/src/ast/node_ext.rs
Fixes #17139 
On master
```rs
mod inner {
pub struct X();
pub struct Y();
}
mod z {
use super::inner::{self, X}$0;
fn f() {
let y = inner::Y();
}
}
```
becomes
```rs
mod inner {
pub struct X();
pub struct Y();
}
mod z {
use super::inner:self;
fn f() {
let y = inner::Y();
}
}
```
with this fix it instead becomes
```
```rs
mod inner {
pub struct X();
pub struct Y();
}
mod z {
use super::inner;
fn f() {
let y = inner::Y();
}
}
```
> handle {self} when removing unused imports

- crates/hir-ty/src/infer/expr.rs
- crates/ide/src/inlay_hints/bind_pat.rs
Fixes #17106
The `infer_async_block` method calls the `infer_block` method internally, which returns the never type without coercion when `tail_expr` is `None` and `ctx.diverges` is `Diverges::Always`.This is the reason for the bug in this issue.
https://github.com/rust-lang/rust-analyzer/blob/cfce2bb46da62950a8b70ddb0b2a12332da1b1e1/crates/hir-ty/src/infer/expr.rs#L1411-L1413
This PR solves the bug by adding a process to coerce after calling `infer_block` method.
This code passes all the tests, including tests I added for this isuue, however, I am not sure if this solution is right. I think that this solution is an ad hoc solution. So, I would appreciate to have your review.
I apologize if I'm off the mark, but `infer_async_block` method should be rewritten to share code with the process …
> Fix: infer type of async block with tail return expr

- editors/code/src/debug.ts
The RA VSCode extension uses an incorrect format for the environment variables in the `launch.json` when debugging with the C/C++ Extension. This extension uses a different format than CodeLLDB or NativeDebug, which means that the environment variables are not actually set for the debuggee.
What it currently looks like:
```json
"env": {
"NAME": "VALUE"
}
```
What the C/C++ extension expects:
```json
"environment": [
{ "name": "NAME", "value": "VALUE" }
]
```
For reference: https://code.visualstudio.com/docs/cpp/launch-json-reference#_environment
> Use correct format for setting environment variables when debugging with cpptools

- crates/ide/src/runnables.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
I stumbled across this when reading this code. This seems like an unnecessary allocation (though likely small?)
> Avoid clone when constructing runnable label.

- crates/hir/src/term_search.rs
- crates/hir/src/term_search/tactics.rs
- crates/ide-assists/src/handlers/term_search.rs
Previously didn't work for structs with generics due to `field.ty()` having placeholders in type.
_Enums were handeled correctly already._
Also renamed `type_constructor -> data_constructor` as this is more correct name for it
> Fix `data_constructor` ignoring generics for struct

- crates/ide-assists/src/handlers/convert_comment_from_or_to_doc.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Hey first PR to rust-analyzer to get my feet wet with the code base. It's an assist to switch a normal comment to a doc comment and back, something I've found myself doing by hand a couple of times.
I shamelessly stole `relevant_line_comments` from `convert_comment_block`, because I didn't see any inter-assist imports happening in the files I peeked at so I thought this would be preferable.
> Implement assist to switch between doc and normal comments

- Cargo.lock
- Cargo.toml
- crates/flycheck/Cargo.toml
- crates/flycheck/src/command.rs
Because command-group no longer receives updates and depends on an older version of nix.
> internal: replace command-group with process-wrap

- crates/flycheck/src/lib.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
This might be causing #17300 or it's a different bug with the same functionality.
I wonder if the decision to clear diagnostics should stay in the main loop or maybe the flycheck itself should track it and tell the mainloop?
I have used a hash map but we could just as well use a vector since the IDs are `usizes` in some given range starting at 0. It would be probably faster but this just felt a bit cleaner and it allows us to change the ID to newtype later and we can just use a hasher that returns the underlying integer.
> fix diagnostics clearing when flychecks run per-workspace

- crates/paths/src/lib.rs
cc https://github.com/rust-lang/rust-analyzer/issues/17335
> Add path info to `AbsPathBuf::assert`'s assert

- crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
- crates/ide-assists/src/utils.rs
- crates/ide-db/src/source_change.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/lib.rs
- crates/syntax/src/parsing.rs
Part of #17332
Fixes `extract_expressions_from_format_string` so that it doesn't generate snippets if the client doesn't support it.
> fix: Only generate snippets for `extract_expressions_from_format_string` if snippets are supported

- crates/hir-def/src/attr/builtin.rs
- crates/hir-ty/src/utils.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
`std::env::set_var` will be unsafe in edition 2024, but not before it. I couldn't quite figure out how to check for the span properly, so for now we just turn the false positives into false negatives, which are less bad.
> Don't mark `#[rustc_deprecated_safe_2024]` functions as unsafe

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/path/lower.rs
- crates/hir-def/src/pretty.rs
- crates/hir-def/src/visibility.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-ty/src/display.rs
- crates/hir/src/attrs.rs
- crates/ide-db/src/helpers.rs
cc https://github.com/rust-lang/rust-analyzer/issues/17339, db80216dac3d972612d8e2d12ade3c28a1826ac2 should fix a case where we don't reduce our search space appropriately. This also adds a fuel system which really shouldn't ever be hit, hence why it warns
> internal: Improve `find_path` performance

- crates/ide-db/src/symbol_index.rs
- crates/ide/src/navigation_target.rs
Fixes #17272 by changing the default behavior of query to skip results that start with `__` (two underscores).
Not sure if this has any far reaching implications - a review would help to understand if this is the right place to do the filtering, and if it's fine to do it by default on the query.
If you type `__` as your search, then we'll show the matching double unders, just in case you actually need the symbol.
> Feat: hide double underscored symbols from symbol search

- crates/hir/src/has_source.rs
> Use `.get(…)` instead of `[…]` in `TypeOrConstParam::source(…)` and `LifetimeParam::source(…)`

- Cargo.lock
Building rust-analyzer currently generates a warning because libc 0.2.154 has been yanked. Update to 0.2.155 in Cargo.lock.
> chore: Update Cargo.lock to avoid yanked version

- crates/ide-diagnostics/src/handlers/unlinked_file.rs
Currently, rust-analyzer highlights the entire region when a `cfg` is inactive (e.g. `#[cfg(windows)]` on a Linux machine). However, unlinked files only highlight the first three characters of the file.
This was introduced in #8444, but users have repeatedly found themselves with no rust-analyzer support for a file and unsure why (see e.g. #13226 and the intentionally prominent pop-up added in PR #14366).
(Anecdotally, we see this issue bite our users regularly, particularly people new to Rust.)
Instead, highlight the entire inactive file, but mark it as all as unused. This allows users to hover and run the quickfix from any line.
Whilst this is marginally more prominent, it's less invasive than a pop-up, and users do want to know why they're getting no rust-analyzer support in certain …
> fix: Highlight unlinked files consistently with inactive files

- crates/rust-analyzer/src/config.rs
- editors/code/package.json
- xtask/src/dist.rs
There are a lot of options that are a part of rust-analyzer, sometimes it can be hard to find an option that you are looking for. To fix this I have put all configurations into categories based on their names. I have also changed the schema in `crates/rust-analyzer/src/config.rs` to reflect this.
Currently for each generated entry the title is redeclared, this does function but I am prepared to change this if it is a problem.
> Changed package.json so vscode extension settings have submenus

- crates/ide/src/hover.rs
- editors/code/src/client.ts
fix #12728.
- Use ` | ` as the separator for actions. (I'm not sure why we use `___` previously)
- Reorder actions to match codelens
> fix: incorrect formatting of hover actions

- crates/ide-assists/src/handlers/auto_import.rs
@joshka pointed out some odd behavior of auto import ordering. It doesn't seem that the current heuristics were applying any sort of precedence to imports from the workspace. I've went ahead and added that.
I hope to get some feedback on the modifier numbers here. I just went with something that felt like it balanced giving more power to workspace crates without completely ignoring relative path distance.
closes https://github.com/rust-lang/rust-analyzer/issues/17303
> Add preference modifier for workspace-local crates when using auto import.

- .cargo/config.toml
- xtask/src/dist.rs
I think the newlines are tripping up CI, so I hope clearing the property to leave an empty object won't make VSCode made here.
> fix: Fix generated markers not being patchable in package.json

- crates/hir/src/has_source.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/utils/suggest_name.rs
- crates/ide-db/src/active_parameter.rs
- crates/ide-db/src/rename.rs
- crates/ide-ssr/src/matching.rs
- crates/ide/src/inlay_hints/param_name.rs
- crates/ide/src/navigation_target.rs
- crates/ide/src/rename.rs
- crates/ide/src/signature_help.rs
Should fix https://github.com/rust-lang/rust-analyzer/issues/17376, specifically 30c04d5aa9523140f0f2daa07bc461534fb09b95
The recent changes here were heavily triggering what I realized in https://github.com/rust-lang/rust-analyzer/issues/17367#issuecomment-2156374726
> fix: Remove extra parse cache from Semantics again

- crates/load-cargo/src/lib.rs
fix #17378.
In `FileSetConfig.map`, different roots might be mapped to the same `root_id` due to deduplication in `ProjectFolders::new`:
```rust
// Example from rustup
/Users/roife/code/rustup/target/debug/build/rustup-863a063426b56c51/out
/Users/roife/code/rustup
```
In `source_root_parent_map`, r-a might encounter paths where their SourceRootId (i.e. `root_id`) is identical, yet one the them is the parent of the another. This situation can cause the `root_id` to be its own parent, potentially leading to an infinite loop.
This PR resolves such cases by adding a check.
> fix: ensure that the parent of a SourceRoot cannot be itself

- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/parser.rs
> Change 'Length' to 'Len'

- Cargo.lock
- crates/hir-ty/src/display.rs
- crates/hir/Cargo.toml
- crates/hir/src/display.rs
- crates/ide/src/hover/render.rs
fix #12917.
1. Added Support for displaying the container and type bounds from it when hovering on functions with generic types.
2. Added a user config to determine whether to display container bounds (enabled by default).
3. Added regression tests.
4. Simplified and refactored `hir/display.rs` to improve readability.
> feat: show type bounds from containers when hovering on functions

- crates/project-model/src/lib.rs
- crates/project-model/src/project_json.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/target_spec.rs
- docs/dev/lsp-extensions.md
- editors/code/src/commands.ts
- editors/code/src/debug.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
- editors/code/src/util.ts
- editors/code/tests/unit/runnable_env.test.ts
This is a follow-up on #16135, resolving the feedback raised :)
Allow rust-project.json to include shell runnables, of the form:
```
{
"build_info": {
"label": "//project/foo:my-crate",
"target_kind": "bin",
"shell_runnables": [
{
"kind": "run",
"program": "buck2",
"args": ["run", "//project/foo:my-crate"]
},
{
"kind": "test_one",
"program": "test_runner",
"args": ["--name=$$TEST_NAME$$"]
}
]
}
}
```
If these runnable configs are present for the current crate in rust-project.json, offer them as runnables in VS Code.
This PR required some boring changes to APIs that previously only handled cargo situations. I've split out these changes as commits labelled 'refactor', so it's easy to see the interesting changes.
> Allow rust-project.json to include arbitrary shell commands for runnables

- crates/rust-analyzer/src/config.rs
See #17409 
This patch prevents infinite looping from cycles by giving up if the number of source roots checked for a config value reaches the total number of source roots.
Alternative more precise options include creating a set of all source roots visited and giving up as soon as a cycle is encountered, but I wasn't sure how costly an allocation would be here for performance.
Can confirm that locally this fixes the problem for me.
> fix: add a breaker to avoid infinite loops from source root cycles

- editors/code/src/tasks.ts
Fixes #17402.
Sorry about this—I think I missed up the rebase!
> fix: avoid doubling cargo args in runnables

- crates/hir-def/src/hir.rs
- crates/hir-def/src/nameres.rs
- crates/hir-expand/src/hygiene.rs
- crates/hir/src/has_source.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide-completion/src/completions/env_vars.rs
- crates/ide-db/src/famous_defs.rs
- crates/parser/src/grammar.rs
- crates/rust-analyzer/src/tracing/hprof.rs
- crates/salsa/src/lib.rs
- crates/span/src/hygiene.rs
- crates/stdx/src/anymap.rs
- crates/test-utils/src/fixture.rs
- crates/test-utils/src/lib.rs
- crates/toolchain/src/lib.rs
`cargo doc` generates a bunch of warnings on rust-analyzer. Fix all the bare URL and empty code block warnings.
> internal: Fix rustdoc warnings

- crates/hir-def/src/lib.rs
- crates/hir-expand/src/lib.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/salsa/src/interned.rs
- crates/salsa/src/lib.rs
`impl_intern_value_trivial` can be defined with a trait directly, so prefer that over a macro definition.
> refactor: Prefer plain trait definitions over macros for impl_intern_value_trivial

- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
- editors/code/src/toolchain.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/17436
> Fix and cleanup VSCode task building

- crates/ide/src/inlay_hints.rs
These are not currently documented and could cause users to think that their rust-analyzer configuration is broken.
Partially addresses #17433.
> docs: document omission heuristics for parameter inlay hints

- docs/user/manual.adoc
To generate all the requisite files, you need to run `cargo xtask codegen` not `cargo test -p xtask`.
> docs: fix manual generation instructions

- crates/ide-diagnostics/src/handlers/unlinked_file.rs
This partially reverts #17350, based on the feedback in #17397.
If we don't have an autofix, it's more annoying to highlight the whole file. This autofix heuristic fixes the diagnostic being overwhelming during startup.
> fix: Only show unlinked-file diagnostic on first line during startup

- crates/ide/src/extend_selection.rs
fix #17420.
When calling 'extend_selection' within a string, r-a attempts to locate the current word at the cursor. This is done by finding the first char before the cursor which is not a letter, digit, or underscore.
The position of this character is referred to as `start_idx`, and the word is considered to start from `start_idx + 1`. However, for wide characters, `start_idx + 1` is not character boundaries, which leading to panic. We should use `ceil_char_boundary` to ensure that the idx is always on character boundaries.
> fix: handle character boundaries for wide chars in extend_selection

- crates/ide-completion/src/completions/field.rs
- crates/ide-completion/src/completions/item_list.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/completions/pattern.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/completions/vis.rs
- crates/ide-completion/src/tests/item.rs
- crates/ide-completion/src/tests/pattern.rs
- crates/ide-completion/src/tests/record.rs
fix #17428.
When completing some specific keywords, it would be convenient if r-a could automatically add a space afterwards.
This PR implements this feature for the following keywords:
- Visibility: `pub`, `pub(crate)`, `pub(super)`, `pub(in xxx)`
- Pattern: `ref` / `mut`
- Others: `unsafe` / `for` / `where`
> feat: add space after specific keywords in completion

- docs/dev/README.md
- docs/user/manual.adoc
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/main.ts
Implement client-side command to toggle LSP logs in VSCode.
The command replaces the need to add/remove the `"rust-analyzer.trace.server": "verbose"` setting each time one wants to display logs. I've also updated the docs/ instances that reference the now outdated manual method.
The command labeled `rust-analyzer: Toggle LSP Logs` enables the setting project-wide and opens the relevant trace output channel.
Closes #8233
> feat: add `toggleLSPLogs` command

- crates/hir/src/term_search.rs
- crates/hir/src/term_search/expr.rs
- crates/hir/src/term_search/tactics.rs
- crates/ide-assists/src/handlers/term_search.rs
- crates/ide-completion/src/render.rs
New tactic to cover some more exotic cases that started bothering me.
Associated constants seem to be common in [axum](https://github.com/tokio-rs/axum/blob/806bc26e62afc2e0c83240a9e85c14c96bc2ceb3/examples/readme/src/main.rs#L53).
> Term search: new tactic for associated item constants

- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/config.rs
See #17409
We can view the connections between roots as a graph. The problem is that this graph may contain cycles, so when adding edges, it is necessary to check whether it will lead to a cycle.
Since we ensure that each node has at most one outgoing edge (because each SourceRoot can have only one parent), we can use a disjoint-set to maintain the connectivity between nodes. If an edge’s two nodes belong to the same set, they are already connected.
Additionally, this PR includes the following three changes:
1. Removed the workaround from #17409.
2. Added an optimization: If `map.contains_key(&SourceRootId(*root_id as u32))`, we can skip the current loop iteration since we have already found its parent.
3. Modified the inner loop to iterate in reverse order with …
> fix: ensure there are no cycles in the source_root_parent_map

- editors/code/src/main.ts
A warning was introduced regarding the incompatabilities between `rust-analyzer` and `panicbit.cargo`'s diagnostics / `cargo check` functionality.
This functionality has been removed in the latest version of the cargo extension (`0.3.0`), which is why the warning can be removed now.
> Remove panicbit.cargo extension warning

- crates/hir/src/semantics.rs
- crates/ide/src/expand_macro.rs
This PR adds a filter on the types of built in macros that are allowed to be expanded. 
Currently, This list of allowed macros contains, `stringify, cfg, core_panic, std_panic, concat, concat_bytes, include, include_str, include_bytes, env` and `option_env`.
Fixes #14177
> Filter builtin macro expansion

- crates/hir-expand/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17453, Fixes https://github.com/rust-lang/rust-analyzer/issues/17458
> fix: Fix IDE features breaking in some attr macros

- crates/hir-expand/src/fixup.rs
> Check that Expr is none before adding fixup

- crates/hir/src/lib.rs
fix #17425.
When converting `PathResolution` to `ItemInNs`, we should convert `ModuleDef::Macro` to `ItemInNs::Macros` to ensure that it can be found in `DefMap`.
> fix: use ItemInNs::Macros to convert ModuleItem to ItemInNs

- crates/hir/src/term_search.rs
- crates/hir/src/term_search/tactics.rs
- crates/ide-assists/src/handlers/term_search.rs
- crates/ide-completion/src/render.rs
- crates/ide-diagnostics/src/handlers/typed_hole.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Working on the paper @phijor found that "Data constructor" tactic could be simplified quite a bit by running it only in the backwards direction. With n+1 rounds it has same coverage as previous implementation in n rounds, however the tactic it self is more simple and also potentially faster as there is less to do.
In a nutshell the idea is to only work with types in the wish-list rather than with any types.
Turns out it is quite a bit faster:
Before:
```
ripgrep:
Tail Expr syntactic hits: 238/1692 (14%)
Tail Exprs found: 1223/1692 (72%)
Term search avg time: 15ms
nalgebra:
Tail Expr syntactic hits: 125/3001 (4%)
Tail Exprs found: 2143/3001 (71%)
Term search avg time: 849ms
```
After
````
ripgrep:
Tail Expr syntactic hits: 246/1692 (14%)
Tail Exprs found: 1209/1692 (71%)
Term search avg …
```
> Simplify some term search tactics

- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/pattern.rs
fix #17480.
We can write `let S { a, b } = s;` or `let Some(x) = a else {}`, so it is reasonable to allow pattern completions in `LetStmt`.
> fix: pattern completions in let-stmt

- crates/ide-diagnostics/src/handlers/unlinked_file.rs
- editors/code/src/client.ts
Use full sentences, and mention how to disable the diagnostic if users are intentionally working on unowned files.
(Full disclosure: I've tested a rust-analyzer build in VS Code, but the pop-up logic is currently disabled due to #17062, so I haven't tested that.)
> fix: Improve hover text in unlinked file diagnostics

- crates/ide-assists/src/handlers/remove_parentheses.rs
- crates/syntax/src/ast/prec.rs
> fix: don't remove parentheses for calls of function-like pointers that are members of a struct or union

- crates/rust-analyzer/src/config.rs
With each `config::apply_change` duplicate configs were being added.
Now we first drain the vec that holds these and then start adding. This fixes #17485
> minor : Fix duplicate snippets showing up on hover.

- .github/workflows/release.yaml
These will stop working in a couple of days. I think we could still use them in a more efficient way, but more tweaking is needed for that.
> minor: Bump `actions/download-artifact` and `upload-artifact`

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/regression.rs
Fixes #17199 and fixes #17403
In the previous implementation, I passed `rpits` as a function parameter and used `idx` of `ImplTraitId` for indexing `ImplTrait`.
https://github.com/rust-lang/rust-analyzer/blob/4e836c622a7bdab41be8e82733dd9fe40af128b2/crates/hir-ty/src/infer.rs#L881-L887
But that `idx` is rather a "local" one, so in the cases like mentioned issues, the async function that can be expanded roughly as
```rust
type TypeAlias = impl Something;
fn expanded_async() -> impl Future<Output = TypeAlias> { ... }
```
there are two bundles of `ImplTraits`; one for the `impl Future` and the other one for `TypeAlias`.
So using `idx` with `rpits` returns `ImplTrait` for `impl Future` even if we are asking for `TypeAlias` and this caused a stack overflow.
This PR is a fix for that …
> Use proper `ImplTraits` in `insert_inference_vars_for_impl_trait`

- crates/ide-completion/src/completions/item_list.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/item_list.rs
fix #17500 
1. fix completions after async kw
2. fix completions for `async` kw in trait
> fix: completions after async kw

- crates/ide-assists/src/handlers/bool_to_enum.rs
This PR adds parameter support for `bool_to_enum` assists. Essentially, the assist can now transform this:
```rs
fn function($0foo: bool) {
if foo {
println!("foo");
}
}
```
To this,
```rs
#[derive(PartialEq, Eq)]
enum Bool { True, False }
fn function(foo: Bool) {
if foo == Bool::True {
println!("foo");
}
}
```
Thanks to @/davidbarsky  for the test skeleton (:
Closes #17400
> feat: add bool_to_enum assist for parameters 

- crates/hir/src/term_search/expr.rs
- crates/ide-assists/src/assist_config.rs
- crates/ide-assists/src/handlers/term_search.rs
- crates/ide-assists/src/tests.rs
- crates/ide-completion/src/render.rs
- crates/ide-diagnostics/src/handlers/typed_hole.rs
- crates/ide-diagnostics/src/lib.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Basically two things:
- Allow optionally disabling "borrow checking" restrictions on term search code assists. Sometimes it is better to get invalid suggestions and fix borrow checking issues later...
- Remove explicit generics in generated expressions. I find it quite rare that one writes `None::<T>` instead of `None`.
> Quality of life improvements to term search

- crates/ide-assists/src/handlers/merge_imports.rs
- crates/ide-assists/src/handlers/normalize_import.rs
- crates/ide-db/src/imports/merge_imports.rs
It changes behaviour and can cause collisions. E.g. for the following snippet
```rs
mod foo {
pub mod bar {}
pub const bar: i32 = 8;
}
// transforming the below to `use foo::bar;` causes the error:
//
//   the name `bar` is defined multiple times
use foo::bar::{self};
const bar: u32 = 99;
fn main() {
let local_bar = bar;
}
```
we still normalize
```rs
use foo::bar;
use foo::bar::{self};
```
to `use foo::bar;` because this cannot cause collisions.
See: https://github.com/rust-lang/rust-analyzer/pull/17140#issuecomment-2079189725
> do not normalize `use foo::{self}` to `use foo`

- editors/code/src/debug.ts
> pass cargo extra args when debugging

- crates/hir-ty/src/builder.rs
- crates/hir-ty/src/generics.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17075, https://github.com/rust-lang/rust-analyzer/issues/17515
We were incorrectly filling the default params due to our odd order of lifetime parameters vs type/const params. So this needs some special handling so that we don't shift the defaults around.
> fix: Fix lifetime parameters moving parameter defaults

- crates/hir-ty/src/diagnostics/expr.rs
Should fix https://github.com/rust-lang/rust-analyzer/issues/17509, checking when errors are involved is generally a bad idea as the algorithm doesn't really expect error types in the first place I believe
> fix: Skip match exhaustiveness checking if pattern type contains errors

- crates/ide-diagnostics/src/lib.rs
These will only add to the noise when something very unexpected breaks or where parser recovery fails to kick in.
> fix: Don't emit semantic diagnostics in files with a lot of syntax errors

- crates/hir-def/src/hir/type_ref.rs
- crates/hir-def/src/lower.rs
- crates/hir-def/src/path/lower.rs
- crates/hir-ty/src/tests/traits.rs
Fixes #17498
The above issue is due to formatting self referencing, recursive bound like `Implemented(^0.0: TraitId(0)<[?0 := ^0.0]>)` on the codes like;
```rust
trait Foo<T> {}
trait Bar {}
fn test(foo: impl Foo<impl Bar>) { ... }
```
When lowering predicate `impl Foo<impl Bar>` in `trait_environment_query`, the outer `impl Foo<...>` is treated as predicates, so the first `TypeRef` that passes the following code is `impl Bar`;
https://github.com/rust-lang/rust-analyzer/blob/cae997e3380363a906588f14c7b4587f39cf09f5/crates/hir-ty/src/lower.rs#L376-L400
and thus the `idx` is `0` in the above context.
But the following code sets `self_ty` as the `BoundVar` with `idx = 0` because the target param id for predicate  `impl Foo<...>` is `0` since `impl Foo` is the first generic-like parameter of …
> Disallow nested impl traits

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/main.ts
This is a basic implementation of a landing and FAQ page; I've included the bare-bones information as well as a [recommended section on inlay hints](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Landing.20Page/near/446135321).
I've also added `rust-analyzer: Open Walkthrough` and `rust-analyzer: Open FAQ` commands for ease of access.
I am hoping to create a small list of FAQ to include that might be useful as well as any other information I may have missed in the landing page. Feel free to share any suggestions!
cc #13351
> feat: Add landing/faq walkthrough pages

- editors/code/src/config.ts
- editors/code/src/debug.ts
- editors/code/src/run.ts
- editors/code/src/toolchain.ts
- editors/code/tests/unit/runnable_env.test.ts
Fixes https://github.com/rust-lang/rust-analyzer/pull/17495#issuecomment-2211717224
> fix: Fix passing `message-format` after -- in debugging

- editors/code/package.json
- editors/code/src/bootstrap.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
- editors/code/tests/unit/settings.test.ts
- editors/code/tests/unit/tasks.test.ts
I've misunderstood parts of the code here which caused runnables to arbitrarily break :) (I have yet to understand the conditions that made them break though, there is some odd caching involved I feel like ...)
Fixes https://github.com/rust-lang/rust-analyzer/issues/17402
> fix: Fix runnables being incorrectly constructed

- crates/flycheck/src/lib.rs
Fixes https://github.com/rust-lang/rustlings/issues/1628
@Veykril I am not sure about what you meant with "unconditionally" in https://github.com/rust-lang/rustlings/issues/1628#issuecomment-2212492230, but I didn't find out how to get the version of the toolchain anyway to do a check like in [this snippet](https://github.com/rust-lang/rust-analyzer/blob/a5b21ea0aa644dffd7cf958b43f11f221d53404e/crates/project-model/src/build_scripts.rs#L125-L127). Is this check even required if rust-analyzer was installed with the toolchain?
`--keep-going` was [stabilized in 1.74](https://github.com/rust-lang/cargo/blob/master/CHANGELOG.md#cargo-174-2023-11-16)
> Add --keep-going to the check command

- crates/hir-def/src/hir.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide/src/hover/tests.rs
- crates/syntax/src/ast/token_ext.rs
Fixes #17556 by delaying parsing until the type is known. Also adds a test to check the issue is fixed.
> fix: Fix double rounding of `f32` literals

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/generic_param.rs
- crates/ide/src/inlay_hints/param_name.rs
- crates/ide/src/lib.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- docs/user/generated_config.adoc
- editors/code/package.json
fixes #11091
By default, only hints for const generic parameters are shown, and this can be configured through `rust-analyzer.inlayHints.genericParameterHints.enable`.
Probably needs more testing.
> feat: add inlay hints for generic parameters

- editors/code/package.json
Having more than one is potentialyl annoying as both will get opened upon install, using walkthroughs for this is not ideal. So this merges the two and also adds a couple tips, fixes https://github.com/rust-lang/rust-analyzer/issues/17569
> internal: Remove faq landing page, improve main one

- crates/ide-assists/src/handlers/bool_to_enum.rs
This PR introduces a check for the existence of another enum within the current scope, and if it exist, we skip `add_enum_def`.
Currently, when using the `bool_to_enum` assist more than once, it is possible to add multiple enum definitions. For example, the following snippet,
```rs
#[derive(PartialEq, Eq)]
enum Bool {
True,
False,
}
fn main() {
let a = Bool::True;
let b = true;
println!("Hello, world!");
}
```
will be transformed into,
```rs
#[derive(PartialEq, Eq)]
enum Bool {
True,
False,
}
#[derive(PartialEq, Eq)]
enum Bool {
True,
False,
}
fn main() {
let a = Bool::True;
let b = Bool::True;
println!("Hello, world!");
}
```
This can be annoying for users to clean up.
> feat: do not add new enum if it already exists

- crates/ide-assists/src/assist_context.rs
- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/tests.rs
- crates/ide-db/src/assists.rs
- crates/ide-db/src/source_change.rs
- crates/ide-diagnostics/src/handlers/trait_impl_redundant_assoc_item.rs
- crates/ide-diagnostics/src/handlers/typed_hole.rs
- crates/ide-diagnostics/src/handlers/unresolved_field.rs
- crates/ide-diagnostics/src/handlers/unresolved_method.rs
- crates/ide-diagnostics/src/handlers/unused_variables.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide/src/ssr.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/main.ts
When the user applies the "Extract Variable" assist, the cursor is
positioned at the newly inserted variable. This commit adds a command
to the assist that triggers the rename action in VSCode. This way, the
user can quickly rename the variable after applying the assist.
Fixes part of: #17579
https://github.com/user-attachments/assets/4cf38740-ab22-4b94-b0f1-eddd51c26c29
I haven't yet looked at the module or function extraction assists yet.
> Trigger VSCode to rename after extract variable assist is applied

- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
Updates the incorrect case diagnostic to check:
1. Fields of enum variants. Example:
```rust
enum Foo {
Variant { nonSnake: u8 }
}
```
2. All variable bindings, instead of just let bindings and certain match arm patters. Examples:
```rust
match 1 { nonSnake => () }
match 1 { nonSnake @ 1 => () }
match 1 { nonSnake1 @ nonSnake2 => () } // slightly cursed, but these both introduce new
// bindings that are bound to the same value.
const ONE: i32 = 1;
match 1 { nonSnake @ ONE } //  ONE is ignored since it is not a binding
match Some(1) { Some(nonSnake) => () }
struct Foo { field: u8 }
match (Foo { field: 1 } ) {
Foo { field: nonSnake } => ();
}
struct Foo { nonSnake: u8 } // diagnostic here, at definition
match (Foo { nonSnake: 1 } ) { // no diagnostic here...
Foo { nonSnake } => ();    // …
```
> feat: Add incorrect case diagnostics for enum variant fields and all variables/params

- Cargo.lock
- crates/hir-expand/src/attrs.rs
- crates/hir-expand/src/lib.rs
- crates/mbe/Cargo.toml
- crates/mbe/src/lib.rs
- crates/mbe/src/syntax_bridge.rs
- crates/proc-macro-api/Cargo.toml
- crates/proc-macro-api/src/msg.rs
- crates/proc-macro-api/src/msg/flat.rs
- crates/proc-macro-srv/Cargo.toml
- crates/tt/Cargo.toml
- crates/tt/src/lib.rs
Quick follow up on https://github.com/rust-lang/rust-analyzer/pull/17559 breaking things
> Fix incorrect encoding of literals in the proc-macro-api on version 4

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/target_spec.rs
- editors/code/src/debug.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
- editors/code/src/toolchain.ts
With this the client doesn't necessarily need to guess the sysroot anymore
> Set `RUSTC_TOOLCHAIN` for runnables

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Missed this in the review but we should show const param hints, not lifetime param hints by default
> Fix incorrect generic parameter hint defaults

- crates/hir-def/src/data.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/intern/src/symbol/symbols.rs
- crates/parser/src/edition.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17256
> Support rustc_skip_during_method_dispatch

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/flycheck/src/lib.rs
- crates/flycheck/src/project_json.rs
- crates/load-cargo/src/lib.rs
- crates/project-model/src/project_json.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/op_queue.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/src/tracing/config.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- docs/dev/lsp-extensions.md
- docs/user/generated_config.adoc
- editors/code/package.json
This PR's been a long-time coming, but like the title says, it introduces server-side project discovery and removes the extension hooks I previously introduced. I don't think this PR is ready to land, but here are the things I'm feeling squishy about:
- I don't think I like the idea of introducing the `cargo-metadata` command-but-for-everything-else in the `flycheck` module, but the progress reporting infrastructure was too convenient to pass up. Happy to move it elsewhere.
Here are the things I _know_ I need to change:
- For progress reporting, I'm extracting from a `serde_json::Value` that corresponds to `tracing_subsciber::fmt::Layer`'s JSON output. I'd like to make this a bit more structured/documented than the current nonsense I wrote.
- The progress reporting currently hardcodes …
> feature: teach rust-analyzer to discover `linked_projects`

- crates/ide-assists/src/handlers/merge_imports.rs
- crates/ide-db/src/imports/merge_imports.rs
> fix: handle synonymous imports with different renaming in 'merge imports'

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/main.ts
Removed no longer functional `rust-analyzer.openFAQ` command created in #17508
> internal: remove rust-analyzer.openFAQ

- crates/ide/src/inlay_hints/closing_brace.rs
close https://github.com/rust-lang/rust-analyzer/issues/17582
> feat: add inlay hint support for block expr with lifetime label

- crates/ide-assists/src/handlers/bind_unused_param.rs
- crates/ide-completion/src/item.rs
- crates/ide-diagnostics/src/handlers/typed_hole.rs
- crates/ide/src/rename.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/lsp/utils.rs
- crates/syntax/src/algo.rs
- crates/syntax/src/ast/make.rs
Clean up a few minor refs in `format!` macro, as it has a performance cost. Apparently the compiler is unable to inline `format!("{}", &variable)`, and does a run-time double-reference instead (format macro already does one level referencing). Inlining format args prevents accidental `&` misuse.
See https://github.com/rust-lang/rust-clippy/issues/10851
> Avoid ref when using format! in compiler

- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
Fixes #17585, which doesn't affect daily use cases but quite annoying in development of r-a itself like writing tests.
This PR applies similar approach as in #17534, skipping match usefulness check for patterns containing errors
> fix: Panic in debug profile for tuple deconstruct with arity mismatch

- crates/hir-def/src/nameres/mod_resolution.rs
- crates/hir-def/src/nameres/tests/macros.rs
Child modules wouldn't use the correct candidate paths due to a branch that doesn't seem to be doing what it's intended to do. Removing the branch fixes the problem and all existing test cases pass.
Having no knowledge of how any of this works, I believe this fixes #17645. Using another test that writes the included mod directly into `lib.rs` instead, I found the difference can be traced to the candidate files we use to look up mods. A separate branch for if the file comes from an `include!` macro doesn't take into account the original mod we're contained within:
```rust
None if file_id.macro_file().map_or(false, |it| it.is_include_macro(db.upcast())) => {
candidate_files.push(format!("{}.rs", name.display(db.upcast())));
candidate_files.push(format!("{}/mod.rs", …
```
> Fix path resolution for child mods of those expanded by `include!`

- crates/hir-def/src/find_path.rs
- crates/test-fixture/src/lib.rs
This should generally speed up path finding for std items as we no longer bother looking through all external dependencies. It also makes more sense to prefer importing std items from the std dependencies directly.
Fixes https://github.com/rust-lang/rust-analyzer/issues/17540
> Prefer standard library paths over shorter extern deps re-exports

- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide/src/file_structure.rs
- crates/test-utils/src/minicore.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/16371
> fix: Allow flyimport to import primitive shadowing modules

- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests/macros.rs
Now with more comprehensive testing! This adds tests for includes within modules. Previous testing was not comprehensive enough since submodules that use `include!` didn't actually work either! The `ModDir` used for resolving mods relative to included files has to be `ModDir::root()`. The original test just so happened to put the submodules in the root which made this work, but if you put the `include!` inside a `mod` block it didn't work.
With this change, when collecting a macro expansion, if the macro call is an `include!`, we use the `ModDir::root()` instead of the current module we're in.
> Fix more path resolution for included submodules

- editors/code/src/bootstrap.ts
- editors/code/src/ctx.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/17663
> Use rustup rust-analyzer component when there is a toolchain file override for the opened workspace

- crates/hir-def/src/body/lower.rs
- crates/ide-diagnostics/src/handlers/mismatched_arg_count.rs
Fixes #17292
Currently, Rust Analyzer lowers `ast::Pat::RestPat` into `Pat::Missing` in general cases on the following lines;
https://github.com/rust-lang/rust-analyzer/blob/ffbc5ad993d5cd2f3b8bcf9a511165470944ab91/crates/hir-def/src/body/lower.rs#L1359-L1367
And in some proper positions such as `TupleStruct(..)`, it is specially handed on the following lines;
https://github.com/rust-lang/rust-analyzer/blob/ffbc5ad993d5cd2f3b8bcf9a511165470944ab91/crates/hir-def/src/body/lower.rs#L1429-L1437
This behavior is reasonable because rustc does similar things in
https://github.com/rust-lang/rust/blob/62c068feeafd1f4abbf87243d69cf8862e4dd277/compiler/rustc_ast_lowering/src/pat.rs#L108-L111
and
https://github.com/rust-lang/rust/blob/62c068feeafd1f4abbf87243d69cf8862e4dd277/compiler/rustc_ast_loweri …
> Allow macro expansions into `RestPat` in tuple args work as ellipsis like plain `RestPat`

- crates/ide-db/src/syntax_helpers/node_ext.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/highlight_related.rs
- crates/ide/src/navigation_target.rs
- crates/ide/src/references.rs
fix #17517.
This PR implements **go-to-definition** and **find-references** functionalities for control flow keywords, which is similar to the behaviors in the `highlight-related` module. Besides, this PR also fixes some incorrect behaviors in `highlight-related`.
1. **Support for go-to-definition on control flow keywords**:  
This PR introduces functionality allowing users to navigate on the definition of control flow keywords (`return`, `break`, `continue`).
Commit: 2a3244ee147f898dd828c06352645ae1713c260f..7391e7a608634709db002a4cb09229de4d12c056.
2. **Bug fixes and refactoring in highlight-related**:
- **Handling return/break/continue within try_blocks**:  
This PR adjusted the behavior of these keywords when they occur within `try_blocks`. When encounter these keywords, the program …
> feat: go-to-def and find-references on control-flow keywords

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
These can crop up when the `Future` related lang items are missing
> Remove incorrect never! invocations

- crates/hir-def/src/db.rs
- crates/hir-expand/src/db.rs
- crates/ide-db/src/lib.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
This query is being invalidated all the time anyways (we have an extra query on top of it for the body incrementality that is not source dependent), so there is little reason to keep these around all the time when only some IDE features are interested in them.
> LRU `body_with_source_map` query

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/hir.rs
- crates/hir-ty/src/diagnostics/match_check.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir/src/lib.rs
- crates/ide/src/inlay_hints/implicit_drop.rs
This should save a bit of memory now that we LRU the source map
> internal: Shrink size of `Binding`

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Closes https://github.com/rust-lang/rust-analyzer/issues/17643
A very simple PR that removes the lens.forceCustomCommands config feature without side effects.
> Remove lens.forceCustomCommands config

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/tests/slow-tests/ratoml.rs
This is a follow-up PR to #17058.
- Parse errors are reflected as such by defining a new variant called `ConfigError::ParseError`
- New error collection has been added to store config level agnostic errors.
EDIT : Some things that this PR promised to solve are removed and will be addressed by other PRs
> minor : fixes for ratoml module

- crates/hir/src/lib.rs
This PR is motivated by an [outside use](https://github.com/regexident/cargo-modules) of the `ra_ap_hir` crate that would benefit from being able to more efficiently query for all impls of a given module (instead of having to query for its parent crate's impls and then filtering on `impl_hir.module(db) == module_hir`).
I have the suspicion that the code as is won't quite work for file-level modules, since those don't have a block, afaict, but with all the crate-rename and version shenanigans around the `ra_ap_` release process I haven't yet been able to figure out how to patch a `ra_ap_` dependency from a third-party crate (let alone how to test this from inside of `rust-analyzer`), so haven't been able to actually run and test this. 😔
Any hints on how to make this (i.e. the code itself, …
> Add method `Impl::all_in_module(…)` for allowing more localized querying

- crates/rust-analyzer/src/handlers/request.rs
Bit of a lazy change, but this is was pretty handy. I think I should clean up the configuration into something a bit more legible (maybe serialize as JSON?), but I think this is a good enough starting point that we might as well start asking people for it in issue reports.
> internal: add more output to the status command

- .github/workflows/ci.yaml
- Cargo.toml
- crates/salsa/src/intern_id.rs
- crates/stdx/src/anymap.rs
- crates/stdx/src/process.rs
- lib/line-index/src/lib.rs
> internal: Fix and enable unsafe_op_in_unsafe_fn

- crates/hir-def/src/attr.rs
- crates/hir-def/src/body.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/data/adt.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/item_tree/tests.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/diagnostics.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/src.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/patterns.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/intern/src/symbol/symbols.rs
- crates/span/src/ast_id.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
- xtask/src/codegen/grammar.rs
These are too volatile, and the only reason for them seems to be for cfg diagnostics which does not carry the weight
> Remove Params and Fields from AstIdMap

- crates/project-model/src/env.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17686
> fix: Support new cargo config get env format

- crates/hir-def/src/hir/type_ref.rs
- crates/ide-db/src/generated/lints.rs
- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/generated/runner.rs
- crates/parser/test_data/parser/inline/ok/precise_capturing.rast
- crates/parser/test_data/parser/inline/ok/precise_capturing.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
This PR adds basic support for the following syntax.
```rs
fn captures<'a: 'a, 'b: 'b, T>() -> impl Sized + use<'b, T> {}
//                                  ~~~~~~~~~~~~~~~~~~~~~~~
//                          This opaque type does not capture `'a`.
fn outlives<'o, T: 'o>(_: T) {}
fn caller<'o, 'a, 'b: 'o, T: 'o>() {
//        ~~
//        ^ Note that we don't need `'a: 'o`.
outlives::<'o>(captures::<'a, 'b, T>());
}
```
Related to #17598
> feat: add preliminary support for `+ use<..>` `precise_capturing` syntax

- crates/hir-expand/src/builtin_fn_macro.rs
- crates/hir-expand/src/lib.rs
Temporary workaround for https://github.com/rust-lang/rust-analyzer/issues/17701
> fix: Fix includes not working with expr fragment inputs

- editors/code/src/client.ts
- editors/code/src/commands.ts
close https://github.com/rust-lang/rust-analyzer/issues/17628
> fix: tweak hover/tooltip links

- docs/dev/architecture.md
Seems this was switched over in https://github.com/rust-lang/rust-analyzer/issues/7922
I'm guessing this should skip the changelog because it's so minor, right? Reading through https://github.com/rust-lang/rust-analyzer/blob/master/docs/dev/style.md and trying to get up to speed here =)
> docs: Reference cov_mark crate instead of test_utils/mark

- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/ide/src/syntax_highlighting/tests.rs
Fix for #17497
The issue occurs because in some configurations of traits where one of them has `Deref` as a supertrait, RA's type inference algorithm fails to resolve the `Deref::Target` type, and instead uses a `TyKind::BoundVar` (i.e. an unknown type). This "autoderefed" type then incorrectly acts as if it implements all traits in scope.
The fix is to re-apply the same sanity-check that is done in [`iterate_method_candidates_with_autoref()`](https://github.com/rust-lang/rust-analyzer/blob/9463d9eea4b87e651e7d8ed8425a9c92f23b1cdf/crates/hir-ty/src/method_resolution.rs#L1008), that is: don't try to resolve methods on unknown types. This same sanity-check is now done on each autoderefed type for which trait methods are about to be checked. If the autoderefed type is unknown, then the …
> #17497 - Invalid RA diagnostic error: expected 2 arguments, found 1

- crates/flycheck/src/lib.rs
- crates/flycheck/src/test_runner.rs
- crates/rust-analyzer/src/handlers/request.rs
For https://github.com/rust-lang/rust-analyzer/issues/17470
Use the test path to identify a package in the workspace and run the unit test there instead of at the workspace.
> #17470 - run unit tests at the crate level not workspace

- crates/ide-assists/src/handlers/convert_comment_from_or_to_doc.rs
I did this the wrong way around when I implemented these assists, so here is a quick fix for it
> flip the naming of the doc comment to comment assist

- .vscode/launch.json
- editors/code/package.json
- editors/code/src/bootstrap.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/util.ts
This change updates the log format to use the vscode log format instead
of the custom log format, by replacing the `OutputChannel` with a
`LogOutputChannel` and using the `debug`, `info`, `warn`, and `error`
methods on it. This has the following benefits:
- Each log level now has its own color and the timestamp is in a more
standard format
- Inspect output (e.g. the log of the config object) is now colored
- Error stack traces are now shown in the output
- The log level is now controlled on the output tab by clicking the gear
icon and selecting "Debug" or by passing the `--log` parameter to
vscode. The `trace.extension` setting has been marked as deprecated.
Motivation:
The large uncolored unformatted log output with a large config object logged whenever it changes has always dominated …
> feat: use vscode log format for client logs

- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests/globs.rs
Follow up to #14930
Fixes #11858
Fixes #14902
Fixes #17704
I haven't reworked the code here at all - I don't feel confident in the codebase to do so - just rebased it onto the current main branch and fixed conflicts.
I'm not _entirely_ sure I understand the structure of the `check` function in `crates/hir-def/src/nameres` tests. I think the change to the test expectation from #14930 is correct, marking the `crate::reexport::inner` imports with `i`, and I understand it to mean there's a specific token in the import that we can match it to (in this case, `Trait`, `function` and `makro` of `pub use crate::defs::{Trait, function, makro};` respectively), but I had some trouble understanding the meaning of the different parts of `PerNs` to be sure.
Does this make sense?
I tested building and …
> fix: let glob imports override other globs' visibility

- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/tests/item_list.rs
- crates/ide-diagnostics/src/handlers/trait_impl_missing_assoc_item.rs
OLD:
Now:
---
This is an preparation for https://github.com/rust-lang/rust-analyzer/issues/17719.
```rust
use std::future::Future;
trait DesugaredAsyncTrait {
fn foo(&self) -> impl Future<Output = usize> + Send;
fn bar(&self) -> impl Future<Output = usize> + Send;
}
struct Foo;
impl DesugaredAsyncTrait for Foo {
fn foo(&self) -> impl Future<Output = usize> + Send {
async { 1 }
}
//
async fn bar(&self) -> usize {
1
}
}
fn main() {
let fut = Foo.bar();
fn _assert_send<T: Send>(_: T) {}
_assert_send(fut);
}
```
If we don't distinguish `async` or not. It would be confusing to generate sugared version `async fn foo ....` and original form `fn foo`  for `async fn in trait` that is defined in desugar form.
> feat(ide-completion): explictly show `async` keyword on `impl trait` methods

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin/fn_macro.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17701
> fix: Fix builtin includes rejecting raw string literals

- crates/rust-analyzer/src/capabilities.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/slow-tests/ratoml.rs
In order to globally configure a project it was, prior to this PR, possible to have a `ratoml` at the root path of a project. This is not the case anymore. Instead we now let ratoml files that are placed at the root of any workspace have a new scope called `workspace`. Although there is not a difference between a `workspace` scope and and a `global` scope, future PRs will change that.
> feat: Introduce workspace `rust-analyzer.toml`s

- crates/project-model/src/env.rs
> minor: Set tracing level to debug when `cargo config get env` fails

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/regression.rs
Fixes #17734 
Currently, we are matching non-lifetime(type or const) generic arg to liftime argument position while building substs for method calling when there are elided lifetimes.
This mismatch just make a subst for error lifetime and while this alone is not much a trouble, it also makes the mismatched type or const generic arg cannot be used in its proper place and this makes type inference failure
> fix: Errors on method call inferences with elided lifetimes

- crates/rust-analyzer/src/config.rs
Should (fingers crossed!) fix https://github.com/rust-lang/rust-analyzer/issues/17664. I opened the `rustc` workspace with the [suggested configuration](https://github.com/rust-lang/rust/blob/e552c168c72c95dc28950a9aae8ed7030199aa0d/src/etc/rust_analyzer_settings.json) and I was able to successfully open some rustc crates (`rustc_incremental`) and have IDE functionality.
@Veykril: can you try these changes and let me know if it fixed rustc?
> fix: remove AbsPath requirement from linkedProjects

- xtask/src/release.rs
Helps debugging https://github.com/rust-lang/rust-analyzer/issues/17733
> when josh-proxy screws up the roundtrip, say what the involved commits are

- editors/code/src/bootstrap.ts
- editors/code/tests/unit/bootstrap.test.ts
Selects a rust-toolchain declared RA based on its date. The earliest (oldest) RA wins and becomes the one that the workspace uses as a whole.
In terms of precedence:
nightly > stable-with-version > stable
With stable-with-version, we invoke the RA with a `--version` arg and attempt to extract a date. Given the same date as a nightly, the nightly RA will win.
Fixes #17663
> feat: Use oldest rustup rust-analyzer when toolchain override is present

- Cargo.lock
- crates/paths/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/lib.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/rust-analyzer/src/lsp/from_proto.rs
- crates/syntax/src/tests.rs
- crates/test-utils/Cargo.toml
- crates/test-utils/src/lib.rs
- crates/vfs-notify/src/lib.rs
https://github.com/rust-lang/rust-analyzer/pull/16889#discussion_r1590993282
> internal: Remove AbsPathBuf::TryFrom impl that checks too many things at once

- crates/hir-def/src/path/lower.rs
- crates/hir-ty/src/tests/regression.rs
Fixes #17191 
We are not inserting a generic arg when lowering generics like
```rust
fn foo<T: B<impl A>(..) { ... }
```
but when we are lowering predicates we do;
https://github.com/rust-lang/rust-analyzer/blob/aa00ddcf654a35ba0eafe17247cf189958d33182/crates/hir-ty/src/lower.rs#L1697-L1718
https://github.com/rust-lang/rust-analyzer/blob/aa00ddcf654a35ba0eafe17247cf189958d33182/crates/hir-ty/src/lower.rs#L310
and this mismatch causes index out of bound panic while substituting the predicates
> fix: Insert a generic arg for `impl Trait` when lowering generic args

- crates/ide-assists/src/handlers/bind_unused_param.rs
- crates/load-cargo/src/lib.rs
- crates/paths/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/manifest_path.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/tests/crate_graph.rs
- docs/user/generated_config.adoc
- editors/code/package.json
See https://github.com/rust-lang/rust/pull/128534, fixes https://github.com/rust-lang/rust-analyzer/issues/7637
Requires a toolchain from 176e54520 2024-08-04 or later to work.
> feat: Load sysroot library via cargo metadata

- docs/user/manual.adoc
Added note for Windows users to have the latest MSVC to minimize setup issues.
Closes #4870
> docs: add msvc note to manual

- crates/ide-diagnostics/src/lib.rs
- crates/ide-diagnostics/src/tests.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/rust-analyzer/src/main_loop.rs
> perf: Segregate syntax and semantic diagnostics

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/await_outside_of_async.rs
- crates/ide-diagnostics/src/lib.rs
> feat: Implement diagnostic for `await` outside of `async`

- Cargo.lock
- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/vfs-notify/Cargo.toml
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/lib.rs
- crates/vfs/src/loader.rs
Simple attempt to make some progress f or https://github.com/rust-lang/rust-analyzer/issues/17373
No clue if those atomic orderings are right, though I don't think they are really too relevant either.
A more complete fix would probably need to replace our `ProjectFolders` handling a bit.
> internal: Load VFS config changes in parallel

- crates/project-model/src/lib.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- editors/code/package.json
> Allow rust-project.json to be hidden

- crates/ide-db/src/search.rs
- crates/ide/src/references.rs
See https://github.com/rust-lang/rust-analyzer/pull/15864/files/e0276dc5ddc38c65240edb408522bb869f15afb4#r1389848845
For ADTs, to handle `{error}` in generic args, we should to convert them to ADT for comparisons; for others, we can directly compare the types.
> fix: tyck for non-ADT types when searching refs for `Self` kw

- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
`StaticIndex::compute` filters out modules from libraries. This makes an exceptions for vendored libraries, ie libraries actually defined inside the workspace being indexed.
This aims to solve https://bugzilla.mozilla.org/show_bug.cgi?id=1846041 In general StaticIndex is meant for code browsers, which likely want to index all visible source files.
> Include vendored crates in StaticIndex

- crates/hir-def/src/nameres/collector.rs
- crates/ide-diagnostics/src/handlers/inactive_code.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17817
> fix: Fix unconfigured diagnostic being attached to the wrong file for modules

- crates/rust-analyzer/src/diagnostics.rs
This should be a `continue` now
_Originally posted by @Veykril in https://github.com/rust-lang/rust-analyzer/pull/17775#discussion_r1706845633_
I've tested the release compile output with IDE in the original PR, but my test workspace had only one `.rs` file 🤦 😢
> fix: Native diagnostics not working

- crates/syntax-bridge/Cargo.toml
This is a follow-up of https://github.com/rust-lang/rust-analyzer/pull/17745, specifically [this comment](https://github.com/rust-lang/rust-analyzer/pull/17745#issuecomment-2271102382) by @lnicola.
It refines the manifest of the newly added 'syntax-bridge' crate, adding a `[package.repository]` as `workspace = true` and changes the existing `[package.description]` from "TBD" to a more useful description.
> Improve crate manifest of 'syntax-bridge', adding missing `[package.repository]` and `[package.description]` fields

- crates/hir-ty/src/display.rs
- crates/ide/src/hover/tests.rs
> fix: Panic while rendering function type hint with impl trait arg

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/lib.rs
- crates/hir-ty/src/display.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/config.rs
- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/snippet.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17840
> fix: Fix find_path not respecting non-std preference config correctly

- crates/hir-def/src/body.rs
- crates/hir-def/src/data.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17852
> fix: Correctly support `#[rustc_deprecated_safe_2024]`

- Cargo.lock
- crates/ide-db/Cargo.toml
- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
- crates/stdx/Cargo.toml
- crates/vfs-notify/Cargo.toml
- crates/vfs-notify/src/lib.rs
- crates/vfs/Cargo.toml
- crates/vfs/src/loader.rs
- lib/lsp-server/Cargo.toml
Used `Sender` directly instead of a boxed closure. There is no need to use the boxed closure. This also allows the caller to decide to do something other than `unwrap` (not a fan of it BTW).
> internal: Optimize the usage of channel senders

- crates/rust-analyzer/src/flycheck.rs
- crates/vfs-notify/src/lib.rs
- Use `Command::arg` directly
- Avoid the overhead of the `select!` macro when possible
- Use `select_biased!`
> internal: Performance optimizations

- Cargo.toml
- crates/rust-analyzer/src/handlers/dispatch.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
There is no reason for us to hit the database with queries when we certainly haven't reached a stable state yet. Instead we just reply with default request results until we are in a state where we can do meaningful work. This should save us from wasting resources while starting up at worst, and at best save us from creating query and interning entries that are non-meaningful which ultimately just end up wasting memory.
> internal: Reply to requests with defaults when vfs is still loading

- .github/workflows/publish-libs.yaml
Follow-up to #17860, see https://github.com/rust-lang/rust-analyzer/actions/runs/10350212090/job/28646162590.
> Only keep lib/ in publish-libs

- crates/hir-def/src/db.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide-diagnostics/src/handlers/macro_error.rs
- crates/ide-diagnostics/src/handlers/unlinked_file.rs
- crates/ide-diagnostics/src/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17390 at the expense of reporting duplicate diagnostics for modules that have includes in them when both the calling and called file are included.
> fix: Resolve included files to their calling modules in IDE layer

- crates/hir/src/semantics.rs
- crates/ide/src/inlay_hints/bind_pat.rs
Turns out https://github.com/rust-lang/rust-analyzer/pull/17863 made this obsolete 🎉
> internal: Remove unreachable logic for include token mapping

- Cargo.lock
- Cargo.toml
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
- crates/ide-diagnostics/src/handlers/non_exhaustive_let.rs
> feat: `min-exhaustive-patterns`

- crates/rust-analyzer/src/op_queue.rs
Add an explanatory sentence and some sample code to help readers understand why this struct exists.
> minor: Add a doc comment for OpQueue

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/simple.rs
Fixes #16287
Fixes #16286
There's one more in `write_fn_trait_method_resolution`, but I'm not sure if it won't cause further problems in `infer_closures`.
> internal: Be more resilient to bad language item definitions in binop inference

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir-ty/src/traits.rs
Fixes #17866 
The root cause of #17866 is quite horrifyng 😨 
```rust
trait T {
type A;
}
type Foo = <S as T>::A; // note that S isn't defined
fn main() {
Foo {}
}
```
While inferencing alias type `Foo = <S as T>::A`;
https://github.com/rust-lang/rust-analyzer/blob/78c2bdce860dbd996a8083224d01a96660dd6a15/crates/hir-ty/src/infer.rs#L1388-L1398
the error type `S` in it is substituted by inference var in L1396 above as below;
https://github.com/rust-lang/rust-analyzer/blob/78c2bdce860dbd996a8083224d01a96660dd6a15/crates/hir-ty/src/infer/unify.rs#L866-L869
This new inference var's index is `1`, as the type inferecing procedure here previously inserted another inference var into same `InferenceTable`.
But after that, the projection type made from the above then passed to the following …
> fix: Panic while canonicalizing erroneous projection type

- crates/hir-ty/src/display.rs
- crates/ide/src/hover/tests.rs
Fixes #17871
We call `generic_args_sans_defaults` here;
https://github.com/rust-lang/rust-analyzer/blob/64a140527b383e3a2fe95908881624fc5374c60c/crates/hir-ty/src/display.rs#L1021-L1034
but the following substitution inside that function panic in #17871;
https://github.com/rust-lang/rust-analyzer/blob/64a140527b383e3a2fe95908881624fc5374c60c/crates/hir-ty/src/display.rs#L1468
it's because the `Binders.binder` inside `default_parameters` has a same length with the generics of the function we are hovering on, but the generics of it is split into two, `fn_params` and `parent_params`.
Because of this, it may panic if the function has one or more default parameters and both `fn_params` and `parent_params` are non-empty, like the case in the title of this PR.
So, we must call …
> fix: Panic while hovering associated function with type annotation on generic param that not inherited from its container type

- crates/ide-db/src/search.rs
This speeds up short identifiers search significantly, while unlikely to have an effect on long identifiers (the analysis takes much longer than some character comparison).
Tested by finding all references to `eq()` (from `PartialEq`) in the rust-analyzer repo. Total time went down from 100s to 10s (a 10x reduction!).
Feel free to close this if you consider this a non-issue, as most short identifiers are local.
> Test for word boundary in `FindUsages`

- crates/rust-analyzer/src/command.rs
Assuming it isn't cancelled. Closes #17902.
The only place CommandHandle::join() is used is when the flycheck command
finishes, so this commit changes the behavior of the method itself.
The only reason I can see for the existing behavior is if the command is somehow holding onto a build lock longer than it should, this would force it to be released. But it would be a pretty heavy-handed way to solve that issue. I'm not aware of this occurring in practice.
> Allow flycheck process to exit gracefully

- crates/ide/src/lib.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
#17809 changed StaticIndex to include vendored libraries. This PR adds a flag to disable that behavior.
At work, our monorepo has too many rust targets to index all at once, so we split them up into several shards. Since all of our libraries are vendored, if rust-analyzer includes them, sharding no longer has much benefit, because every shard will have to index the entire transitive dependency graphs of all of its targets. We get around the issue presented in #17809 because some other shard will index the libraries directly.
> Add scip/lsif flag to exclude vendored libaries

- editors/code/package.json
- editors/code/src/config.ts
The functionality for this vscode config option was removed in #17395, so it doesn't do anything anymore.
> Remove rust-analyzer.workspace.discoverProjectRunner

- crates/syntax/Cargo.toml
To prevent #17914, I think that it would be safer pinning this before we fix it correctly
> Pin `rowan` to `0.15.15`

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
Fixes #17711
From the following test code;
```rust
//- minicore: deref
use core::ops::Deref;
struct Struct<'a, T>(&'a T);
trait Trait {}
impl<'a, T: Deref<Target = impl Trait>> Struct<'a, T> {
fn foo(&self) -> &Self { self }
fn bar(&self) {
let _ = self.foo();
}
}
```
when we call `register_obligations_for_call` for `let _ = self.foo();`,
https://github.com/rust-lang/rust-analyzer/blob/07659783fdfd4ec0a0bffa93017e33e31e567e42/crates/hir-ty/src/infer/expr.rs#L1939-L1952
we are querying `generic_predicates` and it has `T: Deref<Target = impl Trait>` predicate from the parent `impl Struct`;
https://github.com/rust-lang/rust-analyzer/blob/07659783fdfd4ec0a0bffa93017e33e31e567e42/crates/hir-ty/src/lower.rs#L375-L399
but as we can see above, lowering `TypeRef = impl Trait` doesn't take into …
> fix: Wrong BoundVar index when lowering impl trait parameter of parent generics

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/reload.rs
Helps out with https://github.com/rust-lang/rust-analyzer/issues/12499 a bit
> feat: Make rust-analyzer work partially when offline

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/regression.rs
> Include generics when lowering extern type

- crates/project-model/src/build_dependencies.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
These flags were added to help rust-analyzer integrate with repos requiring non-Cargo invocations. The consensus is that having two independent settings are no longer needed. This change removes `invocationLocation` in favor of `invocationStrategy` and changes the internal representation of `InvocationStrategy::Once` to hold the workspace root.
Closes #17848.
> chore(config): remove `invocationLocation` in favor of `invocationStrategy`

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/regression.rs
Fixes  #17921
When there is a TAIT inside of a RPIT like;
```rust
trait Foo {}
type Bar = impl Foo;
fn foo<A>() -> impl Future<Output = Bar> { .. }
```
while inferencing `fn foo`, `insert_inference_vars_for_impl_trait` tries to substitute impl trait bounds of `Bar`, i.e. `Implemented(Foo)` with RPITs `placeholders`, and this causes panic
https://github.com/rust-lang/rust-analyzer/blob/fa003262474185fd62168379500fe906b331824b/crates/hir-ty/src/infer.rs#L903-L905
> fix: Panic when a TAIT exists in a RPIT

- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/slow-tests/ratoml.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- crates/vfs/src/vfs_path.rs
Being able to do this makes little sense as this is effectively a cyclic dependency (and we do not want to fixpoint this really).
> Remove the ability to configure the user config path

- crates/hir-ty/src/lower.rs
I found this gathers wrong `Self: Sized` bound while implementing object safety, though I couldn't find proper test for this.
If we call `generic_predicates_for_param` to `Bar` in the following code;
```rust
trait Foo<T: ?Sized> {}
trait Bar<T: Foo<Self> + ?Sized> {}
```
it returns `T: Sized` and `Self: Sized` bound, because normaly, the `?Sized` bound applied properly in L1059 with;
https://github.com/rust-lang/rust-analyzer/blob/3723e5910c14f0ffbd13de474b8a8fcc74db04ce/crates/hir-ty/src/lower.rs#L1035-L1061
But we filter them before it is lowered with that function here;
https://github.com/rust-lang/rust-analyzer/blob/3723e5910c14f0ffbd13de474b8a8fcc74db04ce/crates/hir-ty/src/lower.rs#L1540-L1586
So, the `?Sized` bounded params are not gathered into `ctx.unsized_types` and thus we are …
> fix: Wrong `Sized` predicate for `generic_predicates_for_param`

- Cargo.toml
- crates/hir-expand/src/files.rs
- crates/hir-expand/src/lib.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-db/src/helpers.rs
- crates/ide-db/src/search.rs
- crates/ide-db/src/syntax_helpers/format_string_exprs.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/extend_selection.rs
- crates/ide/src/goto_declaration.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/goto_type_definition.rs
- crates/ide/src/highlight_related.rs
- crates/ide/src/hover.rs
- crates/ide/src/markup.rs
- crates/ide/src/moniker.rs
- crates/ide/src/references.rs
- crates/ide/src/signature_help.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_macros.html
Fixes https://github.com/rust-lang/rust-analyzer/issues/16235
> internal: Improve macro token mapping heuristics

- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/main_loop.rs
Since querying for a crate's target is a call to salsa and therefore blocking, flycheck task is now deferred out of main thread by using `GlobalState`s `deferred_task_queue`. Fixes #17829  and https://github.com/rust-lang/rustlings/issues/2071
> fix: run flycheck without rev_deps when target is specified

- crates/hir/src/semantics.rs
- crates/ide-db/src/search.rs
- crates/ide/src/references.rs
@Veykril said in https://github.com/rust-lang/rust-analyzer/pull/17908#issuecomment-2292958068 that people complain searches for `new()` are slow (they are right), so here I am to help!
The search is used by IDE features such as rename and find all references.
The search is slow because we need to verify each candidate, and that requires analyzing it; the key to speeding it up is to avoid the analysis where possible.
I did that with a bunch of tricks that exploits knowledge about the language and its possibilities. The first key insight is that associated methods may only be referenced in the form `ContainerName::func_name` (parentheses are not necessary!) (Rust doesn't include a way to `use Container::func_name`, and even if it will in the future most usages are likely to stay in that …
> perf: Speed up search for short associated functions, especially very common identifiers such as `new`

- crates/base-db/src/input.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/expander.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/macro_expansion_tests/mod.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/builtin.rs
- crates/hir-expand/src/builtin/fn_macro.rs
- crates/hir-expand/src/builtin/quote.rs
- crates/hir-expand/src/eager.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_type_definition.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/status.rs
- crates/intern/src/symbol/symbols.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/test-utils/src/minicore.rs
Turns out this is a pain to implement because of our hir-def hir-expand split :)
> feat: Implement `module_path` macro

- crates/project-model/src/project_json.rs
- crates/project-model/src/tests.rs
- crates/project-model/test_data/cfg-groups.json
- crates/project-model/test_data/output/rust_project_cfg_groups.txt
- docs/user/manual.adoc
> feat: Allow declaring cfg groups in rust-project.json, to help sharing common cfgs

- crates/hir-ty/src/lower.rs
Again while implementing object safety like #17939 😅 
If we call `generic_predicates_query` on `fn foo` in the following code;
```
trait Foo {
fn foo();
}
```
It returns implicit bound `Self: Sized`, even though `Self` is not appearing as a generic parameter inside angle brackets, but as a parent generic parameter, "trait self".
This PR prevent pushing "implicit" `Self: Sized` predicates in such cases
> fix: Wrong `Self: Sized` predicate for trait assoc items

- crates/rust-analyzer/src/reload.rs
rust-analyzer always watches Cargo.toml for changes, but other build systems using rust-project.json have their own build files.
Ensure we also watch those for changes, so we know when to reconfigure rust-analyzer when dependencies change.
> fix: rust-analyzer should watch build files from rust-project.json

- crates/ide-db/src/search.rs
In most places where we set a search scope it is a single file, and so the fast path will actually harm performance, since it has to search for aliases in the whole project. The only exception that qualifies for the fast path is SSR (there is an exception that don't qualify for the fast path as it search for `use` items). It sets the search scope to avoid dependencies. We could make it use the fast path, but I didn't bother.
I forgot this while working on #17927.
> fix: Don't enable the search fast path for short associated functions when a search scope is set

- crates/hir-def/src/lib.rs
- crates/hir-ty/src/method_resolution.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-diagnostics/src/handlers/unused_variables.rs
This regressed in https://github.com/rust-lang/rust-analyzer/pull/16555
> fix: Fix trait method completions not acknowledging `Deref` impls

- crates/parser/src/grammar/generic_args.rs
- crates/parser/src/grammar/generic_params.rs
- crates/parser/src/grammar/paths.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/parser/test_data/generated/runner.rs
- crates/parser/test_data/parser/inline/ok/associated_return_type_bounds.rs
- crates/parser/test_data/parser/inline/ok/return_type_syntax_assoc_type_bound.rast
- crates/parser/test_data/parser/inline/ok/return_type_syntax_assoc_type_bound.rs
- crates/parser/test_data/parser/inline/ok/return_type_syntax_in_path.rast
- crates/parser/test_data/parser/inline/ok/return_type_syntax_in_path.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
> fix: Fix Return Type Syntax to include `..` (i.e. `method(..)` and not `method()`) as specified in the RFC

- crates/hir-ty/src/display.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-completion/src/tests/predicate.rs
- crates/ide-completion/src/tests/type_pos.rs
- crates/ide/src/inlay_hints/bind_pat.rs
Fixes #17947
Changed error lifetime argument presentation in non-test environment to `'_` and now showing them even if all of args are error lifetimes.
This also influenced some of the other tests like `extract_function.rs`, `predicate.rs` and `type_pos.rs`. Not sure whether I need to refrain from adding lifetimes args there. Happy to fix if needed
> Always show error lifetime arguments as `'_`

- crates/ide-assists/src/handlers/unwrap_block.rs
The assist just assumes the `{` will be the first character, which led to strange outputs such as `nsafe {`.
Fixes #17964.
> fix: Fix "Unwrap block" assist with block modifiers
