rust-lang/rust-analyzer

- crates/hir-ty/src/display.rs
- crates/proc-macro-api/src/lib.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/env.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/tests/crate_graph.rs
Should fix https://github.com/rust-lang/rust-analyzer/issues/17748. The approach is generally not perfect though as rust-project.json projects don't benefit from this (still, nothing changes in that regard)
> Expand proc-macros in workspace root, not package root

- crates/rust-analyzer/src/main_loop.rs
Most logs lines don't have newlines, ensure fetch errors follow this pattern. This makes it easier to see which log line is associated with the error.
Before:
2024-08-28T21:11:58.431856Z ERROR FetchWorkspaceError:
rust-analyzer failed to discover workspace
After:
2024-08-28T21:11:58.431856Z ERROR FetchWorkspaceError: rust-analyzer failed to discover workspace
> internal: Avoid newlines in fetch errors

- crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs
- crates/proc-macro-srv/src/server_impl/token_id.rs
- crates/proc-macro-srv/src/server_impl/token_stream.rs
- crates/tt/src/lib.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17986
We might wanna consider backporting this to beta if that's simple enough to do
> fix: Fix TokenStream::to_string implementation dropping quotation marks

- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/mir.rs
- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/convert_closure_to_fn.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
The assist converts all captures to parameters.
Closes #17920.
This was more work than I though, since it has to handle a bunch of edge cases...
Based on #17941. Needs to merge it first.
> feat: Create an assist to convert closure to freestanding fn

- crates/rust-analyzer/src/cli/scip.rs
The SCIP output incorrectly marks some symbols as definitions because it doesn't account for the file ID when comparing the token's range to its definition's range.
This means that if a symbol is referenced in a file at the same position at which it is defined in another file, that reference will be marked as a definition. I was quite surprised by how common this is. For example, `PartialEq` is defined [here](https://github.com/rust-lang/rust/blob/1.80.1/library/core/src/cmp.rs#L273) and `uuid` references it [here](https://github.com/uuid-rs/uuid/blob/1.8.0/src/lib.rs#L329). And what do you know, they're both at offset 10083! In our large monorepo, this happens for basically every common stdlib type!
> Fix incorrect symbol definitions in SCIP output

- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/tests/generated.rs
I.e. don't generate `let var_name = &foo()`. Because it always irritates me when I need to fix that.
Anything that creates a new value don't need a reference. That excludes mostly field accesses and indexing.
I had a thought that we can also not generate a reference for fields and indexing as long as the type is `Copy`, but sometimes people impl `Copy` even when they don't want to copy the values (e.g. a large type), so I didn't do that.
> fix: Don't add reference when it isn't needed for the "Extract variable" assist

- crates/ide-assists/src/handlers/convert_named_struct_to_tuple_struct.rs
- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
Fixes #17983.
I tried to use the `SourceChangeBuilder::make_mut()` API, but it duplicated the attribute...
> Consider field attributes when converting from tuple to named struct and the opposite

- xtask/src/codegen.rs
When formatting generated code the xtask crate attempts to run `rustup run stable rustfmt`, which fails if `rustup` is not installed. This results in test failures when another source manages the compiler toolchain, for example when using Nix (or any other distro-specific packaging solution):
* xtask::codegen::grammar::test
* xtask::codegen::assists_doc_tests::test
With this PR xtask will first attempt to run `rustup run stable rustfmt`, and if that fails just plain `rustfmt`. It still validates a stable version is being used. This allows `cargo test` to pass on systems that do not use `rustup`.
> fix: do not assume rustup is installed in xtask codegen

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/generics.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/mir/eval/tests.rs
- crates/hir-ty/src/object_safety.rs
- crates/hir-ty/src/object_safety/tests.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir-ty/src/tests/traits.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/replace_filter_map_next_with_find_map.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/inlay_hints/adjustment.rs
- crates/intern/src/symbol/symbols.rs
- crates/test-utils/src/minicore.rs
> feat: Implement object safety and its hovering hint

- crates/hir-ty/src/db.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/object_safety.rs
- crates/hir-ty/src/object_safety/tests.rs
Fixes #17998
I tried to get generic predicates of assoc function itself, not inherited from the parent here;
https://github.com/rust-lang/rust-analyzer/blob/0ae42bd42576566540a84c62e118aa823edcf2ec/crates/hir-ty/src/object_safety.rs#L420-L442
But this naive equality check approach doesn't work when the assoc function has one or more generic paramters like;
```rust
trait Foo {}
trait Bar: Foo {
fn bar(&self);
}
```
because the generic predicates of the parent, `Bar` is `[^1.0 implements Foo]` and the generic predicates of `fn bar` is `[^1.1 implements Foo]`, which are different.
This PR implements a correct logic for filtering out parent generic predicates for this.
> fix: `std::error::Error` is object unsafe

- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide/src/hover/tests.rs
- crates/test-utils/src/minicore.rs
The compiler no longer does as well; see https://github.com/rust-lang/rust/pull/125834.
Also require unsafe when accessing `extern` `static` (other than by `addr_of!()`).
Fixes #17978.
> Do not report missing unsafe on `addr_of[_mut]!(EXTERN_OR_MUT_STATIC)`

- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/context/analysis.rs
> fix(ide-completion): fix handling of `for` in `impl T for A` in function body

- crates/rust-analyzer/src/op_queue.rs
I spent a while debugging some OpQueue behaviours and found the API slightly confusing, so I've added doc comments to clarify what each OpQueue method does.
> internal: Add doc comments to OpQueue

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fixes #17989.
I wonder if this should be instead done in the editor, that will do it in a language-agnostic way. Can't hurt to do it in rust-analyzer, I guess.
> Provide an option to hide deprecated items from completion

- crates/ide-assists/src/handlers/flip_comma.rs
Attributes often contain path followed by a token tree (e.g. `align(2)`), and the previous code handled them as two separate items, which led to results such as `#[repr(alignC, (2))]`.
An alternative is to just make the assist unavailable in attributes, like we do in macros. But contrary to macros, attributes often have a fixed form, so this seems useful.
Fixes #18013.
> Handle attributes correctly in "Flip comma"

- crates/hir/src/lib.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/tests/item_list.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ted.rs
> feat(ide-completion): extra sugar auto-completion `async fn ...` in `impl trait` for `async fn in trait` that's defined in desugar form

- crates/hir-ty/src/consteval.rs
- crates/ide-assists/src/handlers/explicit_enum_discriminant.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Add assist for adding explicit discriminants to all variants of an enum.
Closes #17798.
> Add explicit enum discriminant assist

- Cargo.lock
- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/hir-def/src/macro_expansion_tests/mod.rs
- crates/hir-def/src/macro_expansion_tests/proc_macros.rs
- crates/hir-expand/src/lib.rs
- crates/hir/src/lib.rs
- crates/ide-db/src/lib.rs
- crates/ide/src/hover/tests.rs
- crates/mbe/Cargo.toml
- crates/mbe/src/lib.rs
- crates/mbe/src/tests.rs
- crates/syntax-bridge/src/insert_whitespace_into_node.rs
- crates/syntax-bridge/src/lib.rs
- crates/vfs/src/lib.rs
Most of our mbe hir-def tests don't actually do anything name res relevant, we can (and should) move those down the stack into `mbe/hir-expand`.
> internal: Lay basic ground work for standalone mbe tests

- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/wrap_return_type_in_result.rs
This commit makes the "Wrap return type in Result" assist prefer type aliases of standard library type when the are in scope, use at least one generic parameter, and have the name `Result`.
The last restriction was made in an attempt to avoid false assumptions about which type the user is referring to, but that might be overly strict. We could also do something like this, in order of priority:
* Use the alias named "Result".
* Use any alias if only a single one is in scope, otherwise:
* Use the standard library type.
This is easy to add if others feel differently that is appropriate, just let me know.
Fixes #17796
> fix: use Result type aliases in "Wrap return type in Result" assist

- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/introduce_named_generic.rs
- crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
- crates/ide-assists/src/utils.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/pattern.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/pattern.rs
- crates/ide-db/src/lib.rs
- crates/ide-db/src/syntax_helpers/suggest_name.rs
fix #17780
1. Refactor: move `ide_assist::utils::suggest_name` to `ide-db::syntax_helpers::suggest_name` for reuse.
2. When completing `IdentPat`, detecte if the current node is a `let_stmt` or `fn_param`, and suggesting a new name based on the context.
> feat: Suggest name in completion for let_stmt and fn_param

- crates/hir-def/src/data/adt.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/cast.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/tests.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir-ty/src/tests/simple.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-assists/src/handlers/inline_local_variable.rs
- crates/ide-diagnostics/src/handlers/invalid_cast.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide/src/inlay_hints/adjustment.rs
- crates/ide/src/syntax_highlighting/tests.rs
Fixes  #17897 and fixes #16564
Mainly adopted from https://github.com/rust-lang/rust/blob/100fde5246bf56f22fb5cc85374dd841296fce0e/compiler/rustc_hir_typeck/src/cast.rs
> feat: Implement cast typecheck and diagnostics

- Cargo.lock
- lib/lsp-server/Cargo.toml
- lib/lsp-server/src/stdio.rs
Should reduce the noise a bit (https://github.com/rust-lang/rust-analyzer/issues/18055). This removes the panic (and a follow up panic) when the server incorrectly shuts down, turning it into a proper late exit error.
> fix: Don't panic lsp writer thread on dropped receiver

- crates/syntax/src/lib.rs
- crates/syntax/src/syntax_editor.rs
- crates/syntax/src/syntax_editor/edit_algo.rs
- crates/syntax/src/syntax_editor/mapping.rs
Related to #15710
Implements a `SyntaxEditor` interface to abstract over the details of modifying syntax trees, to both simplify creating new code fixes and code actions, as well as start on the path of getting rid of mutable syntax nodes.
`SyntaxEditor` relies on `SyntaxMappingBuilder`s to feed in the correct information to map AST nodes created by `make` constructors, as `make` constructors do not guarantee that node identity is preserved. This is to paper over the fact that `make` constructors simply re-parse text input instead of building AST nodes from the ground up and re-using the provided syntax nodes.
`SyntaxAnnotation`s are used to find where syntax elements have ended up after edits are applied. This is primarily useful for the `add_{placeholder,tabstop}` set of methods on …
> internal: Add preliminary `SyntaxEditor` functionality

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin/fn_macro.rs
- crates/hir-expand/src/builtin/quote.rs
This is a small change, but it was the cause of 90% of the errors in `rust-analyzer diagnostics .` 🫢 (because this worked incorrectly with `stringify!()`, which means every `quote!()` (the original one) quoting a string also didn't work).
With this change and #18085 together, all remaining errors are type errors.
This may mean we can enable more errors, but this is out of scope for this PR.
> fix: Correctly escape strings in our quote macro

- crates/hir-ty/src/infer/cast.rs
- crates/hir-ty/src/infer/unify.rs
- crates/ide-diagnostics/src/handlers/invalid_cast.rs
It seems that chalk fails to solve some obvious goals when there are some recursiveness in trait environments.
And it doesn't support trait upcasting yet. rust-lang/chalk#796
This PR just skips for casting into types containing `dyn Trait` to prevent false positive diagnostics like #18047 and #18083
> Skip checks for cast to dyn traits

- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/unresolved_references.rs
Adds `rust-analyzer unresolved-references` which reports unresolved references. This is useful for debugging and regression testing for both rust-analyzer and project generators like Buck's rust-project.
As discussed: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Command.20to.20report.20unresolved.20references
> Add command to report unresolved references

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/config.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-completion/src/tests.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-completion/src/tests/raw_identifiers.rs
- crates/ide-completion/src/tests/special.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- docs/user/generated_config.adoc
- editors/code/package.json
But provide a config to suppress that.
I didn't check whether we are in statement expression position, because this is hard in completion (due to the natural incompleteness of source code when completion is invoked), and anyway using function returning unit as an argument to something seems... dubious.
Fixes #17263.
> feat: Automatically add semicolon when completing unit-returning functions

- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/inline_const_as_literal.rs
This PR fixes a small bug in the IDE assistence (`inline_const_as_literal`). When the being-inlined constant is a number and it is greater than or equal to 10, the assistence inserts unexpected string `(0x...)` after the number itself. A simple example is followed:
Current `inline_const_as_literal` changes
```rs
const A: usize = 16;
fn f() -> usize {
A  // inline the constant
}
```
into
```rs
const A: usize = 16;
fn f() -> usize {
16 (0x10)
}
```
The bug originates from #14925 & #15306 . #14925 added some unittests, but it just tested the number-inlining behavior when the number is `0`.
https://github.com/rust-lang/rust-analyzer/blob/50882fbfa204027c84753e6d51a1a12884dc1b19/crates/ide-assists/src/handlers/inline_const_as_literal.rs#L124-L138
And #15306 modified the behavior of …
> fix: Fix `inline_const_as_literal` error when the number >= 10

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/tests/slow-tests/ratoml.rs
- docs/dev/lsp-extensions.md
This PR makes some improvements on how we test configs that come from `rust-analyzer.toml` files.
It was primarily used to solve #18021 but along the way I could not really determine the cause of the said issue which makes me think that it may not be related to the changes that I made earlier to the ratoml infra. In either way `custom_snippets` are now made `global` because we still don't have a tree that maps a `SourceRootId` to a set of `Snippet`s.
> internal: Better testing infra for ratoml

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir/src/display.rs
- crates/ide/src/hover/tests.rs
Fix #17858 
This PR introduces an option to [hir-def/src/body/pretty.rs](https://github.com/rust-lang/rust-analyzer/blob/08c7bbc2dbe4dcc8968484f1a0e1e6fe7a1d4f6d/crates/hir-def/src/body/pretty.rs) to render the result as a single line, which is then reused for rendering patterns in parameters for hovering.
> feat: render patterns in params for hovering

- crates/rust-analyzer/src/handlers/dispatch.rs
- crates/rust-analyzer/src/main_loop.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18055, if a client sends us an unregistered document path in a did save notification it would force us to exit the thread. That is obviously not great behavior, we should be more fallible here
> fix: Faulty notifications should not bring down the server

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/introduce_named_generic.rs
- crates/ide-completion/src/completions/pattern.rs
- crates/ide-db/src/syntax_helpers/suggest_name.rs
- crates/syntax/src/lib.rs
fix #18034.
This PR includes the following enhancement:
- Introduced a `NameGenerator` in `suggest_name`, which implements an automatic renaming algorithm to avoid name conflicts. Here are a few examples:
```rust
let mut generator = NameGenerator::new();
assert_eq!(generator.suggest_name("a"), "a");
assert_eq!(generator.suggest_name("a"), "a1");
assert_eq!(generator.suggest_name("a"), "a2");
assert_eq!(generator.suggest_name("b"), "b");
assert_eq!(generator.suggest_name("b"), "b1");
assert_eq!(generator.suggest_name("b2"), "b2");
assert_eq!(generator.suggest_name("b"), "b3");
assert_eq!(generator.suggest_name("b"), "b4");
assert_eq!(generator.suggest_name("b3"), "b5");
```
- Updated existing testcases in ide-assists for the new `NameGenerator` (only modified generated names).
- Generate …
> feat: generate names for tuple-struct in add-missing-match-arms

- crates/hir-def/src/nameres.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir/src/semantics.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide-diagnostics/src/lib.rs
- crates/syntax/src/ast/traits.rs
The previous analysis was top-down, and worked on a single file (expanding macros). The new analysis is bottom-up, starting from the diagnostics and climbing up the syntax and module tree.
While this is more efficient (and in fact, efficiency was the motivating reason to work on this), unfortunately the code was already fast enough. But luckily, it also fixes a correctness problem: outline parent modules' attributes were not respected for the previous analysis. Case lints specifically did their own analysis to accommodate that, but it was limited to only them. The new analysis works on all kinds of lints, present and future.
It was basically impossible to fix the old analysis without rewriting it because navigating the module hierarchy must come bottom-up, and if we already have a …
> Use more correct handling of lint attributes

- crates/hir/src/lib.rs
- crates/ide/src/hover/tests.rs
> fix: Fix printing of constants greater than `i128::MAX`

- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/tests.rs
> feat: Implement `expr_2021`

- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide-diagnostics/src/lib.rs
Turns out it's pretty easy, but I did have to add support for allowed-by-default lints.
> feat: Add diagnostics for `unsafe_op_in_unsafe_fn`

- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
[Rust doesn't run the `non_snake_case_name` lint on `extern fn`s with the `#[no_mangle]` attribute](https://github.com/rust-lang/rust/pull/44966).
The conditions are:
- The function must be `extern` and have a `#[no_mangle]` attribute.
- The function's ABI must not be explicitly set to "Rust".
This PR replicates that logic here.
> Don't lint names of #[no_mangle] extern fns

- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide-diagnostics/src/lib.rs
Some lints should not be reported if they originate from an external macro, and quickfixes should be disabled (or they'll change library code).
Fixes #18122.
Closes #18124.
> fix: Handle errors and lints from external macros

- crates/hir-expand/src/builtin.rs
- crates/hir-expand/src/builtin/quote.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_issue_18089.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/test-fixture/src/lib.rs
Previously some expansions were not cached, but were cached in the expansion cache, which caused panics when later queries tried to lookup the node from the expansion cache.
Fixes #18089.
> fix: Always cache macro expansions' root node in Semantics

- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/tests/regression.rs
Fixes #18109
Whenever we create an inference variable in r-a, we extend `type_variable_table` to matching size here;
https://github.com/rust-lang/rust-analyzer/blob/f4aca78c92e03354327c8f6c7fefaef9f45ab166/crates/hir-ty/src/infer/unify.rs#L378-L381 
But sometimes, an inference variable is [created from chalk](https://github.com/rust-lang/chalk/blob/ab710e0c9b455403b138ef72a2fb90967a58eff3/chalk-solve/src/infer/unify.rs#L743) and passed to r-a as a type of an expression or a pattern.
If r-a set diverging flag to this before the table is extended to a sufficient size, it panics here;
https://github.com/rust-lang/rust-analyzer/blob/f4aca78c92e03354327c8f6c7fefaef9f45ab166/crates/hir-ty/src/infer/unify.rs#L275-L277
I think that extending table when setting diverging flag is reasonable becase …
> fix: Extend `type_variable_table` when modifying index is larger than the table size

- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/syntax/src/hacks.rs
This check is incorrect when we have comments and whitespace in the text.
We can strip comments, but then we still have whitespace, which we cannot strip without changing meaning for the parser. So instead I opt to remove the check, and wrap the expression in parentheses (asserting what produced is a parenthesized expression) to strengthen verification.
Fixes #18144.
> fix: Remove check that text of `parse_expr_from_str()` matches the produced parsed tree

- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/mbe/src/expander/matcher.rs
An expression starting with `r#const` etc. should be accepted even in edition <=2021.
Fixes #18148.
This was not fixed when testing with edition 2024, I wonder whether that means our check for edition is incorrect...
> fix: When checking for forbidden expr kind matches, account for rawness

- crates/hir-expand/src/cfg_process.rs
- crates/hir-expand/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide-diagnostics/src/lib.rs
I forgot `cfg_attr` while working on #18099. Although the original code also didn't handle that (although case lints specifically were correct, by virtue of using hir attrs).
> fix: Handle lint attributes that are under `#[cfg_attr]`

- Cargo.lock
- crates/hir-def/src/macro_expansion_tests/mbe/metavar_expr.rs
- crates/mbe/Cargo.toml
- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/parser.rs
- crates/tt/src/iter.rs
I didn't follow rustc precisely, because I think it does some things wrongly (or they are FIXME), but I only allowed more code, not less. So we're all fine.
Closes #18145.
> feat: Support the `${concat(...)}` metavariable expression

- crates/ide-completion/src/context.rs
- crates/ide-completion/src/render/function.rs
Completing it will break syntax.
Fixes #18130.
> fix: Don't complete `;` when in closure return expression

- .github/workflows/release.yaml
These are currently throwing `Error: HttpError: Resource not accessible by integration` because of the organization change, let's disable them for today's release.
> internal: Disable GitHub releases for now

- .github/workflows/release.yaml
Turns out, this wasn't needed for long.
> minor: Revert "internal: Disable GitHub releases for now"

- crates/ide-completion/src/context.rs
If a user ever sees the completion marker, it's confusing to see text about IntelliJ. Use a string that's more explicitly about completion for rust-analyzer.
> internal: Make COMPLETION_MARKER more explicitly r-a

- crates/rust-analyzer/src/handlers/notification.rs
> fix: fix ambigious package name in flycheck

- crates/rust-analyzer/src/cli/analysis_stats.rs
I noticed that this flag wasn't being respected by `analysis-stats` when profiling proc macro expansion, so here's a small fix.
> analysis-stats: respect `--disable-proc-macros` flag

- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/per_ns.rs
- crates/ide/src/goto_definition.rs
The import is flagged as "indeterminate", and previously it was re-resolved, but only at the end of name resolution, when it's already too late for anything that depends on it.
This issue was tried to fix in https://github.com/rust-lang/rust-analyzer/pull/2466, but it was not fixed fully.
That PR is also why IDE features did work: the import at the end was resolved correctly, so IDE features that re-resolved the macro path resolved it correctly.
I was concerned about the performance of this, but this doesn't seem to regress `analysis-stats .`, so I guess it's fine to land this. I have no idea about the incremental perf however and I don't know how to measure that, although when typing in `zbus` (including creating a new function, which should recompute the def map) completion was fast …
> fix: Fix name resolution when an import is resolved to some namespace and then later in the algorithm another namespace is added

- crates/ide-completion/src/completions/postfix.rs
> fix: Better support references in consuming postfix completions

- crates/ide/src/expand_macro.rs
- crates/span/src/map.rs
Because it took me hours to figure out that contrary to common sense, the offset stored is the *end* of the node, and we search by the *start*. Which is why we need a convoluted `partition_point()` instead of a simple `binary_search()`. And this was not documented at all. Which made me make mistakes with my implementation of `SpanMap::merge()`.
The other bug fixed about span map merging is correctly keeping track of the current offset in presence of multiple sibling macro invocations. Unrelated, but because of the previous issue it took me hours to debug, so I figured out I'll put them together for posterity.
Fixes #18163.
> fix: Fix a bug in span map merge, and add explanations of how span maps are stored

- crates/ide-assists/src/handlers/remove_unused_imports.rs
- crates/ide-db/src/search.rs
> fix: Temporary fix for `remove_unused_imports` not handling import aliases correctly

- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/run_tests.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/cli/ssr.rs
Without this, build scripts don't run for tests and as such any proc-macros in dev-deps fail to resolve
> fix: Pass all-targets for build scripts in more cli commands

- crates/rust-analyzer/src/discover.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/tracing/config.rs
With `"env RA_PROFILE=vfs_load|parallel_prime_caches|discover_command>500`, this results in the following output:
```
21888ms discover_command
11627ms vfs_load @ total = 701 
1503ms vfs_load @ total = 701 
30211ms parallel_prime_caches
```
As a followup, I'd like to make hprof emit the information above as JSON.
> internal: add tracing to project discovery and VFS loading

- Cargo.toml
rust-analyzer doesn't build on 1.80 because we use `#[expect(lint)]`:
```
error[E0658]: the `#[expect]` attribute is an experimental feature
--> crates/hir-expand/src/prettify_macro_expansion_.rs:11:1
|
11 | #[expect(deprecated)]
| ^^^^^^^^^^^^^^^^^^^^^
|
= note: see issue #54503 <https://github.com/rust-lang/rust/issues/54503> for more information
```
> Require rust 1.81

- crates/rust-analyzer/src/reload.rs
Previously, r-a would show an error if both fetch_workspaces_queue and discover_workspace_queue were empty. We're in this state at startup, so users would see an error if they'd configured
discover_workspace_config.
Instead, allow the fetch_workspaces_queue to have zero items if discover_workspace_config is set.
Whilst we're here, prefer "failed to fetch" over "failed to discover", so the error message better reflects what this function is doing.
> fix: Don't report a startup error when a discover command is configured

- crates/rust-analyzer/src/handlers/notification.rs
Require the existence of a target and `check_workspace` to be false to restart package-wide flycheck. Fixes #18194 , #18104
> minor: Stricter requirements for package wide flycheck

- crates/ide-assists/src/handlers/extract_variable.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/syntax_factory.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
- crates/syntax/src/syntax_editor.rs
- crates/syntax/src/syntax_editor/mapping.rs
Part of [#​15710](https://github.com/rust-lang/rust-analyzer/issues/15710)
Instead of requiring passing a `&mut SyntaxEditor` to every make constructor to generate mappings, we instead wrap that logic in `SyntaxFactory`, and afterwards add all the mappings to the `SyntaxEditor`.
Includes an example of using `SyntaxEditor` & `SyntaxFactory` in the `extract_variable` assist.
> internal: Add `SyntaxFactory` to ease generating nodes with syntax mappings

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/debug.ts
- editors/code/src/main.ts
Resolves #17901. It adds support for rebuilding after debugging a test was restarted. This means the test doesn't have to be aborted and manually re-ran again.
First, all the Visual Studio Code extensions are loaded into an Extension Host window. Then, a sample test like below was ran and restarted to see if it was correctly rebuild.
```rust
#[test]
fn test_x() {
assert_eq!("1.1.1", "1.1.0");
}
```
> Building before a debugging session was restarted

- Cargo.lock
This version of `cc` contains [a fix](https://github.com/rust-lang/cc-rs/releases/tag/cc-v1.1.22) to prevent spurious rebuilds. Hopefully this should help avoid the CI issues rustc has been having.
> Update cc to 1.1.22

- crates/load-cargo/src/lib.rs
- crates/project-model/src/workspace.rs
We subscribe to `textDocument/didSave` for `filesToWatch`, but the VFS doesn't contain those files. Before https://github.com/rust-lang/rust-analyzer/pull/18105, this would bring down the server. Now, it's only a benign error logged:
```
ERROR notification handler failed handler=textDocument/didSave error=file not found: /foo/bar/TARGETS
```
It's benign, because we will also receive a `workspace/didChangeWatchedFiles` for the file which will invalidate and load it.
Explicitly include the buildfiles in the VFS to prevent the handler from erroring.
> Include buildfiles in VFS

- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
Needed this argument in order to profile the proc macro expansion server (c.f., [this Zulip conversation](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/.60macro_rules!.60-based.20macros.20for.20derives.2Fattributes/near/473466794)). I also took the opportunity to change the phrasing for `--proc-macro-srv`.
Ran with `samply record ~/.cargo/bin/rust-analyzer analysis-stats --proc-macro-srv /Users/dbarsky/.cargo/bin/rust-analyzer-proc-macro-srv --parallel .` on rust-analyzer itself.
> internal: allow overriding proc macro server in analysis-stats

- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir-ty/src/diagnostics/decl_check/case_conv.rs
- crates/ide-db/src/imports/merge_imports.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
Fixed diagnostic messages so they say UpperCamelCase rather than CamelCase, as it is ambiguous.
Usually I'd call it PascalCase, but in the code base it is called UpperCamelCase so I left it with that naming choice.
`rustc` says `upper camel case` also when the case is wrong
```
warning: trait `testThing` should have an upper camel case name
--> src/main.rs:5:7
|
5 | trait testThing {
|       ^^^^^^^^^ help: convert the identifier to upper camel case: `TestThing`
|
= note: `#[warn(non_camel_case_types)]` on by default
```
This is in line with the UPPER_SNAKE_CASE diagnostic messages.
https://github.com/rust-lang/rust-analyzer/blob/546339a7be357b3e95fc4b79a8816dce540d477b/crates/hir-ty/src/diagnostics/decl_check.rs#L60
https://github.com/rust-lang/rust-analyzer/blob/546339a7be357b3e95fc4b79a …
> fix: Ambiguity with CamelCase diagnostic messages, align with rustc warnings

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/op_queue.rs
- crates/rust-analyzer/src/reload.rs
@Wilfred and I were talking about `OpQueue` and we identified one symptom of its (relative) weirdness is that `last_op_result` returns a `T::default()`; not `Option<&T>`, which means it's not possible to distinguish between "the `OpQueue` hasn't run yet" and "the OpQueue ran, but didn't produce a result". This branch fixes that.
> internal: remove `Default` from OpQueue

- crates/hir/src/lib.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/tracing/config.rs
- crates/rust-analyzer/src/tracing/hprof.rs
- crates/rust-analyzer/src/tracing/json.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
- docs/dev/README.md
On `buck2/integrations/rust-project`, this results in the following being printed:
```json
{"name":"discover_command","elapsed_ms":18703}
{"name":"parallel_prime_caches","elapsed_ms":0}
{"name":"vfs_load","elapsed_ms":5895}
{"name":"vfs_load","elapsed_ms":547}
{"name":"parallel_prime_caches","elapsed_ms":23}
{"name":"parallel_prime_caches","elapsed_ms":84}
{"name":"parallel_prime_caches","elapsed_ms":5819}
```
> internal: add json `tracing` Layer for profiling startup

- crates/hir-ty/src/mir/borrowck.rs
Because damnit, it can crash r-a. Why do people make this stupid DFSes anyway (I get it, it's easier until it blows).
Fixes #18223 (who thought DFS will be the problem).
> Use external stack in borrowck DFS

- .github/workflows/release.yaml
> internal: Use macos-13 runners and bump MACOSX_DEPLOYMENT_TARGET to 13.0

- crates/hir-expand/src/prettify_macro_expansion_.rs
- crates/ide/src/hover/tests.rs
> fix: Fix `prettify_macro_expansion()` when the node isn't the whole file

- crates/rust-analyzer/src/lsp/to_proto.rs
while looking at #18245 i noticed that `something_to_resolve` could technically flap between true -> false if some subsequent fields that were requested to be resolved were empty. 
this fixes that by using `|=` instead of `=` when assigning to `something_to_resolve` which will prevent it from going back to false once set. 
although some cases it's simply assigning to `true` i opted to continue to use `|=` there for uniformity sake. but happy to change those back to `=`'s. 
cc @SomeoneToIgnore
> lsp: fix completion_item something_to_resolve not being a latch to true

- crates/project-model/src/workspace.rs
The `build_file` path may be relative to the workspace root.
> Fix panic when json project has relative buildfile paths

- editors/code/src/bootstrap.ts
- editors/code/src/util.ts
- editors/code/tests/unit/bootstrap.test.ts
Extensions should not block the vscode extension host. Replace uses of `spawnSync` with `spawnAsync`, a convenience wrapper around `spawn`.
These `spawnSync`s are unlikely to cause a real issue in practice, because they spawn very short-lived processes, so we aren't blocking for very long. That said, blocking the extension host is poor practice, and if they _do_ block for too long for whatever reason, vscode becomes useless.
> Run subprocesses async in vscode extension

- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/parser/err/0055_impl_use.rast
- crates/parser/test_data/parser/err/0055_impl_use.rs
> Correctly parse `use` in generic parameters

- crates/ide/src/highlight_related.rs
Async blocks act similar to async functions in that the await keywords are related, but also act like functions where the exit points are related.
Fixes #18147
> feat: Highlight exit points of async blocks

- crates/hir-ty/src/infer/cast.rs
- crates/ide-diagnostics/src/handlers/invalid_cast.rs
Just like we don't check for types containing unknown.
Fixes #18214.
See also https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Another.20case.20of.20.2318064.3F.
> fix: Comment out cast checks for unknown ptr kind

- crates/rust-analyzer/src/handlers/request.rs
When providing a custom rustfmt command, join it with the project root instead of the workspace root. This fixes rust-analyzer getting the wrong invocation path in projects containing subprojects.
This makes the behaviour consistent with how a custom path provided in rust-analyzer.procMacro.server behaves already.
Resolves issue #18222
> fix: Join rustfmt overrideCommand with project root

- crates/base-db/src/input.rs
- crates/hir-def/src/data.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests.rs
- crates/ide/src/navigation_target.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
- crates/ide/src/syntax_highlighting/tests.rs
The fix point loop won't progress them given the potential extern crate candidates are set up at build time.
> internal: Don't resolve extern crates in import fix point resolution

- crates/hir-ty/src/infer/mutability.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
Fixes #15799
We are doing some heuristics for deciding whether the given deref is deref or deref_mut here;
https://github.com/rust-lang/rust-analyzer/blob/5982d9c420d0dc90739171829f0d2e9c80d98979/crates/hir-ty/src/infer/mutability.rs#L182-L200
But this heuristic is erroneous if we are dereferencing to a mut ptr and normally those cases are filtered out here as builtin;
https://github.com/rust-lang/rust-analyzer/blob/5982d9c420d0dc90739171829f0d2e9c80d98979/crates/hir-ty/src/mir/lower/as_place.rs#L165-L177
Howerver, this works not so well if the given dereferencing is double dereferencings like the case in the #15799.
```rust
struct WrapPtr(*mut u32);
impl core::ops::Deref for WrapPtr {
type Target = *mut u32;
fn deref(&self) -> &Self::Target {
&self.0
}
}
fn main() {
let mut x = 0u32;
let …
```
> fix: Do not consider mutable usage of deref to `*mut T` as deref_mut

- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/src/builtin/attr_macro.rs
Fixes #18274, although I don't fully understand if this is the best fix (it's not clear to me why this didn't cause issues before https://github.com/rust-lang/rust-analyzer/pull/18085).
> Skip #[test_case] expansion

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
Building atop of https://github.com/rust-lang/rust-analyzer/pull/18195, I switched `GlobalState::fetch_build_data_queue` to use a struct instead of a tuple.
(I didn't switch `fetch_proc_macros_queue` to not return a bool, as the return value is only used in one spot.)
> internal: switch remaining OpQueues to use named structs

- Cargo.toml
Since `ra-salsa`'s package name is actually `salsa` it makes the following warning in `cargo` commands; 
```
warning: profile package spec `ra-salsa` in profile `dev` did not match any packages
```
and the opt level isn't applied to it.
> minor: `ra-salsa` in `profile.dev.package`

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/cast.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/mutability.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/tests/never_type.rs
> Do not consider match/let/ref of place that evaluates to ! to diverge, disallow coercions from them too

- Cargo.lock
- Cargo.toml
- crates/rust-analyzer/src/tracing/config.rs
When debugging rust-analyzer and looking at logs, it's much easier to read when the timestamp is in the local timezone.
Before:
2024-08-28T20:55:38.792321Z  INFO ParseQuery: invoked at R18460
After:
2024-08-28T13:55:38.792321-07:00  INFO ParseQuery: invoked at R18460
> internal: Use local time when formatting logs

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
Follow up to https://github.com/sourcegraph/scip/issues/284
Manually verified that SCIP generation works OK for rust-analyzer itself.
cc @RalfJung
> Bump version of scip crate

- .github/workflows/ci.yaml
- crates/project-model/src/tests.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18326
> fix: Fix CI running analysis-stats incorrectly against the standard libraries

- lib/line-index/Cargo.toml
- lib/line-index/src/lib.rs
- lib/line-index/src/tests.rs
LSP says about Position::character
> If the character value is greater than the line length it defaults back to the line length.
but from_proto::offset() doesn't implement this.
A client might for example request code actions for a whole line by sending
Position::character=99999.  I don't think there is ever a reason (besides laziness) why the
client can't specify the line length instead but I guess we should not crash but follow protocol.
Not sure how to update Cargo.lock (lib/README.md doesn't say how).
Fixes #18240
> Clamp Position::character to line length

- editors/code/src/debug.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/18318. I also took the opportunity to refactor how `discoverSourceFileMap` worked—it now returns a type instead of mutating a map in place.
I tested this change using the LLDB DAP extension. I needed to set `"lldb-dap.executable-path": "/Applications/Xcode.app/Contents/Developer/usr/bin/lldb-dap"` for everything to work, however, but once I did, was able to successfully debug a test.
> internal: fix lldb-dap unconditionally calling rustc

- Cargo.toml
- crates/rust-analyzer/src/lsp/from_proto.rs
Completes https://github.com/rust-lang/rust-analyzer/pull/18243
I don't think I have permissions to target this on the other PR, so we'll need to rebase manually
> Clamp Position::character to line length 2/2

- .editorconfig
Had been testing Zed's editorconfig branch on r-a and noticed that something was odd with yaml files.
https://spec.editorconfig.org/#glob-expressions
> {s1,s2,s3}
> any of the strings given (separated by commas, can be nested) (But {s1} only matches {s1} literally.)
> internal: Fix editorconfig glob

- crates/hir-expand/src/db.rs
Due to the `TOKEN_LIMIT`, rust-analyzer failed to expand macro for `web-sys::WebGl2RenderingContext` https://github.com/rustwasm/wasm-bindgen/blob/main/crates/web-sys/src/features/gen_WebGl2RenderingContext.rs
After increasing the `TOKEN_LIMIT`, the `web-sys::WebGl2RenderingContext` can be expanded successfully:
> Fix: Increase TOKEN_LIMIT in hir-expand 

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/main.ts
See #18356
Add option to start rust-analyzer in "stopped" state when the extension activates.
> feat: support initializeStopped setting

- crates/hir-expand/src/builtin/fn_macro.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/references.rs
- crates/syntax/src/ptr.rs
Supercedes https://github.com/rust-lang/rust-analyzer/pull/18325
Fixes https://github.com/rust-lang/rust-analyzer/pull/18325
Fixes https://github.com/rust-lang/rust-analyzer/issues/18313
Fixes https://github.com/rust-lang/rust-analyzer/issues/18314
> fix: Fix token downmapping failing for include! inputs

- crates/ide-completion/src/completions/item_list.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/item_list.rs
This PR refactors `add_keywords` (making it much clearer!) and enhances completion for `extern` blocks.
It is recommended to reviewing the changes in order of the commits:
- The first commit (f3c4dde0a4917a2bac98605cc045eecfb4d69872) doesn’t change any logic but refactors parts of the `add_keywords` function and adds detailed comments.
- The second commit (5dcc1ab649bf8a49cadf006d620871b12f093a2f) improves completion for `extern` kw and extern blocks.
> feat: better completions for extern blcoks

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-db/src/defs.rs
- crates/ide-db/src/famous_defs.rs
- crates/ide/src/goto_definition.rs
> feat: goto definition on range operators

- crates/hir-def/src/lower.rs
- crates/hir-expand/src/hygiene.rs
- crates/hir-ty/src/autoderef.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/hir-ty/src/dyn_compatibility.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/borrowck.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/monomorphization.rs
- crates/hir-ty/src/mir/pretty.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/semantics.rs
- crates/parser/src/grammar/patterns.rs
- crates/proc-macro-api/src/msg/flat.rs
- crates/ra-salsa/src/derived/slot.rs
- crates/ra-salsa/src/derived_lru/slot.rs
- crates/ra-salsa/src/interned.rs
- crates/ra-salsa/src/lib.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/tracing/hprof.rs
- crates/tt/src/buffer.rs
- editors/code/src/ctx.ts
- xtask/src/codegen.rs
Closes https://github.com/rust-lang/rust-analyzer/pull/18323
> Fix status bar message not being marked markdown

- crates/hir-def/src/hir/type_ref.rs
- crates/hir-def/src/pretty.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/lower.rs
- crates/parser/src/grammar/generic_params.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/parser/test_data/parser/inline/ok/precise_capturing.rast
- crates/parser/test_data/parser/inline/ok/precise_capturing.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18357
> fix: Fix incorrect parsing of use bounds

- crates/ide-db/src/defs.rs
- crates/ide/src/hover/tests.rs
> feat: render docs from aliased type when type has no docs

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/goto_definition.rs
> feat: resolve range patterns to their structs 

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/body/tests.rs
- crates/hir-def/src/hir.rs
- crates/hir-def/src/test_db.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/mutability.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir-ty/src/tests/simple.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
- crates/ide-diagnostics/src/handlers/unresolved_ident.rs
- crates/syntax/src/ast/expr_ext.rs
By lowering it into patterns instead of expressions.
This is a large PR (phew!) but it also removes a lot of code, almost as much as it inserts. All present and probably even future code dedicated to handling destructuring assignments is thrown out of the window. Besides fixing a bunch of bugs, this also means that any future expansion is going to work much less to work with destructuring assignments, and is much more likely to not have bugs/rough edges/forgotten cases.
rustc goes even more than this and desugars destructuring assignment completely; coming to the HIR it vanishes. But we cannot do that, because this will severely affect our ability to map destructuring assignments up and down the lowering chain (for instance, consider what happens when a macro expands to the "pattern". …
> fix: Nail destructuring assignment once and for all

- Cargo.lock
- crates/hir-def/Cargo.toml
- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/expander.rs
- crates/hir-def/src/hir.rs
- crates/hir-def/src/resolver.rs
- crates/hir-expand/src/name.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/mutability.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir-ty/src/tests/simple.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-diagnostics/src/handlers/undeclared_label.rs
- crates/ide/src/goto_definition.rs
The realization that made me do this (as explained in detail in the first commit) is that while def-site hygiene is incredibly hard for us, mixed-site hygiene should be easy (well, I underestimated it due to the need of the second commit, but still). And the best part in that is that mixed-site hygiene rules: def-site hygiene is available only on nightly and without a clear path to stabilization, and even when (if) it will stabilize this will still help solving the case of variables/labels.
This brings diagnostics on self down to four (from five, I think? or more) 🎉 and the remaining diagnostics all require next solver (three due to coercion issue, one due to the issue of trait bounds not being preferred).
Best reviewed commit by commit.
Fixes #18262.
Fixes #16342.
Fixes #13758.
Fixes …
> fix: Implement mixed site hygiene

- crates/rust-analyzer/src/tracing/config.rs
The tracing_subscribe docs state that missing offsets likely mean that we're in a multithreaded context:
https://docs.rs/tracing-subscriber/latest/tracing_subscriber/fmt/time/struct.OffsetTime.html#method.local_rfc_3339
We're not in a multithreaded context at this point, but some platforms (e.g. OpenBSD) still don't have time offsets available.
Since this is only a rust-analyzer debugging convenience, just use system time logging in this situation.
Fixes #18384
> fix: Handle missing time offsets gracefully

- crates/rust-analyzer/src/lsp/capabilities.rs
The check for `labelDetailsSupport` only checks for non-`None`, which means setting `labelDetailsSupport: false` incorrectly treats it as being supported.
For context: https://github.com/mrcjkb/rustaceanvim/discussions/414
> Fix checking for `false` `labelDetailsSupport` value.

- crates/span/src/ast_id.rs
This _doesn't_ solve https://github.com/rust-lang/rust-analyzer/issues/18387, but should make the debugging the issue a lot easier.
> internal: log original syntax on panic

- crates/hir-def/src/item_tree.rs
cc https://github.com/rust-lang/rust-analyzer/issues/18387
> Swap query call order in `file_item_tree_query`

- crates/rust-analyzer/src/handlers/request.rs
Config can become very big, even for relatively small rust projects, and printing everything on one line makes reading the output in VS Code harder.
> internal: Pretty-print Config in status command

- crates/project-model/src/rustc_cfg.rs
Some types in `core` are conditionally compiled based on `target_has_atomic` or `target_has_atomic_load_store` without an argument, for example `AtomicU64`.
This is less noticeable in Cargo projects, where rust-analyzer adds the output of `RUSTC_BOOTSTRAP=1 cargo rustc --print cfg` so it gets the full set of cfg flags.
This fixes go-to-definition on `std::sync::atomic::AtomicU64` in non-cargo projects.
> fix: Add missing cfg flags for `core` crate

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests/globs.rs
- crates/hir-def/src/visibility.rs
Fixes #18308
The original issue is quite complicated.
`polar-rs` monorepo has the following structure;
```rust
// crate polars-core
pub mod prelude {
pub use crate::datatype::DataType;
}
// crate polars-ops
pub mod frame {
pub use join::*;
pub mod join {
pub use hash_join::*;
use polars_core::prelude::*;
mod hash_join {
pub use super::*;
}
}
}
```
1. The glob import `pub use super::*` inside `mod hash_join` reexports the visibility of the glob import `use polars_core::prelude::*` inside the `mod join` as "public", which was previously "module(join)"
2. The glob import `pub use hash_join::*` inside `mod join` overrides visibility of the previous visibility of the glob import `use polars_core::prelude::*` with "public" in 1., which was previously "module(join)"
The problematic step is 1., …
> fix: Prevent public re-export of private item

- crates/project-model/src/workspace.rs
The original message should never really occur and its not really informative to users, this should help a bit in figuring out what went wrong
> internal: Improve proc-macro error msg for failed build scripts

- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/handlers/dispatch.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/capabilities.rs
- crates/rust-analyzer/src/main_loop.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18375
> feat: Implement diagnostics pull model

- editors/code/.vscodeignore
- editors/code/package.json
- editors/code/walkthrough-setup-tips.md
This attempts to resolve https://github.com/rust-lang/rust-analyzer/issues/17788.
It looks like the description text of the "walkthrough" steps doesn't support Markdown code blocks, but you can provide a Markdown file that will be rendered on the right half of the page in place of the logo image. This file does support code blocks and syntax highlighting, and as an added bonus, the text can be selected/copied.
The final result looks like this:
Additionally, it looks like this renderer expects double backticks for inline code snippets, so I updated the descriptions of the other walkthrough steps accordingly.
> Fix formatting on welcome page, read only paths setting example

- crates/ide-assists/src/handlers/remove_dbg.rs
- crates/ide-assists/src/lib.rs
Closes #15364
See https://github.com/microsoft/vscode/issues/193355
> fix: Turn "Remove `dbg!`" into a quick fix for better prioritization

- crates/hir-def/src/macro_expansion_tests/mod.rs
- crates/hir-expand/src/lib.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/macro_error.rs
Split it into `macro-error`, `proc-macros-disabled` and `proc-macro-disabled`.
Closes #18414.
> feat: Split `macro-error` diagnostic so users can ignore only parts of it

- crates/hir-def/src/body/lower.rs
- crates/ide-assists/src/handlers/unmerge_match_arm.rs
- crates/parser/src/grammar/patterns.rs
- crates/parser/src/tests/top_entries.rs
- crates/parser/test_data/parser/inline/ok/match_arm.rast
- crates/parser/test_data/parser/inline/ok/slice_pat.rast
- crates/parser/test_data/parser/inline/ok/tuple_pat.rast
- crates/parser/test_data/parser/inline/ok/tuple_pat_fields.rast
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
Previously it was one level above, and that caused problems with macros that expand to it, because macros expect to get only one top-level node.
Fixes #18333.
> fix: Put leading `|` in patterns under `OrPat`

- Cargo.toml
- crates/hir-ty/src/consteval.rs
- crates/ide-completion/src/completions/mod_.rs
- crates/stdx/src/lib.rs
> Start using `Option::is_none_or`

- crates/ide/src/file_structure.rs
initially i had implemented a bunch more kinds, but eventually realized that `ide_db::SymbolKind` != `lsp_types::SymbolKind` and that many of the former kind are mapped to the same latter kind, which could cause annoyances when e.g. the user wants their outline view in vscode to show `ide_db::SymbolKind::Const` and `ide_db::SymbolKind::Static` but not `ide_db::SymbolKind::ConstParam` (which wouldn't be possible to configure in vscode since all of them are mapped to `lsp_types::SymbolKind::CONSTANT`) so i decided to take a conservative approach and ended up removing all but 1 kind
> Report document symbols of kind `variable` for let statements

- crates/hir-def/src/nameres/path_resolution.rs
- crates/ide-diagnostics/src/handlers/unresolved_macro_call.rs
I.e. the following situation:
```
fn foo() {
mod bar {
fn qux() {
// Prelude path here (e.g. macro use prelude or extern prelude).
}
}
}
```
Those were previously unresolved, because, in order to support `self` and `super` properly, since #15148 we do not ascend block paths when there is a module in between, but only crate def maps register preludes, not block def maps, and we can't change this because block def map prelude can always be overridden by another block. E.g.
```
fn foo() {
struct WithTheSameNameAsPreludeItem;
{
WithTheSameNameAsPreludeItem
}
}
```
Here `WithTheSameNameAsPreludeItem` refer to the item from the top block, but if we would register prelude items in each block the child block would overwrite it incorrectly.
Fixes #18411.
I don't like the approach I took with the …
> fix: Properly resolve prelude paths inside modules inside blocks

- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests.rs
MCVE:
```rust
//- /main.rs crate:main deps:test_crate
use test_crate::foo; // not resolving this!
use foo::Foo;
//- /lib.rs crate:test_crate deps:test_crate2
extern crate test_crate2;
pub use test_crate2 as foo;
//- /lib2.rs crate:test_crate2
pub struct Foo;
```
It seems that I should exempt min visibility for `extern crate`, as it seems to be exceptional in rustc 🤔
_Originally posted by @ShoyuVanilla in https://github.com/rust-lang/rust-analyzer/issues/18390#issuecomment-2438253336_
Should fix the regression made by #18390 
Thank you @lnicola for pointing out this regression 👍
> fix: Allow public re-export of `extern crate` import

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/expander.rs
- crates/hir-def/src/generics.rs
- crates/hir-def/src/hir/type_ref.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/lower.rs
- crates/hir-def/src/path.rs
- crates/hir-def/src/path/lower.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/lower.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
By removing interior mutability from it.
I tried to also cleanup `TyLoweringContext`, but it is much more cursed... I will continue to try.
> Cleanup TypeRef lowering

- crates/hir/src/lib.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/17096
> Do not render meta info when hovering usages

- crates/ide-assists/src/handlers/generate_fn_type_alias.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
closes #18343
Technically this doesn't support generating `for <...>` lifetimes, but I'm not very familiar with them, and they seem a bit outside of the scope of an assist like this. If somebody has a way to generate them feel free to add it. 
Also, when generating aliases with self parameters, they are left unnamed even in the `generate_fn_type_alias_named` assist. I think this behavior makes the most sense but you could also name them something like `this` and add a placeholder to change the name if that's desired.
> feat: Add assist to generate a type alias for a function

- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests/flyimport.rs
Close #17042 
Get the aliased name from `import_path` to use for import instead of name defined inside local module.
> fix: auto-complete import for aliased function and module

- docs/dev/setup.md
Created opinionated rust-analyzer workflow setup guide.
> docs: create setup documentation

- crates/parser/src/grammar.rs
- crates/parser/src/grammar/expressions.rs
- crates/parser/src/grammar/items.rs
- crates/parser/src/grammar/items/traits.rs
- crates/parser/test_data/generated/runner.rs
- crates/parser/test_data/parser/inline/ok/safe_outside_of_extern.rast
- crates/parser/test_data/parser/inline/ok/safe_outside_of_extern.rs
I don't like the party of `bool`s that is becoming, but two isn't worth a refactoring yet IMO.
Fixes #18445.
> fix: Only parse `safe` as contextual kw in extern blocks

- .github/workflows/autopublish.yaml
- crates/test-fixture/Cargo.toml
Currently it's possible to build rust-analyzer from the ra_ap crates, but not
possible to build their tests, as test-fixture isn't published.
If there isn't a particular reason to exclude this crate, I'd like to publish
it so that tests can be built and run from crates.io sources.
Context: I'm importing rust-analyzer code into a non-cargo build environment
(using Bazel). We'd prefer to import from crates.io for uniformity with other
libraries, and to build and run all tests to make sure we didn't break anything.
> Publish test-fixture => ra_ap_test_fixture

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lower.rs
This requires some serious code juggling.
Honestly I'm not sure this is worth it, it's just incredibly hard to fit inherited mutability into types that were not designed into it. This does have some nice advantages but some code becomes strictly worse. I'll leave that to the reviewer's opinion.
> Avoid interior mutability in `TyLoweringContext`

- triagebot.toml
Same as https://github.com/rust-lang/cargo/pull/14777
> The source repository must have an empty transfer table to enable transfers from that repository. Issues can be transferred to any repository in the rust-lang org.
CC @Urgau
> minor: Enable triagebot `transfer` feature

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/client.ts
It's been a year since we last bumped this (see #15904), and VS Code 1.83 is the first version that supports LSP 3.17.5 (via vscode-languageclient 9.0.1).
https://code.visualstudio.com/updates/v1_83#_language-server-protocol
(@davidbarsky and I work together, so I'm sure he'll be happy with this version bump too.)
> editors/code: Change minimum VS Code from 1.78 to 1.83

- editors/code/package.json
In PR #18265 and other we add more supported debug engine, but in VS Code's settings interface only CodeLLDB and MS C++ tools are shown available choices. This tiny PR updates the config to reflect it.
> editors/code: Update supported debug engines in config

- docs/dev/README.md
#7445 added an item to `docs/dev/README.md` describing and linking to the "Design" issue label, which I assume existed at the time. Later, #12722 updated that URL to point to the new repo location. However, this bullet point is now confusing for two reasons:
1. The URL https://github.com/rust-lang/rust-analyzer/issues?q=is%3Aopen+is%3Aissue+label%Design is malformed. Clicking it in Firefox produces a blank page. Interestingly, clicking the URL while editing this Markdown file inside VS Code changes it to the different URL https://github.com/rust-lang/rust-analyzer/issues?q=is:open+is:issue+label%25Design which is no longer malformed, but that just corresponds to the search string "is:open is:issue label%Design" which is not very meaningful.
2. There are currently no issues labeled …
> Replace Design label with C-Architecture

- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/lib.rs
Hi @Veykril,
I need to access a trait's supertraits (as external user of `ra_ap`'s APIs) and while `hir_ty::all_super_traits()` already provides such capabilities to a limited degree I'd like to propose the following accessors on `hir::Trait` itself, it only does provide access to the entire trait hierarchy (while I only want the direct supertraits) and requires a descent into `hir_ty` land. I'd thus like to propose adding the following methods: `hir::Trait::direct_supertraits(db)` & `hir::Trait::all_supertraits(db)`.
---
There seems to be some naming inconsistency with regard to `supertrait` (43 occurrences) vs. `super_trait` (53 occurrences) in the codebase. (I'd be happy to open a follow-up PR unifying the project-wide naming, if so desired.)
I went with `supertraits` in this PR since …
> internal: Add public `direct_supertraits(…)` & `all_supertraits(…)` accessor methods to `hir::Trait`

- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- docs/dev/lsp-extensions.md
Part of https://github.com/rust-lang/rust-analyzer/issues/18363
Closes https://github.com/rust-lang/rust-analyzer/pull/18501
Previously, completions for resolution were re-queried with the same completion parameters, and then picked by matching their properties as
```rs
let Some(mut resolved_completion) = resolved_completions.into_iter().find(|completion| {
completion.label == original_completion.label
&& completion.kind == original_completion.kind
&& completion.deprecated == original_completion.deprecated
&& completion.preselect == original_completion.preselect
&& completion.sort_text == original_completion.sort_text
}) else {
return Ok(original_completion);
};
```
this is incorrect, as 
1. `completion.deprecated == original_completion.deprecated` check may never success due to the …
> Use completion item indices instead of property matching when searching for the completion item to resolve

- crates/ide-assists/src/handlers/reorder_fields.rs
This PR is part of https://github.com/rust-lang/rust-analyzer/issues/15710 and https://github.com/rust-lang/rust-analyzer/issues/18285
> Migrate `reorder_fields` Assist to Use `SyntaxFactory`

- crates/rust-analyzer/src/handlers/request.rs
They were converted to LSP position using the current file's line index, which is obviously wrong.
I'm not sure how to test this since that require an entire operating r-a, since the functionality is in the rust-analyzer crate. I verified manually that this works.
The problem was introduced in #18404. Oopsie :)
Fixes #18513.
> fix: Fix related documents diagnostics

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
- crates/ide-assists/src/tests/generated.rs
When generating missing match arms, we currently use `todo!()`s for the match arm bodies. This is fine, but given they're obviously meant to be replaced, I figure they should also be snippet placeholders.
> feat: Use snippet placeholders for generated match arms

- docs/dev/architecture.md
The path to the request handler file is currently `crates/rust-analyzer/src/handlers/request.rs`. Updated `docs/dev/architecture.md` to reflect that.
> Update file path for request.rs entry point in architecture.md

- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/tests/traits.rs
Fixes #18556.
**Warning to the reviewer:** If you are going to open this in your editor of choice (with r-a of course), r-a will restart again and again, because we provide (some) IDE functionality to our tests which implies this actually overflows the stack when the test is present... Ask me how I know.
> fix: Fix a stack overflow when computing the sizedness of a struct that includes itself as the tail field

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
#17795 removed this option, turning it on for everyone. This commit adds it back, still on by default.
At work, users are effectively offline, so the initial `cargo metadata` will always fail. The `--no-deps` retry will succeed, but the experience with this path is very poor, because a ton of std stuff fails to resolve (some still works, I can't tell the pattern). Something like this is probably happening in #17759.
We want this config option so we can turn it off by default for our users and always use the stitched sysroot library.
> Re-add `rust-analyzer.cargo.sysrootQueryMetadata`

- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/lib.rs
Remove a redundant associated type bound from the return type of `TypeFolder::as_dyn` in some impls. This associated type is already constrained by the definition of `trait TypeFolder`:
```
pub trait TypeFolder<I: Interner>: FallibleTypeFolder<I, Error = Infallible> { ... }
```
And so specifying it is unnecessary. 
Removing this bound may also be necessary to avoid unintended breakage while fixing https://github.com/rust-lang/rust/issues/133361, though this usage **is not unsound**, it's just hard to support while also fixing the underlying issue.
> Remove redundant associated type bounds from `dyn TypeFolder`

- crates/hir-def/src/macro_expansion_tests/mbe/matching.rs
Adds a test covering #17785. Should close that issue.
This seemed like the right location for the test.
The test correctly fails on release 2024-07-15, with:
~~~
---- macro_expansion_tests::mbe::matching::meta_variable_raw_name_equals_non_raw stdout ----
thread 'macro_expansion_tests::mbe::matching::meta_variable_raw_name_equals_non_raw' panicked at crates/hir-def/src/macro_expansion_tests/mbe/matching.rs:190:5:
parse errors in expansion:
[
SyntaxError(
"expected expression, item or let statement",
0..0,
),
]
```
$name
```
~~~
> Add macro expansion test for raw variable names

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/ctx.ts
The status bar can become a bit crowded with many extensions adding status bar items. rust-analyzer can be a good citizen and hide itself unless the user is looking at relevant files.
I've set the default to show on Rust files and Cargo.toml. It could be reasonable to instead keep the current always-show behavior as the default, just giving users the option to configure it. I'm open to discussion!
This could also be a workaround for #15068.
> vscode: Only show status bar item in relevant files

- crates/hir-def/src/lower.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/add_missing_impl_members.rs
Fixes #17321. Fixes #15634.
I don't think this is the same cause as #18387 (I'll try to work on it, no promises), but just in case: CC @compiler-errors.
> fix: Fix a bug when synthetic AST node were searched in the AST ID map and caused panics

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/tests.rs
Fixes #18488 (which was more severe than just wrong highlighting, the variable wasn't bound).
> fix: Fix shadowing of record enum variant in patterns

- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests/globs.rs
Polars yet again reveals issues with our nameres process due to its complex modules structure (and the cursedness of nameres).
When a glob import overriding the visibility of a previous glob import was not properly resolved when the items are only available in the next fixpoint iteration.
The bug was hidden until #18390.
And thanks to @usamoi for minimizing the bug.
Fixes #18580.
> fix: Fixed another bug with glob imports

- crates/ide/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This PR addresses #16084 by adding a new configuration option: `rust-analyzer.typing.excludeChars`.
cc: @darichey 
- Added `rust-analyzer.typing.excludeChars` configuration.
- Defaults to `None`, meaning all trigger characters (`.=<>{(`) are active by default.
- Users can specify a string of characters to exclude from triggering assists.
- Updated documentation and configuration schema to reflect this new option.
> Add Configurable Option to Exclude Trigger Characters for Typing Assists

- crates/hir/src/semantics.rs
- crates/ide-completion/src/completions/attribute.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/attribute.rs
Only their names, anything can go inside.
Closes #18588.
This only completes when you type the first letter, I don't know why...
> feat: Complete derive helper attributes

- crates/hir-def/src/body.rs
- crates/hir-ty/src/diagnostics.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
We add union fields access (in both expressions and patterns) and inline assembly.
That completes the unsafe check (there are some other unsafe things but they are unstable), and so also opens the door to reporting unused unsafe without annoying people about their not-unused unsafe blocks.
> feat: Extend reported unsafe operations

- crates/hir-expand/src/lib.rs
- crates/ide-diagnostics/src/lib.rs
Because I got angry on the yellow squiggly lines below `query_group`, and decided to investigate it once and for all.
> fix: Do not report warnings from proc macros, ever

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This got accidentally re-enabled even though its still bugged
> fix: Disable `<` typing handler again

- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/item_tree/tests.rs
- crates/hir-ty/src/tests/traits.rs
- crates/hir/src/semantics.rs
- crates/ide-completion/src/completions/lifetime.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-db/src/defs.rs
- crates/intern/src/symbol/symbols.rs
- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/parser/inline/ok/lifetime_param.rast
- crates/parser/test_data/parser/inline/ok/precise_capturing.rast
- crates/parser/test_data/parser/ok/0018_struct_type_params.rast
- crates/parser/test_data/parser/ok/0020_type_param_bounds.rast
This mainly aids in error recovery but also makes it a bit easier to handle lifetime resolution. While doing so it also came apparent that we were not actually lowering lifetime outlives relationships within lifetime parameter declaration bounds, so this fixes that.
> fix: Parse lifetime bounds in lifetime param into TypeBoundList

- crates/ide-assists/src/handlers/introduce_named_generic.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
- crates/syntax/src/syntax_editor.rs
- crates/syntax/src/syntax_editor/edits.rs
This PR is part of #15710 and #18285.
**Changes Made**
- Followed the steps in #18285 for migration.
- Added a new `SyntaxFactory` method, `type_param`.
- Replaced `add_generic_param` (originally in `GenericParamList`) with a new method, `syntax_editor_add_generic_param`. This new method is similar but takes a `SyntaxEditor` instance instead of `ted` to avoid the “immutable tree” error.
> Migrate `introduce_named_generic` Assist to Use `SyntaxFactory`

- crates/ide-assists/src/handlers/sort_items.rs
part of #15710 and #18285
For this one, I had to pass `AssistContext` to other methods as well in order to get the file ID.
> Migrate `sort_items` Assist to Use `SyntaxFactory`

- crates/ide/src/typing.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
- editors/code/src/client.ts
Also re-enables the `<` closing handler, getting rid of the snippet edit that was never properly implemetned (and in fact cannot be implemented in VScode)
> Make bracket typing handler work on more things

- crates/rust-analyzer/src/handlers/notification.rs
Our first attempt to make flycheck only check the current crate if the crate is one of bin/bench/test targets had caused `check_workspace` to be ignored, which should have been a config with higher precedence all along. This commit reverts #18197 and closes #18562 and closes #18506
> minor: run `FlycheckHandle::restart_workspace` when `check_workspace` true 

- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/lsp/capabilities.rs
cc https://github.com/rust-lang/rust-analyzer/issues/18547#issuecomment-2523527080
> fix: Temporarily disable completion resolve support for helix and neovim

- crates/ide-assists/src/handlers/flip_binexpr.rs
- crates/ide-assists/src/handlers/flip_comma.rs
- crates/ide-assists/src/handlers/flip_trait_bound.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
- crates/syntax/src/syntax_editor.rs
- crates/syntax/src/syntax_editor/edit_algo.rs
Token tree handling is a bit annoying but I don't think there's anything you can do about it, that's just the nature of raw token trees.
> minor: Migrate `flip_*` assists to `SyntaxEditor`

- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/tests/coercion.rs
That's because they can be the same function but still different substs, which mandates them to coerce to fn pointers in order to unify.
Fixes #18626.
> fix: Coerce two `FnDef`s to fn pointers even if they are the same, if they are subtypes

- crates/ide-assists/src/handlers/flip_binexpr.rs
- crates/ide-assists/src/handlers/flip_comma.rs
- crates/ide-assists/src/handlers/flip_trait_bound.rs
- crates/ide-assists/src/handlers/reorder_fields.rs
- crates/ide-assists/src/handlers/reorder_impl_items.rs
- crates/ide-assists/src/handlers/sort_items.rs
- crates/syntax/src/syntax_editor/edit_algo.rs
closes #18525
Obviously there are lots of in-progress PRs right now which need updating as a result of this
> fix: Map new replacement nodes to their mutable equivalents in `SyntaxEditor`

- crates/hir-def/src/nameres/tests/incremental.rs
That is, fix the helper function and disable the tests for now.
> minor: Fix a test that didn't test what it should

- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/slow-tests/ratoml.rs
- crates/rust-analyzer/tests/slow-tests/support.rs
Closes https://github.com/rust-lang/rust-analyzer/pull/18070
> internal: Do not cache the config directory path

- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/hir-ty/src/inhabitedness.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
cc https://github.com/rust-lang/rust/pull/128934
> fix: Non-exhaustive structs may be empty

- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/extract_function.rs
fix #18639.
Sort locals by `binding_id` (i.e., in the order of definitions).
This PR also fixes the order of parameters in unit tests.
> feat: preserve order of parameters in extract_functions

- crates/ide-diagnostics/src/handlers/type_mismatch.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
closes #18383 
I also reorganized some of the tests for the fix to add a missing `Ok()` or `Some()` wrapper as they were somewhat scattered. The diff for this ended up looking messy but it's just moving functions around.
> feat: Add diagnostic fix to remove unnecessary wrapper in type mismatch

- Cargo.lock
- crates/ide-completion/src/item.rs
- crates/ide-completion/src/lib.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp/capabilities.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- docs/dev/lsp-extensions.md
Closes https://github.com/rust-lang/rust-analyzer/issues/18547
Closes https://github.com/rust-lang/rust-analyzer/issues/18640
Follows https://github.com/rust-lang/rust-analyzer/issues/18547#issuecomment-2525373488 proposal and adds completion items hashing, using all their data possible, that does not change between the edits.
> Hash completion items to properly match them during /resolve

- crates/load-cargo/src/lib.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/manifest_path.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
This in part caused us to not load workspace level rust-analyzer.toml files
> fix: Fix sourceroot construction for virtual manifests

- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/promote_local_to_const.rs
- crates/ide-assists/src/tests.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
closes #7692
Technically, this will permit some invalid const definitions since, as far as I know, we don't have the ability to properly ensure that an expression can be const evaluated, but I believe that would require a larger overhaul of RA's integration of MIR stuff. Either way, this should be fine for now and does a good job rejecting most of the obviously incorrect definitions. 
I could also group these assists if that's desirable, just let me know.
> feat: Add an assist to extract an expression into a constant

- crates/proc-macro-api/src/msg/flat.rs
- crates/proc-macro-api/src/process.rs
That is toolchains older than ~20 months from today on where this version was released. Reason is to simplify the codebase, and we likely don't even support version that old due to other reasons anymore either
> internal: Drop proc-macro server support for ~1.66.0 and older toolchains

- crates/hir-ty/src/display.rs
- crates/ide/src/hover/tests.rs
So, basically functions cannot have default params, but they can if they are something like
```rust
struct Foo<T = i32>(T);
let foo = Foo; // foo is fn<T = i32>(t: T) -> Foo<T>
```
I was puzzled to those things and fixed the previous issue in a wrong way, so it has been panicking for "normal" functions without default parameters for themselves, but for their parents 😅 
Fixes #18664
> fix: Panic when displaying generic params with defaults, again

- crates/proc-macro-srv-cli/src/main.rs
It feels a bit silly to require this at this point
> internal: Do not require a special env var to be set for the proc-macro-srv

- editors/code/src/client.ts
> fix: Revert changes to client capabilities in `bac0ed5`

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/lower/asm.rs
- crates/hir-def/src/hir/format_args.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/semantics.rs
- crates/ide-diagnostics/src/handlers/unresolved_ident.rs
And also a bit of cleanup by storing the capture's span with the open quote included.
> feat: Report unresolved idents for implicit captures in `format_args!()`

- crates/ide-assists/src/assist_context.rs
- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-db/src/syntax_helpers/suggest_name.rs
Use `ide_db::syntax_helpers::suggest_name` to suggest names in `destructure_tuple_binding`. If `NameGenerator` fails to generate new names, it will default to `_{idx}`.
> minor: improve name suggestion for destructure_tuple_binding

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide-assists/src/handlers/qualify_method_call.rs
- crates/ide-assists/src/handlers/qualify_path.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/handlers/wrap_return_type.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/items_locator.rs
Prior to this commit we used to generate import paths, then zipped them with the existing qualifier to check if they agree on the path to import. This is brittle when re-exports come into play causing items to have multiple applicable paths that refer to them. This commit instead rewrites this logic by generating the import path for the qualifier, verifying that the rest of the qualifier resolves and then doing a final lookup on that resolution result for the final segment instead.
Fixes https://github.com/rust-lang/rust-analyzer/issues/18689
> fix: Fix path qualified auto-importing completions not working with re-exports

- crates/ide-diagnostics/src/handlers/unresolved_field.rs
I found it easiest to fix in the quickfix code, and not deeper (e.g. body lowering).
Fixes #18683.
> fix: Fix a panic with a diagnostics fix when a keyword is used as a field

- crates/hir-def/src/body/pretty.rs
- crates/hir-def/src/body/tests.rs
> fix: Fix pretty-printing of `@` patterns

- Cargo.lock
- crates/load-cargo/src/lib.rs
- crates/proc-macro-api/Cargo.toml
- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-srv/Cargo.toml
- crates/span/Cargo.toml
- crates/span/src/hygiene.rs
- crates/span/src/lib.rs
- crates/syntax-bridge/Cargo.toml
It should never attempt to use salsa anyways and it only depends on it due spans requiring the ID
> Remove salsa from proc-macro server dep tree

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/item.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-completion/src/tests/fn_param.rs
- crates/ide-completion/src/tests/item.rs
- crates/ide-completion/src/tests/item_list.rs
- crates/ide-completion/src/tests/pattern.rs
- crates/ide-completion/src/tests/predicate.rs
- crates/ide-completion/src/tests/proc_macros.rs
- crates/ide-completion/src/tests/record.rs
- crates/ide-completion/src/tests/special.rs
- crates/ide-completion/src/tests/type_pos.rs
- crates/ide-completion/src/tests/use_tree.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
Lots of test output changes as I had to adjust things for test rendering. The actual changes are in https://github.com/rust-lang/rust-analyzer/pull/18713/files#diff-1f818ad963401fe13a8a29e158447fa51390f3026ecba9de2e38a1cbdcaf9f4c and the rust-analyzer crate
> internal: Cleanup label structure of `CompletionItem`

- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/nameres/tests/incremental.rs
- crates/hir-def/src/per_ns.rs
- crates/hir-def/src/resolver.rs
The reason I did this is because I plan to add another field to this struct (indicating whether the item was cfg'ed out), but it seems worthy even separately and removes a bunch of one-letter variable names and tuple-indexing. It is also easy to separate from future changes, so it will be easier to review this way.
> minor: Use a record struct instead of a tuple for each namespace in `PerNs`

- Cargo.lock
- Cargo.toml
- crates/paths/Cargo.toml
- crates/proc-macro-api/Cargo.toml
- crates/proc-macro-api/src/msg.rs
- crates/proc-macro-api/src/msg/flat.rs
- crates/project-model/Cargo.toml
- crates/project-model/src/build_dependencies.rs
- crates/project-model/src/cargo_workspace.rs
- crates/ra-salsa/Cargo.toml
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/test_runner.rs
- crates/rust-analyzer/src/tracing/json.rs
- crates/span/src/lib.rs
- lib/lsp-server/Cargo.toml
- lib/lsp-server/src/msg.rs
- lib/lsp-server/src/req_queue.rs
- xtask/Cargo.toml
Ideally we'd not have any dependency pull in the derive feature for faster build times, once that is the case this change would have an actual effect. See https://github.com/matklad/macro-dep-test/blob/master/README.md for context.
> internal: Split `serde` derive feature into `serde_derive` usage

- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/main_loop.rs
Closes https://github.com/rust-lang/rust-analyzer/pull/18332
> Clear flycheck diagnostics more granularly

- crates/proc-macro-api/src/msg/flat.rs
- crates/proc-macro-api/src/process.rs
Reverts rust-lang/rust-analyzer#18670
Reverting for now as this did not go as far back as I initially anticipated, see https://github.com/rust-lang/rust-analyzer/issues/18705#issuecomment-2557404602
> Revert "internal: Drop proc-macro server support for ~1.66.0 and older toolchains"

- crates/ide/src/runnables.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
> fix: remove `always!` check for file_id in `runnables`

- crates/hir-ty/src/chalk_db.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/flycheck.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/17300
> fix: Fix empty check diagnostics not marking files as changed

- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
For Windows, this removes the need to add a breakpoint and modify a value to exit the debugger wait loop.
As a ride along, this adds a 100ms sleep for all platforms so that waiting for the debugger doesn't hog the CPU thread.
> minor: Break out of waiting for debugger on Windows using native debugger check API.

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/ctx.ts
Closes #18665.
`rust-analyzer.statusBar.showStatusBar` can be `"always"`, `"never"` or `{ "documentSelector": <DocumentSelector>[] }`.
I added `DocumentSelector.notebookType` and `.scheme` as possible properties. The array is passed directly to `vscode.languages.match(documentSelector, editor.document)`, so the properties should Just Work.
Manually  testing, `"always"`, `"never"`, and `{ "documentSelector": ... }` seemed to work correctly.
I think the renamed setting is clearer, but it will break previous `statusBar.documentSelector` configs.
> Rename `rust-analyzer.statusBar.documentSelector` to `showStatusBar`, add "always" and "never" options.

- crates/syntax/src/ast/syntax_factory/constructors.rs
In my PR for migrating wrap/unwrap return type, [I remarked about two different ways of taking many elements as a parameter](https://github.com/rust-lang/rust-analyzer/pull/18524#issuecomment-2523440023), and it seemed like a matter of style at the time, but it turns out it actually matters a lot! Because if you provide a parameter taking `IntoIterator + Clone` using something a `.map()`, in which you construct additional elements using the same `SyntaxFactory` you're providing the parameter to, then by the lazy nature of iterators, there will be a looming mutable borrow on the `RefCell` for `mappings`, and the code will panic. So we need to be `collect`ing the iterator to force any internal references be dropped.
> internal: Standardize how we take iterator parameters in `SyntaxFactory`

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-assists/src/handlers/add_turbo_fish.rs
- crates/ide-assists/src/handlers/convert_match_to_let_else.rs
- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
- crates/ide-assists/src/handlers/expand_glob_import.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/extract_module.rs
- crates/ide-assists/src/handlers/generate_constant.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-db/src/defs.rs
- crates/ide-db/src/search.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_declaration.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/ide/src/rename.rs
- crates/ide/src/static_index.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
There are few things to note in the implementation:
First, this is a best-effort implementation. Mainly, type aliases may not be shown (due to their eager nature it's harder) and partial pathes (aka. hovering over `Struct` in `Struct::method`) are not supported at all.
Second, we only need to show substitutions in expression and pattern position, because in type position all generic arguments always have to be written explicitly.
Closes #18688.
I chose a different approach than outlined in that issue. Instead of substituting the generic arguments inline, I display them separately. This is for two reasons: first, it is harder to inline them. Second, inlining them is a lossy process. For example, it makes where bounds less decipherable, and also it will mean we'll have to switch to show the …
> feat: Show substitution where hovering over generic things

- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/path.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/diagnostics.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower/diagnostics.rs
- crates/hir/src/diagnostics.rs
- crates/ide-diagnostics/src/handlers/generic_args_prohibited.rs
Because it was a mess.
Previously, pretty much you had to handle all path diagnostics manually: remember to check for them and handle them. Now, we wrap the resolver in `TyLoweringContext` and ensure proper error reporting.
This means that you don't have to worry about them: most of the things are handled automatically, and things that cannot will create a compile-time error (forcing you top `drop(ty_lowering_context);`) if forgotten, instead of silently dropping the diagnostics.
The real place for error reporting is in the hir-def resolver, because there are other things resolving, both in hir-ty and in hir-def, and they all need to ensure proper diagnostics. But this is a good start, and future compatible.
This PR also ensures proper path diagnostics for value/pattern paths, which is …
> feat: Unify handling of path diagnostics in hir-ty

- crates/proc-macro-srv/src/lib.rs
- crates/ra-salsa/src/lib.rs
- crates/rust-analyzer/src/handlers/dispatch.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
cc https://github.com/rust-lang/rust-analyzer/issues/18745
> internal: Workaround salsa cycles leaking

- crates/ra-salsa/src/lib.rs
- crates/rust-analyzer/src/handlers/dispatch.rs
The caller doesn't really care about the contents of the error; it only cares whether the error is _present_.
I also made `ra_salsa::Cancelled`'s variants `#[non_exhaustive]` again.
> internal: wrap `salsa::Cycle`

- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/lower.rs
- crates/ide-diagnostics/src/handlers/generic_args_prohibited.rs
> fix: Consider `Enum::Variant` even when it comes from a different crate

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/generics.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/lang_items.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests.rs
- crates/hir-ty/src/tests/closure_captures.rs
- crates/hir-ty/src/tests/incremental.rs
- crates/hir-ty/src/variance.rs
- crates/hir/src/lib.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ra-salsa/ra-salsa-macros/src/query_group.rs
- crates/ra-salsa/src/derived/slot.rs
- crates/ra-salsa/src/derived_lru/slot.rs
- crates/ra-salsa/src/input.rs
- crates/ra-salsa/src/lib.rs
- crates/ra-salsa/src/lru.rs
- crates/ra-salsa/src/runtime.rs
- crates/ra-salsa/src/runtime/local_state.rs
This lacks any support for impl trait in type aliases (assoc or free) and functions are not fully supported as we lack lifetime elision. RPITs should also be supported here, but we don't count them as `GenericDefId` yet so.
The inference does not work perfectly unfortunately as it may run into query cycles which we would need to resolve via fixpoint iteration which current salsa does not support (see module doc). Likewise, Const expressions can affect whether a parameter turns invariant which we also lack sometimes.
> Implement parameter variance inference

- crates/ide-assists/src/handlers/destructure_tuple_binding.rs
- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/replace_is_method_with_if_let_method.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-db/src/syntax_helpers/suggest_name.rs
fix #18786.
This PR:
- Move the `for_variable` into the `NameGenerator` and change return types from `String` to `SmolStr`
- Introduces a new method `NameGenerator::new_from_scope_locals`, which is initialized with names of local variables from the current semantics scope, and refactor the following assists:
- `destructure_tuple_binding`
- `extract_variable`
- `replace_is_method_with_if_let_method`
> fix: avoid generating colliding names in extract_variable

- crates/hir/src/semantics.rs
Noticed thanks to hover when browsing in the repo.
> minor: Remove unneeded conversions

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
> Fix bug of "fill match arm" action in tokio::main macro

- Cargo.toml
- crates/ide-assists/src/handlers/generate_fn_type_alias.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/make/quote.rs
- xtask/src/codegen/grammar.rs
And port a few makers.
Fixes #18780, but I suspect there are many more like it lurking, and the work won't finish until we port them all.
I'm not completely satisfied with this (due to the ease of making a mistake in the AST structure, and slightly less but also because of the need to remember whitespaces), but this is already enough to see how this will look like. So I sent a PR to see how people will respond.
Can be reviewed commit by commit.
> internal: Create a quoting mechanism instead of textual AST make

- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
Fixes #18765.
Chose this approach to simplify finding the needed n back ticks, instead of finding the consecutive back ticks. 
Tested for about 100 consecutive back ticks, it was working fine. 
Regarding tests, I'll add some soon. Just wanted to review the implementation.
> Fix render of literal to be rendered in codeblock

- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
> feat: show go-to-type-def actions for subst when hovering

- crates/hir-ty/src/display.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/lib.rs
- crates/ide/src/moniker.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/cli/scip.rs
In particular, the symbol generation before this change creates a lot of symbols with the same name for different definitions. This change makes progress on symbol uniqueness, but does not fix a couple cases where it was unclear to me how to fix (see TODOs in `scip.rs`)
Before this change `SymbolInformation` provided by a document was the
info for all encountered symbols that have not yet been emitted. So,
the symbol information on a `Document` was a mishmash of symbols
defined in the documents, symbols from other documents, and external
symbols.
After this change, the `SymbolInformation` on documents is just the
locals and defined symbols from the document.  All symbols referenced
and not from emitted documents are included in `external_symbols`.
Other behavior changes:
* `scip` command …
> Improve SCIP symbols

- crates/rust-analyzer/src/handlers/request.rs
fix #18800
https://github.com/rust-lang/rust-analyzer/blob/dae15045a76ec3d7d98901cbb2bcfeafbd96c80b/crates/ide/src/call_hierarchy.rs#L16-L20
Here `target` refers to the definition of the fn which is called, while `ranges` indicates the location of the call site.
For example:
```
fn f() {
g(); // ranges[0]
}
// another file
fn g() {} // target
```
> fix: incorrect file_id used for ranges in outgoing calls

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/env.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/reload.rs
Noticed we weren't actually filling these in yet
Fixes https://github.com/rust-lang/rust-analyzer/pull/18807
> fix: Populate cargo config env vars for crates

- crates/ide-assists/src/handlers/replace_if_let_with_match.rs
- crates/ide-assists/src/utils.rs
Closes: #8690 and #10583
Continuation of #10491. r? @Veykril if you don't mind?
The reason why the original author were unable to reproduce the first case in #8690 might be because of misuses of `minicore`, which creates an error in the types and make it fallback to the wildcard. Maybe we should give more information about `minicore` in the docs?
I extended the patterns marked as `FIXME` in #10491, while also covering the cases involving literals.
- Add test cases for `replace_if_let_with_match`
- Cover more cases for using wildcards on `make_else_arm`
> Fix replace-if-let-with-match generates non-exhausive match

- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/inlay_hints/binding_mode.rs
> internal: Do not render closure ids in hover messages

- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/tests.rs
- crates/ide/src/hover/tests.rs
With a bit of higher-order macros everything sorts out well.
And also fix a discovered bug when comparing long strings.
Fixes #18816.
> fix: Fix overflow detection in MIR evaluation

- crates/rust-analyzer/src/config.rs
Using an absolute path for cargo's build dir is allowed. I would like to have a global build dir for rust-analyzer as well, but _not_ use the same one as cargo (to avoid waiting for locks to release).
This was previously allowed, but was changed by @Veykril in c8fdcea85c273c386d1024815b955af6edae3fa2. Unsure of the reason for the change, using an absolute path seems to work fine.
> allow targetDir to be an absolute path

- crates/hir-ty/src/utils.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/18842
> fix: Handle newstyle `rustc_intrinsic` safety correctly

- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/target_spec.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18844, the code here is now a lot clearer as well, no longer mixing two clear branches of logic
> fix: Fix flycheck getting confused which package to check

- crates/rust-analyzer/src/lsp/ext.rs
- docs/dev/lsp-extensions.md
Fixes https://github.com/rust-lang/rust-analyzer/issues/18767, while the client already has this patched not everyone will necessarily want to update their setup there I imagine.
> fix: Be more permissive with completion resolve data

- crates/rust-analyzer/src/flycheck.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18847#issuecomment-2573022201
> fix: Fix non-cargo flychecks immediately clearing received diagnostics

- crates/hir-expand/src/fixup.rs
- crates/ide/src/inlay_hints.rs
- crates/test-fixture/src/lib.rs
> fix: Fix a bug that was caused by fixup reversing

- crates/rust-analyzer/src/flycheck.rs
This _should_ fix #18854.
This is just an impl of [Lukas's comment](https://github.com/rust-lang/rust-analyzer/pull/18848/files#r1904656621); I tested this on rust-analyzer, canceled flycheck while it was running, and saw diagnostics get cleared when they previously wouldn't.
> fix: clear diagnostics on cancel unconditionally

- crates/hir-def/src/nameres/collector.rs
- crates/hir/src/semantics.rs
- crates/ide-completion/src/tests/item.rs
We ignore `#[test]` in the def map, so that's why it failed.
Fixes #18834.
> Fix case where completion inside macro that expands to `#[test]` was unavailable

- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/test-fixture/src/lib.rs
Fixes #17479
This PR disables completions within strings in proc macros.
> fix: do not offer completions within macro strings

- crates/rust-analyzer/src/flycheck.rs
While https://github.com/rust-lang/rust-analyzer/pull/18848 fixed an issue with diagnostics clearing too eagerly, and https://github.com/rust-lang/rust-analyzer/commit/140f91b04503dc9265db27e4fef43e6039fbb2e7 fixed an issue with diagnostics state not being properly reset between flychecks, we're still facing an issue where diagnostics are not cleared at all between flychecks runs.
Indeed, if the diagnostic doesn't have a corresponding package_id (as is the case with rustc diagnostics), it won't get cleared between flychecks.
This diff adds a `diagnostics_cleared_for_all` flag to keep track of such diagnostics, and moves the diagnostics state clearing to its own method.
> fix: Fix diagnostics not clearing between flychecks

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Closes https://github.com/rust-lang/rust-analyzer/issues/18590
> Remove `rust-analyzer.cargo.sysrootQueryMetadata` config again

- crates/project-model/src/lib.rs
- crates/project-model/src/toolchain_info/rustc_cfg.rs
- crates/project-model/src/toolchain_info/target_data_layout.rs
- crates/project-model/src/toolchain_info/target_tuple.rs
- crates/project-model/src/toolchain_info/version.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/flycheck.rs
- docs/user/generated_config.adoc
- docs/user/manual.adoc
- editors/code/package.json
See https://github.com/rust-lang/rust/pull/125579
> internal: target-triple -> target-tuple + version fetching cleanup

- crates/mbe/src/expander/transcriber.rs
We already emit an error. This also printed the entire token tree which can be gigantic.
> Drop unnecessary tracing::warn

- crates/ide-diagnostics/src/tests.rs
- crates/ide-diagnostics/src/tests/overly_long_real_world_cases.rs
- crates/mbe/src/expander/transcriber.rs
We should immediately mark them as finished, on the first entry.
The funny (or sad) part was that this bug was pre-existing, but previously to #18327, it was causing us to generate bindings non-stop, 65535 of them, until we get to the hardcoded repetition limit, and then throw it all away. And it was so Blazingly Fast that nobody noticed.
With #18327 however, this is still what happens, except that now instead of *merging* the fragments into the result, we write them on-demand. Meaning that when we hit the limit, we've already written all previous entries. This is a minor change, I thought for myself when I was writing this, and it's actually for the better, so who cares. Minor change? Not so fast. This caused us to emit 65535 repetitions, all of which the MBE infra needs to handle when …
> fix: Fix a bug with missing binding in MBE

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
- crates/ide-assists/src/handlers/apply_demorgan.rs
- crates/ide-assists/src/handlers/bool_to_enum.rs
- crates/ide-assists/src/handlers/convert_closure_to_fn.rs
- crates/ide-assists/src/handlers/convert_from_to_tryfrom.rs
- crates/ide-assists/src/handlers/convert_while_to_loop.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/move_guard.rs
- crates/ide-assists/src/handlers/remove_dbg.rs
- crates/ide-assists/src/handlers/replace_if_let_with_match.rs
- crates/ide-assists/src/handlers/replace_let_with_if_let.rs
- crates/ide-assists/src/handlers/replace_try_expr_with_match.rs
- crates/ide-assists/src/handlers/unmerge_match_arm.rs
- crates/ide-assists/src/handlers/unwrap_block.rs
- crates/ide-assists/src/utils.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
- crates/ide-assists/src/utils/ref_field_expr.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
- crates/syntax/src/syntax_editor.rs
Part of #15710 and #18285
This PR migrates the `replace_let_with_if_let`, `replace_if_let_with_match`, and `replace_match_with_if_let` assists. It also cleans up a few of the old `make::` constructors which should make future migrations easier, and also subtly hint at the kind of API we'd want from the new `SyntaxFactory` constructors.
> internal: Migrate `if let` replacement assists to `SyntaxEditor`

- crates/hir/src/lib.rs
- crates/ide-completion/src/completions/env_vars.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/18883
> fix: Fix `env`/`option_env` macro check disregarding macro_rules definitions 

- crates/ide-assists/src/handlers/add_turbo_fish.rs
- crates/ide-assists/src/handlers/unwrap_return_type.rs
- crates/ide-assists/src/handlers/wrap_return_type.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
Part of #15710 and #18285
This PR also includes some small fixes to `SyntaxEditor`, in particular a fix to the problem with `affected_range` [outlined here](https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/.60ChangedAncestor.3A.3Aaffected_range.60.20for.20.60SyntaxToken.60s). 
I also updated `unwrap_return_type` to use placeholders when unwrapping `None`. I had tried to do this with the mutable tree API before and it was kind of a pain so it's nice to see improvements like this :)
> internal: Migrate `(un)wrap_return_type` assists to use `SyntaxEditor`

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/extern_abi.rs
- crates/ide-completion/src/completions/format_string.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/completions/lifetime.rs
- crates/ide-completion/src/completions/mod_.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/tests.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/fn_param.rs
- crates/ide-completion/src/tests/item.rs
- crates/ide-completion/src/tests/item_list.rs
- crates/ide-completion/src/tests/pattern.rs
- crates/ide-completion/src/tests/predicate.rs
- crates/ide-completion/src/tests/proc_macros.rs
- crates/ide-completion/src/tests/record.rs
- crates/ide-completion/src/tests/special.rs
- crates/ide-completion/src/tests/type_pos.rs
- crates/ide-completion/src/tests/use_tree.rs
- crates/ide-completion/src/tests/visibility.rs
This PR moves common helper functions within the test files of the ide-completions crate to `tests.rs`.
> refactor test helpers within ide-completions

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This PR replaces the current structure (a `HashMap`) for the `rust-analyzer.cargo.cfgs` setting with a `Vec<String>`. The use of a vector seems more appropriate for the following reasons:
- Repeated same `cfg` keys can be used (currently impossible due to the use of a `HashMap`).
- In the end, the original `HashMap` is turned into a vector of (key, value) tuples, so it seems there is no benefit to using a `HashMap` to hold these settings.
A beneficial side effect of this change is that `rust-analyzer` can have partial support for multi-target analysis through this setting (see the following configuration example).
```json
{
"rust-analyzer.cargo.cfgs": [
"debug_assertion",
"miri",
"target_arch=x86_64",
"target_arch=aarch64",
]
}
> refactor: struct holding cargo cfgs settings

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
The motivation for this is resolving unresolved symbols for Firefox. We build Rust code with cargo but generate some code via our primary build system mach. Additionally, we bundle the windows crate in an out-of-source and out-of-build location. Essentially the same idea as discussed [here](https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/include!.20failing.20for.20some.20paths), Firefox issue tracked [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1890431).
I investigated instead populating the vfs via rustc's `--emit=dep-info` as cargo already emits .d files but at this time cargo [does not relay .d file changes](https://github.com/rust-lang/cargo/issues/13672#issuecomment-2147772916) as it hazards the unspecified cargo directory layout …
> Add config setting which allows adding additional include paths to the VFS.

- crates/ide-completion/src/context/analysis.rs
It should be left biased, not right biased, because when e.g. the use has typed `h` then requested completion, the `h` is what we want to find, not the next token (which might indeed be inside a macro call).
I'm not sure why I wrote `right_biased()` to begin with (I remember I had a reason and not just "both should work"), I might've copied the code in `expand_and_analyze()` (which is wrong, because there it lookups on the speculative file, where right biased will always find the correct token and left biased not).
This is still not perfect, because there might not be an identifier already typed then we might still end up in a macro call, but this is the best we can do.
Fixes #18888. The reason the final assert worked is not because it somehow "reset" things, but because there was no …
> fix: Fix actual token lookup in completion's `expand()`

- crates/hir-expand/src/builtin/quote.rs
- crates/hir-expand/src/fixup.rs
- crates/ide/src/inlay_hints.rs
- crates/test-fixture/src/lib.rs
We need to *remove* the whole subtree, but we don't advance `i` by this, because it hasn't gotten there yet (and never will).
This was a stupid mistake on my part.
Fixes #18898.
> fix: Fix another issue with fixup reversing

- crates/ide-assists/src/handlers/inline_macro.rs
And not just called to be listed.
This was a major performance hang when repeatedly switching back-and-forth between a large `include!`d file, aka. #18879 (but there are others). This does not fix this issue because, well, it was a major hurdle hiding everything else in the profiler, but now that it's fixed other things show up (and it's still slow).
To categorize the main reasons remained, as analyzed by my profiler:
We have a lot of diagnostics, influenced mainly by two salsa queries, `body_with_source_map()` and `borrowck()`. These two are lru'ed so they of course evict with such large files with lots of small bodies. If I didn't let the file to analyze well before starting my back-and-forth, we also have a lot of calls to `infer()`, half of them are blocking on the other. This is also …
> fix: Do not compute `prettify_macro_expansion()` unless the "Inline macro" assist has actually been invoked

- crates/ide-assists/src/handlers/inline_macro.rs
- crates/ide-db/src/famous_defs.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/bounds.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Not too useful per se really, but I'd like r-a to be able to visualize anything that may be implied while expressible explicitly via surface syntax in rust.
> Implement implicit sized bound inlay hints

- crates/hir-def/src/attr.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/tests.rs
- crates/hir-expand/src/mod_path.rs
- crates/hir-ty/src/tests/simple.rs
- crates/ide/src/goto_type_definition.rs
- crates/intern/src/symbol/symbols.rs
This skips lowering of the annotated body except for its signature. This allows analysis that refers to this to still work fine while making it useful already.
cc https://github.com/rust-lang/rust-analyzer/issues/11556
> Implement `#[rust_analyzer::skip]` for bodies

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/adjustment.rs
- crates/ide/src/inlay_hints/discriminant.rs
- crates/ide/src/inlay_hints/implicit_drop.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/13962
> internal: Compute inlay hint tooltips lazily

- Cargo.lock
- crates/vfs-notify/Cargo.toml
Fixes #18932 by updating the `notify` crate to v8.0, which fixed UB on Windows that resulted in a `STATUS_ILLEGAL_INSTRUCTION` in certain workspaces when `rust-analyzer` was compiled in release mode.
> fix: Update `notify` to `8.0.0`

- editors/code/package.json
The new syntax tree view is awesome, but I suspect that it is only useful to a subset of rust-analyzer users who can enable it when they need it. With many extensions installed, the sidebar can become cluttered.
cc @Giga-Bowser what do you think?
> Hide syntax tree view by default

- crates/ide-completion/src/item.rs
- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/lib.rs
This PR adds dereferencing suggestions for Copy types. When a function expects a non-reference type T and we have a &T where T: Copy, we now suggest the dereferenced value in completions.
https://github.com/rust-lang/rust-analyzer/issues/18873
> feat: Add dereferencing autocomplete

- crates/hir-ty/src/display.rs
- crates/ide/src/inlay_hints/bind_pat.rs
Basically if we have some projection `<S as T>::Assoc` if `Assoc` here itself has known bounds (other than `Sized`) we instead render that type as `impl Bounds` (where `Bounds` are the bounds of `Assoc` as that is generally more useful information)
Fixes https://github.com/rust-lang/rust-analyzer/issues/17870
> feat: Render type parameter projection target bounds in inlays

- crates/hir/src/semantics.rs
- crates/ide-db/src/search.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- docs/user/generated_config.adoc
- editors/code/package.json
cc https://github.com/rust-lang/rust-analyzer/issues/16084#issuecomment-2590953581
> Flip on typing config to be opt-in, better defaults

- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/17592
Fixes https://github.com/rust-lang/rust-analyzer/issues/18936
> fix: Fix semantics not always correctly caching file roots

- crates/rust-analyzer/src/test_runner.rs
For issue #18896 - `cargo test` json output does not include a `stdout` field if given the `--nocapture` flag.
RA only records the stdout for failed tests. It would be possible to move the `stdout` field to `CargoTestMessage` so that the user can inspect the stdout of passing tests too.
> fix: Make test_runner::TestState::stdout optional to fix parsing cargo test json output

- Cargo.lock
- Cargo.toml
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
Chalk PR that this brings in: https://github.com/rust-lang/chalk/pull/821
Fixes #18083
cc @ShoyuVanilla I've seen you involved in other trait-upcasting-related issues, maybe this unblocks something else?
> update chalk, fixing trait upcasting

- crates/hir/src/lib.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
- crates/test-utils/src/minicore.rs
E.g. complete `await.foo()`.
Closes #15369.
> feat: Add smart completions that skip `await` or `iter()` and `into_iter()`

- crates/load-cargo/src/lib.rs
- crates/project-model/src/workspace.rs
This caused a bunch of issues, likely due to this changing the way we partition the source roots, this also removes a bit more of our rust-analyzer.toml loading for now, effectively disabling most loading for it (will note that down int he tracking issue), the source root system is just too brittle to support this right now and so the toml support is blocked on our VFS rewrite.
Closes https://github.com/rust-lang/rust-analyzer/issues/18886 
Closes https://github.com/rust-lang/rust-analyzer/issues/18748
> Partially back out "fix: Fix sourceroot construction for virtual manifests"

- crates/hir/src/lib.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/hover.rs
cc https://github.com/rust-lang/rust-analyzer/pull/18946
> Generalize some type walking in hover type actions

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
There is a typo (missing `s` in `debug_assertions`) introduced in 1c5a125beb35725ccc2ade005db9870db734bf23 causing rust-analyzer to incorrectly mark `#[cfg(debug_assertions)]`, `#[cfg_attr(debug_assertions, ...]` as inactive
I would appretiate vscode marketplace release with this bugfix, thanks
> Fix `debug_assertions` broken in 1c5a125

- crates/hir-def/src/body/lower.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/expression.rs
- crates/parser/src/grammar/expressions.rs
- crates/parser/test_data/parser/inline/ok/ref_expr.rast
- crates/parser/test_data/parser/inline/ok/ref_expr.rs
1. complete `raw`, `const` keyword
2. parse `let _ = &raw foo` better
> feat: complete raw, const keyword

- crates/parser/src/event.rs
- crates/parser/src/grammar.rs
- crates/parser/src/grammar/expressions.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/src/parser.rs
- crates/parser/test_data/parser/err/0056_let_else_right_curly_brace_struct.rast
- crates/parser/test_data/parser/err/0056_let_else_right_curly_brace_struct.rs
- crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_arithmetic.rast
- crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_arithmetic.rs
- crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_format_args.rast
- crates/parser/test_data/parser/err/0057_let_else_right_curly_brace_format_args.rs
- crates/parser/test_data/parser/err/0058_let_else_right_curly_brace_range.rast
- crates/parser/test_data/parser/err/0058_let_else_right_curly_brace_range.rs
- crates/parser/test_data/parser/err/0059_let_else_right_curly_brace_closure.rast
- crates/parser/test_data/parser/err/0059_let_else_right_curly_brace_closure.rs
- crates/parser/test_data/parser/err/0060_let_else_right_curly_brace_unary.rast
- crates/parser/test_data/parser/err/0060_let_else_right_curly_brace_unary.rs
- crates/parser/test_data/parser/err/0061_let_else_right_curly_brace_do_yeet.rast
- crates/parser/test_data/parser/err/0061_let_else_right_curly_brace_do_yeet.rs
- crates/parser/test_data/parser/err/0062_let_else_right_curly_brace_become.rast
- crates/parser/test_data/parser/err/0062_let_else_right_curly_brace_become.rs
- crates/parser/test_data/parser/err/0063_let_else_right_curly_brace_reference.rast
- crates/parser/test_data/parser/err/0063_let_else_right_curly_brace_reference.rs
- crates/parser/test_data/parser/err/0064_let_else_right_curly_brace_assignment.rast
- crates/parser/test_data/parser/err/0064_let_else_right_curly_brace_assignment.rs
fixes #18345 - rust-analyzer fails to emit errors for let...else statements when the initializer expression ends in a block-like construct
- Updated `CompletedMarker` to store the position where the node was completed.
- Introduced a new `last_token` function that walks back through the parsing events from the completion position to find the last emitted token.
> Fix: Detect missing errors for } braces before else in let...else statements

- crates/profile/Cargo.toml
I tried using the crate `ra_ap_profile` from crates.io, but I encountered this error due to a missing feature:
```powershell
error[E0425]: cannot find function, tuple struct or tuple variant `GetCurrentProcess` in this scope
--> C:\Users\gvozdvmozgu\.cargo\git\checkouts\rust-analyzer-cf7e117ee9ee1d0a\cd199ea\crates\profile\src\memory_usage.rs:43:37
|
43  |                 let proc = unsafe { GetCurrentProcess() };
|                                     ^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `GetCurrentProcessId`
|
::: C:\Users\gvozdvmozgu\.cargo\registry\src\index.crates.io-6f17d22bba15001f\windows-sys-0.52.0\src\Windows\Win32\System\Threading\mod.rs:179:1
|
179 | ::windows_targets::link!("kernel32.dll" "system" fn GetCurrentProcessId() -> u32);
| …
```
> add missing `Win32_Foundation` feature

- docs/dev/README.md
Updates the documentation in `docs/dev/README.md` to describe the new syntax tree viewer, added in #18813.
> Update syntax tree viewer docs

- Cargo.lock
- crates/proc-macro-srv/Cargo.toml
- crates/proc-macro-srv/src/dylib.rs
the constant is wrong on some platforms (e.g., on mips64el it's 0x10, and 0x8 is RTLD_NOLOAD which makes all this functionality broken), the libc crate takes care of those differences for us.
fallback to not setting the flag in non-glibc environments - some of them might have support for it using a different value that we don't know about, and some of them lack it entirely.
> proc-macro-srv: make usage of RTLD_DEEPBIND portable

- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/lower.rs
- crates/ide-diagnostics/src/handlers/generic_args_prohibited.rs
They should be considered just as well as in value ns, for example for struct literals.
Fixes #18974. I think this needs a beta backport.
> fix: Fix a bug where enum variants were not considered properly in type ns resolution

- Cargo.lock
- Cargo.toml
- crates/hir-def/src/data.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/lang_item.rs
- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/visibility.rs
- crates/hir-expand/src/name.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests.rs
- crates/hir/Cargo.toml
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/child_by_source.rs
- crates/hir/src/symbols.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/items_locator.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
- crates/ide/src/navigation_target.rs
I somehow didn't realize that https://github.com/rust-lang/rust-analyzer/pull/18699 never fixed what it was supposed to fix. Probably because I accidentally expect updated the test.
The gist of this PR is that we now record all imports that have an explicit visibility set (or that exist in the crate-root), treating them as if they are re-exports (opposed to only treating rename imports as such). This in turn fixes the completion issue as the relevant import is now recorded.
I do fear this might have an impact on flyimport completion times as we have a lot more symbols to go through now, will investigate that before merging.
> Properly record meaningful imports as re-exports in symbol index

- editors/code/src/ctx.ts
I don't think this entirely fixes #18959, but at least when debugging, it made whatever race condition is necessary way less common. I'll keep looking into it.
> fix: Only refresh syntax tree view when the active document changes

- crates/ide-completion/src/item.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
I don't think my ranking is perfect, because it places them even behind snippet completions, but this is something.
Fixes #18985.
> fix: Sort completion items that skip `await` and  `iter()` behind those that don't

- crates/project-model/src/project_json.rs
- docs/user/manual.adoc
Ensure that all the fields that rust-analyzer understands are in the manual, they all have doc comments, and they use consistent punctuation (`;` rather than mixing `,` and `;`).
Whilst we're here, fix the `sysroot_src` example and add 2024 as a legal value for Rust edition.
> manual: Document all rust-project.json fields

- crates/hir-ty/src/autoderef.rs
The limit was introduced in https://github.com/rust-lang/rust-analyzer/pull/1408#discussion_r294059044 to avoid infinite cycles but it effectively caps the number of derefs to 10. Types like `ID3D12Device14` from the `windows` crate run into this because it derefs to `ID3D12Device13`, 13 to 12 and so on. Increasing it to 20 is a quick fix; a better cycle detection method would be nicer long term.
> increase `AUTODEREF_RECURSION_LIMIT` to 20

- crates/hir-def/src/body/lower.rs
Fixes reaching `def map should have macro definition, but it doesn't` when a block contains a macro definition which is cfg'd out:
```rust
fn main() {
#[cfg(foo)]
macro_rules! m {
() => {};
}
}
```
> Check cfg when collecting macro defs

- crates/hir-def/src/body/tests/block.rs
- crates/hir-def/src/import_map.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests.rs
- crates/hir-def/src/nameres/tests/globs.rs
- crates/hir-def/src/nameres/tests/macros.rs
- crates/hir-def/src/per_ns.rs
- crates/hir-def/src/resolver.rs
- crates/hir/src/symbols.rs
- crates/ide-db/src/symbol_index.rs
This caused us other code to incorrectly assume in dealing with a declaration when in fact it was dealing with a glob imported definition. This can cause hangs with certain setups that involve glob imports and local item block modules (not sure on the exact setup needed), it also means we do a lot more work in some cases (or even wrong work).
> fix: Fix `ItemScope` not recording glob imports

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/config.rs
- crates/ide-completion/src/tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> feat: Provide a config to control auto-insertion of `await` and `iter()`

- crates/project-model/src/toolchain_info/rustc_cfg.rs
If the user doesn't have rustc on $PATH, rust-analyzer won't be able to run `rustc --print cfg`. This isn't really an error, as rust-analyzer can still proceed without it.
This is particularly noticeable when loading crates defined in a rust-project.json. Until the configuration is loaded, the opened files are briefly treated as detached files and users see this error.
Environments with rust-project.json generally have a sysroot and rustc elsewhere, so the error confuses users.
> internal: Treat cfg fetching failures as a warning

- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/handlers/notification.rs
We only ever have one flycheck runner no matter the number of workspaces, so just kick off flycheck for it immediately.
Supercedes/Closes https://github.com/rust-lang/rust-analyzer/pull/19010, fixes https://github.com/rust-lang/rust-analyzer/issues/18954
> fix: Fix flycheck panicking with "once" invocation strategy

- crates/hir-def/src/lang_item.rs
- crates/hir-ty/src/autoderef.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/ide-completion/src/completions/dot.rs
- crates/intern/src/symbol/symbols.rs
- crates/test-utils/src/minicore.rs
> feat: Implement `arbitrary-self-types`

- crates/hir/src/lib.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/bounds.rs
- crates/ide/src/inlay_hints/chaining.rs
- crates/ide/src/inlay_hints/closing_brace.rs
- crates/ide/src/inlay_hints/closure_captures.rs
- crates/ide/src/inlay_hints/generic_param.rs
- crates/ide/src/inlay_hints/implicit_drop.rs
- crates/ide/src/inlay_hints/param_name.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
Now that we do lazy properties here properly we can keep the ones that we can't resolve lazily (which almost never happens)
> Keep already computed inlay hint properties instead of late resolving them

- crates/load-cargo/src/lib.rs
- crates/project-model/src/workspace.rs
Partially reverts #18668 which changed this such that buildfiles are implicitly included by including their parent directory. This behavior is potentially problematic, because it also includes everything else in that directory. At work, we vendor third-party libraries under a common directory with a single shared buck buildfile. With this approach, the entire third-party directory is included in the PackageRoot.
> Explicitly add buildfiles when constructing ProjectFolders

- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-db/src/syntax_helpers/suggest_name.rs
Previously, we'd suggest a type of `vec` for a value of type `Vec<T>`, which is rarely what the user wants. We also had no suggestions for values of type `&[T]`.
Instead, try to pluralise the inner type name, and fall back to `items`.
> minor: Suggest better names when a type is a sequence

- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
Format niche information like so:
> Make niches into nices

- crates/hir/src/symbols.rs
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
Otherwise this will pollute the index too much with unnecessary symbols
> Only collect implicit visibile use symbols if they have renames

- crates/hir-def/src/find_path.rs
- crates/hir-def/src/lib.rs
- crates/hir-ty/src/display.rs
- crates/ide-assists/src/assist_config.rs
- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/config.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/snippet.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/path_transform.rs
- crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/ide-diagnostics/src/handlers/typed_hole.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide-ssr/src/matching.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
This also should have the benefit of no longer importing intrinsics on stable (as their module is unstable, funnily rustc doesn't check that?).
> fix: Fix flyimport not filtering via stability of import path

- Cargo.lock
- Cargo.toml
- crates/intern/Cargo.toml
- crates/intern/src/symbol.rs
Given its stable now, though we likely wanna wait some time until we bump our crates
> Use `strict_provenance`

- crates/ide/src/hover.rs
- crates/ide/src/hover/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19027
> fix: Fix markdown horizontal ruler sometimes being treated as a heading

- crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs
- crates/proc-macro-srv/src/server_impl/token_id.rs
That is, make the fake number that we return 1 and not 0.
Fixes #19032.
> fix: Make proc_macro span's line & column 1-indexed, as documented

- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/completions/use_.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/use_tree.rs
Also refactor the check a bit.
Fixes #19031.
> fix: Don't complete doc(hidden) enum variants and use trees

- crates/hir-def/src/data.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/term_search/tactics.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/intern/src/symbol/symbols.rs
AKA. target_feature 1.1, or non unsafe target_feature.
It's going to stabilize soon (https://github.com/rust-lang/rust/pull/134090)! Although this isn't fatal, we will just miss some unsafe diagnostics, but I plan to implement unused_unsafe so it will incur annoying warning.
> feat: Support RFC 2396

- crates/rust-analyzer/src/lsp/semantic_tokens.rs
That was used as a fallback, causing a panic when the fallback was chosen.
I also made sure this won't happen again by guaranteeing in the macro generating the tokens that they all exist.
Fixes #19043.
> fix: Fix a missing standard token in semantic highlighting

- crates/hir-def/src/data.rs
- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir/src/source_analyzer.rs
- crates/hir/src/term_search/tactics.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/format.rs
- crates/ide/src/syntax_highlighting/highlight.rs
It should be considered by the edition of the caller, not the callee.
Technically we still don't do it correctly - we need the span of the method name (if it comes from a macro), but we don't keep it and this is good enough for now.
This *is* fatal, we would show wrong errors for people once the stdlib switches to edition 2024.
> fix: Fix #[rustc_deprecated_safe_2024]

- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
- crates/ide/src/syntax_highlighting/tests.rs
CC #19041
Didn't add all of them to the test though. I think the trait alias case already works, even without my change.
> fix: Fix syntactic highlighting for renames

- crates/hir/src/lib.rs
- crates/hir/src/term_search.rs
- crates/ide-assists/src/utils.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
I added it by mistake in #18927.
I chose to keep the method as not static, because it's more comfortable, and keep the name `add_reference()` and not `reference()`, because it is clearer and better matches `strip_reference[s]()`.
> minor: Remove duplicate method from `hir::Type`

- crates/rust-analyzer/src/handlers/dispatch.rs
- crates/rust-analyzer/src/main_loop.rs
Some people still seem to run into https://github.com/rust-lang/rust-analyzer/issues/5111, and I think this might be why.
> Prioritize formatting thread tasks in main_loop

- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
> fix: Report calling unsafe fn pointer as unsafe

- crates/rust-analyzer/tests/slow-tests/testdir.rs
Currently, running rust-analyzer tests on FreeBSD produces an "unused variable" warning. The code is fully compatible with FreeBSD and doesn't have to be omitted.
> Add FreeBSD as a target OS for TestDir to avoid warnings

- crates/hir-ty/src/autoderef.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/ide-completion/src/completions/dot.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19059, will kick off another release after this as this breaks all toolchains <1.84
> Disable `Receiver` based autoderef temporarily

- editors/code/package.json
After #18592, opening the Rust Analyzer Language Server output in vscode hides the rust-analyzer status bar item which is kind of annoying. Add `output:extension-output-rust-lang.rust-analyzer*` document selector to default allow list for showing the status bar item.
> Show status bar in RA output

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/lib.rs
The TentHash spec was frozen Jan 1st 2025, and release 1.0 of the Rust crate is a minor cleanup as a follow-up to that, representing a commitment to API stability as well.
The hash output remains the same as version 0.4, which rust-analyzer was previously using. The only API change was a struct rename.
> Update TentHash to version 1.0

- crates/rust-analyzer/src/lib.rs
Previously it may have been possible for different completion items to produce colliding hashes, not because of the hash but because of how the items were serialized into byte streams for hashing. See #19071 for details.
The chances of that happening were low, if it was actually possible at all. Nevertheless, this commit ensures that it definitely can't happen.
This commit uses a handful of techniques used to fix this, but they all boil down to "ensure this could be re-parsed". If it's possible to parse to recreate the original item, then by construction there is no chance of two different items getting serialized to identical byte streams.
> Fix #19071: ensure `completion_item_hash` serializes items uniquely

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/reload.rs
We desperately need to build better perf monitoring infra, the `RA_PROFILE` setup is honestly quite useless
> More rustfmt hang investigations

- crates/ide/src/moniker.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/scip.rs
- crates/rust-analyzer/tests/slow-tests/cli.rs
* Fix an overflow in computing `is_inherent_impl` (`moniker.identifier.description.len() - 2`). No behavior change, just annoying when trying to debug.
* Fix missing symbol name for occurrences of `crate`. Where we previously emitted, e.g., `{ "range": [ 5, 4, 9 ] }`, we will now emit `{ "range": [ 5, 4, 9 ], "symbol": "rust-analyzer cargo foo . crate/" }`.
* Fix missing symbols for implicit module names. We previously emitted occurrences of module names but not the actual symbol definitions for modules implicitly defined by files.
> Fix scip indexing of module names

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide-diagnostics/src/handlers/incorrect_case.rs
- crates/ide-diagnostics/src/handlers/mutability_errors.rs
It generaly does not work as expected right now as we fallback type parameters to errors, making most generic functions fail
> Do not use make use of `InferenceResult::has_errors` flag for mir building

- crates/base-db/src/input.rs
- crates/hir-def/src/import_map.rs
- crates/hir-def/src/nameres.rs
- crates/hir-expand/src/name.rs
- crates/hir-expand/src/prettify_macro_expansion_.rs
- crates/ide-db/src/prime_caches.rs
- crates/ide/src/view_crate_graph.rs
- crates/intern/src/symbol/symbols.rs
- crates/project-model/src/project_json.rs
- crates/project-model/src/tests.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/unresolved_references.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/test-fixture/src/lib.rs
We want the `DefMap`'s to be computed ASAP, but for local packages we compute the import map (and the even more expensive symbol index) which would delay the def map computation of local leaf crates by a fair bit, so instead we do the def maps first in an initial phase, then follow up on the other indices in a second one.
> Split cache priming into distinct phases

- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/rename.rs
We stopped the expression search too early because `use` is an item.
I thought it'll be complicated, but it turned out to be easy.
Fixes #18286.
> fix: Fix IDE resolution of `use` inside a body

- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
Fixes #18766
This PR upmaps ranges for the `convert_tuple_struct_to_named_struct` ide-assist, fixing broken substitutions within macros.
> fix: upmap ranges in convert_tuple_struct_to_named_struct assist

- crates/proc-macro-srv-cli/src/main_loop.rs
- crates/proc-macro-srv/src/lib.rs
- crates/proc-macro-srv/src/tests/utils.rs
This will allow us to properly multiplex the server
> Use interior mutability for loaded `ProcMacrorv::expanders`

- crates/rust-analyzer/src/cli/scip.rs
We currently emit occurrences without a symbol name (e.g., `{ "range": [ 1, 7, 10 ] }`) for builtins (e.g., `i64`). This happens because `ide::moniker::def_to_moniker` returns `None` for builtins:
https://github.com/rust-lang/rust-analyzer/blob/ca47cddc31ae76a05e8709ed4aec805c5ef741d3/crates/ide/src/moniker.rs#L253-L257
It never makes sense to emit an occurrence without a symbol name, so just skip in that case.
> fix: Don't emit empty scip occurrence for builtins

- crates/hir-ty/src/infer/cast.rs
- crates/ide-diagnostics/src/handlers/invalid_cast.rs
> fix: Resolve projection types before checking casts

- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_definition.rs
fix : https://github.com/rust-lang/rust-analyzer/issues/18941, https://github.com/rust-lang/rust-analyzer/issues/19107
This PR resolves modules if items exist in the module and treats them as modules.
https://github.com/user-attachments/assets/c4a9f8d2-9b99-49b1-858e-ba94aa6ceaff
If a type import overwrites a module, this PR ensures it is resolved as a type
https://github.com/user-attachments/assets/577488e1-357d-42cc-86b8-58a0246d0517
> fix: if item exsits on module, resolve as module instead of type

- .github/workflows/ci.yaml
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/test-utils/src/lib.rs
fixes https://github.com/rust-lang/rust-analyzer/issues/19123.
the test doesn't actually verify that rust-analyzer applies the range *returned* from rustfmt correctly, but i tested locally that it does.
> Fix off-by-one error in RangeFormatting

- crates/load-cargo/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp/from_proto.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/lib.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
I have no idea what the original writer of the code thought (CC @matklad, I don't expect you to remember but it was you), but the logic just seems backwards. We should not exclude a file/directory if it is equal to an include! This also meant that we had to add a `root == path` check so this stuff will actually work, which in turn meant excludes (of root files) no longer worked...
Also rename if to `rust-analyzer.files.exclude`, because it can exclude files as well.
Fixes #14734.
> fix: Make `rust-analyzer.files.excludeDirs` work, actually

- crates/ide/src/inlay_hints/implicit_drop.rs
This PR try to fix https://github.com/rust-lang/rust-analyzer/issues/19100
> Fix: don't emit implicit drop inlay hints for macro

- docs/book/book.toml
The paths that point to the `Repository` and `Suggest an edit` links are incorrect (based on the original PR's assumption of `/manual`).
> doc: fix mdbook repository paths

- xtask/src/codegen.rs
Now that the manual lives at /manual/, we need to use absolute URLs to link to rustdoc content.
> manual: Fix URLs to rustdoc pages

- docs/book/book.toml
I had originally incorporated the [mdbook-toc](https://github.com/badboy/mdbook-toc) plugin to generate a table of contents for some of the generated content but the results were just too big to be of any use. Looks like we still have the config in the `book.toml` which doesn't break anything but probably emits an error in the book build output. Remove the config. It might be useful to create a toc somehow since the generated pages are so big. 
It would be cool to create a foldable sub-toc in the nav that just linked to the spot in the page. Not sure if that's possible in mdbook, but I'll look into it.
> doc: remove unused plugin config

- crates/hir-ty/src/mir.rs
- crates/ide-diagnostics/src/handlers/unused_variables.rs
If you have the `never`/`always` asserts enabled you'll run into frequent panics (which get our diagnostics stuck ...) due to us building mir with error types existing, so this works around  that.
> Propogate error types in mir type projections

- docs/book/README.md
We suggest running both `cargo test` and `cargo xtask codgen` to generate the docs in the book's top level README.md but not in `docs/book/README.md`. Add it there too.
> doc: add xtask codegen command in development README as well

- crates/ide-completion/src/completions/postfix.rs
Previously the receiver text was taken directly from the AST, which in macros is missing trivia, leading to corruption (or just unintended replacement of user code).
Now we upmap the range, and extract the original file text in it.
Fixes #19069.
> fix: Fix postfix completions inside macros

- crates/hir-def/src/macro_expansion_tests/proc_macros.rs
- crates/hir-expand/src/cfg_process.rs
- crates/test-fixture/src/lib.rs
This is not documented (and I discovered that from experimenting and looking at the compiler's source code), but cfg_attrs *on the same level* as the attribute macro should be processed before it is expanded. cfg_attrs *below* should not (and this is contrary to what happens with derive macros, where both should be processed).
Fixes #19121.
> fix: Censor cfg_attr for attribute macros

- crates/stdx/src/panic_context.rs
Housekeeping. `PanicContext::init` doesn't seem necessary.
> Simplify panic_context

- crates/hir-def/src/dyn_map.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir/src/from_id.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/child_by_source.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/inlay_hints/extern_block.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19108
> fix: Do not show safety hints for extern items lacking semantics

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
Part of #18285
#18459 has removed some of mutable syntax tree usages but there were some leftovers
> internal: Remove mutable syntax tree usages from `add_missing_match_arms` assist

- crates/ide/src/annotations.rs
- crates/ide/src/runnables.rs
There were two mistakes: first, tests were sorted before test modules, and second, we re-sorted based on the name only, which cancelled the sort based on the kind.
Fixes #19165.
> fix: Fix sorting of runnables

- crates/hir-def/src/data.rs
- crates/hir-def/src/path.rs
- crates/hir-def/src/resolver.rs
- crates/hir-expand/src/name.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/diagnostics.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower/diagnostics.rs
- crates/hir-ty/src/lower/path.rs
- crates/hir/src/diagnostics.rs
- crates/ide-diagnostics/src/handlers/parenthesized_generic_args_without_fn_trait.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_general.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/intern/src/symbol/symbols.rs
- crates/test-utils/src/minicore.rs
For non-`Fn` parenthesized generic args (each time, I plan working on the diagnostic from #17590, then I discover that ty lowering needs another refactor so I proceed with a refactor and a trivial diagnostic to test it. But this time I believe is the last :) ).
Path lowering started to look like a mess, with each function carrying additional parameters for the diagnostic callback (since paths can occur both in type and in expression/pattern position, and their diagnostic handling is different) and the segment index, for the diagnostics report. So I refactored it from stateless functions on `TyLoweringContext` into stateful struct, `PathLoweringContext`, that tracks the process of lowering a path from resolution til assoc types selection.
(I really hope I'm not making @jackh726's work on …
> feat: Refactor path lowering and serve a new path diagnostic

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/tests/coercion.rs
- crates/hir-ty/src/tests/traits.rs
> pass struct fields to chalk

- crates/ide-assists/src/handlers/expand_glob_import.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Fixes #13511 .
The code ends up pretty messy. To handle this more cleanly, I'd want some equivalent of `hir_def::visibility::Visibility::is_visible_from` that takes a `syntax::ast::Visibility` as the origin, or at least some type that can be easily derived from `syntax::ast::Visibility`.
The general problem (from my naive viewpoint as someone unfamiliar with the codebase) is that as far as I can tell the HIR data types you can get from `ctx.sema` already lost all knowledge about `use xxx` items; and those data types are the ones that can do fancy visibility computation. (`hir_def::item_tree::Use` would be useful, but I haven't found a way to get one from a `syntax::ast::Use`)
Anyway, 99% of re-exports are `pub` or `pub(crate)` anyway, so this should already be a large improvement.
> Implement expand_glob_reexport assist

- crates/hir-ty/src/infer/diagnostics.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/infer/path.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
I was wrong on #19127, I thought hir-def resolver is enough for them, but it turns out not because of paths like `<Enum>::Variant` and `Type::AssocThatIsEnum::Variant`.
> fix: Fix detection of ref patterns for path patterns

- Cargo.lock
I somehow missed this in #19169, maybe we need a `--locked` on CI.
> minor: Update lockfile

- xtask/src/codegen.rs
I just realized that the links to source files in three of the four generated doc files are wrong because they assume relative paths but they point to the doc site url instead of the repository itself (configuration is correct because its a single static link in `configuration.md`). 
This fix just points to the full URL to this repo instead, not sure if there is a better option.
> doc: use fully qualified url for source path

- xtask/src/codegen.rs
Apologies for the churn, missed the `L` to link directly to the line number correctly.
> doc: missed the L for the line number

- .github/workflows/release.yaml
This shouldn't make a difference since we're building in Rocky 8 containers, but let's see..
> internal: Use ubuntu-latest workers for releases

- docs/book/src/other_editors.md
The `Other Editors` section is a bit long, and presumably someone going there wants to find the config for their editor quickly. Add a table of contents.
> doc: toc for other editors

- crates/parser/test_data/generated/runner.rs
- xtask/src/codegen/parser_inline_tests.rs
When running `cargo codegen` the cwd is "rust-analyzer" however when running the tests in `xtask` the cwd is"rust-analyzer/xtask" which makes the codegen panic in various places. This is observed because the path is hard coded to `"crates/parser"` were it instead should be `project_root().join("crates/parser")`.
Furthermore, the parser inline test codegen has two generation targets: 1. the data files in `crates/parser/test_data/inline/**` and 2. the `crates/parser/test_data/generated/runner.rs`. The codegen for the second target is only run when the first target is updated. However, this can make it outdated in some cases. E.g. if the file is manually edited or if the source inline comment and both *.rast and *.rs data files are missing.
> Parser inline test codegen panics and/or does not run

- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
The 'Update Test' runnable was implemented in [PR #18757](https://github.com/rust-lang/rust-analyzer/pull/18757).
It was found that the `insta` snapshot library does not update inline snapshots using the 'Update Test' runnable because it only sets the environment variable `INSTA_UPDATE=always` which does not affect inline snapshots.
`insta` supports updating snapshots using `cargo-nextest`, which run each test in a single process, requiring the external tool `cargo-insta` to collect diffs and apply changes. Thus, updating inline snapshots with plain `cargo test` is not feasible([insta #490](https://github.com/mitsuhiko/insta/issues/490)).
This PR changes the 'Update Test' runnables to use `cargo insta test` instead of `cargo test ...` when the test involves `insta`. This change is …
> feat: update insta inline snapshot when clicking 'Update Test' runnable

- crates/ide-completion/src/completions/expr.rs
Don't filter out private items when completing paths in the same crate. Instead respect the `privateEditable` setting.
Fixes #9850
> Include private items in completions for local crates

- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/drop.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/mir/eval/shim.rs
- crates/hir/src/lib.rs
- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
Also fix the `needs_drop()` intrinsic.
Unions also need this information (to err if they have a drop-needing field), but this will come in a follow-up PR.
Closes #18947.
> feat: Calculate drop glue and show it on hover

- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/tests/generated.rs
- docs/book/src/assists_generated.md
This matches the behavior of the `generate_impl` assist.
I have no idea what this assist-doc demorgan cruft getting pulled along is but if it's just something #19171 forgot to do I'm fine having it done here.
> minor: Add tabstop to impl body in `generate_trait_impl` assist

- .typos.toml
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/target_feature.rs
- crates/hir-ty/src/utils.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
We vendor the list of implications, which isn't nice, but t-compiler doesn't want to make rustc_target available to us.
Fixes #19154. This may need a beta backport, if this won't get into the beta that target_feature 1.1's stabilization (https://github.com/rust-lang/rust/pull/134090) is within.
> fix: Support target features implications in target_feature 1.1

- crates/project-model/src/cargo_workspace.rs
On multi package workspace, cargo accepts "package-name/feature-name" format feature flags to specify package features for specific workspace members.
However, rust-analyzer doesn't forward these features to cargo and several errors are occured. Especially, optional depended proc-macro crates are not build and then `proc-macro crate build data is missing dylib path` error is shown.
So I fixed it.
> Allow "package/feature" format feature flag

- .github/workflows/release.yaml
- xtask/src/dist.rs
- xtask/src/flags.rs
- xtask/src/release.rs
> internal: set up Zig on CI and start using it in rust-analyzer

- crates/project-model/src/workspace.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19214
Needs backporting to beta
> Fix sysroot crate-graph construction not mapping crate-ids for proc-macros

- crates/ide/src/doc_links.rs
- crates/ide/src/doc_links/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/8487, which points out a difference between how `rustdoc` and `rust-analyzer` rewrites intra-doc links in the markdown. `rust-analyzer` currently does not properly add the anchor to reference items associated with a type, such as struct fields or methods in an `impl` block.
This PR implements the fix to add the appropriate anchor for the associated item at the end of the URL, becoming aligned with how `rustdoc` handles it.
* `rewrite_intra_doc_link`
* If no anchor is provided for the link, falls back on the fragment from `filename_and_frag_for_def`
* `filename_and_frag_for_def`
* Modify `Definition::Variant` to follow the same procedure as `Definition::Field`, early returning with the fragment specified
* `doc_links::tests`
* Add a …
> Add anchor for intra-doc links to associated items

- crates/rust-analyzer/src/lsp/capabilities.rs
This field in the server capabilities instructs the client to maintain the diagnostics received from a `textDocument/diagnostic` pull request as a separate set from other diagnostics: namely those sent with classic "push" diagnostics, `textDocument/publishDiagnostic`. rust-analyzer emits "native" diagnostics (computed by rust-analyzer itself) in pull diagnostics and separately emits cargo-based diagnostics with push, so push and pull diagnostics should be different sets. Setting this field instructs the client to avoid clearing push diagnostics when new pull diagnostics arrive and vice versa.
Also see discussion in #18709
> Add `identifier` to pull diagnostic LSP capabilities

- crates/ide-completion/src/render.rs
> completion-ref-matching

- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
- crates/rust-analyzer/src/reload.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/18730
> Warn when the used toolchain looks too old for rust-analyzer

- crates/cfg/src/cfg_expr.rs
- crates/cfg/src/dnf.rs
- crates/cfg/src/lib.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/flycheck.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
Fixes https://github.com/rust-lang/rust-analyzer/issues/5421
Fixes https://github.com/rust-lang/rust-analyzer/issues/11794
> Allow unsetting default cfgs

- crates/hir-def/src/hir/type_ref.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-db/src/generated/lints.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide/src/status.rs
- crates/intern/src/symbol.rs
- crates/profile/src/memory_usage.rs
- crates/test-utils/src/minicore.rs
Use `std::mem::{size_of, size_of_val, align_of, align_of_val}` from the prelude instead of importing or qualifying them.
These functions were added to all preludes in Rust 1.80.
> Use `size_of` from the prelude instead of imported

- crates/project-model/src/cargo_workspace.rs
The errors are silently dropped elsewhere, which make it really hard to debug issues due to dependency download failures.
> Add warning and debug information when `cargo metadata` fails

- editors/code/src/config.ts
We register the provider when we start the server. It confused me why I set the option and it didn't work, so probably better to have it hint people.
> minor: Mark `rust-analyzer.showSyntaxTree` config option as requiring server restart

- crates/ide-completion/src/item.rs
In PR #19297, we overlooked the type inconsistency caused by the new scope for `!0/2` (which then led to logical errors)
---
The rationale is as follows:  
---
Although we modified the threshold expression in PR #19297:
```diff
pub fn is_relevant(&self) -> bool {
-        self.score() > 0
+        self.score() > (!0 / 2)
}
```
We neglected some type-related issues within a new function scope, which resulted in only modifying the "apparent value" while the actual value remained 0 (as shown in the image above)
---
The reason I chose the first fix option is that it expresses the intent more clearly and avoids ambiguity
> Fix logical error in PR #19297

- crates/project-model/src/project_json.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
- crates/project-model/test_data/output/rust_project_cfg_groups.txt
- crates/project-model/test_data/output/rust_project_hello_world_project_model.txt
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/reload.rs
We shouldve probably rolled that back from the start when we noticed this
> Move loaded project MSRV back to 1.78, show notification for the warning

- crates/ide-assists/src/handlers/apply_demorgan.rs
- crates/ide-assists/src/handlers/inline_local_variable.rs
- crates/syntax/src/ast/prec.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
- docs/book/src/assists_generated.md
Fixes #19323
This also migrates `inline_local_variable` to `SyntaxEditor` as a part of #18285
> fix: Prevent wrong invocations of `needs_parens_in` with non-ancestral "parent"s

- Cargo.lock
- Cargo.toml
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/tests/simple.rs
- docs/book/src/assists_generated.md
Fixes #19196
Waiting on rust-lang/chalk#824
> Bump chalk for built-in supports of async closures

- crates/hir-def/src/macro_expansion_tests/mbe/tt_conversion.rs
- crates/hir-expand/src/fixup.rs
- crates/mbe/src/tests.rs
- crates/syntax-bridge/src/lib.rs
- crates/tt/src/lib.rs
- docs/book/src/assists_generated.md
Fixes #19206.
Fixes #18244.
r? @Veykril 
It's a bit hacky, since we keep emitting these invalid `Punct`s from syntax fixup but let `convert_tokens` deal with them.
> Fix syntax fixup producing invalid punctuation

- crates/hir/src/has_source.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- docs/book/src/assists_generated.md
A new syntax node `ast::VariantDef` has been introduced to map between the HIR node and the AST. The files have been updated with `cargo test -p xtask`.
Fixes #19302
> fix(hir): `VariantDef` is `impl HasSource`

- .editorconfig
The `max_line_length` property was set to 100 for all filetypes, which led to git commit messages being wrapped at 100 characters instead of the usual 75. This introduces an exception for the special file used by git to write commit messages.
> fix: do not apply editorconfig to git commit msg

- crates/load-cargo/src/lib.rs
@Veykril This pull request adds some logging for build script error output. I'm not sure this is the best place for the log statement. I picked the `load_workspace_at` because it's the place where the `ProjectWorkspace` and the error messages it may contain is dropped. The other functions have access to the `ProjectWorkspace` so calling application code can handle the errors itself if it wishes to do so. If you want to always log the errors then perhaps the `ProjectWorkspace::set_build_scripts()` method would be a better place for the log statement.
This log output would have been really helpful for figuring out some  undefined `OUT_DIR` error messages I was debugging earlier, so I was hoping it can be logged to make things easier in the future ;-)
> Log build script error output in `load_cargo::load_workspace_at`

- crates/rust-analyzer/src/flycheck.rs
cc @Veykril [this predicate](https://github.com/rust-lang/rust-analyzer/commit/5e18ad0#diff-8028b5acd2856fbdc72fafd05032eb259143fc51f4eecc6d1d87b1022475f857R417-R418) `self.diagnostics_received != DiagnosticsReceived::YesAndClearedForAll` will always evaluate to `true` as you're setting `self.diagnostics_received` to `DiagnosticsReceived::Yes` just before.
This breaks most Clippy diagnostics from displaying in our codebase.
> fix: Fix diagnostics being cleared right after being received

- crates/rust-analyzer/src/reload.rs
Not the prettiest PR so I want to suggest a few things : ( fixes #19184 )
1. While I was tinkering with our build script runners, I saw that we ignore any Warn level diagnostics but if there are any errors, warnings would also be included in the "problems". Since the PR simply adds showing what `cargo check` outputs as a server status message, users will now also see these warning when there are errors and not see them where there are not. This tells me that we can add a `DiagnosticLevel` guard to filter warnings out.
2. I could better format error messages, since they are not very pleasant to look at.
> minor: Show build scripts errors in server status 

- Cargo.lock
- crates/query-group-macro/Cargo.toml
- crates/query-group-macro/src/lib.rs
- crates/query-group-macro/src/queries.rs
- crates/query-group-macro/tests/arity.rs
- crates/query-group-macro/tests/cycle.rs
- crates/query-group-macro/tests/hello_world.rs
- crates/query-group-macro/tests/interned.rs
- crates/query-group-macro/tests/logger_db.rs
- crates/query-group-macro/tests/lru.rs
- crates/query-group-macro/tests/multiple_dbs.rs
- crates/query-group-macro/tests/old_and_new.rs
- crates/query-group-macro/tests/result.rs
- crates/query-group-macro/tests/supertrait.rs
- crates/query-group-macro/tests/tuples.rs
- crates/ra-salsa/ra-salsa-macros/Cargo.toml
- xtask/src/tidy.rs
Dependency of https://github.com/rust-lang/rust-analyzer/pull/18964. This shouldn't land until we get a Salsa release out, which depends on fixing the `powerpc` build failures.
> internal: vendor `query-group-macro` in rust-analyzer

- crates/base-db/src/lib.rs
- crates/hir-def/src/nameres/tests/macros.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir/src/semantics.rs
- crates/hir/src/symbols.rs
- crates/ide-diagnostics/src/lib.rs
- crates/ide-ssr/src/matching.rs
- crates/ide/src/hover.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/runnables.rs
- crates/ide/src/signature_help.rs
- crates/ide/src/static_index.rs
- crates/ide/src/view_memory_layout.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
This comes up when using rust-analyzer with the project discovery functionality (e.g., with Buck or Bazel), as rust-analyzer has *started*, but the crate graph isn't populated yet. I chose to return with an empty set of diagnostics instead of panicking.
@ChayimFriedman2: I think this qualifies as `RootQueryDb::all_crates` being used in query analysis?
> internal: don't panic when the crate graph isn't ready

- crates/ide-assists/src/handlers/convert_for_to_while_let.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
Closes: #19256
adds an assist that converts a for loop into a while let loop.
> feat: for loop to while let assist

- Cargo.toml
rust-analyzer no longer builds on 1.84:
```
error: failed to compile `rust-analyzer v0.0.0 (/rust-analyzer/crates/rust-analyzer)`, intermediate artifacts can be found at `/rust-analyzer/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
Caused by:
failed to download `ra-ap-rustc_index v0.100.0`
Caused by:
unable to get packages from source
Caused by:
failed to parse manifest at `/Users/davidrichey/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ra-ap-rustc_index-0.100.0/Cargo.toml`
Caused by:
feature `edition2024` is required
The package requires the Cargo feature called `edition2024`, but that feature is not stabilized in this version of Cargo (1.84.0 (66221abde 2024-11-19)).
Consider trying a newer version of …
```
> internal: Require Rust 1.85

- crates/rust-analyzer/src/handlers/request.rs
Same as the other resolve code handlers in the same file. 
https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#version_3_17_0 does not forbid resolving with no data, so instead of erroring, just consider such items resolved already.
> Do not error for actions with no data to resolve

- crates/proc-macro-api/src/legacy_protocol/json.rs
`out.flush()` already returns a `io::Result<()>`, so there is no need for `?` operator and `Ok(())`
> refactor: Simplify by removing ? operator

- crates/hir-def/src/generics.rs
- crates/hir-def/src/path.rs
- crates/hir-def/src/path/lower.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/lower/path.rs
- crates/hir/src/diagnostics.rs
- crates/ide-diagnostics/src/handlers/bad_rtn.rs
- crates/ide-diagnostics/src/lib.rs
These are small preparation commits to RTN, which turns out to require some quite big changes, first to lower RPITIT to associated types then to resolve RTN. So I thought I will first set a baseline.
> Preparation to Return Type Notation (RTN)

- crates/hir/src/lib.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
Currently the varargs are ignored, making the function signatures misleading.
> display varargs in completion detail

- crates/proc-macro-api/src/legacy_protocol/json.rs
- crates/proc-macro-api/src/legacy_protocol/msg.rs
- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-api/src/process.rs
Add doc to proc-macro-api crate.
> doc: add doc to proc-macro-api

- xtask/src/codegen/assists_doc_tests.rs
- xtask/src/codegen/diagnostics_docs.rs
- xtask/src/codegen/feature_docs.rs
`cargo test -p xtask` regenerates bindings with xtask. If any of these changes are relevant to a PR, they should a part of the PR. This change causes the CI to fail if a commit does not include the corresponding changes to generated files.
EDIT: The command already panics if any non-doc files are modified. This patch disables doc file generation with `--check`.
> fix(codegen): do not generate docs with `--check`

- crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19380
I believe the issue could occur if we trigger a `recreate_crate_graph` before finishing the proc-macro loading resulting in us only finishing the last report.
We should look into rewriting the workspace loading stuff here soon, it is really convoluted and difficult to reason about
> fix: Fix stale `Building CrateGraph` report

- crates/rust-analyzer/src/cli/analysis_stats.rs
Should help with https://github.com/rust-lang/rust-analyzer/pull/18964#issuecomment-2727329998 bit.
> analysis-stats: run Salsa's LRU at the end of analysis

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/make.rs
> Observe unsafeness when generating manual impls of former derives

- crates/hir-def/src/nameres/assoc.rs
`Expander` is a macro expansion solution for body lowering, there is no need to use it here
> refactor: Do not use `Expander` in assoc item lowering

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
In the body source map, we record each macro call with the `ExprOrPatId` it resolved to, so to lookup the `ExprId` of some node, we don't need to expand it!
> minor: Remove unnecessary expansions

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin/derive_macro.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/parser/src/lib.rs
- crates/parser/src/syntax_kind.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/generated/tokens.rs
- xtask/src/codegen.rs
- xtask/src/codegen/grammar.rs
- xtask/src/codegen/grammar/ast_src.rs
Replaces most of the derives with manual generated implementations that produce less code
> refactor: Reduce codegen burden for generated syntax

- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/closure_ret.rs
This PR fixes the FIXME in `closure_ret` by adding text edit functionality for closures with non-block bodies. When a user activates the return type hint for a closure without a block body (e.g., `|x| x + 1`), the edit now properly inserts both the return type annotation and the necessary braces around the body expression. This makes the return type hint feature work consistently for all types of closures.
> Add text edit support for return type hints on non-block body closures

- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/layout/tests.rs
> fix: Properly calculate the layouts of tuple ptrs whose last fields are DST

- crates/hir-def/src/attr.rs
- crates/hir-def/src/lib.rs
- crates/hir-ty/src/layout/tests.rs
Fixes #15037
In codes like the following cases:
```rust
#[repr(X)]
#[repr(Y)]
#[repr(Z)]
struct Foo { .. }
```
we've been using only the first `#[repr(X)]` attribute on struct, but we should handle them like `#[repr(X, Y, Z)]`
> fix: Handle multiple `#[repr(..)]` attrs correctly

- crates/ide/src/hover.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
> Render layout and other extra information on hovering `Self`

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/format.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_issue_19357.html
- crates/ide/src/syntax_highlighting/tests.rs
> Fix missing syntax highlighting for `&raw const` / `&raw mut` in all files.

- Cargo.toml
- crates/hir-def/src/lib.rs
- crates/query-group-macro/Cargo.toml
One is a leftover from #19416, the other fixes auto-publishing.
> minor: drop `rustc_hashes` dependency, add `syn` feature

- crates/hir-def/src/item_tree.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
Realized that we don't have a good measure for how many lines of code rust-analyzer is processing, so I decided to fix this. When `analysis-stats` is run, it'll now default to including a section titled "Source Stats" under "Database Loaded". See below for an example of me running `analysis-stats` on Salsa:
```
❯ ~/.cargo/bin/rust-analyzer analysis-stats .
Database loaded:     4.17s, 123mb (metadata 556.26ms, 2513kb; build 2.69s, 47kb)
item trees: 207
dependency lines of code: 2_588_498, item trees: 5_039
dependency item stats: traits: 1_562, impl: 23_087, mods: 5_955, macro calls: 9_136, macro rules: 2_175
Item Tree Collection: 4.23s, 934mb
Total Statistics:
crates: 90, mods: 235, decls: 5294, bodies: 4116, adts: 865, consts: 486
Workspace:
traits: 190, macro_rules macros: 14, …
```
> analysis-stats: emit lines of code and item tree counts for workspace; dependencies

- .github/workflows/ci.yaml
- crates/intern/Cargo.toml
Given the use of unsafe in there that seems appropriate
> ci: run `intern` tests via `cargo miri`

- crates/hir-def/src/data/adt.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/parser/src/grammar/items/adt.rs
- crates/parser/test_data/parser/inline/ok/record_field_list.rast
- crates/parser/test_data/parser/inline/ok/record_field_list.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
Safey check semantics can follow but this is the more important bit
> feat: parse `unsafe` record fields

- crates/base-db/src/change.rs
- crates/base-db/src/input.rs
- crates/ide-db/src/apply_change.rs
- crates/ide-db/src/lib.rs
The idea here is that the crate graph may change over time, but library source file contents *never* will (or really never should). Disconnecting the two means that queries that depend on library sources will not need to re-validatewhen the crate graph changes (unless they depend on the crate graph in some capacity).
> refactor: Use MEDIUM durability for crate-graph changes, high for library source files

- crates/proc-macro-srv/src/dylib.rs
- crates/proc-macro-srv/src/lib.rs
- crates/proc-macro-srv/src/proc_macros.rs
cc https://github.com/rust-lang/rust-analyzer/issues/19342
> refactor: Shuffle some unsafety around in proc-macro-srv

- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/tests.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19456
> fix: Fix `format_args` lowering using wrong integer suffix

- crates/hir-ty/src/method_resolution.rs
- crates/ide-diagnostics/src/handlers/trait_impl_orphan.rs
Where a fundamental type applied twice wasn't considered local.
We're going to get a full coherence checker for free with the next trait solver, so I don't want to invest in completing the current check, but this fix is simple enough and it can cause annoying red squiggles.
> fix: Fix a bug in orphan rules calculation

- crates/hir-def/src/data.rs
- crates/hir-def/src/data/adt.rs
- crates/hir-def/src/import_map.rs
- crates/hir-def/src/item_scope.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/lib.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/snippet.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/import_assets.rs
- crates/ide-db/src/items_locator.rs
- crates/ide-db/src/test_data/test_doc_alias.txt
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
- crates/intern/src/symbol/symbols.rs
Via the new `#[rust_analyzer::completions(...)]` attribute.
Closes https://github.com/rust-lang/rust-analyzer/issues/17477.
Also fix a bug with existing settings for that where the paths wouldn't resolve correctly. @Veykril it seems you just blessed the tests incorrectly in https://github.com/rust-lang/rust-analyzer/pull/18179?
> feat: Allow crate authors to control completion of their things

- .github/workflows/ci.yaml
The cache is still not working at all from what I can tell, I don't understand why
> chore: Clean CI a bit

- crates/rust-analyzer/src/cli/progress_report.rs
In the rare occasion that someone has added unicode characters that are multiple code points, the previous slicing operation could incorrectly split that character, and panic. The fix is to use the `chars()` iterator and just skip the prefix.
> fix: Fix panic in progress due to splitting unicode incorrectly

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/dyn_compatibility.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/mir/borrowck.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/monomorphization.rs
- crates/hir-ty/src/mir/pretty.rs
None of these require to be interned to be re-exposed as salsa structs
> chore: Replace some `invoke`s with `invoke_actual` in hir-ty

- crates/ide-assists/src/handlers/toggle_ignore.rs
- crates/ide-db/src/assists.rs
- crates/ide/src/lib.rs
- crates/proc-macro-srv/src/dylib/version.rs
- crates/rust-analyzer/src/lsp/from_proto.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
This was being used by a single assist, which qualifies under the "refactor" kind. The variant has been removed, and all usages updated accordingly.
> fix(ide-assists): remove `AssistKind::None`

- editors/code/language-configuration.json
> Fix color brackets in string context

- crates/hir-expand/src/lib.rs
- crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19489.
The main part of this this change is going from a `self.proc_macro_clients.is_empty()` check to a `self.proc_macro_clients.len() < self.workspaces.len()`. I also rewrote some iterator combinators in favor of two `for`  loops and two `match` statements because I had difficulty understanding the code.
> internal: ensure a Salsa-ified crate graph works with project discovery

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
A Cargo project can now be built without any dependency metadata being fetched. This classifies as a breaking change for the `ra_ap_project_model` public API, since we introduce a new field into the config struct, and a new configuration option for the analyzer.
Fixes #19518
> feat(project-model): provide flag for no deps

- crates/ide/src/doc_links.rs
equivalent to https://github.com/rust-lang/rust/pull/139405, not sure which one is the source of truth
> The rustdoc file prefix for constants is "constant" not "const"

- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/hir-def/src/macro_expansion_tests/mbe/regression.rs
- crates/ide/src/expand_macro.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/parser.rs
- crates/tt/src/iter.rs
- crates/tt/src/lib.rs
Specifically, #18744 was the PR that was supposed to fix the old bug, but it fixed it incorrectly (and didn't add a test!) The underlying reason was that we marked metavariables in expansions as joint if they were joint in the macro call, which is incorrect.
This wrong fix causes other bug, #19497, which this PR fixes by removing the old (incorrect) fix.
Fixes #19497.
> fix: Fix a bug in MBE expansion that arose from incorrect fixing of an older bug in MBE

- crates/ide-completion/src/completions/item_list.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/item.rs
- crates/ide-completion/src/tests/item_list.rs
- crates/ide-completion/src/tests/special.rs
> add more completion about "impl"

- crates/base-db/src/lib.rs
- crates/hir-def/src/expr_store/lower.rs
- crates/hir-ty/src/infer.rs
- crates/hir/src/diagnostics.rs
- crates/ide/src/lib.rs
- crates/intern/src/symbol/symbols.rs
- crates/project-model/src/workspace.rs
Closes https://github.com/rust-lang/rust-analyzer/issues/19456
There might be some 1.87 nightlies that are still broken but that we can't really fix unfortunately
> fix: Fix `format_args` lowering for >=1.87

- Cargo.lock
- crates/stdx/Cargo.toml
- crates/stdx/src/anymap.rs
- crates/stdx/src/lib.rs
- crates/stdx/src/non_empty_vec.rs
- crates/stdx/src/panic_context.rs
- crates/stdx/src/process.rs
- crates/stdx/src/rand.rs
- crates/stdx/src/thread.rs
- crates/stdx/src/thread/intent.rs
- crates/stdx/src/thread/pool.rs
I have some changes on my version of stdx that I figured I might as well PR back to r-a.
Let me know if there are things that you want me to undo.
Almost all of the changes come from following clippy lints which are not currently enabled in this workspace.
> Upstream stdx changes

- crates/hir-ty/src/infer/cast.rs
- crates/hir-ty/src/infer/unify.rs
- crates/ide-diagnostics/src/handlers/invalid_cast.rs
> fix: Yet another false positive invalid cast diagnostic

- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
The current notifications are quite verbose (as discussed in #19410), which
causes some arguably more useful information (like the documentation) to be
harder to see.
One option would just be to disable the option by default, but as proposed
there, it seems like a reasonable middle ground would be to show it but
significantly less verbosely.
This change reduces the amount of information shown (a direct `Drop` impl is
rendered the same way as the drop glue that calls `Drop` impls transitively),
but I don't know of a scenario where the difference is meaningful.
Closes #19410
> Tidy up drop glue notification

- crates/ide-assists/src/handlers/auto_import.rs
- crates/ide-assists/src/handlers/qualify_path.rs
- crates/ide-assists/src/handlers/term_search.rs
- crates/ide-assists/src/tests.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/context/tests.rs
- crates/ide-db/src/active_parameter.rs
- crates/ide/src/signature_help.rs
- crates/syntax/src/algo.rs
A very simple fix to make importing the correct `Ordering` enum less annoying.
> fix(auto-import): Prefer imports of matching types for argument lists

- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
We don't *need* this with chalk (though, I do wonder if this sidesteps rust-lang/chalk#688), but this is required for the next-solver integration.
~I haven't gone through this and done any "cleanups", this is just ripped straight from my next-solver branch.~
I think this is ready for review.
> Port closure inference from rustc

- crates/ide/src/children_modules.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/capabilities.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/book/src/contributing/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
> Add children modules feature

- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/lower/generics.rs
- crates/hir-def/src/expr_store/pretty.rs
- crates/hir-def/src/hir/type_ref.rs
- crates/hir-def/src/resolver.rs
- crates/hir-expand/src/name.rs
- crates/hir-ty/src/display.rs
- crates/hir/src/display.rs
This makes things more structured
> refactor: Turn `LifetimeRef` into an enum

- crates/ide/src/child_modules.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/lsp/capabilities.rs
- crates/rust-analyzer/src/lsp/ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/book/src/contributing/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
I think that "child modules" reads a bit more nicely than "children modules".
> internal: rename `children_modules` to `child_modules`

- crates/hir-def/src/signatures.rs
The tiny bug was that `FnFlags::DEPRECTAED_SAFE_2024` and `FnFlags::RUSTC_ALLOW_INCOHERENT_IMPLS` were assigned the same value.
The catastrophic effect was that every function marked as `#[rustc_allow_incoherent_impl]` was considered safe-deprecated for edition 2024, which caused it to be considered unsafe to call when called from edition 2024. And that includes `<[_]>::into_vec()`, which is called by the `vec![]` macro. So, catastrophic effect.
This innocent-looking bug probably arose from the item tree rewrite. No review would've catch that!
Fixes #19557.
> fix: Fix a small bug with catastrophic effects

- triagebot.toml
This PR enables two new triagebot feature `[canonicalize-issue-links]` and `[no-mentions]`.
Documentation at https://forge.rust-lang.org/triagebot/canonicalize-issue-links.html and https://forge.rust-lang.org/triagebot/no-mentions.html.
> Enable `[canonicalize-issue-links]` and `[no-mentions]` in triagebot

- crates/hir-def/src/resolver.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/lower/path.rs
- crates/hir/src/attrs.rs
- crates/hir/src/source_analyzer.rs
- crates/ide/src/goto_definition.rs
fix: https://github.com/rust-lang/rust-analyzer/issues/19107
> fix: shadow type by module

- crates/hir-def/src/expr_store/pretty.rs
- crates/hir-def/src/signatures.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/dyn_compatibility.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
There was more non-sense in here like the 0th bit being used and some other collisions, also re-orders some flags to use the same bits across differing flag types for the same flags which should give slightly better codegen (though I didn't try too much as its difficult to use the same bits for all of them)
> fix: Fix invalid signature bitflags

- crates/hir/src/display.rs
- crates/ide/src/hover/tests.rs
It caused panics everywhere.
Fixes rust-lang/rust-analyzer#19561.
> fix: Fix an incorrect `ExpressionStore` that was passed

- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/main_loop.rs
#19464
Test notifications with targets containing hyphens are failing with the error:
[error] [Window] [Extension Host] Notification handler 'experimental/changeTestState' failed with message: Cannot read properties of undefined (reading 'id')
The test id expects the namespace form with underscores `tokio_stream` instead of `tokio-stream`.
> Fix missing test update notifications when there are hyphens in the target name and exclude dependencies from `Run All`

- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/expr.rs
- crates/ide/src/inlay_hints.rs
We didn't include them in the sorted closures list, therefore didn't analyze them, then failed to find them.
Fixes rust-lang/rust-analyzer#19577.
> fix: Prevent panics when there is a cyclic dependency between closures

- .github/workflows/ci.yaml
The analysis-stats job takes ~12m to run. This will run even if the tests fail - it's wasted CI minutes. Instead, we can short-circuit the entire workflow if the tests fail.
> ci: cancel parallel jobs if test fails

- crates/ide-assists/src/handlers/convert_for_to_while_let.rs
- crates/ide-assists/src/handlers/convert_from_to_tryfrom.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-assists/src/handlers/remove_dbg.rs
- crates/ide-assists/src/handlers/replace_method_eager_lazy.rs
- crates/ide-assists/src/handlers/replace_try_expr_with_match.rs
- crates/ide-assists/src/utils.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
- crates/ide-assists/src/utils/ref_field_expr.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
Much nicer to work with now, less `unreachable!()`s in the syntax factory.
> fix(ast): return correct types for `make::expr_*` methods

- .github/workflows/release.yaml
- xtask/src/dist.rs
- xtask/src/flags.rs
Empirically this seems to make the resulting `analysis-stats` command ~20% faster.
> Distribute x64 and aarch64 Linux builds with PGO optimizations

- crates/ide-assists/src/handlers/expand_rest_pattern.rs
> refactor: migrate `expand_rest_pattern` to editor

- .github/workflows/release.yaml
Reverts a part of rust-lang/rust-analyzer#19582. PGO does not seem to work with `cargo zigbuild` (https://github.com/rust-lang/rust-analyzer/actions/runs/14448767429/job/40515878851).
> Do not perform PGO on Linux CI

- .github/workflows/release.yaml
- xtask/src/dist.rs
- xtask/src/flags.rs
This PR adds functionality to train PGO on a custom crate downloaded from GitHub (e.g. `--pgo clap-rs/clap`), and enables PGO for Windows on CI.
I added the functionality because training on itself produced OOMs on Windows CI.
I didn't enable PGO for `aarch64-pc-windows-msvc`, because there it's more complicated because of the cross-compilation.
If someone wants to test the performance effect, they could compare the following builds:
- PGO: https://github.com/rust-lang/rust-analyzer/actions/runs/14465225022
- No PGO: https://github.com/rust-lang/rust-analyzer/actions/runs/14458498119
Download and extract the `dist-x86_64-pc-windows-msvc` artifact, and then run `rust-analyzer.exe analysis-stats --run-all-ide-things <rust-analyzer-checkout-directory>`.
Related issue: …
> Allow training PGO on a custom crate and enable it Windows on CI

- .github/workflows/release.yaml
After https://github.com/rust-lang/rust-analyzer/pull/19586 it should be possible to do PGO on Linux.
> Use PGO on Linux x64 builds

- crates/hir-expand/src/proc_macro.rs
I just happened to come across this while investigating an error.
It looks like this comment was mistakenly copied from the function right above it. I'm happy to add a better comment if you like, but I think it's fairly clear from the function name and type signature.
> Remove incorrect doc comment

- crates/ide/src/signature_help.rs
fix rust-lang/rust-analyzer#12729, rust-lang/rust-analyzer#19373.
> feat: enhance signature help to display generic parameters for callables and default values for generic args

- crates/ide-diagnostics/src/handlers/unlinked_file.rs
fix rust-lang/rust-analyzer#19540.
> feat: add `pub(crate) mod` option for unlinked files

- .github/workflows/release.yaml
Uses the manylinux aarch64 image + a native ARM GitHub runner to compile aarch64 builds with PGO.
> Build aarch64 builds on CI with PGO

- crates/ide-assists/src/handlers/destructure_struct_binding.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
Fixes rust-lang/rust-analyzer#19584
> fix: use `ast::TokenTree` in `make::expr_macro`

- .github/workflows/release.yaml
- related to https://github.com/rust-lang/rust-analyzer/issues/9412#issuecomment-2810772246
> Use PGO on macOS x64 and arm64 builds

- crates/hir-ty/src/lower.rs
- crates/ide/src/inlay_hints.rs
The essence of the bug is that bounds on `impl Trait` got lowered with incorrect bound vars, as if we were lowering the parent.
Another bug from the item tree rewrite. Kind of expected, I think (I don't blame anyone!)
Fixes rust-lang/rust-analyzer#19610.
Somewhat ironically, finding & fixing the bug was almost less work than creating a test that fails in the previous version... (and understand the bug deeply, which is needed to create such test).
> fix: Fix a bug with predicate lowering of associated items

- crates/hir-ty/src/db.rs
That is, all queries that have a `with_diagnostic` variant.
Them being tracked was (maybe) needed before rust-lang/rust-analyzer#19462, because back then diagnostics could refer `AstId`s (for macro types), but now they are no longer needed.
> internal: Make hir-ty non-diagnostic queries transparent

- crates/ide/src/hover.rs
Previously it was ordered by what accidentally happened to be the crate graph order, which isn't sensible, plus it caused changes when any change was done to salsa IDs.
> fix: Sort notable traits in hover

- .github/workflows/release.yaml
- xtask/src/dist.rs
This should make the builds more reproducible.
> internal: Support specific revisions for PGO

- crates/hir/src/lib.rs
- crates/ide/src/hover/tests.rs
Shuffle the code a bit.
Fixes rust-lang/rust-analyzer#19607.
I'm not entirely sure what happens is correct - why don't the substitution contain a lifetime? but too tired to think.
> fix: Fix a panic when a trait method in an impl declares a lifetime parameter not in the trait declaration

- crates/rust-analyzer/src/config.rs
previously, these would just silently be ignored. now they give a warning such as:
```
invalid config values: /completion/snippets/custom: invalid type: null, expected a map; /cargo/extraEnv: invalid type: null, expected a string;
```
this also adds a semicolon between errors; previously it was hard to spot that this was actually two different warnings.
cc https://github.com/rust-lang/rust-analyzer/issues/19626
> don't ignore config values that fail to parse

- crates/hir-def/src/lang_item.rs
- crates/hir-def/src/signatures.rs
- crates/hir-ty/src/lang_items.rs
- crates/hir-ty/src/layout/adt.rs
- crates/intern/src/symbol/symbols.rs
cc https://github.com/rust-lang/rust/issues/125735
> fix: Support unstable `UnsafePinned` struct in type layout calc

- crates/parser/src/grammar/expressions.rs
- crates/parser/test_data/parser/inline/ok/let_stmt.rast
- crates/parser/test_data/parser/inline/ok/let_stmt.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19623
> feat: parse `super let`

- crates/load-cargo/src/lib.rs
- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-api/src/process.rs
- crates/project-model/src/build_dependencies.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/env.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/toolchain_info/rustc_cfg.rs
- crates/project-model/src/toolchain_info/target_data_layout.rs
- crates/project-model/src/toolchain_info/target_tuple.rs
- crates/project-model/src/toolchain_info/version.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/discover.rs
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/handlers/request.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/src/test_runner.rs
- crates/toolchain/src/lib.rs
this makes three changes:
- all callsites of `toolchain::command` are changed to use `command(path, extra_env)`, instead of manually adding the env after the fact.
- all `map<str, str>` are changed to `map<str, option<str>>`.
- `command` checks for None and calls `env_remove` if so.
this caught several places where environment variables weren't being propagated:
- when running `rustc --print=target-libdir`
- when running `cargo rustc -- --print=target-spec-json`
- when running the custom DiscoverLinkedProjects config. I *think* this is for use with non-cargo build systems, so I didn't change it.
i verified locally that this actually works.
fixes https://github.com/rust-lang/rust-analyzer/issues/19626
> allow using `null` to unset an environment variable

- crates/ide-completion/src/completions/item_list.rs
Fixes rust-lang/rust-analyzer#19601
> Add semicolon to use

- crates/ide-assists/src/handlers/raw_string.rs
- crates/ide-assists/src/handlers/replace_string_with_char.rs
- crates/ide-assists/src/utils.rs
Fixes rust-lang/rust-analyzer#19621 
Fixes rust-lang/rust-analyzer#19625
> Fix ide-assists raw_string suffix fail

- crates/hir-def/src/expr_store.rs
- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/lower/path.rs
- crates/hir-def/src/hir/generics.rs
- crates/hir-ty/src/builder.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/generics.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/diagnostics.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower/diagnostics.rs
- crates/hir-ty/src/lower/path.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/generic_args_prohibited.rs
- crates/ide-diagnostics/src/handlers/incorrect_generics_len.rs
- crates/ide-diagnostics/src/handlers/incorrect_generics_order.rs
- crates/ide-diagnostics/src/lib.rs
- crates/test-utils/src/minicore.rs
Also known as E0747 and E0107.
And by the way, rewrite how we lower generic arguments and deduplicate it between paths and method calls. The new version is taken almost straight from rustc.
This commit also changes the binders of `generic_defaults()`, to only include the binders of the arguments up to (and not including) the current argument. This make it easier to handle it in the rewritten lowering of generic args. It's also how rustc does it.
This is a step towards https://github.com/rust-lang/rust-analyzer/issues/17590, the next step will be to add a quickfix to the count mismatch diagnostic that adds new parameters. Since this became somewhat big I separated the steps.
> feat: Add two new diagnostics: one for mismatch in generic arguments count, and another for mismatch in their kind

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/goto_definition.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/test_data/generated/runner.rs
- crates/parser/test_data/parser/inline/ok/offset_of_parens.rast
- crates/parser/test_data/parser/inline/ok/offset_of_parens.rs
- crates/test-utils/src/minicore.rs
That is, support nested offset_of that previously failed to parse, and resolve it in IDE properly.
Closes rust-lang/rust-analyzer#18891.
> feat: Better support `offset_of!()`

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/closure_ret.rs
fix rust-lang/rust-analyzer#19646.
It's illegal to return `TextEdit::builder().finish()` here.
> fix: panics in inlay hints that produce empty text edits for closure return types

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower/path.rs
- crates/ide-diagnostics/src/handlers/incorrect_generics_len.rs
- crates/query-group-macro/src/queries.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19668
> fix: Fix incorrect diagnostic for lifetime parameter count mismatch

- crates/hir-def/src/hir/type_ref.rs
- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/diagnostics.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower/diagnostics.rs
- crates/hir-ty/src/lower/path.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-diagnostics/src/handlers/elided_lifetimes_in_path.rs
- crates/ide-diagnostics/src/handlers/missing_lifetime.rs
- crates/ide-diagnostics/src/lib.rs
And also, prepare for correct lowering of lifetime. We still don't handle most lifetimes correctly, but a bit more of the foundation to lifetime elision is now implemented.
This is the "proper" fix for rust-lang/rust-analyzer#19668. rust-lang/rust-analyzer#19672 fixed it in the "quick-and-dirty" way.
rustc does this all differently by inserting the lifetimes in late resolution (which is why my code originally did not work correctly). We can't do this. But I did follow rustc's late resolve closely when implementing this.
This also adds two new diagnostics.
> feat: Properly handle lifetimes when checking generic arguments len

- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/lower/asm.rs
- crates/hir-def/src/expr_store/lower/generics.rs
- crates/hir-def/src/expr_store/lower/path.rs
- crates/hir-def/src/expr_store/lower/path/tests.rs
- crates/hir-def/src/expr_store/pretty.rs
- crates/hir-def/src/hir/generics.rs
- crates/hir-def/src/signatures.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/display.rs
- crates/hir/src/source_analyzer.rs
Also cleans up the impl triat handling a bit, should allow making diagnostics for it easier in the future I think
> refactor: Remove `WherePredicateTypeTarget`

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/path.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower/path.rs
- crates/ide-diagnostics/src/handlers/incorrect_generics_len.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/19669
> fix: Fix type argument mismatch incorrectly triggering on inferred trait args

- crates/rust-analyzer/src/discover.rs
Currently we silently fail if the line can be parsed as json but not as `DiscoverProjectData`. That means if the discover command emits a malformed `DiscoverProjectData`, project discovery will never finish, and rust-analyzer becomes unusable. Instead, return an error if the line isn't a valid `DiscoverProjectData` so the discovery process fails and the error is correctly reported.
> Always error when failed to parse DiscoverProjectMessage

- Cargo.lock
- Cargo.toml
- crates/base-db/src/input.rs
- crates/cfg/src/lib.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/interner.rs
- crates/intern/src/lib.rs
- crates/intern/src/symbol.rs
- crates/intern/src/symbol/symbols.rs
- crates/span/src/ast_id.rs
My secret crystal ball told me there are places we still don't `shrink_to_fit()`. Well, almost a crystal ball. My crystal ball is the memory profiling I implemented for Salsa (very rudimentary right now, but I do plan to polish and release it). This saves 18mb. Speed doesn't regress.
Also packed with an upgrade to dashmap and hashbrown, because I thought this will be related (it won't). My crystal ball was wrong about this one, apparently.
> internal: More `shrink_to_fit()` and upgrade dashmap and hashbrown

- crates/parser/src/input.rs
- crates/parser/src/shortcuts.rs
- crates/syntax-bridge/src/to_parser_input.rs
This saves a whole lot 0.127 seconds in `rust-analyzer prime-caches .`!
> minor: Preallocate `parser::Input`

- crates/ide-assists/src/handlers/add_braces.rs
"to arm expression" is hard to parse, because "arm" can be a verb. Not all Rust users may know that "arm" refers to a `match` expression either.
Tweak the wording to make the sentence easier to parse, and clarify that this assist refers to `match`. Use the same wording style for the closure version too.
> Clarify text for add_braces assist

- crates/ide-assists/src/handlers/remove_underscore.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Addresses rust-lang/rust-analyzer#19631
This PR adds an assist that suggests removing any underscore prefixes from used variables.
> feat: adds an assist to remove underscores from used variables

- crates/ide-assists/src/handlers/merge_imports.rs
- crates/ide-assists/src/handlers/unmerge_imports.rs
- crates/ide-assists/src/handlers/unmerge_use.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
- crates/syntax/src/syntax_editor.rs
- crates/syntax/src/syntax_editor/edits.rs
Contributes to https://github.com/rust-lang/rust-analyzer/issues/18285, and supersedes https://github.com/rust-lang/rust-analyzer/pull/18484.
Needs rebase after rust-lang/rust-analyzer#19465 is merged.
cc @darichey again, thanks for the reviews!
> refactor: `merge_imports` and `unmerge_imports` to editor

- crates/ide-assists/src/handlers/add_missing_match_arms.rs
- crates/ide-assists/src/handlers/convert_let_else_to_match.rs
- crates/ide-assists/src/handlers/destructure_struct_binding.rs
- crates/ide-assists/src/handlers/expand_rest_pattern.rs
- crates/ide-assists/src/handlers/unmerge_match_arm.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
Oof this took a bunch of effort. But I'm much more familiar with the syntax editor after this!
> refactor: migrate `let_else_to_match` to editor

- crates/base-db/src/lib.rs
Someone reported another instance of https://github.com/rust-lang/rust-analyzer/issues/19406, but this time, only on startup. Adding some additional information to the panic.
> base-db: add more details to panic

- crates/hir-expand/src/name.rs
- crates/ide-completion/src/completions/lifetime.rs
- crates/ide-completion/src/tests/expression.rs
Fixes rust-lang/rust-analyzer#19694.
> fix: Escape raw names in labels properly

- xtask/src/dist.rs
- xtask/src/flags.rs
- xtask/src/install.rs
- xtask/src/main.rs
- xtask/src/pgo.rs
- xtask/src/util.rs
Enable PGO optimizations when installing rust-analyzer with the --pgo flag. This mirrors functionality recently merged in rust-lang/rust-analyzer#19582 in dist command, allowing developers to create optimized local builds.
Example:
cargo xtask install --server --pgo clap-rs/clap
PGO code has been extracted to a dedicated module for reuse.
> Add PGO support to install

- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/borrowck.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir-ty/src/mir/monomorphization.rs
- crates/hir-ty/src/mir/pretty.rs
- crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
> fix: Correct span info for mir::Operand

- crates/hir-ty/src/chalk_db.rs
- crates/hir-ty/src/tests/regression.rs
Fixes rust-lang/rust-analyzer#19730 
This slipped through the mesh of our test suite while chalk update for generic param order change.
> fix: Correct assoc ty bound var starting index

- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/tests/method_resolution.rs
Fixes rust-lang/rust-analyzer#19724 
Mimicked part of the method resolution logic of rustc and I think that we should move r-a's closer to rustc's (Maybe I'll do it later)
> fix: Implement mut to const ptr cast for method resolution

- crates/hir-def/src/lib.rs
- crates/hir-def/src/nameres/assoc.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/path_resolution.rs
- crates/hir-def/src/nameres/tests/mod_resolution.rs
- crates/hir-ty/src/tests/traits.rs
Noticed this while looking into trying to make trait item imports partially work (we can't without inlining the query after all).
This does add the relevant tests for trait assoc item imports though.
> fix: Fix incorrect handling of unresolved non-module imports in name resolution

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin/fn_macro.rs
Fixes: #19417
This PR provides a fix to the expansion of the `concat!` macro, where negative numbers give an `unexpected token` error.
```rust
pub const T: &str = concat!(-42.0);
```
expands to:
```rust
pub const T: &str = "-42.0"
```
> fix: negative nums in `concat!` expansion

- crates/ide-db/src/rename.rs
We should not find such results in our search impl anymore
> fix: Remove unnecessary token length check for macros in renaming

- crates/hir-def/src/expr_store/lower/path.rs
- crates/hir-ty/src/tests/simple.rs
Fixes rust-lang/rust-analyzer#19734.
> fix: Don't panic on some weird code

- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/expression.rs
Fixes rust-lang/rust-analyzer#19762.
This has always bothered me (especially because I tend to write `()` at the end of unfinished blocks, because the compiler's error marking the whole block red is very annoying), but I guess I needed someone else to complain about it to go and fix this.
> fix: Still complete parentheses & method call arguments if there are existing parentheses, but they are after a newline

- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/tests/expression.rs
Fixes rust-lang/rust-analyzer#19758.
I'm not entirely sure the `found_ref_or_deref` check is correct - I think maybe we should remove it - but removing it makes `let` postfix completions no longer appear (although I suspect this is because we check the grandparent instead of the parent).
> fix: Fix postfix snippets duplicating derefs

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-assists/src/handlers/remove_unused_imports.rs
fix: https://github.com/rust-lang/rust-analyzer/issues/19119
https://github.com/user-attachments/assets/318712ce-c27c-4de2-872a-9fd09314e767
> fix: Removing all unused imports removes used imports for imports used for Derive macros

- Cargo.lock
- crates/base-db/Cargo.toml
- crates/base-db/src/input.rs
For some reason we had them in some projects, I'm not sure why. But this caused cache priming to appear stuck - because it uses a set of crate IDs for the actual work, but for the number of crates to index it just uses `db.all_crates().len()`.
Fixes rust-lang/rust-analyzer#19790.
> fix: Don't allow duplicate crates in the all_crates list

- crates/hir-def/src/expr_store.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/macros.rs
- crates/hir-ty/src/tests/simple.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/test_data/generated/runner.rs
- crates/parser/test_data/parser/inline/ok/asm_label.rast
- crates/parser/test_data/parser/inline/ok/asm_label.rs
Including:
- Infer `label {}` and `const` operands.
- Correctly handle unsafe check inside `label {}`.
- Fix an embarrassing parser typo that cause labels to never be part of the AST
Our story began when I saw, in the release notes for Rust 1.87, that `label {}` in inline assembly was stabilized, and recalled that I read that the lang team decided that `label {}` blocks will start a new safety scope. Quick glance at the reference, yep that rule is there. Trying to check whether we comply to it in r-a, no we don't. Fixing is simple - unless, as it turns out, we don't support `label` almost at all (+ `const`), including a very funny parser typo.
> fix: Improve asm support

- Cargo.lock
- xtask/Cargo.toml
This makes `cargo outdated` happy.
> minor: Bump zip to 3.0

- .github/workflows/metrics.yaml
This way we can catch regressions from upstream earlier
> ci: Run metrics on the beta channel

- crates/ide/src/highlight_related.rs
close https://github.com/rust-lang/rust-analyzer/issues/19467
> feat: highlight unsafe operations

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/op_queue.rs
- crates/rust-analyzer/src/reload.rs
Potential solution for https://github.com/rust-lang/rust-analyzer/issues/19729
> Debounce workspace fetching for workspace structure changes

- crates/rust-analyzer/src/integrated_benchmarks.rs
Noticed this issue at RustWeek when attempting to run these benchmarks. `struct_data` doesn't exist anymore; it's been replaced by `struct_signature`.
> internal: fix `integrated_benchmarks` to make actual edits

- crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs
- crates/proc-macro-srv/src/server_impl/token_id.rs
- crates/proc-macro-srv/src/server_impl/token_stream.rs
- crates/proc-macro-srv/src/tests/mod.rs
Previously only the open delimiter's span was set, and this caused... weird problems.
Probably fixes (don't close!) rust-lang/rust-analyzer#18471, and possibly also rust-lang/rust-analyzer#19834. The problem is that we only had the span of the closing parentheses of the call, and for descending attributes we look at the first and last token, but we couldn't find the last token (the closing paren) in the macro. However, there could be other problems too, so I don't want to close them yet before we verify it works (it's hard to test proc macro server changes).
Perhaps it's worth reconsidering our strategy for descending into attribute macros, especially given that when users create their own `Group`s they have no way of setting each delimiter span separately, only for both.
> fix: Correctly set the span of the proc_macro crate's Group delimiters

- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide-diagnostics/src/lib.rs
Fixes rust-lang/rust-analyzer#19823.
I knew this cache will cause us problems.
I question the need for a cache (yep, I authored this code, I know). When there is no cache there are no cache problems. And we all know what the hardest problems in computer science are. This code was just needlessly complex.
Ideally I believe we would have lint levels defined as db queries and query them *before* firing the lints. Unfortunately in rustc lint levels are tied with spans, which can be arbitrary pieces of code, and we can't implement something like that for our hir. So we're stuck with AST-based lint resolution (which isn't *that* bad, actually).
> fix: Fix cache problems with lints level

- docs/book/src/other_editors.md
I am removing this extension in my capacity as a rust-lang moderator as there are CoC violations related to it. If you would like to know more about this, please contact me at rust-mods@rust-lang.org
> Remove rust-analyzer.vs from other editors

- crates/hir/src/semantics.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-db/src/search.rs
- crates/ide-ssr/src/lib.rs
- crates/ide-ssr/src/search.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/highlight_related.rs
And rename it to `is_inside_macro_call()` accordingly.
Should fix rust-lang/rust-analyzer#19863.
> fix: Properly implement `might_be_inside_macro_call()` using semantic information instead of syntactical hacks

- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
- crates/hir-ty/src/inhabitedness.rs
- crates/hir-ty/src/mir/lower.rs
- crates/ide-diagnostics/src/handlers/non_exhaustive_let.rs
Fixes rust-lang/rust-analyzer#19848.
> fix: Normalize when checking for uninhabited types for pattern exhaustiveness checking

- crates/ide-assists/src/handlers/generate_new.rs
Fixes rust-lang/rust-analyzer#19784
> fixes: ide-assists, generate_new indent loses

- crates/hir-def/src/db.rs
- crates/hir-def/src/resolver.rs
- crates/hir-expand/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide-completion/src/tests/item.rs
It wasn't inside the source map, because there was no source map.
Fixes rust-lang/rust-analyzer#19860.
This regressed in the item tree refactor. I'm not sure why it switched to the code to lookup in maps instead of relower the macro but I preserved that (CC @Veykril).
> fix: Fix IDE resolution of item macros

- crates/hir-ty/src/diagnostics/expr.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
Fixes rust-lang/rust-analyzer#19844
Playing with tracings on rustc, I found that it never enters `rustc_pattern_analysis` if there exists any typecheck error inside the given body:
- [Entrypoint for pattern analysis](https://github.com/rust-lang/rust/blob/45f256d9d7cffb66185c0bf1b8a864cba79db90c/compiler/rustc_mir_build/src/thir/pattern/check_match.rs#L52)
- [Short circuit on `tcx.thir_body()?`](https://github.com/rust-lang/rust/blob/45f256d9d7cffb66185c0bf1b8a864cba79db90c/compiler/rustc_mir_build/src/thir/pattern/check_match.rs#L36)
- [`tcx.thir_body()` implementation](https://github.com/rust-lang/rust/blob/45f256d9d7cffb66185c0bf1b8a864cba79db90c/compiler/rustc_mir_build/src/thir/cx/mod.rs#L27-L29)
We've been doing simillar "skip on type-error" things on the following lines: …
> fix: Skip pattern analysis on type mismatches

- crates/hir-def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir-expand/src/builtin/fn_macro.rs
- crates/intern/src/symbol/symbols.rs
`concat_idents!` was deprecated in [1] and will be removed in the near future. rust-analyzer's support is independent of rustc's, so drop RA support now to make syncing easier.
[1]: https://github.com/rust-lang/rust/pull/137653
> chore: Remove support for `concat_idents!`

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- docs/book/src/non_cargo_based_projects.md
The Rust source code previously mised ProjectJson and JsonProject, and the TypeScript definition didn't match either.
Use 'ProjectJson' everywhere. This is purely an internal change.
> internal: Use 'ProjectJson' consistently

- crates/hir-ty/src/db.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/tests/regression.rs
Fixes rust-lang/rust-analyzer#19887
> fix: Cycle handlers for `HirDatabase::infer, const_param_ty_with_diagnostics`

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir/src/diagnostics.rs
- crates/ide-assists/src/handlers/fix_visibility.rs
- crates/ide-diagnostics/src/handlers/no_such_field.rs
If you have a struct with a private field
```
struct S {
bar: u32,
}
```
and you try to use it elsewhere
```
let s = S {
bar: 100,
};
```
rust-analyzer will now offer a fix to make the field `pub`, or `pub(crate)`, so that it is visible from the place you're trying to use it from.
> Add a quickfix for accessing a private field of a struct

- .github/workflows/publish-libs.yaml
Might fix (or not) rust-lang/rust-analyzer#19903
All the other conditions - our workspace structure, cargo or rustc version - are same as before (last release on May 26th) but `cargo-workspaces` has released a new version last week and I think there would be some regression there
> ci: Pin `cargo-workspaces` to `0.3.6`

- .github/workflows/autopublish.yaml
- .github/workflows/publish-libs.yaml
c.c rust-lang/rust-analyzer#19903
> ci: When autopublishing, remove `xtask` from workspace

- .github/workflows/autopublish.yaml
Sorry for consecutive mistakes in PRs 😢
> fix: Typo mistake in CI

- .github/workflows/autopublish.yaml
- .github/workflows/publish-libs.yaml
> ci: Pin `cargo-workspaces` version to `0.3.6`, again

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
As reported in https://github.com/rust-lang/rust-analyzer/pull/19772#issuecomment-2946889876.
> fix: Always include quickfixes for diagnostics, even when diagnostics are disabled

- crates/hir/src/semantics/child_by_source.rs
- crates/ide/src/expand_macro.rs
- crates/rust-analyzer/tests/slow-tests/ratoml.rs
https://github.com/rust-lang/rust-analyzer/pull/19932#issuecomment-2945342263
> fix: Record macro calls for fields in `ChildBySource` impls

- crates/ide-diagnostics/src/handlers/json_is_not_rust.rs
We probably should go more systematically over the diagnostics and figure what we can stabilize.
> fix: Stabilize the "JSON is not Rust" diagnostic

- crates/hir/src/semantics.rs
(This is a follow-up for https://github.com/rust-lang/rust-analyzer/pull/19850)
@ChayimFriedman2 it looks like I was a bit too quick trusting the suggested fix of just replacing `DB` with `DB: ?Sized`: it doesn't work, the `Semantics<'_, dyn HirDatabase>` isn't actually constructible.
I only did a quick type-level check like this on the previous PR, following your change request, which compiled just fine:
```rust
fn dummy(db: &'_ dyn HirDatabase) -> Semantics<'_, dyn HirDatabase> {
todo!()
}
```
But replacing `todo!()` with `Semantics::new(db)` would have quickly shown that a couple of `impl`s would require `DB: ?Sized` as well (iirc I had those initially, but clippy complained about them being unnecessary, so I removed them).
That said: even with those fixed, the "just change `DB` to …
> Make `Semantics<'db, DB>` support `Semantics<'db, dyn HirDatabase>`, take two

- crates/proc-macro-srv/proc-macro-test/imp/src/lib.rs
- crates/proc-macro-srv/src/server_impl.rs
- crates/proc-macro-srv/src/tests/mod.rs
It used to decompose them thinking they were numbers.
This arose from rust-lang/rust-analyzer#19746.
Fixes rust-lang/rust-analyzer#19965 (I checked it is indeed fixed, but this will have to wait for a sync).
> fix: Fix proc macro server handling of strings with minuses

- crates/hir-expand/src/db.rs
- crates/hir/src/semantics.rs
We had two bugs wrt. it.
Now this should *really* fix rust-lang/rust-analyzer#19863 (I tested this time).
> fix: Fix completion with some attribute macros

- crates/proc-macro-api/src/legacy_protocol/msg.rs
- crates/proc-macro-api/src/lib.rs
- crates/proc-macro-api/src/process.rs
- crates/proc-macro-srv-cli/src/main_loop.rs
- crates/proc-macro-srv/src/dylib.rs
- crates/proc-macro-srv/src/lib.rs
- crates/proc-macro-srv/src/proc_macros.rs
- crates/proc-macro-srv/src/server_impl/rust_analyzer_span.rs
- crates/proc-macro-srv/src/tests/utils.rs
- crates/span/src/ast_id.rs
The only thing changed is the value of the fixup ast id, so we just swap it.
As @Veykril suggested in rust-lang/rust-analyzer#19837.
This brings unknown types back to normal.
> fix: Support spans with proc macro servers from before the ast id changes

- docs/book/src/contributing/README.md
> Fix link to good first issues

- crates/hir-def/src/attr.rs
- crates/hir-def/src/db.rs
- crates/hir-def/src/item_tree.rs
- crates/hir-def/src/item_tree/lower.rs
- crates/hir-def/src/item_tree/pretty.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/tests/incremental.rs
- crates/hir-ty/src/tests/incremental.rs
- crates/intern/src/symbol.rs
Follow up to https://github.com/rust-lang/rust-analyzer/pull/19837, closes https://github.com/rust-lang/rust-analyzer/issues/9023
There is a bunch of things in the item tree we can replace now as item tree ids are superfluous, we can just replace them with an ast id mapping.
> Simplify and optimize `ItemTree`

- crates/hir-def/src/item_scope.rs
We never query their length here anyways, and `ItemScope` is massive already. Reducing its size is quite beneficial for block def maps
> Use `ThinVec` in `ItemScope` in a couple places

- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/mir/eval/shim.rs
See https://github.com/rust-lang/rust/pull/142410
cc @RalfJung
> remove `pref_align_of` intrinsic handling, rename `{min_=>}align_of{,_val}`

- crates/hir/src/symbols.rs
- crates/ide-db/src/symbol_index.rs
- crates/ide-db/src/test_data/test_doc_alias.txt
- crates/ide-db/src/test_data/test_symbol_index_collection.txt
- crates/ide-db/src/test_data/test_symbols_exclude_imports.txt
- crates/ide-db/src/test_data/test_symbols_with_imports.txt
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers/request.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
This implements the feature proposed in https://github.com/rust-lang/rust-analyzer/issues/19976
> Add support for excluding imports from symbol search

- crates/ide/src/lib.rs
- crates/ide/src/typing.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/lsp/capabilities.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
That is, `&dyn A$0` -> `&(dyn A +$0)` for refs, ptrs and return types (both for `dyn` and `impl` types) as without the parens it would be a parse error
> feat: Insert required parentheses when typing `+` in dyn trait type

- crates/ide-diagnostics/src/handlers/no_such_field.rs
- crates/ide-diagnostics/src/handlers/private_field.rs
The difference between the diagnostics is that no-such-field is for record struct construction, while private-field is for dot syntax.
I tried to unify them, but there is a bit of uniqueness in each. This is possible but maybe not worth it.
Also, fix the quickfix when there is already a visibility to the field (replace it instead of appending to it).
> feat: Add the quickfix for increasing visibility of a private field to the private-field diagnostic (previously it was only on no-such-field)

- crates/ide-diagnostics/src/handlers/type_mismatch.rs
We show fixes now even for experimental diagnostics anyway, and it has false positives.
Fixes rust-lang/rust-analyzer#20021.
> fix: Never make type mismatch diagnostic stable, even when there is a fix

- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/tests/closure_captures.rs
- crates/ide-diagnostics/src/handlers/moved_out_of_ref.rs
Fixes rust-lang/rust-analyzer#18201
We have been handling closure captures for let expressions in a wrong way: 
Here,
https://github.com/rust-lang/rust-analyzer/blob/6807f60ccd74f341f6e7c830ab5d9d0c27ae9dc2/crates/hir-ty/src/infer/closure.rs#L1237-L1241
which ends up as a capture by value if the captured target is not `Copy`
https://github.com/rust-lang/rust-analyzer/blob/6807f60ccd74f341f6e7c830ab5d9d0c27ae9dc2/crates/hir-ty/src/infer/closure.rs#L1034-L1051
But rustc handles this as a capture by ref(immutable, in most cases) in the following lines:
https://github.com/rust-lang/rust/blob/6f935a044d1ddeb6160494a6320d008d7c311aef/compiler/rustc_hir_typeck/src/expr_use_visitor.rs#L452-L454
https://github.com/rust-lang/rust/blob/6f935a044d1ddeb6160494a6320d008d7c311aef/compiler/rustc_hir_typec …
> fix: Closure capturing for let exprs

- crates/hir-def/src/db.rs
- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/tests/body/block.rs
- crates/hir-def/src/lib.rs
- crates/ide-completion/src/completions/postfix.rs
This reverts commit 8643a858dbaf12b37e90b603cdee64434576c229.
Fixes https://github.com/rust-lang/rust-analyzer/issues/20019
> Revert "Turn `BlockId` into a `#[salsa::tracked]`"

- crates/hir/src/lib.rs
Currently you have to do `param.merge().parent(db)` for `TypeParam`, which slightly less ergonomic, but most importantly it requires you to be aware of the available detour via `TypeOrConstParam`.
With its sibling `ConstParam` you can already do `param.parent(db)`. Now with `TypeParam` you can, too.
> Add `fn parent(self, db) -> GenericDef` to `hir::TypeParam`

- crates/project-model/src/build_dependencies.rs
rust-lang/cargo#15674 has been merged and I guess it would be available in toolchain `1.90.0`
I've tested this on rust-analyzer itself with cargo binary built from current master with the following my rust-analyzer branch
https://github.com/ShoyuVanilla/rust-analyzer/tree/comp-time-deps-test
and these are the results (I had run `cargo clean` before each run and modified the code a bit to use `--compile-time-deps` with injected cargo binary path iff env var `$CARGO_BIN_FOR_TEST` is set)
|   | **`analysis-stat` results** | **Time** | **`target` dir size** |
| - | - | - | - |
| **`--compile-time-deps`**  | Identical | 2m 25s | 347 M |
| **default**  | Identical | 2m 55s | 1.4 G |
> internal: Utilize `cargo check --compile-time-deps`

- crates/rust-analyzer/src/config.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
This should make the option less confusing.
@joshka do you think this documentation is good?
> Add better documentation for excluding imports from symbol search

- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/tests/body.rs
- crates/ide-assists/src/handlers/term_search.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/intern/src/symbol/symbols.rs
- crates/test-utils/src/fixture.rs
- crates/test-utils/src/minicore.rs
Fixes rust-lang/rust-analyzer#19929 and fixes rust-lang/rust-analyzer#20051
> Minic rustc's new `format_args!` expansion

- crates/project-model/src/workspace.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/20067
> fix: Fix cargo project manifest not pointing to the workspace root

- crates/project-model/src/env.rs
- crates/project-model/src/workspace.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/20070
> fix: Respect `.cargo/config.toml` `build.target-dir`

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/tests/coercion.rs
- crates/hir-ty/src/tests/display_source_code.rs
- crates/hir-ty/src/tests/method_resolution.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir-ty/src/tests/simple.rs
- crates/hir-ty/src/tests/traits.rs
- crates/ide-completion/src/tests/type_pos.rs
- crates/ide-diagnostics/src/handlers/type_mismatch.rs
- crates/ide/src/inlay_hints/bind_pat.rs
- crates/ide/src/inlay_hints/closing_brace.rs
- crates/project-model/src/workspace.rs
We lack trait object default lifetime elision, so `'static` can be wrong at times, confusing the user
> Do not default to 'static for trait object lifetimes

- Cargo.lock
- Cargo.toml
- crates/hir-expand/src/attrs.rs
- crates/hir-expand/src/builtin/fn_macro.rs
- crates/ide/src/goto_type_definition.rs
- crates/parser/src/lexed_str.rs
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/validation.rs
Port of https://github.com/rust-lang/rust/pull/140999.
> Update to literal-escaper 0.0.4

- crates/rust-analyzer/src/handlers/request.rs
Closes rust-lang/rust-analyzer#20093
I can't actually reproduce rust-lang/rust-analyzer#20095 because there's no notification for me even without enabling DND.
> internal: Don't show notifications on failed rustfmt calls

- crates/project-model/src/build_dependencies.rs
I originally thought that new `cargo` with `--compile-time-deps` is coming with toolchain version `1.90.0`, as `rust-lang/rust`'s `cargo` submodule hasn't been updated to that version by the date written [here](https://releases.rs/docs/1.89.0/):
But surprisingly, [it has been included to `1.89.0` milestone and beta branch](https://github.com/rust-lang/rust/pull/142898)
> minor: Decrease minimal toolchain version for `comp-time-deps` to `1.89.0`

- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/parser/inline/ok/type_param_bounds.rast
- crates/parser/test_data/parser/inline/ok/type_param_bounds.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
- crates/test-utils/src/minicore.rs
cc https://github.com/rust-lang/rust/pull/139858#issuecomment-3005310132
> Parse new const trait syntax

- crates/hir-def/src/lang_item.rs
- crates/hir-ty/src/lower.rs
- crates/ide-assists/src/handlers/generate_enum_is_method.rs
- crates/ide-assists/src/handlers/generate_enum_projection_method.rs
- crates/ide/src/inlay_hints/bounds.rs
- crates/intern/src/symbol/symbols.rs
- crates/test-utils/src/minicore.rs
Not an ideal approach but this quickly mitigates rust-lang/rust-analyzer#20090 as [we discussed on zulip](https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/rustc's.20new.20Sized.20Hierarchy.3A.20Part.20I/near/525687125)[#t-compiler/rust-analyzer > rustc's new Sized Hierarchy: Part I @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/rustc's.20new.20Sized.20Hierarchy.3A.20Part.20I/near/525687125)
> Backport new sized-hierarchy trait bounds in old ways

- crates/hir/src/lib.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/expression.rs
It should show integer, not floating point methods.
I always assumed we have `receiver_is_ambiguous_float_literal` to handle that, but apparently it's only used for some snippet stuff.
Fixes rust-lang/rust-analyzer#19855.
> fix: Fix completion in when typing `integer.|`

- crates/ide-assists/src/handlers/toggle_macro_delimiter.rs
> Migrate `toggle_macro_delimiter` Assist to use `SyntaxEditor`

- crates/ide/src/doc_links.rs
- crates/ide/src/hover/tests.rs
That is, do it for `[macro foo]`, but not for `[macro foo](macro foo)`.
Fixes rust-lang/rust-analyzer#20139.
> fix: Remove keyword prefixes (`macro@` or `macro `) from links in the docs only if the link target is inferred

- crates/load-cargo/src/lib.rs
See code comment for motivation:
```rust
pub fn load_workspace(
ws: ProjectWorkspace,
extra_env: &FxHashMap<String, Option<String>>,
load_config: &LoadCargoConfig,
) -> anyhow::Result<(RootDatabase, vfs::Vfs, Option<ProcMacroClient>)> {
let lru_cap = std::env::var("RA_LRU_CAP").ok().and_then(|it| it.parse::<u16>().ok());
let mut db = RootDatabase::new(lru_cap);
let (vfs, proc_macro_server) = load_workspace_into_db(ws, extra_env, load_config, &mut db)?;
Ok((db, vfs, proc_macro_server))
}
// This variant of `load_workspace` allows deferring the loading of rust-analyzer
// into an existing database, which is useful in certain third-party scenarios,
// now that `salsa` supports extending foreign databases (e.g. `RootDatabase`).
pub fn load_workspace_into_db(
ws: ProjectWorkspace,
extra_env: …
```
> Add `fn load_workspace_into_db` variant for `ra_ap_load_cargo`'s `fn load_workspace`

- crates/hir-def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir-expand/src/builtin/derive_macro.rs
- crates/ide-completion/src/tests/attribute.rs
- crates/test-utils/src/fixture.rs
- crates/test-utils/src/minicore.rs
1. Err on unions on derive where it's required.
2. Err on `#[derive(Default)]` on enums without `#[default]` variant.
3. Don't add where bounds `T: Default` when expanding `Default` on enums (structs need that, enums not).
Also, because I was annoyed by that, in minicore, add a way to filter on multiple flags in the line-filter (`// :`). This is required for the `Debug` and `Hash` derives, because the derive should be in the prelude but the trait not.
Fixes rust-lang/rust-analyzer#20166.
> fix: Fix some things with builtin derives

- crates/ide-assists/src/handlers/unmerge_match_arm.rs
> Migrate `unmerge_match_arm` Assist to use `SyntaxEditor`

- crates/project-model/src/sysroot.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/cli/rustc_tests.rs
Might mitigate rust-lang/rust-analyzer#20143
> fix: Honor `rust-analyzer.cargo.noDeps` option when fetching sysroot metadata

- docs/book/src/contributing/lsp-extensions.md
the method `rust-analyzer/syntaxTree` has been removed by rust-lang/rust-analyzer#18813, yet the book still lists it as available. this PR simply removes it from the book.
> remove `rust-analyzer/syntaxTree` from docs

- crates/hir-ty/src/diagnostics/match_check.rs
- crates/hir-ty/src/diagnostics/match_check/pat_analysis.rs
As of rust-lang/rust#143414, as part of transitioning away from box patterns and towards more general deref patterns (rust-lang/rust#87121), box patterns are now represented in terms of deref patterns in the THIR and in match checking. 
It doesn't seem like box patterns were lowered to the `match_check` IR to begin with though, so the handling of box patterns in `match_check` was dead code. Since it doesn't match with the compiler anymore and it wasn't used, I've removed it in this PR without replacement.
Once rust-lang/rust#143472 (or some successor thereof) is merged, it should be possible to properly implement `match_check` for deref patterns in rust-analyzer as well. I'd be happy to try doing so once syntax for deref patterns is sorted out.
> `hir_ty::match_check` cleanup: remove special handling for box patterns

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/never_type.rs
They need to return `!`, unlike diverging ordinary assignments. See the comment in the code.
Fixes rust-lang/rust-analyzer#20176.
> fix: Fix diverging destructuring assignments

- crates/rust-analyzer/src/main_loop.rs
Previously, the following configuration in settings.json:
"rust-analyzer.workspace.discoverConfig": {
"command": [
"oops",
"develop-json",
"{arg}"
],
"progressLabel": "rust-analyzer",
"filesToWatch": [
"BUCK",
"TARGETS"
]
},
Would previously cause a crash in rust-analyzer:
thread 'LspServer' panicked at crates/rust-analyzer/src/main_loop.rs:776:84:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
Instead, use more specific panic messages.
> fix: Avoid .unwrap() when running the discover command

- crates/hir-expand/src/name.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/variance.rs
Reverts rust-lang/rust-analyzer#20157.
Variance still causes problems.
Fixes rust-lang/rust-analyzer#20199.
> Revert "Re-enable fixpoint iteration for variance computation"

- crates/ide/src/inlay_hints/implied_dyn_trait.rs
- Fix their place when there are parentheses.
- Don't show them for HRTB bounds.
Fixes rust-lang/rust-analyzer#20202.
Although frankly, I'd rather rip them from the codebase.
> fix: Fixes for `dyn` inlay hint

- crates/ide/src/folding_ranges.rs
- crates/rust-analyzer/src/lsp/to_proto.rs
It would be convenient to just one-click fold arg list and func body(TypeScript does). However, this behavior is inconsistent with now, perhaps we need a configurable setting that allows users to customize it?
close https://github.com/rust-lang/rust-analyzer/issues/19299
> feat: support folding multiline arg list & fn body in one folding range

- crates/hir-ty/src/display.rs
Fixes rust-lang/rust-analyzer#20227.
> fix: Fix display of `use<>` syntax

- crates/hir-def/src/expr_store.rs
- crates/hir-def/src/expr_store/body.rs
- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/lower/asm.rs
- crates/hir-def/src/expr_store/lower/path/tests.rs
- crates/hir-def/src/expr_store/pretty.rs
- crates/hir-def/src/expr_store/scope.rs
- crates/hir-def/src/expr_store/tests/body.rs
- crates/hir-def/src/signatures.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/diagnostics/decl_check.rs
- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check.rs
- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/hir-ty/src/infer/mutability.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/layout/tests.rs
- crates/hir-ty/src/mir.rs
- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/as_place.rs
- crates/hir-ty/src/mir/lower/pattern_matching.rs
- crates/hir-ty/src/mir/pretty.rs
- crates/hir-ty/src/tests.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide/src/inlay_hints/implicit_drop.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
And leave only the type stuff without it.
This is because most expression stores don't have anything but types (e.g. generics, fields, signatures) so this saves a lot of memory.
This saves 58mb on `analysis-stats .`.
> perf: Put the expression stuff in the expression store behind an `Option<Box>`

- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/tests/item_list.rs
**Code**:
```rust
trait Foo {
type X<'a> where Self: 'a;
}
impl Foo for () {
$0
}
```
**Current**:
```rust
trait Foo {
type X<'a> where Self: 'a;
}
impl Foo for () {
type X<'a> where Self: 'a = $0;
}
```
**This pr fixed**:
```rust
trait Foo {
type X<'a> where Self: 'a;
}
impl Foo for () {
type X<'a> = $0 where Self: 'a;
}
```
> Fix assoc type where clause position

- crates/ide-assists/src/handlers/generate_default_from_new.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/edit_in_place.rs
follow up https://github.com/rust-lang/rust-analyzer/pull/20223
> Remove `ConstParam::remove_default` and `TypeParam::remove_default` to migrate from ted

- crates/ide-assists/src/handlers/generate_mut_trait_impl.rs
- AsRef -> AsMut
- Borrow -> BorrowMut
Example
====================
```rust
//- minicore: as_ref
struct Foo(i32);
impl core::convert::AsRef$0<i32> for Foo {
fn as_ref(&self) -> &i32 {
&self.0
}
}
```
->
```rust
struct Foo(i32);
$0impl core::convert::AsMut<i32> for Foo {
fn as_mut(&mut self) -> &mut i32 {
&self.0
}
}
impl core::convert::AsRef<i32> for Foo {
fn as_ref(&self) -> &i32 {
&self.0
}
}
```
> Add AsRef and Borrow for generate_mut_trait_impl

- crates/ide-assists/src/handlers/generate_deref.rs
- crates/ide-assists/src/utils.rs
```rust
struct Foo<T>($0T);
```
Current output:
```rust
struct Foo<T>(T);
impl<T: std::ops::Deref> std::ops::Deref for Foo<T> {
type Target = T;
fn deref(&self) -> &Self::Target {
&self.0
}
}
```
This PR fixed output:
```rust
struct Foo<T>(T);
impl<T> std::ops::Deref for Foo<T> {
type Target = T;
fn deref(&self) -> &Self::Target {
&self.0
}
}
```
> Fix ide-assist: generate Deref transitive

- crates/ide-assists/src/handlers/generate_mut_trait_impl.rs
- crates/ide-assists/src/handlers/generate_new.rs
- crates/ide-assists/src/utils.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/syntax_editor.rs
> Migrate `generate new` assist to use `SyntaxEditor`

- crates/ide-assists/src/handlers/convert_bool_then.rs
- crates/ide-assists/src/handlers/convert_to_guarded_return.rs
- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/utils.rs
- crates/ide-assists/src/utils/gen_trait_fn_body.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/syntax_factory.rs
https://github.com/rust-lang/rust-analyzer/pull/20224#issuecomment-3061091923
make mapping Indented node with original node.
> Migrate AstNodeEdit::Indent to SyntaxEditor

- crates/hir-def/src/expr_store/lower.rs
- crates/hir-def/src/expr_store/lower/generics.rs
- crates/ide/src/inlay_hints/lifetime.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/src/grammar/generic_params.rs
- crates/parser/src/grammar/types.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/parser/test_data/generated/runner.rs
- crates/parser/test_data/parser/err/0024_many_type_parens.rast
- crates/parser/test_data/parser/err/0027_incomplete_where_for.rast
- crates/parser/test_data/parser/err/0043_unexpected_for_type.rast
- crates/parser/test_data/parser/inline/ok/closure_binder.rast
- crates/parser/test_data/parser/inline/ok/dyn_trait_type_weak.rast
- crates/parser/test_data/parser/inline/ok/for_binder_bound.rast
- crates/parser/test_data/parser/inline/ok/for_binder_bound.rs
- crates/parser/test_data/parser/inline/ok/for_type.rast
- crates/parser/test_data/parser/inline/ok/lambda_expr.rast
- crates/parser/test_data/parser/inline/ok/maybe_const_trait_bound.rast
- crates/parser/test_data/parser/inline/ok/maybe_const_trait_bound.rs
- crates/parser/test_data/parser/inline/ok/no_dyn_trait_leading_for.rast
- crates/parser/test_data/parser/inline/ok/question_for_type_trait_bound.rast
- crates/parser/test_data/parser/inline/ok/where_pred_for.rast
- crates/parser/test_data/parser/ok/0032_where_for.rast
- crates/parser/test_data/parser/ok/0067_where_for_pred.rast
- crates/syntax/rust.ungram
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
And also refactor parsing of HRTB.
Fixes rust-lang/rust-analyzer#20276.
> fix: Parse `for<'a> [const]`

- Cargo.lock
The dependency of `xtask` on `time` was mistakenly removed.
> minor: Fix Cargo.lock

- crates/ide-assists/src/handlers/generate_trait_from_impl.rs
Input:
```rust
struct Foo;
impl F$0oo {
pub fn a_func() -> Option<()> {
Some(())
}
}
```
Old:
```rust
struct Foo;
trait NewTrait {
fn a_func() -> Option<()>;
}
impl NewTrait for Foo {
fn a_func() -> Option<()> {
Some(())
}
}
```
This PR fixed:
```rust
struct Foo;
trait NewTrait {
fn a_func() -> Option<()>;
}
impl NewTrait for Foo {
fn a_func() -> Option<()> {
Some(())
}
}
```
> Fix generate_trait_from_impl whitespace after vis

- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
Adds this trait impl for a type.
```rust
trait $0Foo {
fn foo(&self) -> i32;
}
```
->
```rust
trait Foo {
fn foo(&self) -> i32;
}
impl Foo for ${1:_} {
$0fn foo(&self) -> i32 {
todo!()
}
}
```
> Add ide-assist: generate_impl_trait for generate_impl

- crates/ide-assists/src/handlers/convert_to_guarded_return.rs
> Migrate `Convert_to_guarded_return` assist to use SyntaxEditor

- crates/base-db/src/input.rs
- crates/project-model/src/build_dependencies.rs
- crates/project-model/src/cargo_config_file.rs
- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/lib.rs
- crates/project-model/src/sysroot.rs
- crates/project-model/src/workspace.rs
cc https://github.com/rust-lang/rust-analyzer/issues/18508
Didn't notice that in https://github.com/rust-lang/rust-analyzer/pull/20290 but it drops the temp dir before the metadata call gets invoked, meaning we never run it against a lockfile
> internal: Fix lockfile temp dir usage and use it for build scripts as well

- editors/code/src/config.ts
- editors/code/src/debug.ts
- editors/code/src/run.ts
- editors/code/src/tasks.ts
- editors/code/src/toolchain.ts
cc https://github.com/rust-lang/rust-analyzer/issues/14066
> fix: Fix runnables extra env not substituting env vars

- triagebot.toml
Needed to unblock https://github.com/rust-lang/rust-analyzer/pull/20321. Sorry, I was thinking about this, but then I completely forgot about it.
Note that the solution isn't perfect, because CI will only run after the PR is opened, not after every push (the bot will force push every few days if the PR isn't merged quickly enough). We're working on improving that.
> Configure triagebot to reopen bot PRs

- crates/ide-assists/src/handlers/generate_documentation_template.rs
And add assert_eq, assert_ne, assert_matches support
Input:
```rust
pub fn $0foo(x: bool) {
debug_assert!(x);
}
```
Old:
```rust
/// .
///
/// # Panics
///
/// Panics if .
pub fn foo(x: bool) {
debug_assert!(x);
}
```
This PR fixes:
```rust
/// .
pub fn foo(x: bool) {
debug_assert!(x);
}
```
> Fix gen panics doc template for debug_assert

- crates/rust-analyzer/src/config.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
- All settings are now phrased in the imperative form stating what the
setting does rather than talking about what it controls. (E.g.:
"Show `Debug` action." instead of "Whether to show `Debug` action"
- Categories are now displayed in title case
- Categories are now sorted lexicographically
- General category is removed (and all the settings are moved to the top
level)
- Language for a few descriptions is made a bit less ambiguous
Before:
After:
> Improve settings tree title and descriptions

- crates/ide-assists/src/handlers/convert_tuple_struct_to_named_struct.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
> Migrate `convert_tuple_struct_to_named_struct` assist to use `SyntaxEditor`

- crates/ide-assists/src/handlers/inline_type_alias.rs
> Migrate `inline_type_alias` assist to use `syntax_editor`

- crates/base-db/src/lib.rs
- crates/hir-expand/src/builtin/fn_macro.rs
- crates/hir-expand/src/files.rs
- crates/hir-ty/src/test_db.rs
- crates/ide-db/src/lib.rs
- crates/ide-db/src/search.rs
- crates/ide-diagnostics/src/tests.rs
- crates/ide-ssr/src/lib.rs
- crates/ide/src/lib.rs
- crates/ide/src/rename.rs
- crates/rust-analyzer/src/global_state.rs
Because, to my unpleasant surprise, I discovered we're not doing that.
I intend to send a small series of improvements to `self` renaming; this is the first one.
> feat: When renaming a parameter to `self`, change callers to use method call syntax

- crates/ide-assists/src/handlers/convert_from_to_tryfrom.rs
> Migrate `convert_from_to_tryfrom` assist to use `SyntaxEditor`

- crates/ide-assists/src/handlers/add_missing_impl_members.rs
- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/handlers/generate_new.rs
- crates/ide-assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/syntax/src/ast/make.rs
> Migrate `generate_delegate_methods` assist to use `SyntaxEditor`

- crates/syntax/src/ast/edit_in_place.rs
those functions are unused because caller's assist handler was migrated to SyntaxEditor.
> Remove unused functions from edit_in_place.rs

- crates/ide-assists/src/handlers/convert_bool_to_enum.rs
- crates/ide-assists/src/handlers/convert_closure_to_fn.rs
- crates/ide-assists/src/handlers/convert_from_to_tryfrom.rs
- crates/ide-assists/src/handlers/extract_function.rs
- crates/ide-assists/src/handlers/extract_module.rs
- crates/ide-assists/src/handlers/extract_type_alias.rs
- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/handlers/generate_delegate_methods.rs
- crates/ide-assists/src/handlers/generate_delegate_trait.rs
- crates/ide-assists/src/handlers/generate_derive.rs
- crates/ide-assists/src/handlers/generate_fn_type_alias.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/generate_getter_or_setter.rs
- crates/ide-assists/src/handlers/generate_impl.rs
- crates/ide-assists/src/handlers/generate_new.rs
- crates/ide-assists/src/handlers/generate_single_field_struct_from.rs
- crates/ide-assists/src/handlers/promote_local_to_const.rs
- crates/ide-assists/src/handlers/unmerge_imports.rs
- crates/ide-assists/src/utils.rs
- crates/ide-db/src/imports/insert_use.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ast/syntax_factory/constructors.rs
- crates/syntax/src/syntax_editor.rs
I set attrs when I use `make::`.
I remove [add_attr()](https://github.com/rust-lang/rust/blob/e1b9081e699065badfc1a9419ec9566e5c8615c4/src/tools/rust-analyzer/crates/syntax/src/ast/edit_in_place.rs#L277)
> remove `add_attr()` from edit_in_place.rs because it use `ted`.

- crates/ide-assists/src/handlers/expand_glob_import.rs
> Migrate `expand_glob_import` assist to use `SyntaxEditor`

- crates/ide/src/doc_links.rs
- crates/ide/src/doc_links/tests.rs
macros annotated with `#[macro_export]` are documented at the root of the crate, yet `externalDocs` was returning a path which considered it to be documented at the module it's defined in.  this PR fixes that.
example:
- before: `externalDocs` for `println!` was returning `https://doc.rust-lang.org/nightly/std/macros/macro.println.html`
- after: `externalDocs` for `println!` returns `https://doc.rust-lang.org/nightly/std/macro.println.html`
> fix external docs for exported macros

- crates/ide-assists/src/handlers/extract_module.rs
- crates/syntax/src/ast/make.rs
When I migrate to use 'SyntaxEditor', It needs AstNode instead of String. 
bug fix:
https://github.com/user-attachments/assets/568ee0fc-8bed-4d74-828a-74241978ef5b
to:
https://github.com/user-attachments/assets/326e4f8d-2531-4927-b588-d70b02911034
> In handlers/extract_module.rs, generate ast::Module instead of String

- crates/ide-assists/src/handlers/generate_function.rs
close rust-lang/rust-analyzer#20398 
`ast::NameRef` can have keyword like `Self`, `super`, but `ast::Name` can't have keyword.
> fix: generate function by indet token

- crates/parser/src/grammar/generic_params.rs
- crates/parser/test_data/generated/runner.rs
- crates/parser/test_data/parser/inline/err/invalid_question_for_type_trait_bound.rast
- crates/parser/test_data/parser/inline/err/invalid_question_for_type_trait_bound.rs
- crates/parser/test_data/parser/inline/ok/question_for_type_trait_bound.rs
The rustc AST allows both `for<>` binders and `?` polarity modifiers in trait bounds, but they are parsed in a specific order and validated for correctness:
1. `for<>` binder is parsed first.
2. Polarity modifiers (`?`, `!`) are parsed second.
3. The parser validates that binders and polarity modifiers do not conflict:
```rust
if let Some(binder_span) = binder_span {
match modifiers.polarity {
BoundPolarity::Maybe(polarity_span) => {
// Error: "for<...> binder not allowed with ? polarity"
}
}
}
```
This implies:
- `for<> ?Sized` → Valid syntax. Invalid semantics.
- `?for<> Sized` → Invalid syntax.
However, rust-analyzer incorrectly had special-case logic that allowed `?for<>` as valid syntax. This fix removes that incorrect special case, making rust-analyzer reject `?for<> Sized` as a …
> parser: fix parsing of trait bound polarity and for-binders

- crates/ide-assists/src/handlers/extract_expressions_from_format_string.rs
**Input**:
```rust
fn main() {
write!(f, "{2+3}$0")
}
```
**Old output**:
```rust
fn main() {
write!("{}"$0, 2+3)
}
```
**This PR output**:
```rust
fn main() {
write!(f, "{}"$0, 2+3)
}
```
> Fix extract_expressions_from_format_string on write!

- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
Resolves https://github.com/rust-lang/rust-analyzer/issues/19854
> internal: Make flycheck generational

- editors/code/package-lock.json
- editors/code/package.json
This isn't a logic change, but it fixes an npm warning during the build. vsce itself hasn't had any major changes between 3.2.2 and 3.6.
* https://github.com/microsoft/vscode-vsce/releases/tag/v3.3.0
* https://github.com/microsoft/vscode-vsce/releases/tag/v3.4.0
* https://github.com/microsoft/vscode-vsce/releases/tag/v3.5.0
* https://github.com/microsoft/vscode-vsce/releases/tag/v3.6.0
> [internal] Update to the latest @vscode/vsce for extension build

- crates/parser/src/lexed_str.rs
- crates/parser/test_data/lexer/err/unterminated_string_unknown_prefix.rast
- crates/parser/test_data/lexer/err/unterminated_string_unknown_prefix.rs
Hi\! This is my first contribution to rust-analyzer - I hope I'm following the right approach.
When rust-analyzer encounters "unknown literal prefix" errors, they can sometimes be caused by unterminated string literals earlier in the code. This makes debugging confusing because the error points to a distant location rather than the actual missing quote.
For example:
```rust
fn main() {
hello("world);
// a bunch of code was here
env("FLAGS", "-help")
}
```
Added simple quote balance detection to provide helpful hints when this situation occurs:
- When an "unknown literal prefix" error happens, check for unbalanced quotes in the preceding 500 characters
- If odd number of quotes found, add a note suggesting to check for unterminated string literals
- If even number, show normal error …
> feat: hint at unterminated strings in unknown prefix errors

- crates/hir-ty/src/next_solver/mapping.rs
- crates/hir-ty/src/tests/traits.rs
Also add comment from @lcnr 
Followup from rust-lang/rust-analyzer#20453
> Add test for webrender-2022 dyn issue

- crates/rust-analyzer/src/reload.rs
When rust-analyzer fails to run a flycheck, it might respond with a status update, something like
```
Language server rust-analyzer:
Failed to run build scripts of some packages.
Please refer to the logs for more details on the errors.
```
The problem is, those messages are shown in the editor's UI and editor's logs, so without specifying what kind of logs to see, it might be somewhat confusing for certain users.
Make it more explicit that the error is located in the language server logs.
> Use a more specific error message when talking about the server logs

- crates/base-db/src/lib.rs
- crates/hir-def/src/lang_item.rs
- crates/hir-def/src/nameres.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-ty/src/tests/regression.rs
- crates/ide-db/src/lib.rs
- crates/test-fixture/src/lib.rs
The panic here: https://github.com/rust-lang/rust-analyzer/issues/20443#issuecomment-3190479593 originates from the "multiple instances" of lang items.
We can verify this running on `analysis-stats` to the following code:
```rust
use std::{ptr, sync::atomic::AtomicPtr};
#[lang = "pointee_trait"]
pub trait Pointee {
#[lang = "metadata_type"]
type Metadata;
}
static HOOK: AtomicPtr<()> = AtomicPtr::new(ptr::null_mut())
```
So, depending on the "starting crate" of lang items query, it sometimes resolved as `crate::Pointee::Metadata` but `core::ptr::metadata::Pointee::Metadata` otherwise, and if we try to compare those items, 💥 
This thing is happening in when we are running `analysis-stats` on `std`.
Though `std` has `#![no_std]` and `core` has `#![no_core]`, we always insert sysroots …
> fix: Make lang items query properly filter out overwritten/excluded sysroots

- crates/ide-assists/src/handlers/replace_arith_op.rs
Similar to rust-lang/rust-analyzer#20511
> replace_arith_op not applicable on selected

- crates/hir-ty/src/next_solver/generics.rs
- crates/hir-ty/src/next_solver/util.rs
- crates/hir-ty/src/tests/regression.rs
- crates/hir-ty/src/tests/regression/new_solver.rs
The parent generics were incorrectly not considered for TAIT.
I'm not convinced we should follow rustc here, also there are items (opaques) with more than 1 parent (opaque -> fn/type alias -> impl/trait) and I'm not sure we properly account for that in all places, but for now I left it as-is.
Also fix a bug where lifetimes' indices were incorrect when there is a self param (they started from 0 instead of 1).
That was the reason for https://github.com/rust-lang/rust-analyzer/issues/20443#issuecomment-3217182201.
> fix: Fix opaque generics

- crates/ide-assists/src/handlers/merge_imports.rs
- crates/ide-assists/src/handlers/normalize_import.rs
- crates/ide-completion/src/tests/flyimport.rs
- crates/ide-db/src/imports/insert_use/tests.rs
- crates/ide-db/src/imports/merge_imports.rs
cc https://github.com/rust-lang/rust-analyzer/issues/20421
I've just copied `version_sort` from `rustfmt` and all the other things are just tedious things like test updates
> Make import sorting order follow 2024 edition style

- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/next_solver/mapping.rs
- crates/hir-ty/src/tests/regression/new_solver.rs
The new solver does not eagerly normalize, but things after inference expect types to be normalized. rustc does the same.
Also, I'm afraid other things in r-a don't expect results of the solver to be unnormalized. We'll need to handle that.
Fixes rust-lang/rust-analyzer#20536.
> fix: Normalize all types when finishing inference

- crates/ide/src/inlay_hints.rs
- crates/ide/src/inlay_hints/adjustment.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/config.rs
- docs/book/src/configuration_generated.md
- editors/code/package.json
Reborrows are consecutive deref then ref. Make it the default because reborrows are mostly useless to the programmer.
Also rename `rust-analyzer.inlayHints.expressionAdjustmentHints.enable: "reborrow"` to `rust-analyzer.inlayHints.expressionAdjustmentHints.enable: "borrows"`, as it's not about reborrows but about any ref/deref and it's confusing with the new setting.
Closes rust-lang/rust-analyzer#20516.
> feat: Add an option to remove reborrows from adjustment inlay hints

- crates/ide-assists/src/handlers/move_guard.rs
Input:
```rust
fn main() {
match 92 {
x $0if true
&& true
&& true =>
{
{
false
}
},
_ => true
}
}
```
Old output:
```rust
fn main() {
match 92 {
x =>
if true
&& true
&& true {
{
{
false
}
}
},
_ => true
};
}
```
This PR fixed:
```rust
fn main() {
match 92 {
x => if true
&& true
&& true {
{
{
false
}
}
},
_ => true
}
}
```
> Fix indent for move_guard_to_arm_body

- crates/hir-ty/src/mir/lower.rs
- crates/hir-ty/src/mir/lower/tests.rs
- crates/hir-ty/src/next_solver/mapping.rs
Chalk represents dyn types as a list of predicate, the self type should be there. The next solver represents them quite differently. The `Self` was forgotten for the auto trait case.
Should mitigate https://github.com/rust-lang/rust-analyzer/issues/20443#issuecomment-3227557481 and https://github.com/rust-lang/rust-analyzer/issues/20443#issuecomment-3231928006. The panic is when we try to display the type (it happens to be in MIR lowering) and Chalk expects the `TraitRef` to have a self type. The actual error is way earlier, in inference, when we normalize the type. I chose to write the test at the panic site because it's easy to reproduce the issue there.
> fix: When mapping next-solver's `dyn` type, add `Self` (aka. bound var ^1.0) to auto traits' substitutions

- crates/project-model/src/toolchain_info/target_data_layout.rs
In `project_model::toolchain_info::target_data_layout::get()`, we are trying to run `rustc --print target-spec-json`.
We first try via `cargo rustc`, and fall back to invoking `rustc` directly in case of failure.
When trying `cargo rustc`, if we have a target string, we add the arguments `["--target", target]` to the very end of the command line, after a `--`. So the target is passed directly to rustc and not interpreted by Cargo.
This becomes an issue when Cargo has also been [given a specific target to use](https://doc.rust-lang.org/cargo/reference/config.html#buildtarget) (e.g. in a `.cargo/config.toml` file), because then Cargo will also add `--target ...` onto its internal invocation of rustc.
Cargo (reasonably) does not inspect the arguments after `--` to check for redundant …
> fix: Avoid `--target` option being given twice to `rustc` when invoked through `cargo rustc` while fetching target data layout

- crates/hir-ty/src/chalk_ext.rs
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/consteval_nextsolver.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/dyn_compatibility.rs
- crates/hir-ty/src/generics.rs
- crates/hir-ty/src/infer/closure.rs
- crates/hir-ty/src/layout.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower/path.rs
- crates/hir-ty/src/lower_nextsolver.rs
- crates/hir-ty/src/lower_nextsolver/path.rs
- crates/hir-ty/src/mapping.rs
- crates/hir-ty/src/mir/monomorphization.rs
- crates/hir-ty/src/next_solver/consts.rs
- crates/hir-ty/src/next_solver/generic_arg.rs
- crates/hir-ty/src/next_solver/generics.rs
- crates/hir-ty/src/next_solver/infer/mod.rs
- crates/hir-ty/src/next_solver/mapping.rs
- crates/hir-ty/src/next_solver/region.rs
- crates/hir-ty/src/next_solver/ty.rs
- crates/hir-ty/src/variance.rs
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
To the extent possible.
Previously they were confused. Sometimes generic params were treated as `Param` and sometimes as `Placeholder`. A completely redundant (in the new solver) mapping of salsa::Id to ints to intern some info where we could just store it uninterned (not in Chalk though, for some weird reason).
Plus fix a cute bug in closure substitution that was caught by the assertions of Chalk but the next solver did not have such assertions. Do we need more assertions?
Should hopefully fix all failures in https://github.com/rust-lang/rust-analyzer/pull/20578.
> fix: Make sense of the mess that were (are) different kind of generics in the solver

- crates/rust-analyzer/src/config.rs
To make it backwards-compatible.
See https://github.com/rust-lang/rust-analyzer/pull/20520#discussion_r2321357436.
> fix: Fix typo in config

- crates/hir-ty/src/tests/regression/new_solver.rs
Not sure what exactly fixed it, but why not.
Closes rust-lang/rust-analyzer#20487, closes rust-lang/rust-analyzer#20489.
> internal: Add a regression test for a fixed new trait solver bug

- Cargo.lock
- Cargo.toml
- crates/hir-ty/src/display.rs
- crates/hir-ty/src/dyn_compatibility.rs
- crates/hir-ty/src/lower_nextsolver.rs
- crates/hir-ty/src/lower_nextsolver/path.rs
- crates/hir-ty/src/method_resolution.rs
- crates/hir-ty/src/next_solver/consts.rs
- crates/hir-ty/src/next_solver/def_id.rs
- crates/hir-ty/src/next_solver/fold.rs
- crates/hir-ty/src/next_solver/fulfill.rs
- crates/hir-ty/src/next_solver/generic_arg.rs
- crates/hir-ty/src/next_solver/infer/canonical/instantiate.rs
- crates/hir-ty/src/next_solver/infer/mod.rs
- crates/hir-ty/src/next_solver/infer/relate/higher_ranked.rs
- crates/hir-ty/src/next_solver/interner.rs
- crates/hir-ty/src/next_solver/ir_print.rs
- crates/hir-ty/src/next_solver/mapping.rs
- crates/hir-ty/src/next_solver/predicate.rs
- crates/hir-ty/src/next_solver/solver.rs
- crates/hir-ty/src/next_solver/ty.rs
- crates/hir-ty/src/next_solver/util.rs
- crates/hir-ty/src/utils.rs
- crates/hir/src/lib.rs
The main changes are (there are some other small changes):
- Using a specific type for trait IDs in the new solver, allowing us to simplify a lot of code.
- Add `BoundConst` similar to `BoundTy` and `BoundRegion` (previously consts used `BoundVar` directly), due to a new trait requirement.
This should enable the sync https://github.com/rust-lang/rust/pull/146086 - CC @lnicola.
I prefer to merge this before https://github.com/rust-lang/rust-analyzer/pull/20578, but if you think this will cause rebase pains for you @ShoyuVanilla - please tell.
> internal: Upgrade rustc crates

- docs/book/README.md
- docs/book/src/faq.md
This was one of the items that people complained about in the recent Compiler Performance Survey. It is "common knowledge" amongst experience RA users, but it wasn't documented in a very visible way before.
I was also thinking about actually making a separate ToC page about this, in the Configuration section, below "Non-Cargo Based Projects". What do you think about that?
> Add a FAQ entry about RA and Cargo build lock/cache conflicts

- crates/syntax/src/ast/node_ext.rs
Lifetime node example:
```
LIFETIME_PARAM@15..21
LIFETIME@15..17
LIFETIME_IDENT@15..17 "'a"
COLON@17..18 ":"
WHITESPACE@18..19 " "
TYPE_BOUND_LIST@19..21
TYPE_BOUND@19..21
LIFETIME@19..21
LIFETIME_IDENT@19..21 "'b"
```
> Fix LifetimeParam::lifetime_bounds invalid implement

- crates/ide/src/hover/tests.rs
- crates/ide/src/runnables.rs
That is, resolve them globally, not from the test's location.
This *should* result in more robust resolution; for example, previously the code failed to detect the presence of snapshot testing if the snapshot library was renamed in the dependency or was an indirect dependency.
Fixes rust-lang/rust-analyzer#20621.
> fix: Resolve paths to snapshot test libraries absolutely

- crates/hir-ty/src/infer/cast.rs
- crates/hir-ty/src/tests/regression/new_solver.rs
This cause the relationships between inference vars to get recorded.
I'm not entirely sure this is the correct thing to do, rustc's cast handling seems much more complicated, but it seems better than the status quo. CC @ShoyuVanilla I think you've inspected the rustc implementation in the past with greater scrutiny.
Fixes rust-lang/rust-analyzer#20644. This issue is unfortunate: when mapping next solver consts to Chalk, Chalk stores the types of the const but the next solver does not, so we stub them with `TyKind::Error`. Unfortunately, that makes Chalk to mark the type as containing errors. I don't see a way around this, we'll probably need to live with spurious error flags in our types for the time being.
> fix: Always coerce in a cast, even when there are unknown types

- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/context/analysis.rs
Fixes rust-lang/rust-analyzer#20620
Example
---
```rust
fn main() {
let x = if true {
()
} $0 else {};
}
```
```rust
fn main() {
let x = if true {
()
} else if $1 {
$0
}; else {};
}
```
```rust
fn main() {
let x = if true {
()
} else if $1 {
$0
} else {};
}
```
> Fix extra semicolon before else in let-stmt

- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/reload.rs
When the user pressed save in a source file that was part of a specific target, rust-analyzer would trigger two flychecks on the workspace that the file was a part of:
- A package-level flycheck (`cargo check -p <package> (--bin | --example | --test | --benchmark) <target>`)
- A workspace-level flycheck (`cargo check --workspace`)
The triggering of the second flycheck cancelled the first, so there was no correctness issue, but the behavior undesirable regardless.
This PR fixes this by making sure that the workspace level check is not triggered if a package check was already triggered.
Closes rust-lang/rust-analyzer#20436
> fix: Don't trigger two flychecks when saving files that are part of targets

- crates/hir-ty/src/dyn_compatibility.rs
- crates/hir-ty/src/dyn_compatibility/tests.rs
- crates/hir-ty/src/lower_nextsolver.rs
- crates/hir-ty/src/next_solver/interner.rs
- crates/hir-ty/src/tests/regression/new_solver.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/20582
> Disclaimer: this code can effectively hang or stack-overflow your rust-analyzer!
```rust
trait DimMax<Other: Dimension> {
type Output: Dimension;
}
trait Dimension: DimMax<<Self as Dimension>:: Smaller, Output = Self> {
type Smaller: Dimension;
}
```
If we gonna normalize projection types related to the above traits, the current implementation endlessly elaborates implied bounds like
- `<T as DimMax>::Output: Dimension` and we have `Dimension: DimMax`
- `<<T as DimMax>::Output as DimMax>::Output: DimMax`
- `<<<T as DimMax>::Output as DimMax>::Output as DimMax>::Output: DimMax`
- `...` 😵 
Though this is not the best I can, I partially ported some implementation details from rustc to fix this infinite loop.
I think we should …
> fix: Infinite loop while elaborting predicates

- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/flags.rs
In my experience the `processing <module>` messages make it harder to search for the actual diagnostics, so remove them and instead print the filename only if there is a diagnostic.
Also allow choosing the minimum severity.
> internal: Improve `rust-analyzer diagnostics`

- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/next_solver.rs
cc [#t-compiler/rust-analyzer > New Trait Solver feedback @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/185405-t-compiler.2Frust-analyzer/topic/New.20Trait.20Solver.20feedback/near/539818036)
Fortunately, `rustc_data_structure` re-exports things in `ena` and `indexmap` so I could fix those "there are multiple different versions of crate" things this time 😌 (there were 93 occurences of it)
> Fix "sync-from-ra" for `rust-lang/rust`

- crates/hir-ty/src/next_solver/inspect.rs
I guess this is the last thing for the errors like `Foo and Foo have similar names, but are actually distinct types` 🙃 
We might need CI that runs cargo check with `in-rust-tree` feature and check whether we are using `ra_ap_*` things
> minor: Fix one more thing in `in-rust-tree`

- crates/hir-ty/src/lower.rs
- crates/hir-ty/src/lower_nextsolver.rs
- crates/ide/src/hover/tests.rs
https://github.com/rust-lang/rust-analyzer/issues/20696
openly admit this was AI-assisted, but it seemed like a sufficiently small/straightforward issue to be a good idea to attempt
> fix negative const generic integer literals

- crates/ide-assists/src/handlers/destructure_struct_binding.rs
Example
---
```rust
struct Foo { x: () }
struct Bar { foo: Foo }
fn f(Bar { mut $0foo }: Bar) {}
```
Panic `Option::unwrap`
```rust
struct Foo { x: () }
struct Bar { foo: Foo }
fn f(Bar { foo: Foo { mut x } }: Bar) {}
```
> Fix panics on `Foo{mut x}` for destructure_struct_binding

- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/tests/expression.rs
Example
---
```rust
fn foo() {
let x = if true {
1
} el$0 else {
2
};
}
```
```text
else~    k [LS]
else if~ k [LS]
```
```text
else if~ k [LS]
```
> Fix `else` completion before else keyword

- crates/project-model/src/build_dependencies.rs
- crates/project-model/src/cargo_workspace.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers/notification.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/target_spec.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/20651
> fix: Make flycheck clearing dependency-aware

- crates/ide-assists/src/handlers/destructure_struct_binding.rs
When the reference type does not require adding a dereference or parentheses, it will panic
Example
---
```rust
struct Foo { bar: i32, baz: i32 }
fn main() {
let $0foo = &Foo { bar: 1, baz: 2 };
let _ = &foo.bar;
}
```
Panic:
```
assertion failed: !self.data().mutable
```
```rust
struct Foo { bar: i32, baz: i32 }
fn main() {
let Foo { bar, baz } = &Foo { bar: 1, baz: 2 };
let _ = bar;
}
```
> Fix panic `!self.data().mutable` for destructure_struct_binding

- crates/ide-diagnostics/src/handlers/unused_variables.rs
Example
---
```rust
struct S { field : u32 }
fn main() {
let s = S { field : 2 };
let S { $0field } = s
}
```
```rust
struct S { field : u32 }
fn main() {
let s = S { field : 2 };
let S { _field } = s
}
```
```rust
struct S { field : u32 }
fn main() {
let s = S { field : 2 };
let S { field: _field } = s
}
```
> Fix unused_variables fixes shorthand record field

- crates/ide-assists/src/handlers/bind_unused_param.rs
Fixes:
- applicable on underscore prefix parameter
- using binding mode as an expression
Examples
---
```rust
fn foo($0_x: i32, y: i32) {}
```
```rust
fn foo(_x: i32, y: i32) {
let _ = _x;
}
```
Assist not applicable
---
```rust
fn foo(ref $0y: i32) {}
```
```rust
fn foo(ref y: i32) {
let _ = ref y;
}
```
```rust
fn foo(ref y: i32) {
let _ = y;
}
```
> Fix applicable on underscore for bind_unused_param

- crates/ide-assists/src/handlers/add_braces.rs
Example
---
**Not applicable**:
```rust
fn foo() {
match () {
() => {
t(|n|$0 n + 100);
}
}
}
```
> Fix closure in match not applicable for add_braces

- crates/hir-ty/src/infer.rs
(This re-introduces a reduced access to a couple of previously public fields on `InferenceResult`)
As per: https://github.com/rust-lang/rust-analyzer/pull/20184#issuecomment-3302177641
@ChayimFriedman2: For my use case I don't really need to distinguish between the different origins of such types, but in order to provide an API that isn't only useful to my use case I've instead added individual iterators, rather than one composite chained one. Lemme know if you had something else in mind though and I'll happily make changes.
> Expose iterators over an inference result's types

- Cargo.lock
- Cargo.toml
- crates/hir-ty/Cargo.toml
- crates/hir-ty/src/consteval.rs
- crates/hir-ty/src/consteval/tests.rs
- crates/hir-ty/src/consteval_nextsolver.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/coerce.rs
- crates/hir-ty/src/infer/fallback.rs
- crates/hir-ty/src/infer/unify.rs
- crates/hir-ty/src/next_solver.rs
- crates/hir-ty/src/next_solver/region.rs
- crates/hir-ty/src/next_solver/ty.rs
- crates/hir-ty/src/tests/never_type.rs
- crates/hir-ty/src/tests/regression.rs
- crates/intern/src/symbol/symbols.rs
fallback.rs was ported straight from rustc (minus the lint parts).
This fixes the `!` regressions.
rustc uses graphs from rustc-data-structures. I opted to depend on an external dependency (`petgraph`), since implementing graph handling ourselves doesn't seem like a good idea.
> fix: Implement fallback properly

- crates/ide-assists/src/handlers/invert_if.rs
- crates/ide-db/src/syntax_helpers/node_ext.rs
Example
---
```rust
fn f() { i$0f x && let Some(_) = Some(1) { 1 } else { 0 } }
```
```rust
fn f() { if !(x && let Some(_) = Some(1)) { 0 } else { 1 } }
```
Assist not applicable
> Fix applicable on if-let-chain for invert_if

- crates/ide-assists/src/handlers/convert_to_guarded_return.rs
Fixes rust-lang/rust-analyzer#20744
Close rust-lang/rust-analyzer#20743
- Add if-let-chain support
- Add early expression `None` in function `Option` return
- Fix not applicable for if-expr in let-stmt
- Add applicable in closure
Examples
---
```rust
fn main() {
if$0 let Ok(x) = Err(92)
&& x < 30
&& let Some(y) = Some(8)
{
foo(x, y);
}
}
```
->
```rust
fn main() {
let Ok(x) = Err(92) else { return };
if x >= 30 {
return;
}
let Some(y) = Some(8) else { return };
foo(x, y);
}
```
---
```rust
fn main() {
let _x = loop {
if$0 let Ok(x) = Err(92) {
foo(x);
}
};
}
```
Assist not applicable
```rust
fn main() {
let _x = loop {
let Ok(x) = Err(92) else { continue };
foo(x);
};
}
```
---
```rust
fn main() {
let _f = || {
bar();
if$0 true {
foo();
// comment …
```
> Add let-chain support for convert_to_guarded_return

- crates/ide-completion/src/completions/attribute.rs
- crates/ide-completion/src/tests/attribute.rs
Partial fixes of rust-lang/rust-analyzer#14600
Example
---
```rust
#[cfg_attr($0, must_use)]
struct Foo;
```
> Add cfg_attr predicate completion

- crates/ide-assists/src/handlers/apply_demorgan.rs
Example
---
```rust
fn f() { $0!(1 || 3 && 4 || 5) }
```
->
```rust
fn f() { !1 && !(3 && 4) && !5 }
```
> Add applicable on bang `!` for apply_demorgan

- crates/hir-ty/src/diagnostics/unsafe_check.rs
- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
follow up https://github.com/rust-lang/rust/pull/141469
i didn’t test it locally, just relying on the tests for now. also not really familiar with rust-analyzer code, but tried my best
if there’s anything that can be improved, feel free to point it out
r? @Veykril
> Allow `&raw [mut | const]` for union field 

- crates/ide-completion/src/completions/attribute/cfg.rs
- crates/ide-completion/src/tests/attribute.rs
Example
---
`#[cfg($0)]` -> `#[cfg(any($0))]`
> Add `all` `any` and `not` attribute completions

- crates/hir-ty/src/tests/regression/new_solver.rs
Fixes rust-lang/rust-analyzer#10653.
> minor: Add regression test for another (long-standing) bug fixed by the new solver

- .github/workflows/release.yaml
and bump `MACOSX_DEPLOYMENT_TARGET` to 14.0.
https://github.blog/changelog/2025-09-19-github-actions-macos-13-runner-image-is-closing-down/
> internal: Build x86_64-apple-darwin binaries on macos-14

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/trait_impl_incorrect_safety.rs
Fixes rust-lang/rust-analyzer#20763.
> fix: Ignore impl trait safety errors when the trait is unresolved

- crates/project-model/src/cargo_workspace.rs
- crates/project-model/src/workspace.rs
- crates/toolchain/src/lib.rs
By setting RUSTUP_AUTO_INSTALL=0.
Closes rust-lang/rust-analyzer#20719.
> fix: Prevent rustup from automatically installing toolchains

- docs/book/src/configuration.md
- docs/book/src/contributing/guide.md
- docs/book/src/contributing/lsp-extensions.md
- docs/book/src/contributing/syntax.md
Minor copy edits to improve clarity and correct contextual typos across the docs.
> minor: fixes small typos in docs

- crates/rust-analyzer/src/cli/analysis_stats.rs
On main, trying to run `cargo xtask install --pgo crate@version` panics due to some code paths trying to re-attach to the salsa database when it's already attached. To resolve that, I changed some parts of the code to not attach to the database when we already know we're attached.
I'm not sure if this is the "correct" approach, but it seems to do the job for me. After this change, I was able to do all the following just fine:
1. `cargo nextest run`
2. `cargo build --release --features mimalloc --target $(rustc --print host-tuple) && cargo xtask install --server --mimalloc --proc-macro-server --pgo apache/datafusion@50.0.0` (as an example crate)
3. Using my ide with the version of rust-analyzer installed in the previous step and jumping around, using suggestions, etc.
This PR is also …
> Fix panic when using analysis-stats

- crates/rust-analyzer/src/cli/analysis_stats.rs
I noticed, when working on rust-lang/rust-analyzer#20777, that we were sort+deduping the same vec twice, so this just pulls that into one sort+dedup instead of two.
It does add to these fns the invariant of passing in an already-sorted list, which may not be ideal? I considered making a `Deduped<'a, T>(&'a [T])` newtype to make this invariant a bit more explicit, but figured that was probably a bit overkill for these fns that are only called once.
> Deduplicate sort+dedup calls

- crates/ide-diagnostics/src/handlers/missing_unsafe.rs
Fixes rust-lang/rust-analyzer#20588
I seem unable to use `Expr::needs_parens*` to complete it
Example
---
```rust
static mut STATIC_MUT: u8 = 0;
fn foo() -> u8 {
STATIC_MUT$0 * 2
}
```
```rust
static mut STATIC_MUT: u8 = 0;
fn foo() -> u8 {
unsafe { STATIC_MUT } * 2
}
```
```rust
static mut STATIC_MUT: u8 = 0;
fn foo() -> u8 {
(unsafe { STATIC_MUT }) * 2
}
```
> Fix missing parentheses for missing_unsafe

- docs/book/src/configuration.md
Motivated by the discussion [here](https://github.com/rust-lang/rust-analyzer/issues/20798#issuecomment-3368962316).
> docs: Mention editor-independent configuration

- crates/rust-analyzer/src/command.rs
- crates/rust-analyzer/src/discover.rs
- crates/rust-analyzer/src/flycheck.rs
- crates/rust-analyzer/src/test_runner.rs
This + fingerprint logging allows for easier figuring out causes of spurious rebuilds
> feat: Log flycheck stdout and stderr to files

- crates/hir-ty/src/consteval/tests/intrinsics.rs
- crates/hir-ty/src/db.rs
- crates/hir-ty/src/drop.rs
- crates/hir-ty/src/lib.rs
- crates/hir-ty/src/mir/eval.rs
- crates/hir-ty/src/mir/eval/shim.rs
- crates/hir/src/lib.rs
And:
- Remove it from being a query (it is only used for hover, where no caching is needed, and MIR evaluation of `needs_drop()`, which is rare).
- Fix handling of `PhantomData`.
> internal: Migrate drop glue handling to new solver
