rust-lang/rust-analyzer

- xtask/src/lib.rs
- xtask/src/main.rs
- xtask/src/release.rs
> Tweak release

- crates/ra_ide/src/goto_definition.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide_db/src/defs.rs
Closes #4764. I'm not familiar with ra codebase, there might be better ways to do that :smile:
> Add goto def for enum variant field

- crates/ra_ide/src/snapshots/highlight_doctest.html
- crates/ra_ide/src/snapshots/highlight_injection.html
- crates/ra_ide/src/snapshots/highlight_strings.html
- crates/ra_ide/src/snapshots/highlight_unsafe.html
- crates/ra_ide/src/snapshots/highlighting.html
- crates/ra_ide/src/snapshots/rainbow_highlighting.html
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide/src/syntax_highlighting/html.rs
- crates/ra_ide/src/syntax_highlighting/tests.rs
> Fix unsafe highlihgintngs

- docs/dev/README.md
> Dev docs nits

- crates/ra_assists/src/assist_context.rs
- crates/ra_assists/src/handlers/add_function.rs
- crates/ra_assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ra_assists/src/handlers/fix_visibility.rs
> Simplify API

- crates/ra_project_model/src/json_project.rs
- crates/ra_project_model/src/lib.rs
Here's the rest of the transition.
> Finish JsonProject transition to cfgs from the separate atoms and features.

- crates/ra_assists/src/handlers/unwrap_block.rs
> Simplify unwrapping of blocks

- crates/ra_assists/src/handlers/unwrap_block.rs
> Unwrap block works with match arms

- crates/ra_assists/src/handlers/early_return.rs
- crates/ra_assists/src/handlers/replace_if_let_with_match.rs
- crates/ra_syntax/src/ast/edit.rs
> Use correct indent when replacing with match

- crates/ra_parser/src/grammar/paths.rs
- crates/ra_parser/src/grammar/patterns.rs
- crates/ra_syntax/test_data/parser/err/0024_many_type_parens.rast
- crates/ra_syntax/test_data/parser/inline/ok/0164_type_path_in_pattern.rast
- crates/ra_syntax/test_data/parser/inline/ok/0164_type_path_in_pattern.rs
> Correctly parse <_> paths in patterns

- crates/ra_flycheck/src/lib.rs
- crates/rust-analyzer/src/config.rs
- editors/code/package.json
This will fix #4631
The implementation works (as far as I have tested) but is suboptimal because I am copying the "cargo.features".
> Let checkOnSafe default to some of the options of cargo

- crates/ra_project_model/src/lib.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/global_state.rs
> Reduce OUT_DIR special casing

- crates/ra_ide/src/snapshots/highlighting.html
- crates/ra_ide/src/syntax_highlighting/tests.rs
- crates/ra_ide_db/src/defs.rs
> In field patterns, don't highlight local binding as a field

- Cargo.lock
- crates/ra_db/src/input.rs
- crates/ra_db/src/lib.rs
- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/lib.rs
- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_def/src/test_db.rs
- crates/ra_hir_expand/Cargo.toml
- crates/ra_hir_expand/src/builtin_derive.rs
- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_hir_expand/src/eager.rs
- crates/ra_hir_expand/src/lib.rs
- crates/ra_hir_expand/src/test_db.rs
- crates/ra_hir_ty/src/test_db.rs
- crates/ra_ide_db/src/lib.rs
> Don't guess macro expansion crate

- crates/ra_ide/src/typing.rs
> Indent chain `.` even if there's more stuff afterwards

- crates/ra_hir_def/src/find_path.rs
- crates/ra_hir_def/src/import_map.rs
If a containing module is already in scope, there's no need to use the full path to the item.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/4846
> find_path: return shorter paths for external items

- crates/rust-analyzer/src/diagnostics/snapshots/rust_analyzer__diagnostics__to_proto__tests__snap_rustc_unused_variable.snap
- crates/rust-analyzer/src/diagnostics/to_proto.rs
This reverts https://github.com/rust-analyzer/rust-analyzer/pull/4721
> Revert "Hide squiggly for unused and unnecessary"

- crates/ra_ide/src/completion/complete_postfix.rs
> Fix if and while postfix completions

- docs/dev/README.md
> Discourage allocation

- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Cleanup URL handling

- crates/ra_hir_ty/src/_match.rs
This results in much nicer rustdoc output
> _match.rs: improve comment formatting

- docs/dev/README.md
> Var naming

- crates/ra_assists/src/ast_transform.rs
- crates/ra_hir_def/src/path.rs
- crates/ra_ide/src/completion/completion_context.rs
- crates/ra_parser/src/grammar/expressions.rs
- crates/ra_syntax/test_data/parser/inline/err/0009_attr_on_expr_not_allowed.rast
- crates/test_utils/src/lib.rs
- docs/dev/README.md
> Deprecate hir::Path::from_ast

- crates/ra_hir_def/src/diagnostics.rs
- crates/ra_hir_def/src/nameres.rs
- crates/ra_hir_def/src/nameres/mod_resolution.rs
- crates/ra_ide/src/diagnostics.rs
- crates/ra_ide/src/references/rename.rs
- crates/ra_ide_db/src/source_change.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/to_proto.rs
> Anchor file-system operations to the file, and not to the source root. 

- crates/ra_ide/src/ssr.rs
Reasoning discussed at https://github.com/rust-analyzer/rust-analyzer/issues/3186#issuecomment-644069324
> Remove :expr from placeholders

- crates/ra_ide/src/snapshots/highlight_doctest.html
- crates/ra_ide/src/syntax_highlighting/injection.rs
- crates/ra_ide/src/syntax_highlighting/tests.rs
> Inspect markdown code fences to determine whether to apply syntax highlighting

- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/global_state.rs
We need to find a better way to do it...
CrateGraph by itself is fine, CargoWorkspace as well, but the mapping
between the two seems arbitrary...
bors r+
🤖
> Better encapsulate reverse-mapping of files to cargo targets

- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide/src/runnables.rs
> display Doctest code lens before comment

- crates/ra_hir_ty/src/_match.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/4416, but replaces it with a false positive.
r? @flodiebold
> Avoid all unchecked indexing in match checking

- crates/ra_hir_ty/src/infer/path.rs
- crates/ra_hir_ty/src/tests/regression.rs
Fixes #4953.
This is the first fix I do in hir_ty, I hope I got it right :)
> Fix substs in resolve_value_path for ImplSelf

- crates/ra_db/src/input.rs
- crates/ra_hir_def/src/nameres/collector.rs
> Don't panic on crates depending on themselves

- editors/code/src/main.ts
- editors/code/src/net.ts
This should prevent partially downloaded files in cases when the user closes vsode before the download is complete.
There is also a new more descriptive error message when the user has multiple vscode windows open and tries to download the server.
Related: https://github.com/rust-analyzer/rust-analyzer/issues/4938#issuecomment-646738360
> Download artifacts into tmp dir

- crates/ra_hir_def/src/body/scope.rs
This is unstable, behind the `bindings_after_at` feature gate, but the semantics are fairly clear, and this is used at lot in rustc.
> Handle bindings after @ in patterns

- crates/ra_ide/src/references/rename.rs
> Fix renaming mod in use tree

- crates/ra_ide/src/completion/complete_attribute.rs
> don't complete top level attrs inside nested attrs and add better labels

- crates/paths/src/lib.rs
> Add paths::RelPath[Buf]

- xtask/src/release.rs
> Add sponsors section to changelog

- crates/ra_ide/src/ssr.rs
- crates/ra_ssr/src/lib.rs
- crates/ra_ssr/src/matching.rs
- crates/ra_ssr/src/replacing.rs
- crates/ra_ssr/src/tests.rs
Matching within macro calls is to come later and matching of macro calls within macro calls later still.
> SSR: Allow matching of whole macro calls

- editors/code/src/main.ts
- editors/code/src/net.ts
> Decouple http file stream logic from temp dir logic

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/test_utils/src/lib.rs
> Remove relative-path dependency

- Cargo.lock
- crates/ra_db/src/fixture.rs
- crates/ra_hir_def/src/nameres/tests.rs
- crates/ra_ide/src/mock_analysis.rs
- crates/rust-analyzer/tests/heavy_tests/support.rs
- crates/test_utils/Cargo.toml
- crates/test_utils/src/fixture.rs
- crates/test_utils/src/lib.rs
> Simplify fixtures

- crates/ra_ide/src/display/function_signature.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/stdx/src/lib.rs
- crates/test_utils/src/fixture.rs
> Slightly better name

- crates/rust-analyzer/tests/heavy_tests/support.rs
> Remove useless test code

- crates/rust-analyzer/tests/heavy_tests/support.rs
This should rid us of the intermittent test failure
https://github.com/rust-analyzer/rust-analyzer/pull/5017#issuecomment-648717983
bors r+
🤖
> Disable file watching when running slow tests

- crates/ra_hir_ty/src/infer/pat.rs
- crates/ra_hir_ty/src/tests/patterns.rs
> Fix string literal inference in match

- Cargo.lock
- crates/paths/src/lib.rs
- crates/ra_project_model/Cargo.toml
- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- crates/ra_project_model/src/sysroot.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/tests/heavy_tests/support.rs
> Be more explicit about absolute paths at various places

- crates/ra_hir_def/src/item_scope.rs
- crates/ra_hir_def/src/nameres/tests/globs.rs
> Account for updated module ids when determining whether a resolution is changed

- Cargo.lock
- crates/ra_project_model/Cargo.toml
- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- crates/ra_project_model/src/project_json.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/loader.rs
- docs/user/manual.adoc
> Cleanup project.json deserialization

- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/loader.rs
> Less error-prone naming

- crates/vfs-notify/src/lib.rs
> Don't watch dirs if not asked to

- crates/ra_hir_ty/src/method_resolution.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/4975
bors r+ :robot: ;)
> Make `iterate_method_candidates` non-generic

- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/to_proto.rs
> Tweak visibility

- crates/ra_ide/src/matching_brace.rs
> matching brace works for | in lambdas

- crates/ra_flycheck/src/lib.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/vfs-notify/src/lib.rs
> Unify code style for worker threads

- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
> Minor, move code

- crates/ra_ide/src/matching_brace.rs
> Fix matchig brace for pipes

- crates/flycheck/src/lib.rs
- crates/vfs-notify/src/lib.rs
> Canonicalize actor API

- crates/rust-analyzer/src/main_loop.rs
> Better event naming

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/thread_pool.rs
> Move TaskPool into GlobalState

- crates/flycheck/src/lib.rs
- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/vfs-notify/src/lib.rs
> Add NotificationDispatcher

- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
> Simplify diagnostics handling

- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
> Prep dynamic reload

- crates/ra_assists/src/handlers/introduce_variable.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
> DWIM introduce variable

- crates/ra_hir_ty/src/method_resolution.rs
> `iterate_method_candidates`: Address review comments

- crates/flycheck/src/lib.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
> Be more precise about flycheck status

- crates/flycheck/src/lib.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
> Type safer requests

- crates/rust-analyzer/src/reload.rs
> Fix config switching

- crates/rust-analyzer/src/global_state.rs
> Set corret request method

- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/body/scope.rs
> Fix a panic with malformed inner items

- docs/dev/README.md
> Document test minimality

- crates/ra_assists/src/handlers/change_return_type_to_result.rs
> do not suggest assist for return type to result in bad case 

- crates/ra_assists/src/handlers/extract_variable.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/tests/generated.rs
> introduce_variable -> extract_variable

- Cargo.lock
- crates/ra_assists/src/handlers/extract_variable.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/tests/generated.rs
- crates/ra_toolchain/src/lib.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/handlers.rs
> Try to find rustfmt in more places

- crates/ra_toolchain/src/lib.rs
> Better exe probing

- crates/ra_ssr/src/lib.rs
- crates/ra_ssr/src/matching.rs
- crates/ra_ssr/src/tests.rs
> SSR: Allow matching within macro calls

- crates/ra_ide/src/completion/complete_keyword.rs
> Add `::` to label for  `crate::` completion

- crates/ra_ide/src/inlay_hints.rs
> Don't show ra_fixture param hints

- crates/flycheck/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/vfs-notify/src/lib.rs
> Cleanup cargo process handling in flycheck

- crates/ra_assists/src/handlers/reorder_fields.rs
- crates/ra_ssr/src/parsing.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/diagnostics.rs
- docs/dev/README.md
```
-rwxr-xr-x 1 me me 37917528 Jun 29 17:26 /home/me/.cargo/bin/rust-analyzer
-rwxr-xr-x 1 me me 37904056 Jun 29 18:14 /home/me/.cargo/bin/rust-analyzer
```
Saved 13.5 KB there :-).
> Use more of FxHash*

- crates/rust-analyzer/src/handlers.rs
> Fix "Run | Debug" lens for examples

- crates/test_utils/src/lib.rs
> Generalize annotations

- crates/ra_ide/src/runnables.rs
> Refactor runnable tests

- crates/ra_ide/src/inlay_hints.rs
- crates/test_utils/src/lib.rs
> Simplify most of the inlay hints tests

- Cargo.lock
Removes clicolors-control and atty
> Bump console and insta

- crates/ra_project_model/src/cargo_workspace.rs
> Don't crash on empty out_dirs with older cargos

- crates/vfs/src/file_set.rs
> FileSetConfig works with empty set of roots

- crates/rust-analyzer/src/main_loop.rs
> Dont show empty progress for empty workspaces

- crates/flycheck/src/lib.rs
> Log flycheck command

- crates/ra_ide/src/expand_macro.rs
> Update expand macro tests

- crates/ra_ide/src/display/structure.rs
- crates/ra_ide/src/folding_ranges.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/test_utils/src/lib.rs
> Fold multiline calls

- crates/ra_ide/src/completion.rs
https://github.com/rust-analyzer/rust-analyzer/blob/a33eefa3b26000b3018e6bb873f18dbe15ab4ab7/crates/ra_ide/src/completion/complete_snippet.rs#L23-L24
> fix: correct pd/ppd/tfn/tmod completion doc

- crates/ra_ide/src/completion/complete_record.rs
- crates/ra_ide/src/completion/completion_item.rs
- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/completion/test_utils.rs
> Cleanup record completion tests

- crates/ra_ide/src/completion/complete_keyword.rs
> Refactor keyword completion tests

- crates/ra_ide/src/completion/complete_attribute.rs
> Refactor attribut completion tests

- Cargo.lock
> :arrow_up: salsa

- crates/ra_ide/src/references/rename.rs
> Fix module renaming

- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/completion/test_utils.rs
> Cleanup presentation tests

- crates/ra_ide/src/completion/complete_keyword.rs
- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/completion/test_utils.rs
> Cleanup more completion tests

- crates/ra_ide/src/completion/complete_dot.rs
- crates/ra_ide/src/completion/complete_keyword.rs
- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/completion/completion_item.rs
- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/completion/test_utils.rs
> Cleanup dot completiont tests

- crates/ra_ide/src/completion/complete_fn_param.rs
- crates/ra_ide/src/completion/complete_macro_in_item_position.rs
- crates/ra_ide/src/completion/complete_pattern.rs
- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/presentation.rs
> Fix lookup in tests

- crates/ra_ide/src/completion/complete_pattern.rs
- crates/ra_ide/src/completion/complete_postfix.rs
> Modernize postfix completion tests

- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
> Add Item change to the set of benches

- crates/ra_ide/src/completion.rs
- crates/ra_ide/src/completion/complete_dot.rs
- crates/ra_ide/src/completion/complete_keyword.rs
- crates/ra_ide/src/completion/complete_pattern.rs
- crates/ra_ide/src/completion/complete_postfix.rs
- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/completion/complete_snippet.rs
- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/completion/test_utils.rs
> Alight details in comkplation list

- crates/ra_cfg/src/lib.rs
- crates/ra_project_model/src/lib.rs
- crates/ra_project_model/src/project_json.rs
Lookup default cfgs per target when generating cfg list.
Should fully address #4840
CC @woody77
> Add optional target to crates in json project

- crates/ra_ide/src/completion/complete_trait_impl.rs
> Modernise item completion tests

- crates/vfs-notify/src/lib.rs
> Simplify file watcher

- xtask/src/release.rs
> sponsors link

- editors/code/src/main.ts
According to: https://github.com/rust-analyzer/rust-analyzer/issues/5009#issuecomment-654561497
> Consider EPERM error as other vscode processes using rust-analyzer

- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/completion_context.rs
- crates/ra_ide/src/completion/completion_item.rs
- crates/ra_ide/src/completion/presentation.rs
- crates/rust-analyzer/src/to_proto.rs
> Modernize unqualified reference completion tests

- crates/ra_db/Cargo.toml
> Upstream salsa

- .github/workflows/ci.yaml
- Cargo.lock
> check cargo.lock

- Cargo.lock
> :arrow_up: backtrace

- crates/vfs/src/file_set.rs
Previous solution for binning paths into disjoint directories was
simple and fast -- just a single binary search.
Unfortunatelly, it wasn't coorrect: if the ditr are
/d
/d/a
/d/c
then partitioning the file /d/b/lib.rs won't pick /d as a correct
directory.
The correct solution here is a trie, but it requires exposing path
components.
So, we use a poor man's substitution -- a *vector* of sorted paths,
such that each bucket is prefix-free
closes #5246
> Fix symbol search in salsa

- xtask/src/main.rs
- xtask/src/not_bash.rs
- xtask/src/release.rs
> Automate rust-analyzer promotion

- Cargo.lock
- crates/ra_db/Cargo.toml
- crates/ra_db/src/lib.rs
- crates/ra_hir_def/src/nameres/mod_resolution.rs
- crates/ra_ide_db/src/change.rs
- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/tests/heavy_tests/support.rs
> Remove relative_path dependency

- crates/ra_ide/src/hover.rs
> Tidyup hover

- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/lib.rs
- crates/ra_ide/src/markup.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/vfs-notify/src/include.rs
- xtask/tests/tidy.rs
> Refactor hover tests

- crates/expect/src/lib.rs
- crates/ra_ide/src/display.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/markup.rs
> Streamline

- Cargo.lock
- crates/expect/src/lib.rs
- crates/ra_ide/Cargo.toml
- crates/ra_syntax/Cargo.toml
- crates/ra_syntax/src/tests.rs
> expect should be a dev dep

- crates/ra_hir_def/src/item_tree/lower.rs
- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/completion_item.rs
> Re-enable IDE features for incomplete impl blocs

- Cargo.lock
- crates/ra_ide/Cargo.toml
- crates/ra_ide/src/diagnostics.rs
- crates/ra_ide/src/mock_analysis.rs
> Remove insta from ra_ide

- crates/ra_ide/src/folding_ranges.rs
> Fold struct literals

- crates/ra_assists/src/handlers/raw_string.rs
- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_ide/src/syntax_highlighting/injection.rs
- crates/ra_syntax/src/ast/tokens.rs
> Don't mess with cursor position when adding hashes

- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
> Avoid accidently stumping over config values

- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir_def/src/body.rs
- crates/ra_ide/src/goto_definition.rs
- crates/ra_ide/src/goto_type_definition.rs
> Goto type definition improvements

- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- crates/ra_project_model/src/sysroot.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- editors/code/package.json
> Automatically reload project info on Cargo.toml changes

- crates/ra_ide/src/completion/complete_fn_param.rs
> Complete parameters more aggressively

- crates/ra_ide/src/completion/complete_fn_param.rs
> Complete params in nested fns

- crates/ra_ide/src/completion/complete_keyword.rs
- crates/ra_ide/src/completion/completion_context.rs
Unit structs are a thing
bors r+
🤖
> Don't add braces after struct

- crates/ra_ide/src/completion/complete_keyword.rs
- crates/ra_ide/src/completion/completion_context.rs
> Better name

- crates/ra_assists/src/handlers/fill_match_arms.rs
> Better caret placement when filling match arms

- crates/ra_project_model/src/cargo_workspace.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/vfs/src/lib.rs
> Reload when new example/test/etc is added

- crates/rust-analyzer/src/reload.rs
- crates/vfs-notify/src/include.rs
- crates/vfs-notify/src/lib.rs
> Don't spawn notify unnecessary

- crates/ra_hir/src/semantics.rs
- crates/ra_ide/src/completion/complete_attribute.rs
- crates/ra_ide/src/completion/complete_dot.rs
- crates/ra_ide/src/completion/complete_macro_in_item_position.rs
- crates/ra_ide/src/completion/complete_pattern.rs
- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/completion_context.rs
> Speed up completion

- crates/rust-analyzer/src/reload.rs
> Don't show error when speculatively reloading workspace

- crates/ra_prof/Cargo.toml
- crates/ra_prof/src/lib.rs
- crates/stdx/src/lib.rs
> Profiling tweaks

- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/rust-analyzer/test_data/rustc_unused_variable.txt
- crates/rust-analyzer/test_data/rustc_unused_variable_as_hint.txt
- crates/rust-analyzer/test_data/rustc_unused_variable_as_info.txt
- crates/rust-analyzer/test_data/snap_multi_line_fix.txt
> Make sure there are no commands in code actions

- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/semantics/source_to_def.rs
- crates/ra_ide/src/goto_definition.rs
closes https://github.com/rust-analyzer/rust-analyzer/issues/5042
bors r+
🤖
> Fix goto definition for type alias type parameters

- Cargo.lock
- crates/ra_syntax/Cargo.toml
- crates/ra_syntax/src/tests.rs
> Make slow test parallel

- crates/expect/Cargo.toml
- crates/ra_toolchain/Cargo.toml
- crates/vfs-notify/Cargo.toml
- crates/vfs/Cargo.toml
> no doctests

- crates/ra_hir/src/code_model.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide/src/syntax_highlighting/html.rs
- crates/ra_ide/src/syntax_highlighting/tags.rs
- crates/ra_ide/test_data/highlight_doctest.html
- crates/ra_ide/test_data/highlight_injection.html
- crates/ra_ide/test_data/highlight_strings.html
- crates/ra_ide/test_data/highlight_unsafe.html
- crates/ra_ide/test_data/highlighting.html
- crates/ra_ide/test_data/rainbow_highlighting.html
- crates/rust-analyzer/src/to_proto.rs
> Use dedicated semantic highlight tag for parameters

- crates/ra_hir_def/src/body.rs
> Bump macro recursion limit in release

- Cargo.lock
- crates/ra_hir_def/Cargo.toml
- crates/ra_hir_def/src/item_tree/lower.rs
- crates/ra_hir_def/src/item_tree/tests.rs
insta review wouldn't update the test, so ...
bors r+
🤖
> Rewrite item_tree tests to expect

- crates/ra_ide/src/display/structure.rs
- crates/rust-analyzer/src/handlers.rs
> Implementations lens for unions

- crates/ra_assists/src/handlers/change_visibility.rs
> change vis works on statics

- crates/ra_syntax/src/parsing/text_tree_sink.rs
> Comment decorations

- crates/ra_ide/src/completion/complete_attribute.rs
> Fix ignore attribute autocompletion

- Cargo.lock
Might boost compression speeds: https://github.com/jonas-schievink/adler/releases/tag/v0.2.3
> Update adler and syn

- xtask/src/release.rs
> Prefill reviewer

- Cargo.lock
- crates/ra_hir/Cargo.toml
- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/semantics/source_to_def.rs
- crates/ra_hir_def/src/lib.rs
- crates/ra_hir_ty/src/infer.rs
- crates/ra_hir_ty/src/lib.rs
- crates/ra_hir_ty/src/lower.rs
- crates/ra_tt/Cargo.toml
- crates/ra_tt/src/lib.rs
- crates/stdx/src/lib.rs
- crates/stdx/src/macros.rs
> Don't copy-paste `impl_froms` into every crate

- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir_ty/src/diagnostics.rs
- crates/ra_hir_ty/src/test_db.rs
> Cleanup visibility

- crates/expect/Cargo.toml
- crates/flycheck/Cargo.toml
- crates/paths/Cargo.toml
- crates/ra_arena/Cargo.toml
- crates/ra_assists/Cargo.toml
- crates/ra_cfg/Cargo.toml
- crates/ra_db/Cargo.toml
- crates/ra_fmt/Cargo.toml
- crates/ra_hir/Cargo.toml
- crates/ra_hir_def/Cargo.toml
- crates/ra_hir_expand/Cargo.toml
- crates/ra_hir_ty/Cargo.toml
- crates/ra_ide/Cargo.toml
- crates/ra_ide_db/Cargo.toml
- crates/ra_mbe/Cargo.toml
- crates/ra_parser/Cargo.toml
- crates/ra_proc_macro/Cargo.toml
- crates/ra_proc_macro_srv/Cargo.toml
- crates/ra_prof/Cargo.toml
- crates/ra_project_model/Cargo.toml
- crates/ra_text_edit/Cargo.toml
- crates/ra_toolchain/Cargo.toml
- crates/ra_tt/Cargo.toml
- crates/rust-analyzer/Cargo.toml
- crates/stdx/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/vfs-notify/Cargo.toml
- crates/vfs/Cargo.toml
- xtask/Cargo.toml
Some are unnecessary but it's okay to have it, I think.
cc https://github.com/rust-lang/rust/issues/74269
> Add a license field to all the crates

- .github/workflows/ci.yaml
> Check power on CI

- crates/ra_hir_ty/src/diagnostics.rs
- crates/ra_hir_ty/src/diagnostics/expr.rs
- crates/ra_hir_ty/src/diagnostics/match_check.rs
- crates/ra_hir_ty/src/test_db.rs
> Compress match checking tests

- .github/workflows/ci.yaml
It has some improvements.
Fixes #5362
> Update actions/cache to v2

- crates/ra_ide/src/completion/completion_context.rs
- crates/ra_ide/src/completion/presentation.rs
> Don't duplicate parens in patterns

- crates/ra_hir_ty/src/diagnostics.rs
- crates/ra_hir_ty/src/diagnostics/match_check.rs
- crates/test_utils/src/lib.rs
> Allow multiline annotations

- xtask/src/lib.rs
- xtask/src/not_bash.rs
- xtask/tests/tidy.rs
> Check licenses

- Cargo.lock
- crates/rust-analyzer/src/main_loop.rs
This was introduced in the latest lsp-types
> Use more explicit type for save registration

- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_def/src/nameres/tests/macros.rs
> Guard against infinite macro expansions

- crates/ra_ide/src/call_info.rs
> Off by one error when determining the active param

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
> Don't drop flycheck messages during restart

- crates/ra_hir_def/src/nameres/collector.rs
> Add missing cancellation point

- crates/ra_ide/src/diagnostics.rs
> Show fewer syntax errors

- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir_expand/src/lib.rs
> Cap macro expansion depth for IDE features

- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir_ty/src/db.rs
- crates/ra_hir_ty/src/diagnostics/unsafe_check.rs
- crates/ra_hir_ty/src/display.rs
- crates/ra_hir_ty/src/infer/expr.rs
- crates/ra_hir_ty/src/lib.rs
- crates/ra_hir_ty/src/lower.rs
- crates/ra_hir_ty/src/traits/chalk.rs
- crates/ra_hir_ty/src/traits/chalk/mapping.rs
- crates/ra_hir_ty/src/traits/chalk/tls.rs
- crates/ra_ide/src/call_hierarchy.rs
- crates/ra_ide/src/call_info.rs
- crates/ra_ide/src/inlay_hints.rs
> Align CallableDefId naming with other ids

- docs/user/manual.adoc
> More prominent link to the manual

- crates/ra_ide/src/typing.rs
- crates/ra_ide/src/typing/on_enter.rs
> Continue non-doc comments with trailing space

- crates/ra_ide/src/call_info.rs
- crates/ra_ide/src/completion/presentation.rs
> Fix out of bounds panic in active parameter

- Cargo.lock
- crates/ra_hir_def/Cargo.toml
- crates/ra_hir_def/src/import_map.rs
- crates/ra_hir_def/src/nameres/tests/mod_resolution.rs
> Remove insta for ra_hir_def

- crates/ra_assists/src/handlers/raw_string.rs
> More precise ranges in remove hashes assist

- crates/ra_assists/src/handlers/add_turbo_fish.rs
> Add turbo-fish works after `()`

- crates/rust-analyzer/src/to_proto.rs
> Don't show docs in concise signature help

- crates/flycheck/src/lib.rs
- crates/rust-analyzer/src/config.rs
> Propagate cargo.target to checkOnSave

- Cargo.lock
- crates/ra_syntax/Cargo.toml
> Bump lexer

- crates/ra_assists/src/handlers/extract_variable.rs
> Cleanup extact variable

- crates/ra_assists/src/handlers/fix_visibility.rs
Fixes #4636
I would have liked to do something about the `// FIXME: this really should be a fix for diagnostic, rather than an assist.`, but that would take a while and there's no reason not to fix this immediately.
> Replace existing visibility modifier in fix_visibility

- Cargo.lock
- crates/ra_prof/Cargo.toml
- crates/ra_prof/src/lib.rs
- crates/ra_prof/src/memory_usage.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/bin/main.rs
- docs/dev/README.md
- xtask/src/dist.rs
- xtask/src/install.rs
- xtask/src/main.rs
It worked before, but was roundabout
bors r+
🤖
> Setup global allocator in the correct crate

- crates/ra_hir_def/src/item_scope.rs
- crates/ra_hir_def/src/nameres.rs
- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_def/src/nameres/tests.rs
- crates/ra_hir_def/src/visibility.rs
- crates/ra_hir_ty/src/tests/traits.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/2736
> Support `Trait as _` imports

- Cargo.lock
- crates/ra_ide_db/Cargo.toml
- crates/ra_ide_db/src/line_index.rs
- crates/stdx/src/lib.rs
- xtask/tests/tidy.rs
> Replace superslice with API on path to stabilization

- crates/ra_cfg/src/cfg_expr.rs
- crates/ra_cfg/src/lib.rs
- crates/ra_hir_def/src/attr.rs
- crates/ra_ide/src/runnables.rs
- crates/ra_project_model/src/lib.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
> Cleanup CFG API

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/tests/heavy_tests/main.rs
- crates/rust-analyzer/tests/heavy_tests/support.rs
- crates/rust-analyzer/tests/heavy_tests/testdir.rs
> Lighter weight tempdir

- crates/ra_hir/src/semantics.rs
> Add profiling call

- README.md
- xtask/src/main.rs
- xtask/src/metrics.rs
> Link metrics

- crates/ra_prof/src/memory_usage.rs
- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/lib.rs
- xtask/src/metrics.rs
- xtask/src/not_bash.rs
> Add rustc-perf to metrics

- crates/vfs/src/file_set.rs
> Add one more test

- crates/rust-analyzer/src/cli/analysis_stats.rs
> Report type errors in metrics

- crates/ra_ide/src/folding_ranges.rs
> Fold multiline fn parameters

- crates/rust-analyzer/tests/heavy_tests/support.rs
> Bump test timeout for macs

- crates/ra_parser/src/grammar.rs
- crates/ra_parser/src/grammar/items.rs
- crates/ra_syntax/test_data/parser/ok/0007_extern_crate.rast
> Fix nameref parsing

- crates/ra_ide/src/runnables.rs
Sometimes I group tests into submodules located in the root `#[cfg(test)]` crate and want to (re)run them all at once.
This PR adds more test runnables to allow running all tests in the file via a module runner.
Not all possible module runners are added, to avoid displaying too many code lens.
before:
after (`nested_tests_0` got the runnable, `root_tests` had not):
> Allow running more tests at once via the module runners

- xtask/src/ast_src.rs
- xtask/src/codegen/gen_syntax.rs
> Owned AST IR

- crates/ra_prof/src/memory_usage.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
Gotta be optimistic about those memory usage optimizations
bors r+
🤖
> Allow negative bytes

- Cargo.lock
- crates/ra_prof/Cargo.toml
- crates/ra_prof/src/lib.rs
- crates/ra_prof/src/stop_watch.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
> Measure instructions in addition to time

- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/item_tree.rs
- crates/ra_hir_def/src/item_tree/lower.rs
- crates/ra_hir_def/src/item_tree/tests.rs
- crates/ra_parser/src/grammar/items.rs
- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/test_data/parser/inline/ok/0060_extern_crate.rast
- crates/ra_syntax/test_data/parser/ok/0007_extern_crate.rast
- xtask/src/ast_src.rs
- xtask/src/codegen/rust.ungram
> Finish extern crate grammar

- xtask/src/ast_src.rs
- xtask/src/codegen/gen_syntax.rs
> Simplify codegen

- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/ast_src.rs
- xtask/src/codegen/gen_syntax.rs
- xtask/src/codegen/rust.ungram
> Finalize structs grammar

- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/src/ast/node_ext.rs
- xtask/src/ast_src.rs
- xtask/src/codegen/rust.ungram
> Introduce GenericParam

- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/codegen/rust.ungram
> Attrs & Vis

- crates/ra_assists/src/handlers/add_custom_impl.rs
- crates/ra_hir_def/src/attr.rs
- crates/ra_ide/src/completion/complete_attribute.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/src/ast/node_ext.rs
- xtask/src/codegen/rust.ungram
> Finalize attribute grammar

- crates/ra_assists/src/handlers/add_explicit_type.rs
- crates/ra_assists/src/handlers/generate_new.rs
- crates/ra_assists/src/handlers/introduce_named_lifetime.rs
- crates/ra_hir_def/src/adt.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/item_tree.rs
- crates/ra_hir_def/src/item_tree/lower.rs
- crates/ra_hir_def/src/path/lower.rs
- crates/ra_hir_def/src/type_ref.rs
- crates/ra_ide/src/display/short_label.rs
- crates/ra_ide/src/file_structure.rs
- crates/ra_ide/src/inlay_hints.rs
- crates/ra_ide/src/references/rename.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/src/ast/traits.rs
- xtask/src/codegen/gen_syntax.rs
- xtask/src/codegen/rust.ungram
> Remove TypeAscriptionOwner

- crates/ra_assists/src/handlers/change_return_type_to_result.rs
- crates/ra_assists/src/handlers/generate_from_impl_for_enum.rs
- crates/ra_hir_def/src/adt.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/item_tree/lower.rs
- crates/ra_hir_def/src/path/lower.rs
- crates/ra_hir_def/src/type_ref.rs
- crates/ra_ide/src/display.rs
- crates/ra_ide/src/file_structure.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/codegen/rust.ungram
> Use ty to access most TypeRefs

- crates/ra_project_model/src/cfg_flag.rs
- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/handlers.rs
- crates/stdx/src/lib.rs
- crates/test_utils/src/fixture.rs
> Use split_once polyfill

- crates/ra_hir_def/src/generics.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/src/ast/node_ext.rs
- xtask/src/codegen/rust.ungram
> Finalize TypeBound grammar

- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/codegen/rust.ungram
> Finalize WhereClause gramamr

- crates/ra_assists/src/handlers/change_return_type_to_result.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/codegen/gen_syntax.rs
- xtask/src/codegen/rust.ungram
> Item is a Stmt

- crates/ra_assists/src/handlers/extract_variable.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_expand/src/db.rs
- crates/ra_ide/src/completion/patterns.rs
- crates/ra_parser/src/grammar/expressions/atom.rs
- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/test_data/parser/err/0010_unsafe_lambda_block.rast
- crates/ra_syntax/test_data/parser/err/0012_broken_lambda.rast
- crates/ra_syntax/test_data/parser/err/0039_lambda_recovery.rast
- crates/ra_syntax/test_data/parser/inline/ok/0106_lambda_expr.rast
- crates/ra_syntax/test_data/parser/inline/ok/0130_let_stmt.rast
- crates/ra_syntax/test_data/parser/inline/ok/0155_closure_params.rast
- crates/ra_syntax/test_data/parser/inline/ok/0158_lambda_ret_block.rast
- crates/ra_syntax/test_data/parser/ok/0035_weird_exprs.rast
- crates/ra_syntax/test_data/parser/ok/0044_let_attrs.rast
- xtask/src/ast_src.rs
- xtask/src/codegen/gen_syntax.rs
- xtask/src/codegen/rust.ungram
> Finalize expressions grammar

- docs/dev/README.md
> Document crates.io deps policy

- crates/ra_assists/src/handlers/change_return_type_to_result.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/codegen/gen_syntax.rs
- xtask/src/codegen/rust.ungram
> Specify literal tokens

- crates/ra_assists/src/ast_transform.rs
- crates/ra_assists/src/utils.rs
- crates/ra_hir_def/src/item_tree/lower.rs
- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide/src/file_structure.rs
- crates/ra_ide/src/references/rename.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/src/ast/node_ext.rs
- crates/ra_syntax/src/validation.rs
- xtask/src/codegen/gen_syntax.rs
- xtask/src/codegen/rust.ungram
> Cleanup impl gramamr

- crates/ra_assists/src/handlers/early_return.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- crates/ra_syntax/src/ast/node_ext.rs
- xtask/src/codegen/rust.ungram
> Finish rename

- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/bin/main.rs
and use `Display` when printing errors.
> Simplify argument parsing

- crates/ra_ide/src/folding_ranges.rs
> Fold trait declarations

- crates/ra_assists/src/assist_context.rs
- crates/ra_assists/src/handlers/expand_glob_import.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/tests/generated.rs
- crates/ra_syntax/src/ast/make.rs
closes https://github.com/rust-analyzer/rust-analyzer/issues/5557
> Add expand glob import assist

- crates/ra_hir_ty/src/diagnostics/unsafe_check.rs
Accessing or modifying a static mut is an unsafe operation. The "missing unsafe" diagnostic now tracks this.
> Account for static mut in missing unsafe diagnostic

- crates/ra_assists/src/handlers/add_turbo_fish.rs
- crates/ra_assists/src/utils.rs
- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/semantics.rs
- crates/ra_ide/src/display/short_label.rs
- crates/ra_ide/src/goto_definition.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide/src/syntax_highlighting/tests.rs
- crates/ra_ide/test_data/highlight_extern_crate.html
- crates/ra_ide_db/src/defs.rs
- crates/ra_ide_db/src/imports_locator.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
This adds syntax highlighting, hover and goto def functionality for extern crate.
Fixes #5690
> Add support for extern crate

- docs/dev/syntax.md
> Fix typos in syntax.md

- .github/workflows/ci.yaml
- Cargo.lock
- crates/ra_prof/src/memory_usage.rs
I just copied the "Rust Power" configuration, not sure if that's the best idea.
Fixes #5712
> Fix build on musl and test it in CI

- crates/ra_ide/src/inlay_hints.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/4960
Avoid displaying any param name hints like 
Those hints seem to occupy plenty of space for no apparent benefit, with their destructured content not used in the code with the function hints.
I'm not entirely sure if we should show something else than `IdentPat`s, since I don't understand some of the `Pat` variant meanings:
https://github.com/rust-analyzer/rust-analyzer/blob/a1c187eef3ba08076aedb5154929f7eda8d1b424/crates/syntax/src/ast/generated/nodes.rs#L1336-L1352
> Consider only IdentPats for param name hints

- crates/hir_ty/src/display.rs
- crates/ide/src/hover.rs
> display correctly 'impl Trait<T> + Trait<T>' #4814

- Cargo.lock
- crates/proc_macro_srv/Cargo.toml
- crates/proc_macro_srv/src/tests/mod.rs
- crates/proc_macro_srv/src/tests/utils.rs
- crates/proc_macro_test/Cargo.toml
- crates/proc_macro_test/src/lib.rs
This exports all 3 kinds of proc macros and is useful for testing.
bors r+
> Add a proc_macro_test crate

- crates/ide/src/syntax_highlighting.rs
> Some trivial local simiplifications

- docs/dev/style.md
> Add Early Return rule to style

- crates/assists/src/handlers/invert_if.rs
- crates/assists/src/utils.rs
- crates/syntax/src/ast/make.rs
> Invert if should be smart about is_some, is_none, is_ok, is_err

- .github/workflows/publish.yml
- crates/assists/Cargo.toml
- crates/base_db/Cargo.toml
- crates/cfg/Cargo.toml
- crates/flycheck/Cargo.toml
- crates/hir/Cargo.toml
- crates/hir_def/Cargo.toml
- crates/hir_expand/Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/ide/Cargo.toml
- crates/ide_db/Cargo.toml
- crates/mbe/Cargo.toml
- crates/parser/Cargo.toml
- crates/paths/Cargo.toml
- crates/proc_macro_api/Cargo.toml
- crates/proc_macro_srv/Cargo.toml
- crates/proc_macro_test/Cargo.toml
- crates/profile/Cargo.toml
- crates/project_model/Cargo.toml
- crates/rust-analyzer/Cargo.toml
- crates/ssr/Cargo.toml
- crates/stdx/Cargo.toml
- crates/syntax/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/text_edit/Cargo.toml
- crates/toolchain/Cargo.toml
- crates/tt/Cargo.toml
- crates/vfs-notify/Cargo.toml
- crates/vfs/Cargo.toml
This is the same system I set up on Chalk repo.
Every week it creates a new minor version, pushes it to github and then deploys it to crates.io.
> Do a weekly minor publish to crates.io

- crates/arena/Cargo.toml
Sorry I missed this, @matklad. Please run manually again once this is merged.
> Add TBD description to arena

- .github/workflows/publish.yml
@matklad Tested and working with publish dry run. Please run the action manually once merged.
> Rename rust_analyzer lib in the binaries before publishing

- crates/hir/src/attrs.rs
- crates/hir/src/code_model.rs
- crates/hir/src/lib.rs
> Move code_model attrs to a new module

- .github/workflows/publish.yml
There's so much trial and error regarding shells and stuff I needed to do to get this correctly working on github runner.
> Correct sed replacement when called in a bash file

- crates/text_edit/src/lib.rs
> Opportunistically check indel overlap

- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/bin/logger.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- docs/user/manual.adoc
> Allow logging to file

- crates/ide/src/runnables.rs
- crates/rust-analyzer/src/markdown.rs
> Improve fenced code block support for doctests

- .github/workflows/publish.yml
I think this is a good balance.
> Don't publish every day and do it only for release

- .github/workflows/ci.yaml
- xtask/tests/tidy.rs
> Add a test that forbids merge commits

- .github/workflows/ci.yaml
- xtask/tests/tidy.rs
>  "How I survived Git" tips 

- crates/ide/src/typing.rs
> Document VS Code setting needed for on-typing assists

- crates/rust-analyzer/src/config.rs
> default `checkOnSave.enable` to `true` in server

- Cargo.lock
- crates/hir_ty/Cargo.toml
Picks up flodiebold's infinite loop fix
> Chalk 0.25

- crates/assists/src/handlers/replace_impl_trait_with_generic.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/make.rs
> Implement "Replace `impl Trait` function argument with the named generic" assist.

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
> Add consuming modifier to lvalues that are passed by value and not Copy

- crates/assists/src/handlers/remove_dbg.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/5911
> Use better heuristics for replacement text when removing dbg!

- crates/assists/src/handlers/remove_dbg.rs
Do `dbg![2 + 2] * 5` -> `(2 + 2) * 5`
This PR also implicitly handles the `{}` case too, but I decided not to add it into the test case since it's a compiler error on the latest stable rustc.
> Properly preserve macro braces during dbg! removal

- crates/ide/src/completion/complete_trait_impl.rs
Currently, we can complete type/const/fn but only if we typed an identifier.
That is, `impl .. { fn f<|> }` has completions with all trait fn including `f`, but `impl .. { fn <|> }` doesn't provide any suggestion (even if explicit trigger it).
This PR tweak the logic of completion match to make it possible.
However, we still need to explicit trigger suggestions (`Control + Space` by default) in vscode to show. Not sure if we can make it automatically triggered after typing the space after `fn`.
Another question is that I cannot figure out why `BLOCK_EXPR` need to be checked. A block expr directly inside a impl block should be invalid, and nested items will failed to locate impl block in specific offset and skip the suggestion. Now I simply removed it and no tests are broken. …
> Complete trait impl immediately after type/const/fn

- crates/ide/src/completion/complete_qualified_path.rs
- crates/ide/src/display.rs
> inline parameters for a function description

- crates/ide/src/completion/complete_trait_impl.rs
Refactor the logic of `completion_match` to check deterministic number of ancestors instead of `token.ancestors().find_map()`.
This should fix wrong completions (https://github.com/rust-analyzer/rust-analyzer/pull/5976#issuecomment-692332191) and hopefully make completion to be faster (#6004).
More play and test? @jonas-schievink @hammypants 
If this patch works, we can avoid the revert #6005 . :disappointed:
> Avoid checking all ancestors and fix mis-completion

- editors/code/package.json
cc https://github.com/rust-analyzer/rust-analyzer/pull/5957/files
> Document "consuming" semantic tokens modifier

- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
> Fix LSP requests with no arguments

- crates/hir/src/code_model.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
git got really confused, but all I did in the first commit was unindent a few lines
> Small proc macro cleanup

- crates/rust-analyzer/src/reload.rs
Fixes #5742
Fixes #4263
or so I hope.
> Don't re-read open files from disk when reloading a workspace

- docs/dev/syntax.md
This might be a typo, so I fixed it.
> Fix typo in syntax.md

- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
Fixes the issue brought up here https://github.com/rust-analyzer/rust-analyzer/pull/5957#discussion_r486625707
cc @jonas-schievink
> Cleanup unintended unresolved reference in syntax higlighting test

- docs/dev/style.md
> More style advice

- crates/rust-analyzer/src/dispatch.rs
> More panic_context

- Cargo.lock
- crates/syntax/Cargo.toml
- crates/syntax/src/parsing/lexer.rs
> Up rustc-ap-rustc_lexer to 681

- docs/dev/style.md
> Document Clippy strategy

- crates/assists/src/utils/insert_use.rs
~~This PR includes the commit from #6102 there as I found a bug while writing that(so either merging this or both in order works) so I included a test there already which was just ignored.~~ This PR fixes that, basically inserting imports didn't consider path length for equality, so depending on the order it might insert the path before or after another import if they only differ in segment length.
~~Diff without the commit of #6102 https://github.com/rust-analyzer/rust-analyzer/commit/2d90d3937d71f9a00f3d44c15b20679215311637~~
> Fix path comparison not comparing paths correctly with unequal lengths

- crates/ide/src/lib.rs
- crates/ide/src/mock_analysis.rs
> Reduce visibiity

- crates/ide/src/references.rs
> Expectify find_references tests

- crates/assists/src/ast_transform.rs
> Simplify ast_transform

- crates/ide/src/completion/complete_postfix/format_like.rs
- xtask/src/codegen/gen_feature_docs.rs
> Fix feature name

- crates/ide/src/completion/complete_unqualified_path.rs
- crates/ide/src/completion/completion_context.rs
Fixes #6091. Let me know if the test is placed into the right file or if it is even desired.
> Correctly complete items with leading underscore

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6138
> Account for proc macro helpers when parsing attr

- PRIVACY.md
> Add some notes related to privacy and network access

- xtask/tests/tidy.rs
> Smoke test docs generation

- crates/hir_ty/src/display.rs
- crates/ide/src/inlay_hints.rs
> Fix trait object hir formatting behind pointer and references

- crates/assists/src/ast_transform.rs
- crates/assists/src/handlers/add_missing_impl_members.rs
- crates/assists/src/handlers/auto_import.rs
- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/assists/src/handlers/fill_match_arms.rs
- crates/assists/src/utils.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/path.rs
> Move ModPath->ast::Path function to IDE layer

- crates/hir_def/src/import_map.rs
> Constrain ImportMap to only store simple paths

- crates/hir_def/src/find_path.rs
> Add test makr

- crates/syntax/src/ptr.rs
> Document privacy invariant of SyntaxPtr

- docs/user/manual.adoc
> Document "*.mutable" trick in manual

- crates/syntax/src/validation.rs
- crates/syntax/test_data/parser/err/0046_ambiguous_trait_object.rast
- crates/syntax/test_data/parser/err/0046_ambiguous_trait_object.rs
- crates/syntax/test_data/parser/ok/0069_multi_trait_object.rast
- crates/syntax/test_data/parser/ok/0069_multi_trait_object.rs
> Add validation check for ambiguous trait objects

- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
> Better progress API

- docs/dev/style.md
> Add comparisons guideline to style

- crates/hir/src/semantics/source_to_def.rs
- crates/ide/src/references.rs
> Fix source_to_def for named enum variant fields

- crates/ide/src/references.rs
- crates/ide_db/src/search.rs
> Treat `ast::Name` in field patterns as use

- editors/code/src/commands.ts
> Fix resolveCodeAction request

- bors.toml
> Reduce bors timeout

- docs/dev/README.md
> Introduce S-actionable and S-unactionable labels

- crates/project_model/src/sysroot.rs
> Log around sysroot discovery

- docs/dev/style.md
> Style: default over new

- docs/dev/style.md
> Cleanup alloc advice

- crates/assists/src/handlers/auto_import.rs
> Document auto_import as a feature

- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/field_shorthand.rs
> Diagnost shorthand in patterns

- crates/assists/src/handlers/add_turbo_fish.rs
- crates/assists/src/handlers/expand_glob_import.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/imports_locator.rs
- crates/ide_db/src/search.rs
> Clarify classification API

- docs/dev/style.md
> Document awkward names

- docs/dev/style.md
> Expand code order section

- xtask/src/codegen.rs
- xtask/src/codegen/gen_assists_docs.rs
- xtask/src/codegen/gen_features.rs
- xtask/src/codegen/gen_syntax.rs
> Improve compile time a tiny bit

- docs/dev/lsp-extensions.md
As was requested in https://github.com/rust-analyzer/rust-analyzer/pull/5954#issuecomment-708325521
> Document change of 'cargo' Runnable kind in lsp-extensions.md

- Cargo.lock
> :arrow_up: xshell

- crates/hir_def/src/body.rs
- crates/hir_expand/src/db.rs
- crates/ide/src/completion/complete_dot.rs
> Complete methods when receiver is a macro

- crates/assists/src/handlers/change_visibility.rs
- crates/assists/src/handlers/fix_visibility.rs
> Change visibility works for type aliases

- Cargo.lock
> :arrow_up: crates

- crates/completion/Cargo.toml
> Try to fix publishing

- crates/assists/src/handlers/auto_import.rs
> Minor, rename feature

- docs/user/manual.adoc
> Document logging of project model

- editors/code/src/run.ts
> Check cargoExtraArgs for undefined before using

- .github/actions/github-release/main.js
> Tag release branch rather than master

- .github/workflows/release.yaml
> Fix deprecation warning

- .gitignore
- crates/hir_def/src/diagnostics.rs
- crates/hir_ty/src/diagnostics.rs
- xtask/src/codegen.rs
- xtask/src/codegen/gen_assists_docs.rs
- xtask/src/codegen/gen_diagnostic_docs.rs
- xtask/src/codegen/gen_feature_docs.rs
- xtask/src/codegen/gen_parser_tests.rs
- xtask/src/release.rs
- xtask/tests/tidy.rs
> Generate diagnostics docs

- crates/base_db/src/input.rs
- crates/project_model/src/lib.rs
> Add a hacky remidy for #6038

- crates/assists/src/utils.rs
- crates/base_db/src/fixture.rs
- crates/base_db/src/input.rs
- crates/base_db/src/lib.rs
- crates/hir/src/code_model.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/nameres.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/hover.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/prime_caches.rs
- crates/ide/src/status.rs
- crates/project_model/src/lib.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
> More type safety around names

- crates/assists/src/utils.rs
- crates/base_db/src/fixture.rs
- crates/base_db/src/input.rs
- crates/base_db/src/lib.rs
- crates/hir/src/code_model.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/nameres.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/hover.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/prime_caches.rs
- crates/ide/src/status.rs
- crates/project_model/src/lib.rs
- crates/project_model/src/project_json.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- docs/user/manual.adoc
> Support Display name in project.json

- crates/assists/src/handlers/fill_match_arms.rs
- crates/assists/src/handlers/generate_from_impl_for_enum.rs
- crates/assists/src/utils.rs
- crates/ide/src/inlay_hints.rs
> Don't rely on display names in inlay_hints

- crates/assists/src/handlers/generate_impl.rs
> generate assist respect cfg attributes 

- crates/ide/src/inlay_hints.rs
This causes `foo.clone()` parameters to be handled as if they were just `foo` parameters for inlay hint logic.
Fixes #6315
> hide paramater inlay hints for cloned vars if applicable

- crates/rust-analyzer/src/dispatch.rs
- crates/stdx/src/panic_context.rs
> Fix panic context

- crates/hir_ty/src/traits/chalk/mapping.rs
The lifetime placeholder can be replaced by the static lifetime, and for array
sizes we should just be using a concrete const.
> Get rid of FAKE_PLACEHOLDER

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
> Fix unary minus highlighting

- crates/assists/src/lib.rs
> Better ordering of assists

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
> Highlight never type as BuiltinType

- editors/code/src/inlay_hints.ts
> Also set textDecoration: none on inlay hints

- editors/code/rust.tmGrammar.json
> Textmate grammar: allow comments in attributes

- crates/rust-analyzer/src/main_loop.rs
> Remove unnecessary clone

- crates/rust-analyzer/src/main_loop.rs
The previous implementation could try to create a progress bar when one
was already registered.
> Fix coalescing of prime_caches updates

- crates/assists/src/handlers/convert_integer_literal.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/expr_ext.rs
> Fix overflow panic in convert_interger_literal assist

- crates/project_model/src/sysroot.rs
> Ignore RUST_SRC_PATH if it is set to invalid value

- docs/dev/style.md
> don\t indent tests

- crates/syntax/src/parsing/lexer.rs
> Minor, cleanup style

- crates/completion/src/completions/postfix.rs
Nothing much to explain. Just a simple addition. I was recently doing some refactoring and this would have made it a bit more faster.
> Add some postfix snippet

- crates/assists/src/assist_context.rs
- editors/code/src/snippets.ts
> Support multiple file edits in AssistBuilder

- crates/syntax/src/algo.rs
> Fix debug for SyntaxRewriter

- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/assists/src/tests.rs
> Support multi-file assist tests

- crates/assists/src/assist_context.rs
- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
> Fix panic when extracting struct

- crates/rust-analyzer/src/config.rs
> Be more pedantic when checking codeAction/resolve support

- crates/syntax/src/ast.rs
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/parsing/text_tree_sink.rs
- crates/syntax/test_data/parser/ok/0037_mod.rast
> Fix attachment of inner doc comments

- crates/assists/src/handlers/remove_unused_param.rs
Also adds a test to check that it removes unused params across files.
> Support qualified function calls in remove_unused_param

- editors/code/package-lock.json
- xtask/src/install.rs
> Upgrade version of npms lockfile

- crates/completion/src/completions/keyword.rs
> Don't complete keywords in struct initializers

- crates/rust-analyzer/src/handlers.rs
> Prepare to recompute completions on every keystroke

- crates/base_db/src/input.rs
- crates/project_model/src/sysroot.rs
- crates/project_model/src/workspace.rs
> Cleanup project model

- crates/assists/src/handlers/unwrap_block.rs
> Use standard code style for test fixtures

- crates/cfg/src/lib.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/reload.rs
> Simpify project_model

- crates/ide/src/references/rename.rs
> Minor, import style

- crates/assists/src/handlers/ignore_test.rs
> Avoid string allocations in ignore_test

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/to_proto.rs
> New lsp-types to fix versioning

- crates/hir/src/lib.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/status.rs
This is needed to collect and report expansion errors later.
> hir_expand: propagate expansion errors

- crates/flycheck/Cargo.toml
- crates/proc_macro_srv/Cargo.toml
- crates/project_model/Cargo.toml
See: https://github.com/oli-obk/cargo_metadata/pull/142#issuecomment-733653275
> Pin cargo_metadata

- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/incremental.rs
> Fix def map volatility with `#[cfg]` diagnostics

- crates/rust-analyzer/src/main_loop.rs
Not sure why CI didn't catch this...
bors r+
> Remove unused import

- crates/mbe/src/lib.rs
- crates/tt/src/lib.rs
> Simplify error formatting

- crates/completion/src/completions/pattern.rs
- crates/completion/src/context.rs
> Complete struct in irrefutable let

- crates/hir/src/code_model.rs
> Remove single r#trait identifier usage

- crates/assists/src/handlers/infer_function_return_type.rs
`Add this function's return type` becomes `Add this closure's return type` for closures. This makes it more obvious that we are indeed planning on modifying the closure and not its containing function.
> Don't call a closure a function in the infer_function_return_type assist label

- Cargo.lock
- crates/assists/src/utils.rs
- crates/assists/src/utils/insert_use.rs
- crates/completion/src/item.rs
- crates/completion/src/render/enum_variant.rs
- crates/completion/src/render/function.rs
- crates/completion/src/render/macro_.rs
- crates/syntax/Cargo.toml
- crates/syntax/src/algo.rs
During https://github.com/rust-analyzer/rust-analyzer/issues/6612 investigation, had added a few more profiling points and considered that they can be useful later, ergo the PR.
> Profile completions better

- crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6596
bors r+
> Downgrade "failed to load" error to warning

- crates/ide/src/goto_definition.rs
> Support "go to definition" for SelfParams

- crates/ide/src/hover.rs
Show the type of `self` when hovering the token in a `SelfParam`.
> Show type of self param on hover

- crates/ide/src/goto_definition.rs
Also reverts #6660, instead of showing the type it now works like it does for names by returning the declaration we are already on. This for example enables VSCode to show all references(#6665) when executing `go to definition` on the declaration.
> Support 'go to definition' for self

- crates/assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ide_db/src/helpers/insert_use.rs
Finally figured out why nested imports don't properly merge in some cases
> Fix use merging not using the first path segment

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
> builtin_macro: move to `mbe::ExpandResult`

- crates/completion/src/completions/qualified_path.rs
- crates/completion/src/completions/trait_impl.rs
- crates/completion/src/render/builder_ext.rs
- crates/completion/src/render/function.rs
- crates/hir/src/code_model.rs
- crates/ide/src/references/rename.rs
> Place cursor correctly when completing assoc fns with self

- crates/completion/src/completions/postfix.rs
> Trigger .let postfix snippet in the middle of the block

- crates/hir_def/src/body/tests.rs
> Test macro diagnostics in body lowering

- crates/proc_macro_api/src/process.rs
> Minor proc macro cleanups

- crates/rust-analyzer/src/cli/diagnostics.rs
The `diagnostics` subcommand used to only compute diagnostics for `lib.rs` / the root module of all workspace crates. This fixes it and makes it look at every module.
bors r+
> Fix `diagnostics` subcommand, look at all modules

- crates/proc_macro_api/src/process.rs
Now the thread managing IPC will exit when the server process crashes instead of respawning it.
Closes https://github.com/rust-analyzer/rust-analyzer/issues/6707
bors r+
> Don't respawn proc macro server on crash

- crates/hir/src/code_model.rs
- crates/ide_db/src/defs.rs
> Add slightly more profiling details

- crates/project_model/src/cargo_workspace.rs
> Pass `--target` when loading out dirs from check

- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/handlers.rs
> Open Cargo.toml opens more specific manifest

- docs/dev/README.md
> fix typo of README in dev

- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/test_db.rs
> Add test for `$crate` in builtin macros

- crates/proc_macro_srv/src/lib.rs
> Better error when a proc macro panics

- crates/hir_def/src/body.rs
> Increment recursion count in Expander only on success

- crates/ide/src/diagnostics/fixes.rs
> Fix MissingFields DiagnosticFix trigger range

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- docs/user/manual.adoc
- xtask/src/release.rs
> Include config into the manual

- crates/base_db/src/lib.rs
- crates/hir_def/src/nameres/mod_resolution.rs
- crates/hir_def/src/test_db.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/test_db.rs
- crates/hir_ty/src/test_db.rs
- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/fixes.rs
- crates/ide/src/references/rename.rs
- crates/ide_db/src/lib.rs
- crates/ide_db/src/source_change.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/vfs/src/anchored_path.rs
- crates/vfs/src/file_set.rs
- crates/vfs/src/lib.rs
> Introduce anchored_path

- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/vfs/src/lib.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6622
Let's hope I got it right this time, but I feel like I slowly begin to understand the main loop logic.
bors r+
> Fix "no value set for FileTextQuery(FileId(..))"

- crates/hir_ty/src/display.rs
This could be useful for diagnostics, but isn't used right now
bors r+
> Implement HirDisplay for FnSig

- crates/hir_expand/src/builtin_macro.rs
fixes https://github.com/rust-analyzer/rust-analyzer/issues/6728
bors r+
> format_args: handle key-value arguments

- crates/ide/src/diagnostics/fixes.rs
Fixes the sub-issue mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/4058#issuecomment-741919659
bors r+
> Fix FileId computation in IncorrectCase fix

- crates/assists/src/assist_config.rs
- crates/assists/src/handlers/merge_imports.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/config.rs
- crates/completion/src/item.rs
- crates/completion/src/lib.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
- crates/rust-analyzer/src/config.rs
- docs/dev/style.md
> Normalize spelling to American English

- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/item.rs
- crates/completion/src/lib.rs
- crates/completion/src/test_utils.rs
> Minor, more orthogonal code

- crates/hir/src/diagnostics.rs
- crates/hir_ty/src/diagnostics.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/fixes.rs
> Add native "remove this semicolon" diagnostics

- docs/user/manual.adoc
> Improve docs for building from source

- xtask/src/metrics.rs
Let's see if this fixes https://github.com/rust-analyzer/rust-analyzer/issues/6808
bors r+
> Fix memory usage metrics

- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/lib.rs
- xtask/src/metrics.rs
This is getting hit during metrics collection.
bors r+
> Avoid panic when collecting memory metrics

- crates/mbe/src/mbe_expander/matcher.rs
- crates/mbe/src/tests.rs
> negative sign matching in mbe matching for literal

- crates/hir_ty/src/diagnostics.rs
Closes https://github.com/rust-analyzer/rust-analyzer/pull/6769#discussion_r540150066
> Added "Remove this semicolon" test

- docs/user/manual.adoc
same as https://github.com/rust-analyzer/rust-analyzer.github.io/pull/81 , just against the correct repository this time
> Docs: Explain manual installation in VS Code

- docs/user/manual.adoc
> Link config source

- crates/hir/src/code_model.rs
- crates/hir/src/from_id.rs
- crates/hir/src/has_source.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/keys.rs
This is stuff required for the lifetime references/definitions PR. I pulled this out to make it easier to review as well as because there is one thing that still has to be addressed which can be found in the review comments.
> Add LifetimeParam resolving to Semantics

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/name.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/6747
bors r+
> Implement `module_path!()`

- crates/assists/src/handlers/reorder_fields.rs
- docs/dev/style.md
> Use standard test style

- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_expand/src/db.rs
- crates/hir_ty/src/tests/regression.rs
> Expand statements for macros in lowering

- crates/hir/src/code_model.rs
- crates/hir/src/from_id.rs
- crates/hir/src/has_source.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/hover.rs
- crates/ide/src/runnables.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/search.rs
> Rename ImplDef -> Impl

- crates/ide/src/call_hierarchy.rs
- crates/ide/src/display.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/file_structure.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/lib.rs
- crates/ide/src/parent_module.rs
- crates/ide/src/references.rs
- crates/ide/src/runnables.rs
- crates/ide_db/src/symbol_index.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Don't expose SyntaxKind from IDE API

- crates/ide/src/display/navigation_target.rs
- crates/ide/src/references.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/format.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/rust-analyzer/src/to_proto.rs
> Deduplicate highlight tags and symbol kinds

- crates/hir_def/src/attr.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/hir_def/src/path.rs
- crates/hir_expand/src/name.rs
> Minor `#[derive]` resolution cleanup

- crates/hir_def/src/attr.rs
> Remove resolved FIXME

- crates/hir_def/src/attr.rs
> Make attribute API more private

- crates/hir_def/src/attr.rs
This will be useful for emitting diagnostics pertaining to a specific attribute
> Add API for mapping `Attr` back to its syntax node

- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
- crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
> Make sure that HighlightModifier::ALL is synchronized with enum

- crates/ide/src/references/rename.rs
> Add test_rename_bind_pat

- crates/mbe/src/tests.rs
- crates/parser/src/grammar.rs
- crates/parser/src/lib.rs
> Use pattern_single instead of pattern in mbe pat

- docs/user/manual.adoc
> Document the version requirements for building from source

- crates/ide/src/references.rs
> Acquire original text range when searching for references

- editors/code/src/main.ts
> Remove outdated FIXME

- editors/code/src/main.ts
> Don't download x64 binaries on non-Mac arm64

- crates/rust-analyzer/src/config.rs
- docs/user/manual.adoc
> Document, how to view config in effect

- crates/assists/src/handlers/extract_module_to_file.rs
- crates/hir_def/src/nameres/mod_resolution.rs
> Don't think that /submod.rs is /mod.rs

- crates/syntax/src/ast/make.rs
> Document `make` module design

- crates/hir/src/code_model.rs
- crates/ide/src/diagnostics.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6970
> Prevent multiple incorrect case diagnostics in functions

- docs/dev/style.md
> Improve commit message style

- crates/hir_def/src/nameres/tests/macros.rs
- crates/mbe/src/tests.rs
- crates/parser/src/grammar.rs
> Fix mbe fail to pass expr with attr

- crates/assists/src/handlers/extract_variable.rs
- crates/assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/assists/src/utils/import_assets.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/lib.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/nameres.rs
- crates/ide/src/lib.rs
- crates/ide_db/src/imports_locator.rs
- crates/rust-analyzer/src/handlers.rs
r? @Veykril 
TBH I'm not sure this is worth it, but the other `Query` was already taking a `String`.
> Avoid a couple of allocations

- editors/code/src/commands.ts
> Use applySnippetWorkspaceEdit again for actions, allow it to create files

- crates/mbe/src/lib.rs
- crates/mbe/src/mbe_expander/matcher.rs
- crates/mbe/src/mbe_expander/transcriber.rs
- crates/mbe/src/parser.rs
Inspire by #5426 , this PR refactor out the parsing code such that it only parsed on `mbe::Rule`, but not on invocations. 
However, it just improve the overall performance unnoticeablely :(
> Refactor mbe parsing code

- crates/hir_ty/src/infer/expr.rs
> Allow spurious warning from rust-lang/rust#80501

- crates/mbe/src/lib.rs
> Remove unused clones in mbe

- crates/proc_macro_srv/src/rustc_server.rs
> Fix spacing bug in proc-macro TokenStream::to_string

- crates/completion/src/completions/attribute.rs
- crates/hir_def/src/nameres.rs
- crates/ssr/src/matching.rs
> Remove some unneeded string allocations

- crates/hir_expand/src/builtin_macro.rs
> Fix `==` in in format causes mismatched-arg-count

- crates/rust-analyzer/src/handlers.rs
In order to fix #6052 and to fix #4249 this PR installs `rustfmt` using `rustup` if `rustfmt --help` fails.
In theory we ought to memoise the attempts (both the `--help` and the installation) so that we don't keep retrying something which will fail (e.g. if nightly is missing rustfmt), but this is a first-pass for opinions.
In order to make it possible to notify the user of what happened, I added a facility for `GlobalStateSnapshot` to send *messages* to the client indicating what happened.  There may be a cleaner way to do this as well but I wasn't sure exactly what might be best given this is my first time in this codebase.
It may be worth, longer term, working with `rustup` to provide a way to detect a missing component binary since `rustup` returns `1` if `rustfmt` is not installed, …
> Install rustfmt if needed during formatting request

- crates/project_model/src/cargo_workspace.rs
Context: I was having an error in my workspace config that I couldn't figure out without this added output. In particular, I have a Code workspace with a docs folder and one of my top level crates [which each have their own custom target], which was picking up the Cargo workspace level Cargo.toml incorrectly [which in my project should not ever be used for the editor], and ultimately had to override it with `linkedProjects`.
Here's a sample of the changed output:
```
[INFO rust_analyzer::main_loop] handle_event(Workspaces([Err(Failed to read Cargo metadata from Cargo.toml file /home/jade/dev/mu/Cargo.toml, cargo 1.50.0-nightly (75d5d8cff 2020-12-22)
Caused by:
0: Failed to run `cargo metadata --manifest-path /home/jade/dev/mu/Cargo.toml` in `/home/jade/dev/mu`
1: Error during execution of …
```
> add working dir to cargo metadata fail messages

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/diff.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/tests/rust-analyzer/main.rs
> Split textDocument/formatting TextEdit with diff

- xtask/tests/tidy.rs
> deny_clippy test works with cfg_attr

- crates/assists/src/ast_transform.rs
- crates/hir/src/code_model.rs
- crates/hir/src/from_id.rs
- crates/hir/src/has_source.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/keys.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/resolver.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/simple.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/hover.rs
- crates/ide/src/references.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/ide_db/src/defs.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
> Implement ConstParams for HIR

- xtask/src/dist.rs
> Stop using beta toolchain in xtask dist

- crates/hir_expand/src/eager.rs
- crates/hir_ty/src/tests/macros.rs
> Fixed nested eager macro bug

- crates/hir_def/src/path/lower.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/hir_ty/src/tests/macros.rs
- crates/mbe/src/mbe_expander/matcher.rs
- crates/mbe/src/mbe_expander/transcriber.rs
- crates/mbe/src/parser.rs
Reverts rust-analyzer/rust-analyzer#7133
It caused a fairly significant performance regression.
bors r+
> Revert "Proper handling $crate and local_inner_macros"

- crates/ide/src/display/short_label.rs
- crates/ide/src/hover.rs
- crates/rust-analyzer/src/handlers.rs
> Implement hover for ConstParam

- crates/assists/src/handlers/pull_assignment_up.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
> rename exrtract_assignment -> pull

- .github/workflows/release.yaml
> Fix x86_64-pc-windows-msvc artifact name

- editors/code/package.json
- editors/code/src/config.ts
> Rename extension config

- crates/hir_expand/src/proc_macro.rs
- crates/mbe/src/mbe_expander/matcher.rs
- crates/mbe/src/subtree_source.rs
- crates/mbe/src/syntax_bridge.rs
- crates/tt/src/buffer.rs
> Refactor mbe to reduce clone and copy

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
> Allow `#anchor` linking of config options

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/rust-analyzer/tests/rust-analyzer/support.rs
> More maintainable caps config

- crates/rust-analyzer/src/handlers.rs
> Normalize line endings when formatting

- crates/completion/src/completions/attribute.rs
Solve #7167.
I removed the optional args for the attributes ```deprecated```, ```must_use``` and ```should_panic```.
I also updated their respective tests.
Please let me know if I missed something.
> Attribute completion

- crates/ide/src/hover.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/runnables.rs
- crates/project_model/src/project_json.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/rust-analyzer/tests/rust-analyzer/main.rs
- crates/rust-analyzer/tests/rust-analyzer/support.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> Speed up snapshoting

- crates/assists/src/handlers/move_module_to_file.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
> Better target for move module

- crates/profile/src/stop_watch.rs
> Less confusing instr stat

- crates/rust-analyzer/tests/rust-analyzer/main.rs
> More readable test

- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/config.rs
- crates/completion/src/lib.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
> YAGNI active_resolve_capabilities

- crates/assists/src/assist_config.rs
- crates/assists/src/assist_context.rs
- crates/assists/src/handlers/generate_function.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests.rs
- crates/assists/src/utils.rs
- crates/completion/src/completions/postfix.rs
- crates/completion/src/completions/postfix/format_like.rs
- crates/completion/src/completions/snippet.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/config.rs
- crates/completion/src/item.rs
- crates/completion/src/lib.rs
- crates/completion/src/render.rs
- crates/completion/src/render/function.rs
- crates/completion/src/render/pattern.rs
- crates/completion/src/test_utils.rs
- crates/ide/src/lib.rs
- crates/ide_db/src/helpers.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/to_proto.rs
> Align config's API with usage

- xtask/tests/tidy.rs
> Extend git evacuation procedure

- crates/assists/src/handlers/fix_visibility.rs
- crates/ide/src/diagnostics/fixes.rs
- crates/ide/src/hover.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/handlers.rs
> Remove some stale deprecations

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> Use american spelling for config

- editors/code/src/main.ts
> Don't update the server if managed by the user

- crates/assists/src/handlers/flip_comma.rs
- crates/base_db/src/fixture.rs
- crates/ide/src/join_lines.rs
- crates/ide/src/syntax_highlighting/injection.rs
- crates/ide/src/syntax_highlighting/test_data/injection.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/test_utils/src/lib.rs
> Better fixture highlight

- docs/dev/style.md
> Document `std::ops` style

- docs/dev/style.md
> Styleguide readability

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/flycheck/src/lib.rs
- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/stdx/src/lib.rs
> Show progress for fetching workspace (cargo-metadata and loadOutDirsFromCheck)

- crates/hir/src/diagnostics.rs
- crates/hir_def/src/path.rs
- crates/hir_expand/src/name.rs
- crates/hir_ty/src/diagnostics.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/fixes.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7095
> Add fix to wrap return expression in Some

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/inject.rs
> Refactor highlighting

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/format.rs
> Replace state with function

- crates/ide/src/syntax_highlighting/highlights.rs
- crates/ide/src/syntax_highlighting/injector.rs
- crates/stdx/src/lib.rs
> Cleaner API

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/op_queue.rs
- crates/rust-analyzer/src/reload.rs
> Fix progress token is already registered crash

- crates/assists/src/handlers/remove_dbg.rs
- crates/completion/src/completions/attribute.rs
- crates/completion/src/completions/trait_impl.rs
- crates/completion/src/patterns.rs
- crates/ide/src/references.rs
- crates/ide/src/syntax_highlighting/macro_rules.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/src/grammar/items.rs
- crates/parser/src/grammar/items/traits.rs
- crates/parser/src/grammar/patterns.rs
- crates/parser/src/grammar/type_params.rs
- crates/syntax/src/ast/node_ext.rs
https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/style.md#token-names
> Replace SyntaxKind usage with T! macro where applicable

- crates/rust-analyzer/src/cli/analysis_stats.rs
> Make default memory stats less verbose

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
> Honor client's dynamic registration caps

- crates/completion/src/completions/postfix.rs
> Postfix completions like ifl now works with references

- crates/ide/src/goto_definition.rs
- crates/ide/src/runnables.rs
> Goto for inner doc links works for module inner doc comments

- crates/completion/src/completions/dot.rs
- xtask/tests/tidy.rs
Same as `check_todo` but for dbg! macro
r? @matklad
> Check dbg! macro in tidy_test

- docs/dev/style.md
> Encourage gifs

- xtask/src/main.rs
> Add build benchmark xtask command

- crates/ide/src/references/rename.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Don't show internal server error on rename

- Cargo.lock
- crates/ide/src/syntax_highlighting/highlights.rs
- crates/ide/src/syntax_highlighting/injector.rs
> Use upstream TextSize API

- crates/assists/src/handlers/reorder_impl.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
> Add quick fix to sort impl methods by trait definition

- crates/vfs/src/anchored_path.rs
- crates/vfs/src/file_set.rs
- crates/vfs/src/lib.rs
- crates/vfs/src/loader.rs
- crates/vfs/src/path_interner.rs
- crates/vfs/src/vfs_path.rs
This documents every item in the `vfs` crate, except for a few private, windows-specific items.
> vfs documentation

- crates/mbe/src/tests.rs
- crates/parser/src/parser.rs
Fixes #7207
Added `L_DOLLAR` in `ITEM_RECOVERY_SET` , but I don't know whether it is a good idea.
r? @matklad
> Fixed expr meta var after path colons in mbe

- crates/project_model/src/cargo_workspace.rs
https://github.com/rust-analyzer/rust-analyzer/issues/5040#issuecomment-759853153
> Use --workspace when loading extern resources

- crates/completion/src/completions/unqualified_path.rs
> Add a test for #7110

- Cargo.lock
- crates/profile/Cargo.toml
- crates/profile/src/lib.rs
- crates/stdx/Cargo.toml
- crates/stdx/src/lib.rs
> Make printin the backtrace more convenient

- crates/completion/src/completions/qualified_path.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/item.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/stdx/src/lib.rs
- crates/stdx/src/macros.rs
- crates/syntax/src/display.rs
- docs/dev/style.md
> Introduce more appropriate assertion mechanism

- Cargo.lock
- lib/arena/Cargo.toml
> bump arena

- crates/completion/src/completions/keyword.rs
- crates/completion/src/context.rs
> Insert `;` when completing keywords in let

- crates/assists/src/assist_context.rs
- crates/completion/src/context.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/extend_selection.rs
- crates/ide/src/join_lines.rs
- crates/ide/src/syntax_tree.rs
- crates/syntax/src/algo.rs
- crates/syntax/src/parsing/reparsing.rs
> Remove useless wrapper

- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt
- crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
Should fix https://github.com/rust-analyzer/rust-analyzer/issues/6851
> Don't duplicate rustc diagnostics fixes

- crates/assists/src/handlers/unmerge_use.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/syntax/src/ast/make.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/7185
> Add Unmerge Use assist

- Cargo.lock
> Simpler and faster rowan

- Cargo.lock
- crates/hir_expand/src/ast_id_map.rs
- crates/syntax/Cargo.toml
> When building an item-tree, keep fewer nodes in memory

- Cargo.lock
- crates/hir_def/Cargo.toml
- crates/hir_expand/Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/profile/Cargo.toml
- crates/project_model/Cargo.toml
- lib/arena/Cargo.toml
> :arrow_up: arena

- crates/completion/src/completions/keyword.rs
> Less annoying `mod` completion

- crates/parser/src/syntax_kind.rs
> Add missing inlines

- crates/project_model/src/lib.rs
- crates/project_model/src/rustc_cfg.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/reload.rs
> Avoid blocking the main loop when editing Cargo.toml

- crates/proc_macro_api/Cargo.toml
> Enable serde_json unbounded_depth feature

- crates/completion/src/item.rs
> Use assert_never properly

- crates/hir_def/src/item_tree.rs
> Remove `item_tree::Expr`

- crates/ide/src/references.rs
> Add test for reference search on self declaration param

- Cargo.lock
- crates/proc_macro_srv/src/tests/fixtures/test_serialize_proc_macro.txt
Update test_serialize_proc_macro for new serde version.
I'm assuming the test update is legitimate but I would like someone to double check since I'm not familiar with this area.
> cargo update

- crates/ide/src/diagnostics/fixes.rs
- crates/ide/src/lib.rs
- crates/ide/src/references/rename.rs
- crates/rust-analyzer/src/handlers.rs
> Remove obsolete RangeInfo usage in rename

- crates/assists/src/handlers/auto_import.rs
- crates/assists/src/handlers/qualify_path.rs
- crates/completion/src/completions/flyimport.rs
- crates/completion/src/config.rs
- crates/completion/src/item.rs
- crates/completion/src/lib.rs
- crates/completion/src/render.rs
- crates/completion/src/test_utils.rs
- crates/hir/src/code_model.rs
- crates/hir_def/src/import_map.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/lib.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_db/src/imports_locator.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Propose trait associated items and autoimport traits on completion

- Cargo.lock
- crates/parser/src/grammar/items/traits.rs
- crates/syntax/test_data/parser/inline/ok/0161_impl_def_const.rast
- crates/syntax/test_data/parser/inline/ok/0161_impl_def_const.rs
> Parse `impl const Trait`

- crates/completion/src/completions/attribute.rs
> Delete optional arg for inline attr and add doc alias attr completion

- crates/assists/src/handlers/qualify_path.rs
- crates/completion/src/completions/flyimport.rs
- crates/completion/src/render.rs
- crates/completion/src/render/const_.rs
- crates/completion/src/render/function.rs
- crates/completion/src/render/type_alias.rs
- crates/completion/src/test_utils.rs
- crates/hir/src/code_model.rs
TIL that there are two kinds of deprecation tags and a few details about String methods.
> Show deprecated completions for deprecated traits

- crates/ide/src/hover.rs
- crates/ide/src/runnables.rs
> Support runnables in macros

- crates/mbe/src/syntax_bridge.rs
Reduces HygieneFrameQuery's memory usage by to another 10 MB.
cc #7331
bors r+
> Reduce TokenMap size

- crates/completion/src/completions/unqualified_path.rs
- crates/hir/src/code_model.rs
- crates/hir/src/semantics.rs
- crates/hir_def/src/resolver.rs
> Show const params in completions

- crates/ide/src/runnables.rs
- docs/dev/style.md
> Dont show runnables from nested mods

- crates/hir/src/code_model.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/lang_item.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/test_db.rs
- crates/hir_ty/src/diagnostics.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/test_db.rs
- crates/ide_db/src/symbol_index.rs
This gives us more freedom to change the implementation for name resolution within block expressions.
bors r+
> Make public DefMap fields private

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_expand/src/ast_id_map.rs
To do name resolution within block expressions, we need to know which inner items are located inside each block expression. This adds such a mapping to `ItemTree`, replacing the previous one, which was seemingly unused other than to access all the inner items.
This also assigns `AstId`s to block expressions, which is needed to store the mapping in salsa.
> ItemTree: store a mapping from blocks to inner items

- crates/hir_def/src/body.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/resolver.rs
> DefMap: hide remaining crate-visible fields

- Cargo.lock
- crates/hir_ty/Cargo.toml
Fixes #6945
Fixes #6812
bors r+
> Bump chalk

- xtask/src/codegen/gen_assists_docs.rs
- xtask/src/codegen/gen_diagnostic_docs.rs
- xtask/src/codegen/gen_feature_docs.rs
- xtask/src/lib.rs
- xtask/tests/tidy.rs
> fix mega bug

- crates/hir_def/src/nameres/tests/block.rs
> Add test for nameres in nested blocks

- crates/hir_def/src/nameres/tests/block.rs
> Remove unnecessary annotations from tests

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/data.rs
Reverts rust-analyzer/rust-analyzer#7380, since it broke stuff
bors r+
> Revert "Make use of `block_def_map` in body lowering"

- crates/hir_def/src/body/tests.rs
> Add test for path resolution bug

- crates/hir_def/src/item_tree/lower.rs
> Remove unused field

- crates/project_model/src/build_data.rs
- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/lib.rs
- crates/project_model/src/workspace.rs
It refactors for separating logic for build script specific data. 
bors r+
> Refactor build script specific data

- crates/project_model/src/build_data.rs
> Minor fix for #7387

- crates/ide/src/goto_definition.rs
> Remove approximate goto def

- crates/hir/src/attrs.rs
- crates/hir_def/src/resolver.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/hover.rs
Fix #5546 
The intra-doc link doesn't work fine for trait associated method.
> Fix broken link in intra-doc

- docs/dev/style.md
> Style: use the right string

- docs/dev/style.md
> Promote marks

- crates/assists/src/handlers/add_lifetime_to_type.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
> Add assist: add lifetime to type

- crates/completion/src/completions/dot.rs
- crates/completion/src/completions/flyimport.rs
- crates/completion/src/completions/qualified_path.rs
- crates/completion/src/completions/trait_impl.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/item.rs
- crates/completion/src/lib.rs
- crates/completion/src/render.rs
- crates/completion/src/render/function.rs
- crates/rust-analyzer/src/bin/main.rs
> More annoying asserts

- crates/stdx/src/lib.rs
bors r+
🤖
closes https://github.com/rust-analyzer/rust-analyzer/issues/7397
> stave off zombies

- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/nameres/tests/diagnostics.rs
> Fix error when using "extern crate self as"

- crates/hir/src/diagnostics.rs
- crates/hir_def/src/path.rs
- crates/hir_expand/src/name.rs
- crates/hir_ty/src/diagnostics.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/fixes.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/1725
> Add diagnostic for filter_map followed by next

- crates/completion/src/render.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide_db/src/symbol_index.rs
> Handle unions in symbol search

- crates/parser/src/grammar/items/consts.rs
- crates/syntax/src/validation.rs
- crates/syntax/test_data/parser/err/0047_mutable_const_item.rast
- crates/syntax/test_data/parser/err/0047_mutable_const_item.rs
- crates/syntax/test_data/parser/ok/0024_const_item.rast
- crates/syntax/test_data/parser/ok/0024_const_item.rs
> Add validation for mutable const items

- crates/hir_expand/src/builtin_macro.rs
> Unquote strings when expanding concat!

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/generated_config.adoc
- editors/code/package.json
- editors/code/src/config.ts
> Add References CodeLens.

- docs/dev/README.md
> Fix RA_LOG example in dev docs

- docs/dev/style.md
> Fix typo in style guide

- docs/dev/README.md
> Document design label

- crates/assists/src/handlers/fill_match_arms.rs
- crates/assists/src/handlers/replace_if_let_with_match.rs
- crates/assists/src/utils.rs
- crates/ide_db/src/ty_filter.rs
> if_let_match: don't assume happy path

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> Remove the need to manually sync config in package.json

- Cargo.lock
- crates/completion/src/item.rs
- crates/ide/src/references/rename.rs
- crates/ide_db/src/source_change.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/stdx/Cargo.toml
- crates/stdx/src/lib.rs
- crates/stdx/src/macros.rs
- docs/dev/style.md
- xtask/src/install.rs
> Make always-assert crate reusable

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_expand/src/ast_id_map.rs
> add more counts

- Cargo.lock
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_expand/src/ast_id_map.rs
- crates/profile/Cargo.toml
- crates/rust-analyzer/src/bin/args.rs
> Squelch a warning

- crates/project_model/src/build_data.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7462
bors r+
> Export `CARGO` for proc. macros

- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
> Fix legacy macro resolution in block expressions

- crates/assists/src/handlers/fill_match_arms.rs
Fixes #3936
The indentation is a bit off, but I don't think it's worth trying to fix that up until we have a proper formatting thing set up, as this most likely requires some hand picked specializing making the implementation worse to read(Assuming this can even be fixed for all cases by hardcoding indentation fixes).
bors r+
> Enable fill_match_arms in macros

- crates/rust-analyzer/tests/rust-analyzer/support.rs
> Easier to debug timeouts in tests

- crates/rust-analyzer/tests/rust-analyzer/support.rs
> Use RA_LOG in tests

- crates/flycheck/src/lib.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/reload.rs
> Make logger-based debugging more pleasant

- Cargo.lock
> :arrow_up: cm

- crates/hir_def/src/nameres/tests/block.rs
> block_def_map: add a few macro tests

- crates/completion/src/completions/flyimport.rs
> Forbid flyimport completions in use statements

- crates/mbe/src/expander.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/tests.rs
Handle parse error in rule parsing instead of matching in mbe.
bors r+
> Simplify mbe match error.

- crates/rust-analyzer/src/bin/args.rs
> Add --print-config-schema to help

- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/parser.rs
> Simpilfy mbe parsing

- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/hir_ty/src/lib.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
> Classify function calls as functions when shadowed by types

- crates/syntax/src/ast/token_ext.rs
> Fix ast::String::value not properly escaping in some cases

- docs/dev/README.md
> Explain what to do if a release fails

- docs/user/manual.adoc
> Improve nvim-lsp setup instructions

- Cargo.lock
- crates/proc_macro_api/Cargo.toml
- crates/proc_macro_api/src/process.rs
Fixes #7510, but not the root cause.
> Reap proc macro server instances

- crates/rust-analyzer/src/reload.rs
> Only allow one proc-macro process

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/expr.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/nameres/tests/block.rs
- crates/hir_ty/src/infer/expr.rs
Reverts rust-analyzer/rust-analyzer#7506
bors r+
> Revert "Use block_def_map in body lowering"

- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/path_resolution.rs
Fixes the bugs encountered in https://github.com/rust-analyzer/rust-analyzer/pull/7506#issuecomment-771417467
bors r+
> Use the right `DefMap` when looking up modules

- docs/dev/style.md
> add useless types to the styleguide

- Cargo.lock
- crates/hir_ty/Cargo.toml
- crates/hir_ty/src/traits/chalk.rs
- crates/syntax/Cargo.toml
> Bump chalk and rustc_lexer

- docs/dev/README.md
- docs/dev/architecture.md
> Make architecture more informative

- crates/syntax/fuzz/Cargo.toml
- xtask/src/lib.rs
- xtask/tests/tidy.rs
> Add cargo file tidy test

- docs/dev/architecture.md
I think line 235 is still wrong, but I am not sure.
Is the `crated/tt` in line 252 supposed to be `crates/tt`?
> Grammar fixes

- crates/hir_def/src/db.rs
- crates/hir_def/src/nameres.rs
> Update `DefMap` and `block_def_map` docs

- crates/hir_def/src/item_tree/lower.rs
> Add a FIXME to ItemTree

- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/nameres.rs
> Add newline between block and crate maps

- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/nameres.rs
This is helpful for more targeted debugging
bors r+
> Split out ItemScope::dump from DefMap::dump

- docs/dev/architecture.md
> More architecture.md

- crates/hir_def/src/path.rs
- crates/hir_def/src/path/lower.rs
- crates/hir_def/src/path/lower/lower_use.rs
> Avoid using ModPath's fields directly

- crates/hir_ty/src/diagnostics/decl_check/case_conv.rs
> Remove unnecessary allocs in case_conv

- docs/dev/README.md
> Add howtos

- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/nameres/path_resolution.rs
> Fix resolution of `self` module within blocks

- editors/code/src/commands.ts
> Fix resolveCodeAction trying to edit files before creating them

- docs/dev/architecture.md
> More information for mbe in architecture.md

- docs/dev/architecture.md
Fixing [issue](https://github.com/rust-analyzer/rust-analyzer/issues/7581)
> Fixing architecture image on dark theme

- docs/dev/architecture.md
> Add a section on entry points

- Cargo.lock
- crates/assists/src/handlers/add_lifetime_to_type.rs
- crates/assists/src/handlers/generate_derive.rs
- crates/assists/src/handlers/generate_enum_match_method.rs
- crates/assists/src/handlers/generate_impl.rs
- crates/assists/src/handlers/generate_new.rs
- crates/assists/src/utils.rs
- crates/ide/src/goto_implementation.rs
- crates/syntax/src/ast/generated/nodes.rs
> AdtDef -> Adt

- crates/completion/src/completions/keyword.rs
> fix: add for keyword in completion #7588

- docs/user/manual.adoc
> Add emacs guide

- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
> Check for dyn impls in method resolution

- crates/ide/src/join_lines.rs
- crates/ide/src/syntax_tree.rs
- editors/code/package.json
> Cleanup test

- bench_data/glorious_old_parser
- crates/ide/src/syntax_highlighting/tests.rs
- crates/syntax/src/tests.rs
- crates/test_utils/src/bench_fixture.rs
> Add parsing benchmark

- crates/completion/src/completions.rs
- crates/completion/src/completions/pattern.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/render/pattern.rs
> Show qualified variant pattern completions

- docs/dev/architecture.md
> Use track caller in test documentation

- crates/hir/src/source_analyzer.rs
- crates/ide/src/references.rs
> Resolve TupleStructPat in SourceAnalyzer::resolve_path

- crates/hir_ty/src/tests/simple.rs
> Add test for #1165

- Cargo.lock
- crates/proc_macro_srv/Cargo.toml
- crates/proc_macro_srv/src/dylib.rs
See https://docs.rs/libloading/0.7.0/libloading/changelog/r0_7_0/index.html
> libloading 0.7

- docs/dev/style.md
> Document config pattern

- crates/assists/src/handlers/inline_local_variable.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/handlers.rs
- crates/syntax/src/ast/node_ext.rs
Addresses #4290
This PR is still a bit unpolished. Its main purpose for now is to discuss the direction of the changes as to whether this seems to be the right approach or not. I annotated a few parts with reviews to give a better overwiew without having to read into it too much.
Big part of the diff are test output changes in the `references` module.
> Refactor reference searching to work with the ast 

- crates/ide/src/annotations.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
> Move CodeLens to ide crate

- crates/assists/src/handlers/generate_getter.rs
- crates/assists/src/handlers/generate_getter_mut.rs
- crates/assists/src/handlers/generate_setter.rs
> Group generate getter/setter assist

- crates/assists/src/handlers/generate_impl.rs
- crates/assists/src/utils.rs
> strip type parameter defaults when generating impl generics

- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Make it clear which client-side commands we use

- crates/rust-analyzer/src/line_endings.rs
This is both simpler to read and compiles to better code: https://rust.godbolt.org/z/MxKodv
> Simplify find_crlf

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/caps.rs
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/client.ts
Companion to https://github.com/gluon-lang/lsp-types/pull/199 which <strike>has not been merged yet</strike>  has been merged.
This doesn't opt into any 3.17 functionality yet.
> Start LSP 3.17 support

- crates/parser/src/grammar/items.rs
- crates/syntax/test_data/parser/inline/ok/0162_default_async_unsafe_fn.rast
- crates/syntax/test_data/parser/inline/ok/0162_default_async_unsafe_fn.rs
- crates/syntax/test_data/parser/inline/ok/0163_default_async_fn.rast
- crates/syntax/test_data/parser/inline/ok/0163_default_async_fn.rs
Fixes #7669.
Adapting the parser seemed to be all that was needed, but I am not very experienced with the codebase. Is this enough ?
> Specialization for async traits

- editors/code/package-lock.json
Supposedly backwards compatible
> Use npm 7.x package-lock.json

- crates/ide/src/inlay_hints.rs
Currently, chaining hints are not generated if there are comments between newlines, which is a very common pattern:
```rust
let vec = (0..10)
// Multiply by 2
.map(|x| x * 2)
// Add 3
.map(|x| x + 3)
.collect::<Vec<i32>>();
```
Besides, it seems a bit weird that this piece of code generates a chaining hint:
```rust
let vec = (0..10)
.collect::<Vec<i32>>();
```
But this one doesn't:
```rust
let vec = (0..10)
// This is a comment
.collect::<Vec<i32>>();
```
> Allow comments between newlines in chaining hints

- editors/code/package-lock.json
- editors/code/src/client.ts
> Remove semantic tokens workaround

- crates/ide/src/hover.rs
Unlike field shorthand patterns, const patterns don't have match ergonomics, see related issue that caused `ConstReference` to show the type instead as a side effect #6146
Closes #7671
bors r+
> Show hover info of the definition of ConstReference patterns instead of its type

- crates/hir_ty/src/diagnostics.rs
- crates/syntax/src/ast/node_ext.rs
> Fix incorrect missing field diagnostic with box patterns

- crates/hir/src/code_model.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/lib.rs
> Consider import prefix config settings during flyimports

- crates/assists/src/handlers/generate_impl.rs
- crates/assists/src/utils.rs
> fix(assist): display where predicates when we want to generate impl

- editors/code/src/main.ts
Fixes https://github.com/rust-analyzer/rust-analyzer/pull/7658#issuecomment-782701138
> Try to detect musl distros in the Code extension

- Cargo.lock
- crates/assists/Cargo.toml
- crates/assists/src/lib.rs
- crates/assists/src/tests.rs
- crates/base_db/src/fixture.rs
> Make more common assist easier to ues

- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/visibility.rs
- crates/ide_completion/src/completions/dot.rs
fixes https://github.com/rust-analyzer/rust-analyzer/issues/7728
bors r+
> Fix visibility computation when inside a block expression

- xtask/src/main.rs
> reliable memory usage during benchmarking

- crates/ide/src/references.rs
- crates/ide_db/src/search.rs
> Pickup ConstReference patterns in FindUsages

- crates/ide_assists/src/handlers/flip_comma.rs
Fix #7693 
Disables "Flip comma" assist if called inside a macro call.
> Disable "Flip comma" assist inside a macro call

- crates/hir_expand/src/builtin_macro.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tt_iter.rs
> Fix builtin macros split exprs on comma

- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests.rs
Fixes #7781
Off-topic: A [beautiful poem](http://chinesepoetryinenglishverse.blogspot.com/2013/12/blog-post_4784.html) from by Li Shangyin.
bors r+
> Fix non-latin characters doc comment in mbe expansion

- crates/hir_expand/src/builtin_macro.rs
> Fix assert split exprs on comma

- crates/ide_assists/src/handlers/convert_for_to_iter_for_each.rs
- crates/ide_assists/src/handlers/replace_for_loop_with_for_each.rs
- crates/ide_assists/src/handlers/replace_let_with_if_let.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests.rs
- crates/ide_assists/src/tests/generated.rs
> Use consistent naming for assist

- crates/hir/src/code_model.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
> Turn Ty::Tuple variant into a tuple-variant

- crates/hir/src/code_model.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
> Lift Ty::Fn into a struct

- crates/rust-analyzer/tests/rust-analyzer/main.rs
- crates/rust-analyzer/tests/rust-analyzer/support.rs
> Speedup heavy tests

- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- editors/code/README.md
Nothing grande but I figured this is a bit better than showing almost nothing
> Update vscode README with a small features list

- crates/mbe/Cargo.toml
r? @lnicola 
See also https://github.com/pksunkara/cargo-workspaces/issues/39
> Paperover a bug in cargo-workspace for publish RA

- crates/hir/src/code_model.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
> Introduce Ty::Alias

- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/cli/ssr.rs
> Fix ProcMacroClient dropped too early in cli

- crates/ide_assists/src/handlers/convert_comment_block.rs
- crates/ide_assists/src/lib.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/token_ext.rs
Fixes: https://github.com/rust-analyzer/rust-analyzer/issues/6515
> Implement line<->block comment assist

- xtask/src/tidy.rs
Closes https://github.com/rust-analyzer/rust-analyzer/pull/7828#issuecomment-788174522.
This looks a bit ugly, but at least fixes an issues where we missed target-specific dependencies.
> Check for path dev-dependencies with a version number

- xtask/src/metrics.rs
> Fix xflags fallout

- crates/ide/src/join_lines.rs
> Don't add space when joining line to opening quote

- crates/ide_assists/src/tests.rs
- crates/ide_assists/src/utils/suggest_name.rs
> Compress tests

- docs/dev/style.md
> Clarify comparison rule

- crates/ide_assists/src/handlers/apply_demorgan.rs
> Special-case parenthesized and negated expressions in demorgan assist

- crates/ide/src/references/rename.rs
> Prevent renaming SelfType and BuiltinType

- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/completions/fn_param.rs
- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/completions/qualified_path.rs
> Complete `while let`

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> Migrate to user-centric config name for `cargo check` stuff
