- .travis.yml
- src/parser/input.rs
> Use stable rustfmt-preview

- .travis.yml
> Add Clippy to CI

- CONTRIBUTING.md
- README.md
- crates/ra_lsp_server/src/main_loop/handlers.rs
Change a few `libsyntax2` to `rust-analyzer`
> libsyntax2 -> rust-analyzer

- crates/ra_editor/src/code_actions.rs
- crates/ra_editor/src/completion.rs
- crates/ra_editor/src/extend_selection.rs
- crates/ra_editor/src/folding_ranges.rs
- crates/ra_editor/src/lib.rs
- crates/ra_editor/src/scope/fn_scope.rs
- crates/ra_editor/src/symbols.rs
- crates/ra_editor/src/typing.rs
- crates/ra_syntax/src/algo/mod.rs
- crates/ra_syntax/src/algo/walk.rs
- crates/ra_syntax/src/lib.rs
- crates/ra_syntax/src/reparsing.rs
- crates/ra_syntax/src/utils.rs
- crates/ra_syntax/src/yellow/mod.rs
- crates/ra_syntax/src/yellow/syntax_text.rs
> Inherent traversal

- .gitignore
Ignore .idea directory generated by IntelliJ
> Ignore .idea/

- crates/ra_editor/src/extend_selection.rs
> Extend comments by single word first

- crates/ra_analysis/src/lib.rs
- crates/ra_editor/src/lib.rs
- crates/ra_editor/src/typing.rs
- crates/ra_lsp_server/src/conv.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/main_loop/mod.rs
- crates/ra_lsp_server/src/req.rs
- editors/README.md
- editors/code/package-lock.json
- editors/code/src/commands/index.ts
- editors/code/src/commands/on_enter.ts
- editors/code/src/extension.ts
Now, typing doc comments is much more pleasant
> Add on-enter handler

- Cargo.lock
- crates/ra_analysis/Cargo.toml
- crates/ra_analysis/src/db/imp.rs
- crates/ra_analysis/src/imp.rs
- crates/ra_analysis/src/lib.rs
- crates/ra_analysis/src/roots.rs
- crates/ra_analysis/tests/tests.rs
- crates/ra_editor/Cargo.toml
- crates/ra_editor/src/completion.rs
- crates/ra_editor/src/folding_ranges.rs
- crates/ra_editor/src/lib.rs
- crates/ra_editor/src/scope/fn_scope.rs
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/lib.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/main_loop/mod.rs
- crates/ra_lsp_server/src/main_loop/subscriptions.rs
- crates/ra_lsp_server/src/project_model.rs
- crates/ra_lsp_server/src/req.rs
- crates/ra_lsp_server/src/server_world.rs
Replace std's HashMap, HashSet with FxHashMap and FxHashSet.
Closes #121 
Thanks!
> Use rustc-hash crate

- crates/ra_analysis/src/descriptors.rs
- crates/ra_analysis/src/imp.rs
- crates/ra_analysis/src/lib.rs
- crates/ra_analysis/tests/tests.rs
- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/main_loop/mod.rs
- crates/ra_lsp_server/src/req.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/grammar.ron
@matklad Once this is in shape I would like to add tests. I think a separate PR should be done for returning documentation information and markdown.
Fixes #102
> Signature help

- editors/code/src/server.ts
> Fix a small typo

- README.md
@skade just took the logo from the website. Is there a more specific page we want to link to?
> Add link to ferrous

- Cargo.lock
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/lib.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/main_loop/mod.rs
> Add LspError to explicity return errors from LSP handlers

- crates/ra_editor/src/folding_ranges.rs
> Restore folding import groups

- editors/code/src/commands/apply_source_change.ts
> Fix on enter

- crates/ra_analysis/src/arena.rs
- crates/ra_analysis/src/db.rs
- crates/ra_analysis/src/descriptors/function/scope.rs
- crates/ra_analysis/src/descriptors/module/imp.rs
- crates/ra_analysis/src/descriptors/module/mod.rs
- crates/ra_analysis/src/lib.rs
> Codify Arena pattern

- crates/ra_analysis/src/completion/mod.rs
- crates/ra_analysis/src/completion/reference_completion.rs
I haven't fully updated the previous commented out test - I don't know why it was commented out so some clarification would be welcome.
> Improve the suggestion for test functions

- crates/ra_editor/src/extend_selection.rs
> check for empty range when extending in comment

- crates/tools/src/lib.rs
- crates/tools/src/main.rs
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/commands/extend_selection.ts
Make the extend selection keybinding less annoying for users not used to Injelli-J (myself included). Also fixes a minor style issue and runs `npm update`.
> Fix the extend keybinding

- crates/ra_editor/src/extend_selection.rs
> use \b as word boundary when expanding single word in comments

- Cargo.lock
- crates/ra_analysis/Cargo.toml
- crates/ra_analysis/src/completion.rs
- crates/ra_analysis/src/lib.rs
- crates/ra_editor/src/code_actions.rs
- crates/ra_editor/src/lib.rs
- crates/ra_editor/src/typing.rs
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/conv.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_syntax/Cargo.toml
- crates/ra_syntax/src/lib.rs
- crates/ra_syntax/src/reparsing.rs
- crates/ra_syntax/src/text_utils.rs
- crates/ra_syntax/src/yellow/syntax_text.rs
- crates/ra_syntax/tests/data/parser/fuzz-failures/0000.rs
- crates/ra_text_edit/Cargo.toml
- crates/ra_text_edit/src/edit.rs
- crates/ra_text_edit/src/lib.rs
- crates/ra_text_edit/src/text_edit.rs
- crates/ra_text_edit/src/text_utils.rs
> Extract and rename AtomEdit and Edit into ra_text_edit

- Cargo.lock
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/lib.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/project_model.rs
- crates/ra_lsp_server/src/vfs.rs
- crates/ra_lsp_server/tests/heavy_tests/support.rs
- crates/thread_worker/Cargo.toml
- crates/thread_worker/src/lib.rs
Going to tackle https://github.com/rust-analyzer/rust-analyzer/issues/243, this is a refactoring towards that goal
> move thread worker to a separate crate

- crates/ra_analysis/src/imp.rs
- crates/ra_hir/src/db.rs
we've recmoputed item map every time previously :man_facepalming: :man_facepalming: :man_facepalming:
> WIP: fix accidently quadratic behavior

- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/module.rs
- crates/ra_hir/src/module/imp.rs
- crates/ra_hir/src/module/nameres.rs
- crates/ra_hir/src/query_definitions.rs
- crates/ra_hir/src/source_binder.rs
Fixes this problem: https://github.com/rust-analyzer/rust-analyzer/pull/289#issuecomment-448398571
> File module source does not depend on syntax

- crates/gen_lsp_server/src/msg.rs
- crates/ra_lsp_server/src/main_loop.rs
https://github.com/Microsoft/language-server-protocol/commit/25679c2e4b26cb18af8c943319d40d4f3561a340
> Use ContentModified error code

- ARCHITECTURE.md
- Cargo.lock
- crates/ra_analysis/src/imp.rs
- crates/ra_db/src/input.rs
> docs for input queries

- crates/gen_lsp_server/src/msg.rs
- crates/ra_analysis/src/lib.rs
- crates/ra_analysis/src/symbol_index.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/server_world.rs
Try not to log *huge* messages, to make logging more useful.
> More useful logging

- Cargo.lock
- Cargo.toml
https://github.com/salsa-rs/salsa/issues/99
https://github.com/Amanieu/parking_lot/issues/101
> workaround salsa/parking-log bug

- crates/ra_db/src/input.rs
> When constructing a crate graph, detect and forbid cycles.

- crates/ra_editor/src/code_actions.rs
- crates/ra_editor/src/lib.rs
> Add make_pub_crate code action to ra_editor

- crates/ra_analysis/src/imp.rs
- crates/ra_analysis/src/lib.rs
- crates/ra_analysis/src/mock_analysis.rs
- crates/ra_analysis/tests/tests.rs
- crates/ra_editor/src/lib.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
Add inspection for unnecessary braces in use statement
> resolved #324: remove unnecessary braces in use statement.

- Cargo.lock
- crates/ra_db/Cargo.toml
- crates/ra_db/src/cancelation.rs
- crates/ra_db/src/lib.rs
- crates/ra_lsp_server/src/main_loop.rs
This is primaraly to debug semengly spurious canceled requests
> add cancelation module & cancelation backtraces

- crates/ra_analysis/src/completion/complete_path.rs
- crates/ra_analysis/src/completion/completion_item.rs
- crates/ra_analysis/src/extend_selection.rs
- crates/ra_analysis/src/macros.rs
- crates/ra_analysis/src/mock_analysis.rs
- crates/ra_hir/src/adt.rs
- crates/ra_hir/src/db.rs
- crates/ra_hir/src/module.rs
- crates/ra_hir/src/name.rs
- crates/ra_hir/src/query_definitions.rs
- crates/ra_hir/src/ty.rs
- crates/ra_lsp_server/src/conv.rs
and a bunch of unrelated stuff
> Macro extend selection

- .travis.yml
> Deny warnings on CI (#329)

- crates/ra_hir/src/db.rs
- crates/ra_hir/src/query_definitions.rs
- crates/ra_hir/src/ty.rs
Also get rid of the indirection through query_definitions for the type-related
queries.
> Add more docs in ty.rs

- crates/ra_vfs/src/io.rs
- crates/ra_vfs/src/lib.rs
Some random code/comment improvements I saw whilst trying to understand `ra_vfs`.
Let's see if this works:
bors r+
> Improve comments and code in ra_vfs

- Cargo.toml
See https://github.com/salsa-rs/salsa/pull/103 for the upstream fix
> fix the cancellation bug

- crates/ra_analysis/src/imp.rs
- crates/ra_analysis/src/lib.rs
- crates/ra_analysis/tests/tests.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
Fixes #230. Supersedes #235.
TODO: add some tests for this
> Move renames into ra_analysis and rename the correct range

- .travis.yml
I'm gonna let the PR build run to see if this has worked.
> Disable incremental compilation again on CI

- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
> Implement DocumentHighlight

- .cargo/config
- crates/tools/src/lib.rs
- crates/tools/src/main.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/61#issuecomment-450641045.
> Add a fuzzing subcommand

- crates/ra_editor/src/extend_selection.rs
- crates/ra_vfs/src/lib.rs
> extend selection inside a string literal should select a word first

- crates/ra_analysis/src/lib.rs
- crates/ra_analysis/tests/test/main.rs
- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/tests/data/parser/ok/0037_mod.rs
- crates/ra_syntax/tests/data/parser/ok/0037_mod.txt
> remove non-doc comments from doc comments

- crates/ra_analysis/src/hover.rs
- crates/ra_analysis/src/imp.rs
- crates/ra_analysis/src/lib.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
Primaraly this moves `hover` to `ra_analysis`, so that we finally can write tests for it!
> Refactor hover

- crates/ra_analysis/src/lib.rs
- crates/ra_editor/src/lib.rs
- crates/ra_editor/src/typing.rs
- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
Fixes #439.
The unit test passes, but I can't seem to make VS code perform the action. The existing action on "=" doesn't work either on my end either though.
I didn't add any smart way of detecting the current indent level. Any ideas how I would do that?
> WIP: indent on typing dot

- Cargo.lock
- Cargo.toml
- crates/ra_lsp_server/src/project_model.rs
This handles renames
closes https://github.com/rust-analyzer/rust-analyzer/issues/464
> switch to newer cargo-metadata

- crates/ra_hir/src/adt.rs
- crates/ra_hir/src/code_model_api.rs
- crates/ra_hir/src/lib.rs
- crates/ra_ide_api/src/completion/complete_dot.rs
- crates/ra_ide_api/src/completion/completion_item.rs
- crates/ra_lsp_server/src/conv.rs
> Show types of fields in completion

- .travis.yml
- crates/ra_arena/src/lib.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/project_model.rs
- crates/ra_lsp_server/src/project_model/cargo_workspace.rs
- crates/ra_lsp_server/src/project_model/sysroot.rs
- crates/ra_lsp_server/src/server_world.rs
- crates/ra_lsp_server/tests/heavy_tests/main.rs
- crates/ra_lsp_server/tests/heavy_tests/support.rs
> support std

- crates/ra_ide_api_light/src/assists.rs
- crates/ra_ide_api_light/src/formatting.rs
- crates/ra_ide_api_light/src/typing.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
Looks like our on type handlers didn't actually worked, this shoud fix that!
> Fix on type handlers

- crates/ra_lsp_server/src/main_loop/handlers.rs
> Switch hover to use MarkupContent

- editors/README.md
`--depth 1` will make a shallow clone, of master branch only.
> Do not recommend fetching whole repo for end users

- crates/ra_hir/src/ty.rs
- crates/ra_ide_api/src/goto_definition.rs
This uses type inference results for `goto method` functionality.
This is achieved by adding another map to `InferenceResult`. I wonder how we should handle this long-term... The pattern seems to be "we are doing some analysis, and we produce some stuff as a by-product, and IDE would like to use the stuff". Ideally, adding an additional bit of info shouldn't require threading it through all data structures. 
I kinda like how Kotlin deals with this problem. They have this [`BindingContext`](https://github.com/JetBrains/kotlin/blob/72e351a0e3610051fe4222dca4e1eeedf7ae45da/compiler/frontend/src/org/jetbrains/kotlin/resolve/BindingContext.java#L122) thing, which is basically an [`AnyMap`](https://github.com/JetBrains/kotlin/blob/72e351a0e3610051fe4222dca4e1eeedf7ae45da/compiler/frontend/src/or …
> goto defenition works for type-inferred methods

- editors/code/src/commands/apply_source_change.ts
> Reveal the newly added source change in the editor.

- crates/ra_ide_api/src/completion.rs
- crates/ra_ide_api/src/completion/complete_postfix.rs
- crates/ra_ide_api/src/completion/completion_item.rs
- crates/ra_ide_api/src/completion/snapshots/completion_item__filter_postfix_completion1.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__filter_postfix_completion2.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__filter_postfix_completion3.snap
> Postfix completion

- crates/ra_hir/src/code_model_impl/module.rs
- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/path.rs
- crates/ra_ide_api/src/completion/complete_snippet.rs
- crates/ra_ide_api/src/completion/completion_context.rs
- crates/ra_ide_api/src/completion/snapshots/completion_item__bindings_from_for.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__bindings_from_if_let.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__bindings_from_let.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__completes_break_and_continue_in_loops1.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__completes_break_and_continue_in_loops2.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__dont_add_semi_after_return_if_not_a_statement.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__dont_show_both_completions_for_shadowing.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__filter_postfix_completion3.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__keywords_in_function1.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__keywords_in_function2.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__keywords_in_function3.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__keywords_in_function4.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__keywords_in_use_stmt1.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__keywords_in_use_stmt3.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__last_return_in_block_has_semi1.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__last_return_in_block_has_semi2.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__module_items.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__module_items_in_nested_modules.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__return_type.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__self_in_methods.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__should_not_complete_snippets_in_path.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__should_not_complete_snippets_in_path2.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__snippets_in_expressions.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__snippets_in_items.snap
- crates/ra_syntax/src/ast.rs
The result is as below. 
before:
after:
> fix completion bugs

- .travis.yml
- crates/tools/src/lib.rs
> Use stable toolchain

- crates/ra_hir/src/ty.rs
- crates/ra_hir/src/ty/snapshots/tests__bug_651.snap
- crates/ra_hir/src/ty/tests.rs
> Fix type inference of binops on int/float variables

- crates/ra_hir/src/marks.rs
- crates/ra_hir/src/ty.rs
- crates/ra_hir/src/ty/snapshots/tests__recursive_vars.snap
- crates/ra_hir/src/ty/snapshots/tests__recursive_vars_2.snap
- crates/ra_hir/src/ty/tests.rs
This might be the cause of #587.
> Handle cycles in type vars

- crates/ra_hir/src/mock.rs
- crates/ra_hir/src/module_tree.rs
- crates/ra_hir/src/nameres/tests.rs
- crates/ra_ide_api/tests/test/main.rs
- crates/ra_syntax/src/algo.rs
> Fix module resolution for non standard filenames

- crates/ra_ide_api/src/call_info.rs
- crates/ra_ide_api/src/completion.rs
- crates/ra_ide_api/src/completion/completion_item.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_lsp_server/src/conv.rs
- crates/ra_lsp_server/src/lib.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/markdown.rs
> Pass Documentation up to LSP and add "rust" to our codeblocks there

- README.md
- crates/ra_hir/src/code_model_api.rs
- crates/ra_hir/src/code_model_impl/module.rs
- crates/ra_hir/src/db.rs
- crates/ra_hir/src/impl_block.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_hir/src/ty/method_resolution.rs
- crates/ra_ide_api/src/impls.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_ide_api/src/navigation_target.rs
- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/req.rs
> Go to Implementation

- crates/ra_ide_api_light/src/assists.rs
- crates/ra_ide_api_light/src/assists/introduce_variable.rs
- crates/ra_ide_api_light/src/test_utils.rs
Fix #667 (but not re-indenting currently), plus many other improvements.
@matklad I'm not sure how to handle re-indenting here.
>  Fix #667 and improvements to introduce_variable

- crates/ra_lsp_server/src/main_loop/handlers.rs
I find that this makes code lenses stand out more otherwise they can be easy to miss.
> Use "▶" for test code lens

- crates/ra_hir/src/source_binder.rs
- crates/ra_hir/src/ty/method_resolution.rs
- crates/ra_ide_api/src/impls.rs
If on a trait def you can now go to all the impls of that trait in the crate.
This is more of #620.
> Go To Implementation for Trait

- crates/ra_hir/src/adt.rs
- crates/ra_hir/src/code_model_api.rs
- crates/ra_hir/src/code_model_impl/function.rs
- crates/ra_hir/src/code_model_impl/krate.rs
- crates/ra_hir/src/code_model_impl/module.rs
- crates/ra_hir/src/db.rs
- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/expr/scope.rs
- crates/ra_hir/src/generics.rs
- crates/ra_hir/src/ids.rs
- crates/ra_hir/src/impl_block.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/macros.rs
- crates/ra_hir/src/mock.rs
- crates/ra_hir/src/module_tree.rs
- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/nameres/lower.rs
- crates/ra_hir/src/nameres/tests.rs
- crates/ra_hir/src/query_definitions.rs
- crates/ra_hir/src/ty.rs
- crates/ra_ide_api/src/db.rs
> split HirDatabase

- crates/ra_lsp_server/src/project_model/sysroot.rs
> Add core to STD_DEPS

- crates/ra_mbe/src/lib.rs
- crates/ra_mbe/src/mbe_expander.rs
Factors out a helper and adds support for matching idents.
> mbe: Add support matching for matching idents

- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- editors/code/src/extension.ts
> Implement lens for impls and support resolving lenses.

- crates/ra_hir/src/ty/snapshots/tests__infer_self.snap
- crates/ra_hir/src/ty/tests.rs
These cases didn't look covered.
> Test more Self inference

- crates/ra_lsp_server/src/main_loop/handlers.rs
As pointed out in https://github.com/rust-analyzer/rust-analyzer/pull/738/files#r253651450
> Move comment

- crates/ra_assists/src/lib.rs
> assists: compute edit

- Cargo.lock
- crates/ra_assists/Cargo.toml
- crates/ra_assists/src/assist_ctx.rs
- crates/ra_assists/src/replace_if_let_with_match.rs
- crates/ra_fmt/Cargo.toml
- crates/ra_fmt/src/lib.rs
- crates/ra_ide_api_light/Cargo.toml
- crates/ra_ide_api_light/src/join_lines.rs
- crates/ra_ide_api_light/src/lib.rs
- crates/ra_ide_api_light/src/typing.rs
As discussed https://github.com/rust-analyzer/rust-analyzer/pull/762#discussion_r254905885
I did only move the code without other improvements.
> Formatting code into ra_fmt

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/server.ts
See https://github.com/Microsoft/vscode-languageserver-node/pull/444
I am just working on testing this now, but I think it should work.
> Add support for a seperate output channel for trace messages

- crates/ra_hir/src/code_model_api.rs
- crates/ra_hir/src/marks.rs
- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/nameres/tests.rs
This implements glob imports, completing #231 :)
> Glob imports

- crates/gen_lsp_server/Cargo.toml
- crates/ra_arena/Cargo.toml
- crates/ra_assists/Cargo.toml
- crates/ra_batch/Cargo.toml
- crates/ra_cli/Cargo.toml
- crates/ra_db/Cargo.toml
- crates/ra_fmt/Cargo.toml
- crates/ra_hir/Cargo.toml
- crates/ra_ide_api/Cargo.toml
- crates/ra_ide_api_light/Cargo.toml
- crates/ra_lsp_server/Cargo.toml
- crates/ra_mbe/Cargo.toml
- crates/ra_project_model/Cargo.toml
- crates/ra_syntax/Cargo.toml
- crates/ra_syntax/fuzz/Cargo.toml
- crates/ra_text_edit/Cargo.toml
- crates/ra_tt/Cargo.toml
- crates/ra_vfs/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/thread_worker/Cargo.toml
- crates/tools/Cargo.toml
> Update authors field in Cargo.tomls to "rust-analyzer developers"

- crates/gen_lsp_server/Cargo.toml
- crates/ra_arena/Cargo.toml
- crates/ra_assists/Cargo.toml
- crates/ra_batch/Cargo.toml
- crates/ra_cli/Cargo.toml
- crates/ra_db/Cargo.toml
- crates/ra_fmt/Cargo.toml
- crates/ra_hir/Cargo.toml
- crates/ra_ide_api/Cargo.toml
- crates/ra_ide_api_light/Cargo.toml
- crates/ra_lsp_server/Cargo.toml
- crates/ra_mbe/Cargo.toml
- crates/ra_project_model/Cargo.toml
- crates/ra_syntax/Cargo.toml
- crates/ra_syntax/fuzz/Cargo.toml
- crates/ra_text_edit/Cargo.toml
- crates/ra_tt/Cargo.toml
- crates/ra_vfs/Cargo.toml
- crates/test_utils/Cargo.toml
- crates/thread_worker/Cargo.toml
- crates/tools/Cargo.toml
> Fix typo in Cargo.toml authors

- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/nameres/tests.rs
- crates/ra_hir/src/resolve.rs
- crates/ra_ide_api/src/completion/complete_path.rs
- crates/ra_ide_api/src/completion/snapshots/completion_item__completes_use_paths_across_crates.snap
> Fix completion of paths

- crates/ra_ide_api/src/completion/complete_path.rs
- crates/ra_ide_api/src/completion/completion_item.rs
- crates/ra_ide_api/src/marks.rs
> fix regression in self-referential completion

- crates/ra_vfs/src/io.rs
- crates/ra_vfs/src/lib.rs
> don't distinguish Create and Write events in VFS

- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/remove_dbg.rs
- crates/ra_db/src/cancellation.rs
- crates/ra_hir/src/code_model_api.rs
- crates/ra_hir/src/expr/scope.rs
- crates/ra_hir/src/ids.rs
- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/nameres/lower.rs
- crates/ra_hir/src/path.rs
- crates/ra_ide_api/src/completion.rs
- crates/ra_ide_api/src/completion/complete_fn_param.rs
- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_ide_api/src/hover.rs
- crates/ra_ide_api/src/impls.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_ide_api/src/mock_analysis.rs
- crates/ra_ide_api/src/references.rs
- crates/ra_ide_api/src/symbol_index.rs
- crates/ra_mbe/src/lib.rs
- crates/ra_mbe/src/mbe_expander.rs
- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_vfs/src/io.rs
- crates/ra_vfs/src/lib.rs
- crates/test_utils/src/lib.rs
- crates/test_utils/src/marks.rs
- crates/thread_worker/src/lib.rs
Cherry-picked and updated from my now-closed PR. All credit goes to [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).
> Fix some typos

- editors/code/package.json
This is for #796 
It doesn't seem to fix the problem if you manually install the extension but it is the "right thing to do".
> Specify vscode 1.31

- crates/ra_ide_api/src/completion.rs
- crates/ra_ide_api/src/completion/complete_dot.rs
- crates/ra_ide_api/src/completion/snapshots/completion_item__method_attr_filtering.snap
> Filter attributes from the completion details/label

- crates/ra_assists/src/auto_import.rs
> auto_import: import in enclosing module by default

- crates/ra_ide_api/src/call_info.rs
> Be precise about the argument list

- crates/ra_batch/src/lib.rs
- crates/ra_vfs/src/io.rs
- crates/ra_vfs/src/lib.rs
- crates/ra_vfs/src/roots.rs
Some slight refctorings of VFS, in preparation for moving it to a separate repo
> Refactor vfs

- crates/ra_syntax/src/parsing.rs
- crates/ra_syntax/src/parsing/builder.rs
- crates/ra_syntax/src/parsing/event.rs
- crates/ra_syntax/src/parsing/grammar.rs
- crates/ra_syntax/src/parsing/reparsing.rs
- crates/ra_syntax/src/parsing/token_set.rs
More work on making parser independent from text
> Parser decoupling

- crates/ra_assists/src/flip_comma.rs
- crates/ra_assists/src/lib.rs
- crates/ra_ide_api_light/src/join_lines.rs
- crates/ra_syntax/src/algo.rs
> Fix join_lines not adding a comma after join_single_expr_block with match arm

- crates/ra_assists/src/fill_match_arms.rs
> Fix fill_match_arms not working with references

- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/lower.rs
- crates/ra_hir/src/ty/snapshots/tests__infer_associated_method_generics.snap
- crates/ra_hir/src/ty/tests.rs
Refactor associated method resolution a bit and make it work with generics.
> Associated method generics

- crates/ra_ide_api/src/completion.rs
- crates/ra_ide_api/src/completion/complete_struct_literal.rs
- crates/ra_ide_api/src/completion/completion_context.rs
- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/ast/generated.rs.tera
> Field completion

- crates/ra_ide_api/src/completion.rs
- crates/ra_ide_api/src/completion/complete_pattern.rs
- crates/ra_ide_api/src/completion/completion_context.rs
> complete patterns

- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_ide_api/src/hover.rs
- crates/ra_ide_api/src/marks.rs
This works partially towards fixing #512
> Add support for goto definition and hover for struct fields

- crates/ra_ide_api/src/hover.rs
> Update hover message since we do support globs

- crates/ra_ide_api/src/hover.rs
This adds highlighting when hovering over items which are resolved using
`type_of`.
This adds basic highlighting, discussed in #904.
> Enable markup for hover on expressions which resolve using type_of

- crates/ra_mbe/src/lib.rs
- crates/ra_mbe/src/mbe_expander.rs
- crates/ra_mbe/src/mbe_parser.rs
- crates/ra_mbe/src/tt_cursor.rs
> Error handling for macros

- crates/ra_hir/src/ty/infer.rs
- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_ide_api/src/hover.rs
- crates/ra_ide_api/src/navigation_target.rs
Just functions so far. Looking for comments.
Fixes #911
Towards #832
> Make goto definition/hover work for associated items

- crates/ra_lsp_server/src/init.rs
- crates/ra_lsp_server/src/lib.rs
- crates/ra_lsp_server/src/main.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/req.rs
- crates/ra_lsp_server/tests/heavy_tests/main.rs
- crates/ra_lsp_server/tests/heavy_tests/support.rs
- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/server.ts
This fixes #935 
This adds support for more `InitializationOptions` which are provided by the client.
> Show workspace loaded notification

- crates/tools/src/lib.rs
- crates/tools/src/main.rs
Fixes #918.
Edit: Windows encoding for Unicode is UTF-16 so String::from_utf8 will probably fail unless `Vec<u8>` is already UTF-8 somehow, which I don't know for sure.
> Check installed extension

- crates/ra_hir/src/source_binder.rs
- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_ide_api/src/hover.rs
- crates/ra_ide_api/src/navigation_target.rs
> Add support for goto definition and hover on Self

- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/ty.rs
- crates/ra_hir/src/ty/display.rs
- crates/ra_hir/src/ty/lower.rs
- crates/ra_hir/src/ty/tests.rs
- crates/ra_ide_api/src/completion/presentation.rs
- crates/ra_ide_api/src/hover.rs
This allows removing the names from Adt and FnDef (and more later), as a first
step towards aligning more with chalk's Ty :)
I may have gone a bit overboard with the definition of the PrettyPrint trait...
> Replace Display by a pretty printing trait for Ty

- crates/ra_assists/src/add_missing_impl_members.rs
- crates/ra_assists/src/lib.rs
Closes #878.
This took longer than expected as I wrapped my head around the API and the project - hopefully I didn't miss any edge case here.
r? @matklad
> Add missing impl members

- crates/ra_assists/src/fill_struct_fields.rs
> Fill partial fields

- crates/ra_ide_api/src/folding_ranges.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_ide_api_light/src/lib.rs
> Move folding_ranges to ra_ide_api

- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/tests.rs
> Fix apply_substs assertion failure

- crates/ra_ide_api/src/assists.rs
- crates/ra_ide_api/src/diagnostics.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_ide_api/src/references.rs
- crates/ra_ide_api/src/typing.rs
> Add convenience functions to SourceChange for creating single edits

- crates/ra_assists/src/inline_local_variable.rs
- crates/ra_assists/src/lib.rs
> inline immutable local varialbe

- crates/tools/src/lib.rs
Tested on Git Bash, CMD and Powershell.
Closes: #875
> Use EXE extension for pre-commit hook on Window

- crates/ra_ide_api/src/call_info.rs
> Take number of arguments at the call-site into account for signature help

- editors/code/src/commands/cargo_watch.ts
- editors/code/src/commands/watch_status.ts
* Refactoring code and fixed some minor bugs.
* Add more error log and better error handling.
* Add current checking artifact name in Cargo-watch animation.
> Improve cargo-watch animation and refactoring

- crates/ra_hir/src/code_model_api.rs
- crates/ra_hir/src/db.rs
- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/expr/scope.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/tests.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/grammar.ron
This is the second part of #887. I've added type inference on const bodies and introduced the DefWithBody containing Function, Const and Static. I want to add tests but im unsure on how I would go about testing that completions work.
> Const body inference

- crates/ra_prof/src/lib.rs
> added some docs to public functions

- crates/ra_assists/src/split_import.rs
- crates/ra_fmt/src/lib.rs
- crates/ra_hir/src/ty/autoderef.rs
- crates/ra_syntax/src/algo.rs
- crates/ra_syntax/src/ptr.rs
- crates/ra_syntax/src/syntax_node.rs
> replace usages of `algo::generate` with `iter::successors` from std

- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/tests.rs
As discussed in #1099, this PR try to "plug" a `self type` type parameters in `infer_path_expr`.
All the cases in 1099 was fixed and tested.
And luckily, this PR fixed bug #1030 again and make the test output correct.
> Fix #1099, plug self type type parameters in infer_path_expr

- docs/user/README.md
Hey all!
I'm a Sublime Text 3 user and I wrote instructions to make `rust-analyzer` work with it.
So far works flawlessly, barring the missing features, which is fine (and not the point of this PR).
Great work <3
Thanks,
Mathieu
> Added instructions for Sublime Text 3 setup

- crates/ra_mbe/src/lib.rs
- crates/ra_mbe/src/mbe_expander.rs
- crates/ra_mbe/src/subtree_parser.rs
- crates/ra_mbe/src/syntax_bridge.rs
- crates/ra_mbe/src/tt_cursor.rs
- crates/ra_parser/src/grammar.rs
- crates/ra_parser/src/lib.rs
This PR adds following  mbe matchers:
* block
* meta
* tt
* literal
* vis
> Add all remaining mbe matchers

- crates/ra_hir/src/ty/tests.rs
Somehow I forgot that we should add a test for this in #1154 until after it was already merging. So I'll just add one now :)
> Add a simple test for str method completion

- crates/ra_mbe/src/lib.rs
A little PR to add a test case for #1178
> Add a test for #1178 case

- crates/ra_mbe/src/subtree_source.rs
I just did some simple profiling, the most slowest part of the mbe related code is the tree traversal, so i add a very simple cache in here is the result:
``` target\release\ra_cli analysis-stats```
*Before
```
Database loaded, 21 roots, 1.2731481s
Crates in this dir: 26
Total modules found: 282
Total declarations: 4783
Total functions: 3126
Total expressions: 59452
Expressions of unknown type: 8999 (15%)
Expressions of partially unknown type: 2672 (4%)
Analysis: 17.9596334s
```
```
*After
Database loaded, 21 roots, 1.7425901s
Crates in this dir: 26
Total modules found: 282
Total declarations: 4783
Total functions: 3126
Total expressions: 59452
Expressions of unknown type: 8999 (15%)
Expressions of partially unknown type: 2672 (4%)
Analysis: 13.4007118s
```
Save 4 seconds :)
> Add cached for SubtreeSource

- crates/ra_parser/src/grammar/params.rs
- crates/ra_parser/src/grammar/types.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0032_fn_pointer_type.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0032_fn_pointer_type.txt
> Add `...`  parsing for fn pointer type

- crates/ra_ide_api/src/goto_type_definition.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- docs/dev/lsp-features.md
- docs/user/features.md
Very basic go to type definition
> Goto Type Definition for ADTs

- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/move_guard_to_arm_body.rs
- docs/user/features.md
> Move guard to arm body assist

- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/ast/traits.rs
- crates/ra_syntax/src/grammar.ron
This PR add a `default_type` method in `TypeParam` Node which allow future PR to handle #1099 case.
> Add `default_type` method in `TypeParam` Node

- crates/ra_mbe/src/mbe_parser.rs
This PR fixed a bug which cannot use `$true` and `$false` as `$var` name in mbe.
> Fix `$true` and `$false` as $var name error

- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_ide_api/src/completion/completion_item.rs
- crates/ra_ide_api/src/display/navigation_target.rs
- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_ide_api/src/marks.rs
- crates/ra_lsp_server/src/conv.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/grammar.ron
Adds goto definition for macros. Currently only works for macros in the current crate ~~otherwise it panics~~. Proper macro resolution needs to be added for it to resolve macros in other crates.
Todo
> [WIP] Goto for Macro's

- Cargo.lock
> :arrow_up: deps

- crates/ra_ide_api/src/diagnostics.rs
Add profiling to `diagnostics()` - see #1244.
> Add profiling to diagnostics

- crates/ra_assists/src/add_missing_impl_members.rs
> Remove collect

- crates/ra_mbe/src/syntax_bridge.rs
This PR add a check to prevent non single root token tree conversion between token trees and syntax tree.
It should prevent the assert produced in #1267.
> Error out non single root token tree conversion

- crates/ra_hir/src/ids.rs
- crates/ra_ide_api/src/change.rs
- crates/ra_lsp_server/tests/heavy_tests/main.rs
- crates/ra_lsp_server/tests/heavy_tests/support.rs
> check for cancellation during macro expansion

- crates/ra_ide_api/src/snapshots/highlighting.html
- crates/ra_ide_api/src/syntax_highlighting.rs
> Highlight names correctly

- crates/ra_ide_api/src/snapshots/highlighting.html
- crates/ra_ide_api/src/syntax_highlighting.rs
This is a hack to get better highlighting of primitive types until #1340.
> Highlight primitive types

- editors/emacs/ra-emacs-lsp.el
Also fix a minor race condition in the 'extend selection' initialization.
> Add status buffer function to emacs integration

- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/resolve.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_ide_api/src/name_ref_kind.rs
This PR improve the macro resolution for goto definition and expression macro invocation by using proper path resolution for external macros.
> Improve goto definition for MBE

- crates/ra_hir/src/diagnostics.rs
- crates/ra_mbe/src/syntax_bridge.rs
- crates/ra_syntax/src/parsing/lexer/numbers.rs
> fix: clean up warnings

- crates/ra_parser/src/grammar/expressions.rs
- crates/ra_parser/src/parser.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0130_let_stmt.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0130_let_stmt.txt
Closes https://github.com/rust-analyzer/rust-analyzer/issues/1326
r? @matklad
> fix: never type with binding

- docs/dev/architecture.md
This PR fixed some links in architecture.md.
> fixed links

- crates/ra_ide_api/src/hover.rs
```rust
fn x() {}
fn y() {
let x = 0i32;
x; // hover on `x` is expected to be `i32`, but the actual result was `fn x()`
}
```
This was because: if [`res.is_empty()`](https://github.com/sinkuu/rust-analyzer/blob/656a0fa9f99298123d7dcee8c65a8a5ed7043bc4/crates/ra_ide_api/src/hover.rs#L205), it fallbacks to "index based approach" and adds `fn x()` to `res`, which makes [`res.extend(type_of)` below](https://github.com/sinkuu/rust-analyzer/blob/656a0fa9f99298123d7dcee8c65a8a5ed7043bc4/crates/ra_ide_api/src/hover.rs#L260-L266) not happen.
> Fix hover for pat that shadows items

- docs/dev/architecture.md
Hi
Sorry about that I didn't check all links in my previous PR and two of them were incorrectly fixed.
I think they are all proporly fixed this time :)
> fixed wrong links again

- crates/ra_parser/src/grammar/items.rs
- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/grammar.ron
- crates/ra_syntax/tests/data/parser/err/0011_extern_struct.txt
- crates/ra_syntax/tests/data/parser/inline/err/0010_wrong_order_fns.txt
- crates/ra_syntax/tests/data/parser/inline/ok/0131_existential_type.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0131_existential_type.txt
Closes https://github.com/rust-analyzer/rust-analyzer/issues/1387
r? @matklad
> fix: support existential type

- crates/ra_project_model/src/sysroot.rs
- editors/emacs/ra-emacs-lsp.el
Also a small fix for the ra-emacs-lsp company fix.
> Add alloc -> core dependency

- Cargo.lock
- crates/gen_lsp_server/Cargo.toml
- crates/gen_lsp_server/examples/01_gen_lsp_server.rs
- crates/gen_lsp_server/examples/02_gen_lsp_server_with_logging.rs
- crates/gen_lsp_server/src/lib.rs
- crates/gen_lsp_server/src/msg.rs
- crates/gen_lsp_server/src/stdio.rs
- crates/ra_batch/Cargo.toml
- crates/ra_batch/src/lib.rs
- crates/ra_cli/Cargo.toml
- crates/ra_cli/src/main.rs
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/lib.rs
- crates/ra_lsp_server/src/main.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/world.rs
- crates/ra_project_model/Cargo.toml
- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- crates/ra_project_model/src/sysroot.rs
- crates/ra_syntax/src/lib.rs
issue #1400 
Now only `ra_tools` crate depends on `failure`, should I also fight those? :grin:
> Fight down failures!

- docs/user/README.md
I spent ~1 hour trying to figure this out. It's all pretty simple stuff, but very annoying...
> More details on how to set up coc

- crates/ra_parser/src/grammar/items.rs
- crates/ra_syntax/tests/data/parser/inline/err/0014_default_fn_type.rs
- crates/ra_syntax/tests/data/parser/inline/err/0014_default_fn_type.txt
- crates/ra_syntax/tests/data/parser/inline/ok/0132_default_fn_type.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0132_default_fn_type.txt
> fix: specialization

- crates/ra_hir/src/ty/method_resolution.rs
`impl<T> [T]` is separately defined in `core` and `alloc`, so I changed `def_crate` function in `method_resolution.rs` to return multiple crates.
> Method resolution for slices

- crates/ra_assists/src/fill_match_arms.rs
Addresses this issue https://github.com/rust-analyzer/rust-analyzer/issues/1399
One minor issue I noticed is that complete_postfix creates an arm like this
```
match E::X {
<|>_ => {},
}
```
but fill_match_arms creates arms like this
```
E::X => (), 
```
> Make fill_match_arm work with trivial arm

- crates/ra_lsp_server/src/main_loop/handlers.rs
My workflow in Visual Studio Code + Rust Analyzer has become:
1. Make a change to Rust source code using all the analysis magic
2. Save the file to trigger `cargo watch`. I have format on save enabled for all file types so this also runs `rustfmt`
3. Fix any diagnostics that `cargo watch` finds
Unfortunately if the Rust source has any syntax errors the act of saving will pop up a scary "command has failed" message and will switch to the "Output" tab to show the `rustfmt` error and exit code.
I did a quick survey of what other Language Servers do in this case. Both the JSON and TypeScript servers will swallow the error and return success. This is consistent with how I remember my workflow in those languages. The syntax error will show up as a diagnostic so it should be clear why the file …
> Swallow expected `rustfmt` errors

- crates/ra_parser/src/grammar/expressions.rs
- crates/ra_parser/src/grammar/items.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0134_nocontentexpr_after_item.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0134_nocontentexpr_after_item.txt
> fixed #1384

- editors/emacs/ra-emacs-lsp.el
This PR adds preliminary support for showing syntax tree.
> Add show syntax tree function to emacs

- crates/ra_hir/src/code_model.rs
- crates/ra_ide_api/src/completion/complete_path.rs
- crates/ra_ide_api/src/completion/snapshots/completion_item__enum_associated_method.snap
- crates/ra_ide_api/src/completion/snapshots/completion_item__union_associated_method.snap
This has been seriously annoying me for a while ;)
> Complete associated methods on enums (and unions) as well

- crates/ra_ide_api/src/completion/complete_dot.rs
With trait method completion + autoderef, we were getting a lot of duplicates, which was really annoying...
> Deduplicate method candidates

- Cargo.lock
- crates/gen_lsp_server/Cargo.toml
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/main_loop/handlers.rs
> Update to lsp-types 0.58.0

- Cargo.lock
> cargo update run

- crates/ra_assists/src/fill_match_arms.rs
- crates/ra_assists/src/split_import.rs
- crates/ra_db/src/input.rs
- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_syntax/src/validation/unescape.rs
A few more clippy changes.
I'm a little unsure of the second commit. It's the trivially_copy_pass_by_ref lint and there are a number of places in the code we could use it if it makes sense.
> More clippy

- crates/ra_hir/src/adt.rs
- crates/ra_hir/src/expr/validation.rs
- crates/ra_hir/src/ids.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/method_resolution.rs
- crates/ra_hir/src/ty/primitive.rs
- crates/ra_hir/src/ty/traits.rs
- crates/ra_ide_api/src/impls.rs
- crates/ra_ide_api/src/line_index_utils.rs
- crates/ra_mbe/src/subtree_source.rs
- crates/ra_mbe/src/tt_cursor.rs
Clippy says that this is more efficient.
> Clippy trivially_copy_pass_by_ref

- Cargo.lock
- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/generics.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/name.rs
- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/nameres/collector.rs
- crates/ra_hir/src/resolve.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_syntax/Cargo.toml
> Constify KnownName's

- Cargo.lock
- crates/gen_lsp_server/Cargo.toml
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/tests/heavy_tests/main.rs
Takes advantage of protocol inheritance via composition and simplifies some responses via the `From`/`Into` traits.
> Simplify LSP handlers

- crates/ra_hir/src/name.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/tests.rs
Logical continuation of https://github.com/rust-analyzer/rust-analyzer/pull/1501
cc https://github.com/rust-analyzer/rust-analyzer/issues/1426
> Infer ? operator

- crates/ra_syntax/src/syntax_text.rs
Just saw the new release of SmolStr and was reminded of this FIXME I added :)
> Remove a fixme

- crates/ra_ide_api/src/completion/complete_postfix.rs
Restrict `if`, `not` and `while` postfix magic completions to boolean expressions and expressions of an unknown type.
(this may be controversial, marking as draft for this reason)
See the discussion in #1526.
> Less magic completions

- crates/ra_parser/src/grammar/expressions/atom.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0132_box_expr.rs
- crates/ra_syntax/tests/data/parser/inline/ok/0132_box_expr.txt
> fix: parse box syntax inside parentheses

- crates/ra_cli/src/analysis_bench.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_ide_api/src/references.rs
- crates/ra_ide_api/src/syntax_tree.rs
- crates/ra_ide_api/src/typing.rs
- crates/ra_lsp_server/src/conv.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/world.rs
Based on the discussion from here: https://github.com/rust-analyzer/rust-analyzer/pull/1549#discussion_r305593236
> Make Analysis api cancellable

- editors/code/src/commands/inlay_hints.ts
> Ignore cancelled inlay hints responses

- crates/ra_hir/src/nameres/collector.rs
- crates/ra_hir/src/nameres/tests/mods.rs
> Resolve modules inside inline module

- Cargo.lock
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/merge_match_arms.rs
- crates/ra_syntax/Cargo.toml
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/1250
> Assist to merge identical match arms

- crates/ra_assists/src/flip_comma.rs
Should fix and close #1619 🤔
r? @matklad
> Fix flip comma assist

- crates/ra_lsp_server/src/conv.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/markdown.rs
> Hide ignored lines in rustdoc

- crates/ra_hir/src/nameres/collector.rs
- crates/ra_hir/src/nameres/raw.rs
- crates/ra_hir/src/nameres/tests/mods.rs
> Resolve out of line modules inside inline module with attribute path

- docs/dev/architecture.md
> architecture.md: "finish not Y" -> "finish node Y"

- crates/ra_syntax/src/parsing/lexer.rs
During an investigation of a fix for #1218, I stumbled upon some code duplication in the lexer.
> Reduce code duplication in lexer

- crates/ra_hir/src/diagnostics.rs
- crates/ra_ide_api/src/diagnostics.rs
> Use Source in Diagnostic

- crates/ra_parser/src/grammar/expressions.rs
- crates/ra_syntax/test_data/parser/inline/ok/0138_expression_after_block.rs
- crates/ra_syntax/test_data/parser/inline/ok/0138_expression_after_block.txt
try to fix [issue-1598](https://github.com/rust-analyzer/rust-analyzer/issues/1598).
> fix block parse problem

- crates/ra_parser/src/grammar/expressions.rs
- crates/ra_parser/src/grammar/expressions/atom.rs
- crates/ra_parser/src/grammar/items.rs
- crates/ra_parser/src/grammar/items/use_item.rs
- crates/ra_parser/src/grammar/paths.rs
- crates/ra_parser/src/grammar/patterns.rs
- crates/ra_parser/src/grammar/type_params.rs
- crates/ra_parser/src/grammar/types.rs
- crates/ra_syntax/test_data/parser/inline/ok/0081_for_type.rs
- crates/ra_syntax/test_data/parser/inline/ok/0081_for_type.txt
> Fix for<'lifetime> for types specified by path

- crates/ra_assists/src/add_explicit_type.rs
- crates/ra_assists/src/add_missing_impl_members.rs
- crates/ra_assists/src/fill_match_arms.rs
- crates/ra_assists/src/inline_local_variable.rs
- crates/ra_assists/src/merge_match_arms.rs
- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/generics.rs
- crates/ra_hir/src/impl_block.rs
- crates/ra_hir/src/nameres/raw.rs
- crates/ra_hir/src/traits.rs
- crates/ra_hir/src/type_ref.rs
- crates/ra_ide_api/src/call_info.rs
- crates/ra_ide_api/src/impls.rs
- crates/ra_ide_api/src/inlay_hints.rs
- crates/ra_ide_api/src/references.rs
- crates/ra_ide_api/src/runnables.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/lib.rs
- crates/ra_tools/src/boilerplate_gen.rs
> remove  ast::*Kind enums

- crates/ra_assists/src/add_explicit_type.rs
- crates/ra_assists/src/add_missing_impl_members.rs
- crates/ra_assists/src/fill_match_arms.rs
- crates/ra_assists/src/inline_local_variable.rs
- crates/ra_assists/src/merge_match_arms.rs
- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/generics.rs
- crates/ra_hir/src/impl_block.rs
- crates/ra_hir/src/nameres/raw.rs
- crates/ra_hir/src/traits.rs
- crates/ra_hir/src/type_ref.rs
- crates/ra_ide_api/src/call_info.rs
- crates/ra_ide_api/src/impls.rs
- crates/ra_ide_api/src/inlay_hints.rs
- crates/ra_ide_api/src/references.rs
- crates/ra_ide_api/src/runnables.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/lib.rs
- crates/ra_tools/src/boilerplate_gen.rs
(only the last commit is relevant, the rest are from #1700) 
bors r+
>  qualify ast types with `ast::` 

- crates/ra_hir/src/generics.rs
- crates/ra_hir/src/ty/tests.rs
- crates/ra_syntax/src/ast/extensions.rs
> Don't add `?` bounds as real bounds

- .cargo/config
- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- website/src/index.html
- website/src/wasm-demo/index.html
- website/website-gen/Cargo.toml
- website/website-gen/src/main.rs
> start GitHub pages

- crates/ra_cli/src/analysis_stats.rs
- crates/ra_hir/src/code_model/src.rs
- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/expr/lower.rs
- crates/ra_hir/src/expr/validation.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_hir/src/ty/tests.rs
- crates/ra_syntax/src/ptr.rs
> Correctly build BodySourceMap for macro-expanded expressions

- crates/ra_project_model/src/lib.rs
> close #1763

- crates/ra_cli/src/analysis_bench.rs
- crates/ra_db/src/input.rs
- crates/ra_db/src/lib.rs
- crates/ra_hir/src/mock.rs
- crates/ra_hir/src/nameres/mod_resolution.rs
- crates/ra_ide_api/src/change.rs
- crates/ra_ide_api/src/symbol_index.rs
> make source_root API more abstract

- Cargo.lock
- crates/ra_cli/Cargo.toml
- crates/ra_cli/src/help.rs
- crates/ra_cli/src/main.rs
- crates/ra_tools/Cargo.toml
- crates/ra_tools/src/help.rs
- crates/ra_tools/src/main.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/1768
> refactor(args): Switch to pico-args

- Cargo.lock
- crates/ra_hir/src/ty.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/traits/chalk.rs
... and remove Ty::UnselectedProjection. It'll be handled differently.
> Upgrade Chalk

- crates/ra_assists/src/auto_import.rs
- crates/ra_hir/src/expr/validation.rs
- crates/ra_hir/src/name.rs
- crates/ra_hir/src/nameres.rs
- crates/ra_hir/src/path.rs
- crates/ra_hir/src/resolve.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_hir/src/ty/autoderef.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/tests.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/grammar.ron
> Support path starting with a type

- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/from_source.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/mock.rs
- crates/ra_hir/src/nameres/tests/incremental.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_ide_api/src/completion/completion_context.rs
- crates/ra_ide_api/src/diagnostics.rs
- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_ide_api/src/impls.rs
- crates/ra_ide_api/src/parent_module.rs
- crates/ra_ide_api/src/references.rs
- crates/ra_ide_api/src/runnables.rs
The idea is to provide an ability to get HIR from AST in a more general way than it's possible using `source_binder`. 
It also could help with #1622 fixing.
> Introduce FromSource trait

- crates/ra_parser/src/grammar.rs
- crates/ra_parser/src/grammar/attributes.rs
- crates/ra_parser/src/grammar/expressions.rs
- crates/ra_parser/src/grammar/expressions/atom.rs
- crates/ra_parser/src/grammar/items.rs
- crates/ra_parser/src/grammar/items/consts.rs
- crates/ra_parser/src/grammar/items/nominal.rs
- crates/ra_parser/src/grammar/items/traits.rs
- crates/ra_parser/src/grammar/items/use_item.rs
- crates/ra_parser/src/grammar/params.rs
- crates/ra_parser/src/grammar/patterns.rs
- crates/ra_parser/src/grammar/type_args.rs
- crates/ra_parser/src/grammar/type_params.rs
- crates/ra_parser/src/grammar/types.rs
> Replace usages of bump_any with bump

- crates/ra_hir/src/nameres/collector.rs
- crates/ra_hir/src/nameres/mod_resolution.rs
- crates/ra_hir/src/nameres/tests/mod_resolution.rs
> Fix path attribute causing false "unresolved module" error for submodules

- crates/ra_ide_api/Cargo.toml
- crates/ra_ide_api/src/change.rs
- crates/ra_ide_api/src/db.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_ide_api/src/symbol_index.rs
- crates/ra_ide_api/src/wasm_shims.rs
> allow compiling ra_ide_api on wasm

- crates/ra_parser/src/grammar/expressions/atom.rs
- crates/ra_syntax/test_data/parser/ok/0057_loop_in_call.rs
- crates/ra_syntax/test_data/parser/ok/0057_loop_in_call.txt
> Support loop as argument

- crates/ra_hir/src/db.rs
- crates/ra_hir/src/lang_item.rs
- crates/ra_hir/src/ty/traits/chalk.rs
- crates/ra_ide_api/src/change.rs
I used the wrong query, so it only used the lang items from the respective
crate...
> Fix retrieval of the Fn traits

- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/generics.rs
- crates/ra_hir/src/ty/infer/path.rs
- crates/ra_hir/src/ty/lower.rs
- crates/ra_hir/src/ty/tests.rs
E.g. `Default::default` or `<Foo as Default>::default`.
> Resolve trait associated items

- Cargo.lock
- crates/ra_assists/Cargo.toml
- crates/ra_assists/src/assists/move_bounds.rs
- crates/ra_assists/src/ast_editor.rs
- crates/ra_syntax/Cargo.toml
- crates/ra_syntax/src/algo.rs
- crates/ra_syntax/src/ast/extensions.rs
> add new editing API, suitable for modifying several nodes at once

- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/marks.rs
- crates/ra_hir/src/ty.rs
- crates/ra_hir/src/ty/autoderef.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/infer/path.rs
- crates/ra_hir/src/ty/infer/unify.rs
- crates/ra_hir/src/ty/lower.rs
- crates/ra_hir/src/ty/method_resolution.rs
- crates/ra_hir/src/ty/tests.rs
- crates/ra_hir/src/ty/traits/chalk.rs
> Add SubstsBuilder

- Cargo.lock
Has performance improvements. See https://github.com/alexcrichton/proc-macro2/issues/198
> proc-macro2 1.0.5

- crates/ra_hir/src/code_model/docs.rs
- crates/ra_ide_api/src/completion/complete_scope.rs
- crates/ra_ide_api/src/completion/completion_context.rs
- crates/ra_ide_api/src/completion/presentation.rs
- crates/ra_ide_api/src/marks.rs
@flodiebold wdyt? Is it correct that we always need to add `<>` in generic types?
> Add <> when completing generics

- crates/ra_ide_api/src/completion/complete_dot.rs
- crates/ra_ide_api/src/completion/complete_path.rs
- crates/ra_ide_api/src/completion/complete_scope.rs
- crates/ra_ide_api/src/completion/completion_item.rs
- crates/ra_ide_api/src/completion/presentation.rs
> if completion does auto-insertion, indicate this in the label

- editors/code/package.json
Per https://code.visualstudio.com/api/working-with-extensions/testing-extension
> engine.vscode and @types/vscode should match

- editors/code/package-lock.json
- editors/code/package.json
I got sick of the vsce warning on install and noticed that rollup was also out of date.
> Bump rollup and vsce

- crates/ra_lsp_server/src/lib.rs
> No need to make config pub

- crates/ra_ide_api/src/completion/complete_postfix.rs
- crates/ra_ide_api/src/completion/completion_context.rs
Fix for #1435 Incorrect postfix completion for integer literals
> #1435 postfix completion for integer literals

- Cargo.lock
> bump proc-macro-hack

- crates/ra_lsp_server/src/conv.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/world.rs
> Fixup folding ranges for clients with lineFoldingOnly=true

- crates/ra_assists/src/assists/early_return.rs
- crates/ra_assists/src/lib.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/make.rs
first draft for #1782. I'm pretty sure I missed something.
> Adds "replace with guarded return" assist

- crates/ra_lsp_server/src/main_loop/handlers.rs
> add couple of profiling calls

- Cargo.lock
- crates/ra_hir/Cargo.toml
- crates/ra_ide_api/Cargo.toml
> bump insta

- Cargo.lock
- crates/ra_hir/Cargo.toml
> Specify working chalk revisions in manifest

- crates/ra_ide_api/src/extend_selection.rs
When multiple traits bounds are present, expanded selection
from a single trait bound will include the nearest plus sign
(and whitespace after) before including the whole trait bound.
Fixes: #2055
> Extend selection in trait bound extends to plus

- crates/ra_ide_api/src/call_info.rs
Finds the closest call expr.
Fixes #2093
> Be more precise with function signatures

- crates/ra_ide_api/src/call_info.rs
- crates/ra_ide_api/src/display/function_signature.rs
Signature help using call syntax with tuple structs and enum variants
Fixes #2102.
> Expand signature help

- crates/ra_ide_api/src/call_info.rs
- crates/ra_ide_api/src/display/function_signature.rs
This is really basic and just adds info and docs. Does something like this even make sense to have? I wasn't sure how to handle arguments so left them empty for now.
> Basic signature help for mbe

- crates/ra_ide_api/src/call_info.rs
- crates/ra_syntax/src/lib.rs
Suggested by @matklad in https://github.com/rust-analyzer/rust-analyzer/pull/2129#discussion_r340708660
> Document match_ast! and use it in call_info

- editors/code/src/extension.ts
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/1831
> Add link to the vscode VIM extension compatibility warning.

- crates/ra_hir/src/source_binder.rs
- crates/ra_ide_api/src/runnables.rs
- crates/ra_syntax/src/ast/traits.rs
Use `match_ast!` in more places
> More match ast

- xtask/src/lib.rs
> Use run-time project path in xtask

- crates/ra_parser/src/grammar/types.rs
Needed to pass tests on latest stable
> cargo xtask format with rust 1.39

- crates/ra_ide_api/src/hover.rs
> Hover for builtins

- xtask/src/main.rs
> Fix snap missing node path

- crates/ra_ide_api/src/completion/complete_postfix.rs
- crates/ra_ide_api/src/feature_flags.rs
- docs/user/README.md
> Implement postfix completions feature flag

- Cargo.lock
- xtask/Cargo.toml
- xtask/src/main.rs
> Use autocfg to determine rust version

- crates/ra_prof/Cargo.toml
- crates/ra_prof/src/lib.rs
- crates/ra_prof/src/memory_usage.rs
> Even if jemalloc feature is used do not use it on msvc

- crates/ra_hir/src/from_source.rs
- crates/ra_ide_api/src/references.rs
- crates/ra_ide_api/src/references/classify.rs
> Handle ast::MacroCall in classify_name and impl FromSource for MacroDef

- crates/ra_hir/src/source_binder.rs
- crates/ra_hir_expand/src/lib.rs
- crates/ra_ide_api/src/goto_definition.rs
- crates/ra_mbe/src/syntax_bridge.rs
This builds on the awesome infrastructure created by @edwin0cheng
> goto in macro calls

- .github/workflows/ci.yaml
Example run: https://github.com/CAD97/libsyntax2/runs/306447310
VS Code tests are not yet working. Main tests seem to be approximately 10% faster on GitHub Actions than Travis.
Deployment should be done in a separate yaml file.
r? @matklad
> GitHub actions

- crates/ra_ide_api/src/hover.rs
Allows hover to work through macros like `match_ast!`.
> Support hover through macro

- crates/ra_hir/src/source_binder.rs
- crates/ra_ide_api/src/expand_macro.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/req.rs
- docs/user/features.md
- editors/code/package.json
- editors/code/src/commands/expand_macro.ts
- editors/code/src/commands/index.ts
- editors/code/src/extension.ts
> Show expanded macro in vscode

- .cargo/config
- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/expr.rs
- crates/ra_hir/src/generics.rs
- crates/ra_hir/src/impl_block.rs
- crates/ra_hir/src/resolve.rs
- crates/ra_hir/src/source_binder.rs
- crates/ra_hir/src/ty/infer.rs
- crates/ra_hir/src/ty/lower.rs
- crates/ra_ide_api/src/completion/complete_scope.rs
> Add HasResolver trait

- crates/ra_db/src/fixture.rs
- crates/ra_db/src/input.rs
- crates/ra_db/src/lib.rs
- crates/ra_ide_api/src/lib.rs
- crates/ra_ide_api/src/mock_analysis.rs
- crates/ra_ide_api/src/parent_module.rs
- crates/ra_project_model/src/lib.rs
> Add support for environment to CrateGraph

- crates/ra_hir/src/ty/tests.rs
- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_hir_expand/src/name.rs
See https://github.com/rust-analyzer/rust-analyzer/pull/2355#issuecomment-557541873
> Expand file! to dummy ""

- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_hir_expand/src/db.rs
- crates/ra_hir_expand/src/lib.rs
- crates/ra_hir_expand/src/test_db.rs
Refactor builtin macro and add some local tests.
> Refactor builtin macro

- crates/ra_ide_api/src/expand_macro.rs
Due to lack of implementation or other types of errors, some macros do not expand correctly in the current situation. The PR attempts to make `expand-macro` more flexible in error situations by ignoring internal failed macro expansion.
> Make expand-macro more flexible

- crates/ra_hir/src/source_binder.rs
- crates/ra_hir_def/src/path.rs
- crates/ra_ide_api/src/call_info.rs
- crates/ra_ide_api/src/expand_macro.rs
- crates/ra_ide_api/src/references/classify.rs
This should fix https://github.com/rust-analyzer/rust-analyzer/pull/2392#issuecomment-557964686
> Add hygiene information to SourceAnalyzer

- Cargo.lock
- crates/ra_cli/Cargo.toml
- crates/ra_cli/src/analysis_stats.rs
- crates/ra_cli/src/main.rs
- crates/ra_cli/src/progress_bar.rs
- crates/ra_cli/src/progress_report.rs
> Use a simple progress bar instead of indicatif

- crates/ra_tt/src/lib.rs
Preparation for intern `TokenTree` to salsa database
> Derive Hash for tt::TokenTree

- crates/ra_ide/src/lib.rs
- crates/ra_ide/src/references/rename.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
> Only allow renames to valid identifiers

- crates/ra_hir/src/source_binder.rs
- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/nameres.rs
- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_def/src/nameres/path_resolution.rs
- crates/ra_hir_def/src/resolver.rs
- crates/ra_hir_ty/src/tests.rs
This PR try to fix #1905 by introduce an `BuiltinShadowMode` in name resolving functions. 
cc @flodiebold
> Add BuiltinShadowMode

- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/grammar.ron
> Add `ModuleItemsOwner` to `Block`

- crates/ra_assists/src/assists/add_new.rs
> Get rid of unwraps in add_new

- README.md
- docs/user/README.md
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/extension.ts
- editors/code/src/server.ts
I'm not really sure about the TS changes. I just made a couple of functions async and it seems to work.
> Code: check whether the LSP binary is in PATH

- crates/ra_hir_def/src/nameres/collector.rs
This PR make the following changes:
* Delay legacy macro expansion such that we concentrated all item collecting macro expansion in one place.
* Add `MacroDirective` to replace 3-tuples 
* After this refactoring, no macro is expanded recursively, hence we can remove the `MacroStackMonitor` and we handle the expansion limit by the fix-point loop count.
> Delay legacy macro expansion

- .vscode/launch.json
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/rollup.config.js
> Add sourcemap for rollup and fix launch.json outfiles

- crates/ra_ide/src/extend_selection.rs
Bugfix Debriefing:
1. Tuple in type annotation expands correctly;
2. Expansion will prefer the following delimiter when possible. This involves modification of previous test cases to match current behaviour. 
3. New regression tests added to verify the consistency between tuple expansion in type annotation and tuple expansion in rvalue. Both should behave exactly the same.
> Fixed #2250

- Cargo.lock
- crates/ra_lsp_server/Cargo.toml
- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/tests/heavy_tests/main.rs
This merely upgrades our protocol support. It does not add any of the new features.
> Support LSP 3.15

- crates/ra_lsp_server/src/caps.rs
Brings us in line with TS.
Context: https://github.com/rust-analyzer/rust-analyzer/issues/2532#issuecomment-564994368
> Do not trigger signature help on close

- crates/ra_hir_def/src/path.rs
- crates/ra_hir_expand/src/name.rs
- crates/ra_hir_ty/src/infer.rs
- crates/ra_hir_ty/src/infer/expr.rs
- crates/ra_hir_ty/src/tests/traits.rs
Found some low hanging fruit while taking a cursory look at index inferring.
> Infer - and ! using std::ops::{Neg, Not}

- crates/ra_assists/src/assists/add_new.rs
I think this file could probably be simplified a little more but this at least gets me around the panic.
Fixes #2556
> Remove some unwraps in add_new

- crates/ra_batch/src/lib.rs
- crates/ra_lsp_server/src/config.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/server.ts
> Support setting cargo features and resolve `default` features by default

- editors/code/package.json
- editors/code/src/commands/cargo_watch.ts
- editors/code/src/config.ts
> Add option to disable all-targets.

- docs/user/README.md
I took some freedom to remove additional tips that I simply considered unnecessary as I view it as responsibility of plugin's own docs.
> Cleanup Vim and NeoVim instructions. Fix #2579

- Cargo.lock
- crates/ra_hir/src/from_source.rs
- crates/ra_hir_def/Cargo.toml
- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_ide/src/goto_definition.rs
> More ground work for local defs

- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_syntax/src/ast/edit.rs
Just a few tweaks from the latest clippy.  There are a lot more but we should probably tweak our settings.
> Clippy cleanup

- Cargo.lock
Brings in https://github.com/gluon-lang/lsp-types/pull/129 for https://github.com/rust-analyzer/rust-analyzer/issues/2651#issuecomment-568554427
> Update lsp-types and rayon

- xtask/src/main.rs
> Notify that latest version of VS Code is required

- crates/ra_hir_def/src/lang_item.rs
- crates/ra_hir_def/src/path.rs
- crates/ra_hir_ty/src/infer.rs
- crates/ra_hir_ty/src/tests/simple.rs
- crates/ra_hir_ty/src/tests/traits.rs
As we already have the infrastructure for collecting lang items, use it to find the right traits when doing type-inference.
> Resolve traits for infer using lang item infrastructure

- crates/ra_cargo_watch/src/conv.rs
- crates/ra_cargo_watch/src/lib.rs
- crates/ra_lsp_server/src/world.rs
> Fix cargo-watcher file urls on windows

- editors/code/src/server.ts
> Fix server config mispell in vscode extension

- crates/ra_prof/src/lib.rs
In particular:
- Use strict inequality for comparisons, since that's what the filter
syntax supports.
- Convert to millis for comparisons, since that's the unit used both
for the filter and when printing.
Now something like `RA_PROFILE='*>0'` will only print things that took
at least 1ms (when rounded to millis).
Signed-off-by: Michal Terepeta <michal.terepeta@gmail.com>
> Improve profiling output when duration filter is specified

- .github/workflows/ci.yaml
- bors.toml
Make GitHub actions run our tests on all their currently supported platforms.
This will probably require some trial and error as this can't really be tested locally :)
> Run tests on ubuntu, windows and macos

- .github/workflows/ci.yaml
bors r+
I predict that bors will fail on this PR with permissions denied
> Try to restore caching on CI

- crates/ra_ide/src/expand.rs
This PR fixed a bug which `descend_into_macros` cannot resolve deeper macro, by use source node for SourceAnalyzer.
> Use src node for analyze source in `descend_into_macros`

- crates/ra_ide/src/references.rs
- crates/ra_ide/src/references/rename.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
> [Draft] Adds a way to limits reference search by StructLiteral

- Cargo.lock
- crates/ra_ide/Cargo.toml
- crates/ra_ide/src/call_hierarchy.rs
- crates/ra_ide/src/call_info.rs
- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide/src/lib.rs
- crates/ra_lsp_server/src/caps.rs
- crates/ra_lsp_server/src/conv.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/req.rs
Support experiment incoming and outgoing calls.
Fixes #2546
> Call Hierarchy

- crates/ra_parser/src/grammar/items/traits.rs
- crates/ra_syntax/test_data/parser/inline/ok/0151_trait_alias.rs
- crates/ra_syntax/test_data/parser/inline/ok/0151_trait_alias.txt
Implements the needed changes to correctly parse trait aliases.
This is my first change in the parser code, so would appreciate a comment on whether this is the right way to go about it.
> Parse trait aliases

- crates/ra_ide/src/hover.rs
This PR implement back the `Local` hover information generation, which is fall back to a general case catch previously :
https://github.com/rust-analyzer/rust-analyzer/blob/9a44f627be0b3c49184e3ad594849f9b5ed78daa/crates/ra_ide/src/hover.rs#L173-L182
> Proper handling local in hover

- crates/ra_hir_expand/src/db.rs
I will open another issues for tracking adding back the cases implemented in the PR.
> Add missing expr cases for expand macro

- crates/ra_hir_expand/src/db.rs
- crates/ra_hir_ty/src/tests/macros.rs
> Add test for macro expansion in various expressions

- crates/ra_cargo_watch/src/lib.rs
- crates/ra_lsp_server/src/main_loop.rs
> Defer cargo check until after workspace load

- editors/code/package-lock.json
- editors/code/package.json
The main change is that it removes progress from the proposed section.
> vscode-languageclient 6.0.0-next.10

- crates/ra_assists/src/assists/add_custom_impl.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
Display a nicer label and categorize
> Tweak add_custom_impl

- crates/ra_assists/src/assist_ctx.rs
Re: https://github.com/rust-analyzer/rust-analyzer/pull/2841#discussion_r366510725
thanks @bjorn3!
> Cleanup assert

- editors/code/package-lock.json
- editors/code/package.json
> Language Server Protocol 3.15 is now stable

- Cargo.lock
- crates/ra_cargo_watch/Cargo.toml
- crates/ra_lsp_server/Cargo.toml
Stabilizes most proposed features
> lsp-types 0.69.0

- crates/ra_prof/src/lib.rs
Previously `ra_prof` wouldn't actually print the unaccounted time in
some cases.
We would print, for instance, this:
```
5ms - foo
2ms - bar
```
instead of:
```
5ms - foo
2ms - bar
3ms - ???
```
The fix is to properly handle the case when an entry has 0 children
instead of using the `last` variable.
Signed-off-by: Michal Terepeta <michal.terepeta@gmail.com>
> Fix a corner case when printing unaccounted time

- crates/ra_assists/src/assists/inline_local_variable.rs
This also affects issues like #2666.
> fixed inline_local_variable bug #2900

- editors/code/package-lock.json
- editors/code/package.json
Adds client side support for proposed semantic highlighting extension
> vscode-languageclient 6.1.0

- crates/ra_ide/src/references.rs
Hey, I've made some changes to improve search for struct literals, now it works for `struct Foo<|> {`, `struct Foo <|>{`, `struct Foo<|>(`. Unfortunately tuple creation is represented as a call expression, so for tuples it works only is search is started in a tuple declaration.  It leads to incorrect classification of function calls during search phase, but from user perspective it's not visible and works as expected. May be it worth to add a comment or rename it to remove this misleading classification. Issue #2549.
> Improves reference search by StructLiteral

- crates/ra_lsp_server/src/main_loop.rs
> Don't compute diagnostics on the main thread

- crates/ra_assists/src/assists/auto_import.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/2932
The corresponding test has the caret placed in the beginning of the document despite the import inserted, but I don't think I should fix it here:
* in real life, there's some text written before the import and for those cases the caret behaves normally
* it's a separate functionality that needs to be refactored anyway later (the `auto_import_text_edit`)
> Properly select a target for auto importing

- crates/ra_project_model/src/cargo_workspace.rs
In some rare cases, deps node-id from cargo-metadata do not match its version-id, which cause a panic in `cargo-workspace.rs`. This PR try to ignore these ill-formed node id from `cargo-metadata`. An alternative is return  `Err` in these cases but I think make it resilience is a better choice here.
Related #2767
> Better handle illformed node id from metadata

- editors/code/src/color_theme.ts
- editors/code/src/highlighting.ts
- editors/code/tsconfig.json
> [VSCode] Fix syntax highlighting

- editors/code/package.json
> Fix repo link in package.json

- crates/ra_assists/src/assists/auto_import.rs
- crates/ra_ide/src/inlay_hints.rs
A follow-up to https://github.com/rust-analyzer/rust-analyzer/pull/2990#discussion_r374044482
> Small cleanup

- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_def/src/nameres/raw.rs
- crates/ra_hir_def/src/path.rs
- crates/ra_hir_def/src/path/lower/lower_use.rs
pre for Fixing Issue 2736 
edited to avoid autoclosing the issue
> Differentiate underscore alias from named aliases

- docs/user/README.md
I hope I got the typo right 😅 
Thanks a lot of this wonderful project 🙇
> Fix unneeded `.` in `docs/user/README.md`

- editors/code/package-lock.json
- editors/code/src/client.ts
- editors/code/src/color_theme.ts
- editors/code/src/commands/on_enter.ts
- editors/code/src/config.ts
- editors/code/src/highlighting.ts
- editors/code/src/main.ts
It compiles, it runs in dev extension host, It bundles, it runs when bundled and installed.
Removed 5 lines of code as you like less code, especially TypeScript code)
> vscode: yet another refactor commit

- editors/code/package.json
- editors/code/src/commands/index.ts
- editors/code/src/commands/syntax_tree.ts
- editors/code/src/config.ts
- editors/code/src/highlighting.ts
- editors/code/src/inlay_hints.ts
- editors/code/src/status_display.ts
- editors/code/tslint.json
> vscode: eliminate floating promises and insane amount of resource handle leaks

- crates/ra_assists/src/doc_tests/generated.rs
- crates/ra_assists/src/handlers/auto_import.rs
- crates/ra_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ra_assists/src/lib.rs
- crates/ra_ide/src/completion/complete_scope.rs
- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/ast/generated.rs
- docs/user/assists.md
- xtask/src/lib.rs
Based on the https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/2.20assists.20with.20the.20same.20action.20name/near/187655643 and the related discussion.
> Rename add import assist

- crates/ra_ide/src/completion/complete_scope.rs
We now have a real auto-import system, so we can do a proper thing.
> Remove hard-coded auto-import during completion

- README.md
- crates/ra_syntax/Cargo.toml
Make capitalization more consistent and fix some typos.
> Some README fixes/cleanups

- crates/ra_assists/src/assist_ctx.rs
- crates/ra_assists/src/doc_tests.rs
- crates/ra_assists/src/handlers/auto_import.rs
- crates/ra_assists/src/lib.rs
- crates/ra_ide/src/assists.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
Instead of building a physical tree structure, just tag related
assists with the same group
> Simplify Assists interface

- crates/ra_assists/src/handlers/auto_import.rs
> Set auto-import target

- crates/ra_assists/src/handlers/auto_import.rs
Part of initial https://github.com/rust-analyzer/rust-analyzer/pull/3061, closing 2nd issue mentioned in the last comment there.
> Do not import anything if first segment of the qualified path resolves

- docs/dev/README.md
- docs/user/README.md
Better documented breaking changes as per an incident in #2988
Follow up for #3053
> Freshen docs for prebuilt binaries and raLspServer setting

- editors/code/src/installation/download_file.ts
> vscode: add error handling to downloadFile()

- editors/code/src/config.ts
> vscode: filter out arm linux from using prebuilt binaries

- crates/ra_ide/src/references.rs
- crates/ra_ide/src/references/rename.rs
> Handle macro token cases for rename

- editors/code/src/installation/download_file.ts
- editors/code/src/installation/language_server.ts
Inspired by [cpptools code](https://github.com/microsoft/vscode-cpptools/blob/0d91db0e060b946939ee620130c1dbc0fb1d7c42/Extension/src/packageManager.ts#L385-L386)
> vscode: remove chmod in favour of an option to createWriteStream()

- crates/ra_lsp_server/src/main_loop/handlers.rs
> prevent "Play" symbol in "Run Test" code lens from rendering as emoji

- .github/workflows/release.yaml
[npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b)
> cicd: simplify vsce call

- editors/code/src/inlay_hints.ts
> vscode: fix stupid mistake of mine

- .vscode/launch.json
> vscode: skip node internals while debugging

- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/lib.rs
- crates/ra_hir_def/src/nameres/collector.rs
This PR introduce `AsMacroCall` trait to help convert `ast::MacroCall` to `MacroCallId`. The main goal here is to centralize various conversions to single place and make implementing eager macro calls without further ado.
```rust
pub trait AsMacroCall {
fn as_call_id(
&self,
db: &(impl db::DefDatabase + AstDatabase),
resolver: impl Fn(path::ModPath) -> Option<MacroDefId>,
) -> Option<MacroCallId>;
}
```
> Introduce AsMacroCall trait

- docs/dev/debugging.md
Updated `debugging.md` file, added two useful demo videos.
> Update debug docs

- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/inlay_hints.ts
> vscode: minor refactorings

- crates/ra_lsp_server/src/config.rs
- crates/ra_lsp_server/src/main_loop.rs
- crates/ra_lsp_server/src/main_loop/handlers.rs
- crates/ra_lsp_server/src/world.rs
- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/config.ts
> Add ability to pass additional arguments to rustfmt.

- editors/code/package-lock.json
- editors/code/package.json
Fixes semantic token mispellings
> vscode-languageclient 6.1.1

- editors/code/src/installation/server.ts
> vscode: remove comment about updates notification

- crates/ra_ide/src/syntax_highlighting.rs
> Cleanup imports

- crates/ra_assists/src/doc_tests/generated.rs
- crates/ra_assists/src/handlers/remove_mut.rs
- crates/ra_assists/src/lib.rs
- docs/user/assists.md
> Add `remove_mut` assist

- crates/ra_ide/src/extend_selection.rs
> Extend selection handles commas in tuple pats

- crates/ra_hir/src/code_model.rs
- crates/ra_ide/src/references/classify.rs
- crates/ra_ide/src/references/search_scope.rs
- crates/ra_ide_db/src/defs.rs
> Don't store deriveable Module info in NameDefinition

- crates/ra_ide/src/references/classify.rs
- crates/ra_ide/src/references/search_scope.rs
- crates/ra_ide_db/src/defs.rs
> Derive visibility as well

- crates/ra_ide/src/goto_definition.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide/src/references/classify.rs
- crates/ra_ide/src/references/search_scope.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide_db/src/defs.rs
- crates/ra_ide_db/src/imports_locator.rs
> Merge NameDefinition and NameKind

- Cargo.lock
- crates/rust-analyzer/src/caps.rs
> Bump lsp-types

- crates/ra_prof/Cargo.toml
- crates/ra_prof/src/lib.rs
> Make backtrace optional

- crates/ra_hir_ty/src/expr.rs
- crates/ra_ide/src/diagnostics.rs
> Fill missing fields of enum variants

- crates/ra_hir_ty/src/method_resolution.rs
- crates/ra_hir_ty/src/tests/method_resolution.rs
> Exclude methods from non-parameter types introduced by generic constraints

- crates/rust-analyzer/src/main_loop.rs
> Better errorse

- editors/code/.eslintrc.js
- editors/code/src/color_theme.ts
- editors/code/src/commands/expand_macro.ts
- editors/code/src/installation/fetch_artifact_release_info.ts
> enforce camel case

- crates/ra_hir_ty/src/infer/unify.rs
- crates/ra_hir_ty/src/tests/traits.rs
> Normalize associated types in types coming from Chalk

- docs/user/features.md
- docs/user/readme.adoc
Thought I'd tidy up the docs while reading through them. Hope you don't mind!
For the most part, I just made the formatting consistent through-out and added a few words here and there. Also updated the language server install graphic.
> Tidy up documentation.

- crates/ra_mbe/src/subtree_source.rs
- crates/ra_mbe/src/tests.rs
> ra_mbe: convert_literal now works with malformed tokens

- crates/ra_hir_def/src/item_scope.rs
- crates/ra_hir_def/src/nameres/path_resolution.rs
- crates/ra_hir_def/src/resolver.rs
- crates/ra_ide/src/completion/complete_path.rs
- crates/ra_ide/src/marks.rs
This fixes autocompletion suggesting e.g. `self::usize`. (I thought we had a bug for that, but I didn't find it.)
> Refactor how builtins are resolved

- docs/user/features.md
Closes https://github.com/rust-analyzer/rust-analyzer/issues/3267
> Add inlay hints documentation

- docs/user/features.md
Addresses the first point of https://github.com/rust-analyzer/rust-analyzer/issues/3186.
> Add Structural Search and Replace doc

- editors/code/.eslintrc.js
- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/inlay_hints.ts
- editors/code/src/installation/download_artifact.ts
- editors/code/src/installation/download_file.ts
- editors/code/src/installation/fetch_artifact_release_info.ts
- editors/code/src/installation/server.ts
- editors/code/src/main.ts
- editors/code/src/util.ts
> Extract client-side logging

- editors/code/src/ctx.ts
- editors/code/src/highlighting.ts
- editors/code/src/inlay_hints.ts
- editors/code/src/util.ts
This PR fixes a fleet of errors that rapidly populate the Developer Tools console.
> vscode: gracefully handle cancellation errors

- crates/ra_ide/src/inlay_hints.rs
After using new hints for a while, I've started to think that hints for enum variants are an overkill.
Another user also shares the same toughts: https://github.com/rust-analyzer/rust-analyzer/issues/3273#issuecomment-590172297
> Omit type hints for enum variant bind pats

- editors/code/src/main.ts
> Don't break onEnter if rust-analyzer fails to start

- editors/code/src/installation/server.ts
> Quick fix circular json error when sanity-check fails

- editors/code/src/commands/on_enter.ts
> Don't block onEnter if request fails

- Cargo.lock
- crates/ra_syntax/Cargo.toml
> :arrow_up: rowan

- crates/ra_assists/src/handlers/introduce_variable.rs
- crates/ra_assists/src/lib.rs
- crates/test_utils/src/lib.rs
> Remove code duplication in tests

- Cargo.lock
- crates/ra_ide/Cargo.toml
- crates/ra_ide_db/Cargo.toml
> Actually drop unicase dependency

- crates/ra_hir/src/from_id.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir/src/source_binder.rs
> Reduce visibility

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/installation/download_artifact.ts
> Remove unnecessary dep

- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/config.ts
- editors/code/src/main.ts
> Config to switch to semantic tokens

- crates/ra_ide/src/lib.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide/src/syntax_highlighting/highlight_tag.rs
- crates/rust-analyzer/src/conv.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/req.rs
> More type safety for highlighting

- crates/rust-analyzer/src/conv.rs
> Fix bitset ops

- .github/workflows/ci.yaml
> cicd: add cargo audit

- editors/code/src/client.ts
> Fix flickering with new syntax highlighting

- .github/workflows/ci.yaml
- editors/code/package.json
- editors/code/src/client.ts
> Actually gate CI on eslint

- xtask/src/install.rs
- xtask/src/not_bash.rs
> Make xtask install path-agnostic

- crates/ra_ide/src/syntax_highlighting.rs
> Split loop into orthogonal phases

- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide/src/syntax_highlighting/tests.rs
> More cleanup

- crates/ra_ide_db/src/line_index.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
> Ensure that semantic tokens are single-line

- crates/ra_ide/src/hover.rs
Since currently (or impossible ?) builtin-macro do not support mapping up/down tokens. 
This PR add a guard to check whether the `descend_into_macro` fail to expand and return `None` from `hover`.
> Ignore hover on builtin macro

- crates/ra_assists/src/handlers/raw_string.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_syntax/src/ast/tokens.rs
> Refactor string literals

- crates/ra_assists/src/handlers/raw_string.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_syntax/src/ast/tokens.rs
- editors/code/package.json
> Map unsafe keyword

- editors/code/package.json
> Set attr scope

- editors/code/package.json
> Map builtin

- crates/ra_parser/src/grammar/expressions.rs
- crates/ra_syntax/test_data/parser/inline/ok/0130_let_stmt.rs
- crates/ra_syntax/test_data/parser/inline/ok/0130_let_stmt.txt
> Parse attribues in RHS of let statments

- editors/code/package.json
@matklad i didn't see this mentioned anywhere else in the features.md
> removing ctrl+r key binding fixes #2733

- crates/ra_ide/src/snapshots/highlighting.html
- crates/ra_ide/src/snapshots/rainbow_highlighting.html
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide/src/syntax_highlighting/html.rs
- crates/ra_ide/src/syntax_highlighting/tags.rs
- crates/ra_ide/src/syntax_highlighting/tests.rs
- crates/rust-analyzer/src/conv.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- editors/code/package.json
> Cleanup highlighting tags

- crates/ra_assists/src/ast_transform.rs
- crates/ra_assists/src/handlers/early_return.rs
- crates/ra_assists/src/handlers/move_bounds.rs
- crates/ra_ide/src/expand_macro.rs
- crates/ra_mbe/src/syntax_bridge.rs
- crates/ra_syntax/src/algo.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/make.rs
> Cleanup editing API a bit

- crates/ra_ide/src/syntax_highlighting.rs
> Remove debug print

- crates/rust-analyzer/src/main_loop/handlers.rs
> Tighten up an assert

- crates/ra_assists/src/ast_transform.rs
> One more assert

- editors/code/README.md
- editors/code/package.json
> Minimal viable meta

- editors/code/src/highlighting.ts
> Don't fail loudly if the old highlighting breaks

- editors/code/src/highlighting.ts
- xtask/src/lib.rs
> Print log on release

- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_ide/src/goto_definition.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide/src/references/classify.rs
- crates/ra_ide/src/syntax_highlighting.rs
Callers can now decide for themselves if they should prefer field or
local definition. By default, it's the local.
bors r+
🤖
> More principled approach for gotodef for field shorhand

- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_ide/src/goto_definition.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide/src/references/classify.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide_db/src/defs.rs
> Simplify: remove couple of useless functions

- Cargo.lock
- crates/ra_hir_ty/Cargo.toml
- crates/ra_hir_ty/src/traits/chalk.rs
> Update chalk for RawId removal, Ty interners

- crates/ra_ide/src/syntax_highlighting.rs
> Remove stray dbg

- crates/ra_assists/src/handlers/inline_local_variable.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/marks.rs
- crates/ra_ide/src/syntax_highlighting.rs
> Highlight assist tests

- crates/ra_ide/src/references.rs
> Add profile call

- crates/ra_hir/src/code_model.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide_db/src/defs.rs
> Refactor reference search a bit

- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide/src/references/classify.rs
- crates/ra_ide/src/references/search_scope.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide_db/src/defs.rs
- crates/ra_ide_db/src/imports_locator.rs
- editors/code/.vscodeignore
> Rename NameDefinition -> Definition

- crates/ra_ide/src/completion/complete_path.rs
- crates/ra_ide/src/completion/presentation.rs
> Fix completion snippet for reexported functions

- Cargo.lock
- crates/ra_ide/src/goto_definition.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide_db/Cargo.toml
- crates/ra_ide_db/src/defs.rs
- crates/ra_ide_db/src/lib.rs
- crates/ra_ide_db/src/marks.rs
- crates/test_utils/src/marks.rs
> Remove stray FIXME

- crates/ra_ide/src/completion/presentation.rs
> Skip self param when completing methods

- crates/ra_assists/src/handlers/inline_local_variable.rs
- crates/ra_assists/src/marks.rs
- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
> Remove old find refs infra

- crates/ra_hir/src/source_analyzer.rs
> Minor cleanup

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
> Deindent YAML

- .github/actions/github-release/Dockerfile
- .github/actions/github-release/README.md
- .github/actions/github-release/action.yml
- .github/actions/github-release/main.js
- .github/actions/github-release/package.json
- .github/workflows/release.yaml
This doesn't publish nightly plugin to the marketplace yet
bors r+
🤖
> Nightly binary releases

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
> Remove needless dep

- .github/workflows/release.yaml
- .gitignore
- xtask/src/install.rs
- xtask/src/lib.rs
- xtask/src/main.rs
- xtask/src/not_bash.rs
This builds the typescript extension
bors r+
🤖
> cargo xtask dist

- .github/workflows/rustdoc.yaml
> Fix yaml syntax

- .github/workflows/rustdoc.yaml
> Fix rustdoc some more

- .github/workflows/release.yaml
- xtask/src/dist.rs
- xtask/src/lib.rs
- xtask/src/main.rs
> Use xtask dist for releases

- .github/workflows/release.yaml
> Install node for release

- xtask/src/dist.rs
> Don't disable proposed features for nightly

- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
> Cleanup SourceAnalyzer

- crates/ra_hir_expand/src/builtin_derive.rs
- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_hir_expand/src/db.rs
- crates/ra_mbe/src/mbe_expander/matcher.rs
- crates/ra_mbe/src/syntax_bridge.rs
- crates/ra_mbe/src/tests.rs
- crates/ra_mbe/src/tt_iter.rs
> Fix mbe composited token bug

- xtask/src/dist.rs
> Install node deps during dist

- xtask/src/dist.rs
- xtask/src/not_bash.rs
> Remove pwd

- xtask/src/dist.rs
> Fix dist again

- crates/ra_ide/src/lib.rs
- crates/ra_ide/src/prime_caches.rs
- crates/rust-analyzer/src/main_loop.rs
> Prime open files on load

- crates/rust-analyzer/src/bin/args.rs
> Fix options for analysis-bench

- crates/ra_hir_def/src/data.rs
- crates/ra_hir_def/src/generics.rs
> Add profiling calls

- README.md
> Link proper docs from readme

- crates/ra_syntax/src/ast/edit.rs
> Add with_use_tree

- crates/ra_assists/src/handlers/split_import.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/make.rs
The code is more verbose and less efficient now, but should be
reusable in add_import context as well
bors r+
🤖
> Rerail split_import API onto AST

- crates/ra_db/src/fixture.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_ty/src/expr.rs
- crates/ra_hir_ty/src/tests.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
> More robust expression lowering 

- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/make.rs
> Simplify creation of `T[,]`

- crates/ra_hir_ty/src/infer.rs
- crates/ra_hir_ty/src/tests/simple.rs
- crates/ra_ide/src/diagnostics.rs
> Support aliases and Self in struct literals

- crates/ra_syntax/src/ast/make.rs
> make::use_item

- crates/ra_hir_def/src/db.rs
- crates/ra_hir_def/src/nameres.rs
- crates/ra_hir_ty/src/db.rs
- crates/ra_hir_ty/src/infer.rs
> Less confusing profile names

- crates/ra_hir_ty/src/db.rs
- crates/ra_hir_ty/src/traits.rs
- crates/ra_prof/src/lib.rs
> Allow specifying additional info on call to profile

- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide_db/src/feature_flags.rs
- crates/rust-analyzer/src/conv.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- editors/code/package.json
> Don't creat public APIs with typos

- editors/code/package-lock.json
- editors/code/package.json
> :arrow_up: npm deps

- crates/ra_hir/src/db.rs
- crates/ra_hir_def/src/db.rs
- crates/ra_hir_def/src/nameres.rs
- crates/ra_hir_ty/src/db.rs
- crates/ra_hir_ty/src/infer.rs
- crates/ra_hir_ty/src/lib.rs
- crates/ra_ide_db/src/change.rs
> Normalize waiting queries names

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
> Use actions/checkout@v2

- crates/ra_ide/src/inlay_hints.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/3488
> Omit unit struct hints

- crates/rust-analyzer/src/main_loop.rs
> Ignore client-specific notifications

- crates/ra_db/src/fixture.rs
- crates/ra_db/src/input.rs
- crates/ra_hir/src/code_model.rs
- crates/ra_hir_def/src/find_path.rs
- crates/ra_hir_def/src/lang_item.rs
- crates/ra_hir_def/src/nameres.rs
- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_ty/src/traits.rs
- crates/ra_ide/src/display.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/lib.rs
- crates/ra_ide/src/mock_analysis.rs
- crates/ra_ide/src/parent_module.rs
- crates/ra_ide_db/src/change.rs
- crates/ra_ide_db/src/lib.rs
- crates/ra_project_model/src/lib.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/world.rs
> Show mod path on hover

- crates/ra_hir_def/src/nameres.rs
> Print crate name in profil

- docs/user/readme.adoc
> Fix quotes

- docs/user/readme.adoc
- xtask/src/dist.rs
> Use jemalloc for linux builds

- Cargo.lock
- crates/ra_ide_db/Cargo.toml
- crates/ra_ide_db/src/symbol_index.rs
> :arrow_up: fst

- crates/ra_ide/src/completion/complete_trait_impl.rs
Allow trait autocompletions for unimplemented associated fn's, types,
and consts without using explicit keywords before hand (fn, type,
const).
The sequel to #3108.
> Next steps in assoc item completion #3183

- crates/ra_ide/src/typing.rs
- crates/ra_ide/src/typing/on_enter.rs
> Continue multiline non-doc comment blocks

- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/generated.rs
- xtask/src/codegen/gen_syntax.rs
> Add `std::fmt::Display` as a supertrait for `AstNode`

- crates/ra_ide/src/completion/complete_scope.rs
- crates/ra_ide/src/completion/completion_item.rs
- crates/ra_ide/src/completion/presentation.rs
> Fix completion tests

- crates/ra_parser/src/grammar/params.rs
- crates/ra_syntax/src/tests.rs
- crates/ra_syntax/test_data/parser/inline/ok/0032_fn_pointer_type.txt
- crates/ra_syntax/test_data/parser/inline/ok/0123_param_list_vararg.txt
- crates/ra_syntax/test_data/parser/ok/0051_parameter_attrs.txt
- crates/ra_syntax/test_data/parser/ok/0063_variadic_fun.rs
- crates/ra_syntax/test_data/parser/ok/0063_variadic_fun.txt
> Parse variadics correctly

- crates/ra_hir_def/src/nameres/collector.rs
Something I noticed while trying to make macro expansion more resilient against errors.
There was a test for this, but it wasn't actually working because the first recursive expansion failed. (The comma...)
Even with this limit, that test (when fixed) still takes some time to pass because of the exponential growth of the expansions, so I disabled it and added a different one without growth.
CC @edwin0cheng
> Protect against infinite macro expansion in def collector

- crates/ra_hir_def/src/data.rs
- crates/ra_hir_def/src/visibility.rs
- crates/ra_ide/src/completion/complete_dot.rs
Trait items should be public by default.
> Fix completion of trait items

- crates/ra_ide/src/display.rs
- crates/ra_ide/src/hover.rs
https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/hover/near/190671355
> ra_ide: remove dead code, migrate from readonly String -> &str

- crates/ra_ide/src/lib.rs
- crates/ra_ide/src/ssr.rs
- crates/ra_syntax/src/ast/make.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/req.rs
- editors/code/src/commands/ssr.ts
- editors/code/src/rust-analyzer-api.ts
> Swtches to rust SSR query check

- crates/ra_db/src/fixture.rs
- crates/ra_db/src/input.rs
- crates/ra_hir_def/src/nameres.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/mock_analysis.rs
- crates/ra_project_model/src/lib.rs
A follow-up of https://github.com/rust-analyzer/rust-analyzer/pull/3602#discussion_r392733525
> Fix crate display name dashes

- crates/ra_ide/src/hover.rs
> Remove dat fixme

- .github/workflows/ci.yaml
https://github.com/rust-analyzer/rust-analyzer/runs/511553989?check_suite_focus=true#step:3:6
bors r+
🤖
> Retry rust audit as well

- .github/workflows/ci.yaml
> Cache cargo-audit on CI

- .github/workflows/ci.yaml
> Fix audit caching better

- .github/workflows/ci.yaml
- editors/code/src/commands/server_version.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/installation/extension.ts
- editors/code/src/installation/server.ts
- editors/code/src/main.ts
- editors/code/src/persistent_state.ts
That way, we clearly see which things are not change, and we also
clearly see which things are persistent.
r? @Veetaha
> Separate persistent mutable state from config

- .github/workflows/release.yaml
Should Fix https://github.com/rust-analyzer/rust-analyzer/issues/3589
> Gate release action to rust-analyzer owner

- xtask/src/dist.rs
> Make xtask dist more reliable

- crates/ra_assists/src/handlers/move_bounds.rs
- crates/ra_syntax/src/lib.rs
> Use match_ast

- editors/code/package-lock.json
- editors/code/package.json
> :arrow_up: npm

- crates/ra_assists/src/handlers/merge_imports.rs
- crates/ra_assists/src/handlers/merge_match_arms.rs
- crates/ra_syntax/src/algo.rs
> Generalize

- crates/ra_assists/src/handlers/merge_imports.rs
> Merge nested use trees

- editors/code/package-lock.json
- editors/code/package.json
Looks like it broke completion :(
bors r+
🤖
> Downgrade vscode-langaugeclient

- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- crates/ra_project_model/src/sysroot.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
> More direct CargoWorkspace

- docs/user/readme.adoc
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/main.ts
- xtask/src/dist.rs
- xtask/src/install.rs
> Make from-source install use cargo installed binary by default

- crates/ra_project_model/src/lib.rs
> Use target-name for crate-name in Crate graph building

- crates/ra_hir_def/src/body.rs
> Add recursive limit for macro expansion when expanding expression

- crates/ra_cargo_watch/src/conv.rs
- crates/ra_cargo_watch/src/conv/snapshots/ra_cargo_watch__conv__test__snap_clippy_pass_by_ref.snap
Fixes #3676
Fixes #3633
Fixes #3391 
r? @kiljacken
> Only include machine-applicable suggestions

- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/source_analyzer.rs
@matklad I have a feeling you won't like the name or maybe the constructor I added to `Type`. If so, please elaborate on how this should be done instead (or maybe even not done anyhow).
> ra_hir: add more privacy for Type

- editors/code/src/client.ts
- editors/code/src/config.ts
- editors/code/src/main.ts
> Don't try to enable proposed API's on stable

- docs/user/readme.adoc
> Add troubleshooting secion

- crates/ra_assists/src/handlers/add_missing_impl_members.rs
- crates/ra_ide/src/completion/complete_trait_impl.rs
- crates/ra_syntax/src/ast/edit.rs
> Align naming

- crates/ra_assists/src/assist_ctx.rs
- crates/ra_assists/src/ast_transform.rs
- crates/ra_assists/src/handlers/merge_imports.rs
- crates/ra_hir_expand/src/eager.rs
- crates/ra_ide/src/expand_macro.rs
- crates/ra_syntax/src/algo.rs
- crates/ra_syntax/src/ast/edit.rs
> Generalise syntax rewriting infrastructure to allow removal of nodes

- crates/ra_syntax/src/algo.rs
> Remove dead code

- editors/code/src/main.ts
> Use the right arch name for x86 (32 bit)

- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_ide/src/goto_definition.rs
> Always expand macros during analysis

- crates/ra_assists/src/handlers/change_visibility.rs
- crates/ra_assists/src/marks.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
> Fix couple of assists

- crates/ra_hir/src/code_model.rs
- crates/ra_hir_def/src/item_scope.rs
> Fix typo of visibility_of

- crates/ra_hir/src/db.rs
- crates/ra_hir_def/src/db.rs
- crates/ra_hir_ty/src/db.rs
- crates/ra_ide_db/src/change.rs
> Cleanup memory usage stats

- crates/ra_db/src/fixture.rs
- crates/ra_hir_def/src/nameres/tests/incremental.rs
> Minor incremental tests cleanup

- crates/ra_assists/src/handlers/add_explicit_type.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/nameres/raw.rs
- crates/ra_hir_expand/src/ast_id_map.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/ast/traits.rs
- xtask/src/ast_src.rs
> Get rid of ItemOrMacro

- .github/workflows/ci.yaml
It depends on openssl ;-(
bors r+
🤖
> Don't deny C for cargo audit

- crates/ra_assists/src/handlers/early_return.rs
- crates/ra_syntax/src/ast/make.rs
> More general ctor for ifs

- crates/ra_assists/src/doc_tests/generated.rs
- crates/ra_assists/src/handlers/replace_let_with_if_let.rs
- crates/ra_assists/src/lib.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/make.rs
- docs/user/assists.md
> Replace if with if-let

- crates/ra_assists/src/handlers/replace_let_with_if_let.rs
- docs/user/assists.md
> Fix assist description

- Cargo.lock
- crates/ra_assists/Cargo.toml
- crates/ra_assists/src/handlers/add_custom_impl.rs
- crates/ra_assists/src/handlers/add_impl.rs
- crates/ra_assists/src/handlers/add_new.rs
- crates/ra_assists/src/handlers/introduce_variable.rs
- crates/ra_hir_def/Cargo.toml
- crates/ra_hir_def/src/nameres.rs
- crates/ra_hir_ty/Cargo.toml
- crates/ra_hir_ty/src/diagnostics.rs
- crates/ra_hir_ty/src/test_db.rs
- crates/ra_hir_ty/src/tests.rs
- crates/ra_ide/Cargo.toml
- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/diagnostics.rs
- crates/ra_ide/src/display.rs
- crates/ra_ide/src/display/function_signature.rs
- crates/ra_ide/src/display/short_label.rs
- crates/ra_syntax/Cargo.toml
- crates/ra_syntax/src/ast/make.rs
- crates/ra_syntax/src/lib.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/world.rs
- crates/stdx/Cargo.toml
- crates/stdx/src/lib.rs
> Introduce stdx crate

- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/world.rs
> Move roots_to_scan to LoopState

- crates/ra_cargo_watch/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/world.rs
> Pull options outwards

- crates/ra_assists/src/handlers/fill_match_arms.rs
- crates/ra_syntax/src/ast/edit.rs
> Use IntoIter

- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/semantic_tokens.rs
This matches the next stable vscode api
> Simplify SemanticTokensBuilder build method

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/req.rs
- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/commands/runnables.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/status_display.ts
> New config names

- editors/code/package.json
> Fix semantic coloring

- editors/code/package-lock.json
- editors/code/package.json
Fixes a security vulnerability
> Bumps vsce to 1.75

- .github/workflows/ci.yaml
https://github.com/rust-analyzer/rust-analyzer/pull/3800#issuecomment-607186153
r=@matklad
> Remove deny_c in CI

- editors/code/package.json
> Set semantic tokens supertypes

- editors/code/.vscodeignore
> Include grammar for syntax trees into vsix

- Cargo.lock
- crates/ra_proc_macro_srv/Cargo.toml
> Remove unused dependencies

- crates/ra_hir_def/src/type_ref.rs
- crates/ra_hir_ty/src/tests/simple.rs
> Fix inference of function pointer return types

- .github/workflows/ci.yaml
https://github.com/rust-analyzer/rust-analyzer/commit/32770794128d45208a7a208e7b0d54912e584f20#commitcomment-38299575
cc @matklad
> Add back deny_c

- crates/ra_ide/src/ssr.rs
#3186 
maybe I've missed some corner cases, but it works in general
> Adds to SSR match for semantically equivalent call and method call

- crates/ra_hir_ty/src/traits.rs
> Use log::info in trait_solve_query instead of eprintln

- crates/rust-analyzer/src/config.rs
fixes #3871
Previously if `get::<Vec<String>>(value, "/checkOnSave/overrideCommand")` returned `Some` we'd never execute `set(value, "/checkOnSave/command", command)`, even if the `overrideCommand` was empty. 
I am not sure of the best way to prove this, but I believe the LSP clients send this config with a default value if it is not set by the user, which means `get::<Vec<String>>(value, "/checkOnSave/overrideCommand")` would return `Some(vec![])` and thus we'd never set the command to the user specified value (in the case of #3871, "clippy").
I have tested this fix manually by installing this modified version of rust-analyzer and verifying I can see clippy lints in my editor (`coc.nvim`) with `rust-analyzer.checkOnSave.command": "clippy"`.
As best I can tell this would have affected …
> fix cargo check config with custom command

- editors/code/package.json
> Better config scheme & defaults

- xtask/src/lib.rs
> When making a release, just promote the latest nightly

- crates/ra_ide/src/completion/complete_record.rs
- crates/ra_ide/src/completion/completion_context.rs
- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/marks.rs
> A more precise panic macro

- crates/ra_ide/src/completion/complete_record.rs
> Add functional update test

- crates/ra_syntax/src/algo.rs
> Fix warnings emitted when compiling as part of rustc

- crates/ra_assists/src/lib.rs
> Fix add missing items assist order

- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/ast/tokens.rs
- xtask/src/codegen/gen_syntax.rs
> Generate tokense

- crates/ra_assists/src/handlers/add_impl.rs
- crates/ra_assists/src/handlers/add_new.rs
- crates/ra_assists/src/handlers/introduce_variable.rs
- crates/ra_assists/src/handlers/merge_imports.rs
- crates/ra_fmt/src/lib.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/nameres/raw.rs
- crates/ra_hir_def/src/path/lower.rs
- crates/ra_hir_def/src/path/lower/lower_use.rs
- crates/ra_hir_def/src/visibility.rs
- crates/ra_hir_ty/src/tests.rs
- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/expr_extensions.rs
- crates/ra_syntax/src/ast/extensions.rs
- crates/ra_syntax/src/ast/generated.rs
- crates/ra_syntax/src/ast/traits.rs
- xtask/src/ast_src.rs
- xtask/src/codegen/gen_syntax.rs
> Genrate token accessors

- crates/ra_syntax/src/algo.rs
I haven't actually profiled this, but not allocating a hash map (or
anything, really) seems like a good idea
bors r+
🤖
> Remove allocations from LCA

- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/expr_extensions.rs
- crates/ra_syntax/src/ast/extensions.rs
- crates/ra_syntax/src/ast/traits.rs
> Remove code duplication

- crates/ra_hir_def/src/lang_item.rs
> profile queries

- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/diagnostics.rs
- crates/ra_hir_expand/src/ast_id_map.rs
- crates/ra_hir_ty/src/diagnostics.rs
- crates/ra_hir_ty/src/expr.rs
- crates/ra_hir_ty/src/tests.rs
- crates/ra_syntax/src/ptr.rs
> Forward compat

- crates/ra_hir_def/src/adt.rs
- crates/ra_hir_def/src/attr.rs
- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/data.rs
- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_def/src/nameres/tests/incremental.rs
> Cleanup cfg handling in items

- crates/ra_ide/src/call_info.rs
> Remove #[should_panic] from call_info tests

- crates/ra_assists/src/handlers/reorder_fields.rs
> Remove more unnecessary braces

- crates/ra_assists/src/doc_tests/generated.rs
- crates/ra_assists/src/handlers/add_function.rs
- docs/user/assists.md
- xtask/tests/tidy-tests/main.rs
> Change add_function assist to use todo!() instead of unimplemented!()

- Cargo.lock
- crates/ra_proc_macro_srv/Cargo.toml
- crates/ra_proc_macro_srv/src/dylib.rs
> Use mmap for proc macro libs

- crates/ra_ide/src/completion/complete_trait_impl.rs
> Better snippet when completing trait method

- crates/ra_hir/src/source_analyzer.rs
> Don't use SyntaxNodePtr::range when determining scope for offset

- crates/ra_ide/src/inlay_hints.rs
> Omit more parameter hints in the presence of underscores

- crates/ra_hir_ty/src/_match.rs
- crates/ra_hir_ty/src/test_db.rs
This PR implements match statement exhaustiveness checking for record type enums.
It also make a minor addition to the test infrastructure to allow testing against a single diagnostic, so you can be sure your test is triggering (or not) whichever diagnostic you expect.
> Match check enum record

- crates/ra_proc_macro/src/lib.rs
- crates/ra_proc_macro/src/msg.rs
- crates/ra_proc_macro/src/process.rs
- crates/ra_proc_macro/src/rpc.rs
- crates/ra_proc_macro_srv/src/cli.rs
- crates/ra_proc_macro_srv/src/dylib.rs
- crates/ra_proc_macro_srv/src/lib.rs
- crates/ra_proc_macro_srv/src/rustc_server.rs
- crates/ra_proc_macro_srv/src/tests/utils.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/world.rs
> ra_proc_macro: cleanups here and there

- docs/user/readme.adoc
cleanup unavailable configurations/commands
> docs(readme): improve user docs

- crates/rust-analyzer/src/bin/args.rs
> Cleanup args a bit

- editors/code/src/commands/syntax_tree.ts
> Work around crlf in syntax tree

- crates/rust-analyzer/src/config.rs
- editors/code/package.json
> Fix config naming

- crates/ra_proc_macro/src/process.rs
> proc_macro: add ability to log to stderr and view output in vscode

- crates/ra_hir_def/src/body/scope.rs
- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide_db/src/symbol_index.rs
> Remove SyntaxPtr::range from more places

- crates/ra_hir_ty/src/tests.rs
- crates/ra_syntax/src/ptr.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
> Fully get rid of SyntaxNodePtr::range

- crates/ra_ide/src/completion/completion_config.rs
- crates/rust-analyzer/src/config.rs
> Honor snippet capability

- Cargo.lock
> :arrow_up: crates (to bust the caches)

- crates/ra_ide/src/completion/complete_macro_in_item_position.rs
- crates/ra_ide/src/completion/complete_pattern.rs
- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/presentation.rs
> Better label for macros completion

- crates/ra_project_model/src/cargo_workspace.rs
> More helpful error message if toolchain is not in PATH

- crates/ra_project_model/src/cargo_workspace.rs
> Don't print cargo version to stdout, breaking everything

- crates/ra_hir/src/code_model.rs
- crates/ra_hir/src/from_id.rs
- crates/ra_hir/src/has_source.rs
- crates/ra_hir/src/lib.rs
- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/semantics/source_to_def.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_hir_def/src/adt.rs
- crates/ra_hir_def/src/attr.rs
- crates/ra_hir_def/src/child_by_source.rs
- crates/ra_hir_def/src/docs.rs
- crates/ra_hir_def/src/keys.rs
- crates/ra_hir_def/src/lib.rs
- crates/ra_hir_ty/src/db.rs
- crates/ra_hir_ty/src/expr.rs
- crates/ra_hir_ty/src/infer.rs
- crates/ra_hir_ty/src/infer/expr.rs
- crates/ra_hir_ty/src/infer/pat.rs
- crates/ra_hir_ty/src/lower.rs
- crates/ra_ide/src/completion/presentation.rs
- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/references.rs
- crates/ra_ide/src/references/rename.rs
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide_db/src/defs.rs
- crates/ra_ide_db/src/search.rs
> Rename StructField -> Field

- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/tests/heavy_tests/main.rs
> Add `cargo test` to the list of Run commands

- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/completion_context.rs
- crates/ra_ide/src/completion/presentation.rs
> Precompute expected type during completion

- crates/rust-analyzer/src/semantic_tokens.rs
> Make it impossible to forget to add a semantic token type / modifier

- Cargo.lock
- crates/ra_flycheck/Cargo.toml
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/conv.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/req.rs
- crates/rust-analyzer/tests/heavy_tests/main.rs
* Fixes a bunch of param types to take partial progress into account.
* Will allow us to support insert/replace text in completions
> lsp-types 0.74

- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/presentation.rs
> Better filtering of qualified enum variants in completion

- docs/user/readme.adoc
https://github.com/fannheyward/coc-rust-analyzer/issues/177#issuecomment-621109410
> docs(user): method chaining hints support

- xtask/src/lib.rs
- xtask/src/not_bash.rs
> Allow to set env vars and pipe stdin via not_bash

- crates/ra_fmt/src/lib.rs
- crates/ra_ide/src/join_lines.rs
- crates/ra_syntax/src/ast/expr_extensions.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/ast_src.rs
> Fix a bunch of false-positives in join-lines

- docs/dev/syntax.md
Eric Lippert has a new blog that he keeps updating, update the link to that
> Update Roslyn link in syntax.md

- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/expr.rs
- crates/ra_hir_ty/src/infer/expr.rs
- crates/ra_parser/src/grammar/expressions/atom.rs
- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/expr_extensions.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/ast_src.rs
> Remove dead TryBlock expressio

- crates/ra_syntax/src/ast/extensions.rs
Clippy complained about it and it seems wrong, copy paste error?
> Fix pub(self) visibility?

- docs/user/readme.adoc
> Document Gnome Builder support

- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/expr.rs
- crates/ra_hir_ty/src/infer/expr.rs
- crates/ra_parser/src/grammar/expressions/atom.rs
- crates/ra_parser/src/syntax_kind/generated.rs
- crates/ra_syntax/src/ast.rs
- crates/ra_syntax/src/ast/expr_extensions.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/ast_src.rs
> Put ? back in place

- crates/ra_hir_def/src/adt.rs
- crates/ra_hir_ty/src/tests.rs
> add support of cfg attributes on enum variants

- crates/ra_ide/src/marks.rs
- crates/ra_ide/src/references/rename.rs
> Add test marks

- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide/src/goto_definition.rs
> Fix focus range for TypeParam

- crates/ra_flycheck/Cargo.toml
- crates/ra_ide/src/display/navigation_target.rs
- crates/ra_ide/src/goto_definition.rs
> no doctests for flycheck

- crates/ra_hir_def/src/data.rs
- crates/ra_hir_ty/src/tests/traits.rs
> Support macro for trait items

- editors/code/package.json
> Specify cotributed semanticTokenTypes in package.json

- crates/ra_ide/src/completion.rs
- crates/ra_ide/src/completion/complete_attribute.rs
> Cleanup attribute completion

- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/completion/complete_unqualified_path.rs
> Remove false positive attr compleitons

- crates/ra_hir_def/src/adt.rs
- crates/ra_hir_def/src/body.rs
- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/data.rs
As promised @edwin0cheng here is the PR to resolve the comment [here](https://github.com/rust-analyzer/rust-analyzer/pull/4285#discussion_r419200375).
> refactor: use attrsOwner directly in is_cfg_enabled

- crates/ra_assists/src/handlers/change_visibility.rs
> Make `change_visibility` assist work for tuple struct fields

- crates/ra_hir_def/src/body/lower.rs
- crates/ra_hir_def/src/item_scope.rs
- crates/ra_hir_def/src/nameres/collector.rs
- crates/ra_hir_def/src/nameres/raw.rs
- crates/ra_hir_def/src/nameres/tests.rs
- crates/ra_hir_def/src/nameres/tests/macros.rs
- crates/ra_hir_ty/src/tests/regression.rs
> Favor types for record type struct in name resolution

- crates/ra_assists/src/handlers/add_missing_impl_members.rs
- crates/ra_assists/src/handlers/add_new.rs
- crates/ra_assists/src/utils.rs
- crates/ra_hir/src/code_model.rs
- crates/ra_hir_def/src/data.rs
- crates/ra_hir_ty/src/tests/macros.rs
- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/completion/complete_trait_impl.rs
- crates/ra_mbe/src/syntax_bridge.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/generated/nodes.rs
- xtask/src/ast_src.rs
Related discussion: https://github.com/rust-analyzer/rust-analyzer/pull/4283#discussion_r419352265
> Rename ImplItem to AssocItem

- crates/rust-analyzer/src/main_loop.rs
> Add tests for #4306

- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/world.rs
- editors/code/package.json
> Defining a default target to support cross-compilation targets 

- crates/ra_ide_db/src/line_index.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/pull/4276#issuecomment-623079855.
> Fix column conversion for supplementary plane characters

- crates/ra_assists/src/assist_ctx.rs
- crates/ra_assists/src/lib.rs
- crates/ra_ide/src/assists.rs
- crates/ra_ide/src/diagnostics.rs
- crates/ra_ide/src/references/rename.rs
- crates/ra_ide/src/source_change.rs
- crates/ra_ide/src/typing/on_enter.rs
- crates/rust-analyzer/tests/heavy_tests/main.rs
> Refactor assists

- crates/ra_flycheck/src/lib.rs
- crates/rust-analyzer/src/config.rs
- editors/code/package.json
> add the allFeatures flag (true by default)

- crates/ra_ide/src/lib.rs
> Fix capitalization

- crates/ra_ide/src/lib.rs
- crates/ra_ide/src/ssr.rs
- crates/ra_ide/src/typing.rs
- crates/ra_ide_db/src/lib.rs
- crates/ra_ide_db/src/source_change.rs
- crates/ra_text_edit/src/lib.rs
> Lift SourceChange to the ra_ide_db

- crates/ra_assists/src/assist_ctx.rs
- crates/ra_assists/src/handlers/add_function.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/tests.rs
- crates/ra_ide/src/completion/completion_item.rs
- crates/ra_ide/src/lib.rs
> Refactor assists a bit

- crates/ra_assists/src/handlers/change_return_type_to_result.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/tests/generated.rs
- docs/user/assists.md
About issue #3907 
close #3907
> add Ok wrapping assist #3907

- docs/user/readme.adoc
> Fix Windows server path

- editors/code/package.json
https://github.com/microsoft/vscode/issues/94367#issuecomment-608629883
bors r+
🤖
> Better mapping to TextMate scopes for keywords

- crates/ra_ide/src/display/function_signature.rs
> Fix panic in FunctionSignature

- crates/ra_assists/src/assist_context.rs
- crates/ra_assists/src/handlers/early_return.rs
- crates/ra_assists/src/handlers/merge_imports.rs
- crates/ra_assists/src/handlers/merge_match_arms.rs
- crates/ra_assists/src/handlers/split_import.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/tests.rs
- crates/ra_ide/src/lib.rs
> Touch up assists public API

- editors/code/package.json
This works around https://github.com/microsoft/vscode/issues/97162
bors r+
🤖
> Use the correct color for structs

- crates/rust-analyzer/src/main_loop/handlers.rs
> do not show runnables for main function outside of a binary target 

- crates/ra_cfg/src/lib.rs
- crates/ra_project_model/src/lib.rs
> Move feature desugaring to the right abstraction layer

- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/inlay_hints.ts
> Add master config for inlayHints to make disabling easy

- Cargo.lock
- crates/ra_flycheck/Cargo.toml
- crates/ra_flycheck/src/lib.rs
- crates/ra_project_model/Cargo.toml
- crates/ra_project_model/src/cargo_workspace.rs
- crates/ra_project_model/src/lib.rs
- crates/ra_project_model/src/sysroot.rs
- crates/ra_toolchain/Cargo.toml
- crates/ra_toolchain/src/lib.rs
> Cleanup toolchain handling

- crates/ra_project_model/src/lib.rs
> Add stderr to error message

- crates/ra_assists/src/assist_context.rs
- crates/ra_assists/src/handlers/add_function.rs
- crates/ra_assists/src/handlers/add_missing_impl_members.rs
- crates/ra_assists/src/handlers/early_return.rs
- crates/ra_assists/src/handlers/replace_if_let_with_match.rs
- crates/ra_assists/src/handlers/replace_let_with_if_let.rs
- crates/ra_assists/src/handlers/replace_unwrap_with_match.rs
- crates/ra_syntax/src/ast/edit.rs
> More fluent indent API

- crates/ra_assists/src/handlers/early_return.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/test_utils/src/lib.rs
> unindent -> dedent

- crates/ra_assists/src/handlers/add_explicit_type.rs
> Ascribe more correct types

- crates/ra_assists/src/handlers/add_from_impl_for_enum.rs
> Add From should not move the cursor

- crates/ra_ide/src/display/function_signature.rs
I am totally agree this comment: 
https://github.com/rust-analyzer/rust-analyzer/blob/f1cb5b8a29ce509bf1f8d6df97d4b6586b9a2dac/crates/ra_ide/src/display/function_signature.rs#L3-L4
But let hot fix all panic for right now, it is so disturbing when browsing code...
> Hot fix panic for function_signature

- crates/ra_assists/src/handlers/add_explicit_type.rs
- crates/ra_hir_ty/src/display.rs
- crates/ra_hir_ty/src/tests/display_source_code.rs
> Omit default types in HirDisplay SourceCode mode

- crates/ra_assists/src/handlers/unwrap_block.rs
> do not remove then block when you unwrap else block #4361

- crates/ra_syntax/src/ast/make.rs
> Improve panic message for ast_from_text

- crates/ra_ide/src/completion/complete_snippet.rs
Request from a friend coming from intellij Rust
> add tests module snippet

- .github/workflows/release.yaml
> Use older ubuntu for releases

- crates/ra_ide/src/completion/complete_postfix.rs
In order to have the same behavior than `if let` and `while let`
> add more specific match postfix for Result and Option

- crates/rust-analyzer/src/main_loop/handlers.rs
> Remove VARIATION SELECTOR-16 in Run arrow

- crates/ra_ide/src/completion/completion_context.rs
- crates/ra_ide/src/completion/presentation.rs
> Prioritize locals with correct types

- crates/ra_hir_expand/src/db.rs
- crates/ra_mbe/src/lib.rs
- crates/ra_tt/src/lib.rs
> Store proc-macro result in salsa db

- crates/ra_ide/src/references/rename.rs
This is a first stab at #3439
I liked the idea to do this as a rename instead of separate assist, so I tried implementing that.
It mostly works, but I'm sure there are some cases that I missed, especially in regards to parameter type.
Note: I'm playing with this this as a way to learn Rust and this project. So I'm sure it could be cleaner and put in better places`. Any suggestions?
> Add rename self to parameter and back.

- crates/ra_hir/src/semantics.rs
- crates/ra_hir/src/source_analyzer.rs
- crates/ra_ide/src/completion/complete_qualified_path.rs
- crates/ra_ide/src/hover.rs
This fixes #3970 and also fixes completion for the same issue.
> Fix path resolution for module and function with same name

- docs/user/readme.adoc
- editors/code/package.json
> Relax VS Code version requirement

- crates/ra_hir_def/src/db.rs
- crates/ra_hir_def/src/find_path.rs
This brings the time needed to compute the `add_missing_impl_members` assist down from ~5 minutes to 20 seconds on my test workload (which is editing within an impl of a MIR [`MutVisitor`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/visit/trait.MutVisitor.html))
cc #4498
> Querify `importable_locations_in_crate`

- crates/ra_hir_def/src/db.rs
- crates/ra_hir_def/src/find_path.rs
> find_path cleanups

- crates/ra_ide/src/runnables.rs
> fix doctest inside impl block

- crates/ra_assists/src/handlers/add_turbo_fish.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/marks.rs
- crates/ra_assists/src/tests/generated.rs
- docs/user/assists.md
- xtask/tests/tidy.rs
> New assist: add turbo fish

- editors/code/src/commands/index.ts
> Fix client-side snippets

- crates/ra_assists/src/handlers/add_explicit_type.rs
- crates/ra_assists/src/handlers/add_from_impl_for_enum.rs
- crates/ra_assists/src/handlers/add_function.rs
- crates/ra_assists/src/tests/generated.rs
- crates/ra_assists/src/utils.rs
- crates/ra_syntax/src/algo.rs
- crates/ra_syntax/src/ast/edit.rs
- crates/ra_syntax/src/ast/make.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/stdx/src/lib.rs
- docs/user/assists.md
> Use snippets in add_function

- crates/ra_assists/src/handlers/replace_unwrap_with_match.rs
- crates/ra_syntax/src/ast/make.rs
> Explain the purpose of `ast::make` module more clearly

- crates/ra_assists/src/assist_context.rs
- crates/ra_assists/src/handlers/add_function.rs
- crates/ra_assists/src/handlers/add_missing_impl_members.rs
- crates/ra_assists/src/tests/generated.rs
- crates/ra_assists/src/utils.rs
- docs/user/assists.md
> Use snippets in add_missing_members

- crates/ra_assists/src/handlers/add_missing_impl_members.rs
- crates/ra_assists/src/tests/generated.rs
- docs/user/assists.md
> Better cursor placement when adding impl members

- editors/code/src/cargo.ts
Fixes an issue reported here: https://github.com/rust-analyzer/rust-analyzer/pull/4222#issuecomment-631073448
> Debug lens fix for a binary.

- crates/ra_assists/src/handlers/fill_match_arms.rs
- crates/ra_assists/src/marks.rs
- crates/ra_assists/src/utils.rs
> Fix Some|None order in fill_match_arms

- crates/ra_assists/src/handlers/add_new.rs
- crates/ra_assists/src/handlers/auto_import.rs
- crates/ra_assists/src/handlers/change_return_type_to_result.rs
- crates/ra_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ra_assists/src/tests/generated.rs
- crates/ra_assists/src/utils/insert_use.rs
- docs/user/assists.md
> Use snippets in change_return_type_to_result

- crates/ra_assists/src/handlers/change_visibility.rs
- crates/ra_assists/src/handlers/fill_match_arms.rs
- crates/ra_assists/src/handlers/fix_visibility.rs
- crates/ra_assists/src/handlers/unwrap_block.rs
- crates/ra_assists/src/tests/generated.rs
- docs/user/assists.md
> More snippets

- crates/ra_assists/src/handlers/add_explicit_type.rs
- crates/ra_assists/src/handlers/add_from_impl_for_enum.rs
- crates/ra_assists/src/handlers/apply_demorgan.rs
- crates/ra_assists/src/handlers/auto_import.rs
- crates/ra_assists/src/handlers/change_visibility.rs
- crates/ra_assists/src/handlers/flip_binexpr.rs
- crates/ra_assists/src/handlers/flip_comma.rs
- crates/ra_assists/src/handlers/flip_trait_bound.rs
- crates/ra_assists/src/handlers/invert_if.rs
- crates/ra_assists/src/handlers/move_bounds.rs
- crates/ra_assists/src/handlers/raw_string.rs
- crates/ra_assists/src/handlers/reorder_fields.rs
- crates/ra_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ra_assists/src/tests.rs
Those will be replaced with snippets anyway
bors r+
🤖
> Relax cursor position tests in assists

- crates/ra_assists/src/assist_context.rs
- crates/ra_assists/src/handlers/replace_if_let_with_match.rs
- crates/ra_assists/src/handlers/replace_let_with_if_let.rs
- crates/ra_assists/src/handlers/replace_unwrap_with_match.rs
- crates/ra_assists/src/handlers/split_import.rs
- crates/ra_assists/src/handlers/unwrap_block.rs
- crates/ra_assists/src/tests/generated.rs
- docs/user/assists.md
> Remove set_cursor

- crates/ra_ide/src/typing.rs
> Remove unused cursor positions

- editors/code/package.json
Part of #4549
r? @LucianoBestia
> Fix phrasing in inlay hints settings

- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- docs/dev/lsp-extensions.md
- editors/code/src/commands/ssr.ts
- editors/code/src/rust-analyzer-api.ts
> Use WorkspaceEdit for ssr

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/snapshots/rust_analyzer__diagnostics__to_proto__tests__snap_multi_line_fix.snap
- crates/rust-analyzer/src/diagnostics/snapshots/rust_analyzer__diagnostics__to_proto__tests__snap_rustc_unused_variable.snap
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- editors/code/src/client.ts
- editors/code/src/commands/index.ts
- editors/code/src/main.ts
> CodeAction groups

- docs/dev/lsp-extensions.md
> Link upstream issues

- editors/code/src/main.ts
This adds Nix support, and fixes #4542
> VSCode: added patchelf after download for NixOS support

- .github/workflows/ci.yaml
- .vscode/launch.json
- .vscode/tasks.json
- editors/code/.vscodeignore
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/rollup.config.js
- editors/code/src/cargo.ts
- editors/code/tests/runTests.ts
- editors/code/tests/unit/index.ts
- editors/code/tests/unit/launch_config.test.ts
- editors/code/tsconfig.json
vscode tests as discussed in [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/vscode.20integration.20tests/near/198170032)
It remains only to add `npm test` to https://github.com/rust-analyzer/rust-analyzer/blob/3dfc461f1e44ee7cebee672cac02d56ba5523f67/.github/workflows/ci.yaml#L116-L120
Do not want to modify CI files myself.
A draft because I want to check how draft pull requests work :) Does bors check them or not?
> vscode client side tests

- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- docs/dev/lsp-extensions.md
- editors/code/src/commands/matching_brace.ts
- editors/code/src/rust-analyzer-api.ts
> Document some rust-analyzer specific protocol extensions

- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
> Document `parentModule` experimental LSP request

- editors/code/package.json
> Add boolean literal semantic token type to package.json

- .github/actions/github-release/main.js
- .github/workflows/release.yaml
> Try fixing release tags

- editors/code/rust.tmGrammar.json
> Highlight question mark operator

- crates/ra_ide/src/completion/complete_attribute.rs
> Fix the `should_panic` snippet

- crates/ra_hir/src/code_model.rs
- crates/ra_ide/src/completion/complete_unqualified_path.rs
- crates/ra_ide/src/completion/completion_context.rs
> fix textedit range returned for completion when left token is a keyword

- README.md
- docs/user/readme.adoc
> Link forum topic

- docs/dev/lsp-extensions.md
> Fix typo in docs/dev/lsp-extensions.md: automagiacally -> automagically

- crates/ra_assists/src/handlers/change_lifetime_anon_to_named.rs
- crates/ra_assists/src/lib.rs
- crates/ra_assists/src/tests/generated.rs
- docs/user/assists.md
> Assist: replace anonymous lifetime with a named one

- docs/user/generated_assists.adoc
- docs/user/manual.adoc
- xtask/src/codegen.rs
- xtask/src/codegen/gen_assists_docs.rs
- xtask/src/codegen/gen_feature_docs.rs
- xtask/src/lib.rs
> Move assists documentation into the manual

- docs/user/generated_assists.adoc
- docs/user/generated_features.adoc
- xtask/src/codegen.rs
- xtask/src/codegen/gen_assists_docs.rs
- xtask/src/codegen/gen_feature_docs.rs
> Link docs and code

- editors/code/src/commands.ts
- editors/code/src/debug.ts
- editors/code/src/run.ts
> Move run commands to commands.ts

- crates/ra_hir/src/code_model.rs
- crates/ra_hir_def/src/data.rs
- crates/ra_ide/src/snapshots/highlight_strings.html
- crates/ra_ide/src/snapshots/highlight_unsafe.html
- crates/ra_ide/src/snapshots/highlighting.html
- crates/ra_ide/src/snapshots/rainbow_highlighting.html
- crates/ra_ide/src/syntax_highlighting.rs
- crates/ra_ide/src/syntax_highlighting/html.rs
- crates/ra_ide/src/syntax_highlighting/tags.rs
- crates/ra_ide/src/syntax_highlighting/tests.rs
Addresses ide highlighting for #190
> Add highlight support for unsafe fn calls and raw ptr deref

- crates/ra_project_model/src/json_project.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/world.rs
- crates/rust-analyzer/tests/heavy_tests/main.rs
> Derive local roots from Workspaces

- crates/rust-analyzer/src/cargo_target_spec.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Rename WorldState -> GlobalState

- crates/ra_project_model/src/lib.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/tests/heavy_tests/support.rs
> Groundwork for specifying the set of projects via config

- crates/rust-analyzer/tests/heavy_tests/main.rs
> Drop test for old format

- crates/ra_project_model/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/user/manual.adoc
- editors/code/package.json
> Document rust-project.json

- crates/ra_assists/src/handlers/introduce_named_lifetime.rs
followed anonymous lifetime token
(fixes #4684)
> introduce_named_lifetime assist wasn't applicable when type parameter

- crates/ra_ide/src/inlay_hints.rs
> Inlay Hints: more directly account for self param

- crates/ra_db/src/lib.rs
- crates/ra_hir_def/src/nameres/mod_resolution.rs
- crates/ra_hir_def/src/test_db.rs
- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_hir_expand/src/test_db.rs
- crates/ra_hir_ty/src/test_db.rs
- crates/ra_ide_db/src/lib.rs
- crates/rust-analyzer/tests/heavy_tests/main.rs
> Cleanup resolution of file paths

- crates/rust-analyzer/tests/heavy_tests/main.rs
It triggered index-based goto definition before :-(
bors r+
🤖
> Actually test include!(concant!(env!()));

- crates/ra_db/src/lib.rs
- crates/ra_hir_def/src/test_db.rs
- crates/ra_hir_expand/src/builtin_macro.rs
- crates/ra_hir_expand/src/test_db.rs
- crates/ra_hir_ty/src/test_db.rs
- crates/ra_ide_db/src/lib.rs
> Minimize FileLoader interface

- docs/dev/README.md
> Document certain invariants

- crates/ra_ide/src/syntax_highlighting/tests.rs
Follow up from #4683. Improves syntax highlighting testing by introducing a function that contains the boilerplate comparison code. Keeps the `ra_fixture` argument in the first position, thus, the editor syntax highlighting injection still works.
> Remove redundancy in syntax highlighting tests

- docs/dev/README.md
> Document more knowledge

- docs/dev/README.md
> Don't @ people in commit messages

- crates/ra_ide/src/hover.rs
- crates/ra_ide/src/runnables.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
- editors/code/package.json
This hover actions work exactly like corresponding lenses.
> Run|Debug hover actions.
