rust-lang/rust-analyzer

- crates/base_db/src/input.rs
- crates/ide/src/lib.rs
- crates/ide/src/prime_caches.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/thread_pool.rs
It now computes the `CrateDefMap` of all crates, which is generally a reasonable approximation for "IDE features ready". There is still some delay after this finishes, I suspect mostly due to impl collection, which takes a while, but this should be an improvement already.
For more accurate progress reports, this topologically sorts all crates before starting this operation. ~~Because that is also the ordering in which parallelization makes sense (which was previously attempted in https://github.com/rust-analyzer/rust-analyzer/pull/3529), I decided to throw that into the mix as well. It still doesn't provide *that* much of a performance boost, but it does scale beyond the current single-core architecture, and adding it was very easy.~~
~~Unfortunately, as written, this will not tell the …
> Improve prime_caches and display its progress

- editors/code/rust.tmGrammar.json
Thanks to everyone working hard on Rust Analyzer - my impression is that it's quickly becoming the community default.
I think it would be helpful to have a more robust TextMate grammar to fall back on, for those who wish to disable semantic highlighting for any reason. It should allow theming of punctuation, and provide scopes for all tokens on the page. This can be done at zero cost to those who enable semantic highlighting, as the TextMate scopes will be invisible to those users.
I can see a couple ways of accomplishing this:
1. Ship a new grammar by merging this PR.
1. Ship no TextMate grammar at all (like the [Rust](https://marketplace.visualstudio.com/items?itemName=rust-lang.rust) extension), and allow users to install a separate extension that provides the grammar of their choice …
> add a new TextMate grammar

- crates/ide/src/inlay_hints.rs
Turns out I made a mistake with the heuristic check which is always true, so all iterators exposed from `core` were shortened, including things like ranges. 😅
> Fix iterator hint shortening heuristic

- crates/assists/src/handlers/generate_function.rs
- crates/assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
I made a little change when we use the assist to generate a new function, instead of focusing on the function body, it will focus on return type
> when generating new function, focus on return type instead of body

- crates/assists/src/handlers/merge_imports.rs
- crates/assists/src/handlers/replace_qualified_name_with_use.rs
- crates/assists/src/utils/insert_use.rs
Fixes #6221.
#6108 shouldn't be related to this as autocompletion doesn't depend on this code.
> Fix stackoverflow in insert_use::recursive_merge

- docs/dev/lsp-extensions.md
- xtask/tests/tidy.rs
> Add reminder to update lsp-extensions.md

- crates/assists/src/handlers/auto_import.rs
- crates/assists/src/utils.rs
- crates/assists/src/utils/import_assets.rs
See https://github.com/rust-analyzer/rust-analyzer/pull/6172#issuecomment-707182140
I couldn't fully pull out `AssistContext` as `find_node_at_offset_with_descend`: https://github.com/rust-analyzer/rust-analyzer/blob/81fa00c5b5d5ffb559a39c7ff5190a2519a8ea61/crates/assists/src/assist_context.rs#L90-L92 requires the `SourceFile` which is private in it and I don't think making it public just for this is the right call?
> Extract ImportAssets out of auto_import

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/format.rs
- crates/ide/src/syntax_highlighting/macro_rules.rs
This moves `format`-like macro string highlighting and macro_rules highlight skipping out of the main module.
> Factor macro_rules and format-string highlighting out into submodules

- editors/code/src/inlay_hints.ts
to prevent the editor from displaying a ligature there. 
Fixes #6235
> Code: Insert a ZWNJ before `after` type hints

- crates/ide/src/hover.rs
Instead of the information about the field, it now shows the information
about the local.
Fixes #6146
> Fix hover over field pattern shorthand

- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/simple.rs
Extend type inference of *binary operator expression*, by adding support for operator overloads.
Before this merge request, the type inference of binary expressions could only resolve operations done on built-in primitive types. This merge requests adds a code path, which is executed in case the built-in inference could not get any results. It resolves the proper operator overload trait in *core::ops* via lang items, and then resolves the associated *Output* type.
```rust
struct V2([f32; 2]);
#[lang = "add"]
pub trait Add<Rhs = Self> {
/// The resulting type after applying the `+` operator.
type Output;
/// Performs the `+` operation.
#[must_use]
fn add(self, rhs: Rhs) -> Self::Output;
}
impl Add<V2> for V2 {
type Output = V2;
fn add(self, rhs: V2) -> V2 {
let x = self.0[0] + rhs.0[0]; …
```
> implement binary operator overloading type inference

- crates/vfs-notify/src/lib.rs
Fixes #3691.
~~WIP pending further testing~~:
> Follow symlinks when walking project trees

- crates/ide/src/completion.rs
- crates/ide/src/completion/completion_context.rs
- crates/ide/src/completion/patterns.rs
- crates/ide/src/completion/test_utils.rs
Closes #5206
This is a second part of the fix (first was #5997).
This PR adds a new method to the `CompletionContext`: `no_completion_required`. If this method returns `true`, it essentially means that user is unlikely to expect any hints from the IDE at this cursor position.
Currently, checks for the following cases were added:
- Previous item is `fn`: user creates a new function, names of existing functions won't be helpful. Exception for this case is `impl Foo for Bar` -- we must suggest trait function names.
- User entered `for _ i<|>`: it's obviously going to be `in` keyword, any hints here will be confusing.
More checks may be added there later, but currently I've only figured two cases.
> Do not spawn redundant hints

- editors/code/rust.tmGrammar.json
Problematic sample code from #6042:
```rust
#[derive(Debug, Clone, Logos)]
enum Quoted<'source> {
#[regex(r#"[^\\"']+"#)]
Text(&'source str),
#[token("\\")]
StartEscape,
#[token("\'", |_| Quote::Single)]
#[token("\"", |_| Quote::Double)]
End(Quote),
#[error]
Error,
}
```
Before fix:
After fix:
> Textmate grammar: prevent early termination of raw strings with hash (closes #6042)

- editors/code/rust.tmGrammar.json
Fixes the issues noted by @matklad after merging #6248. 
1. prevent accidental interpolation scopes when `{` is used in a string
1. prevent interpolations from extending beyond the end of a string
> Textmate grammar: prevent unwanted interpolation scopes

- crates/hir/src/diagnostics.rs
- crates/hir_def/src/diagnostics.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/field_shorthand.rs
- crates/rust-analyzer/src/handlers.rs
This emits a hint-level diagnostic with `Unnecessary` tag to "gray out" any items whose `#[cfg]` attributes remove the item before name resolution.
> Diagnose items that are #[cfg]d out

- crates/assists/src/handlers/auto_import.rs
- crates/assists/src/handlers/qualify_path.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
- crates/assists/src/utils/import_assets.rs
- crates/syntax/src/ast/make.rs
This implements a `qualify_path` assist which works quite similar to the `auto_import` assist but instead of adding imports to the file it well, qualifies the path. This PR also moves out the `AutoImportAssets` struct and functions from `auto_import` into a utils submodule as most of this is now shared between `auto_import` and `qualify_path`.
Changes made to `AutoImportAssets` are solely in its `search_for_imports` function which now takes a prefixed parameter to discern between using `find_use_path_prefixed` and `find_use_path` as the former is the required behavior by `auto_import` and the latter by this assist.
For missing imported traits instead of importing this will qualify the path with a trait cast as in:
```rust
test_mod::TestStruct::TEST_CONST<|>
```
becomes
```rust …
```
> Add qualify path assist

- crates/assists/src/handlers/replace_string_with_char.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
> Assist: replace string with char

- editors/code/rust.tmGrammar.json
1. Fixes the raw string highlighting issue noted by @matklad in https://github.com/rust-analyzer/rust-analyzer/pull/6275.
2. Improves raw string highlighting by requiring the number of surrounding `#` to match.
> Textmate grammar: fix raw string highlighting

- crates/ide/src/doc_links.rs
The whole path/URL joining code is kind of ugly which is what led to
this, but at the same time I don't really want to rewrite it right
now...
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6286
> Fix opening module documentation opening parent documentation instead

- editors/code/rust.tmGrammar.json
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6281.
Previously, line comments were able to break block comments by essentially commenting out the closing `*/`, resulting in a never-ending comment. This PR splits block comments into a separate repository group to fix this problem.
Since the comment scopes also include ignored parameters and inferred types, I've added the change proposed by @bnjjj in https://github.com/rust-analyzer/rust-analyzer/pull/6317, in order to close https://github.com/rust-analyzer/rust-analyzer/issues/6311 as well.
> Textmate grammar: prevent line comments from breaking block comments (closes #6281)

- crates/hir_ty/src/diagnostics/decl_check.rs
- crates/hir_ty/src/diagnostics/decl_check/case_conv.rs
> Properly identify camel cased acronyms as UpperCamelCase

- docs/user/manual.adoc
It seemed that we're not actually including the generated diagnostic docs anywhere yet? So I added something to the manual. This is completely untested though.
> Add generated diagnostic docs to the manual

- crates/completion/src/completion_context.rs
- crates/completion/src/completion_item.rs
- crates/completion/src/presentation.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
Follow up to https://github.com/rust-analyzer/rust-analyzer/pull/5846. When we have a local in scope which needs a ref or mutable ref to match the name and type of the active in the completion context then a new completion item with `&` or `&mut ` is inserted. E.g.
```rust
fn foo(arg: &i32){};
fn main() {
let arg = 1_i32;
foo(a<|>)
}
```
now offers `&arg` as a completion option with the highest score.
> Insert ref for completions

- crates/completion/src/presentation.rs
> Complete variants when only enun name is typed

- crates/hir_ty/src/traits.rs
- add panic context for the trait goal if CHALK_DEBUG is set
- print the Chalk program even if we're panicking
- log goal/solution while TLS is still set
> Improve Chalk debugging

- crates/hir/src/code_model.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/diagnostics.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/diagnostics.rs
- crates/hir_def/src/nameres/tests/diagnostics.rs
- crates/hir_def/src/test_db.rs
- docs/user/generated_diagnostic.adoc
This PR threads diagnostics through body lowering using the `BodySourceMap`, and emits `InactiveCode` diagnostics for expressions, statements, and match arms that are `#[cfg]`d out.
> Diagnose #[cfg]s in bodies

- Cargo.lock
- crates/ide/Cargo.toml
- crates/ide/src/diagnostics.rs
- crates/syntax/Cargo.toml
- crates/syntax/src/algo.rs
This in turn also makes `algo::diff` generate finer diffs(maybe even minimal diffs?) as insertions and deletions aren't always represented as as replacements of parent nodes now.
Required for #6287 to go on.
> Rewrite algo::diff to support insertion and deletion

- crates/hir/src/code_model.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
- editors/code/package.json
This PR added the `HighlightModifier::Callable` variant and assigned it to variables and parameters that are fn pointers, closures and implements FnOnce trait.
This allows to colorize these variables/parameters when used in call expression.
> Semantic Highlight: Add Callable modifier for variables

- editors/code/rust.tmGrammar.json
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6293.
I've included the possibility of the `r#` prefix in:
- function definitions
- function/method calls
- variables/parameters
This way the raw ID will simply get whatever the intended scope was, instead of a unique scope that might be inappropriately themed for its purpose.
Will wait a bit for feedback, in case there are other places you might use raw IDs.
> Textmate grammar: raw IDs, underscore fixes (closes #6293, #6340)

- crates/ide/src/hover.rs
- crates/syntax/src/ast/node_ext.rs
Fixes #6300 by improving the handling of raw string literals in attribute style doc comments.
This still has a bug where it could consume too many `"` at the start or end of the comment text, just as the original code had. Not sure if we want to fix that as part of this PR or not? If so, I think I'd prefer to add a unit test for either the `as_simple_key_value` function (I'm not exactly sure where this would belong / how to set this up) or create a `fn(&SmolStr) -> &SmolStr` to unit test by factoring out the `trim` operations from `as_simple_key_value`. Thoughts on this?
> correct hover text for items with doc attribute with raw strings

- crates/assists/src/handlers/remove_dbg.rs
Fixes #6355
~~This causes remove-dbg to not keep parentheses when it comes to ranges though due to ranges not having `DOT2` and `DOT2EQ` tokens but having two `DOT` tokens inside of macro invocations.~~
> Don't keep parens around with remove-dbg

- editors/code/rust.tmGrammar.json
Fixes #6323 
After tinkering, it became clear that `<` and `>` should really default to the punctuation interpretation in the vast majority of cases. In addition, the breakage is greater when an angle bracket is missed. So, rather than optimizing for a type parameter `meta` scope and considering every possible parent scope and child scope, the easier fix was to narrow the case where `<` and `>` are treated as comparison operators.
> Textmate grammar: angle bracket fix (closes #6323)

- crates/hir_ty/src/diagnostics/decl_check/case_conv.rs
This closes #6343 and closes #6345.
The old algorithm which used a `DetectedCase` enum, didn't match how rustc thinks of cases. Some inputs can be interpreted as more than 1 case depending on the situation. For example, to rustc:
- `ABCD`: Can be both camel case and upper snake case
- `X86_64`: Can be both camel case and upper snake case
I could've made `detect_case` return a collection of `DetectedCase` and then modified the other code as such, but I think using the same code rustc uses is simpler and a surefire way to achieve the same diagnostics as rustc.
> Make IncorrectDiagnostic match rustc by copying rustc's code.

- crates/assists/src/handlers/move_guard.rs
- crates/parser/src/grammar.rs
- crates/syntax/test_data/parser/inline/ok/0153_pub_parens_typepath.rast
- crates/syntax/test_data/parser/inline/ok/0153_pub_parens_typepath.rs
This closes #5902.
I only check that the next token isn't equal to `T![:]`, instead of the next two not being equal to `T![::]`. Is that ok?
> Don't interpret type path as part of visibility.

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests.rs
Now we correctly skip analysis of winapi on non-Windows platforms.
> Handle #![cfg] in crate root

- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
> Don't suggest extracting out 1-tuple enum variants

- crates/hir/src/code_model.rs
- crates/hir_ty/src/method_resolution.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
This PR should fix #6375 
This adds a variation of `method_resolution::implements_trait` called `method_resolution::implements_trait_unique`, that only returns true when the trait solving is unique, and also change `impls_fnonce` to use the later instead.
I also added a test just to be sure.
> Avoid impls_fnonce to return true when the trait solving is ambiguous 

- crates/ide/src/runnables.rs
I will check for how to do the same on trait implementation on another PR.
#6356
> add doctest runnables on struct

- editors/code/src/inlay_hints.ts
This makes things a lot more readable but isn't officially supported by vscode: https://github.com/Microsoft/vscode/issues/9078
Inspired by Visual Studio, IntelliJ and Resharper.
> Smaller inlay hints

- crates/hir_ty/src/display.rs
Linked to bug discovery from #6387
The main goal is to not use `display()` method inside `hir_fmt` to not override any parameters (like `DisplayTarget`). 
cc @flodiebold
> refactor(hir_ty): do not override DisplayTarget in hir_fmt

- docs/user/manual.adoc
`nvim-lsp` updated their repository to `nvim-lspconfig` to lessen confusion about what it does.
> docs: Update Neovim nvim-lspconfig repository link

- crates/project_model/src/sysroot.rs
Remove 'FIXME' after rust 1.47 comes out.  And for compatibility with versions before 1.47, did't remove 'src'.
> remove FIXME after rust 1.47 comes out

- Cargo.lock
- Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/interner.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- crates/hir_ty/src/traits/chalk/tls.rs
Quite a few changes, because Chalk got rid of the `ApplicationTy` nesting.
> Upgrade Chalk to 0.36

- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/main_loop.rs
> Respond with JSON-RPC error if we failed to deserialize request

- docs/dev/style.md
> Document doer object anti-pattern

- crates/rust-analyzer/src/main_loop.rs
This reduces the number of progress bar updates we send to the client by collapsing subsequent updates into one. This doesn't work as well as I'd hoped (which is that we end up sending *no* updates, or only `start` and `end`, when the cache is already fresh), but it does reduce the number considerably: instead of ~720 updates on the rust-analyzer codebase, we now only send ~60.
It uses the same approach that is already in use for coalescing VFS events.
Hopefully this is enough to fix https://github.com/rust-analyzer/rust-analyzer/issues/6413.
> Coalesce prime_caches updates

- crates/assists/src/handlers/qualify_path.rs
The `qualify_path` assists currently eats up already annotated generics in all but one cases which can be annoying if one already pre-fills generics of a type before it's been qualified.
> Keep generic annotations when qualifying things

- crates/ide/src/diagnostics.rs
- crates/syntax/src/algo.rs
This is the last blocker for #6287 after this I can update that PR to properly fix things through using `SyntaxRewriter`.
This PR also shuffles tests around a bit and adds some more.
Ideally this is just a hack until we implement a "proper" diff algorithm that approximates a minimal diff. Maybe something like [gumtree](https://github.com/GumTreeDiff/gumtree)?
> Do insertion lookahead in algo::diff

- crates/hir_ty/src/diagnostics/decl_check.rs
Resolves #6348
This is not a full-fledged solution, as it doesn't looks up for parent elements (e.g. function -> module -> parent module -> crate root), but it does at least checks attributes of item being checked.
I played a bit with code, and it seems that implementing a proper solution (which will also check for `deny` / `warn` attributes overriding values for `allow`s from above).
So, this solution should fix all the macros which intentionally do "weird" naming and wrap it with `allow`, such as `lazy_static`.
cc @ArifRoktim
> Check for allow(..) attributes in case check diagnostic

- editors/code/rust.tmGrammar.json
Functions inside trait declarations can break subsequent highlighting, because they have no curly brackets. In a case such as:
```rust
pub trait Summary {
fn summarize(&self) -> String;
}
```
the scope `meta.function.definition.rust` will continue past the end of the block looking for `{` after `fn`. This PR allows `meta.function.definition.rust` to terminate with `;` in these cases.
> Textmate grammar: allow function declarations without curly brackets

- editors/code/rust.tmGrammar.json
> Textmate grammar: Distinguish turbofish function calls from namespaces

- crates/ide/src/inlay_hints.rs
This just hints all self parameters with the `self` token, this is therefor equal to how all other parameters are displayed, but given the self param special in how its defined in a function signature it might make sense to keep the `&`/`&mut` parts as well as emitting those tokens for explict `Self` types that are taken by ref like `self: &Rc<Self>`?
Fixes #6400
> Only show `self` ident when showing parameter self hints

- crates/assists/src/handlers/auto_import.rs
- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/assists/src/handlers/replace_qualified_name_with_use.rs
- crates/assists/src/utils/insert_use.rs
- crates/syntax/src/ast/make.rs
This change minifies the resulting diff of import insertions by inserting or replacing the produced use tree directly through an `action` return value instead replacing the entire container node. This action has to be applied by the caller now. This unfortunately pulls the `AssistBuilder` into scope of `insert_use` back again but I tried to at least keep it away from the `insert_use` fn itself.
I'm open to more/better ideas regarding this :)
Fixes #6196
> Don't replace entire module and file nodes when inserting imports

- crates/assists/src/handlers/add_custom_impl.rs
When we find at least one trait with the same name as the derive accessible from the current module we now generate a qualified path to that trait in the generated impl.
If we don't find any we just do what was done before and emit the trait name in the generated impl.
> Qualify trait impl created by add_custom_impl assist

- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ide/src/diagnostics/fixes.rs
- crates/syntax/src/ast/make.rs
As requested :)
This also prevents the assist from being disabled if a definition in the value namespace exists with the same name as our new struct since that won't cause a collision
#4468
> Support record variants in extract_struct_from_enum_variant

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/mod_resolution.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/nameres/tests/mod_resolution.rs
> Don't stack overflow on circular modules

- .github/ISSUE_TEMPLATE/bug_report.md
> Add common issues to the bug report template

- editors/code/src/client.ts
Closes #6452 
Info
-----
* As discussed in #6452, the `Error('busy')` workaround for semantic token flickering was removed because the underlying issue was believed to be fixed in VS Code.
* It turns out that the fix isn't yet complete, so this caused flickering of the semantic highlighting when making rapid edits (e.g. typing quickly).
* This PR restores that workaround and makes it slightly more robust, covering all areas of semantic token middleware.
Changes
-----
* Added middleware functions for `provideDocumentSemanticTokens`, `provideDocumentSemanticTokensEdits`, and `provideDocumentRangeSemanticTokens` to match the 3 possible middleware hooks defined in https://github.com/microsoft/vscode-languageserver-node/blob/master/client/src/common/semanticTokens.ts#L33
* Each intercepts a …
> Restore semantic token flickering workaround removed in #5697

- crates/assists/src/handlers/convert_integer_literal.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/generated/tokens.rs
- crates/syntax/src/ast/token_ext.rs
- xtask/src/codegen/gen_syntax.rs
> More orthogonal API

- crates/assists/src/handlers/infer_function_return_type.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
This adds an assist to insert a functions return type if it hasn't been specified yet by inferring it from the functions tail expression. This assist only becomes active if the cursor is on the tail expression. See https://github.com/rust-analyzer/rust-analyzer/issues/6303#issuecomment-714657326
> Add infer_function_return_type assist

- crates/assists/src/handlers/convert_integer_literal.rs
- crates/hir_def/src/body/lower.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/validation.rs
> Cleanup API

- editors/code/rust.tmGrammar.json
Fixes https://github.com/dustypomerleau/rust-syntax/issues/3.
> Textmate grammar: add `+=` to assignment operators

- editors/code/rust.tmGrammar.json
- prevent `pat` from matching before `path` in metavariable types
- reduce the precedence of math operators so that assignment operators match correctly
> Textmate grammar: Precedence fixes

- editors/code/rust.tmGrammar.json
Variables were originally designed not to match after a dot, in order to avoid matching struct field access, however this resulted in variables that end ranges not being highlighted. In order to fix this we match a preceding dot, only if it's preceded by at least one other dot. Attempting to match on `(\.{2,})?` won't work, because the optional group allows struct field access to match even when one dot is present.
> Textmate grammar: allow variables to terminate ranges

- crates/assists/src/handlers/add_custom_impl.rs
- crates/assists/src/handlers/add_missing_impl_members.rs
- crates/assists/src/utils.rs
- crates/syntax/src/ast/make.rs
- xtask/tests/tidy.rs
```rust
use std::fmt;
#[derive(Debu<|>g)]
struct Foo {
bar: String,
}
```
->
```rust
use std::fmt;
struct Foo {
bar: String,
}
impl fmt::Debug for Foo {
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
${0:todo!()}
}
}
```
> Add missing AssocItems in add_custom_impl assist

- editors/code/rust.tmGrammar.json
Addresses some of the issues mentioned here: https://github.com/dustypomerleau/rust-syntax/issues/5.
In sync with https://github.com/dustypomerleau/rust-syntax/issues/6.
> vscode: fix tmGrammar issues around non-controlflow keywords

- crates/assists/src/assist_context.rs
- crates/assists/src/handlers/expand_glob_import.rs
- crates/assists/src/handlers/reorder_fields.rs
Also fixes a small bug in `expand_glob_import` in regards to the very nice looking `something::{*}` import when only one item was used. Before it would duplicate the path and just append it, causing the following wrong import `something::something::UsedItem`.
> Remove text_edit_builder api from AssistBuilder

- editors/code/rust.tmGrammar.json
> Textmate grammar: prevent `/**/` from matching block doc comments

- crates/syntax/src/algo.rs
This makes the diff a bit more detailed.
See https://github.com/rust-analyzer/rust-analyzer/pull/6287#issuecomment-723889267 for context
cc @SomeoneToIgnore
> Don't replace parent node when inserting as first child in algo::diff

- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt
- crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
Note that we have to maintain custom implementation on the client
side: I don't see how to marry bulitin resolve support with groups and
snippets.
> Switch to upstream protocol for resolving code action

- Cargo.lock
- crates/hir_ty/Cargo.toml
- crates/hir_ty/src/tests.rs
- crates/stdx/src/lib.rs
> Replace RacyFlag with OnceCell

- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
> Fix extract_struct_from_enum_variant not updating record references

- Cargo.lock
- crates/assists/src/utils.rs
- crates/completion/Cargo.toml
- crates/completion/src/completions/record.rs
I'm not sure I should import `assists` crate inside `completions`, maybe we should move out `FamousDefs` from `assists` ? Let me know :) 
close #6492
Signed-off-by: Benjamin Coenen <5719034+bnjjj@users.noreply.github.com>
> add suggestion ..Default::default() for remaining struct fields in a constructor

- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide_db/src/search.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/node_ext.rs
> Properly handle shorthands in destructure patterns when renaming

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/document.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/rust-analyzer/tests/rust-analyzer/support.rs
- docs/dev/lsp-extensions.md
Pulls in https://github.com/gluon-lang/lsp-types/pull/186
> Latest LSP 3.16 protocol

- crates/assists/src/handlers/unwrap_block.rs
> **Unwrap Block** supports stand-alone blocks

- crates/hir/src/diagnostics.rs
- crates/hir_expand/src/diagnostics.rs
- crates/ide/src/diagnostics.rs
- crates/rust-analyzer/src/handlers.rs
> Fill the diagnostic code field in publish_diagnostics

- crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt
- crates/rust-analyzer/src/diagnostics/test_data/handles_macro_location.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_incompatible_type_for_trait.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_mismatched_type.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_wrong_number_of_parameters.txt
- crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/handlers.rs
Fixes #6371
This makes the error code in here clickable, same for clippy lints
For clippy I just chose the master build of the site as I believe that to be pretty much always the best fitting.
> Link rustc error page and clippy lint page via CodeDescription

- crates/assists/src/handlers/remove_dbg.rs
If the expr in the `dbg!` macro consists of multiple elements it won't remove the parentheses if its in a `match` or condition-using construct, as these are followed by siblings causing the `is_leaf` check to fail.
> Don't wrap parens around expr in remove_dbg assist if its in conditions

- editors/code/rust.tmGrammar.json
Adding round brackets ensures word boundaries on both sides of booleans (reported in https://github.com/dustypomerleau/rust-syntax/issues/7).
> Textmate grammar: ensure word boundary after `true`

- crates/rust-analyzer/src/main_loop.rs
> Don't assume DidChangeTextDocument paths exist

- crates/assists/src/handlers/ignore_test.rs
The `Ignore this test` assist previously allowed ignoring multiple times, each time adding a `#[ignore]` attribute.
This PR instead shows an assist to undo the ignoring.
> add 'Re-enable this test' assist

- Cargo.lock
This is a `cargo update` run without updating `cargo_metadata`.
`cargo_metadata` `0.12.1` pins `semver-parser` to `0.10.0` (https://github.com/oli-obk/cargo_metadata/commit/4e88e5624c5f20ca94dad0ea97fdb438fdea443f) which brings back the compile time blowup that @matklad tried so hard to avoid in https://github.com/steveklabnik/semver-parser/pull/50.
> cargo update (without cargo_metadata)

- crates/hir/src/db.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/status.rs
- crates/ide_db/src/apply_change.rs
- crates/ide_db/src/lib.rs
https://github.com/rust-analyzer/rust-analyzer/pull/6625
> followup to "hir_expand: propagate expansion errors"

- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/config.rs
- crates/completion/src/lib.rs
- crates/rust-analyzer/src/config.rs
- editors/code/package.json
Part of https://github.com/rust-analyzer/rust-analyzer/issues/6612
Adds a possibility to disable autoimports:
and other experimental completions we might want to add later.
> Gate autoimports begind experimental completions flag

- crates/rust-analyzer/src/semantic_tokens.rs
- editors/code/package.json
VSCode has added more builtin fallback scopes, so we can remove some of our fallback scopes by aligning with their conventions. 
Note that the macro scope doesn't seem to actually *work* at the moment. I have filed a bug with VSCode: https://github.com/microsoft/vscode/issues/110150
> Use builtin scopes more

- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/render.rs
- crates/hir_def/src/import_map.rs
- crates/ide_db/src/imports_locator.rs
Presumably closes https://github.com/rust-analyzer/rust-analyzer/issues/6594
May help https://github.com/rust-analyzer/rust-analyzer/issues/6612
* Ignore modules eaferly
* Do less completion string rendering
> Improve autoimports on completion speed

- crates/rust-analyzer/src/main_loop.rs
Diagnostics are sometimes only showing up when typing. This should fix that.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6381
> Publish diagnostics on file open

- crates/hir_expand/src/db.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/mbe_expander.rs
- crates/mbe/src/mbe_expander/matcher.rs
- crates/mbe/src/mbe_expander/transcriber.rs
> Use named fields in `ExpandResult`

- crates/hir/src/lib.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/status.rs
- crates/mbe/src/lib.rs
> Use `ExpandResult` instead of `MacroResult`

- crates/hir/src/diagnostics.rs
- crates/hir_def/src/diagnostics.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/hir_expand/src/proc_macro.rs
- crates/ide/src/diagnostics.rs
- crates/mbe/src/lib.rs
- docs/user/generated_diagnostic.adoc
This adds 2 new diagnostics, emitted during name resolution:
* `unresolved-proc-macro`, a weak warning that is emitted when a proc macro is supposed to be expanded, but was not provided by the build system. This usually means that proc macro support is turned off, but may also indicate setup issues when using rust-project.json. Being a weak warning, this should help set expectations when users see it, while not being too obstructive. We do not yet emit this for attribute macros though, just custom derives and `!` macros.
* `macro-error`, which is emitted when any macro (procedural or `macro_rules!`) fails to expand due to some error. This is an error-level diagnostic, but currently still marked as experimental, because there might be spurious errors and this hasn't been tested too well. …
> Publish diagnostics for macro expansion errors

- crates/hir_expand/src/diagnostics.rs
> Explain how we get precise spans for diagnostics.

- crates/ide/src/references/rename.rs
This fixes renaming owned SelfParams turning the parameter into a reference, as in, for a type `Foo`, `fn foo(self) {}` became `fn foo(renamed_name: &Foo) {}` prior to this.
Similarly for the other way around, we now support renaming non-ref parameters to `self`. Additionally we do more checks now than before. We check:
- that the function has an impl block
- that we are renaming the first parameter(prior we ignored which parameter was renamed and always picked the first nevertheless)
- that the parameter's type aligns with the impl block(minus one level of reference abstraction to account for `&self`/`&mut self`)
> Allow renaming between self and first param with owned parameters

- crates/completion/src/completions/postfix.rs
- crates/completion/src/lib.rs
> add let and letm postfix to turn expressions into variables

- crates/ide/src/references.rs
- crates/ide_db/src/search.rs
The approach here is simply checking the descendants of the function body for `PathExpr` then checking whether it only contains a single `self` `PathSegment`, this is to prevent us from picking up `self` tokens from local `UseTree`s.
> Support self in reference search

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/diagnostics.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/data.rs
Changes `Expander::enter_expand` to return an `ExpandResult`, and adds any contained errors to the body diagnostic list.
> Emit macro diagnostics when lowering bodies

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/semantic_tokens.rs
> lsp-types 0.85: Fixes OptionalVersionedTextDocumentIdentifier specification

- crates/hir_def/src/nameres/tests/mod_resolution.rs
- crates/hir_def/src/path/lower/lower_use.rs
> Don't discard PathKind::Abs information in lower_use::convert_path

- crates/syntax/src/ast/token_ext.rs
I am not entirely sure whether to keep or remove the `SUFFIXES` but I figured we can always bring them back once they are needed.
> Accept more than just the standard rust literal suffixes in *Number::suffix

- crates/hir_def/src/body/lower.rs
Previously it attached them to the result of the macro expansion (or, if no result was produced, to the file containing the invocation). Always use the file containing the invocation.
This doesn't seem to have any observable difference, but seems better in theory.
bors r+
> Attach macro expansion errors to the right file

- crates/rust-analyzer/src/main_loop.rs
Fixes occasional "progress handler already registered" errors.
bors r+
> Don't prime caches when just opening a file

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/lib.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
This threads macro expansion errors through `eager.rs` and the `AsMacroCall` trait, improving macro diagnostics emitted during body lowering.
> More macro diagnostics improvements

- crates/hir_def/src/lib.rs
- crates/hir_expand/src/lib.rs
Diagnostics inside proc macros are currently incorrectly placed at their original offset, but inside the containing file. This fixes that, by allowing the creation of `ExpansionInfo` from non-`macro_rules!` macro invocations.
bors r+
> Fix proc macro token mapping

- crates/hir_def/src/body/tests.rs
- crates/hir_expand/src/builtin_macro.rs
It only consists of the argument passed to it.
bors r+
> Make `compile_error!` message match upstream rustc

- crates/ide/src/diagnostics.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6363
bors r+
> Don't diagnose `#[cfg]` in macros

- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
Without arbitrary self types, the self type could never refer to the method type parameters, so this wasn't a problem; but with arbitrary self types, it can.
This fixes the crash from #6668; but it doesn't make method resolution work for these methods.
> Use correct, full substs for self type in impl

- crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt
- crates/rust-analyzer/src/diagnostics/test_data/macro_compiler_error.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_wrong_number_of_parameters.txt
- crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
This makes rust-analyzer diagnostics match native rustc diagnostics in the terminal more closely. Unfortunately all of this is a bodge, since we already provide this information to the client in the form of `DiagnosticRelatedInformation`, but at least VS Code chooses such a poor UI for these that they don't help much, as evidenced [here](https://twitter.com/yaahc_/status/1335297260444250112) and in https://github.com/rust-lang/rust/issues/79741.
This PR papers over these client UI problems by taking the `DiagnosticRelatedInformation` and turning each one into its own hint-level diagnostic, which makes it show up in the source code. Quick fixes are attached to all resulting diagnostics, which makes them more discoverable.
> Emit additional diagnostics for hints/help/etc

- crates/completion/src/completions/attribute.rs
Might be nice to have them grouped for readability/maintainability similar to how the [reference](https://doc.rust-lang.org/reference/attributes.html#built-in-attributes-index) does it but that would require the use of a `OnceCell` for sorting the entries back after construction.
> Update attributes completion list

- crates/assists/src/handlers/early_return.rs
- crates/assists/src/handlers/move_guard.rs
- crates/assists/src/handlers/replace_if_let_with_match.rs
- crates/assists/src/handlers/replace_let_with_if_let.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
Basically the counterpart to `replace_if_let_with_match`, I personally sometimes want to replace matches like
```rust
match foo {
pat => expr,
_ => (),
}
``` 
into the corresponding
```rust
if let pat = foo {
expr
}
```
which is the main reasoning behind this.
I put this into the same file as `replace_if_let_with_match` because the are complementing each other and I would probably rename the file to something like `replace_if_let_match` but I didn't do that for now because I was unsure whether git would still view this as a rename or not due to the amount of changes in the file so that the diff is still properly visible for now.
> Add replace_match_with_if_let assist

- crates/hir_def/src/docs.rs
- crates/ide/src/hover.rs
Fixes #6742.
Doc attributes should be concatenated via a single linebreak as written in the [rustdoc book](https://doc.rust-lang.org/nightly/rustdoc/the-doc-attribute.html).
Also changed the loop to use an iterator to get rid of the `docs.trim_end_matches("\n\n").to_owned()` part using `Itertools::intersperse`.
> Don't insert blank lines between doc attributes

- Cargo.lock
- crates/base_db/src/input.rs
- crates/base_db/src/lib.rs
- crates/hir_expand/src/proc_macro.rs
- crates/proc_macro_api/Cargo.toml
- crates/proc_macro_api/src/lib.rs
- crates/proc_macro_api/src/process.rs
- crates/proc_macro_api/src/rpc.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
* Remove `ProcMacroClient::dummy` and just use `Option<ProcMacroClient>` instead
* Remember the type of proc macros (later allows us to reject using an incorrect macro type)
* Prepare a few internals for procedural attribute macros
bors r+
> Some more proc macro cleanups

- crates/hir_expand/src/hygiene.rs
Fixes the incorrect macro resolution in https://github.com/rust-analyzer/rust-analyzer/issues/6716
No test, because diagnostics do not get remapped correctly for some reason. I've checked manually that this fixes the resolution errors.
bors r+
> Use the right `def_crate` for builtin macros

- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/workspace.rs
Fixes inclusion of generated files in typenum/heapless/defmt etc.
bors r+
> Apply environment set by build scripts

- editors/code/src/net.ts
Remove workaround for https://github.com/rollup/plugins/issues/491
because it's fixed in 15.0
https://github.com/rollup/plugins/blob/master/packages/commonjs/CHANGELOG.md#v1500.
Also fix fetch$1 is not a function error
https://github.com/rust-analyzer/rust-analyzer/issues/6757.
> Remove workaround & fix fetch$1 is not a function

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir_def/src/test_db.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/display/navigation_target.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
This also aligns the diagnostics behavior of `TestDB` with the one from the real IDE (by making the logic from `semantics.rs` a method on `InFile<&SyntaxNode>`), which makes bugs like this easier to find.
This should fix the misplaced diagnostics seen in https://github.com/rust-analyzer/rust-analyzer/issues/6747 and other issues.
bors r+
> Fix file range computation in macros

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- crates/test_utils/src/lib.rs
- editors/code/package.json
Configuration is editor-independent. For this reason, we pick
JSON-schema as the repr of the source of truth. We do specify it using
rust-macros and some quick&dirty hackery though.
The idea for syncing truth with package.json is to just do that
manually, but there's a test to check that they are actually synced.
I'll add something like `rust-analyzer --config-schema` in a follow-up
commit.
> Make config.rs a single source of truth for configuration.

- xtask/src/install.rs
VSCode has a feature to install the command to the PATH. 
`code-exploration` is the command name for the ARM64 experimental build. As of today, this is the only build running natively on Apple Silicon.
See _ARM64_ Experimental in https://code.visualstudio.com/insiders/#osx.
The `-exploration` prefix seems pretty undocumented, my understanding of it is that it is an insider-like version that uses a different electron version (in this case, maybe the election version that was recently ported to Apple Silicon?).
> Add client install support for `code-exploration` builds.

- crates/hir_expand/src/builtin_macro.rs
Addresses https://github.com/rust-analyzer/rust-analyzer/issues/6747#issuecomment-740778402
bors r+
> Fix `concat!` with integer literals

- xtask/src/main.rs
Support for `code-exploration` client was added #6766 in but the usage string wasn't updated.
> Update usage string to include code-exploration client.

- crates/hir_def/src/attr.rs
- crates/ide/src/hover.rs
- crates/syntax/src/ast/token_ext.rs
Properly attach inner and outer attributes to the things they actually belong to in the HIR. ~~I can add some tests for this if wanted once I know where to put them/how to test for this.~~ Put some tests into `hover.rs`.
So the following snippet
```rust
mod foo {
//! Hello
}
```
now shows `Hello` on hover 🎉
Fixes #2148
> Properly attach inner attributes in Attrs::new

- crates/proc_macro_srv/src/rustc_server.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6744
bors r+
> Avoid nesting Subtrees when parsing TokenStream

- crates/syntax/src/algo.rs
> Fix accidently quadratic syntax rewriter

- crates/hir_expand/src/db.rs
Should fix https://github.com/rust-analyzer/rust-analyzer/issues/6504
Not entirely sure what the previous limit was based on, but it looks like it does get hit in practice.
> Bump the macro token limit

- Cargo.lock
- crates/project_model/Cargo.toml
- crates/project_model/src/cargo_workspace.rs
These might be relied on by procedural macros, and can also be accessed via `env!`.
Required for fixing https://github.com/rust-analyzer/rust-analyzer/issues/6696. We do not yet propagate these to any proc macros though.
> Replicate Cargo environment variables

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
> Improve code structure

- crates/ide/src/hover.rs
> Don't highlight parent nodes of comments on hover

- xtask/src/metrics.rs
Reverts rust-analyzer/rust-analyzer#6825
It broke metrics entirely. Will debug this later, unless someone else gets to it first.
bors r+
> Revert "Fix memory usage metrics"

- crates/hir_def/src/builtin_attr.rs
- crates/hir_def/src/lib.rs
These are not yet used, but have to go through nameres later in order to support procedural macro attributes
> Add builtin attributes for use in nameres

- crates/hir_def/src/attr.rs
- crates/ide/src/runnables.rs
I figured that we should probably move as much of the doc usage to the HIR as possible hence this PR. If we should keep this AST-based feel free to close.
This change does have the nice(but not really useful as I doubt anyones gonna write doc tests like these) side effect that these two doc string snippets allow being run now.
> Use Attrs::docs in runnables instead of DocCommentsOwner

- crates/hir_def/src/attr.rs
- crates/ide/src/display/navigation_target.rs
That should be the last place where the AST comment machinery is referred to.
> Use Attrs::docs in NavigationTarget instead of DocCommentsOwner

- crates/assists/src/ast_transform.rs
- crates/hir/src/code_model.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/path.rs
- crates/hir_def/src/path/lower.rs
- crates/hir_def/src/type_ref.rs
- crates/hir_expand/src/name.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/utils.rs
This doesn't handle resolve yet as I don't know yet how that will be used. I'll get to that once I start moving the lifetime reference PR to the hir.
This also adds a new `hir` name type for lifetimes and labels, `hir::LifetimeName`.
> Add Lifetimes to the HIR

- crates/assists/src/handlers/add_missing_impl_members.rs
- crates/hir_ty/src/display.rs
Was wondering why the add missing impl assist didn't do anything here:
Turns out me forgetting to set the Index::Idx type in the trait causes RA to panic due to it trying to to create an unparsable type in the `make` module.
Now we get this instead which imo is definitely better to have.
> Don't HirDisplay unknown types when displaying for source

- crates/hir_def/src/item_tree.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lower.rs
[`hir_ty::utils::Generics`](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/hir_ty/src/utils.rs#L153) currently only assumes type parameters but not lifetime parameters and therefor creates incorrect index and length calculations, this PR just makes the use sites ignore LifetimeGenerics for now.
This fixes the panic at least locally for me for `analysis-stats`. Funnily enough this panic prevented me from using reference search for the `args` field to fix this problem.
> Ignore lifetime params in substitutions

- crates/project_model/src/sysroot.rs
Since we just tried running `rustup component add`, it doesn't make sense to me to recommend trying that again. If we're reaching this case, it's probably more likely that rustc was installed via package manager, in which case the source should be installed the same way (e.g. if you install the rust-src package on Ubuntu it will install a symlink in the right place to make our sysroot
detection work, and IMO we should get other distributors to do the same if they aren't already).
> Change recommendation when source can't be loaded from sysroot

- editors/code/language-configuration.json
- editors/code/package.json
There has been recent discussion in #6451 and #6682 about the need to include angle brackets in auto-close and auto-surround functionality. This PR will accomplish that, but only for users of VS Code, as it uses the VS Code-specific `language-configuration.json` to get the job done. Since there are a large number of VS Code users in the Rust Analyzer cohort, it may be reasonable to fix the issue for them, while waiting on a more comprehensive solution in the language server. In addition to the usual brackets, I've added auto-closing of block comments. I avoided autoclosing single quotes, given that lifetimes are more common than chars.
> Add a language configuration file for VS Code

- Cargo.lock
- crates/proc_macro_srv/Cargo.toml
- crates/proc_macro_srv/src/dylib.rs
> Replace goblin crate with object

- editors/code/.vscodeignore
#6840 added a `language-configuration.json` file to `package.json`, but because `.vscodeignore` was not updated, this file was not uploaded when the extension was published, leading to constant errors in the VS Code dev tools console:
```
[Extension Host] stack trace: Error: ENOENT: no such file or directory, open '/Users/-/.vscode/extensions/matklad.rust-analyzer-0.2.416/language-configuration.json'
```
> Add !language-configuration.json to .vscodeignore

- crates/ide/src/references.rs
- crates/ide_db/src/search.rs
> Add find usages for enum constructors

- docs/dev/style.md
> Add `#` to canonical test example

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/name.rs
We currently stub these out as returning unit.
This fixes spurious RA `macro-error` diagnostics introduced somewhere around 0.2.400 in the following:
```rust
unsafe { asm!(""); llvm_asm!(""); }
```
I'd ideally like to write a unit test for this, but I'm not familiar with where the tests for `hir_expand` are.
Thanks to @edwin0cheng for help on resolving this issue.
> Resolve `macro-error` diagnostics on asm & llvm_asm

- crates/assists/src/handlers/invert_if.rs
- crates/assists/src/utils.rs
- crates/syntax/src/ast/make.rs
> Parenthesize composite if condition before inverting in invert-if assist

- crates/assists/src/handlers/generate_default_from_enum_variant.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
> generate default implementation for an enum from an enum variant #6860

- docs/dev/README.md
> Document new permissions

- Cargo.lock
- Cargo.toml
- crates/hir/src/code_model.rs
- crates/hir/src/has_source.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/hir_expand/src/builtin_derive.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/hir_ty/src/tests/macros.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
- crates/syntax/src/display.rs
This adds support for (built-in-only) macros 2.0, and removes some hacks used for builtin derives, which are declared via macros 2.0 in libcore.
First steps for https://github.com/rust-analyzer/rust-analyzer/issues/2248.
Blocked on https://github.com/rust-analyzer/ungrammar/pull/16.
> Basic support for macros 2.0

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres/collector.rs
ItemTree is per-file, so there is no unique crate associated with it.
This means that it cannot know the active CfgOptions and thus couldn't
handle `cfg_attr`.
Prepare it for `cfg_attr`s by avoiding accessing attributes.
bors r+
> Avoid querying attributes in item tree lowering

- crates/hir/src/db.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/lang_item.rs
- crates/ide_db/src/apply_change.rs
It isn't used anywhere except in `crate_lang_items`. Remove it to
slightly reduce memory usage and simplify the code.
bors r+
> Remove `module_lang_items`

- crates/hir/src/code_model.rs
- crates/hir_ty/src/diagnostics.rs
- crates/hir_ty/src/diagnostics/decl_check.rs
Instead, store it in the `DeclValidator`.
Also pass the `CrateId` that defines the checked item along. This is not yet needed, but will be once I've refactored `Attrs` to handle `cfg_attr` internally.
We could also try to extract the crate from the "owner" `ModuleDefId` instead of passing it in, but then it might not be present for builtin types. Open to suggestions.
> decl_check: don't pass `db` around so often

- crates/ide/src/display/navigation_target.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/search.rs
- crates/ide_db/src/symbol_index.rs
- crates/rust-analyzer/src/handlers.rs
PR #6787 but rewritten to make use of the HIR now. This only applies to Lifetimes, not labels. Also Higher-Ranked Trait Bounds aren't supported yet, but I feel like this PR is big enough as is which is why I left them out after noticing I forgot about them.
Supporting renaming required slight changes in the renaming module as lifetime names aren't allowed for anything but lifetimes(and labels) and vice versa for normal names.
> Lifetime reference search 

- crates/hir_def/src/lib.rs
Access to the containing crate will be needed to handle `cfg_attr`.
bors r+
> Add `AttrDefId::krate`

- crates/hir/src/code_model.rs
- crates/hir_def/src/attr.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/runnables.rs
It is only meant for use inside `hir` crates.
Removes `docs_from_symbol`, which didn't seem to have any visible effect in VS Code.
> Make `Attrs::from_attrs_owner` private

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/to_proto.rs
- editors/code/package-lock.json
- editors/code/package.json
Companion to gluon-lang/lsp-types#192
> Latest LSP 3.16

- crates/ide/src/display/navigation_target.rs
- crates/ide/src/runnables.rs
> Rewrite doctest runnables

- crates/hir/src/code_model.rs
> Minor API cleanup

- crates/project_model/src/cargo_workspace.rs
This modifies the logic for calling cargo metadata so that it will use
the host platform if no explicit target platform is given. This is
needed since cargo metadata defaults to outputting information for _all_
targets.
Fixes #6908.
> Default to host platform for cargo metadata

- crates/hir_def/src/adt.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres/collector.rs
> Refactor attributes API to allow handling cfg_attr later

- crates/completion/src/render/macro_.rs
- crates/hir/src/code_model.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/hover.rs
There are some panic when hover/goto definition for proc-macro. It is because in current design, we don't have `ast-node` for proc-macro and then it trigger [this](https://github.com/rust-analyzer/rust-analyzer/blob/479d1f7eec22c3564867223e2093f14774092528/crates/hir/src/has_source.rs#L116) line to panic.
This PR is a temp fix for all of these similar to https://github.com/rust-analyzer/rust-analyzer/blob/bd4c352831662762ee7a66da77ec9adf623b0a0a/crates/completion/src/render/macro_.rs#L42
> Temp fixes panic caused by no ast for proc-macro

- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
> Do not merge imports with different attributes

- crates/assists/src/handlers/generate_function.rs
- crates/syntax/src/ast/make.rs
> Minor, cleanup API

- editors/code/src/main.ts
Added a warning if conflicting rust-lang.rust plugin is enabled.
Resolves #6463
> Added a warning if conflicting rust-lang.rust is enabled.

- crates/ide/src/display/navigation_target.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/references.rs
- crates/ide/src/runnables.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Reduce test verbosity

- crates/hir_def/src/attr.rs
- crates/hir_def/src/nameres/tests/diagnostics.rs
- crates/hir_expand/src/name.rs
- crates/parser/src/grammar.rs
- crates/parser/src/lib.rs
- crates/syntax/src/lib.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/5548
> Implement `cfg_attr` handling

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres/collector.rs
Resolves 2 `cfg_attr` FIXMEs
bors r+
> Don't look at attributes when lowering to ItemTree

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
- crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/rust-analyzer/src/to_proto.rs
> Use more Rustic highlighting specifiers

- crates/completion/src/completions/attribute.rs
- crates/completion/src/completions/dot.rs
- crates/completion/src/completions/keyword.rs
- crates/completion/src/completions/mod_.rs
- crates/completion/src/completions/pattern.rs
- crates/completion/src/completions/postfix.rs
- crates/completion/src/completions/qualified_path.rs
- crates/completion/src/completions/record.rs
- crates/completion/src/completions/snippet.rs
- crates/completion/src/completions/trait_impl.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/test_utils.rs
Continuation of the https://github.com/rust-analyzer/rust-analyzer/pull/6922, mainly created for a test.
Turns out our current completions tests were sorting the completions by label, I had to remove that to test the order properly and update this order in a bunch of tests (ergo the changes)
> Better fuzzy heuristics

- crates/mbe/src/mbe_expander/transcriber.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests.rs
> Handle $_ in mbe

- crates/hir/src/code_model.rs
- crates/hir_def/src/generics.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/utils.rs
- crates/ide/src/goto_definition.rs
There is a slight problem with this which is also noted in a FIXME now but `LifetimeParameters` of these ForLifetime where clauses allocate the lifetimes in the corresponding arena as if they were lifetimes of the item itself and not just the clause they belong to. I wasn't entirely sure what I could do about this but given nothing really uses lifetimes like that currently I figured it might be fine? Open to suggestions for that problem.
> Higher-ranked trait bounds for where clauses

- docs/user/manual.adoc
> Split lines in the manual between sentences

- crates/parser/src/grammar/type_params.rs
- crates/parser/src/grammar/types.rs
- crates/syntax/test_data/parser/inline/ok/0154_no_dyn_trait_leading_for.rast
- crates/syntax/test_data/parser/inline/ok/0154_no_dyn_trait_leading_for.rs
> Correctly parse legacy trait objects with leading ForType

- crates/parser/src/grammar/expressions/atom.rs
- crates/parser/src/grammar/params.rs
- crates/syntax/test_data/parser/inline/ok/0138_self_param_outer_attr.rast
- crates/syntax/test_data/parser/inline/ok/0154_tuple_attrs.rast
- crates/syntax/test_data/parser/inline/ok/0154_tuple_attrs.rs
- crates/syntax/test_data/parser/ok/0051_parameter_attrs.rast
- crates/syntax/test_data/parser/ok/0063_variadic_fun.rast
Fixes #2783, fixes #2781
The problem with `let _a = [0,#[cfg(feature = "L")]0];` has already been fixed some time ago it seems:
<details>
<summary>Syntax Tree for the const item</summary>
```
LET_STMT@200..236
LET_KW@200..203 "let"
WHITESPACE@203..204 " "
IDENT_PAT@204..206
NAME@204..206
IDENT@204..206 "_a"
WHITESPACE@206..207 " "
EQ@207..208 "="
WHITESPACE@208..209 " "
ARRAY_EXPR@209..235
L_BRACK@209..210 "["
LITERAL@210..211
INT_NUMBER@210..211 "0"
COMMA@211..212 ","
LITERAL@212..234
ATTR@212..233
POUND@212..213 "#"
L_BRACK@213..214 "["
PATH@214..217
PATH_SEGMENT@214..217
NAME_REF@214..217
IDENT@214..217 "cfg"
TOKEN_TREE@217..232
L_PAREN@217..218 "("
IDENT@218..225 "feature"
WHITESPACE@225..226 " "
EQ@226..227 "="
WHITESPACE@227..228 " "
STRING@228..231 "\"L\""
R_PAREN@231..232 ")" …
```
> Properly attach attributes to Param instead of parent ParamList

- crates/rust-analyzer/src/handlers.rs
Closes #2042
We're now using the `CompletionItem::tags` field to mark `CompletionItem`s as deprecated, and `CompletionItem::deprecated` is gone from LSP.
> Stop setting CompletionItem::deprecated

- crates/rust-analyzer/src/handlers.rs
We should keep setting it, according to https://github.com/rust-analyzer/rust-analyzer/pull/6974#issuecomment-748983789.
> Revert "Stop setting CompletionItem::deprecated"

- crates/rust-analyzer/src/diagnostics/to_proto.rs
Hopefully, this fixes https://github.com/rust-analyzer/rust-analyzer/issues/6892 (I couldn't test it since r-a currently requires a too recent version of VS Code)
> Filter out empty rustc spans

- crates/assists/src/handlers/remove_unused_param.rs
Include adjacent whitespace in the text edits to remove the
parameter declaration and its occurences in calling code.
https://github.com/rust-analyzer/rust-analyzer/issues/6663
> Delete related whitespace when removing unused param

- editors/code/src/main.ts
Closes #5641
The motivation in #5641 isn't too strong, but /etc/os-release exists on pretty much every Linux distro, while /etc/nixos sounds like an implementation detail.
> Use /etc/os-release to check for NixOS

- editors/code/src/main.ts
Apple chip has a new `arch`. It subsequently downloads Intel version of `rust-analyzer` but it works regardless.
> Allow code extension to download binary in apple arm

- .github/workflows/release.yaml
- xtask/src/dist.rs
This splits the `dist` matrix job into four and tries to make `xtask dist` more principled about target and artifact naming.
> Build aarch64-apple-darwin binaries on CI

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Use two consecutive newlines (`\n\n`) to actually continue text on a
new line.
Use proper markup to reference related settings.
Consistently format references to files, command line arguments, etc.
as `code`. Format mentions of UI elements in _italic_.
Fix typos, add missing full-stops, add missing default values.
> Clean up descriptions for settings

- editors/code/src/main.ts
This will also detect conflicts with kalitaalexey.vscode-rust and work correctly after RA is integrated with rust-lang.rust extension.
> Extension conflict check detects more combinations

- crates/assists/src/handlers/extract_module_to_file.rs
> Improve extract_module_to_file assist

- editors/code/src/main.ts
There's also a slight behavior change here: we no longer download our 64-binaries on 32-bit Darwin and Linux. We still do that on Windows, as I don't know how to detect 32-bit Node on 64 Windows.
But some people install the 32-bit Code by mistake, I doubt 32-bit Windows is that popular in the Rust crowd.
> Add support for downloading aarch64-apple-darwin binaries

- crates/completion/src/completions.rs
- crates/completion/src/completions/pattern.rs
- crates/completion/src/context.rs
- crates/completion/src/render.rs
- crates/completion/src/render/builder_ext.rs
- crates/completion/src/render/enum_variant.rs
- crates/completion/src/render/pattern.rs
- crates/hir/src/code_model.rs
Just gonna call it full pattern completion as pattern completion is already implemented in a sense by showing idents in pattern position. What this does is basically complete struct and variant patterns where applicable(function params, let statements and refutable pattern locations).
This does not replace just completing the corresponding idents of the structs and variants, instead two completions are shown for these, a completion for the ident itself and a completion for the pattern(if the pattern make sense to be used that is). I figured in some cases one would rather type out the pattern manually if it has a lot of fields but you only care about one since this completion would cause one more work in the end since you would have to delete all the extra matched fields again.
These …
> Add full pattern completions for Struct and Variant patterns

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/goto_definition.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6992
r? @edwin0cheng 
I'm not sure if this is totally correct, it looks like we create **two** `EagerCallLoc`s per macro invocation, one for the arguments (?), and one for the actual macro call. I gave both the same `AstId`, hopefully that's correct.
> Store invocation site for eager macros

- .github/workflows/release.yaml
- xtask/src/dist.rs
> Don't release uncompressed binaries under the new naming scheme

- .github/workflows/release.yaml
bors r+
Addresses https://github.com/rust-analyzer/rust-analyzer/pull/7011#discussion_r547772639.
> Set RA_TARGET at job level

- crates/proc_macro_srv/Cargo.toml
We `mmap` the files so they should be reasonably aligned.
Let's see what https://github.com/rust-analyzer/rust-analyzer/pull/6817#issuecomment-744866239 is about.
> Disable the unaligned feature of the object crate

- crates/completion/src/completions/qualified_path.rs
- crates/completion/src/completions/unqualified_path.rs
Fixes first part of #6549
Fixes #6550
> Show enum variant on Self qualified paths

- crates/rust-analyzer/src/handlers.rs
> Cleanup handle_code_action

- crates/ide/src/lib.rs
- crates/ide/src/references/rename.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
Automatically rename modules during file rename if they're in the same directory.
Fixes #6780
> Implement workspace/willRenameFiles for single-level file moves

- docs/user/manual.adoc
coc-rust-analyzer now supports inlay hints for variables and method chaining.
> chore: update coc-rust-analyzer inlay hints support

- crates/hir/src/code_model.rs
- crates/hir/src/from_id.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/expr.rs
- crates/hir_ty/src/infer/expr.rs
> Track labels in the HIR

- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers.rs
> pit-of-success API for unresolved code actions

- crates/rust-analyzer/src/cli/progress_report.rs
To prevent this from happening:
```
Database loaded 496.24ms, 288mi
Crates in this dir: 1
Total modules found: 14
Total declarations: 159
Total functions: 122
Item Collection: 6.02s, 61846mi
122/122 100% processing: archive::sizeTotal expressions: 6592       
Expressions of unknown type: 4 (0%)
Expressions of partially unknown type: 104 (1%)
Type mismatches: 3
Inference: 1.03s, 8622mi
Total: 7.05s, 70468mi
```
> Flush stdout when clearing the progress bar

- crates/ide/src/display/navigation_target.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/html.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
- crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
- crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
- crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/test_data/rainbow_highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/ide_db/src/defs.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
Implements general navigation for labels, goto def, rename and gives labels their own semantic highlighting class.
Fixes #6966
> Support labels in reference search

- crates/ide/src/diagnostics.rs
> Simplify more

- crates/ide/src/runnables.rs
> Don't split path separators apart in doctest runnables

- crates/assists/src/handlers/add_missing_impl_members.rs
- crates/assists/src/tests/generated.rs
> Fix type typo in add_missing_impl_members doc

- crates/assists/src/assist_context.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> Simplify assists resolution API

- crates/proc_macro_srv/src/dylib.rs
- crates/proc_macro_srv/src/proc_macro/bridge/client.rs
- crates/proc_macro_srv/src/proc_macro/bridge/mod.rs
- crates/proc_macro_srv/src/proc_macro/bridge/server.rs
https://github.com/rust-lang/rust/pull/75082 and https://github.com/rust-lang/rust/pull/76292 added a new flag in `proc_macro::Bridge` such that the ABI was changed. These ABI changing are the reason of some weird panics which caused #6880 and maybe related to the panic mentioned in #6820.
These changes are landed on rust stable 1.48 so I think it is okay to apply it now.
fixes #6880
r @jonas-schievink
> Add force_show_panics flag for proc-macro bridge

- crates/base_db/src/input.rs
- crates/base_db/src/lib.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/proc_macro.rs
- crates/proc_macro_api/src/lib.rs
- crates/proc_macro_api/src/rpc.rs
- crates/proc_macro_srv/src/lib.rs
- crates/tt/src/lib.rs
In theory, fixes https://github.com/rust-analyzer/rust-analyzer/issues/6696.
This seems to result in these obscure crashes for some reason:
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/jonas/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/proc_macro/src/bridge/scoped_cell.rs:75:51
stack backtrace:
0: rust_begin_unwind
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
1: core::panicking::panic_fmt
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
2: core::panicking::panic
at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
3: core::option::Option<T>::unwrap
at …
```
> Pass the crate environment to proc macros

- crates/mbe/src/parser.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests.rs
In #6929, we treat '_' as an ident but rustc is only allow it in some special places (e.g. meta var in mbe , type, pat etc). 
This PR rollback that and we only make '$_' works in meta var matching. 
Fixes #7056
> Special case $_ in meta var instead of treat it as ident in mbe 

- crates/completion/src/completions/postfix.rs
- crates/completion/src/completions/postfix/format_like.rs
See https://github.com/rust-analyzer/rust-analyzer/issues/6843
this brings it back in line with the documentation
> format-postfix completion takes format instead of fmt

- crates/completion/src/completions/unqualified_path.rs
- crates/hir_def/src/import_map.rs
- crates/ide_db/src/imports_locator.rs
A follow-up of https://github.com/rust-analyzer/rust-analyzer/pull/6918#issuecomment-748511151 and the PR itself.
Tweaks the `import_map` query api to be more flexible with the ways to match against the import path and now fuzzy imports search in names only.
This had improved the completion speed for me locally in ~5 times for `fuzzy_completion` span time, but please recheck me here.
IMO we're fast and presice enough now, so I've added the modules back to the fuzzy search output.
Also tweaks the the expect tests to display functions explicitly, to avoid confusing "duplicate" results.
> Ignore qualifiers when doing autoimport completions lookup

- crates/ide/src/diagnostics.rs
- crates/syntax/src/ast/node_ext.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/4531
Makes it so that if a bracketed use statement contains a comment inside the braces, no "Unnecessary braces in use statement" diagnostic is shown.
> Smarter bracketed `use` diagnostic

- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
I was debugging some issues with the RA extension around getting `cargo check` to work and it was particularly frustrating to get the RA_LOG variable set on the server since I had to change it in a login file. This should make that easier.
> Add an option for extra env vars in the Code extension

- crates/project_model/src/cargo_workspace.rs
There is a repro case and background in the linked issue.
In short, the goal of this MR is to allow rust-analyzer to discover proc-macros which come from your tests (including, most importantly, dev-dependencies).
By default, `cargo check` implies the equivalent of `--lib --bins`, meaning it'll check your libraries and binaries -- but not tests! This means proc-macros (or, I guess, build scripts as well) weren't discovered by rust-analyzer if they came from tests.
One solution would be to manually add `--lib --bins --tests` (i.e., just augment the effective options to include tests). However, in this MR, I threw in `--all-targets`, which [according to the docs](https://doc.rust-lang.org/cargo/commands/cargo-check.html#target-selection) implies `--benches --examples` too. I have absolutely …
> Pass --all-targets to "cargo check" when discovering external resources

- crates/completion/src/completions/record.rs
Previously the inserted text was always `..Default::default()` which ends up as `...Default::default()`
if `.` was typed. Now  checks if the current token is `.` and inserts `.Default::default()`
if it is, so `..Default::default()` is correctly completed.
I think there's probably a better way to implement this context aware completion because I've seen it in other parts of rust-analyzer as a user but I'm not sure how to do it.
Fixes #6969
> Fix completion of Default struct update syntax

- .github/workflows/release.yaml
Because beta was promoted to stable yesterday.
bors r+
> Use stable instead of beta on macos-11 release runner

- crates/base_db/src/input.rs
- crates/ide/src/runnables.rs
- crates/ide/src/syntax_highlighting/injection.rs
- crates/project_model/src/project_json.rs
- crates/rust-analyzer/src/markdown.rs
- docs/user/manual.adoc
This adds `2021` in all places where rust-analyzer already knew about `2015` and `2018`.
The only edition-specific behaviour I could find in the source code was gated on a direct comparison with `Edition2015`, so `Edition2021` should (correctly) behave the same as `Edition2018`:
https://github.com/rust-analyzer/rust-analyzer/blob/56a7bf7ede12f6bec194265ea4a95911c9e469bd/crates/hir_def/src/nameres/path_resolution.rs#L132
> Add support for Rust 2021.

- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/lib.rs
> Don't emit arg count diagnostics for method calls with unknown receiver

- crates/hir_expand/src/db.rs
- crates/hir_ty/src/tests/regression.rs
Fixed following infer error:
```rust
macro_rules! bar { () => {0u32} }
fn test() {
let a = [bar!()];   // a : [unknown]
}
```
bors r+
> Fix infer error of macro invocation in array expr

- crates/assists/src/handlers/extract_assignment.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
Add extract-assignment assist (#7006).
Assist is for now only implemented on if/match-statements where the assigment is the last statement in every block,
as for other cases, one would have to check whether the assignment has effects on the rest of the block and
extract a temporary variable for it in the block.
> Add extract_assignment assist

- crates/hir_def/src/path/lower.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/hir_ty/src/tests/macros.rs
- crates/mbe/src/mbe_expander/matcher.rs
- crates/mbe/src/mbe_expander/transcriber.rs
- crates/mbe/src/parser.rs
This PR introduces `HygineFrames` to store the macro definition/call site hierarchy in hyginee and when resolving `local_inner_macros` and `$crate`, we use the token to look up the corresponding frame and return the correct value.
See also: https://rustc-dev-guide.rust-lang.org/macro-expansion.html#hygiene-and-hierarchies
fixe #6890 and  #6788
r? @jonas-schievink
> Proper handling $crate and local_inner_macros

- crates/assists/src/handlers/fill_match_arms.rs
- crates/assists/src/handlers/fix_visibility.rs
- crates/assists/src/utils.rs
- crates/completion/src/completions.rs
- crates/completion/src/completions/trait_impl.rs
- crates/completion/src/render.rs
- crates/completion/src/render/const_.rs
- crates/completion/src/render/function.rs
- crates/completion/src/render/macro_.rs
- crates/completion/src/render/type_alias.rs
- crates/hir/src/code_model.rs
- crates/hir/src/has_source.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/diagnostics/fixes.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/goto_type_definition.rs
- crates/ide/src/hover.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
I've made a start on fixing #6913 based on the provided work plan, migrating `HasSource::source` to return an `Option`. The simple cases are migrated but there are a few that I'm unsure exactly how they should be handled:
- Logging the processing of functions in `AnalysisStatsCmd::run`: In verbose mode it includes the path to the module containing the function and the syntax range. I've handled this with an if-let but would it be better to blow up here with `expect`? I'm not 100% on the code paths but if we're processing a function definition then the source should exist.
I've handled `source()` in all code paths as `None` being a valid return value but are there some cases where we should just blow up? Also, all I've done is bubble up the returned `None`s, there may be some places where …
> Migrate HasSource::source to return Option

- crates/hir/src/code_model.rs
- crates/ide/src/lib.rs
- crates/ide/src/view_hir.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/README.md
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
Will fix https://github.com/rust-analyzer/rust-analyzer/issues/7061. Very rough initial version just to work out where I needed to wire everything up.
@matklad would you be happy merging a hir visualiser of some kind? If so, do you have any thoughts on what you'd like it show, and how?
I've spent very little time on this thus far, so I'm fine with throwing away the contents of this PR, but I want to avoid taking the time to make this more polished/interactive/useful only to discover that no-one else has any interest in this functionality.
> Add VSCode command to view the hir of a function body

- crates/hir_def/src/diagnostics.rs
- docs/user/manual.adoc
Add some details on how to build the manual and some clarification on how to deal with "proc macro2 warnings.
For context, this arose from [this question](https://users.rust-lang.org/t/how-to-disable-rust-analyzer-proc-macro-warnings-in-neovim/53150) on users.rust-lang.org.
> Manual updates

- crates/hir/src/code_model.rs
- crates/ide/src/hover.rs
Shows goto type actions for type parameters:
Shows goto type actions for const parameters:
Also shows implementations for `Self`:
> Show goto type actions for Const and TypeParams

- crates/hir/src/code_model.rs
Hello !
As said in #7158, I noticed that `hir::Function` has no direct way of getting the return type, so this PR adds this functionality.
> Get `hir::Function` return type

- .github/workflows/release.yaml
Our builds get queued for 40-50 minutes waiting for a `macos-11.0` runner, let's keep using the older OS.
> Use macos-latest for aarch64-apple-darwin releases

- crates/hir_def/src/attr.rs
- crates/hir_def/src/db.rs
This change introduces two new queries to compute:
1) attributes for all variants of an enum, and
2) attributes for all fields of a variant.
The purpose of this change is to avoid the current n^2 behavior when rendering completion for variants (which prevents completion for enums with large numbers of variants).
> Introduce queries to avoid problems when performing completion for enums with many variants

- crates/assists/src/handlers/inline_function.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
This introduces an `inline_function` assist which will convert code like this:
```rust
fn add(a: u32, b: u32) -> u32 { a + b }
fn main() {
let x = add<|>(1, 2);
}
```
Into something like this:
```rust
fn add(a: u32, b: u32) -> u32 { a + b }
fn main() {
let x = { 
let a = 1; 
let b = 2; 
a + b 
};
}
```
Fixes #6863.
> Created an assist for inlining a function's body into its caller

- crates/completion/src/completions/unqualified_path.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/item_scope.rs
- crates/ide_db/src/imports_locator.rs
Store imported traits' associated function/methods and constants into `ImportMap.fst` and pefrorm the imports search on them.
This is a first step towards trait autoimport during completion functionality, the way I see it, after this PR, only a few major things are left to be done:
* store all traits' assoc items into fst, not only the ones in scope, as we do now. Any code pointers on how to do this are welcome 😄 
* adjust a few modules in completions crate (`dot.rs`, `qualified_path.rs` at least) to query the import map, reusing the `import_assets` logic heavily
==
With the current import and autoimport implementations, it looks like for a single query, we're either interested in either associated items lookup or in all other `fst` contents lookup, but never both simultaneously.
I would …
> Store trait associated items in fst

- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/lib.rs
This PR adds some documentation for the `project_model` crate.
Some of the field descriptions were taken directly from their `cargo_metadata` counterpart :
- `PackageData` -> `cargo_metadata::Package`
- `TargetData` -> `cargo_metadata::Target`
> Document project_model::PackageData and project_model::TargetData

- docs/dev/README.md
- docs/user/manual.adoc
Fixes https://github.com/rust-analyzer/rust-analyzer/pull/7156#issuecomment-755487667
> Update remaining serverPath references

- crates/vfs/src/lib.rs
This removes an outdated comment, and uses intra-doc links
> Adjust vfs crate documentation

- crates/hir/src/db.rs
- crates/hir_def/src/path/lower.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_ty/src/tests/macros.rs
- crates/ide_db/src/apply_change.rs
- crates/mbe/src/mbe_expander/matcher.rs
- crates/mbe/src/mbe_expander/transcriber.rs
- crates/mbe/src/parser.rs
Similar to previous PR (#7133) , but improved the following things :
1. Instead of storing the whole `ExpansionInfo`, we store a similar but stripped version `HygieneInfo`.
2. Instread of storing the `SyntaxNode` (because every token we are interested are IDENT), we store the `TextRange` only.
3. Because of 2, we now can put it in Salsa.
4. And most important improvement: Instead of computing the whole frames every single time, we compute it recursively through salsa: (Such that in the best scenario, we only need to compute the first layer of frame)
```rust
let def_site = db.hygiene_frame(info.def.file_id);
let call_site = db.hygiene_frame(info.arg.file_id);
HygieneFrame { expansion: Some(info), local_inner, krate, call_site, def_site }
```
The overall speed compared to previous PR is …
> Proper handling $crate Take 2 [DO NOT MERGE]

- crates/mbe/src/mbe_expander/transcriber.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/tests.rs
We treated `$crate` as meta variable in LHS of mbe, which should be an `ident`. 
Fixes #7204
> Fix bug for $crate in LHS of mbe

- crates/ide/src/inlay_hints.rs
The case-insensitive prefix/suffix check can be performed
character-by-character. This allows the check to be done without having
to allocate a new string. As a side effect, it's also no longer
necessary to convert the entire string to lowercase, as it's done as
needed. As the only case equality we're handling is ASCII, this
operation can be further optimized by using byte equality, rather than
character equality.
cc @SomeoneToIgnore, as it's an update on my PR from yesterday.
> Remove unnecessary allocation when checking whether to hide argument name hint

- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
Helps with #6168 
This PR is very limited implementation to support intra-doc. It only support links indicate same file function.
I want someone to feedback me about this implementation. If the approach is good, I will continue this PR to support other symbols like enum and struct.
> Implement to support intra-doc link

- crates/hir/src/code_model.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/references.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/search.rs
Basically just this:
```diff
pub enum Definition {
Macro(MacroDef),
Field(Field),
ModuleDef(ModuleDef),
SelfType(Impl),
Local(Local),
-    TypeParam(TypeParam),
-    LifetimeParam(LifetimeParam),
-    ConstParam(ConstParam),
+    GenericParam(GenericParam),
Label(Label),
}
```
> Use hir::GenericParam in ide_db::Definition instead of relisting all 3

- crates/parser/src/grammar/type_args.rs
- crates/syntax/test_data/parser/inline/ok/0039_type_arg.rast
- crates/syntax/test_data/parser/inline/ok/0039_type_arg.rs
This should fix #7232 - hopefully I've done it right, it passes the tests and the rast file looks like it's picking up the true and false in the test
> Allow `true` and `false` keywords in const generics

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/proc_macro_srv/Cargo.toml
- crates/project_model/Cargo.toml
It now pulls in a newer version of semver-parser.
This does add a dependency on `cargo-platform` in the interest of correctness.
> Unfreeze cargo_metadata

- crates/ide/src/hover.rs
- crates/ide/src/references/rename.rs
Improves the user facing error messages a bit and prevents renaming to `_` when the name is referenced as this would change source to not compile anymore since `_` is only a pattern, not a proper identifier.
> Refactor rename name checking

- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/assists/src/handlers/inline_local_variable.rs
- crates/assists/src/handlers/remove_unused_param.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/handlers.rs
- crates/ssr/src/search.rs
Fixes #4901
This doesn't address https://github.com/rust-analyzer/rust-analyzer/pull/7032/files#diff-a7e1e771e911237bb893e1b0f5e0f2c2a856b54ca06f95ef0818a922f1a8b5ebR266
> Group references by FileId

- crates/hir_def/src/per_ns.rs
- crates/hir_def/src/resolver.rs
- crates/hir_def/src/visibility.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/7081
When iterating over the names within the `hir_def::resolver::Scope` for a module, track what macros are in the `hir_def::item_scope::ItemScope::legacy_macros` collection for the module. When iterating over names from the prelude, do not proccess the name if it had been in the `legacy_macros` collection.
This is implemented with a `FxHashSet` in the `Scope::process_names` function that is populated when iterating over `legacy_macros` and checked when iterating over the prelude.
Alternative implementation could instead query the `legacy_macros` `FxHashMap` directly when processing names in the prelude.
Also, I'd like to add a test for this, but I'm not sure where it could be added.
> Deduplicate macros when offering completion

- crates/assists/src/handlers/unmerge_use.rs
followup for https://github.com/rust-analyzer/rust-analyzer/pull/7289
> Add test mark for skipping single use item in Unmerge use assist

- crates/assists/src/assist_config.rs
- crates/assists/src/handlers/auto_import.rs
- crates/assists/src/handlers/qualify_path.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests.rs
- crates/assists/src/utils.rs
- crates/completion/src/completions.rs
- crates/completion/src/completions/flyimport.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/config.rs
- crates/completion/src/lib.rs
- crates/completion/src/render.rs
- crates/completion/src/test_utils.rs
- crates/ide/src/lib.rs
- crates/ide_db/src/helpers.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/imports_locator.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/to_proto.rs
Part of https://github.com/rust-analyzer/rust-analyzer/pull/7293
Addresses https://github.com/rust-analyzer/rust-analyzer/pull/7293#issuecomment-761569558
Prepares `import_assets` and related to be used later for the trait fuzzy importing.
Also moves fuzzy imports into a separate completion module and renames them, as suggested in https://github.com/rust-analyzer/rust-analyzer/pull/7293#discussion_r558896685
> Share import_assets and related entities

- Cargo.lock
- crates/hir_def/Cargo.toml
- crates/hir_expand/Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/profile/Cargo.toml
- crates/project_model/Cargo.toml
This addresses [this comment](https://github.com/rust-analyzer/rust-analyzer/pull/7276#issuecomment-760909936). #7275 and #7276 should start compiling if this is merged.
> Depend on local copy of la-arena instead of crates.io’s

- crates/hir_def/src/adt.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/src.rs
- crates/hir_def/src/trace.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/lower.rs
- lib/arena/src/lib.rs
- lib/arena/src/map.rs
It’s unlikely that more items will be added to the module, so it’s simpler for users if `ArenaMap` is re-exported and the module made private.
This doesn’t compile for the same reason that #7275 doesn’t:
> This pull request doesn’t compile because dependencies on la-arena go through crates.io, so existing dependencies on the crate are referencing an old version. As such, this PR will only compile once a new la-arena version has been published.
> Remove map module from la-arena public API

- crates/hir_def/src/expr.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/trace.rs
- lib/arena/src/lib.rs
- lib/arena/src/map.rs
This makes naming consistent with `la_arena::RawId`. Alternatively, la-arena’s documentation could be updated to use ‘index’ terminology instead of ‘ID’ terminology, and `RawId` renamed to `RawIdx`.
This pull request doesn’t compile because dependencies on la-arena go through crates.io, so existing dependencies on the crate are referencing an old version. As such, this PR will only compile once a new la-arena version has been published.
> Make arena index vs ID naming consistent

- .github/workflows/release.yaml
- editors/code/src/main.ts
> Build dist-aarch64-unknown-linux-gnu releases

- crates/hir_expand/src/proc_macro.rs
- crates/ide/src/syntax_tree.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
- crates/mbe/src/tests.rs
- crates/proc_macro_srv/src/tests/mod.rs
- crates/proc_macro_srv/src/tests/utils.rs
Fixes #7283 
Swap assert_eq_text parameters in the order (expected, actual)
> Swap assert_eq_text\!(expected, actual)

- Cargo.lock
- crates/hir_def/src/type_ref.rs
- crates/parser/src/syntax_kind/generated.rs
- crates/syntax/src/ast/generated/nodes.rs
- xtask/src/ast_src.rs
Adds syntax-level support for macros in type position.
Based on https://github.com/rust-analyzer/rust-analyzer/pull/7291 due to the ungrammar update
> Add `MacroType`

- crates/hir_expand/src/hygiene.rs
- crates/mbe/src/syntax_bridge.rs
Reduces `HygieneFrameQuery`'s memory usage by like 10 MB or so
bors r+
> shrink_to_fit `TokenMap`'s backing storage

- Cargo.lock
- crates/profile/Cargo.toml
- crates/profile/src/memory_usage.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/bin/main.rs
- xtask/src/install.rs
- xtask/src/main.rs
jemalloc is useful due to its introspection API, which allows obtaining quick and accurate memory usage statistics without running into `mallinfo`'s limitations.
> Add back jemalloc support

- crates/ide/src/diagnostics/fixes.rs
- crates/ide/src/references/rename.rs
https://github.com/rust-analyzer/rust-analyzer/pull/7251#discussion_r556644241
> Rename reference search uses ide_db::search directly

- crates/hir_def/src/body.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/resolver.rs
- crates/hir_def/src/visibility.rs
- crates/hir_ty/src/tests.rs
I propose handling local items by computing a `DefMap` for every block expression, using the regular (early) name resolution algorithm. The result of that will be a `DefMap` that has a reference to the parent `DefMap`, which is either the one computed for the containing block expression, or the crate's root `DefMap`. Name resolution will fall back to a name in the parent `DefMap` if it cannot be resolved in the inner block.
The `DefMap`s computed for block expressions will go through a separate query that can be garbage-collected much more aggressively, since these `DefMap`s should be cheap to compute and are never part of a crate's public API.
The first step towards that is to make `CrateDefMap` not specific to crates anymore, hence this rename (if this plans sounds reasonable).
cc …
> Rename `CrateDefMap` to `DefMap`

- crates/ide/src/call_hierarchy.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
Didn't even realize these were only here for renaming as well!
bors r+
> Remove obsolete RangeInfo usage in references

- crates/base_db/src/input.rs
- crates/parser/src/event.rs
- crates/stdx/src/lib.rs
These were the warnings previously:
<details>
```
warning: could not parse code block as Rust code
--> crates/stdx/src/lib.rs:137:9
|
137 |   ///     ∀ x in slice[..idx]:  pred(x)
|  _________^
138 | | ///  && ∀ x in slice[idx..]: !pred(x)
| |____^
|
= note: error from rustc: unknown start of token: \u{2200}
warning: 1 warning emitted
warning: unresolved link to `package`
--> crates/base_db/src/input.rs:181:15
|
181 |     /// it's [package].name, can be different for other project types or even
|               ^^^^^^^ no item named `package` in scope
|
= note: `#[warn(broken_intra_doc_links)]` on by default
= help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: unresolved link to `package`
--> crates/base_db/src/input.rs:181:15
|
181 |     /// it's …
```
> Fix warnings when running `cargo doc --document-private-items`

- crates/assists/src/handlers/generate_function.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/nameres.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/display/short_label.rs
- crates/ide/src/hover.rs
- crates/ide/src/runnables.rs
- crates/ide_db/src/search.rs
A block containing inner items acts like the root module of a crate, so it needs to be representable as a `ModuleSource` and `ModuleOrigin`.
> Treat BlockExpr as a potential module origin

- crates/rust-analyzer/src/handlers.rs
> Change directory before running rustfmt to respect rustfmt.toml

- crates/hir/src/db.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/nameres/tests/block.rs
- crates/ide_db/src/apply_change.rs
This adds a `block_def_map` query that runs the name resolution algorithm on a block expression, and returns a `DefMap` that stores a link to the parent `DefMap` (either the containing block or the crate-level `DefMap`). Blocks with no inner items return the parent's `DefMap` as-is, to avoid creating unnecessarily long `DefMap` chains.
Path resolution is updated to recurse into the parent `DefMap` after looking up a path in the original `DefMap`.
I've added a few new tests for this, but outside of those this isn't used yet.
bors r+
> Add support for running name resolution in block expressions

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/data.rs
Removes the `local_scope` argument from `Expander` in favor of tracking the `DefMap` in use during body lowering.
For now, we still collect inner items as usual, because other code still relies on `item_scope`.
bors r+
> Make use of `block_def_map` in body lowering

- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/simple.rs
In 1.49.0, the definition of Box was modified to support an optional
Allocator[1]. Adapt the parsing of the `box` keyword to supply the
expected number of parameters to the constructor.
[1] https://github.com/rust-lang/rust/commit/f288cd2e179f600fa00c2a407206a12f6c5a91e0
Fixes: #6956
> Handle box with allocator

- .github/workflows/release.yaml
Run `analysis-stats` on `std` as part of the release workflow. Uses the `--with-deps` to also parse other crates defined in `stdlibs`. Remove the condition for exection, both analysis will be run for nightly and release builds.
Do not submit until #6956 has been fixed.
Bug: #6956
> Add step to run analysis-stats on std

- crates/hir/src/code_model.rs
- crates/hir/src/has_source.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/resolver.rs
- crates/hir_def/src/visibility.rs
- crates/hir_ty/src/tests.rs
Once `ModuleId` can represent modules inside block expressions, this will be required in order to obtain the correct `DefMap`. Otherwise existing code might use a `LocalModuleId` from the wrong `DefMap` and cause a panic.
bors r+
> Obtain `ModuleId`'s `DefMap` through a method

- crates/hir/src/code_model.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/lib.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/test_db.rs
- crates/hir_ty/src/tests.rs
- crates/hir_ty/src/traits/chalk.rs
> Make `ModuleId`'s `krate` field private and audit uses

- crates/hir/src/code_model.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/resolver.rs
- crates/hir_def/src/test_db.rs
- crates/hir_ty/src/test_db.rs
`ModuleId` needs to be able to represent blocks, and only the
associated `DefMap` will know how to construct that `ModuleId`
bors r+
> Create all `ModuleId`s through a `DefMap` method

- crates/hir_def/src/db.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/nameres/tests/block.rs
We now intern `BlockLoc` and use `BlockId` to refer to block expressions. This is needed to keep `ModuleId` simple, since it would otherwise have to store an arbitrarily long chain of blocks and couldn't be `Copy`.
The `DefMap` hierarchy is now created as the caller descends into an item body. This is necessary to link the correct module as the block's parent, which is important for correct name resolution.
As a result, we can now resolve `super` paths inside block expressions by climbing the `DefMap` chain.
bors r+
> Handle `super` paths inside blocks correctly

- editors/code/src/main.ts
- editors/code/src/net.ts
This avoids leaving the user with no LSP binary available if their network goes down during the download, and should not keep the current behavior: overwriting a running executable works on Unix and fails on Windows.
It also removes the `overwrite` argument, which is always enabled and wasn't working anyway.
Nominally closes #3896 (although that's already fixed)
> Simplify file download code

- crates/ide/src/display/navigation_target.rs
- crates/ide/src/references.rs
I noticed that selecting `Self` here highlights the entire trait,
this should cut it down to just the trait name and the `Self` which imo seems better.
> Shorten hir::TypeParam ranges for traits in NavigationTarget

- .vscode/launch.json
- crates/rust-analyzer/src/bin/args.rs
- crates/rust-analyzer/src/bin/logger.rs
- crates/rust-analyzer/src/bin/main.rs
- docs/dev/debugging.md
Adds two command line flags: `--no-buffering` and `--wait-dbg`. 
Not  sure if someone else needs this, but personally I found both flags extremely useful trying to figure out why RA does not work with Visual Studio. Or better to say why Visual Studio does not work with RA.
> Add no-buffering file logging and wait for a debugger option.

- crates/ide/src/inlay_hints.rs
Doing this check for other expressions makes little sense to me.
Fixes #7458
> Only hide parameter hints for path, field and methodcall expressions

- .github/workflows/release.yaml
Pin an Xcode version in the release workflow to avoid:
```
Run SDKROOT=$(xcrun -sdk macosx11.0 --show-sdk-path) MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx11.0 --show-sdk-platform-version) cargo xtask dist
xcodebuild: error: SDK "macosx11.0" cannot be located.
xcodebuild: error: SDK "macosx11.0" cannot be located.
xcrun: error: unable to lookup item 'Path' in SDK 'macosx11.0'
xcodebuild: error: SDK "macosx11.0" cannot be located.
xcodebuild: error: SDK "macosx11.0" cannot be located.
xcrun: error: unable to lookup item 'PlatformVersion' in SDK 'macosx11.0'
```
> Force XCode version

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
> ItemTree: Treat items in `MacroStmts` as top-level

- crates/hir_def/src/nameres/path_resolution.rs
Otherwise this might cause us to resolve the path from the wrong module, or even from a module that doesn't exist in the used `DefMap`.
bors r+
> Update `original_module` when ascending `DefMap`s

- crates/project_model/src/build_data.rs
- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/lib.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/op_queue.rs
- crates/rust-analyzer/src/reload.rs
- docs/dev/lsp-extensions.md
- editors/code/src/ctx.ts
- editors/code/src/lsp_ext.ts
cc #7328
[Edit] 
~~Finding a way to know when the workspace and build data are loaded...~~
[Edit 2] 
Not perfect solution, but seem to work now.
> Async loading for outdir and proc-macro

- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
Apparently we were using the crate's root file instead of the file
containing the block.
bors r+
> Fix incorrect `FileId` and remove broken shortcut

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
Fixes #7501
Since `ItemTree` builds the `RawAttrs` directly we need the special check here as I don't think we can fix this in `RawAttrs` constructor as its solely AST based and we need to touch two different ASTs here.
This just made me realize that `attrs_query` suffers from a similar problem, for example hovering an outline `mod` decl won't show inner docs, only outer ones, #7503.
> Honor #![macro_use] in mod source files

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/expr.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_ty/src/infer/expr.rs
This makes `lower_block` update the `DefMap` and `ModuleId` used by the expander to the corresponding `block_def_map`. This cleans up a bit of code, but doesn't expose any new features.
bors r+
> Use block_def_map in body lowering

- crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
I've noticed that there are various suggestions that rust-analyzer seems to filter out, even if they make sense.
Here's an example of where it seems like there should be a suggestion, but there isn't:
It turns out that this specific suggestion is not considered `MachineApplicable`, which are the only suggestions that rust-analyzer accepts. However if you read the documentation for `MachineApplicable`,
[Source](https://github.com/rust-lang/rust/blob/b3897e3d1302391ed02efbac1dce8073646b8173/compiler/rustc_lint_defs/src/lib.rs#L27-L29)
```rust
/// The suggestion is definitely what the user intended. This suggestion should be
/// automatically applied.
MachineApplicable,
```
then you realize that these are specifically only those suggestions that rust-analyzer could even automatically apply …
> Don't filter code suggestions on Applicability

- crates/ide/src/display/short_label.rs
Closes #7511 
Display underlying type in the tooltip:
```rust
pub type SomeAlias = f64
```
instead of:
```rust
pub type SomeAlias
```
> Show alias underlying type

- Cargo.lock
- crates/proc_macro_srv/Cargo.toml
- crates/proc_macro_srv/src/dylib.rs
`cargo audit` complains that `memmap` is unmaintained so switch to
RazrFalcon's maintained version.
Removes yet another edge on winapi
> Use non-deprecated memmap2 crate

- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/path_resolution.rs
They resolve to the crate root, not the DefMap's root module (which
can be a block)
bors r+
> Fix resolution of `crate` paths from within blocks

- docs/dev/architecture.md
- docs/dev/lsp-extensions.md
- docs/dev/style.md
- docs/dev/syntax.md
Also adds a line for `crates/cfg` and `crates/stdx` to the architecture.
bors r+
> Fix spelling mistakes in docs/dev

- crates/mbe/Cargo.toml
How do I prevent this happening in the future by doing something in the CI? IIRC this is the second time.
> Make sure normal dependencies always have version

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/expr.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_ty/src/infer/expr.rs
After https://github.com/rust-analyzer/rust-analyzer/pull/7380 and https://github.com/rust-analyzer/rust-analyzer/pull/7506 both had to be reverted, this should have finally resolved all remaining bugs.
Most importantly, the optimization to skip `block_def_map` computation when the block contains no inner items was fixed (which fortunately was simpler than expected).
I've ran `analysis-stats` on libstd locally, which works fine, and also ran this PR locally for a short while without issues.
Note that this *still* has no (or almost no) user-facing impact, because the rest of r-a still relies on some local item support hacks.
bors r+
> Use block_def_map in body lowering (third time's the charm)

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
It already stores the DefMap containing the module, so having
a full ModuleId is unnecessary and makes it easier to mix things up
bors r+
> Expander: store a LocalModuleId, not ModuleId

- crates/hir_def/src/adt.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
This reduces the memory used by `ItemTreeQuery` by ~20%. As it turns out, `TypeRef` is very heavy, and is used a lot in `ItemTree`:
* Many types are frequently repeated throughout the same file. This is what this PR addresses by storing identical `TypeRef`s only once per `ItemTree`.
* The vast majority of `TypeRef` consist of a plain path with only a single element. "Type anchors" like in `<Ty>::func` are used incredibly rarely, and even multi-segment paths are much rarer than single-segment paths.
> Intern `TypeRef`s in the containing `ItemTree`

- crates/assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/completion/src/completions/flyimport.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/item.rs
- crates/completion/src/render.rs
- crates/completion/src/render/enum_variant.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/path.rs
- crates/hir_def/src/resolver.rs
- crates/hir_def/src/visibility.rs
- crates/hir_ty/src/infer.rs
- crates/ide_db/src/helpers.rs
- crates/rust-analyzer/src/handlers.rs
This lets us switch out the `Vec` for something more efficient
bors r+
> Make `ModPath`'s representation private

- crates/assists/src/handlers/extract_function.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
This PR adds `extract function/method` assist. closes #5409.
Assist should support extracting from expressions(`1`, `2 + 2`, `loop { }`) and from a series of statements, e.g.:
```rust
foo();
$0bar();
baz();$0
quix();
```
Assist also supports extracting parameters, like:
```rust
fn foo() -> i32 {
let n = 1;
$0n + 1$0
}
// -
fn foo() -> i32 {
let n = 1;
fun_name(n)
}
fn fun_name(n: i32) -> i32 {
n + 1
}
```
Extracting methods also generally works.
Assist allows referencing outer variables, both mutably and immutably, and handles handles access to variables local to extracted function:
```rust
fn foo() {
let mut n = 1;
let mut m = 2;
let mut moved_v = Vec::new();
let mut ref_mut_v = Vec::new();
$0
n += 1;
let k = 1;
moved_v.push(n);
let r = &mut m;
ref_mut_v.push(*r);
let h = 3;
$0
n = …
```
> Extract function assist

- crates/hir_def/src/nameres/path_resolution.rs
This caused associated item lookup to fail when modifying `resolver.rs` to handle block expressions with inner items.
bors r+
> Fix merging of `segment_index` in path resolution

- crates/assists/src/handlers/generate_enum_match_method.rs
- crates/assists/src/handlers/generate_new.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests/generated.rs
- crates/assists/src/utils.rs
This adds a `generate_enum_match` assist, which generates `is_` variants for enums (e.g. `Option::{is_none,is_some}` in std). This is my first attempt at contributing to Rust-Analyzer, so I'm not sure if I've gotten everything right. Thanks!
**Input**
```rust
pub(crate) enum Variant {
Undefined,
Minor, // cursor here
Major,
}
```
**Output**
```rust
pub(crate) enum Variant {
Undefined,
Minor,
Major,
}
impl Variant {
pub(crate) fn is_minor(&self) -> bool {
matches!(self, Self::Minor)
}
}
```
I made this as a stepping stone for some of the more involved refactors (e.g. #5944). I'm not sure yet how to create, use, and test `window.showQuickPick`-based asssists in RA. But once that's possible, it'd probably be nice to be able to generate match methods in bulk through the quickpick UI rather …
> add `generate_enum_match` assist

- crates/assists/src/handlers/generate_enum_match_method.rs
- crates/assists/src/tests/generated.rs
Implements a small extension to https://github.com/rust-analyzer/rust-analyzer/pull/7562, generating default comments. I wasn't sure if this would fit the goals of Rust-Analyzer, so I chose to split it into a separate PR. This is especially useful when writing code in a codebase which uses `#![warn(missing_docs)]` lint, as many production-grade libraries do.
The comments we're generating here are similar to the ones found on [`Option::is_some`](https://doc.rust-lang.org/std/option/enum.Option.html#method.is_some) and [`Result::is_err`](https://doc.rust-lang.org/std/result/enum.Result.html#method.is_err). I briefly considered only generating these for `pub` types, but they seem small and unobtrusive enough that they're probably useful in the general case. Thanks!
__input__
```rust …
```
> Add doc gen to the `generate_enum_match_method` assist

- Cargo.lock
- crates/hir_ty/src/diagnostics.rs
- crates/hir_ty/src/diagnostics/decl_check.rs
- crates/stdx/Cargo.toml
> Cleanup decl_check

- crates/ide/src/syntax_highlighting.rs
There have been a few issues about/containing spurious syntax highlighting panics, which all seem to come from the `rust_analyzer::handlers::handle_semantic_tokens_range` request, which I believe this to be the cause of as the text range we want to highlight here is currently potentially smaller than that of the covering element, so we might highlight something that is inside the covering element, but outside of the text range we wish to highlight causing the assert to fail.
Unfortunately this isn't really easy to test since I have yet to find a reproducible cause(#7504 doesn't work for me cause I can't seem to checkout the given commit).
See #7504, #7298, #7299 and #7416, all of those contain an assertion failure in syntax highlighting, but only in the range request.
> Widen Highlights root range to covering element

- crates/assists/src/assist_context.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/test_db.rs
- crates/hir_ty/src/diagnostics.rs
- crates/proc_macro_api/src/rpc.rs
- crates/test_utils/src/fixture.rs
I noticed when running clippy through RA that there are a few instances where `clone` is called where it's not actually needed. I figured a small patch to remove these might be welcome here.
Thanks!
> Remove various redundant clones

- docs/dev/debugging.md
- xtask/src/install.rs
Use `npm ci` instead of `npm install`. `npm install` will overwrite
the lock file if you have a newer npm version than the one that
generated the package-lock.json
> Do not overwrite lock file

- crates/assists/src/handlers/generate_enum_match_method.rs
- crates/assists/src/handlers/generate_new.rs
- crates/assists/src/utils.rs
This is another continuation of https://github.com/rust-analyzer/rust-analyzer/pull/7562, introducing a small util to either find an `impl` block, or create a new one if none exists. I copied this code from the `generate_new` assist into https://github.com/rust-analyzer/rust-analyzer/pull/7562, and this unifies both into a helper.
It doesn't feel super polished in its current state, but my hope is that this is enough of a starting point that it can be expanded on later. For example something that would be useful would be a flag which either returns the index of the start of the block, or the end of the block.
Anyway, I hope this is useful. Thanks!
> Add `find_or_create_impl_block` to assist utils

- docs/user/manual.adoc
This request contains two related but independent changes.
The first explains `rust-analyzer` initial configuration over LSP.
The second - adds documentation on `vim-lsp` Vim plugin and provides an example of the initial configuration for `rust-analyzer` when using this particular LSP client.
Let me know if you would prefer the changes to be reviewed in two separate pull requests.
>  Documentation: Explain how initial configuration is sent over LSP and document vim-lsp

- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/cli/ssr.rs
For projects using rust-analyzer as a library it is desirable to be able to provide a custom-config to `fn load_cargo(…)` to pass features, etc, rather than having to copy & paste `fn load_cargo(…)` into one's project and maintain a fork of it and keep it in sync with upstream.
> Add `config: &CargoConfig` parameter to `fn load_cargo(…)`

- xtask/src/release.rs
to hopefully fix this:
```
$ git switch master
Already on 'master'
Your branch is up to date with 'upstream/master'.
$ git fetch upstream
$ git reset --hard upstream/master
HEAD is now at 921ec4b3fca Auto merge of #81313 - LeSeulArtichaut:revert-32558, r=jyn514
$ git submodule update --recursive
Submodule path 'src/tools/rust-analyzer': checked out '1a59f75cdaa730c16a694a4294eccf6dfe6fe0ad'
$ git switch -c rust-analyzer-2021-02-08
Switched to a new branch 'rust-analyzer-2021-02-08'
$ git fetch origin
$ git reset --hard origin/release
HEAD is now at 336909b63 Merge #7587
$ git add src/tools/rust-analyzer
$ git commit "-m:arrow_up: rust-analyzer"
[rust-analyzer-2021-02-08 1774ec1a683] :arrow_up: rust-analyzer
1 file changed, 1 insertion(+), 1 deletion(-)
$ git push
fatal: The current branch …
```
> Set remote branch on xtask promote

- crates/hir_def/src/body/scope.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/resolver.rs
- crates/hir_def/src/test_db.rs
> Unleash inner item resolution to users

- crates/completion/src/completions/pattern.rs
- crates/completion/src/completions/unqualified_path.rs
- crates/completion/src/context.rs
Variant pattern completions are to be done still.
Closes #6549, at least that should address all that's left from that issue from what I can see.
> Show `Self` pattern and Self-prefixed enum-variant completions

- crates/assists/src/tests.rs
This points the source of a failed assertion to the code which called it, rather than the location within the assertion helper method. While working on https://github.com/rust-analyzer/rust-analyzer/pull/7617 I had trouble locating some failing tests, and it was only by adding these attributes during development that I was able to locate them.
This is only applied to test helpers, which means it comes at no runtime cost. And even then: I didn't experience any noticeable performance with this enabled or disabled. Mostly just a more pleasant experience debugging test failures (:
> Add #[track_caller] to assist tests

- crates/assists/src/handlers/generate_enum_match_method.rs
- crates/assists/src/handlers/generate_getter.rs
- crates/assists/src/handlers/generate_getter_mut.rs
- crates/assists/src/handlers/generate_new.rs
- crates/assists/src/handlers/generate_setter.rs
- crates/assists/src/lib.rs
- crates/assists/src/tests.rs
- crates/assists/src/tests/generated.rs
- crates/assists/src/utils.rs
This patch makes progress towards the design outlined in https://github.com/rust-analyzer/rust-analyzer/issues/5943, and includes a small refactor which closes https://github.com/rust-analyzer/rust-analyzer/issues/7607. All together this patch does 4 things:
- Adds a `generate_getter` assist.
- Adds a `generate_getter_mut` assist.
- Adds a `generate_setter` assist.
- Moves the `generate_impl_text` function from `generate_new` into `utils` (which closes #7607).
I've chosen to follow the [Rust API guidelines on getters](https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter) as closely as possible. This deliberately leaves "builder pattern"-style setters out of scope.
Also, similar to https://github.com/rust-analyzer/rust-analyzer/pull/7570 this …
> Add getter/setter assists

- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/main.ts
- editors/code/src/run.ts
> Add **Copy Run Command Line** command for vscode

- crates/rust-analyzer/src/lsp_ext.rs
- docs/dev/lsp-extensions.md
With a recent nightly (e.g. 2021-02-10) a warning comes up. This PR reorders the attributes to fix the warning.
See https://github.com/rust-lang/rust/issues/79202
> fix nightly warning `legacy_derive_helpers`

- crates/completion/src/completions/qualified_path.rs
- crates/hir/src/code_model.rs
- crates/hir/src/from_id.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/resolver.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/hover.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7642
> Primitive completion

- .github/workflows/ci.yaml
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- crates/vfs-notify/src/lib.rs
- crates/vfs/src/loader.rs
In some situations we reloaded the workspace in the tests after having reported
to be ready. There's two fixes here:
1. Add a version to the VFS config and include that version in progress reports,
so that we don't think we're done prematurely;
2. Delay status transitions until after changes are applied. Otherwise the last
change during loading can potentially trigger a workspace reload, if it contains
interesting changes.
> Fix slow tests sometimes failing

- crates/assists/src/handlers/generate_enum_match_method.rs
- crates/assists/src/handlers/generate_getter.rs
- crates/assists/src/handlers/generate_getter_mut.rs
- crates/assists/src/handlers/generate_new.rs
- crates/assists/src/handlers/generate_setter.rs
- crates/assists/src/utils.rs
Fixes #7605. This makes it so assists can use helpers to either append a method to the start or the end of an `impl` block. Thanks!
@Veykril if this is merged, perhaps it could be good to update the gif in https://github.com/rust-analyzer/rust-analyzer/pull/7617#issuecomment-776622135 ? -- this should fix the ordering issue when generating multiple methods.
> Add `find_impl_block_end` assist helper

- docs/dev/README.md
- xtask/src/release.rs
This version omits any direct pushes, and maybe even pull requests merged from the GitHub UI. But I think it makes writing the release notes easier.
> Include a commit log summary in the changelog

- .github/workflows/release.yaml
- xtask/src/dist.rs
Closes #4956.
* Artifact sample: [rust-analyzer-x86_64-unknown-linux-musl.gz](https://github.com/rust-analyzer/rust-analyzer/files/5975504/rust-analyzer-x86_64-unknown-linux-musl.gz)
* Build time: ~14m
```
$ ls -lh
-rwxr-xr-x    1 root     root       29.7M Feb 13 18:24 rust-analyzer-x86_64-unknown-linux-musl
$ ldd rust-analyzer-x86_64-unknown-linux-musl
/lib/ld-musl-x86_64.so.1 (0x7f2751f13000)
libgcc_s.so.1 => /lib/libgcc_s.so.1 (0x7f2750a78000)
libc.musl-x86_64.so.1 => /lib/ld-musl-x86_64.so.1 (0x7f2751f13000)
$ ./rust-analyzer-x86_64-unknown-linux-musl --version
rust-analyzer 63fcf65
```
I can do `aarch64-unknown-linux-musl` if it's also needed.
> Build dist-x86_64-unknown-linux-musl releases

- crates/assists/src/handlers/generate_from_impl_for_enum.rs
- crates/assists/src/tests/generated.rs
* Allows any field type. Previously it was restricted to path types, but I don't see why it couldn't apply to all other types too. (the main reason for is PR is that I'm too lazy to write out `From<&'static str>` by hand 😄)
* More correct handling for generic enums - previously it wouldn't emit generic params on the impl.
* Also accepts variants with named field.
The impl generation code got mostly copy-pasted from generate_impl assist - please tell if there's an easy way to avoid this duplication.
> Improve "Generate From impl"

- crates/ide/src/references.rs
- crates/ide_db/src/defs.rs
> Don't classify attribute macros as their path unless it's a function with the proc_macro_attribute attribute

- crates/assists/src/handlers/generate_from_impl_for_enum.rs
- crates/assists/src/handlers/generate_impl.rs
- crates/assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/assists/src/utils.rs
Follow-up to #7659: all impl generation in assists (at least what I found) is now done through `utils::{generate_impl_text, generate_trait_impl_text}`.
> refactor impl generation in assists

- crates/ide/src/references/rename.rs
- crates/syntax/src/ast/node_ext.rs
This should be the final PR in regards to rewriting rename stuff, #4290.
It addresses 3 things:
- Currently renaming import aliases causes some undesired behavior(see #5198) which is why this PR causes us to just return an error if an attempt at renaming an alias is made for the time being. Though this only prevents it from happening when the alias import is renamed, so its not too helpful.
- Fixes #6898
- If we are inside a macro file simply rename the input name node as there isn't really a way to do any of the fancy shorthand renames and similar things as for that we would have to exactly know what the macro generates and what not.
> Finalize rename infra rewrite

- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/lib.rs
- crates/project_model/src/sysroot.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
If the configured rustcSource was not set, then try to automatically
detect a source for the sysroot rustc directory.
I wasn't sure how to do it in the case of the project.json file, though.
> Automatically detect the rustc-src directory (fixes #3517)

- editors/code/src/main.ts
If path to original file contains space (I.e on code insiders, where
default data directory is ~/Code - Insiders/), then there is syntax
error evaluating src arg.
Instead pass path as str, and coerce to path back in nix expression
> Tolerate spaces in nix binary patching

- crates/assists/src/handlers/inline_local_variable.rs
- crates/ide/src/references.rs
This PR moves the filering for enum constructors to the HIR, with this unprefixed variants as well as when the enum has been renamed via use will then still show up properly.
We now walk the ast of the `NameRef` up until we find a `PathExpr`(which also handles `CallExpr` for tuple-type structs and variants already) or a `RecordExpr`. For enum search we then take the `path` out of that expression and do a resolution on it to compare it with the definition enum.
With this PR we now support searching for all constructor literals, Unit-, Tuple- and Record-Structs, Unit-, Tuple- and Record-Variants as well as Unions.
There is one shortcoming due to how the search is triggered. Unit Variants constructors can't be searched as we have no position for it to kick off the search(since a comma …
> Implement constructor usage search for almost all items

- crates/ide/src/annotations.rs
Changes
to
Sorry for missing this one in original PR. This was an issue before https://github.com/rust-analyzer/rust-analyzer/pull/7596/commits/ee049b256a7718fb346a7172a34f0fc324b3269b, and I fixed it, yet *somehow* order got reversed (to a logical one)
> Actually fix runnable order

- crates/assists/src/handlers/early_return.rs
- crates/assists/src/handlers/extract_function.rs
- crates/assists/src/handlers/generate_function.rs
- crates/assists/src/tests.rs
- crates/hir/src/code_model.rs
- crates/syntax/src/ast/make.rs
Support `return`ing from outer function, `break`ing and `continue`ing outer loops when extracting function.
Transforms
```rust
fn foo() -> i32 {
let items = [1,2,3];
let mut sum = 0;
for &item in items {
<|>if item == 42 {
break;
}<|>
sum += item;
}
sum
}
```
Into 
```rust
fn foo() -> i32 {
let items = [1,2,3];
let mut sum = 0;
for &item in items {
if fun_name(item) {
break;
}
sum += item;
}
sum
}
fn fun_name(item: i32) -> bool {
if item == 42 {
return true;
}
false
}
```
Supported variants
- break and function does not return => uses `bool` and plain if
- break and function does return => uses `Option<T>` and matches on it
- break with value and function does not return => uses `Option<T>` and if let
- break with value and function does return => uses `Result<T, U>` and matches on t
- …
> Support control flow in `extract_function` assist

- crates/ide_db/Cargo.toml
- crates/ide_db/src/apply_change.rs
Not that WASM works right now anyways...
bors r+
> Use `cfg(target_arch)` instead of a Cargo feature

- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/analysis_bench.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/cli/ssr.rs
Unfortunately in https://github.com/rust-analyzer/rust-analyzer/pull/7595 I forgot to `pub use` (rather than just `use`) the newly introduced `LoadCargoConfig`.
So this PR fixes this now.
It also:
- splits up `fn load_cargo` into a "workspace loading" and a "project loading" phase
- adds a `progress: &dyn Fn(String)` to allow third-parties to provide CLI progress updates, too
The motivation behind both of these is the fact that rust-analyzer currently does not support caching.
As such any third-party making use of `ra_ap_…` needs to providing a caching layer itself.
Unlike for rust-analyzer itself however a common use-pattern of third-parties is to analyze a specific target (`--lib`/`--bin <BIN>`/…) from a specific package (`--package`). The targets/packages of a crate can be obtained via …
> Extract `fn load_workspace(…)` from `fn load_cargo(…)`

- crates/proc_macro_srv/src/rustc_server.rs
`std::collections::Bound` has been deprecated since Rust 1.26, but due to a bug (https://github.com/rust-lang/rust/issues/82080) it never triggered a visible deprecation warning. Fixing this is being done in https://github.com/rust-lang/rust/pull/82122 , but landing that requires rustc-analyzer to build without triggering any deprecation warnings (https://github.com/rust-lang-ci/rust/runs/1911884006#step:24:19361).
> Remove use of deprecated `std::collections::Bound`

- crates/rust-analyzer/src/diagnostics.rs
Reading through the code for diagnostics and observing debug logs, I noticed
that diagnostics are transmitted after every change for every opened file,
even if they haven't changed (especially visible for files with no diagnostics).
This change avoids marking files as "changed" if diagnostics are the same to what
was already sent before. This will only work if diagnostics are always produced in
the same order, but from my limited testing it seems this is the case.
> Avoid transmitting unchanged diagnostics

- crates/hir_expand/src/name.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide_db/src/search.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/node_ext.rs
With this `search`(and 2 other modules) don't necessarily go through 3 calls of `find_node_at_offset_with_descend` to find the correct node. Also makes the code that searches for NameLikes a bit easier on the eyes imo, though that can be fixed with just a helper function as well so its not that relevant.
> Implement ast::AstNode for NameLike and move it to node_ext

- crates/hir_expand/src/name.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/node_ext.rs
This reverts commit e1dbf43cf85f84c3a7e40f9731fc1f7ac96f8979.
> Revert "Replace usage of ast::NameOrNameRef with ast::NameLike"

- crates/ide/src/extend_selection.rs
Closes #7454
This is available in LSP as `textDocument/selectionRange` and no longer exists as a stand-alone command, so we shouldn't mention it in the manual because it's confusing (it doesn't appear in `package.json`).
> Remove documentation of obsolete extend selection command

- crates/hir/src/code_model.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/method_resolution.rs
- crates/hir_ty/src/tests/traits.rs
- crates/ide/src/hover.rs
Basically we just discard the typebound for now instead when lowering to `GenericPredicate`. I think this shouldn't have any other side effects?
Fixes #7683(hopefully for real this time)
I also played around with introducing `GenericPredicate::LifetimeOutlives` and `GenericPredicate::TypeOutlives`(see https://github.com/Veykril/rust-analyzer/commit/b9d69048451a5f2e9c5a72c800369bbeef36fdcf) but that won't fix this issue(at least not for now) due to lifetime predicate mismatches when resolving methods so I figure this is a good way to fix it for now.
> Don't lower TypeBound::Lifetime as GenericPredicate::Error

- crates/assists/src/handlers/inline_local_variable.rs
Depending on the discussion in https://github.com/rust-lang/rfcs/pull/3058 this might not end up being necessary, but I think it's a reasonable change regardless.
> Stop mixing Result and Option with ? in inline_local_variable

- crates/proc_macro_srv/src/rustc_server.rs
The missing `isize` in `typed_integers` seems to just be an oversight.
Might fix: #7751
> Add isize to the list of suffixed integers in typed_integer

- crates/ide_assists/src/handlers/apply_demorgan.rs
- crates/ide_assists/src/handlers/early_return.rs
- crates/ide_assists/src/handlers/invert_if.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_assists/src/utils.rs
- crates/ide_db/src/helpers.rs
- crates/ide_db/src/helpers/famous_defs_fixture.rs
- crates/syntax/src/ast/make.rs
Closes #7694 by parenthesizing binary expressions that are negated.
> De Morgan's Law assist now correctly parenthesizes binary expressions.

- crates/hir_expand/src/name.rs
- crates/ide_assists/src/handlers/convert_for_to_iter_for_each.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
Implements one direction of #7681 
I wonder if this tries to guess too much at the right thing here. A common pattern is:
```rust
let col = vec![1, 2, 3];
for v in &mut col {
*v *= 2;
}
// equivalent to:
col.iter_mut().for_each(|v| *v *= 2);
```
I've tried to detect this case by checking if the expression after the `in` is a (mutable) reference and if not inserting iter()/iter_mut(). This is just a convention used in the stdlib however, so could sometimes be wrong. I'd be happy to make an improvement for this, but not sure what would be best. A few options spring to mind:
1. Only allow this for types that are known to have iter/iter_mut (ie stdlib types)
2. Try to check if iter/iter_mut exists and they return the right iterator type
3. Don't try to do this and just add `.into_iter()` to …
> Add convert_for_to_iter_for_each assist

- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/nameres/path_resolution.rs
Visibilities must always point into the DefMap where they are used, but in a block expression `self` resolves to the *containing* non-block module, which is in a different DefMap. Restrict visibilities accordingly, turning them into basically `pub(block)`, which Rust has no syntax for.
bors r+
> Restrict visibilities to the containing DefMap

- crates/hir/src/diagnostics.rs
- crates/hir/src/semantics.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/diagnostics.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/ide/src/diagnostics.rs
> For unresolved macros, hightlight only the last segment

- crates/base_db/src/change.rs
- crates/ide_db/src/apply_change.rs
- crates/ide_db/src/source_change.rs
- docs/dev/guide.md
(The type was renamed/moved in 8716c4cec3a05ba891b20b5f28df69d925b913ad)
> Fixed remaining references to `AnalysisChange` (now: `Change`)

- crates/hir/src/code_model.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/builtin_type.rs
- crates/hir_def/src/expr.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/op.rs
- crates/hir_ty/src/primitive.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
`TypeCtor::Int(..) | TypeCtor::Float(..) | TypeCtor::Char | TypeCtor::Bool` => `TypeCtor::Scalar(..)`, in this case we can actually just straight up use `chalk_ir::Scalar` already since its just a POD without any IDs or anything.
> Introduce TypeCtor::Scalar

- crates/hir/src/code_model.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/diagnostics/match_check.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/op.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
This removes the `ApplicationTy` variant from `Ty` bringing the representation a lot closer to chalk's `TyKind`.
> Inline TypeCtor into Ty

- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/simple.rs
r? @flodiebold
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6837 according to https://github.com/rust-analyzer/rust-analyzer/issues/6837#issuecomment-787456488.
> hir_ty: use default type generic for box expressions

- crates/hir_def/src/path/lower.rs
- crates/ide/src/hover.rs
Noticed that hovering over `self` in a use tree like `use foo::bar::{self}` showing documentation and such for the current module instead of `bar`.
> Fix lowering trailing self paths in UseTrees

- crates/mbe/Cargo.toml
Apparently, dev dependencies shouldn't be versioned. This hopefully fixes publishing to crates.io.
> Use an unversioned profile dependency in mbe

- crates/hir_def/src/find_path.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7750 (but adds a bunch of FIXMEs, because a lot of this code is still wrong in the presence of inner items)
bors r+
> Fix `find_path` when inner items are present

- crates/proc_macro_srv/src/rustc_server.rs
To be honest, I don't know what it changes from a user perspective.
Internally, this fixes spans (token ids) of a `TokenStream` parsed from a string:
```rust
#[proc_macro_derive(FooDerive)]
pub fn foo_derive(item: TokenStream) -> TokenStream {
"fn foo() {}".parse().unwrap()
}
```
Previously, `TokenStream` was constructed from tokens with incremental ids (that conflicted with call-site tokens). Now they are `-1`.
> Fix proc macro TokenStream::from_str token ids

- editors/code/README.md
A lot of these are duplicated from the documentation or main README. While it's unfortunate to have duplicated information, the current VSCode page is very barebones and doesn't offer much confidence. 
This updated README offers a few more links and follows a structure similar to the official rust extension and other popular vscode extensions. The additions are, as much as possible specific to the vscode extension and not rust-analyzer as a LSP.
The note about not using the official extension is also right there at the top because that's a common issue people have when trying it out. 
I added the sponsor section since it's common in other extensions README, but I'm not sure if it's necessary
> Add more information to VSCode extenstion README

- crates/ide_assists/src/handlers/extract_variable.rs
- crates/ide_assists/src/tests.rs
- crates/ide_assists/src/utils.rs
- crates/ide_assists/src/utils/suggest_name.rs
Generate better default name in extract variable assist as was mentioned in issue #1587
(in order of declining precedence)
1. Expr is argument to a function; use corresponding parameter name
2. Expr is result of a function or method call; use this function/method's name
3. Use expr type name (if possible)
4. Fallback to `var_name` otherwise
* Should we more aggressively strip known types? E.g. we already strip `&T -> T`; should we strip `Option<T> -> T`, `Result<T, E> -> T`, and others?
* Integers and floats use `var_name` by default. Should we introduce a name, like `i`, `f` etc?
* Can we return a list and suggest a name when renaming(like IntelliJ does)?
* Should we add counters to remove duplicate variables? E.g. `type`, `type1`, type2`, etc.
> Suggest name in extract variable

- crates/hir_def/src/find_path.rs
`Struct` cannot be named at all in that position, since `super` doesn't
resolve to the block scope
bors r+
> Remove incorrect broken test

- crates/hir/src/code_model.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/diagnostics/match_check.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
It's a bit unfortunate that we got two AdtId's now(technically 3 with the alias in the chalk module but that one won't allow pattern matching), one from hir_def and one from chalk_ir(hir_ty). But the hir_ty/chalk one doesn't leave hir so it shouldn't be that bad I suppose. Though if I see this right this will happen for almost all IDs.
I imagine most of the intermediate changes to using chalk ids will turn out not too nice until the refactor is over.
> Use chalk_ir::AdtId

- crates/proc_macro_srv/src/rustc_server.rs
- crates/proc_macro_srv/src/tests/fixtures/test_serialize_proc_macro.txt
Make sure `FromStr` ignore all `TokenMap` in all cases.
bors r+
> Simplify TokenStream FromStr

- crates/ide_assists/src/handlers/generate_function.rs
This PR fixes one of the points listed by @TimoFreiberg in #3639. Specifically that all generated argument names should be converted to lower snake case. 
```rust
struct BazBaz;
fn foo() {
bar$0(BazBaz);
// ^ when triggering the assist here, you get the output below
}
// BEFORE
fn bar(BazBaz: BazBaz) ${0:-> ()} {
todo!()
}
// AFTER
fn bar(baz_baz: BazBaz) ${0:-> ()} {
todo!()
}
```
> generate_function assist: convert arg names to lower snake case

- crates/ide_assists/src/handlers/replace_string_with_char.rs
Currently it replaces escape sequence with the actual value, which is very wrong for `"\n"`.
> preserve escape sequences when replacing string with char

- crates/hir/src/code_model.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/resolver.rs
These could all be block `DefMap`s instead of crate-level `DefMap`s
bors r+
> Rename a few `crate_def_map`s to `def_map`

- crates/proc_macro_srv/src/dylib.rs
- crates/proc_macro_srv/src/proc_macro/bridge/client.rs
- crates/proc_macro_srv/src/rustc_server.rs
- crates/proc_macro_srv/src/tests/utils.rs
TokenStream holds a `tt::Subtree` but assumes its `delimiter` is always `None`. In particular, the iterator implementation iterates over the inner `token_trees` and ignores the `delimiter`.
However, `TokenStream::from_str` violated this assumption when the input consists of a single group by producing a Subtree with an outer delimiter, which was ignored as seen by a procedural macro.
`tt::Subtree` is just `pub delimiter: Option<Delimiter>, pub token_trees: Vec<TokenTree>`, so a Subtree that is statically guaranteed not to have a delimiter is just `Vec<TokenTree>`.
Fixes #7810
Fixes #7875
> Fix TokenStream::from_str for input consisting of a single group with delimiter

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/main.ts
- editors/code/src/net.ts
This patch makes vscode extension respect proxy settings when fetching release metadata and rust-analyzer binary.
> Make extension respect http proxy settings

- crates/ide_assists/src/handlers/generate_function.rs
This PR makes two changes to the generate function assist:
1. Attempt to infer an appropriate return type for the generated function
2. If a return type is inferred, and that return type is not unit, don't render the snippet
```rust
fn main() {
let x: u32 = foo$0();
//              ^^^ trigger the assist to generate this function
}
// BEFORE
fn foo() ${0:-> ()} {
todo!()
}
// AFTER (only change 1)
fn foo() ${0:-> u32} {
todo!()
}
// AFTER (change  1 and 2, note the lack of snippet around the return type)
fn foo() -> u32 {
todo!()
}
```
These changes are made as two commits, in case we want to omit change 2. I personally feel like it is a nice change, but I could understand there being some opposition.
If we are able to infer a return type, and especially if that return type is not the …
> generate_function assist: infer return type

- crates/ide_completion/src/completions/postfix.rs
> Add completion to turn x.err into Err(x)

- crates/hir/src/lib.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/render.rs
- crates/rust-analyzer/src/to_proto.rs
> Selecting `&mut foo` completion now actually inserts `&mut`

- crates/hir/src/lib.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/resolver.rs
- crates/hir_ty/src/diagnostics/decl_check.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/utils.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/7632
Instead of storing an `ItemScope` filled with inner items, we store the list of `BlockId`s for all block expressions that are part of a `Body`. Code can then query the `block_def_map` for those.
bors r+
> Remove `item_scope` field from `Body`

- Cargo.lock
- crates/proc_macro_api/Cargo.toml
- crates/proc_macro_api/src/lib.rs
- crates/proc_macro_api/src/version.rs
Signed-off-by: Jay Somedon <jay.somedon@outlook.com>
This PR is to fix #6174.
I basically
* added two methods, `read_version` and `read_section`(used by `read_version`)
* two new crates `snap` and `object` to be used by those two methods
I just noticed that some part of code were auto-reformatted by rust-analyzer on file save. Does it matter?
> Read version of rustc that compiled proc macro

- crates/ide/src/lib.rs
- crates/ide/src/ssr.rs
- crates/ide_ssr/src/from_comment.rs
- crates/ide_ssr/src/lib.rs
This PR adds an `Apply SSR` assist which was briefly mentioned in #3186. It allows writing an ssr rule as a comment, and then applying that SSR via an assist. This workflow is much nicer than the default available via `coc-rust-analyzer` when iterating to find the proper replacement.
As currently implemented, this requires the ssr rule is written as a single line in the comment, and it doesn't require any kind of prefix. Anything which properly parses as a ssr rule will enable the assist. The benefit of requiring the ssr rule be on a single line is it allows for a workflow where the user has several rules written one after the other, possibly to be triggered in order, without having to try to parse multiple lines of text and determine where one rule ends and the next begins. The benefit …
> add apply ssr assist

- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_ty/src/diagnostics.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7919
Just one more special case, how bad could it be.
bors r+
> Prefer names from outer DefMap over extern prelude

- crates/ide_ssr/src/lib.rs
@matklad 
This is a small follow up on #7874, adding user docs for the SSR assist functionality. Since most other assists aren't handled this way I wasn't sure exactly how we wanted to document this, so feel free to suggest alternatives.
> add user docs for ssr assist

- crates/ide/src/lib.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/render.rs
- crates/rust-analyzer/src/to_proto.rs
I was working on extending #3954 to apply completion scores in more places (I'll have another PR open for that soon) when I discovered that actually completion sorting was not working for me at all in `coc.nvim`. This led me down a bit of a rabbit hole of how coc and vs code each sort completion items.
Before this PR, rust-analyzer was setting the `sortText` field on completion items to `None` if we hadn't applied any completion score for that item, or to the label of the item with a leading whitespace character if we had applied any completion score. Completion score is defined in rust-analyzer as an enum with two variants, `TypeMatch` and `TypeAndNameMatch`. 
In vs code the above strategy works, because if `sortText` isn't set [they default it to the …
> Improved completion sorting

- crates/ide_assists/src/handlers/convert_iter_for_each_to_for.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
This PR resolves #7821.
Adds an assist to that converts an `Iterator::for_each` into a for loop: 
```rust
fn main() {
let vec = vec![(1, 2), (2, 3), (3, 4)];
x.iter().for_each(|(x, y)| {
println!("x: {}, y: {}", x, y);
})
}
```
becomes
```rust
fn main() {
let vec = vec![(1, 2), (2, 3), (3, 4)];
for (x, y) in x.iter() {
println!("x: {}, y: {}", x, y);
});
}
```
> Add assist to convert for_each into for loops

- crates/hir_expand/src/db.rs
- crates/mbe/src/expander.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/tt/src/lib.rs
In some cases (e.g.  #4186), mbe matching is very slow due to a lot of copy and allocation for bindings, this PR try to solve this problem by introduce a semi "link-list" approach for bindings building.
I used this [test case](https://github.com/weiznich/minimal_example_for_rust_81262) (for `features(32-column-tables)`) to run following command to benchmark:
```
time rust-analyzer analysis-stats  --load-output-dirs ./ 
```
Before this PR : 2 mins
After this PR: 3 seconds.
However, for 64-column-tables cases, we still need 4 mins to complete. 
I will try to investigate in the following weeks.
bors r+
> Speed up mbe matching in heavy recursive cases

- crates/rust-analyzer/build.rs
- editors/code/src/commands.ts
Maybe closes #7854
The version string for unreleased builds looks like this now:
```
$ rust-analyzer --version
rust-analyzer 2021-03-08-159-gc0459c535
```
Release builds should only have the tag name (`2021-03-15`).
> Improve version display

- crates/cfg/src/cfg_expr.rs
- crates/ide/src/lib.rs
- crates/ide/src/runnables.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
This adds an ability to look for tests for the item under the cursor: function, constant, data type, etc
The LSP part is bound to change. But the feature itself already works and I'm looking for a feedback :)
> Related tests

- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/diagnostics/match_check.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/op.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
Currently `Ty` just wraps `TyKind`, but this allows us to change most
places to already use `intern` / `interned`.
> Separate `Ty` and `TyKind` like in Chalk

- crates/hir_def/src/attr.rs
- crates/hir_def/src/nameres/tests/diagnostics.rs
Apparently `#[cfg_attr(cfg_expr, attr1, attr2)]` is valid, so let's add support for that.
bors r+
> Handle `cfg_attr` gating multiple attributes

- crates/rust-analyzer/src/bin/flags.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
Add `no-sysroot` flag for `rust-analyzer analysis-stats`. It is very useful for debugging propose. 
bors r+
> Add no-sysroot flag for analysis-stats

- .cargo/config
- xtask/src/flags.rs
- xtask/src/main.rs
This strips the run_clippy implementation out of xtask and replaces it by
a simple "cargo lint" alias which runs clippy with the corresponding flags.
Unfortunately  I could not name the alias "clippy" because that would lead to infinite recursion. :sweat_smile:
> xtask: replace "lint" command by a simply cargo alias

- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- rename a bunch of fields
- use `chalk_ir::FnSig`
> More Chalk adaptations

- crates/ide_completion/src/item.rs
- crates/ide_completion/src/render.rs
- crates/rust-analyzer/src/to_proto.rs
This PR provides a small completion relevance score bonus for items in local scope. The changes here are relatively minimal, since `coc` by default pre-sorts by position in file. But as we move toward fully server side sorting #7935 I think we'll want some relevance score bump for items in local scope. 
Note `let~` and `syntax` are both ahead of locals. Ultimately we may decide that `let~` is a high relevance completion given my cursor position here, but that should be done with some explicit scoring on the server side, rather than being caused by (I think) `coc` preferring shorter completions.
> increase completion relevance for items in local scope

- crates/ide/Cargo.toml
- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/unlinked_file.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6377
I'm not sure if this is the best way to do this. It will cause false positives for all `include!`d files (though I'm not sure how much IDE functionality we have for these).
> Diagnose files that aren't in the module tree

- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/handlers.rs
Not too sure how useful this is for reference search overall, but for completeness sake it should be there 
Also enables document highlighting for them.
> Enable searching for builtin types

- crates/hir/src/lib.rs
- crates/hir_expand/src/builtin_derive.rs
- crates/ide/src/join_lines.rs
- crates/ide/src/typing.rs
- crates/ide_completion/src/completions/postfix/format_like.rs
- crates/mbe/src/syntax_bridge.rs
- crates/proc_macro_api/src/version.rs
- crates/project_model/src/rustc_cfg.rs
- crates/rust-analyzer/src/lsp_utils.rs
use vec![] instead of Vec::new() + push()
avoid redundant clones
use chars instead of &str for single char patterns in ends_with() and starts_with()
allocate some Vecs with capacity to avoid unnecessary resizing
> some clippy::performance fixes

- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render.rs
Currently there are two ways completions use to determine the expected type. There is the `expected_type` field on the `CompletionContext`, as well as the `expected_name_and_type` method on the `RenderContext`. These two things returned slightly different results, and their results were only valid if you had pre-checked some (undocumented) invariants. A simple combination of the two approaches doesn't work because they are both too willing to go far up the syntax tree to find something that fits what they are looking for.
This PR makes the following changes:
1. Updates the algorithm that sets `expected_type` on `CompletionContext`
2. Adds `expected_name` field to `CompletionContext`
3. Re-writes the `expected_name_and_type` method to simply return the underlying fields from …
> Completion context expected type

- crates/ide_completion/src/render.rs
This is a minor cleanup PR following #8008. It removes the `expected_name_and_type` method on completion context in favor of using the fields. 
I thought this method was used in more places, or else it may have just made sense to make this change directly in #8008 :shrug:
> Completion context remove exact match method in favor of fields

- crates/hir/src/lib.rs
- crates/hir_ty/src/method_resolution.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/inlay_hints.rs
by allowing it to be invoked on references of names, now showing all (trait)
implementations of the given type in all crates instead of just the defining
crate as well as including support for builtin types
Example screenshot of `impl`s of Box in `log`, `alloc`, `std` and the current crate. Before you had to invoke it on the definition where it would only show the `impls` in `alloc`.
> Power up goto_implementation

- xtask/src/metrics.rs
This commit adds diesel to the continuosly run benchmark suite. Diesel
heavily relies internally on macro generated code. Additionally there
are lots of complicated trait releations used as part of their API.
Therefore this benchmark will be quite sensitive to:
* Performance related changes in the macro expanding code
* Performance related changes while resolving trait bounds
CC #7950
cc @lnicola
> Add diesel to the benchmark suite

- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/function.rs
This PR improves completion sorting for functions and methods. Related to #7935.
The methods are being sorted by `coc` by closeness in file. 
Notice `bbb()` on top (type + name match), followed by `ddd()` (type match).
> improved completion sorting for functions and methods

- crates/hir_def/src/diagnostics.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/diagnostics.rs
1. Use a built in macro in such a way that rust-analyzer fails to expand it. For example:
**lib.rs**
```
include!("<valid file but without a .rs extension so it is not indexed by rust-analyzer>");
```
2. rust-analyzer highlights the macro call and says the macro itself cannot be resolved even though include! is in the standard library (unresolved-macro-call diagnostic).
3. No macro-error diagnostic is raised.
**Root cause for incorrect unresolved-macro-call diagnostic:**
1. collector:collect_macro_call is able to resolve include! in legacy scope but the expansion fails. Therefore, it's pushed into unexpanded_macros to be retried with module scope.
2. include! fails at the resolution step in collector:resolve_macros now that it's using module scope. Therefore, it's …
> Fix incorrect diagnostics for failing built in macros

- crates/hir/src/lib.rs
- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/function.rs
This resolves #7842 by updating the detail for function completions from `-> T` to `fn(T, U) -> V`. I added an expicit unit test for this, `ide_completion::render::fn_detail_includes_args_and_return_type`, which passes.
Lots of other unit tests fail (~60 of them) due to this change, although I believe the failures are purely cosmetic (they were testing the exact format of this output). I'm happy to go update those tests, but before I do that I'd like to make sure this is in fact the format we want for the detail?
edit - I realized `UPDATE_EXPECT=1 cargo test` automatically updates `expect!` tests. Big :+1: to whoever worked on that! So I'll go ahead and update all these tests soon. But I still would like to confirm `fn(T, U) -> V` is the desired content in the `detail` field.
> show function params in completion detail

- xtask/src/metrics.rs
I gave it a try to add the hash as described in #8031 
Feel free to tell me if there is something I could improve.
> Add perf_revision to benchmark results

- crates/hir_def/src/body.rs
- crates/hir_def/src/body/diagnostics.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/diagnostics.rs
- crates/hir_def/src/lib.rs
- crates/hir_expand/src/eager.rs
This was an issue I found while working on https://github.com/rust-analyzer/rust-analyzer/pull/7970.
1. Call a non-existent macro in a function body.
```
fn main() {
foo!();
}
```
2. No diagnostics are raised. An unresolved-macro-call diagnostic is expected.
3. If the macro call is instead outside of the function body, this works as expected.
I believe this worked previously and regressed in https://github.com/rust-analyzer/rust-analyzer/pull/7805.
**Behavior prior to https://github.com/rust-analyzer/rust-analyzer/pull/7805:**
- The unresolved-macro-call diagnostic did not exist. Instead, a macro-error diagnostic would be raised with the text "could not resolve macro [path]".
- This was implemented by adding an error to the error sink …
> Fix missing unresolved macro diagnostic in function body

- crates/hir_def/src/body/lower.rs
- crates/hir_ty/src/diagnostics/expr.rs
This resolved the issue reported in this comment: https://github.com/rust-analyzer/rust-analyzer/issues/5649#issuecomment-789424608
bors r+
> Handle `#[cfg]` on call arguments

- crates/hir_def/src/attr.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/runnables.rs
- crates/ide_completion/src/lib.rs
- crates/ide_db/src/call_info.rs
- crates/ide_db/src/call_info/tests.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/ast/traits.rs
Moves doc string processing to `Attrs::docs`, as we need the indent info from all comments before being able to know how much to strip
Closes #7774
> Better handling of block doc comments

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/diagnostics.rs
"load out dirs from check" is enabled by default now, but better late than never I guess.
bors r+
> Fix "unset `OUT_DIR`" diagnostic when using it in item position

- crates/hir_expand/src/builtin_derive.rs
This moves them closer to the builtin_macro tests
bors r+
> Create AstId for builtin_derive macro in tests

- crates/hir/src/has_source.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_derive.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
This makes it clearer (in the type definition) which macros have or don't have an `AstId`
bors r+
> Make MacroDefId's `AstId` mandatory when possible

- crates/hir/src/has_source.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/display/navigation_target.rs
- crates/ide/src/hover.rs
- crates/ide_completion/src/render/macro_.rs
Point `HasSource` to the `ast::Fn`, and go to it in `TryToNav`.
bors r+
> Store an `AstId` for procedural macros

- crates/hir_def/src/lib.rs
> Document fields of `ModuleId`

- crates/hir_def/src/builtin_attr.rs
We also have to know about these to resolve them
bors r+
> Add builtin macro-like attributes

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/mod_resolution.rs
> Fix handling of `#![cfg]` in outline module file

- crates/hir/src/has_source.rs
- crates/hir_def/src/attr.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
> Return `Either` from `MacroDefId::ast_id`

- crates/hir/src/attrs.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/db.rs
- crates/ide/src/syntax_highlighting/inject.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/node_ext.rs
This adds `AttrsWithOwner`, which can construct an accurate `AttrSourceMap` without requiring additional information from the caller.
r? @Veykril
> Revamp `hir_def` attribute API

- crates/hir_ty/src/display.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
Chalk doesn't have it, and judging from the removed code, it wasn't useful anyway.
> Remove WhereClause::Error

- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/chalk_cast.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
This includes starting to make use of Chalk's `Cast` trait.
> Turn Obligation into something similar to chalk_ir::DomainGoal

- crates/ide_assists/src/handlers/add_lifetime_to_type.rs
- crates/ide_assists/src/handlers/add_turbo_fish.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/tests/rust-analyzer/main.rs
>  Don't return a SourceChange on WillRenameFiles when nothing gets refactored

- crates/ide/src/syntax_highlighting/inject.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render.rs
- crates/ide_db/src/call_info.rs
- crates/syntax/src/ast/node_ext.rs
> Don't use an untyped String for ActiveParam tracking

- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/completions/lifetime.rs
- crates/ide_completion/src/completions/pattern.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/lib.rs
This adds basic lifetime completion, basic in the sense that the completions for lifetimes are only shown when the user enters `'` followed by a char. Showing them when nothing is entered is kind of a pain, as we would want them to only show up where they are useful which in turn requires a lot of tree traversal and cursor position checking to verify whether the position is valid for a lifetime. This in itself doesn't seem too bad as usually when you know you want to write a lifetime putting `'` to ask for lifetime completions seems fine.
~~I'll take a look at whether its possible to lift the restriction of having to put a char after `'`.~~ This actually already works so I guess this is the clients responsibility, in which case VSCode doesn't like it.
> Add basic lifetime completion

- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/subtree_source.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests/expand.rs
- crates/mbe/src/tests/rule.rs
- crates/mbe/src/tt_iter.rs
- crates/proc_macro_srv/src/rustc_server.rs
In rustc and proc-macro2, a bare `_` token is parsed for procedural macro purposes as `Ident` rather than `Punct` (see https://github.com/rust-lang/rust/pull/48842). This changes rust-analyzer to match rustc's behavior and implementation by handling `_` as an Ident in token trees, but explicitly preventing `$x:ident` from matching it in MBE.
proc macro crate:
```rust
#[proc_macro]
pub fn input(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
dbg!(input)
}
```
test crate:
```rust
test_proc_macro::input!(_);
```
output (rustc):
```rust
[test-proc-macro/src/lib.rs:10] input = TokenStream [
Ident {
ident: "_",
span: #0 bytes(173..174),
},
]
```
output (rust-analyzer before this change):
```rust
[test-proc-macro/src/lib.rs:10] input = TokenStream [
Punct {
ch: '_',
spacing: Joint, …
```
> Make bare underscore token an Ident rather than Punct in proc-macro

- crates/hir_ty/src/autoderef.rs
- crates/ide_assists/src/handlers/qualify_path.rs
- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/lib.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_db/src/items_locator.rs
Part of https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/autoimport.20weirdness
Removes all flyimport completions for any unqualified associated type, effectively reverting https://github.com/rust-analyzer/rust-analyzer/pull/8095 
I've explained the reasoning in the corresponding FIXME and open to discussions.
As an alternative way, we could add yet another parameter in the method that's used by the `qualify_path` and enable it for the qualify assists only.
> Do not display unqualified assoc item completions

- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/lib.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_db/src/items_locator.rs
- crates/ide_db/src/symbol_index.rs
For now, last actionable part of https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Fwg-rls-2.2E0/topic/autoimport.20weirdness
Should help https://github.com/rust-analyzer/rust-analyzer/issues/7902
Now during the flyimport completion, if the input is searched case-sensitively, if the input contains any non-lowercase letters; otherwise the lookup done as before, case-insensitively.
> Do smart case fuzzy search during flyimports

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8120
> Expand legacy-scoped macro during collection

- crates/ide_completion/src/completions/lifetime.rs
- crates/ide_completion/src/context.rs
- crates/rust-analyzer/src/caps.rs
Fixes having to type a character after `'` to complete lifetimes and labels
> Add `'` to trigger_characters, allowing more direct lifetime completions

- crates/hir/src/lib.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/traits/chalk.rs
This allows us to handle more cases without a query cycle, which includes certain cases that rustc accepted. That in turn means we avoid triggering salsa-rs/salsa#257 on valid code (it will still happen if the user writes an actual cycle).
We actually accept more definitions than rustc now; that's because rustc only ignores bindings when looking up super traits, whereas we now also ignore them when looking for predicates to disambiguate associated type shorthand. We could introduce a separate query for super traits if necessary, but for now I think this should be fine.
> Ignore type bindings in generic_predicates_for_param (fix panic on ena and crates depending on it)

- crates/hir_def/src/nameres/mod_resolution.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/lib.rs
- crates/hir_ty/src/tests/macros.rs
This PR should fix #7846. It mostly follows the instructions from @edwin0cheng in that issue.
> Correct the paths of submodules from the include! macro

- crates/ide_db/src/helpers/insert_use.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/to_proto.rs
Note that we still need hir for cli.
bors r+
> Reexport PrefixKind to remove deps of hir for non-cli part of rust-analzyer crate

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- crates/hir_ty/src/utils.rs
This introduces a bunch of new binders in lots of places, which we have to be careful about, but we had to add them at some point. There's a lot of skipping of the binders; once we're done with the Chalk move, we should review the remaining ones.
> Introduce QuantifiedWhereClause and DynTy analogous to Chalk

- crates/ide/src/lib.rs
- crates/ide/src/move_item.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
Closes #6823
https://user-images.githubusercontent.com/14003886/111331579-b4f43480-8679-11eb-9af0-e4dabacc4923.mp4
Implementation issues:
> Item movers

- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/function.rs
This PR implements a temporary workaround for #8058 by disabling ref match completions for struct fields and methods. Disabling this doesn't break any existing functionality (that I am aware of) since these completions were broken.
I plan to keep working on a real fix for the underlying issue here, but I think a proper fix could take some time, so I'd prefer to quickly fix the bug to buy some more time to implement a better solution (which would ultimately allow re-enabling ref matches for struct fields and methods).
> temp disable broken ref match completions for struct fields/methods

- crates/base_db/src/input.rs
- crates/hir/src/lib.rs
- crates/ide_db/src/search.rs
By including the crate itself, we make the resulting set closed with
respect to `transitve_reveres_dependencies` operation, as it becomes a
proper transitive closure. This just feels more proper and mathy.
And, indeed, this actually allows us to simplify call sites somewhat.
> Compute more mathematically well-rounded notion of transitive deps

- crates/proc_macro_api/src/msg.rs
- crates/proc_macro_api/src/process.rs
- crates/proc_macro_srv/src/cli.rs
- crates/rust-analyzer/tests/rust-analyzer/main.rs
> Ignore proc-macro stdout to prevent IPC crash

- crates/proc_macro_api/src/rpc.rs
This PR try to trim down the json of proc macro IPC by ignoring token id if it equals to `TokenId::unspecifed`. 
Test by following commands:
```bash
$ git clone https://github.com/gluon-lang/lsp-types.git  
$ cd lsp-types
$ export RA_LOG="proc_macro_api=debug"
$ rust-analyzer -q analysis-stats --load-output-dirs --with-proc-macro . 2> debug.log
$ cat debug.log | awk '/^\[DEBUG proc_macro_api::msg\] >/ {print substr($0,31)}' >expand.log
$ stat -c "%s" expand.log
```
Before: 37576726
After: 28551718
So it trimed down 25%.  
bors r+
> Trim down IPC json size

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8175
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/3138
> Limit the hints size by default

- crates/hir_expand/src/lib.rs
- crates/ide/src/annotations.rs
1. Define a struct through a macro (can be via `macro_rules`, proc macro, or `include!()`).
2. !!MISSING: command!! annotation appears. Clicking on it results in an error message. No matter where the macro is called/defined, the annotation is always at the start of the file.
**Cause:**
- For struct `A`, a `HasImpls` annotation is added just like for struct `B`. Unlike `B`, the file id for `A` is not the file we are adding annotations to but a macro file.
- The resolving step of the code lens does not succeed.
**Fix:**
- Check that the files match before computing offsets and adding `HasImpls`/`HasReferences` annotations.
> Fix missing command error with macros

- crates/hir/src/lib.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/enum_variant.rs
- crates/ide_completion/src/render/function.rs
- crates/rust-analyzer/src/to_proto.rs
This PR improves completion relevance scoring for generic types, in cases where the types could unify. 
changelog feature improve completions
> completion relevance consider if types can be unified

- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/expr.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_expand/src/db.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/macros.rs
This PR attempts to properly handle macro statement expansion by implementing the following:
1.  Merge macro expanded statements to parent scope statements.
2.  Add a new hir `Expr::MacroStmts` for handle tail expression infer.
PS : The scope of macro expanded statements are so strange that it took more time than I thought to understand and implement it :(
Fixes  #8171
> Fix recursive macro statements expansion

- docs/user/manual.adoc
Closes #7860
bors r+
changelog fix mention the `rustup` version in the installation instructions.
> Mention the rustup version in the manual

- crates/ide/src/diagnostics/unlinked_file.rs
When there is a `lib.rs` and `main.rs` in one crate, one usually wants the `lib.rs` file to declare the modules.
bors r+
> Prefer adding `mod` declaration to lib.rs over file.rs in UnlinkedFile fix

- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/hir_ty/src/tests/macros.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/file_structure.rs
- crates/ide/src/hover.rs
- crates/ide/src/move_item.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/inject.rs
- crates/ide/src/syntax_highlighting/macro_.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/symbol_index.rs
- crates/syntax/src/ast/node_ext.rs
- crates/syntax/src/parsing/text_tree_sink.rs
Turn out it is quite straight forward :)
r @jonas-schievink
> Basic support macro 2.0

- crates/ide/src/diagnostics.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8215, at least on VS Code
> Don't mark unlinked file diagnostic as unused

- README.md
rust-analyzer is not very experimental anymore, so let's drop that.
bors r+
> README: drop "experimental"

- crates/hir_ty/src/infer/expr.rs
We have a bug where type-checking `per_query_memory_usage` takes a
couple of seconds. It also reveals another bug: our type inference is
not cancellable.
> internal: ensure that runaway type-inference doesn't block the main loop

- crates/ide/src/goto_definition.rs
- crates/ide_db/src/defs.rs
Previously `Iterator<Whoops$0 = ()>` would go to the `Iterator` trait. This fixes that and correctly marks `Whoops` as unresolved.
bors r+
> More accurately classify assoc. types in paths

- crates/ide/src/hover.rs
- crates/ide/src/move_item.rs
> Item movers improvements

- crates/hir_def/src/path/lower.rs
- crates/hir_ty/src/tests/traits.rs
We reverse the segments and generic args of the lowered path after building it, this wasn't accounted for when inserting the self parameter in `Type as Trait` segments.
Fixes #5886
> Fix generic arguments being incorrectly offset in qualified trait casts

- crates/ide/src/annotations.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/extend_selection.rs
- crates/ide/src/file_structure.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/goto_type_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/join_lines.rs
- crates/ide/src/matching_brace.rs
- crates/ide/src/move_item.rs
- crates/ide/src/parent_module.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide/src/runnables.rs
- crates/ide/src/status.rs
- crates/ide/src/syntax_tree.rs
- crates/ide/src/typing/on_enter.rs
- crates/ide/src/view_hir.rs
- crates/ide_assists/src/handlers/auto_import.rs
- crates/ide_completion/src/completions/postfix/format_like.rs
- crates/ide_completion/src/lib.rs
- crates/ide_db/src/apply_change.rs
For #6539
This includes most of gif or screenshot examples of most items in the "Features" header. With the exceptions of:
- **On Typing Assists** - couldn't get it to work for a demo, I'm probably missing something?
- **Structural search and replace** - looked to be already a visual example of the feature
- **Workspace symbol** - wasn't sure how best to show this, all of the examples maybe? Also wasn't sure of the best code example to show it off
- **Semantic Syntax Highlighting** - seemed obvious enough to not need a screenshot, but I could easily add this
All the gifs/pngs are hosted in this [comment](https://github.com/rust-analyzer/rust-analyzer/issues/6539#issuecomment-809574840). Please let me know if any of them aren't suitable (and why) and I'll improve it! Or if you don't like …
> Adding gifs and screenshots for features in manual

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/typing.rs
Related  #8267,#6539. Gifs are [here](https://github.com/rust-analyzer/rust-analyzer/issues/6539#issuecomment-809574840)
Finishing up the last PR,  for the last two features that didn't have a visual example. 
For syntax highlighting, I wasn't able to find a theme that displayed the difference between an enum and struct, but I only tried a few apart from the default so there could be one out there! 
e.g., with the default light theme, `Ord` and `Ordering` in `use std::cmp::{Ord, Ordering}` had the same highlight colour. So I just went with displaying `mut` items being underlined.
> Adding a few more gifs and screenshots for features in manual

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/lower.rs
- crates/ide/src/hover.rs
- crates/ide_completion/src/completions/qualified_path.rs
Prior we were only resolving paths until the first type was found, then discarding the result if the path wasn't fully consumed. That of course causes associated types to not resolve. Fixes #5003
> Resolve associated types

- crates/rust-analyzer/src/diagnostics/test_data/handles_macro_location.txt
- crates/rust-analyzer/src/diagnostics/test_data/macro_compiler_error.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
Try to mirror rustc diagnostics more closely by:
* Emitting hint-level diagnostics at *all* macro invocation sites that caused the diagnostic
* Previously we emitted a copy of the diagnostic (not at hint level) at the last macro invocation site only
* Emitting the original diagnostic inside the macro, if it was caused by a macro
* Always including related information pointing to the invocation site or the macro, respectively (the old code contained a bug that would sometimes omit it)
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8260
> Improve rustc diagnostic mapping

- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
This is just the most trivial check: If no inference variables have been updated, and there are no new obligations, we can just skip trying to solve them again. We could be smarter about it, but this already helps quite a bit, and I don't want to touch this too much before we replace the inference table by Chalk's.
Fixes #8263 (well, improves it quite a bit).
> Don't recheck obligations if we have learned nothing new

- Cargo.lock
- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir_def/Cargo.toml
- crates/hir_def/src/adt.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/intern.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/path.rs
- crates/hir_def/src/path/lower.rs
- crates/hir_ty/src/lower.rs
This saves around 50 mb when running `analysis-stats` on r-a itself. Not a lot, but this infra can be easily reused to intern more stuff.
> Reduce memory usage by using global `Arc`-based interning

- crates/hir_def/src/intern.rs
Only one upgradeable read lock can be handed out at the same time, and
we never acquire a non-upgradeable read lock, so this has no benefit
over just using a write lock in the first place.
bors r+
> Stop using an upgradeable read lock in interning

- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/name.rs
- crates/hir_expand/src/quote.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/tests/expand.rs
- crates/mbe/src/tt_iter.rs
Includes a minor fixup to macro 2.0 parsing.
bors r+
> Support the new `panic!()` macro

- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/chalk_cast.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/diagnostics/match_check.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
Plus some more adaptations to Substitution.
Lots of `assert_ty_ref` that we should revisit when introducing lifetime/const parameters.
> Introduce `GenericArg` like in Chalk

- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/diagnostics/match_check.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/op.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk.rs
... since that's the actual method on Chalk side that matches the signature.
> Rename Ty::interned to Ty::kind

- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- lib/arena/src/lib.rs
Especially `block_def_map` can overallocate when there's not a lot of items in the `DefMap`. This saves around 10 MB during analysis-stats. Not too much, but a cheap win.
bors r+
> Use shrink_to_fit to reduce DefMap sizes

- crates/cfg/src/tests.rs
- crates/hir_def/src/attr.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests.rs
- crates/mbe/src/tests/rule.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
It could never return `None`, so reflect that in the return type
bors r+
> Make `ast_to_token_tree` infallible

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/builder.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/op.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/utils.rs
- crates/ide/src/inlay_hints.rs
When we'll move to using `chalk_ir::Ty` (#8313), we won't be able to have our own inherent methods on `Ty` anymore, so we need to move the helpers elsewhere.
This adds a `TyBuilder` that allows easily constructing `Ty` and related types (`TraitRef`, `ProjectionTy`, `Substitution`). It also replaces `SubstsBuilder`. `TyBuilder` can construct different things based on its type parameter; e.g. if it has an `AdtId`, we're constructing an ADT type, but if it has a `TraitId`, we're constructing a `TraitRef`. The common thing for all of them is that we need to build a `Substitution`, so the API stays the same for all of them except at the beginning and end.
We also use `TyBuilder` to house various one-shot methods for constructing types, e.g. `TyBuilder::unit()`.
> Move `Ty` creation methods out of `Ty` (Chalk move preparation)

- crates/ide_assists/src/handlers/convert_into_to_from.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_db/src/helpers.rs
- crates/ide_db/src/helpers/famous_defs_fixture.rs
This adds a "Convert Into to From" assist, useful since clippy has
recently started adding lints on every `Into`.
It covers converting the signature, and converting any `self`/`Self`
references within the body.
It does assume that every instance of `Into` can be converted to a
`From`, which I _think_ is the case now.  Let me know if there's
something I'm not thinking of and I can try and make it smarter.
Closes #8196 
I'm extremely new to this codebase so please let me know if anything needs
changed.
> Add `convert_into_to_from` assist

- Cargo.lock
- crates/hir_def/Cargo.toml
- crates/hir_def/src/data.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
Bitflags is generally a good dependency -- it's lightweight, well
maintained and embraced by the ecosystem.
I wonder, however, do we really need it? Doesn't feel like it adds much
to be honest.
> Check if bitflags deps pulls its weight

- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/builder.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- crates/hir_ty/src/types.rs
- crates/hir_ty/src/walk.rs
- all the types that will be replaced by Chalk go to `types`
- `TypeWalk` impls go to `walk`
- also fix signature of `Substitution::interned`
> Move things in hir_ty into submodules

- crates/rust-analyzer/src/handlers.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8331
When the toolchain has no installable rustfmt component, running `rustfmt` complains with
```
error: the 'rustfmt' component which provides the command 'rustfmt' is not available for the 'nightly-2021-04-04-x86_64-unknown-linux-gnu' toolchain
```
Check for occurrence of "not available" in addition to the existing "not installed" to detect this case and report a user-visible error.
rustfmt and/or rustup should *really* be changed to not use the same exit status here
bors r+
> Error when `rustfmt` component is unavailable

- crates/rust-analyzer/src/bin/flags.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
This removes "noise" from memory profiles since it avoids lowering
function bodies and types
bors r+
> analysis-stats: allow skipping type inference

- crates/hir_def/src/attr.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/syntax_highlighting/inject.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/ide_db/src/defs.rs
Unfortunately involves a bit of weird workarounds due to pulldown_cmark's incorrect lifetimes on `BrokenLinkCallback`... I should probably open an issue there asking for the fixes to be pushed to a release since they already exist in the repo for quite some time it seems.
Fixes #8258, Fixes #8238
> Properly resolve intra doc links in hover and goto_definition

- crates/hir_ty/src/display.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
> Pass interner to `ProjectionTy::self_type_parameter` and `TraitRef::self_type_parameter`

- Cargo.lock
- crates/hir/Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/syntax/Cargo.toml
See: https://github.com/bluss/arrayvec/issues/182
> Use arrayvec 0.7 to avoid perf regression in 0.6.1

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/builder.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- crates/hir_ty/src/types.rs
- crates/hir_ty/src/utils.rs
- crates/hir_ty/src/walk.rs
Working towards #8313.
- hide `value`
- use `VariableKinds`
- adjust `subst` to be like Chalk's `substitute`
- also clean up some other `TypeWalk` stuff to prepare for it being replaced by Chalk's `Fold`
> Make `Binders` more like Chalk

- crates/hir_def/src/nameres/collector.rs
I was investigating some unrelated macro issue when I noticed this dead code. This legacy macro expansion logic was changed in https://github.com/rust-analyzer/rust-analyzer/pull/8128.
> Remove dead legacy macro expansion code

- crates/hir/src/lib.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits/chalk.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- crates/hir_ty/src/types.rs
Related to #8313.
Move some inherent methods that don't exist in Chalk to an extension trait, remove some others.
> Align more methods to Chalk

- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
- crates/hir_ty/src/walk.rs
- don't shift in/out for Chalk mapping (we want to have the same binders now)
- do shift in when creating the signature for a closure (though it shouldn't matter much)
- do shift in when lowering a `fn()` type
- correctly deal with the implied binder in TypeWalk
Tested with the binders validator on various repos, so I'm pretty sure this doesn't mess things up :grimacing:
> Fix shifting of binders in FnPointer

- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/lib.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/utils.rs
It stores no useful data, since we can derive all fields from
`variant_resolutions`
> infer: remove `record_field_resolutions` field

- crates/hir_ty/src/display.rs
The issue was basically that when displaying for `DisplayTarget::SourceCode` some `hir_fmt` functions would create `HirDisplayWrapper`s which would then `fmt` these triggering the Display panic since `fmt::Display` can't fail the same way as `HirDisplay`. Simple fix is to just use `hir_fmt` directly. Should probably write that down somewhere in source, looking for a good spot to put that right now.
Fixes #8077, Fixes #8370
> Don't use HirDisplayWrapper when displaying SourceCode

- crates/hir_def/src/attr.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/lib.rs
- crates/ide_db/src/apply_change.rs
Brings https://github.com/rust-analyzer/rust-analyzer/issues/8377 down to 2.52s on my machine. Not quite back to where it was before, so I'll leave that issue open for now.
bors r+
> Avoid O(n²) when constructing AttrSourceMap

- crates/ide_completion/src/completions/flyimport.rs
When only fields are relevant during record literal syntax (`Foo { field_$0 }`), RA already avoids completions of in-scope items, but with `rust-analyzer.completion.enableAutoimportCompletions` enabled, more than field names were eagerly suggested. This PR adds a case to `import_on_the_fly` to avoid the extra completions in this context.
Closes #8300
> Do not import on the fly during fields of record literal syntax

- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7550
bors r+
> Support trait impls in unnamed consts

- crates/ide/src/expand_macro.rs
When a lifetime is followed by an ident, this lead to invalid syntax. This adds a whitespace between the lifetime and the identifier.
Noticed this here: https://github.com/simrat39/rust-tools.nvim/issues/2#issuecomment-814551847
> Add space after lifetime in expand macro

- crates/rust-analyzer/src/main_loop.rs
When requests are made to rust-analyzer and the server is still loading, a response error is returned with the code `ContentModified` and text `"Rust Analyzer is still loading..."`. This error code doesn't seem to be the more appropriate for this situation. Using `ServerNotInitialized` seems better.
As this is such a small change, I have not created an issue for it.
> Return proper error code when server is loading

- crates/hir/src/lib.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/walk.rs
Almost all uses actually only care about ADT substs, so it's better to be explicit. The methods were a bad abstraction anyway since they already didn't include the inner types of e.g. `TyKind::Ref` anymore.
> Remove Ty::substs{_mut}

- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lib.rs
I'd prefer getting rid of it, but it's used in the impl search and not super easy to replace there (I think ideally the impl search would do proper unification, but that's a bit more complicated).
> Move `equals_ctor` to `TyExt`

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
This lsp-types now supports a default InsertTextMode for completion and a per-completion item commit_characters
> Bump lsp-types and syn

- crates/hir_def/src/nameres/collector.rs
You can write a custom derive that expands to itself:
```rust
#[proc_macro_derive(Derive)]
pub fn derive(item: TokenStream) -> TokenStream {
let mut out: TokenStream = "#[derive(Derive)]".parse().unwrap();
out.extend(item);
out
}
```
rustc reports a recursion limit error, but rust-analyzer used to spin in name resolution and eventually fail with "name resolution is stuck". This makes it fail fast by respecting the recursion depth of the invocation.
bors r+
> Track recursion limit when expanding custom derive

- crates/hir/src/lib.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/traits/chalk/interner.rs
- crates/hir_ty/src/traits/chalk/mapping.rs
This uses the new interning infrastructure for most type-related things, where it had a positive effect on memory usage and performance. In total, this gives a slight performance improvement and a quite good memory reduction (1119MB->885MB on RA, 1774MB->1188MB on Diesel).
> Intern lots of things

- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/regression.rs
If we get lifetime variables back in autoderef, just immediately replace them by static lifetimes for now. Method resolution doesn't really deal correctly with new variables being introduced (this needs to be fixed more properly).
This fixes `rust-analyzer analysis-stats --with-deps` crashing in the RA repo.
> Fix crash on syn involving lifetimes returned by Chalk

- crates/hir/src/lib.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits/chalk.rs
Store impls for e.g. &Foo with the ones for Foo instead of the big "other" bucket. This can improve performance and simplifies the HIR impl search a bit.
> Improve indexing of impls

- crates/ide/src/diagnostics.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8442
(the diagnostic fires intentionally on `#[cfg]`d modules, but with this won't cover the whole file)
bors r+
> Shrink `unlinked-file` diagnostic to 3 characters

- crates/hir_def/src/attr.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_derive.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/input.rs
- crates/hir_expand/src/lib.rs
- crates/hir_expand/src/proc_macro.rs
We now remove any `#[derive]` before and including the one we want to expand, in the `macro_arg` query.
The same infra will be needed by attribute macros (except we only remove the attribute we're expanding, not any preceding ones).
Part of https://github.com/rust-analyzer/rust-analyzer/issues/8434 (doesn't implement the cfg-expansion yet, because that's more difficult)
> Rewrite `#[derive]` removal code to be based on AST

- crates/hir_def/src/nameres/path_resolution.rs
Reverts the change made in https://github.com/rust-analyzer/rust-analyzer/pull/7959
We don't populate the extern prelude for block DefMaps anymore,
so this is unnecessary
bors r+
> Undo path resolution hack for extern prelude

- crates/ide_completion/src/item.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/to_proto.rs
> Use CompletionTextEdit::InsertAndReplace if supported by the client

- crates/hir_ty/src/method_resolution.rs
This condition should always be true for *valid* code, but of course
there might be invalid code or things that we can't currently resolve.
Fixes #8464.
> Remove assertion in impl collection

- crates/project_model/src/build_data.rs
- crates/rust-analyzer/src/benchmarks.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/bin/rustc_wrapper.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/cli/ssr.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/tests/rust-analyzer/main.rs
- crates/rust-analyzer/tests/rust-analyzer/support.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> feat: avoid checking the whole project during initial loading

- crates/rust-analyzer/build.rs
Closes #8239
Otherwise if we run `git describe` on the release day we pick up the `nightly` tag from the previous release.
changelog fix
bors r+
> Exclude nightly tag from git describe to fix version string

- crates/ide/src/typing/on_enter.rs
This improves on https://github.com/rust-analyzer/rust-analyzer/pull/8388 by also indenting the created block expression on enter.
> Indent block expressions on enter

- crates/ide_assists/src/handlers/extract_function.rs
```rust
fn main() {
let n = 1;
let k = n * n;
dbg!(n);
}
```
1. Select the second and third lines of the main function. Use the "Extract into function" code assist.
2. Panic occurs in debug, error is logged in release: "[ERROR ide_assists::handlers::extract_function] assertion failed: matches!(path, ast :: Expr :: PathExpr(_))".
3. Function generates successfully on release where the panic was bypassed.
```rust
fn fun_name(n: i32) {
let k = n * n;
dbg!(n);
}
```
**Cause:**
- The generated function will take `n` as a parameter. The extraction logic needs to search the usages of `n` to determine whether it is used mutably or not. The helper `path_element_of_reference` is called for each usage but the second usage is a macro call and fails the `Expr::PathExpr(_)` match …
> Fix faulty assertion when extracting function with macro call

- crates/hir_def/src/lib.rs
- crates/hir_ty/src/diagnostics/decl_check.rs
- docs/user/manual.adoc
Fix #8417. Also makes it less noisy about no_mangle annotated stuff the
user can do nothing about.
Note: this still is broken with bitfield! macros. A repro in an ignore
test is included here. I believe this bug is elsewhere, and I don't
think I can work around it here.
I would like help filing the remaining bug, as it does actually affect
users, but I don't know how to describe the behaviour (or even if it
is unintended).
> decl_check: consider outer scopes' allows

- Cargo.lock
Fixes a potential memory leak in unbound channels.
> crossbeam-channel 0.5.1

- crates/hir_ty/src/autoderef.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8503
I've added a minimal set of spans to remove `???` and showcase the underlying issue:
`db.trait_solve` reliably produces the same timings for the same input in the same place for me, despite supposedly being cached by Salsa.
In my perception, this is a bit odd, so I've decided to stop at this point and discuss it with people with better knowledge on the topic.
> internal: Add more profiling spans into type inference

- crates/ide_completion/src/completions/flyimport.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/8518
Removes autoimport suggestions for the case: 
> inside trait definitions / impls (trait Trait {$0} / impl Foo {$0}), nothing except the fn, type and const keywords (and the full item completions for trait impls) should appear (currently many types and autoimport suggestions)
> fix: Do not show flyimports in trait or impl declarations

- Cargo.lock
- xtask/src/tidy.rs
Fixes windows leak: https://github.com/notify-rs/notify/pull/298
> minor: notify 5.0.0.pre7

- crates/ide/src/move_item.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
This updates the cursor position when moving items around to stay in the same location within the moved node.
I changed the `moveItem` response to `SnippetTextEdit[]`, since that made more sense to me (the file was ignored by the client anyways, since the edits always apply to the current document). It also matches `onEnter`, which seems logical to me, but please let me know if this doesn't make sense.
There's still a bug in the client-side snippet code that will cause the cursor position to be slightly off when moving parameters in the same line (presumably we don't track the column correctly after deleting `$0`). Not really sure how to fix that immediately, but this PR should already be an improvement despite that bug.
> Move cursor position when using item movers

- crates/ide_assists/src/handlers/fill_match_arms.rs
- crates/syntax/src/ast/make.rs
This is rather a small fix addressing an issue mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/8493#issuecomment-818770670
> Assist fix: Fill match arms for a tuple of a single enum.

- crates/hir/src/lib.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/utils.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_db/src/helpers/import_assets.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/8520
I've went with a separate method approach, since the [highlighted code](https://github.com/rust-analyzer/rust-analyzer/issues/8520#issuecomment-819856337) has not`Type` and uses `Ty` to get his data, but the code I had to change has no access to `Ty` and has `Type` only.
>  fix: Do not propose inherent traits in flyimports and import assists

- crates/syntax/Cargo.toml
The different pre versions include breaking changes, which cause build failures for the users.
> nail rowan version down

- crates/base_db/src/fixture.rs
Improve the error message when folks forget to add an `$0` in one of the fixtures. Figuring this one out was 20 minutes down the drain for me, so figured I might as well make sure nobody else has to go through the same thing in the future. Thanks!
> Add an error message to fixture errors

- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests/expand.rs
Previously they were escaped twice, both by `.escape_default()` and the debug view of strings (`{:?}`). This leads to things like newlines or tabs in documentation comments being `\\n`, but we unescape literals only once, ending up with `\n`.
This was hard to spot because CMark unescaped them (at least for `'` and `"`), but it did not do so in code blocks.
This also was the root cause of #7781. This issue was solved by using `.escape_debug()` instead of `.escape_default()`, but the real issue remained.
We can bring the `.escape_default()` back by now, however I didn't do it because it is probably slower than `.escape_debug()` (more work to do), and also in order to change the code the least.
Example (the keyword and primitive docs are `include!()`d at …
> Escape characters in doc comments in macros correctly

- crates/ide/src/syntax_highlighting/inject.rs
- crates/rust-analyzer/src/markdown.rs
````
```compile_fail,E0000
```
````
The code was stolen from rustdoc at https://github.com/rust-lang/rust/blob/392ba2ba1a7d6c542d2459fb8133bebf62a4a423/src/librustdoc/html/markdown.rs#L866-L867
> Accept `E<error_number>` notation in doctests

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/name.rs
fixes https://github.com/rust-analyzer/rust-analyzer/issues/8563
bors r+
> fix: Expand `global_asm!` to nothing

- crates/hir_def/src/lib.rs
- crates/hir_def/src/visibility.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
It turns out that some proc. macros not only generate *trait* impls wrapped in `const _: () = { ... };`, but inherent impls too. Even though it is questionable whether *custom derives* should produce non-trait impls, this is useful for procedural attribute macros once we support them.
bors r+
> Support inherent impls in unnamed consts

- crates/ide_assists/src/handlers/generate_deref.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_db/src/helpers.rs
- crates/ide_db/src/helpers/famous_defs_fixture.rs
This PR adds a new `generate_deref` assist that automatically generates a deref impl for a given struct field.
Check out this gif:
--
I have a few Q's:
> Adds impl Deref assist

- crates/ide/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt
- crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
This change causes renames that happen on items coming from crates outside the workspace to fail. I believe this should be the right approach, but usage of cargo's workspace might not be entirely correct for preventing these kinds of refactoring from touching things they shouldn't. I'm not entirely sure?
cc #6623, this is one of the bigger footguns when it comes to refactoring, especially in combination with import aliases people tend to rename items coming from a crates dependency which this prevents.
> Prevent being able to rename items that are not part of the workspace

- crates/ide_assists/src/handlers/fill_match_arms.rs
Fix for #8493
However, the assist is still flaky and does not use `hir_ty::diagnostics::match_check`
> Fill match arms assist: add remaining arms for tuple of enums

- crates/ide_assists/src/handlers/introduce_named_lifetime.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ted.rs
This extends `GenericParamsOwnerEdit` trait with `get_or_create_generic_param_list` method
> Switch introduce_named_lifetime assist to use mutable syntax tree 

- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/nameres.rs
This is currently broken due to the way ItemTree stores inner items. This test serves as a reminder until this gets fixed.
bors r+
> minor: Add failing local items test

- crates/hir_def/src/item_tree.rs
> minor: Remove `ItemTree::all_inner_items`

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/flycheck/src/lib.rs
This change allows non-Cargo build systems to be used for Flycheck provided they call `rustc` with `--error-format=json` and emit those JSON messages to `stdout`.
> Flycheck tries to parse both Cargo and Rustc messages.

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Currently VSCode Problem Matchers will resolve a path like `//foo_crate/src/main.rs` if `${workspaceFolder}/foo_crate/src/main.rs` exists.  Presumably their behavior is functionally a string concatenation that would produce `${workspaceFolder///foo_crate/src/main.rs` and repeated path separators get ignored.
This PR attempts to mimic this behavior by stripping any `Component::RootDir` from `file_name` before joining it to `workspace_root`, and then checking if the file exists.  If it does, this path is used, and if not, the behavior falls through to the existing Rust path join behavior.
> Diagnostic paths support specifying `remapPrefix`

- crates/ide_assists/src/handlers/auto_import.rs
- crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ide_assists/src/handlers/reorder_fields.rs
- crates/ide_assists/src/handlers/reorder_impl.rs
- crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/lib.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
- crates/syntax/src/ast/make.rs
- crates/syntax/src/ted.rs
Unfortunately changing `insert_use` to not use `SyntaxRewriter` creates a lot of changes since so much relies on that. But on the other hand this should be the biggest usage of `SyntaxRewriter` I believe.
> Remove SyntaxRewriter usage in insert_use in favor of mutable syntax trees

- crates/rust-analyzer/build.rs
- xtask/src/dist.rs
> fix: correct version string to contain hash, build date and channel

- crates/ide/src/display/navigation_target.rs
- crates/ide/src/references/rename.rs
Attempting to rename an element of a tuple field would previously replace the type with the new name, which doesn't make sense; now it fails instead.
The check is done in both `prepare_rename` and `rename` so that the case is caught before the user is prompted for a new name. Some other existing failure cases are also now additionally checked in `prepare_rename`.
Closes: #8592
(I threw in some doc edits for a relevant type; of course, I can remove those if the policy here is to be strict about scope of changes within a PR.)
> Check more carefully for cases where a rename can't be done

- .github/workflows/release.yaml
- crates/rust-analyzer/build.rs
- xtask/src/main.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/8571
```
$ docker run -it --rm ubuntu:20.04 bash
root@7393d1e7bbad:/# date -u +%Y-%m-%d
2021-04-26
```
```
$ date -u +%Y-%m-%d
2021-04-26
$ uname -a
Darwin alaptop.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```
Some of the places where I've change this do not really require it (since macos bin would have failed with `--iso` param also), but I've changed them for consistency.
> internal: Use more cross-platform utc `date` argument

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/config.ts
- editors/code/src/inlay_hints.ts
As requested on issue #6883 this PR provides an option for users to opt out of the smaller font size for inlay hints. Part of #6883.
> Add option to opt out of smaller font size for inlay hints.

- Cargo.lock
- crates/rust-analyzer/Cargo.toml
According to the spec we should return ServerNotInitialized if the server is waiting for an initialize request and something else comes in.
Upgrading to lsp-server 0.5.1 will do this and retry until the initialize request comes in.
Fixes #8581
> Return ServerNotInitialized according to the spec

- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/tests/simple.rs
Previously, the unification of closure types is blocked by `Ty.equals_ctor` which compares the ClosureId of the closures. Here is a workaround to allow closures to unify their substitutions.
Fixes #8604.
> fix: closure unify without check ClosureId

- crates/ide/src/prime_caches.rs
- crates/rust-analyzer/src/main_loop.rs
> fix: don't duplicate Progerss::Finised for cache priming

- Cargo.lock
- crates/proc_macro_api/Cargo.toml
- crates/proc_macro_api/src/version.rs
#7522 did the same for `proc_macro_srv` before this usage of `memmap` was introduced to `proc_macro_api` in #6822 .
Something like [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny-action) could help prevent specific crates (and versions, licenses, etc) from being introduced into the crate tree, but that's unrelated to this pull request.
> Replace `memmap` with `memmap2` in `proc_macro_api`

- crates/ide_completion/src/completions/qualified_path.rs
> Complete enum variants through type aliases

- crates/ide/src/folding_ranges.rs
- crates/rust-analyzer/src/to_proto.rs
#8664 
I added a test that assert folding multi-line where clauses while leaving single lined one. Please, let me know if the code needs further improvements.
> fix for #8664: Emit folding ranges for multi-line where clauses

- crates/ide_completion/src/completions/trait_impl.rs
> fix: Do not overwrite comments and attrs in trait impl completion

- Cargo.toml
- crates/hir/src/attrs.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/find_path.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/tests/incremental.rs
- crates/hir_def/src/path.rs
- crates/hir_def/src/path/lower.rs
- crates/hir_def/src/path/lower/lower_use.rs
- crates/hir_def/src/visibility.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_ty/src/display.rs
This threads a lot more database references around in order to avoid storing a bare `TextOffset` in the hygiene info. This `TextOffset` made hygiene info and `ItemTree`s more volatile than they should be, leading to excessive recomputation of `ItemTree`s.
The incremental test added in https://github.com/rust-analyzer/rust-analyzer/pull/8721 is now passing with these changes.
closes https://github.com/rust-analyzer/rust-analyzer/pull/8721
> Don't store call-site text offsets in hygiene info

- crates/hir/src/semantics.rs
- crates/ide/src/goto_type_definition.rs
I'm unsure if the approach of lowering an `ast::Type` to a `hir::Type` is a good idea, it seems fine to me at least.
Fixes #2882
> Support goto_type_definition for types

- crates/ide/src/diagnostics.rs
- crates/syntax/src/ast/make.rs
fixes https://github.com/rust-analyzer/rust-analyzer/issues/8680
bors r+
> fix: use raw idents in `make::{name, name_ref}` when used with a keyword

- Cargo.lock
- crates/profile/Cargo.toml
- crates/rust-analyzer/Cargo.toml
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8252.
No idea if we're still interested in this but it was a simple change so here's the PR.
> Switch from jemalloc to tikv-jemalloc

- crates/rust-analyzer/src/dispatch.rs
> internal: add rust-analyzer version to panic context

- Cargo.toml
- crates/syntax/src/algo.rs
> internal: removed dead code

- crates/ide_assists/src/handlers/pull_assignment_up.rs
- crates/syntax/src/ast/make.rs
> feat: add "mentoring instructions" test for pull up assist

- crates/hir/src/lib.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/ide/src/references.rs
- crates/ide/src/references/rename.rs
- crates/ide_assists/src/handlers/convert_tuple_struct_to_named_struct.rs
- crates/ide_db/src/search.rs
> fix: Correctly support SelfType when searching for usages

- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/rustc_cfg.rs
- crates/project_model/src/workspace.rs
Implements `cargo/.config` build target and cfg access by using unstable cargo options:
- `cargo config get` to read the target triple out of the config to pass to `cargo metadata` --filter-platform
- `cargo rustc --print` to read out the `rustc_cfgs`, this causes us to honor `rustflags` and the like.
If those commands fail, due to not having a nightly toolchain present for example, they will fall back to invoking rustc directly as we currently do.
I personally think it should be fine to use these unstable options as they are unlikely to change(even if they did it shouldn't be a problem due to the fallback) and don't burden the user if they do not have a nightly toolchain at hand since we fall back to the previous behaviour.
cc #8741
Closes #6604, Closes #5904, Closes #8430, Closes #8480
> feat: Honor `.cargo/config.toml`

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/quote.rs
Fixes #8749
It is the same bug in #8560 but in our `quote!` macro. 
Because the "\\" are added exponentially in #8749 case, so the text just eat up all the memory. 
bors r+
> Escape characters in builtin macros correctly

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/incremental.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/lib.rs
This computes a macro's fragment kind eagerly (when the calling file is still available in parsed form) and stores it in the `MacroCallLoc`. This means that during expansion we no longer have to reparse the file containing the macro call, avoiding the unnecessary salsa dependencies (https://github.com/rust-analyzer/rust-analyzer/pull/8746#issuecomment-834776349).
Marking as draft until I manage to find a test for this problem, since for some reason `typing_inside_a_function_should_not_invalidate_expansions` does not catch this (which might indicate that I misunderstand the problem).
I've manually confirmed that this fixes the issue described in https://github.com/rust-analyzer/rust-analyzer/pull/8746#issuecomment-834776349:
```
7ms - parse_query @ FileId(179)
12ms - …
```
> fix: fix unnecessary recomputations due to macros

- crates/ide/src/join_lines.rs
- crates/ide_assists/src/handlers/extract_variable.rs
- crates/ide_assists/src/handlers/introduce_named_lifetime.rs
- crates/ide_assists/src/handlers/replace_impl_trait_with_generic.rs
- crates/ide_assists/src/utils/suggest_name.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
> internal: rewrite **Repalce impl Trait** assist to mutable syntax trees

- docs/user/manual.adoc
> fix: fix manual rendering

- crates/ide_assists/src/handlers/merge_imports.rs
- crates/ide_assists/src/tests.rs
- crates/ide_completion/src/test_utils.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
- crates/ide_db/src/helpers/merge_imports.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- docs/user/generated_config.adoc
- editors/code/package.json
I never really liked the variant names I gave this enum from the beginning and then I found out about rustfmt's `imports_granularity` config:
> imports_granularity
>
> How imports should be grouped into use statements. Imports will be merged or split to the configured level of granularity.
> 
>     Default value: Preserve
>     Possible values: Preserve, Crate, Module, Item
>     Stable: No
I personally prefer using `crate` over `full` and `module` over last, they seem more descriptive. Keeping these similar between tooling also seems like a good plus point to me.
We might even wanna take over the entire enum at some point if we have a `format/cleanup imports` assists in the future which would probably want to also have the `preserve` and `item` options.
> minor: Give MergeBehaviour variants better names

- crates/ide/src/lib.rs
- crates/ide/src/view_crate_graph.rs
- crates/rust-analyzer/src/handlers.rs
Addresses https://github.com/rust-analyzer/rust-analyzer/pull/8801#discussion_r630570615
bors r+
> internal: Move `dot` invocation to rust-analyzer crate

- crates/hir_expand/src/input.rs
- crates/hir_expand/src/lib.rs
This broke in https://github.com/rust-analyzer/rust-analyzer/pull/8796 (again), the fix is easy though
bors r+
> fix: Strip delimiter from fn-like macro invocations

- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
Previously, we added a dependency for all targets in a package to the package's library target. This is correct for most targets, except build scripts, which run before the library crate is built. This PR removes the incorrect dependency on the library target.
We also used to treat all dependencies the same, which led to build scripts being able to use regular dependencies as well as dev-dependencies. This is also fixed by this PR, and build scripts only depend on build-dependencies.
Incorrect dependency graph:
Fixed graph after this PR:
> fix: fix dependencies of build scripts

- crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
Fixes #6730
Still unsure if existing visibilities of fields should be forced to pub (which is what was previously done), or if it's okay to keep it in the extracted struct.
> Keep comments and attrs when extracting struct from enum variant

- crates/hir_def/src/find_path.rs
- crates/ide_assists/src/handlers/auto_import.rs
> fix: Return absolute paths in find_path if crate start is ambiguous

- crates/hir/src/lib.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
close https://github.com/rust-analyzer/rust-analyzer/issues/8633
> Apply async semantic token modifier to async/await keywords

- Cargo.toml
- crates/ide_assists/src/handlers/add_missing_impl_members.rs
- crates/ide_assists/src/handlers/generate_new.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_assists/src/utils.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/edit_in_place.rs
- crates/syntax/src/ast/make.rs
> internal: rewrite assoc item manipulaion to use mutable trees

- crates/flycheck/src/lib.rs
- crates/project_model/src/build_data.rs
Cargo commands are affected by the `.cargo/config` files above
their working directory. If cargo is invoked from above the directory
holding `Cargo.toml`, it may not pick up important settings like
registry replacements, causing it to behave differently or even fail.
Most cargo invocations are currently setting their working directories
to the directory containing `Cargo.toml`, but a couple of paths remain
in which cargo is invoked from the default workspace root instead.
This change fixes that, resolving some cargo check failures that I
experienced in a multi-root workspace in which packages used different
registries.
> Use package root as `cargo check` working directory

- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/fixes.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/edit_in_place.rs
> internal: use mutable syntax trees when filling fields

- crates/ide_assists/src/handlers/generate_default_from_new.rs
Try to close https://github.com/rust-analyzer/rust-analyzer/issues/8827
> Generate the impl block via generate_trait_impl_text_from_impl

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/rust-analyzer/tests/rust-analyzer/main.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7111
Pretty straightforward change, but open to any suggestions if there's a more recommended testing strategy than what I went with.
> Allow semantic tokens for strings to be disabled

- crates/ide/src/diagnostics.rs
- crates/ide/src/diagnostics/field_shorthand.rs
- crates/ide/src/diagnostics/fixes.rs
- crates/ide/src/diagnostics/fixes/change_case.rs
- crates/ide/src/diagnostics/fixes/create_field.rs
- crates/ide/src/diagnostics/fixes/fill_missing_fields.rs
- crates/ide/src/diagnostics/fixes/remove_semicolon.rs
- crates/ide/src/diagnostics/fixes/replace_with_find_map.rs
- crates/ide/src/diagnostics/fixes/unresolved_module.rs
- crates/ide/src/diagnostics/fixes/wrap_tail_expr.rs
- crates/ide/src/diagnostics/unlinked_file.rs
- crates/ide/src/lib.rs
close #8228
This is a draft that changes `Diagnostic` to contain multiple fixes. Pre analysis is in https://github.com/rust-analyzer/rust-analyzer/issues/8228#issuecomment-812887085 Because this solution is straightforward so I decided to type it out for discussion.
Currently the `check_fix` is not able to test the situation when multiple fixes available. <del>Also because `Insert 'mod x;'` and  `Insert 'pub mod x;'` are so similar, I don't know how to test them correctly and want some suggestions.</del>. I added 
`check_fixes` to allow checking mutiple possible fixes.
In additional, instead of append after possible existing `mod y`, I think it's possible to Insert `pub mod x;` after `pub mod y`. Should I implement this too?
> Add pub mod option for UnlinkedFile

- crates/hir_def/src/intern.rs
- crates/hir_def/src/nameres/collector.rs
Closes https://github.com/rust-analyzer/rust-analyzer/pull/7049
This should not have any observable effect, since we don't attempt to expand attribute macros yet, and I have implemented a fallback that treats items with unresolved attributes as if the attribute wasn't there.
Derive helpers are not yet resolved. `#![register_{attr,tool}]` are not yet supported.
> internal: resolve attributes in name resolution (minimal version)

- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/diagnostics/match_check.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/tests.rs
- crates/hir_ty/src/tests/patterns.rs
`InferenceResult` now records pattern type mismatches.
> fix: false positive "Missing match arm" when an or-pattern has mismatched types

- crates/hir/src/db.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_derive.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/input.rs
- crates/hir_expand/src/lib.rs
- crates/ide_db/src/apply_change.rs
- Share structures with lazy macros, make both use `MacroCallLoc`.
- Remove `intern_eager_expansion`, `EagerCallLoc`, `EagerMacroId`, and *many* matches on `MacroCallId`.
- Make a lot of FIXMEs obsolete since the code no longer distinguishes between eager and lazy macros.
- Add `EagerCallInfo`, which is `Some` for calls to eager macros and holds the argument or expansion result and the included file.
> internal: greatly simplify eager macro representation

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
`ModItem`s are per-file, so we have to track the file if we store them in the crate-level `DefCollector`.
Fixes the remaining issue in https://github.com/rust-analyzer/rust-analyzer/pull/8882#issuecomment-844379170
bors r+
> fix: fix unresolved attribute fallback again

- crates/ide_assists/src/tests.rs
- crates/ide_completion/src/test_utils.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
- crates/ide_db/src/helpers/merge_imports.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This renames our `MergeBehavior` to `ImportGranularity` as rustfmt has it as the purpose of them are basically the same. `ImportGranularity::Preserve` currently has no specific purpose for us as we don't have an organize imports assist yet, so it currently acts the same as `ImportGranularity::Item`.
We now try to guess the import style on a per file basis and fall back to the user granularity setting if the file has no specific style yet or where it is ambiguous. This can be turned off by setting `import.enforceGranularity` to `true`.
Closes https://github.com/rust-analyzer/rust-analyzer/issues/8870
> Implement import-granularity guessing 

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/diagnostics.rs
- crates/hir_expand/src/name.rs
Relatively straightforward since these are crate-local.
bors r+
> internal: support `#[register_attr]` and `#[register_tool]`

- crates/rust-analyzer/src/to_proto.rs
> fix: Fix code completion not inserting borrow text when client supports InsertAndReplace

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
The ItemTree lowering code used to attach attributes on an `extern {}` block to all the children. This is wrong and causes problems with attribute resolution that manifested as a hang.
This PR treats extern blocks as first-class items in the ItemTree and lowers its contents in the `ModCollector` instead.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8414#issuecomment-845607923
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8905
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8909
bors r+
> fix: Don't hang on unresolved attribute on extern block and its children

- crates/hir/src/lib.rs
- crates/hir_ty/src/builder.rs
- crates/hir_ty/src/chalk_db.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/interner.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/coercion.rs
- crates/hir_ty/src/tests/patterns.rs
- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/tests/simple.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/tls.rs
- crates/hir_ty/src/traits.rs
- crates/ide_completion/src/render.rs
- use Chalk's unification, get rid of our own `unify`
- rewrite coercion to not use unification internals and to be more analogous to rustc
- fix various coercion bugs
- rewrite handling of obligations, since the old hacky optimization where we noted when an inference variable changes wasn't possible anymore
- stop trying to deeply resolve types all the time during inference, instead only do it shallowly where necessary
> Use Chalk for unification

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres/collector.rs
The `Fields` enum already encodes this, so `StructDefKind` is redundant.
bors r+
> internal: remove `StructDefKind`

- crates/hir_def/src/attr.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/item_tree/tests.rs
- crates/hir_def/src/path.rs
- crates/ide/src/lib.rs
- crates/ide/src/view_item_tree.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
This adds a printer for `ItemTree` contents, and a few tests to ensure that `ItemTree` lowering works like we expect it to. It also adds a new "Debug ItemTree" command that can be used to see the `ItemTree` of the currently open file. The pretty-printed output is usually close enough to Rust syntax that we can even use Rust syntax highlighting.
This is similar to the old `ItemTree` tests we had, but produces significantly more readable output, so these should actually carry their weight.
> ItemTree pretty-printing

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8905 (again)
bors r+
> fix: fix hang caused by non-unique attribute IDs

- crates/ide_assists/src/handlers/fill_match_arms.rs
- crates/ide_assists/src/tests.rs
+ Lazy computation of missing arms.
+ Convenience function to test lazy computation: `ide_assists::tests::check_assist_unresolved`.
Fixes #8835
> fix: `fill_match_arms` hangs on a tuple of large enums

- crates/hir_ty/src/infer/unify.rs
Chalk's unification can sometimes create lifetime variables, which we
currently don't really deal with, but at least we don't want to leak
them outside of inference.
Should fix #8919.
> Resolve any lifetime variables to 'static after inference

- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/item_tree/tests.rs
Extends the ItemTree pretty printer to handle all `Path`s, and to print generic parameters and where-clauses.
bors r+
> internal: even prettier itemtrees

- editors/code/src/config.ts
- editors/code/src/main.ts
- editors/code/src/persistent_state.ts
When any nightly is downloaded, we store its GitHub release id in the local cache and never invalidate that cache.
Due to this, it was possible to do the following sequence:
* have the nightly locally
* downgrade the extension to any stable version
* observe that despite the `"rust-analyzer.updates.channel": "nightly",` setting, no nightly updates are happening
* on the next day, the actual update happens (given the new nightly is released)
Since it's impossible to install nightly version directly through the VSCode marketplace, any fiddling with dev version results in the same situation: one have to wait for the next nightly release to happen in order to restore the nightly.
This PR 
* invalidates the cache eagerly during bootstrap if the current plugin is not nightly
* enforces the …
> fix: Improve nightly downloads with better local state management

- xtask/src/dist.rs
> internal: disable debug symbols due to failing windows build

- crates/hir/src/lib.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
Hi! This is my first pull request that touches rust-analyzer itself beyond a search-and-replace, so please tell me if I should change anything or do anything differently. :)
> Give ‘unsafe’ semantic token modifier to unsafe traits

- crates/hir_def/src/type_ref.rs
> minor: explain why nested `TypeRef` aren't interned

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/lib.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/ide_assists/src/handlers/fix_visibility.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render.rs
- crates/ide_db/src/call_info/tests.rs
- crates/ide_db/src/defs.rs
Also makes call info show the correct types for generic methods.
> fix: Make expected type work in more situations

- crates/project_model/src/lib.rs
- crates/project_model/src/sysroot.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
- editors/code/src/client.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
Closes https://github.com/rust-analyzer/rust-analyzer/issues/6388
Caveats: 
* I've decided to support multiple detached files in the code (anticipating the scratch files), but I found no way to open multiple files in VSCode at once: running `code *.rs` makes the plugin to register in the `vscode.workspace.textDocuments` only the first file, while code actually displays all files later.
Apparently what happens is the same as when you have VSCode open at some workplace already and then run `code some_other_file.rs`: it gets opened in the same workspace of the same VSCode with no server to support it.
If there's a way to override it, I'd appreciate the pointer.
* No way to toggle inlay hints, since the setting is updated for the workspace (which does not exist for a single file opened)
> …
> feature: Support standalone Rust files

- editors/code/src/snippets.ts
> fix cursor position after item move command

- crates/project_model/src/cargo_workspace.rs
Cargo collapses identical dependencies that are listed under `[dependencies]` and `[build-dependencies]` into a single `NodeDep`. We have to undo that by duplicating the dependency for each of its listed `DepKind`s.
Not doing that would incorrectly treat a dependency as `DepKind::Normal`, even though it is *also* meant to be a `DepKind::Build`.
Fixes https://github.com/rust-analyzer/rust-analyzer/pull/8812#issuecomment-847125395
bors r+
> fix: duplicate dependencies that have multiple DepKinds

- crates/ide_assists/src/handlers/fill_match_arms.rs
- crates/ide_assists/src/tests/generated.rs
- crates/syntax/src/ast/edit_in_place.rs
- xtask/src/tidy.rs
`todo!()` seems to be a better fit for this than `{}`. Seeing that this assist predates stabilization of `todo` my guess is that simply no one bothered to change it yet.
Also fixed the issue where if the last arm was not block-like, rust-analyzer would not add a comma after it and would generate invalid code.
> Use todo!() as placeholder body for generated match arms

- crates/base_db/src/input.rs
`cfg` flags are now implemented, and crates *may* have names, it doesn't
doesn't matter for name resolution
bors r+
> minor: update `CrateGraph` comment

- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/coercion.rs
MacroStmts should be completely transparent, but it prevented
coercion. (I should maybe give `infer_expr` and `infer_expr_inner`
better names.)
> Fix type mismatch caused by macros

- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Fixes #7580.
This PR implements the `textDocument/rangeFormatting` request using `rustfmt`'s `--file-lines` option.
Still needs some tests. What I want to know is how I should handle the instability of the `--file-lines` option. It's still unstable in rustfmt, so it's only available on nightly, and needs a special flag to enable. Is there a way for `rust-analyzer` to detect if it's using nightly rustfmt, or for users to opt-in?
> implement range formatting

- crates/ide/src/goto_implementation.rs
> feat: go to implementation on trait functions

- crates/hir_def/src/path/lower.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/tests/traits.rs
This should result in an implicit `-> ()`, not leaving out the binding.
> Fix lowering of FnOnce() without return type

- crates/ide/src/goto_implementation.rs
I forgot to put this into #8988, sorry.
Goto implementation on a const on the trait will go to the
implementations with their respective definitions of the const, if
present.
> feat: Also do goto implementation on assoc consts

- crates/rust-analyzer/src/reload.rs
The current logic used to transfer global_excludes into vfs exclusions
only transfers global_excludes that are the parent of an item in
dirs.include.
This commit additionally adds an item from global_exclude to the vfs
exclusions if the global_exclude is a child of an included item.
> Check for subdirs in vfs loader exclusions.

- crates/ide_completion/src/completions/keyword.rs
Add tab stops for all the keywords that I judged fit. I also introduced some line breaks and spaces, following the pattern I saw in the `postfix` module.
> feat: add tab stops for keyword completions

- crates/ide_completion/src/completions/pattern.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render.rs
The two bools, `is_pat_binding_or_const` and `is_irrefutable_pat_binding` can never both be set so this is basically just a tri-state enum.
bors r+
> internal: Merge pattern completion related bools into an enum

- editors/code/src/client.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
- editors/code/src/tasks.ts
Follow-up of https://github.com/rust-analyzer/rust-analyzer/pull/8955#discussion_r637897170
Before: 
After: 
This is the first time I've used multiple workspaces feature in VSCode, but so far looks like
* opening detached files works
* run and debug lens work
* Rust Analyzer: Run action works
* run task works and now shows tasks for all workspaces
* there are no platform-specific changes involved
> fix: Create tasks for all workspaces

- crates/ide_db/src/helpers/import_assets.rs
Inherent traits can be omitted before trait solving, presumably slightly helping https://github.com/rust-analyzer/rust-analyzer/issues/7542 and slightly simplifying the code.
> internal: Reduce the number of traits passed through chalk during applicable trait lookup

- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/completions/snippet.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/patterns.rs
> Collapse more CompletionContext booleans into enums

- crates/ide/src/syntax_highlighting.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
> internal: Document semantic token tags

- docs/dev/lsp-extensions.md
> internal: explain the motivation behind early configuration

- crates/hir/src/lib.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/item_tree/tests.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/diagnostics.rs
- crates/hir_def/src/path.rs
- crates/hir_def/src/path/lower.rs
- crates/hir_def/src/path/lower/lower_use.rs
- crates/hir_def/src/test_db.rs
- crates/ide/src/diagnostics.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/8908
Messy diff, but `ItemTree` lowering got simpler, since we now have a strict 1-to-1 mapping between `ast::Item` and `ModItem`.
The most messy part is mapping a single `UseTree` back to its `ast::UseTree` counterpart for diagnostics, but I think the ad-hoc source map built during lowering does the job.
> internal: stop expanding UseTrees during ItemTree lowering

- crates/ide_completion/src/render/macro_.rs
cc https://github.com/rust-analyzer/rust-analyzer/issues/7072#issuecomment-850396203
This doesn't fix it non builtin derives yet I think cause of a FIXME somewhere that doesn't categorize proc-macro derives as derives yet
bors r+
> Don't label derive macros with their banged_name

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/eager.rs
- crates/hir_ty/src/tests/macros.rs
This PR removes determination of fragment kinds from the eager macro implementations. The fragment kind is always determined by the syntax position in which a macro is invoked, not by the macro implementation, even for eager macros.
This makes `include!` work in expression position, and should have the same effect for all macros that may be used in different positions.
bors r+
> fix: make `include!` etc. work in expression position

- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/completions/attribute/derive.rs
- crates/ide_completion/src/completions/attribute/lint.rs
> Add some lint completion tests

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Descriptions for diagnostic warning hint and info display were swapped.
Fixes #8485.
> Fix incorrect setting descriptions

- crates/mbe/src/expander/matcher.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9043
bors r+
> fix: fix `matches!` macro on nightly toolchains

- crates/ide_completion/src/completions/attribute/derive.rs
HIR now gives them `MacroKind::Derive` instead of `MacroKind::ProcMacro`
bors r+
> fix: Only complete derive proc macros in `#[derive]`

- crates/hir_ty/src/chalk_db.rs
- crates/hir_ty/src/tests/traits.rs
> hir_ty: don't pass where clauses of associated types down to chalk

- Cargo.toml
1.52.1 turns incremental off regardless of this setting, so this is unnecessary. Removing this allow manually overriding Cargo to enable incremental.
bors r+
> minor: Don't force-disable incremental

- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/diagnostics.rs
- crates/hir_def/src/test_db.rs
- crates/ide/src/diagnostics.rs
A number of built-in attribute macros are unsupported, I thought it might be useful to put a diagnostic on their definition in libcore. Not sure.
> feat: Diagnose unimplemented built-in macros

- crates/hir_def/src/find_path.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/hir_expand/src/name.rs
- crates/hir_ty/src/tests/macros.rs
- crates/hir_ty/src/tests/method_resolution.rs
- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/tests/simple.rs
- crates/hir_ty/src/tests/traits.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_db/src/helpers/famous_defs_fixture.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/9056
Our previous implementation was incorrect (presumably because of the misleading comment in libstd [here](https://github.com/rust-lang/rust/blob/a7890c7952bdc9445eb6c63dc671fa7a1ab0260d/library/std/src/lib.rs#L339-L343)). `#[prelude_import]` does not define the prelude, it can only override the implicit prelude for the current crate.
This PR fixes that, which also makes the prelude imports in `rustc_span` work. Closes https://github.com/rust-analyzer/rust-analyzer/issues/8815.
bors r+
> feat: Implement per-edition preludes

- crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/syntax/src/ast/make.rs
bors r+
Fixes #9100
Fixes #9099
Kind of fixes  #9109, it now copies all the generics which might be incorrect if the variant doesn't use all of them
> Fix some bugs in `extract_struct_from_enum_variant` assist

- crates/ide_assists/src/handlers/extract_variable.rs
```rust
fn main() {
let mut i = 3;
$0if i >= 0 {
i += 1;
} else {
i -= 1;
}$0
}
```
1. Select the snippet of code between the $0's.
2. The extract into variable assist shows up, pushing down the more useful extract into function assist.
3. The resulting output of selecting the extract into variable assist is valid but with the extracted variable having the unit type:
```rust
fn main() {
let mut i = 3;
let var_name = if i >= 0 {
i += 1;
} else {
i -= 1;
};
var_name
}
```
**Fix:**
- Don't show the extract into variable assist for unit expressions. I could not think of any scenarios where such a variable extraction would be desired.
> Don't show extract into variable assist for unit expressions

- crates/ide/src/expand_macro.rs
I don't really see a reason to only limit this to the name-ref of a macro.
bors r+
Closes #4606
> Allow expand-macro to be invoked anywhere inside a macro call

- docs/user/manual.adoc
Added installation instructions for the binary ebuild of the "latest" `rust-analyzer` in Gentoo's GURU repository.
> manual.adoc: add Gentoo Linux installation method

- crates/hir_def/src/data.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
haxx run the world
Closes https://github.com/rust-analyzer/rust-analyzer/issues/8552
Part of https://github.com/rust-analyzer/rust-analyzer/issues/9056
> Implement `#[rustc_skip_array_during_method_dispatch]`

- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/tests.rs
No observable changes from what I can tell, but this is "more correct".
bors r+
> internal: make variant fields inherit the enum's visibility in the ItemTree

- crates/hir/src/lib.rs
- crates/hir_def/src/builtin_attr.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/test_db.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/input.rs
- crates/hir_expand/src/lib.rs
- crates/hir_expand/src/proc_macro.rs
- crates/hir_ty/src/test_db.rs
- crates/ide_db/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This adds experimental support for attribute macros. They can be enabled by setting `rust-analyzer.experimental.procAttrMacros` to `true`.
Known issues:
* Tokens aren't remapped, presumably because we edit the input syntax tree (this causes IDE features to not work inside items with attribute macros on them)
* Macro errors aren't reported correctly
Closes https://github.com/rust-analyzer/rust-analyzer/issues/8971
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8964 / https://github.com/la10736/rstest/issues/120
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/2984
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/5412
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6029
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6687 …
> feat: expand procedural attribute macros

- crates/ide/src/hover.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/generated_config.adoc
- editors/code/package.json
- editors/code/src/config.ts
This is off by default as this can slow down hover messages significantly for very big projects I believe.
Fixes #6590
bors r+
> feat: Add function references hover action

- crates/hir_def/src/nameres/collector.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9133
cursed bug
bors r+
> fix: fix incorrect "unresolved import" error when using derive helpers

- crates/rust-analyzer/src/cli/load_cargo.rs
Before:
```
> $ rust-analyzer -q analysis-stats --with-proc-macro --load-output-dirs .
Database loaded:     19.08s, 277minstr
crates: 34, mods: 688, decls: 13202, fns: 10412
Item Collection:     16.21s, 76ginstr
exprs: 290580, ??ty: 2508 (0%), ?ty: 1814 (0%), !ty: 947
Inference:           27.46s, 108ginstr
Total:               43.67s, 184ginstr
```
After:
```
> $ ./target/release/rust-analyzer -q analysis-stats --with-proc-macro --load-output-dirs .
Database loaded:     1.09s, 277minstr
crates: 34, mods: 688, decls: 14790, fns: 11006
Item Collection:     18.20s, 78ginstr
exprs: 297826, ??ty: 493 (0%), ?ty: 558 (0%), !ty: 342
Inference:           28.34s, 111ginstr
Total:               46.54s, 190ginstr
```
> internal: Enable attribute macro expansion in `analysis-stats`

- crates/ide/src/references/rename.rs
Otherwise trying to rename a usage that goes through an alias will still rename the aliased item instead, cc https://github.com/rust-analyzer/rust-analyzer/issues/5671
bors r+
> minor: Prevent renaming of aliases on usages

- crates/hir_expand/src/input.rs
This is needed to that the `TokenMap` we create contains offsets that match the source. Currently the offsets don't match because the attribute is removed, shifting all subsequent token offsets by the attribute's text length.
Currently this fix has no visible effect because we don't remap tokens in attribute macros.
bors r+
> internal: replace attribute with equivalent whitespace

- crates/hir/src/lib.rs
- crates/ide/src/goto_definition.rs
e.g. if you have a trait T and `impl T for S` for some struct, if you
goto definition on some function name inside the impl, it will go to the
definition of that function inside the `trait T` block, rather than the
current behaviour of not going anywhere at all.
> feat: goto definition on an impl fn goes to that fn in the trait

- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/keys.rs
- crates/hir_def/src/nameres/collector.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/syntax_highlighting.rs
This doesn't work yet, but we seem to be getting a bit further along (for example, we now stop highlighting `use` items inside item with attribute macros as if they were written verbatim).
bors r+
> internal: steps towards attribute macro token mapping

- crates/hir/src/semantics/source_to_def.rs
In `SourceToDefCtx::find_container`, we might encounter a container that has an attribute macro. We need to skip that item, instead of bailing out and creating an empty `Resolver`, otherwise all names in the macro stay unresolved.
Part of https://github.com/rust-analyzer/rust-analyzer/issues/9142
bors r+
> fix: fix some IDE functionality inside attribute macros

- crates/hir/src/lib.rs
- crates/ide_completion/src/completions/pattern.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/completions/unqualified_path.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/8518
bors r+
> fix: don't complete derive macros as fn-like macros

- crates/hir/src/semantics.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
> fix: Don't descend MacroCall TokenTree delimiters

- crates/ide/src/references.rs
- crates/ide_db/src/defs.rs
> fix: Don't classify attributes on macro-calls are the macro itself

- Cargo.lock
- crates/profile/Cargo.toml
- crates/profile/src/memory_usage.rs
Unfortunately there is no convenient API for heap statistics, so this instead uses the Commit Charge value, which is the amount of memory that needs to be allocated either in physical RAM or in the page file. This approximation seems to be good enough to find queries that waste a large amount of memory, but it should generally be expected to be off by several MB.
bors r+
> feat: Make `MemoryUsage` work on Windows

- crates/base_db/src/lib.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/lang_item.rs
- crates/hir_def/src/per_ns.rs
- crates/ide_db/src/symbol_index.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/7542
A number of profile calls added for `import_on_the_fly` contents.
Before:
After:
As a result, low hanging fruit was spotted: crazy amount of `fst_path` calls. Reducing that won ~200ms in the `import_on_the_fly @ sel` case in the `integrated_completion_benchmark`:
I'm not sure how to proceed with the remaining `???` marks in such methods as `collect_import_map` though: there's nothing but library calls in cycles, but maybe I'll come up with something later.
> minor: Speed up fst items lookup during completions

- crates/ide/src/prime_caches.rs
- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/diagnostics.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/cli/ssr.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
Part of #7542
Follow up of https://github.com/rust-analyzer/rust-analyzer/pull/9206#issuecomment-859097783
Reduces `import_on_the_fly @ sel` case in the `integrated_completion_benchmark` by ~300ms.
Also enables cache priming for manual workspace loading to reflect the results in the benchmarks.
Before:
After:
> minor: Populate import maps eagerly to speed up flyimports

- Cargo.lock
- crates/profile/src/memory_usage.rs
This adds support for the new `mallinfo2` API added in glibc 2.33. It addresses a shortcoming in the `mallinfo` API where it was unable to handle memory usage of more than 2 GB, which we sometimes exceed.
Blocked on https://github.com/rust-lang/libc/pull/2228
> feat: more accurate memory usage info on glibc Linux

- crates/base_db/src/lib.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests.rs
- crates/hir_ty/src/tests/coercion.rs
- crates/hir_ty/src/tests/patterns.rs
Plus add infrastructure to test type mismatches without expect.
CC #8961
> fix: Fix coercion in match with expected type

- crates/hir_def/src/lib.rs
- crates/hir_ty/src/chalk_db.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/traits.rs
As long as either the trait or the implementing type are defined in the same block.
CC #8961
> feat: Make block-local trait impls work

- editors/code/src/config.ts
- editors/code/src/main.ts
- editors/code/src/net.ts
- editors/code/src/toolchain.ts
I encountered an error where `bootstrap()` attempts to create a directory with the path `C:\C:\...`. I couldn't find this reported anywhere else. Using the `vscode.FileSystem` API instead of the `fs` one works here. I assume the latter automatically prepends `C:\` to paths whereas the former does not. I don't know if this suggests `vscode.FileSystem` should be used in more places for consistency.
> internal: migrate to vscode.FileSystem API
