rust-lang/rust-analyzer

Cargo.lock
xtask/src/flags.rs
xtask/src/install.rs
xtask/src/main.rs

Cleanup install command

---

crates/hir_def/src/attr.rs
crates/ide/src/runnables.rs

Fix some warnings

---

crates/ide_assists/src/handlers/extract_function.rs

Honor snippet capability when using the extract function assist

---

xtask/src/flags.rs
xtask/src/install.rs
xtask/src/main.rs

Underengineer `cargo xtask install --client`

---

crates/mbe/src/tests.rs
crates/parser/src/grammar.rs

Fix fail to parse :: for meta in mbe

---

crates/ide_assists/src/handlers/generate_default_from_new.rs
crates/ide_assists/src/lib.rs
crates/ide_assists/src/tests/generated.rs

The Generate Default impl from new function.

[WIP] 7708: Initial implementation of generate Default assist.

---

crates/ide_assists/src/handlers/replace_string_with_char.rs

Only replace quotes in replace_string_with_char assist

---

crates/hir_def/src/import_map.rs

While debugging https://github.com/rust-analyzer/rust-analyzer/issues/7902, I've found that there are some duplicates are produced during the external dependencies lookup.
I've spotted at least some of the `indexed_value.value` duplicated when typed `Arc` and requested the completions for that, so I've also deduped the `IndexedValue`'s to avoid unnecessary computations.
This helps to show `Arc` in the completion suggestions in a zero dependency project and in `hir` module, but we loose it again in the `ide` module.

Dedupe import map results

---

crates/rust-analyzer/src/config.rs
docs/user/generated_config.adoc
editors/code/package.json

Make code completion "just work" in more cases

---

Cargo.lock
crates/rust-analyzer/tests/rust-analyzer/support.rs
crates/test_utils/Cargo.toml
crates/test_utils/src/lib.rs

Don't punish every crate with serde-json

---

crates/rust-analyzer/src/config.rs
crates/syntax/src/tests.rs
crates/test_utils/src/bench_fixture.rs
crates/test_utils/src/lib.rs
docs/dev/architecture.md
xtask/src/codegen.rs
xtask/src/codegen/gen_assists_docs.rs
xtask/src/codegen/gen_diagnostic_docs.rs
xtask/src/codegen/gen_feature_docs.rs
xtask/src/codegen/gen_lint_completions.rs
xtask/src/codegen/gen_parser_tests.rs
xtask/src/codegen/gen_syntax.rs
xtask/src/flags.rs
xtask/src/main.rs
xtask/src/release.rs
xtask/src/tidy.rs

Generalize file ensuring infrastructure

---

docs/dev/lsp-extensions.md

Clarify that all caps are experimental

---

crates/hir/src/lib.rs

Use `Type::new_with_resolver_inner` more

---

crates/rust-analyzer/src/config.rs
docs/user/generated_config.adoc
editors/code/package.json

Make code less surprising

---

crates/syntax/Cargo.toml

Improve compilation speed

---

crates/rust-analyzer/src/handlers.rs

Fix unused definitions not being document highlit

---

crates/hir/src/lib.rs
crates/ide/src/display/short_label.rs
crates/ide/src/hover.rs
crates/ide/src/syntax_highlighting/highlight.rs

Show whether a binding is mutable or not on hover

---

crates/ide_completion/src/item.rs
crates/ide_completion/src/lib.rs
crates/ide_completion/src/render.rs
crates/rust-analyzer/src/to_proto.rs

Future proof completion scores

---

crates/hir_def/Cargo.toml
crates/hir_expand/Cargo.toml
crates/hir_ty/Cargo.toml
crates/ide/Cargo.toml
crates/ide_assists/Cargo.toml
crates/ide_completion/Cargo.toml
crates/ide_db/Cargo.toml
crates/ide_ssr/Cargo.toml
crates/mbe/Cargo.toml
crates/proc_macro_srv/Cargo.toml

Compilation speed

---

crates/hir_def/src/body/lower.rs

Stop fetching ItemTrees for no reason

---

crates/ide_assists/src/handlers/auto_import.rs
crates/ide_assists/src/handlers/qualify_path.rs

Fix labels for single import assists

---

Cargo.lock
crates/hir_expand/Cargo.toml
crates/hir_expand/src/builtin_macro.rs
crates/hir_expand/src/name.rs
crates/hir_expand/src/quote.rs

Implement builtin `cfg!` macro

---

Cargo.lock
crates/hir_expand/Cargo.toml
crates/hir_expand/src/builtin_derive.rs
crates/hir_expand/src/builtin_macro.rs

Use expect-test for builtin macro/derive tests

---

crates/ide_assists/src/handlers/add_turbo_fish.rs

fix: add semicolon after type ascription

---

crates/ide_completion/src/completions/attribute.rs
crates/ide_completion/src/completions/fn_param.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/mod_.rs
crates/ide_completion/src/completions/postfix.rs
crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/completions/snippet.rs
crates/ide_completion/src/completions/trait_impl.rs
crates/ide_completion/src/item.rs
crates/ide_completion/src/render.rs
crates/ide_completion/src/render/builder_ext.rs
crates/ide_completion/src/render/const_.rs
crates/ide_completion/src/render/enum_variant.rs
crates/ide_completion/src/render/function.rs
crates/ide_completion/src/render/macro_.rs
crates/ide_completion/src/render/pattern.rs
crates/ide_completion/src/render/type_alias.rs

@matklad 
This is a follow up to [this pr](https://github.com/rust-analyzer/rust-analyzer/pull/7973)

use references in CompletionItem's builder

---

crates/ide_completion/src/completions/attribute.rs
crates/ide_completion/src/completions/fn_param.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/mod_.rs
crates/ide_completion/src/completions/postfix.rs
crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/completions/snippet.rs
crates/ide_completion/src/completions/trait_impl.rs
crates/ide_completion/src/render.rs
crates/ide_completion/src/render/enum_variant.rs
crates/ide_completion/src/render/function.rs
crates/ide_completion/src/render/macro_.rs
crates/ide_completion/src/render/pattern.rs

Unify naming

---

crates/hir_def/src/item_tree.rs
crates/hir_ty/src/tests.rs

`HasSource` should be used instead
bors r+

Remove `ItemTree::source`

---

crates/hir_def/src/test_db.rs

Simplify hir_def TestDB

---

crates/rust-analyzer/src/to_proto.rs

fix folding range kind

---

crates/mbe/src/expander/transcriber.rs

Make sure ill-form macro handle propely

---

crates/mbe/src/expander/matcher.rs

Simpify mbe bindings builder

---

crates/syntax/src/parsing/text_tree_sink.rs

Attach trivia to ast::Union nodes

---

crates/ide_completion/src/render.rs
crates/rust-analyzer/src/to_proto.rs

Use auto-deref in completion scoring

---

crates/ide/src/runnables.rs

Don't drop type params in doc-test paths

---

crates/ide/src/annotations.rs
crates/ide/src/file_structure.rs
crates/ide/src/lib.rs
crates/ide_db/src/lib.rs
crates/rust-analyzer/src/to_proto.rs

Move code to the appropriate layer

---

crates/hir/src/source_analyzer.rs
crates/ide/src/goto_definition.rs

Goto definition works for `S { a: }` case

---

crates/hir/src/source_analyzer.rs
crates/hir_def/src/body.rs
crates/hir_def/src/body/lower.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/expr.rs

Simplify source maps for fields

---

crates/hir/src/semantics.rs
crates/ide/src/annotations.rs
crates/ide/src/runnables.rs
crates/ide_db/src/helpers.rs

See https://github.com/rust-analyzer/rust-analyzer/issues/3538#issuecomment-798920601

 Introduce Semantics::visit_file_defs

---

crates/rust-analyzer/src/config.rs
docs/user/generated_config.adoc
editors/code/package.json

Enable proc-macros by default

---

crates/proc_macro_api/src/lib.rs
crates/proc_macro_api/src/version.rs
crates/proc_macro_srv/src/tests/mod.rs
crates/proc_macro_srv/src/tests/utils.rs

Add test for proc-macro meta info retrieval

---

crates/ide_completion/src/completions/pattern.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/render/pattern.rs

unqualfied_path completions aren't responsible for variant pattern completions

---

crates/hir_expand/src/name.rs
crates/ide_assists/src/handlers/generate_is_empty_from_len.rs
crates/ide_assists/src/lib.rs
crates/ide_assists/src/tests/generated.rs

Updated the implementation to get the function from implementation

Assist is empty 7709

---

crates/hir_ty/src/lib.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/traits/chalk/interner.rs

Doesn't help as much as I hoped, but it helps a bit and I also did some
refactorings that were necessary anyway.

Use SmallVec for Substs

---

.github/workflows/release.yaml

Increase fetch-depth to make `git describe` work

---

crates/ide_completion/src/render.rs
crates/ide_completion/src/render/enum_variant.rs
crates/ide_completion/src/render/function.rs

This PR makes several improvements to completions and completion sorting:
1. Provide exact match type relevance score bonus for enum variants
2. Suggest `&Foo` (ref_match) for enums if that is an exact type match
3. Suggest `&foo()` (ref_match) if `foo` returns a type which would be an exact match either with the reference or due to a `Deref` impl
I think generic types will require some kind of fancier logic when testing for `exact_type_match`, so for now `Option`/`Result`/etc unfortunately still don't have great completions.
I implemented this in a way that I think makes it most likely for each completion type to be handled consistently. Just replace `CompletionItem::new` with `CompletionItem::new_with_type_info` and `exact_type_match`/`exact_name_match`/`ref_match` are all handled for …

completions: provide relevance bonus for enum types, and suggest ref matches for fn and enum

---

docs/dev/style.md

Prefer match to if let else

---

crates/hir/src/display.rs
crates/hir/src/lib.rs
crates/hir_def/src/adt.rs
crates/hir_def/src/data.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_def/src/path.rs
crates/hir_ty/src/diagnostics/decl_check.rs
crates/hir_ty/src/diagnostics/unsafe_check.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/traits/chalk.rs
crates/ide/src/display.rs
crates/ide/src/display/navigation_target.rs
crates/ide/src/hover.rs

Fix #2765 , (should) fix #4665

Use hir formatter for hover text

---

crates/ide_completion/src/context.rs

Fix more unused wariable warnings

---

crates/ide_completion/src/render.rs

cc @matklad  - this PR addresses your comments in #8036. 
changelog fixup #8036

minor style fixes per feedback on #8036

---

crates/hir/src/display.rs
crates/ide/src/hover.rs

Implement HirDisplay for some more types

---

crates/ide_assists/src/handlers/move_bounds.rs
crates/syntax/src/ast/edit_in_place.rs

Move more bounds

---

crates/syntax/src/ast/edit_in_place.rs
crates/syntax/src/ted.rs

Auto-magical whitespace

---

crates/syntax/src/ast/edit_in_place.rs
crates/syntax/src/ted.rs

pit-of-successify tree editor

---

crates/hir_def/src/data.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_ty/src/diagnostics/expr.rs
crates/parser/src/grammar/params.rs
crates/syntax/test_data/parser/inline/ok/0139_param_outer_arg.rast
crates/syntax/test_data/parser/ok/0051_parameter_attrs.rast

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/5649

Correctly handle `#[cfg]` on function parameters

---

crates/ide/src/syntax_highlighting/inject.rs
crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
crates/ide/src/syntax_highlighting/tests.rs

bors r+
Closes https://github.com/rust-analyzer/rust-analyzer/issues/6873

Inject highlight into block doc comments

---

crates/hir_def/src/body/tests.rs
crates/hir_def/src/nameres/tests/diagnostics.rs
crates/hir_expand/src/builtin_macro.rs

Improve diagnostic when including nonexistent file

---

crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/nameres/tests.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/4644
bors r+

Fix `use crate as <name>;` imports

---

crates/hir_ty/src/tests/traits.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/4438 (and duplicates)
bors r+

Add test for self-calling inner function

---

crates/hir_def/src/data.rs
crates/hir_ty/src/tests/simple.rs

Support `#[cfg]` on all associated items

---

crates/hir_def/src/data.rs

Avoid cloning `CfgOptions`

---

crates/hir/src/db.rs
crates/hir/src/semantics.rs
crates/hir_def/src/adt.rs
crates/hir_def/src/attr.rs
crates/hir_def/src/data.rs
crates/hir_def/src/db.rs
crates/hir_def/src/generics.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/nameres.rs
crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/src.rs
crates/ide_db/src/apply_change.rs

...which won't go through salsa because the AST is already cached anyways
bors r+

Change ItemTree API to accomodate creating an ItemTree per block expression

---

crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_ty/src/tests/macros.rs

Fixes #7645
cc @jonas-schievink 
bors r+

Proper handle inner recursive macro rules cases

---

crates/ide/src/goto_definition.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7073
bors r+

Add test for goto def on proc macro invocation

---

crates/hir_def/src/nameres.rs
crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/nameres/proc_macro.rs
crates/hir_def/src/nameres/tests/macros.rs

Also clean up proc macro attribute parsing a bit
bors r+

Record custom derive helpers in `DefMap`

---

crates/hir_ty/src/diagnostics/decl_check.rs

Fix infinite recursion when computing diagnostics for inner items

---

crates/hir_def/src/attr.rs
crates/ide/src/syntax_highlighting.rs
crates/ide/src/syntax_highlighting/inject.rs

Fixes the panics/incorrect injection highlighting of outline module declarations until we figure out a nicer source mapping strategy for attributes.

Track source file IDs in source mapping of Attrs

---

crates/ide_assists/src/handlers/qualify_path.rs

Cleanup qualify_path

---

crates/hir_def/src/lib.rs
crates/hir_def/src/nameres.rs
crates/hir_def/src/nameres/collector.rs
crates/hir_expand/src/builtin_derive.rs
crates/hir_expand/src/lib.rs

Indicate that they're derive-specific
bors r+

Rename derive-specific APIs

---

crates/syntax/src/ast/edit_in_place.rs
crates/syntax/src/ted.rs

Make ast editing more ergonomic

---

.github/workflows/release.yaml

Temporarily run git describe on CI to debug #8043

---

.github/workflows/release.yaml

Reverts rust-analyzer/rust-analyzer#8121
bors r+
changelog skip

Revert "Temporarily run git describe on CI to debug #8043"

---

crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs
crates/hir_ty/src/tests/patterns.rs

Fix box pattern inference panic

---

docs/user/manual.adoc

Document our security stance

---

docs/dev/README.md

Document patch policy

---

crates/hir_ty/src/display.rs

close https://github.com/rust-analyzer/rust-analyzer/issues/8084

bail out early for source code closures

---

crates/ide_assists/src/handlers/merge_imports.rs
crates/ide_assists/src/handlers/unmerge_use.rs
crates/ide_db/src/helpers/insert_use.rs
crates/syntax/src/ast/edit.rs
crates/syntax/src/ast/edit_in_place.rs
crates/syntax/src/ast/make.rs
crates/syntax/src/ted.rs

rewrite merge use trees assist to use muatable syntax trees

---

crates/hir_def/src/nameres.rs
crates/hir_def/src/nameres/path_resolution.rs
crates/hir_def/src/resolver.rs
crates/hir_ty/src/tests/regression.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8152
bors r+

Fix confusion between parameters and the function

---

crates/hir_ty/src/lower.rs
crates/hir_ty/src/tests/traits.rs

Correctly lower TraitRefs with default params

---

crates/hir/src/lib.rs
crates/ide/src/references.rs
crates/ide_completion/src/completions/attribute.rs
crates/ide_db/src/search.rs

Set up a search scope when searching for mbe macro references

---

crates/ide_assists/src/assist_context.rs
crates/ide_assists/src/handlers/merge_imports.rs
crates/ide_assists/src/handlers/move_bounds.rs

Tweak assits API to fit mutable syntax trees

---

crates/ide_assists/src/assist_context.rs
crates/ide_assists/src/handlers/add_explicit_type.rs
crates/ide_assists/src/handlers/merge_imports.rs
crates/ide_assists/src/handlers/move_bounds.rs

Unify test style

---

crates/ide_assists/src/handlers/add_explicit_type.rs
crates/ide_assists/src/handlers/add_lifetime_to_type.rs

Use styleguide conforming import for ast nodes

---

crates/hir/src/lib.rs
crates/ide/src/references/rename.rs

Make more use of the HIR in rename::rename_to_self

---

crates/hir_def/src/nameres/collector.rs

Merge bang-macros and derives in name resolution

---

crates/ide_assists/src/handlers/add_missing_impl_members.rs
crates/ide_assists/src/handlers/convert_comment_block.rs
crates/syntax/src/ast/token_ext.rs

Simplify code

---

crates/ide/src/call_hierarchy.rs
crates/ide/src/doc_links.rs
crates/ide/src/goto_definition.rs
crates/ide/src/hover.rs
crates/ide/src/runnables.rs
crates/ide/src/syntax_highlighting/inject.rs

Show item info when hovering intra doc links

---

crates/ide_assists/src/handlers/early_return.rs

close https://github.com/rust-analyzer/rust-analyzer/issues/8074

correct `convert to guard return` let_stmt

---

crates/ide_assists/src/handlers/early_return.rs
crates/ide_assists/src/handlers/unwrap_block.rs

Fix the comment style issues, it's in tests but maybe it's a little better to change it to this.

refine comment style of tests

---

crates/ide_db/src/apply_change.rs

Sweep the new TraitEnvironmentQuery

---

crates/ide/src/diagnostics/unlinked_file.rs

fixes https://github.com/rust-analyzer/rust-analyzer/issues/8188
bors r+

Document unlinked-file diagnostic

---

crates/hir_ty/src/lib.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/traits/chalk.rs
crates/hir_ty/src/utils.rs

Fixes #8150.
I implemented a validator that catches this in the tests, but it'd need to get merged in Chalk first.

Fix chalk_ir assertion

---

crates/ide/src/runnables.rs

Ignore main functions not in root module

---

crates/hir/src/semantics.rs
crates/hir_expand/src/name.rs
crates/ide/src/diagnostics/fixes.rs
crates/ide/src/inlay_hints.rs
crates/ide/src/syntax_highlighting/format.rs
crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
crates/ide_assists/src/handlers/generate_enum_is_method.rs
crates/ide_assists/src/handlers/generate_enum_projection_method.rs
crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
crates/ide_assists/src/utils.rs
crates/ide_db/src/defs.rs
crates/ide_db/src/helpers/import_assets.rs
crates/ide_db/src/helpers/insert_use.rs
crates/ide_ssr/src/resolving.rs
crates/syntax/src/ast/make.rs
crates/syntax/src/ast/node_ext.rs

Quick hack? to alleviate https://github.com/rust-analyzer/rust-analyzer/issues/8181#issuecomment-806019126. I haven't run any tests but this should affect performance since we are deallocating more.
r? @matklad

syntax: return owned string instead of leaking string

---

crates/ide_assists/src/handlers/generate_impl.rs
crates/ide_assists/src/utils.rs

Added support for const generics in impl generation

---

crates/ide_db/src/call_info/tests.rs
crates/ide_db/src/helpers/insert_use.rs
crates/ide_db/src/label.rs
crates/ide_db/src/search.rs
crates/ide_db/src/source_change.rs
crates/ide_db/src/traits.rs
crates/ide_db/src/traits/tests.rs
crates/ide_db/src/ty_filter.rs

Reorder some ide_db imports

---

docs/dev/README.md

internal: make --log-file more discoverable

---

crates/ide/src/folding_ranges.rs
crates/rust-analyzer/src/to_proto.rs

Fold consecutive consts and statics

---

crates/profile/src/hprof.rs

internal: cleanup hprof

---

crates/ide/src/doc_links.rs
crates/ide/src/syntax_highlighting/inject.rs

Remove code duplication in highlight injection

---

crates/base_db/src/lib.rs
crates/profile/src/hprof.rs
crates/profile/src/lib.rs

internal: track missing `.check_cancelled`

---

docs/user/manual.adoc

Fixes https://github.com/rust-analyzer/rust-analyzer.github.io/pull/97

update vim ycm installation instruction

---

docs/dev/README.md

internal: touch up dev readme

---

crates/profile/src/google_cpu_profiler.rs
crates/profile/src/lib.rs
crates/rust-analyzer/src/benchmarks.rs

internal: revive google_cpu_profile infra

---

crates/hir_ty/src/diagnostics/match_check.rs

Fix expansion of OR-patterns in match check

---

crates/proc_macro_srv/src/rustc_server.rs

Fix fail to parse u128  in proc-macro

---

crates/hir_def/src/item_tree/lower.rs
crates/hir_ty/src/tests/macros.rs

Fixes  #8229
r? @jonas-schievink

Fix block inner item defined in macro

---

crates/rust-analyzer/src/handlers.rs

Include remaining memory in memory usage stats

---

docs/dev/style.md

internal: document Cargo.lock maintenance process

---

docs/dev/style.md

internal: document style for helper functions and variables

---

crates/hir_ty/src/infer.rs

minor: add profile call for resolve_obligations

---

crates/hir_def/src/nameres/collector.rs
crates/ide/src/hover.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8281
bors r+

Only populate prelude for crate-level DefMaps

---

crates/hir_def/src/intern.rs

We don't use it yet, that's a bit more complicated.
bors r+

Allow interning strings

---

crates/ide/src/join_lines.rs

Fix joinLines panic if run on empty last line

---

crates/hir_def/src/nameres/tests/diagnostics.rs
crates/hir_def/src/test_db.rs
crates/mbe/src/syntax_bridge.rs

Allow include! an empty content file

---

Cargo.lock
crates/hir/src/display.rs
crates/hir/src/lib.rs
crates/hir_def/Cargo.toml
crates/hir_def/src/data.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_def/src/nameres/collector.rs
crates/hir_ty/src/diagnostics/decl_check.rs
crates/hir_ty/src/diagnostics/unsafe_check.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/method_resolution.rs

This was mostly a failed experiment, but still seems like the right thing to do. Memory reduction is mostly negligible.
bors r+

Try to reduce ItemTree size further

---

crates/hir/src/db.rs

Avoids having to constantly adjust this list
bors r+

Glob-reexport hir_def database types

---

crates/hir_def/src/item_scope.rs
crates/hir_def/src/nameres.rs

Use exhaustive matches in shrink_to_fit impls

---

crates/hir_def/src/body.rs
crates/hir_def/src/child_by_source.rs
crates/hir_ty/src/diagnostics/decl_check.rs
crates/hir_ty/src/tests.rs

Access a body's block def maps via a method

---

crates/hir_def/src/body.rs
crates/hir_def/src/body/lower.rs

Only remember blocks that have a DefMap

---

crates/hir_def/src/body.rs

Add `Body::shrink_to_fit`

---

crates/hir_def/src/db.rs
crates/hir_def/src/generics.rs
crates/hir_def/src/intern.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_def/src/lib.rs
crates/hir_def/src/path.rs
crates/hir_def/src/path/lower.rs
crates/hir_def/src/resolver.rs
crates/hir_def/src/visibility.rs
crates/hir_ty/src/utils.rs
lib/arena/src/lib.rs

Intern and shrink more data to reduce memory usage

---

crates/rust-analyzer/src/handlers.rs
docs/dev/style.md

internal: explain "extract if condition" refactoring

---

crates/ide_assists/src/handlers/reorder_fields.rs

This also instead uses `Either` to use the typed `RecordPat` and `RecordExpr` nodes, this unfortunately gives a bit of code duplication

Rewrite reorder fields assist to use mutable syntax trees

---

crates/ide_assists/src/handlers/extract_variable.rs

fix: extract variable works in guards

---

crates/hir/src/lib.rs
crates/hir_ty/src/builder.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/path.rs
crates/hir_ty/src/infer/unify.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/op.rs
crates/hir_ty/src/traits/chalk.rs
crates/hir_ty/src/traits/chalk/mapping.rs
crates/hir_ty/src/types.rs
crates/hir_ty/src/walk.rs

Rename `TyKind::Unknown` and `TyKind::ForeignType` (Chalk move)

---

crates/ide_completion/src/lib.rs

internal: document hypothetical completion problem

---

crates/hir_def/src/intern.rs

Minor interning improvements

---

crates/rust-analyzer/src/global_state.rs
crates/rust-analyzer/src/op_queue.rs
crates/rust-analyzer/src/reload.rs

internal: prepare to store OpQueue results in the queue itself

---

crates/hir_ty/src/traits/chalk/interner.rs

Makes it sligthly easier to swap out these types

Use more assoc. type aliases in the chalk interner

---

crates/hir_ty/src/db.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/types.rs

Our `Lifetime` isn't really used yet so this is a rather simple change

Replace hir_ty::Lifetime with chalk equivalent

---

crates/hir_ty/src/builder.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/unify.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/traits/chalk/mapping.rs
crates/hir_ty/src/types.rs
crates/hir_ty/src/walk.rs

Align FnPointer with Chalk

---

crates/hir/src/lib.rs
crates/hir_ty/src/diagnostics/expr.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/infer/coerce.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs
crates/hir_ty/src/infer/unify.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/traits/chalk/mapping.rs
crates/hir_ty/src/types.rs
crates/hir_ty/src/walk.rs

Add Lifetime to TyKind::Ref and DynTy

---

crates/hir/src/lib.rs
crates/hir_ty/src/db.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs
crates/hir_ty/src/infer/unify.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/traits/chalk/mapping.rs
crates/hir_ty/src/types.rs
crates/hir_ty/src/walk.rs

Add chalk_ir::Const to TyKind::Array

---

crates/hir/src/lib.rs
crates/hir_ty/src/builder.rs
crates/hir_ty/src/chalk_ext.rs
crates/hir_ty/src/diagnostics/match_check.rs
crates/hir_ty/src/diagnostics/unsafe_check.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/coerce.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs
crates/hir_ty/src/infer/path.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/traits/chalk.rs
crates/rust-analyzer/src/cli/analysis_stats.rs

Move Ty accessors to TyExt

---

crates/hir_def/src/body/lower.rs
crates/hir_def/src/expr.rs

Minor improvement to memory usage (1 MB or so)
bors r+

Intern TypeRefs stored in Body

---

crates/paths/src/lib.rs
crates/project_model/src/build_data.rs
crates/project_model/src/workspace.rs
crates/rust-analyzer/src/reload.rs
crates/stdx/src/lib.rs

feat: show errors from `cargo metadata` and initial `cargo check` in the status bar

---

crates/hir/src/source_analyzer.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/pat.rs

Same as https://github.com/rust-analyzer/rust-analyzer/pull/8376, this
can be computed from other data
bors r+

infer: remove `record_pat_field_resolutions` field

---

crates/hir_def/src/attr.rs

Lower attributes on tuple fields

---

docs/dev/README.md

internal: document broken windows

---

crates/hir/src/lib.rs
crates/hir_ty/src/autoderef.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/coerce.rs
crates/hir_ty/src/traits.rs
crates/hir_ty/src/traits/chalk/mapping.rs
crates/hir_ty/src/types.rs

... just missing the constraints.

Remove `SolutionVariables`, add ConstrainedSubst analogous to Chalk

---

crates/hir_ty/src/infer.rs
crates/hir_ty/src/tests/simple.rs

Infer variants through type aliased enums

---

crates/hir/src/lib.rs
crates/hir_ty/src/autoderef.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/method_resolution.rs

Uncouple Ty::builtin_deref and Ty::def_crates from Ty

---

crates/hir_def/src/body/tests.rs
crates/hir_def/src/nameres/tests/diagnostics.rs
crates/hir_expand/src/builtin_macro.rs

The setting was renamed, so the diagnostic should follow
bors r+

Update `OUT_DIR` diagnostic to match setting

---

crates/hir/src/lib.rs
crates/hir_ty/src/chalk_ext.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/coerce.rs
crates/hir_ty/src/infer/pat.rs
crates/hir_ty/src/infer/path.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/lower.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/traits.rs
crates/hir_ty/src/traits/chalk.rs
crates/hir_ty/src/traits/chalk/mapping.rs
crates/hir_ty/src/types.rs
crates/hir_ty/src/utils.rs

Various remaining fixes for Chalk IR move

---

crates/ide/src/folding_ranges.rs
crates/rust-analyzer/src/to_proto.rs

Emit folding ranges for multiline array literals

---

crates/ide_assists/src/handlers/remove_dbg.rs

Show dbg remove assist on empty contents

---

docs/dev/architecture.md

Remove extra bracket in architecture docs

---

crates/hir_def/src/lib.rs
crates/hir_def/src/nameres.rs
crates/hir_def/src/nameres/collector.rs
crates/hir_expand/src/builtin_derive.rs
crates/hir_expand/src/builtin_macro.rs
crates/hir_expand/src/eager.rs
crates/hir_expand/src/lib.rs

Use named fields in `MacroCallKind`

---

crates/ide/src/typing/on_enter.rs

8425: Added documentation for on enter covering //! doc comments.

---

crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/nameres/path_resolution.rs
crates/hir_ty/src/tests/traits.rs

Should fix https://github.com/rust-analyzer/rust-analyzer/issues/8418
bors r+

Resolve prelude and crate root names in the root DefMap

---

crates/hir_def/src/child_by_source.rs
crates/ide_assists/src/handlers/remove_dbg.rs

Don't ignore unnamed consts when looking for definitions

---

crates/hir_def/src/attr.rs

Avoid an unnecessary `collect`

---

.github/workflows/ci.yaml
crates/ide/src/syntax_highlighting/tests.rs
crates/test_utils/src/bench_fixture.rs

add is quadratic test

---

crates/hir_ty/src/tests/traits.rs

Respect test style guidelines in tests::traits

---

crates/ide_assists/src/handlers/extract_function.rs

```rust
fn main() {
let mut k = 1;
let mut j = 2;
j += 1;
k += j;
}
```
1. Select the first to third lines of the main function. Use the "Extract into function" code assist.
2. The output is the following which does not compile because the outlived variable `k` is declared as immutable:
```rust
fn main() {
let (k, j) = fun_name();
k += j;
}
fn fun_name() -> (i32, i32) {
let mut k = 1;
let mut j = 2;
j += 1;
(k, j)
}
```
3. We would instead expect the output to be:
```rust
fn main() {
let (mut k, j) = fun_name();
k += j;
}
```
**Fix:**
- Instead of declaring outlived variables as immutable unconditionally, check for any mutable usages outside of the extracted function.

Fix extract function's mutability of variables outliving the body

---

crates/hir_ty/src/method_resolution.rs

This helped find https://github.com/rust-analyzer/rust-analyzer/issues/8464
changelog skip
bors r+

Include more info in assert

---

crates/rust-analyzer/src/reload.rs

fix: don't spam repeated error messages when `cargo check` fails

---

crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/field_shorthand.rs
crates/ide/src/diagnostics/fixes.rs
crates/ide/src/diagnostics/unlinked_file.rs
crates/ide/src/lib.rs
crates/rust-analyzer/src/handlers.rs

internal: prepare for lazy diagnostics

---

crates/ide/src/syntax_highlighting/tests.rs

Fix typo: liner -> linear

---

crates/ide_assists/src/lib.rs
crates/rust-analyzer/src/from_proto.rs
crates/rust-analyzer/src/handlers.rs
crates/rust-analyzer/src/to_proto.rs
crates/rust-analyzer/tests/rust-analyzer/main.rs

internal: unfork code paths for unresolved and resolved assist

---

crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/fixes.rs
crates/ide/src/diagnostics/unlinked_file.rs
crates/ide/src/lib.rs
crates/rust-analyzer/src/cli/diagnostics.rs
crates/rust-analyzer/src/handlers.rs
crates/rust-analyzer/tests/rust-analyzer/support.rs

feat: improve performance by delaying computation of fixes for diagnostics

---

crates/ide/src/goto_definition.rs
crates/ide_assists/src/handlers/flip_comma.rs
docs/dev/style.md

internal: don't use `#[should_panic]` for tests

---

crates/ide/src/syntax_highlighting/tests.rs
crates/test_utils/src/assert_linear.rs
crates/test_utils/src/lib.rs

internal: fix flakiness of accidentally quadratic test

---

crates/hir_ty/src/diagnostics/decl_check.rs

decl_check: follow test style guide

---

crates/ide/src/typing.rs

internal: follow test style guide in typing.rs

---

crates/hir_ty/src/autoderef.rs
crates/hir_ty/src/db.rs
crates/ide_db/src/apply_change.rs

Follow-up of https://github.com/rust-analyzer/rust-analyzer/pull/8514#issuecomment-819610492

internal: Profile trait solving for all invocations

---

crates/hir_def/src/find_path.rs

minor: Make `find_path` tests adhere to style guide

---

crates/hir_def/src/find_path.rs

Addresses https://github.com/rust-analyzer/rust-analyzer/pull/8532#discussion_r614247375
bors r+

Remove unneeded annotations from find_path tests

---

docs/dev/README.md

Fix markdown links

---

crates/rust-analyzer/src/main_loop.rs

indexing -> Indexing
fetching -> Fetching
loading -> Loading
roots scanned -> Roots Scanned

change grammar

---

crates/hir_def/src/nameres/path_resolution.rs
crates/hir_ty/src/tests/simple.rs

fix: Fix primitive shadowing with inner items

---

crates/ide_db/src/call_info.rs
crates/ide_db/src/call_info/tests.rs

Return CallInfo for unclosed call expressions

---

crates/hir_def/src/find_path.rs
crates/hir_def/src/test_db.rs

Found while looking into https://github.com/rust-analyzer/rust-analyzer/issues/8519
bors r+

Fix `TestDB::module_at_position` with submodules

---

crates/mbe/src/tests/expand.rs
crates/parser/src/grammar.rs
crates/parser/src/grammar/attributes.rs

Handle extended key value attributes in mbe

---

crates/base_db/src/fixture.rs
crates/ide_assists/src/tests.rs

Add some more error messages to fixture failure cases

---

.github/ISSUE_TEMPLATE/bug_report.md

minor: update bug report template

---

crates/ide/src/syntax_highlighting/inject.rs
crates/ide/src/syntax_highlighting/tests.rs
crates/ide_db/src/helpers.rs
crates/ide_db/src/helpers/rust_doc.rs
crates/rust-analyzer/src/markdown.rs

Check for rust doc code attributes like rustdoc does

---

crates/ide_assists/src/handlers/extract_function.rs

```rust
fn foo() {
let n = 1;
let mut v = $0n * n;$0
v += 1;
}
```
1. Select the snippet ($0) and use the "Extract into function" assist.
2. Extracted function is incorrect and does not compile:
```rust
fn foo() {
let n = 1;
let mut v = fun_name(n);
v += 1;
}
fn fun_name(n: i32) {}
```
3. Omitting the ending semicolon from the selection fixes the extracted function:
```rust
fn fun_name(n: i32) -> i32 {
n * n
}
```
**Cause:**
- When `extraction_target` uses a block extraction (semicolon case) instead of an expression extraction (no semicolon case), the user selection is directly used as the TextRange.
- However, the existing function extraction logic for blocks requires that the TextRange spans from start to end of complete statements to work correctly.
- For example: …

Fix extract function with partial block selection

---

docs/dev/README.md

* don't feel obliged to quickly review every PR assigned to you
* so that other folks can notify you about interesting PRs without
thinking to much about creating additional work for you

internal: document review requesting etiquette

---

crates/ide/src/doc_links.rs

Support crates/module roots in external_docs

---

docs/dev/lsp-extensions.md

Fix spec bug

---

docs/dev/lsp-extensions.md

Remove confusion around serverStatusNotification

---

crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/tags.rs
crates/rust-analyzer/src/semantic_tokens.rs
crates/rust-analyzer/src/to_proto.rs

Fix typo: comparision -> comparison

---

crates/rust-analyzer/tests/rust-analyzer/main.rs

internal: fix slightly broken test

---

crates/hir_def/src/find_path.rs
crates/ide_assists/src/handlers/auto_import.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8519
bors r+

Fix some find_path bugs around inner items

---

docs/user/manual.adoc

minor: fix ugly line wrapping in the rendered manual

---

crates/ide_assists/src/handlers/inline_local_variable.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8530
bors r+

Trigger "Inline variable" assist when on a use of the variable

---

crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs

Fix panic in `replace_derive_with_manual_impl`

---

crates/parser/src/grammar/patterns.rs
crates/syntax/test_data/parser/inline/ok/0145_record_pat_field.rast
crates/syntax/test_data/parser/inline/ok/0145_record_pat_field.rs

Parse outer attributes for RecordPatField

---

crates/ide_assists/src/handlers/fill_match_arms.rs
crates/syntax/src/ast/make.rs

- Add support for boolean inside tuple
closes #8593

Add support for fill match arms of boolean values

---

Cargo.lock
crates/hir_ty/Cargo.toml
crates/syntax/Cargo.toml

minor: Bump deps

---

crates/ide_assists/src/handlers/extract_function.rs

This change addresses the first bullet point of https://github.com/rust-analyzer/rust-analyzer/issues/7839.
Specifically, when extracting block expressions, remove the unneeded extra braces inside the generated function.

Remove unnecessary braces for extracted block expression

---

Cargo.lock
crates/proc_macro_api/Cargo.toml
crates/proc_macro_api/src/lib.rs
crates/rust-analyzer/src/reload.rs

Add profiling spans under cargo_to_crate_graph

---

crates/base_db/src/input.rs

minor: Add one more profiling span to add_dep

---

crates/ide_assists/src/handlers/convert_tuple_struct_to_named_struct.rs
crates/ide_assists/src/lib.rs
crates/ide_assists/src/tests/generated.rs
crates/ide_db/src/search.rs
crates/syntax/src/ast/make.rs

Closes https://github.com/rust-analyzer/rust-analyzer/issues/8192

Convert tuple struct to named struct assist

---

crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/tags.rs
crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
crates/ide/src/syntax_highlighting/test_data/highlighting.html

and shuffle some code around
Closes #8634
bors r+

Tag `yield` and `await` as ControlFlow in semantic highlighting

---

xtask/src/dist.rs

fix: 'configuration.property' error in VS Code

---

crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/test_data/highlighting.html

Added `mutable` semantic token modifier for `&mut self` methods

---

crates/project_model/src/build_data.rs

fix: make error message in the status bar more useful

---

crates/stdx/src/lib.rs

minor: simplify

---

crates/rust-analyzer/src/main_loop.rs

fix: don't show error message for a valid notification

---

crates/rust-analyzer/src/config.rs
docs/user/generated_config.adoc
editors/code/package.json

internal: ensure that client and server-side configs are not mixed up

---

crates/parser/src/grammar/type_args.rs
crates/parser/src/grammar/type_params.rs
crates/syntax/test_data/parser/inline/ok/0165_const_param_defaults.rast
crates/syntax/test_data/parser/inline/ok/0165_const_param_defaults.rs

These will probably be stabilized in a few releases, let's make sure we can at least parse them
bors r+

feat: parse const param defaults

---

crates/hir/src/display.rs
crates/hir/src/lib.rs
crates/ide/src/runnables.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_assists/src/handlers/generate_from_impl_for_enum.rs
crates/ide_assists/src/utils/suggest_name.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/render/enum_variant.rs

internal: fix naming polarity

---

crates/hir_def/src/find_path.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8688
bors r+

fix: search only crate-level prelude when looking for an item

---

crates/ide_completion/src/completions/postfix/format_like.rs

Just something that bugged me :)

Fix feature description inconsistency

---

crates/rust-analyzer/src/global_state.rs
crates/rust-analyzer/src/main_loop.rs

Ensure that only one cache priming task can run at a time

---

xtask/src/dist.rs

feat: build releases with lto=true

---

crates/ide_assists/src/handlers/reorder_impl.rs

Map nodes to their mutable counterpart before mutating in reorder_impl

---

docs/user/manual.adoc

I was confused about how to do this, so I filed #8474. I apologize for initially filing this incorrectly and spamming people.

 Mention how to customize unsafe operation styles

---

crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/context.rs

Make CompletionContext expected_type smarter

---

crates/ide_assists/src/assist_context.rs
crates/ide_assists/src/handlers/extract_function.rs

internal: remove one more usage of the rewriter

---

crates/hir_def/src/attr.rs
crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
crates/ide/src/syntax_highlighting/tests.rs

Fix block comment intra doc link injection ranges

---

crates/hir_expand/src/db.rs

minor: unconfuse myself about macro def vs macro rules

---

crates/rust-analyzer/src/integrated_benchmarks.rs

internal: env var to toggle slow benches

---

crates/hir_expand/src/db.rs

internal: reduce visibility

---

crates/hir_expand/src/db.rs

minor: use standard import style

---

crates/hir_expand/src/db.rs
crates/hir_expand/src/hygiene.rs
crates/hir_expand/src/lib.rs
docs/dev/style.md

internal: refactor expansion queries

---

crates/ide_completion/src/completions/qualified_path.rs

Add some cov marks for qualified_path completion

---

docs/dev/style.md

internal: explain why sentence-per-line

---

crates/ide_completion/src/completions/trait_impl.rs

minor: simplify 

---

crates/rust-analyzer/build.rs

minor: standard snippet

---

Cargo.lock
crates/cfg/src/lib.rs
crates/hir/Cargo.toml
crates/hir/src/lib.rs

internal: expose cfg attrs from hir::Crate

---

docs/user/manual.adoc
xtask/src/release.rs

fix: direct people to the right repository

---

docs/user/manual.adoc

Replaces https://github.com/rust-analyzer/rust-analyzer.github.io/pull/111#issuecomment-834797031

docs: Add Kate installation section

---

editors/code/package-lock.json
editors/code/package.json

:arrow_up: package-lock.json

---

docs/user/manual.adoc

feat: friendlier trouble shooting guide

---

Cargo.toml

internal: disable broken incremental builds 😿

---

crates/ide_assists/src/handlers/extract_function.rs

internal: remove one more usage of SyntaxRewriter

---

crates/syntax/src/ast/edit.rs

minor: remove dead code

---

crates/ide_completion/src/context.rs
crates/parser/src/grammar/patterns.rs

minor: Add `=` to pattern recovery

---

crates/ide/src/join_lines.rs

fix: join lines doesn't add space before closing quote

---

crates/ide_assists/src/handlers/extract_function.rs
crates/ide_assists/src/handlers/introduce_named_lifetime.rs
crates/ide_assists/src/handlers/replace_impl_trait_with_generic.rs
crates/syntax/src/ast/make.rs

internal: fix make API

---

crates/ide_assists/src/handlers/early_return.rs
crates/ide_assists/src/handlers/expand_glob_import.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_assists/src/handlers/generate_function.rs
crates/ide_assists/src/handlers/move_bounds.rs
crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
crates/ide_assists/src/handlers/replace_let_with_if_let.rs
crates/ide_assists/src/handlers/replace_unwrap_with_match.rs
crates/ide_assists/src/handlers/wrap_return_type_in_result.rs
crates/ide_assists/src/tests/generated.rs
crates/ide_assists/src/utils.rs
crates/ide_db/src/helpers/merge_imports.rs
crates/ide_db/src/ty_filter.rs
crates/syntax/src/ast/make.rs

internal: introduce `ast::make::ext` module with common shortcuts

---

crates/ide/src/typing.rs

cc https://github.com/rust-analyzer/rust-analyzer/issues/8636
bors r+

feat: auto-insert `}` when typing `{` in use item

---

crates/ide/src/typing/on_enter.rs

feat: auto-indent use tree lists

---

crates/ide/src/doc_links.rs

Enable OPTION::ENABLE_TASKLISTS in pulldown_cmark

---

crates/ide_assists/src/handlers/move_module_to_file.rs

fix: Keep doc comments and outer attrs on "Move module to file" assist

---

crates/hir_def/src/body.rs
crates/syntax/src/parsing.rs
docs/dev/style.md

minor: Cleanup imports

---

crates/hir_expand/src/builtin_macro.rs
crates/hir_expand/src/name.rs

feat: Implement bulitin macro `concat_idents`

---

Cargo.lock
crates/ide_db/src/helpers/merge_imports.rs
crates/syntax/Cargo.toml
crates/syntax/src/algo.rs
crates/syntax/src/ast.rs
crates/syntax/src/ast/edit.rs
crates/syntax/src/ast/make.rs
docs/dev/style.md

internal: remove SyntaxRewriter

---

crates/ide_assists/src/utils.rs
crates/syntax/src/ast/edit.rs
crates/syntax/src/ast/edit_in_place.rs

internal: use more mutable APIs

---

crates/rust-analyzer/src/integrated_benchmarks.rs

minor: more useful bench

---

crates/ide/src/matching_brace.rs
crates/ide/src/parent_module.rs
crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
crates/ide/src/syntax_highlighting/tests.rs
crates/syntax/src/parsing/text_tree_sink.rs
crates/syntax/test_data/parser/ok/0045_block_attrs.rast

Attach comments to ast::Impl

---

crates/ide_assists/src/assist_context.rs
crates/ide_assists/src/handlers/auto_import.rs
crates/ide_assists/src/handlers/expand_glob_import.rs
crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
crates/ide_assists/src/handlers/introduce_named_lifetime.rs
crates/ide_assists/src/handlers/merge_imports.rs
crates/ide_assists/src/handlers/move_bounds.rs
crates/ide_assists/src/handlers/pull_assignment_up.rs
crates/ide_assists/src/handlers/reorder_fields.rs
crates/ide_assists/src/handlers/reorder_impl.rs
crates/ide_assists/src/handlers/replace_impl_trait_with_generic.rs
crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs

minor: use uniform names

---

crates/ide_assists/src/handlers/fill_match_arms.rs
crates/syntax/src/ast/edit.rs
crates/syntax/src/ast/edit_in_place.rs

internal: use mutable trees when filling match arms

---

crates/ide/src/syntax_highlighting/test_data/highlighting.html
crates/ide/src/syntax_highlighting/tests.rs
crates/rust-analyzer/src/to_proto.rs

Tag Self in impls as a TypeAlias

---

docs/user/manual.adoc

minor: and one more recipe for ace

---

crates/ide/src/diagnostics/fixes/fill_missing_fields.rs
crates/ide/src/diagnostics/fixes/remove_semicolon.rs
crates/ide/src/diagnostics/fixes/replace_with_find_map.rs
crates/syntax/src/ast/edit_in_place.rs

fix: don't add extra whitespace around fields

---

crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/nameres/tests.rs

Ignore macro import from `extern crate self`

---

crates/ide_assists/src/handlers/extract_function.rs

The extract function assist will check for an AWAIT_EXPR or AWAIT_KW in the body and if found, will add async to the generated function.
closes #8232

Extract function assist will add async if required

---

crates/hir_def/src/nameres/collector.rs

internal: Simplify `DefCollector::resolve_macros`

---

crates/rust-analyzer/src/caps.rs
docs/dev/lsp-extensions.md

feat: allow clients to feature detect symbol filtering

---

crates/ide_assists/src/handlers/add_explicit_type.rs

In
```rust
let name @ () = ();
```
an explicit type should be inserted after the pattern, not just after the name.
`let` statement defined as `LetStmt = Attr* 'let' Pat (':' Type)? '=' initializer:Expr ';'`

fix: add_explicit_type produces invalid code on `@` patterns

---

crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/nameres/tests/macros.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/pull/8882#issuecomment-844379170
bors r+

fix: fix derive collection after unresolved attribute fallback

---

crates/hir_def/src/nameres/collector.rs
crates/hir_expand/src/lib.rs

...without using them yet
bors r+

internal: Track in-scope derive helpers during nameres

---

crates/ide_assists/src/handlers/auto_import.rs
docs/user/manual.adoc

Update outdated auto-import documentation

---

crates/ide_assists/src/handlers/merge_imports.rs
crates/ide_db/src/helpers/merge_imports.rs
crates/stdx/src/lib.rs
crates/syntax/src/ast/node_ext.rs

minor: Don't compare ast::Visibility by stringifying

---

crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/nameres/tests/macros.rs

internal: resolve derive helpers

---

crates/hir/src/db.rs
crates/hir/src/diagnostics.rs
crates/ide/src/display/navigation_target.rs
crates/ide/src/folding_ranges.rs
crates/ide_assists/src/assist_context.rs
crates/ide_assists/src/path_transform.rs
crates/profile/src/lib.rs
crates/profile/src/memory_usage.rs
crates/profile/src/stop_watch.rs
crates/project_model/src/cargo_workspace.rs
crates/project_model/src/lib.rs
crates/project_model/src/project_json.rs
crates/syntax/fuzz/fuzz_targets/parser.rs
crates/syntax/fuzz/fuzz_targets/reparse.rs
crates/syntax/src/algo.rs
crates/syntax/src/fuzz.rs
crates/syntax/src/parsing/text_tree_sink.rs
crates/syntax/src/ptr.rs
crates/tt/src/buffer.rs
xtask/src/tidy.rs

Add more docs

---

crates/hir_expand/src/name.rs
crates/mbe/src/subtree_source.rs
crates/mbe/src/syntax_bridge.rs
crates/mbe/src/tt_iter.rs
crates/parser/src/grammar.rs
crates/parser/src/grammar/attributes.rs
crates/parser/src/grammar/expressions.rs
crates/parser/src/grammar/expressions/atom.rs
crates/parser/src/grammar/items.rs
crates/parser/src/grammar/items/adt.rs
crates/parser/src/grammar/items/consts.rs
crates/parser/src/grammar/items/traits.rs
crates/parser/src/grammar/items/use_item.rs
crates/parser/src/grammar/params.rs
crates/parser/src/grammar/paths.rs
crates/parser/src/grammar/patterns.rs
crates/parser/src/grammar/type_args.rs
crates/parser/src/grammar/type_params.rs
crates/parser/src/grammar/types.rs
crates/parser/src/parser.rs
crates/parser/src/syntax_kind.rs
xtask/src/tidy.rs

Add even more docs

---

crates/hir_ty/src/diagnostics/expr.rs
xtask/src/tidy.rs

That was easier than expected.

Add last remaining module docstring

---

xtask/src/dist.rs

internal: try enabling debug info for releases

---

xtask/src/dist.rs

internal: Drop uncompressed release artifacts and those following the old naming convention

---

docs/user/manual.adoc

I'm not sure what to write there but this seems fine
https://github.com/simrat39/rust-tools.nvim/issues/16

docs(manual): Add rust-tools.nvim to nvim-lsp

---

crates/hir/src/lib.rs
crates/hir/src/semantics.rs
crates/hir_ty/src/lib.rs
crates/ide_completion/src/completions/dot.rs

- and add some better checking for similar bugs

internal: Fix #8931

---

crates/ide/src/inlay_hints.rs

Minor: fix comment style

---

crates/hir/src/source_analyzer.rs
crates/ide/src/hover.rs
crates/ide_assists/src/lib.rs

Correctly resolve crate name in use paths when import shadows it

---

crates/ide_db/src/ty_filter.rs
editors/code/src/snippets.ts

minor: align import style with styleguide

---

crates/hir_def/src/item_tree.rs

internal: document ItemTree design

---

crates/ide_assists/src/handlers/generate_getter.rs
crates/ide_assists/src/tests/generated.rs

feat: generate getter avoids generating types like `&Vec<T>`

---

editors/code/src/config.ts

fix: can download server binary on windows again

---

xtask/src/dist.rs

internal: try re-enabling debug info on releases again

---

crates/hir/src/display.rs
crates/hir_def/src/data.rs
crates/hir_def/src/generics.rs
crates/hir_def/src/intern.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_def/src/item_tree/pretty.rs
crates/hir_def/src/path.rs
crates/hir_def/src/path/lower.rs
crates/hir_def/src/type_ref.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/lower.rs

Saves a few MB, but not much
bors r+

internal: intern `TypeBound` and `GenericArgs`

---

docs/user/manual.adoc

docs: fix binary installation instructions

---

docs/user/manual.adoc

fix: Update download instructions

---

crates/hir/src/semantics.rs
crates/hir_expand/src/db.rs
crates/hir_ty/src/lower.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/lib.rs

internal: rename hypothetical -> speculative

---

crates/hir_expand/src/db.rs
crates/hir_expand/src/hygiene.rs
crates/hir_expand/src/lib.rs
crates/mbe/src/lib.rs
crates/mbe/src/syntax_bridge.rs
crates/mbe/src/tests/expand.rs
crates/mbe/src/token_map.rs

internal: minor `TokenMap` cleanups

---

crates/hir_def/src/attr.rs
crates/hir_def/src/intern.rs
crates/hir_def/src/nameres/collector.rs

internal: intern `AttrInput`

---

crates/ide/src/goto_type_definition.rs

Example:
```rust
struct A;
struct B {
a/*<- cursor*/: A,
}
```
Go to type definition used to not work on this position. It now goes to
`A` as expected.

feat: Add go to type definition for struct fields within struct

---

crates/hir_ty/src/infer.rs
crates/hir_ty/src/tests/traits.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8907
bors r+

fix: Fix type inference not working for new Try trait

---

crates/hir_def/src/resolver.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/tests/traits.rs

Consider trait to be in scope for trait-impls

---

crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/completions/snippet.rs

fix: don't show pd/ppd completions where it shouldn't be

---

crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/test_data/highlighting.html
crates/ide/src/syntax_highlighting/tests.rs

Sorry about forgetting to test this in my last PR.

Fix bug where library functions were not highlighted as such

---

editors/code/src/run.ts

minor: explicitly set the focus to false

---

crates/ide/src/annotations.rs

This moves annotations/code lenses below attributes in items, bringing them inline with functions where this is already the case. This is done by changing the annotations covering range to just the name node's range which is also more inline with what the lsp expects which is that the range should ideally only cover a single line. 
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9000
bors r+

minor: Move annotations below item attributes

---

crates/ide/src/syntax_highlighting.rs
crates/ide/src/syntax_highlighting/tags.rs

minor: Document semantic token modifiers

---

crates/hir_expand/src/eager.rs
crates/hir_ty/src/infer/coerce.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs
crates/ide_assists/src/handlers/expand_glob_import.rs
crates/project_model/src/build_data.rs
crates/project_model/src/cargo_workspace.rs

Internal: `clippy::redundant_clone` fixes

---

crates/ide_completion/src/completions/unqualified_path.rs

fix: remove undesired completions from trait/impl blocks

---

crates/ide_completion/src/completions/pattern.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/render.rs

Set `record_pat_syntax` more precisely in CompletionContext

---

crates/ide_completion/src/completions/flyimport.rs
crates/ide_completion/src/completions/lifetime.rs
crates/ide_completion/src/completions/macro_in_item_position.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/context.rs

internal: simplify

---

xtask/src/dist.rs

internal: disable debuginfo afterall

---

crates/hir/src/display.rs
crates/hir_def/src/data.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_def/src/item_tree/pretty.rs
crates/hir_def/src/item_tree/tests.rs

internal: Don't store supertraits in ItemTree

---

crates/ide_completion/src/completions/macro_in_item_position.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/patterns.rs

Complete modules in assoc item lists

---

crates/hir_def/src/nameres/tests/incremental.rs
crates/hir_ty/src/tests.rs
crates/hir_ty/src/tests/incremental.rs

minor: test that `ItemTree` makes `hir_def` queries syntax-independent

---

crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/patterns.rs

Only complete modules in empty use-statements

---

crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/patterns.rs

Complete keywords in (Assoc)ItemList with leading attribute

---

crates/ide/src/annotations.rs

minor: Move runnable lenses below attributes

---

crates/ide/src/folding_ranges.rs
crates/rust-analyzer/src/to_proto.rs

Folding range for return types

---

crates/base_db/src/fixture.rs
crates/ide/src/fixture.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/test_utils.rs
crates/ide_db/src/call_info/tests.rs
crates/ide_db/src/traits/tests.rs
crates/test_utils/src/lib.rs

internal: Implement prev sibling determination for `CompletionContext `

---

crates/hir_def/src/data.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_def/src/item_tree/pretty.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/tests/traits.rs

hir_ty: use async ret type for inference inside async bodies

---

crates/base_db/src/input.rs
crates/hir/src/lib.rs
crates/hir_def/src/nameres/collector.rs
crates/hir_def/src/nameres/proc_macro.rs
crates/hir_expand/src/lib.rs

Should help with completion of derives. cc @Veykril 
bors r+

internal: Thread proc-macro types through the HIR

---

Cargo.lock
crates/hir_ty/Cargo.toml
crates/syntax/Cargo.toml

internal: Bump deps

---

crates/ide_completion/src/completions/attribute.rs

Fix incorrect prefer_inner calls on some attribute completions

---

crates/ide_completion/src/completions/fn_param.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/mod_.rs
crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/patterns.rs

internal: Move more `CompletionContext` fields to `ImmediateLocation`

---

Cargo.toml

forgot to turn this back on in https://github.com/rust-analyzer/rust-analyzer/pull/9069

minor: reenable incremental release builds

---

crates/ide_completion/src/completions.rs
crates/ide_completion/src/completions/lifetime.rs
crates/ide_completion/src/completions/macro_in_item_position.rs
crates/ide_completion/src/completions/pattern.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/render.rs
crates/ide_completion/src/render/enum_variant.rs
crates/ide_completion/src/render/function.rs
crates/ide_completion/src/render/macro_.rs

internal: Use `Name`s instead of Strings in the completion rendering api

---

crates/ide_completion/src/completions.rs
crates/ide_completion/src/completions/dot.rs
crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/config.rs
crates/ide_completion/src/render.rs
crates/ide_completion/src/render/function.rs
crates/ide_completion/src/test_utils.rs
crates/rust-analyzer/src/config.rs
crates/rust-analyzer/src/integrated_benchmarks.rs
crates/rust-analyzer/src/to_proto.rs
docs/dev/architecture.md
docs/user/generated_config.adoc
editors/code/package.json

feat: Complete fields and methods with `self.` prefixed when inside methods

---

crates/ide_completion/src/completions/attribute.rs

bors r+
fixes https://github.com/rust-analyzer/rust-analyzer/issues/9076

Don't take the parent kind of trailing attributes in attr completion

---

docs/dev/architecture.md

minor: expand docs a tiny bit

---

crates/ide/src/runnables.rs

add support of impl block for doctest into runnables

---

crates/proc_macro_srv/src/tests/utils.rs

Not entirely sure what's going wrong in https://github.com/rust-analyzer/rust-analyzer/pull/9084, but this might fix it?
bors r+

minor: try fixing proc_macro_srv tests

---

crates/hir_ty/src/diagnostics.rs
crates/hir_ty/src/diagnostics/decl_check.rs

fix: avoid panics in match case diagnostic

---

editors/code/src/tasks.ts

fix: fix shell injection in task spawning

---

crates/syntax/src/tests.rs

minor: remove debug print

---

editors/code/src/main.ts

Closes https://github.com/rust-analyzer/rust-analyzer/issues/9082

Fix opening single files

---

crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/tests/simple.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8100.

hir_ty: use correct receiver_ty in method resolution

---

crates/hir_def/src/nameres/collector.rs
crates/hir_expand/src/name.rs

should fix https://github.com/rust-analyzer/rust-analyzer/issues/9101
bors r+

minor: Fall back to legacy prelude

---

crates/ide_assists/src/handlers/extract_type_alias.rs

fix: make "extract type alias" place extracted type alias outside of impl

---

crates/rust-analyzer/src/config.rs
docs/user/generated_config.adoc
editors/code/package.json

Document that `addCallArgumentSnippets` requires `addCallParenthesis

---

crates/ide/src/inlay_hints.rs

Reorganize inlay_hints tests

---

crates/ide_assists/src/handlers/inline_local_variable.rs

fix: Don't inline mutable locals in 'inline_local_variable'

---

crates/ide_completion/src/completions/postfix/format_like.rs

minor: Fix incorrect list nesting in format_like feature description

---

crates/hir_def/src/attr.rs
crates/ide_completion/src/completions/attribute.rs
crates/ide_completion/src/completions/attribute/derive.rs
crates/ide_completion/src/completions/attribute/lint.rs

Nothing fancy as all the std derives aren't really documented though maybe some 3rd party crates document them equally to their trait counterparts.

feat: Render documentation for derive completion

---

crates/ide/src/goto_definition.rs

feat: Support goto-definition for include macros input path

---

crates/rust-analyzer/src/handlers.rs

Fix incorrect config usage in hover references

---

crates/ide_completion/src/completions/dot.rs
crates/ide_completion/src/completions/flyimport.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/postfix.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/snippet.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/render.rs
crates/ide_completion/src/render/builder_ext.rs
crates/ide_completion/src/render/macro_.rs

Doesn't make the code much simpler yet.
bors r+

internal: Reduce the number of direct fields in `CompletionContext` some more

---

docs/dev/README.md

Also some other cleanups while I'm there.

Clarify label documentation

---

editors/code/src/ctx.ts

Now, when you click the little status bar text, it will automatically reload the server. I don't think I've ever seen anyone click it randomly, and, it's there to save you a few clicks.

QOL: VSCode status bar icon on click now shows server status

---

crates/hir/src/lib.rs
crates/hir/src/semantics.rs
crates/ide_completion/src/completions.rs
crates/ide_completion/src/completions/attribute.rs
crates/ide_completion/src/completions/flyimport.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/render.rs

Will add some proper tests in a bit

Don't complete values in type position

---

crates/ide/src/expand_macro.rs

This allows expanding attribute macros on fn-like macro invocations
bors r+

fix: Prefer attr macros in "expand macro recursively"

---

crates/ide_assists/src/handlers/remove_unused_param.rs

See the added test for description

Don't suggest Remove unused param in trait impls

---

crates/ide_completion/src/render.rs
crates/ide_completion/src/render/function.rs

fix: Don't allow lookup by self for unprefixed self access completions

---

crates/hir/src/lib.rs
crates/ide/src/references/rename.rs
crates/ide_db/src/search.rs

Item search now respects trait impl items

---

crates/ide/src/goto_implementation.rs
crates/ide_completion/src/render.rs

minor: Replace some AssocItem::containing_trait calls trait_or_trait_impl

---

crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/test_data/highlighting.html
crates/ide/src/syntax_highlighting/tests.rs

fix: Highlight tuple field accesses correctly

---

crates/ide_completion/src/completions.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/render/type_alias.rs

Complete associated types in dyn and impl trait

---

crates/profile/src/memory_usage.rs

minor: squelch "unused" warning

---

crates/hir/src/diagnostics.rs
crates/hir/src/lib.rs
crates/hir_ty/src/diagnostics.rs
crates/hir_ty/src/diagnostics/unsafe_check.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/lib.rs
crates/ide/src/diagnostics.rs

internal: move inference diagnostics to hir

---

Cargo.lock
crates/hir/Cargo.toml
crates/hir/src/lib.rs
crates/hir_ty/src/diagnostics/unsafe_check.rs

minor: optimize

---

crates/ide_completion/src/completions/flyimport.rs

Fix some typos in flyimport docs

---

crates/hir_def/src/body/tests/block.rs
crates/hir_ty/src/diagnostics/match_check/deconstruct_pat.rs
crates/ide/src/diagnostics.rs
crates/ide_completion/src/render.rs
xtask/src/tidy.rs

internal: check that coverage marks are always paired

---

crates/hir/src/diagnostics.rs
crates/hir/src/lib.rs
crates/hir_def/src/nameres/tests/diagnostics.rs
crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/fixes.rs
crates/ide/src/diagnostics/unresolved_module.rs
xtask/src/tidy.rs

internal: start new diagnostics API

---

crates/hir/src/diagnostics.rs
crates/hir/src/lib.rs
crates/hir_ty/src/diagnostics/expr.rs
crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/fixes.rs
crates/ide/src/diagnostics/missing_fields.rs
crates/ide/src/diagnostics/unresolved_module.rs

internal: unified missing fields diagnostic

---

crates/hir/src/diagnostics.rs
crates/hir/src/lib.rs
crates/hir_def/src/nameres/tests/diagnostics.rs
crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/unresolved_extern_crate.rs

internal: refactor unresolved extern crate diagnostic

---

crates/hir/src/diagnostics.rs
crates/hir/src/lib.rs
crates/hir_def/src/nameres/tests/diagnostics.rs
crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/unresolved_import.rs
crates/ide/src/diagnostics/unresolved_macro_call.rs
crates/ide/src/diagnostics/unresolved_module.rs

internal: refactor unresolved macro call diagnostic

---

crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/inactive_code.rs
crates/ide/src/diagnostics/macro_error.rs
crates/ide/src/fixture.rs
crates/ide/src/goto_definition.rs
crates/test_utils/src/lib.rs

internal: check diagnostics in all files and not just the first one

---

crates/ide/src/diagnostics.rs
crates/ide/src/diagnostics/field_shorthand.rs
crates/ide/src/diagnostics/unresolved_module.rs
crates/rust-analyzer/src/handlers.rs

internal: diagnostic code is mandatory

---

crates/ide/src/references/rename.rs

fix: don't use display-related functionality where semantics matters

---

crates/ide/src/references/rename.rs

internal: prepare to move rename to base_db 

---

crates/ide_completion/src/completions/unqualified_path.rs

minor: Add assoc type in trait bound completion test

---

Cargo.lock
crates/hir_ty/Cargo.toml

internal: don't pull tracing via chalk

---

crates/ide/src/goto_type_definition.rs

feat: Support goto type for field expressions and patterns

---

crates/ide_diagnostics/src/handlers/break_outside_of_loop.rs
crates/ide_diagnostics/src/handlers/field_shorthand.rs
crates/ide_diagnostics/src/handlers/inactive_code.rs
crates/ide_diagnostics/src/handlers/incorrect_case.rs
crates/ide_diagnostics/src/handlers/macro_error.rs
crates/ide_diagnostics/src/handlers/mismatched_arg_count.rs
crates/ide_diagnostics/src/handlers/missing_fields.rs
crates/ide_diagnostics/src/handlers/missing_match_arms.rs
crates/ide_diagnostics/src/handlers/missing_unsafe.rs
crates/ide_diagnostics/src/handlers/no_such_field.rs
crates/ide_diagnostics/src/handlers/remove_this_semicolon.rs
crates/ide_diagnostics/src/handlers/replace_filter_map_next_with_find_map.rs
crates/ide_diagnostics/src/handlers/unlinked_file.rs
crates/ide_diagnostics/src/handlers/unresolved_extern_crate.rs
crates/ide_diagnostics/src/handlers/unresolved_import.rs
crates/ide_diagnostics/src/handlers/unresolved_macro_call.rs
crates/ide_diagnostics/src/handlers/unresolved_module.rs
crates/ide_diagnostics/src/handlers/useless_braces.rs
crates/ide_diagnostics/src/lib.rs

internal: refactor diagnostics more

---

crates/hir/src/has_source.rs
crates/hir_def/src/generics.rs
crates/hir_def/src/item_tree/lower.rs
crates/ide/src/display/navigation_target.rs
crates/ide_db/src/rename.rs
crates/ide_diagnostics/src/handlers/break_outside_of_loop.rs
crates/ide_diagnostics/src/handlers/field_shorthand.rs
crates/ide_diagnostics/src/handlers/inactive_code.rs
crates/ide_diagnostics/src/handlers/incorrect_case.rs
crates/ide_diagnostics/src/handlers/macro_error.rs
crates/ide_diagnostics/src/handlers/mismatched_arg_count.rs
crates/ide_diagnostics/src/handlers/missing_fields.rs
crates/ide_diagnostics/src/handlers/missing_match_arms.rs
crates/ide_diagnostics/src/handlers/missing_unsafe.rs
crates/ide_diagnostics/src/handlers/no_such_field.rs
crates/ide_diagnostics/src/handlers/remove_this_semicolon.rs
crates/ide_diagnostics/src/handlers/replace_filter_map_next_with_find_map.rs
crates/ide_diagnostics/src/handlers/unlinked_file.rs
crates/ide_diagnostics/src/handlers/unresolved_extern_crate.rs
crates/ide_diagnostics/src/handlers/unresolved_import.rs
crates/ide_diagnostics/src/handlers/unresolved_macro_call.rs
crates/ide_diagnostics/src/handlers/unresolved_module.rs
crates/ide_diagnostics/src/handlers/useless_braces.rs
crates/ide_diagnostics/src/lib.rs

internal: more natural order of sources for TypeParam

---

crates/rust-analyzer/src/config.rs
editors/code/package.json
xtask/src/dist.rs

Addresses https://github.com/rust-analyzer/rust-analyzer/issues/9174#issue-913980665.

fix: Use objects instead of bools for markers in package.json

---

crates/hir_def/src/nameres/collector.rs

minor: add a test variation

---

crates/ide_assists/src/handlers/qualify_path.rs
crates/ide_assists/src/handlers/replace_impl_trait_with_generic.rs
crates/ide_db/src/helpers/insert_use/tests.rs

internal: cleanup tests

---

crates/ide/src/goto_definition.rs
crates/ide_assists/src/handlers/fix_visibility.rs
crates/ide_assists/src/handlers/generate_function.rs
crates/ide_completion/src/completions/attribute/derive.rs
crates/syntax/test_data/parser/ok/0011_outer_attribute.rast
crates/syntax/test_data/parser/ok/0011_outer_attribute.rs
xtask/src/tidy.rs

internal: enforce no #[ignore] and no #[should_panic]

---

xtask/src/tidy.rs

minor: fix typo

---

crates/base_db/src/fixture.rs
crates/hir_ty/src/tests/coercion.rs
crates/hir_ty/src/tests/method_resolution.rs
crates/hir_ty/src/tests/regression.rs
crates/hir_ty/src/tests/simple.rs
crates/hir_ty/src/tests/traits.rs
crates/ide/src/hover.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/render.rs
crates/rust-analyzer/tests/slow-tests/support.rs
crates/test_utils/src/fixture.rs
crates/test_utils/src/lib.rs
crates/test_utils/src/minicore.rs

Clearly, we need one more fixed point iteration loop!

internal: introduce minicore -- a subset of libcore for testing

---

crates/ide/src/lib.rs

fix: Show diagnostic fixes before assists

---

crates/ide_completion/src/completions/attribute/derive.rs

internal: Add builtin derives to attribute completion fixtures

---

crates/ide/src/inlay_hints.rs
crates/ide_assists/src/handlers/replace_for_loop_with_for_each.rs
crates/test_utils/src/fixture.rs
crates/test_utils/src/minicore.rs

internal: minimize minicore

---

crates/ide_assists/src/handlers/move_module_to_file.rs
crates/syntax/src/ast/node_ext.rs

fix: Create modules in correct directory for nested modules in move_module assist

---

crates/ide_completion/src/completions/flyimport.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/render/builder_ext.rs
crates/ide_completion/src/render/macro_.rs
crates/ide_completion/src/tests.rs
crates/ide_completion/src/tests/use_tree.rs

internal: Refine and test UseTree completions

---

crates/ide_completion/src/completions/attribute.rs
crates/ide_completion/src/completions/attribute/derive.rs
crates/ide_completion/src/completions/attribute/lint.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/lifetime.rs
crates/ide_completion/src/completions/mod_.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/snippet.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/tests.rs
crates/ide_completion/src/tests/items.rs

internal: Move out item specific completion tests

---

crates/ide/src/hover.rs
crates/ide_assists/src/handlers/generate_default_from_enum_variant.rs
crates/ide_assists/src/handlers/generate_default_from_new.rs
crates/ide_completion/src/completions/record.rs
crates/ide_db/src/helpers/famous_defs_fixture.rs
crates/test_utils/src/minicore.rs

internal: add default to minicore

---

crates/ide/src/hover.rs
crates/ide_assists/src/handlers/convert_into_to_from.rs
crates/ide_assists/src/handlers/generate_from_impl_for_enum.rs
crates/ide_db/src/helpers/famous_defs_fixture.rs
crates/test_utils/src/minicore.rs

internal: add From to minicore

---

crates/ide/src/hover.rs
crates/ide_assists/src/handlers/apply_demorgan.rs
crates/ide_assists/src/tests.rs
crates/ide_db/src/helpers/famous_defs_fixture.rs
crates/test_utils/src/minicore.rs

internal: add derive and ord support to minicore

---

xtask/src/tidy.rs

Minor: Fix line numbering in tidy

---

crates/ide/src/hover.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/test_utils/src/minicore.rs

internal: add Copy to minicore

---

crates/hir_ty/src/tests/regression.rs
crates/hir_ty/src/tests/simple.rs
crates/hir_ty/src/tests/traits.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_completion/src/completions/dot.rs
crates/ide_completion/src/context.rs

minor: use minicore

---

crates/base_db/src/fixture.rs
crates/hir_ty/src/tests/regression.rs
crates/hir_ty/src/tests/simple.rs
crates/hir_ty/src/tests/traits.rs
crates/ide/src/hover.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_completion/src/completions/dot.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/render.rs
crates/test_utils/src/minicore.rs

internal: add index to minicore

---

crates/ide_assists/src/handlers/auto_import.rs
crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
crates/ide_assists/src/tests.rs
crates/ide_completion/src/item.rs
crates/ide_completion/src/tests.rs
crates/ide_db/src/helpers/insert_use.rs
crates/ide_db/src/helpers/insert_use/tests.rs
crates/rust-analyzer/src/config.rs
crates/rust-analyzer/src/integrated_benchmarks.rs
crates/rust-analyzer/src/to_proto.rs
crates/syntax/src/ast/node_ext.rs
docs/user/generated_config.adoc
editors/code/package.json

On by default as I feel like this is something the majority would prefer.
Closes #8490

feat: Allow to disable import insertion on single path glob imports

---

crates/ide/src/rename.rs

fix: rename works when invoked on a reference

---

crates/ide_completion/src/context.rs
crates/ide_completion/src/render.rs

fix: don't add duplicate `&` during completion

---

crates/ide/src/typing.rs

Checks that the token at the cursor is `L_CURLY`.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9351
bors r+

Don't insert `}` when typing `{` in string

---

crates/base_db/src/fixture.rs
crates/base_db/src/input.rs
crates/cfg/src/lib.rs
crates/hir/src/lib.rs
crates/ide/src/lib.rs
crates/ide_completion/src/completions/attribute.rs
crates/ide_completion/src/completions/attribute/cfg.rs
crates/project_model/src/workspace.rs

This will close #5398 and it also adds some completion for cfg options.

Improve completion of cfg attributes

---

crates/syntax/src/ptr.rs

feature: massively improve performance for large files

---

crates/proc_macro_test/build.rs

Fix #9360 
r? @jonas-schievink

Set explicit target directory to avoid cargo deadlock

---

crates/ide/src/hover.rs
crates/ide/src/lib.rs
crates/rust-analyzer/src/config.rs
crates/rust-analyzer/src/handlers.rs

Split hover actions config into its own config struct

---

crates/syntax/src/ptr.rs

Document perf characteristic of to_node

---

crates/ide/src/expand_macro.rs

fix: Prefer identifier tokens in expand_macro

---

crates/hir/src/semantics/source_to_def.rs

internal: document source_to_def and it's connection to Kotlin&Roslyn

---

crates/hir/src/semantics/source_to_def.rs

minor: extend source_to_def docs

---

crates/hir/src/lib.rs
crates/hir/src/semantics/source_to_def.rs

intenral: dont export impl details

---

crates/ide/src/call_hierarchy.rs
crates/ide/src/doc_links.rs
crates/ide/src/expand_macro.rs
crates/ide/src/goto_definition.rs
crates/ide/src/goto_type_definition.rs
crates/ide/src/hover.rs
crates/ide/src/lib.rs
crates/ide/src/move_item.rs
crates/ide_db/src/helpers.rs

internal: Factor out `pick_best_token` ide pattern into `ide_db`

---

crates/hir_def/src/item_scope.rs
crates/hir_def/src/nameres/collector.rs

minor: clarify naming

---

crates/hir_def/src/item_scope.rs
crates/hir_def/src/nameres/collector.rs

internal: count ItemScopes

---

.github/workflows/ci.yaml
crates/stdx/src/lib.rs
crates/stdx/src/process.rs

Fix compilation on WASM

---

crates/mbe/src/syntax_bridge.rs

Part of https://github.com/rust-analyzer/rust-analyzer/issues/9358, this fixes the first cause of the stack overflow there. Unfortunately we now run into a stack overflow in the parser.
bors r+

internal: Rewrite token tree lowering to use an explicit stack

---

crates/project_model/src/workspace.rs

Fixes #7715 
For example, if a sub-crate includes sets the path='../somewhere-else/lib.rs', the files will not be in pkg_root , but in the target root's parent.
It may actually be in root.parent().parent(), I'm not sure about that.
At the moment it is just a fix, are there any relevant tests that this could go in? I've got about 1 brain cell left... but im happy to add tests where appropriate.

Include extra targets when the pkg_root is not the same as the target root.

---

crates/ide/src/highlight_related.rs

fix: Fix break point highlighting not considering outer labels

---

crates/ide/src/rename.rs
crates/ide_db/src/search.rs

fix: Fix renaming associated trait items with colliding names

---

crates/proc_macro_srv/src/tests/mod.rs
crates/proc_macro_test/imp/src/lib.rs

internal: add cloning macro fixture

---

crates/project_model/src/lib.rs

intenral: small improvements to compile time

---

crates/project_model/src/workspace.rs

minor: Avoid redundant clone

---

crates/ide/src/hover.rs
crates/ide/src/references.rs
crates/ide_db/src/defs.rs
crates/syntax/src/display.rs

Unfortunately not (yet) unit-testable I believe

fix: Make hover on attribute paths work again

---

crates/rust-analyzer/src/reload.rs

fix: Watch for Cargo.toml and .lock changes

---

Cargo.lock
crates/syntax/Cargo.toml

This brings in the new hashbrown for better compile times.

Cargo update and pull in the new rowan

---

crates/ide_assists/src/handlers/split_import.rs
crates/ide_db/src/defs.rs
crates/syntax/src/ast/node_ext.rs

fix: Don't classify paths inside attribute TokenTrees

---

crates/ide_assists/src/handlers/merge_match_arms.rs
crates/ide_db/src/helpers/insert_use.rs
crates/ide_db/src/helpers/insert_use/tests.rs

I think this should be the last fix needed for this(🤞)
bors r+

internal: Add ModuleOrItem guess to import granularity guessing

---

crates/ide/src/hover.rs

minor: Add `goto_type_action` for field hovers

---

crates/ide_assists/src/handlers/early_return.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_assists/src/handlers/fill_match_arms.rs
crates/ide_assists/src/handlers/replace_if_let_with_match.rs
crates/ide_assists/src/handlers/replace_unwrap_with_match.rs
crates/syntax/src/ast/edit.rs
crates/syntax/src/ast/make.rs

minor: Remove make::match_arm_with_guard

---

crates/ide/src/runnables.rs

fix: Fix runnables using wrong file ids for module doctests

---

crates/ide_assists/src/handlers/unmerge_use.rs
crates/ide_assists/src/handlers/wrap_return_type_in_result.rs
crates/ide_assists/src/tests/generated.rs
crates/ide_db/src/helpers.rs

internal: wrap_return_type_in_result works on the HIR

---

crates/ide_assists/src/handlers/unmerge_use.rs
crates/ide_assists/src/handlers/wrap_return_type_in_result.rs

minor: Don't hide meta lines

---

crates/ide_assists/src/handlers/early_return.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_assists/src/handlers/fill_match_arms.rs
crates/ide_assists/src/handlers/generate_function.rs
crates/ide_assists/src/handlers/inline_call.rs
crates/ide_assists/src/handlers/inline_function.rs
crates/ide_assists/src/handlers/replace_unwrap_with_match.rs
crates/ide_assists/src/lib.rs
crates/ide_assists/src/tests/generated.rs
crates/ide_db/src/ty_filter.rs
crates/syntax/src/ast/make.rs

feat: Make `inline_function` work on methods

---

crates/syntax/src/tests.rs

minor: better error message

---

crates/ide_completion/src/tests/sourcegen.rs

minor: fix lint completion sourcegen

---

Cargo.lock
crates/rust-analyzer/Cargo.toml
crates/rust-analyzer/tests/slow-tests/main.rs
crates/rust-analyzer/tests/slow-tests/tidy.rs
xtask/Cargo.toml
xtask/src/main.rs

internal: make `xtask` lighter

---

Cargo.lock
crates/rust-analyzer/Cargo.toml
crates/rust-analyzer/src/to_proto.rs
crates/rust-analyzer/tests/slow-tests/main.rs
crates/rust-analyzer/tests/slow-tests/tidy.rs
docs/dev/style.md
xtask/Cargo.toml
xtask/src/main.rs

minor: style

---

crates/rust-analyzer/src/handlers.rs
crates/rust-analyzer/src/lsp_ext.rs
crates/rust-analyzer/src/to_proto.rs
docs/dev/lsp-extensions.md

internal: better factoring for to_proto::completion

---

crates/ide/src/lib.rs
crates/ide_completion/src/item.rs
crates/ide_completion/src/lib.rs
crates/rust-analyzer/src/to_proto.rs

internal: make CompletionItem and SourceChange consistent

---

crates/ide_completion/src/completions/postfix.rs
crates/ide_completion/src/item.rs
crates/ide_completion/src/render.rs
crates/rust-analyzer/src/to_proto.rs

feat: always prefer postfix snippets if there's exact textual match

---

crates/syntax/src/ted.rs

minor: untangle complex condition

---

crates/ide_assists/src/handlers/inline_call.rs
crates/ide_assists/src/tests/generated.rs
crates/syntax/src/ast/edit_in_place.rs
crates/syntax/src/ast/node_ext.rs
crates/syntax/src/ted.rs

fix: Inline parameters in `inline_call` if possible

---

crates/hir_def/src/body/tests/block.rs
crates/hir_def/src/visibility.rs

https://github.com/rust-analyzer/rust-analyzer/pull/9499#discussion_r663966671
bors r+

internal: Add a coverage mark

---

crates/ide/src/join_lines.rs
crates/ide/src/lib.rs
crates/rust-analyzer/src/config.rs
crates/rust-analyzer/src/handlers.rs
docs/user/generated_config.adoc
editors/code/package.json

feat: make join lines behavior configurable

---

crates/ide/src/annotations.rs
crates/ide/src/hover.rs
crates/ide/src/inlay_hints.rs
crates/ide/src/lib.rs
crates/rust-analyzer/src/handlers.rs
docs/dev/style.md

internal: ensure consistent passing for config params

---

crates/ide_assists/src/handlers/inline_call.rs

See https://github.com/rust-analyzer/rust-analyzer/pull/9474#discussion_r663881507 for reasoning.
This still inlines single use closures and literals as naming these is usually not as useful. Prime examples being the Option/Result consuming functions like `map_or` etc.

internal: Only inline closure, literal and local arguments when used once

---

crates/ide_assists/src/handlers/auto_import.rs
crates/ide_assists/src/handlers/early_return.rs
crates/ide_assists/src/handlers/inline_local_variable.rs
crates/ide_assists/src/handlers/invert_if.rs
crates/ide_assists/src/handlers/replace_let_with_if_let.rs
crates/ide_assists/src/utils.rs

internal: Invert boolean literals in assist negation logic

---

.github/ISSUE_TEMPLATE/bug_report.md

Fix #9386 
Remove all resolved issues

Update bug_report template

---

.github/ISSUE_TEMPLATE/bug_report.md

minor: Add nightly proc macro issue to the bug report template

---

crates/ide_completion/src/completions/dot.rs

minor: Add test for trait completion label edit

---

crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/tests/regression.rs

Addresses https://github.com/rust-analyzer/rust-analyzer/pull/9526#issuecomment-876206100.

fix: Don't unify arrays with their elements

---

docs/dev/style.md

minor: one more usless type

---

crates/hir_ty/src/diagnostics/match_check.rs
crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/closure.rs
crates/hir_ty/src/infer/coerce.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs
crates/hir_ty/src/infer/unify.rs
crates/hir_ty/src/tests.rs
crates/hir_ty/src/tests/coercion.rs

cc https://github.com/rust-analyzer/rust-analyzer/issues/9475

Record coercion adjustments

---

crates/ide_assists/src/handlers/generate_function.rs
crates/syntax/src/ast/make.rs

Adding async keyword when await is present in generate_function assist

---

crates/hir_ty/src/autoderef.rs
crates/hir_ty/src/infer/coerce.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/lib.rs
crates/hir_ty/src/tests/coercion.rs
crates/hir_ty/src/tests/method_resolution.rs

Record autoderef adjustments

---

crates/ide_completion/src/completions/fn_param.rs

Solves #9522
I haven't added Arc<self> for now as there were some conflicting opinions on it

add: Adding self keyword completion in complete_fn_param

---

crates/ide_assists/src/handlers/auto_import.rs
crates/ide_db/src/helpers/import_assets.rs

Helpful for when you want to import a type in a pattern right before destructuring it.

feat: Enable `auto_import` on ident patterns

---

crates/ide_db/src/defs.rs

internal: document NameClass and NameRefClass

---

crates/hir/src/semantics.rs
crates/hir/src/source_analyzer.rs
crates/ide_assists/src/handlers/add_explicit_type.rs
crates/ide_assists/src/handlers/inline_call.rs

minor: Simplify Semantics::type_of_expr_with_coercion

---

crates/ide/src/doc_links.rs
crates/ide/src/goto_declaration.rs
crates/ide/src/goto_definition.rs
crates/ide/src/goto_implementation.rs
crates/ide/src/hover.rs
crates/ide/src/references.rs
crates/ide/src/rename.rs
crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
crates/ide_assists/src/handlers/add_turbo_fish.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_assists/src/handlers/remove_unused_param.rs
crates/ide_db/src/defs.rs
crates/ide_db/src/items_locator.rs
crates/ide_diagnostics/src/handlers/incorrect_case.rs

remove unneded special case

---

crates/sourcegen/src/lib.rs

minor: make sure that project_root works correctly

---

crates/ide/src/syntax_highlighting/highlight.rs

Makes the main logic a bit more manageable 
bors r+

internal: Split main highlighting function up into a few subfunctions 

---

crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/test_data/highlighting.html
crates/ide/src/syntax_highlighting/tests.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9578

Assign mutable semantic token modifier to assignment operators

---

crates/ide/src/goto_type_definition.rs

Return type arguments in goto_type_definition result 

---

crates/ide/src/goto_type_definition.rs

Use Type::walk for goto_type_definition

---

crates/ide_completion/src/completions/keyword.rs

Complete true and false keywords

---

crates/ide_assists/src/handlers/unwrap_block.rs

Fixes #8411
Rework the system for stripping whitespace and braces in the unwrap_block assist to allow correct unwrapping of blocks such as:
```rust
{ $0 0 }
```
into
```rust
0
```
and nested blocks, such as:
```rust
$0{
{
3
}
}
```
into
```rust
{
3
}
```
This is done by creating the `update_expr_string_with_pat` function (along with `update_expr_string` and `update_expr_string_without_newline`), which strips whitespace and braces in a way that ensures that only whitespace and a maximum of one brace are removed from the start and end of the expression string.
I have also created several tests to ensure that this functionality works correctly.

fix: Single-line and nested blocks in the `unwrap_block` assist

---

crates/ide/src/folding_ranges.rs

fix: Don't fold consecutive modules with item lists

---

crates/ide/src/folding_ranges.rs

internal: Folding ranges respect item visibilities

---

crates/ide_completion/src/tests/use_tree.rs

minor: Add regression test fo #7222

---

crates/hir_def/src/find_path.rs
crates/ide_assists/src/handlers/auto_import.rs

Follows up https://github.com/rust-analyzer/rust-analyzer/pull/8820/

minor: Explicitly connect an ambiguous import path case logic with its test

---

crates/base_db/src/fixture.rs
crates/base_db/src/input.rs
crates/ide/src/lib.rs
crates/project_model/src/cargo_workspace.rs
crates/project_model/src/workspace.rs

internal: make it clearer where IO happens

---

Cargo.lock
crates/parser/src/grammar/paths.rs
crates/parser/src/grammar/type_args.rs
crates/syntax/src/ast/generated/nodes.rs
crates/syntax/test_data/parser/inline/ok/0138_associated_type_bounds.rast
crates/syntax/test_data/parser/inline/ok/0138_associated_type_bounds.rs

Parse GATs in associated type args

---

crates/base_db/src/input.rs
docs/dev/architecture.md
docs/dev/style.md

internal: explain why we avoid serializing everything

---

crates/project_model/src/cargo_workspace.rs
crates/project_model/src/lib.rs
crates/project_model/src/manifest_path.rs
crates/project_model/src/rustc_cfg.rs
crates/project_model/src/sysroot.rs
crates/project_model/src/workspace.rs
crates/rust-analyzer/src/cargo_target_spec.rs

internal: replace some unwraps with types

---

crates/rust-analyzer/src/main_loop.rs
docs/dev/architecture.md

docs: publish Explaining Rust Analyzer series

---

Cargo.lock
lib/arena/Cargo.toml

minor: publish la_arena

---

.github/workflows/ci.yaml

internal: easier to skim CI logs

---

crates/ide_completion/src/completions/flyimport.rs
crates/ide_completion/src/item.rs

Fixes #9643
looks like there was an if condition that had to be removed.

add 'use' prefix for any auto-import

---

crates/hir/src/lib.rs
crates/hir_def/src/item_scope.rs
crates/ide/src/inlay_hints.rs
crates/ide_assists/src/handlers/expand_glob_import.rs
crates/ide_assists/src/handlers/fix_visibility.rs
crates/ide_db/src/defs.rs

internal: remove potentially slow method

---

crates/hir/src/lib.rs
crates/ide_assists/src/handlers/expand_glob_import.rs
crates/ide_assists/src/handlers/fix_visibility.rs
crates/ide_db/src/defs.rs

minor: address review comments

---

crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/tests.rs
crates/ide_completion/src/tests/visibility.rs
crates/parser/src/grammar.rs
crates/syntax/src/validation.rs

Restrict completions inside visibility modifiers

---

crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs

Also keep the path if we can't find a path to the item instead of becoming non applicable.
bors r+

Don't concat path in replace_qualified assist when they start with a keyword

---

crates/ide/src/doc_links.rs
crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/tests/visibility.rs

minor: cov-mark

---

docs/user/manual.adoc

docs: fix typo

---

crates/ide_assists/src/handlers/extract_variable.rs

fix: Don't offer extract_variable assist when there is no surrounding block

---

crates/ide_completion/src/completions/keyword.rs
crates/ide_completion/src/completions/postfix.rs
crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/tests.rs
crates/ide_completion/src/tests/item.rs
crates/ide_completion/src/tests/use_tree.rs
crates/ide_completion/src/tests/visibility.rs

Minor completions cleanup

---

crates/ide_completion/src/completions/qualified_path.rs
crates/ide_completion/src/tests/visibility.rs

Only complete ancestors and self in visibility path completions

---

crates/ide_completion/src/completions/attribute/cfg.rs
crates/ide_completion/src/completions/attribute/lint.rs
crates/ide_completion/src/completions/postfix.rs
crates/ide_completion/src/completions/postfix/format_like.rs
crates/ide_completion/src/render/const_.rs
crates/ide_completion/src/render/enum_variant.rs
crates/ide_completion/src/render/function.rs
crates/ide_completion/src/render/macro_.rs
crates/ide_completion/src/render/pattern.rs
crates/ide_completion/src/render/type_alias.rs

minor: Fix some clippy lints in ide_completion

---

.github/ISSUE_TEMPLATE/bug_report.md

minor: Remove proc macro ABI issue from bug report template

---

crates/ide/src/highlight_related.rs
crates/rust-analyzer/src/handlers.rs

minor: Fix a couple of clippy nits

---

crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs
crates/hir_ty/src/tests/patterns.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8694

fix: Fix pattern name resolution when name is also occupied in type namespace

---

crates/ide_completion/src/completions/lifetime.rs
crates/ide_completion/src/tests/predicate.rs
crates/ide_completion/src/tests/type_pos.rs

minor: Describe the current lifetime/label completion specifics

---

crates/ide/src/hover.rs
crates/ide_db/src/defs.rs

fix: Correctly classify Rename Names

---

crates/ide_completion/src/completions/dot.rs

This removes the last FIXME related to visibility and thus fixes https://github.com/rust-analyzer/rust-analyzer/issues/824
bors r+

internal: add tests for tuple struct field completion and resolve a FIXME

---

crates/ide_assists/src/handlers/fill_match_arms.rs

fix: Keep catch-all arm in fill_match_arms if it has a non-empty expression

---

crates/ide_assists/src/handlers/remove_unused_param.rs

fix: Adding remove_unused_param for method and fixing same for assoc func

---

crates/parser/src/grammar/type_args.rs
crates/syntax/test_data/parser/inline/ok/0138_associated_type_bounds.rast
crates/syntax/test_data/parser/inline/ok/0138_associated_type_bounds.rs

fix: Fix generic_arg not parsing opt_generic_arg_list properly in arg lists

---

crates/rust-analyzer/src/caps.rs
docs/dev/lsp-extensions.md

fix: add capability for "open cargo.toml" lsp extension

---

crates/ide_assists/src/handlers/add_missing_impl_members.rs
crates/ide_db/src/path_transform.rs

fix: Don't qualify self as crate in add_missing_impl_members assist

---

crates/ide/src/rename.rs
crates/ide_assists/src/handlers/extract_function.rs
crates/ide_db/src/rename.rs

Closes https://github.com/rust-analyzer/rust-analyzer/issues/7748
bors r+

fix: Refine extraction targets of extract_function assist

---

docs/dev/lsp-extensions.md

minor: drop impl-specific stuff from lsp docs

---

crates/ide/src/join_lines.rs
crates/ide/src/move_item.rs
crates/ide_assists/src/handlers/merge_match_arms.rs
crates/ide_diagnostics/src/handlers/inactive_code.rs
crates/parser/src/grammar/expressions/atom.rs
crates/syntax/src/ast/edit_in_place.rs
crates/syntax/test_data/parser/err/0032_match_arms_inner_attrs.rast
crates/syntax/test_data/parser/err/0033_match_arms_outer_attrs.rast
crates/syntax/test_data/parser/inline/ok/0055_literal_pattern.rast
crates/syntax/test_data/parser/inline/ok/0058_range_pat.rast
crates/syntax/test_data/parser/inline/ok/0059_match_arms_commas.rast
crates/syntax/test_data/parser/inline/ok/0066_match_arm.rast
crates/syntax/test_data/parser/inline/ok/0118_match_guard.rast
crates/syntax/test_data/parser/inline/ok/0120_match_arms_inner_attribute.rast
crates/syntax/test_data/parser/inline/ok/0121_match_arms_outer_attributes.rast
crates/syntax/test_data/parser/inline/ok/0156_or_pattern.rast
crates/syntax/test_data/parser/ok/0035_weird_exprs.rast
crates/syntax/test_data/parser/ok/0047_minus_in_inner_pattern.rast

fix: Attach comma token to MATCH_ARM instead of MATCH_ARM_LIST

---

crates/rust-analyzer/src/config.rs
crates/rust-analyzer/src/handlers.rs
crates/rust-analyzer/src/lsp_ext.rs
crates/rust-analyzer/src/to_proto.rs
docs/dev/lsp-extensions.md
docs/user/generated_config.adoc
editors/code/package.json
editors/code/src/client.ts

feat: gate custom clint-side commands behind capabilities

---

docs/dev/lsp-extensions.md

minor: cleanup lsp-extensions docs

---

crates/ide_assists/src/handlers/add_explicit_type.rs
crates/ide_assists/src/handlers/invert_if.rs
crates/syntax/src/ast/node_ext.rs

Closes https://github.com/rust-analyzer/rust-analyzer/issues/8886
bors r+

feat: `add_explicit_type` is applicable for closure parameters

---

crates/ide_assists/src/handlers/replace_if_let_with_match.rs
crates/ide_db/src/search.rs
crates/proc_macro_api/src/rpc.rs

minor: Replace useless types

---

crates/ide/src/hover.rs
crates/ide_assists/src/handlers/invert_if.rs

fix: Fix hover range for derive inputs

---

crates/ide_completion/src/render/function.rs
crates/profile/src/hprof.rs

internal: a bit of completion profiling

---

crates/hir_expand/src/db.rs
crates/limit/Cargo.toml
crates/limit/src/lib.rs

internal: add API to check what are the max limits in practice

---

crates/hir/src/attrs.rs
crates/ide/src/display/navigation_target.rs
crates/ide/src/doc_links.rs
crates/ide/src/hover.rs
crates/ide/src/syntax_highlighting/inject.rs
crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html

internal: `resolve_doc_path` is able to resolve to macros

---

crates/hir_def/src/resolver.rs
crates/ide_completion/src/completions/unqualified_path.rs

internal: completion cleanups

---

crates/hir/src/lib.rs
crates/hir_def/src/attr.rs
crates/hir_def/src/resolver.rs
crates/hir_ty/src/diagnostics/expr.rs
crates/hir_ty/src/display.rs
crates/hir_ty/src/infer/pat.rs
crates/ide/src/annotations.rs
docs/dev/style.md

internal: explain that we don't `ref` in style.md

---

crates/ide_assists/src/assist_context.rs
crates/ide_assists/src/handlers/inline_local_variable.rs

internal: Simplify inline_local_variable assist

---

crates/ide/src/hover.rs

fix: Fix ranged hover result range

---

Cargo.lock
crates/hir/Cargo.toml
crates/hir/src/semantics.rs
crates/hir_def/src/resolver.rs
crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/render.rs
crates/ide_completion/src/tests/expression.rs
crates/ide_completion/src/tests/item.rs
crates/ide_completion/src/tests/item_list.rs
crates/ide_completion/src/tests/pattern.rs
crates/ide_completion/src/tests/predicate.rs
crates/ide_completion/src/tests/type_pos.rs
docs/dev/style.md

feat: filter out duplicate macro completions

---

crates/ide_assists/src/handlers/extract_function.rs

- fix: It doesn't try to overwrite parts of selected comments any longer
- fix: It doesn't wrap tail expressions and return types in a result or option unnecessarily
- feat?: It now adds a `const` modifier to the created function if extract somethings from a const context 
Fixes #7840

internal: Improve `extract_function` assist

---

crates/ide_assists/src/handlers/extract_type_alias.rs
crates/syntax/src/ast/node_ext.rs

fix: extract_type_alias extracts generics correctly

---

crates/hir_ty/src/lower.rs
crates/hir_ty/src/tests/regression.rs

Fix binders with bare dyn trait

---

crates/rust-analyzer/src/main_loop.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9766
bors r+

fix: Don't publish diagnostics in crates.io or sysroot files

---

crates/hir/src/diagnostics.rs
crates/hir/src/lib.rs
crates/hir_ty/src/diagnostics/expr.rs
crates/ide_diagnostics/src/handlers/add_reference_here.rs
crates/ide_diagnostics/src/lib.rs

Add reference here

---

crates/ide_completion/src/render/macro_.rs

fix: add `!` to macro completions with existing arg

---

crates/hir_expand/src/name.rs
crates/ide_assists/src/handlers/convert_bool_then.rs
crates/ide_assists/src/lib.rs
crates/ide_assists/src/tests/generated.rs
crates/syntax/src/ast/node_ext.rs

One half of https://github.com/rust-analyzer/rust-analyzer/issues/8413

feat: Implement if_to_bool_then assist

---

crates/text_edit/src/lib.rs

minor: as per code-styple, add invariant comment

---

editors/code/src/commands.ts

internal: remove client-side support for latest requests

---

crates/rust-analyzer/src/bin/main.rs
crates/rust-analyzer/src/cli.rs
crates/rust-analyzer/src/cli/analysis_stats.rs
crates/rust-analyzer/src/cli/diagnostics.rs
crates/rust-analyzer/src/cli/flags.rs
crates/rust-analyzer/src/cli/highlight.rs
crates/rust-analyzer/src/cli/parse.rs
crates/rust-analyzer/src/cli/ssr.rs
crates/rust-analyzer/src/cli/symbols.rs

internal: unify subcommand handling between ra and xtask

---

crates/ide/src/hover.rs
crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
crates/ide_assists/src/utils/gen_trait_fn_body.rs
crates/test_utils/src/minicore.rs

Implements a default trait function body when generating the `Hash` trait for a type. Thanks!
r? @Veykril

feat: Generate default trait fn impl when generating `Hash`.

---

crates/ide_assists/src/handlers/convert_bool_then.rs
crates/ide_assists/src/lib.rs
crates/ide_assists/src/tests/generated.rs
crates/ide_db/src/helpers.rs
crates/test_utils/src/minicore.rs

Other half of https://github.com/rust-analyzer/rust-analyzer/issues/8413

feat: Implement `bool_then_to_if` assist

---

docs/dev/style.md

internal: document codebase stance on using functional combinators

---

docs/dev/style.md

minor: reword a bit

---

crates/rust-analyzer/src/cli/analysis_stats.rs
crates/rust-analyzer/src/cli/flags.rs

internal: print total size of source code in analysis-stats

---

crates/ide_assists/src/handlers/inline_call.rs
crates/ide_assists/src/utils.rs
crates/ide_completion/src/completions/trait_impl.rs
crates/ide_db/src/path_transform.rs

fix: Substitute generic types in inline_call

---

crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
crates/ide_assists/src/utils/gen_trait_fn_body.rs

Implements a default trait function body when generating the `Clone` trait for a type. Thanks!
r? @\veykril

feat: Generate default trait fn impl when generating `Clone`

---

crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/tests/record.rs

cc https://github.com/rust-analyzer/rust-analyzer/issues/9839, reverts the regression in https://github.com/rust-analyzer/rust-analyzer/pull/9845
bors r+

internal: Refine functional update completion some more

---

crates/ide_assists/src/handlers/sort_items.rs
crates/vfs/src/loader.rs
docs/dev/style.md

internal: document that ascription is preferred to a turbo fish

---

crates/ide/src/fixture.rs
crates/ide/src/hover.rs
crates/test_utils/src/lib.rs

Show type actions on ranged type hover

---

crates/ide_assists/src/handlers/extract_function.rs

fix: Fix extract_function tagging params as mut unnecessarily

---

crates/ide_assists/src/handlers/extract_function.rs
crates/ide_assists/src/handlers/inline_local_variable.rs

fix: `extract_variable` handles selection ranges better

---

crates/ide_completion/src/context.rs
crates/ide_completion/src/tests/record.rs

Last part of https://github.com/rust-analyzer/rust-analyzer/issues/9839
bors r+

internal: Fill out expected type for functional update syntax completion

---

crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
crates/ide_assists/src/utils/gen_trait_fn_body.rs
crates/syntax/src/ast/expr_ext.rs
crates/syntax/src/ast/make.rs

Implements a default trait function body when generating the `PartialEq` trait for a type. Thanks!
r? @veykril

feat: Generate default trait fn impl when generating `PartialEq`

---

crates/ide_assists/src/handlers/generate_function.rs

Worked on this with @yoshuawuyts.
We thought we ran into an issue with the `generate_function` assist where the code was not being generated in a certain situations. However, it wasn't actually a bug just a very confusing implementation where the cursor is not moved to the newly generated function. This happened when the return type was successfully inferred (and not unit). The function would be generated, but selection would not be changed.
This can be very confusing: If the function is generated somewhat far from where the assist is being invoked, the user never sees that the code was generated (nor are they given the chance to actually implement the function body). 
This PR makes it so that the cursor is _always_ moved to somewhere in the newly generated function. In addition, if we …

Jump to generated func

---

crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/tests/patterns.rs

This turned out fairly simple
bors r+

feat: type inference for if-let guards

---

crates/ide_assists/src/handlers/convert_to_guarded_return.rs

internal: use standard test style

---

crates/ide_completion/src/completions/fn_param.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/render/pattern.rs
crates/ide_completion/src/render/struct_literal.rs
crates/ide_completion/src/tests/pattern.rs

internal: Only complete type annotations for patterns in function params

---

crates/ide_assists/src/handlers/convert_to_guarded_return.rs

internal: remove old editing API

---

crates/ide_assists/src/utils.rs
crates/ide_completion/src/completions/trait_impl.rs
crates/syntax/src/algo.rs
crates/syntax/src/ast/edit.rs

internal: remove one more usage of old editing API.

---

crates/mbe/src/syntax_bridge.rs
crates/syntax/src/algo.rs
crates/syntax/src/lib.rs

internal: remove dead code

---

crates/ide_assists/src/utils.rs
crates/ide_completion/src/completions/trait_impl.rs
crates/syntax/src/ast/edit.rs
crates/syntax/src/ast/edit_in_place.rs

minor: move functionality to a better place

---

Cargo.lock
crates/rust-analyzer/Cargo.toml
crates/rust-analyzer/src/lib.rs

internal: optimize compile time

---

crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
crates/ide_assists/src/utils/gen_trait_fn_body.rs

Closes https://github.com/rust-analyzer/rust-analyzer/issues/9914. Thanks!
r? @Veykril

Fix gen debug for enums

---

crates/hir/src/semantics/source_to_def.rs
crates/hir_def/src/child_by_source.rs
crates/hir_def/src/generics.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9919
Running the test as described in the issue I do not get any eprintln output at all anymore.

Only add entries to SourceToDef dynmaps when they come from the same file

---

crates/hir/src/source_analyzer.rs
crates/ide_assists/src/utils.rs

minor: Fix some clippy lints

---

crates/ide/src/highlight_related.rs

Looks like I forgot this one somehow.
bors r+

fix: Highlight function exit points on `fn` keyword

---

crates/proc_macro_api/src/version.rs

proc_macro_api: make commit & date suffix of binary version optional

---

crates/base_db/src/input.rs

feat: include full path in the cyclic deps error

---

crates/ide/src/highlight_related.rs

fix: Don't trigger related highlighting on unrelated tokens

---

crates/hir_expand/src/builtin_attr.rs
crates/hir_expand/src/builtin_derive.rs
crates/hir_expand/src/db.rs
crates/hir_expand/src/input.rs
crates/hir_expand/src/proc_macro.rs

internal: Use ExpandResult in all TokenExpanders

---

.github/workflows/ci.yaml
crates/hir_expand/src/lib.rs
crates/rust-analyzer/src/dispatch.rs
crates/rust-analyzer/src/main_loop.rs

internal: prep to 2021 edition

---

crates/project_model/src/sysroot.rs
crates/project_model/src/tests.rs
crates/project_model/src/workspace.rs

fix: resolve core::arch module

---

crates/ide_assists/src/handlers/replace_if_let_with_match.rs

This PR changes some behaviour of the `replace_match_with_if_let` ide-assist.
Concretely, it makes two changes:
it introduces a check for empty expression bodies. This means that checks of the shape
```rs
match x {
A => {}
B => {
println!("hi");
}
}
```
will prefer to use the B branch as the first (and only) variant.
It also reprioritizes the importance of "happy" and "sad" patterns.
Concretely, if there are reasons to prefer having the sad pattern be the first (/only) pattern,
it will follow these.
This means that in the case of 
```rs
match x {
Ok(_) => {
println!("Success");
}
Err(e) => {
println!("Failure: {}", e);
}
}
```
the `Err` variant will correctly be used as the first expression in the generated if.
Up until now, the generated code was actually invalid, as it would generate …

Add empty-body check to replace_match_with_if_let and re-prioritize choices

---

crates/hir_ty/src/infer.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/unify.rs
crates/hir_ty/src/tests/coercion.rs
crates/hir_ty/src/tests/regression.rs

Second attempt :sweat_smile: 
Fixes #9560

fix: Determine expected parameters from expected return in calls

---

editors/code/src/tasks.ts
editors/code/src/toolchain.ts
editors/code/src/util.ts

fix check of the toolchain's path

---

crates/ide_completion/src/completions/record.rs
crates/ide_completion/src/tests/record.rs

fix: Do not show functional update completion when already qualified

---

crates/hir/src/semantics.rs
crates/ide/src/expand_macro.rs

fix: Expand attributes recursively in expand_macro

---

Cargo.lock
crates/proc_macro_api/Cargo.toml
crates/proc_macro_api/src/lib.rs
crates/rust-analyzer/Cargo.toml
crates/rust-analyzer/src/cli/load_cargo.rs
crates/rust-analyzer/src/reload.rs

internal: remove unreasonable crate dependency

---

crates/hir_expand/src/input.rs

Merely detaching the attributes causes incorrect spans to appear when mapping tokens up as the token ids resolve to the ranges of the stripped item so all the text ranges of its tokens are actually lower than the non-stripped ones.
Same fix as with attributes can be applied here, just replace the derive attribute with an equal amount of whitespace.
Fixes #9387

fix: Incorrect up-mapping for tokens in derive attributes

---

crates/syntax/src/tests.rs

internal: use single env var to controll all benchmarks

---

crates/ide_assists/src/handlers/sort_items.rs

A small fix to the problem noted by @lnicola :
> ![sort-fields](https://user-images.githubusercontent.com/308347/129513196-4ffc7937-be58-44d4-9ec7-ba8745dcb460.gif)
> 
> (note the slight inconsistency here: to sort the variants of `Animal` I have to select the enum name, but to sort the fields of `Cat` I have to select the fields themselves)

Sort enum variant

---

crates/ide/src/ssr.rs
crates/ide_assists/src/assist_context.rs
crates/ide_db/src/label.rs
crates/ide_diagnostics/src/lib.rs
crates/proc_macro_api/src/rpc.rs

internal: slightly improve compile times

---

crates/rust-analyzer/src/handlers.rs

internal: make upstream bug less annoying

---

crates/hir_expand/src/db.rs

I'm not entirely sure if the message is still correct, it seems to have survived a number of refactors, but it is mangled english anyway.

Fix error message

---

crates/rust-analyzer/src/cli/analysis_stats.rs
crates/rust-analyzer/src/cli/load_cargo.rs

internal: split database loading time in anaysis-stats into components

---

crates/hir_expand/src/lib.rs
crates/tt/src/lib.rs

minor: dead code

---

crates/proc_macro_api/src/lib.rs
crates/rust-analyzer/src/cli/load_cargo.rs
crates/rust-analyzer/src/global_state.rs
crates/rust-analyzer/src/reload.rs

minor: improve readability

---

crates/base_db/src/input.rs
crates/base_db/src/lib.rs
crates/hir_expand/src/proc_macro.rs
crates/mbe/src/lib.rs
crates/rust-analyzer/src/reload.rs
crates/tt/src/lib.rs

internal: reduce coupling

---

crates/ide_assists/src/handlers/extract_function.rs
crates/syntax/src/ast/expr_ext.rs

Fix extract_function with macro arg

---

crates/ide/src/goto_implementation.rs
crates/ide_db/src/search.rs

fix: make `goto_implementation` multi-token mapping aware

---

crates/ide_assists/src/handlers/auto_import.rs
crates/ide_assists/src/handlers/qualify_path.rs

fix: Deduplicate imports for qualify_path

---

crates/rust-analyzer/src/main_loop.rs

fix error message for when DidChangeTextDocument path doesn't exist

---

crates/hir_def/src/nameres/path_resolution.rs

Add crate name to nameres panic context

---

crates/hir_def/src/data.rs
crates/hir_ty/src/lower.rs

To debug https://github.com/rust-analyzer/rust-analyzer/issues/10084 further
bors r+

Add panic info for `impl_trait`/`trait_data`

---

crates/hir_def/src/data.rs
crates/hir_ty/src/lower.rs

Fixes perf after https://github.com/rust-analyzer/rust-analyzer/pull/10159
bors r+

minor: Don't dump `DefMap`s to build the panic context

---

crates/ide_completion/src/render.rs

minor: Avoid extra allocation in completion rendering

---

crates/hir_def/src/attr.rs
crates/hir_expand/src/builtin_derive.rs
crates/hir_expand/src/db.rs
crates/hir_expand/src/eager.rs
crates/mbe/src/expander/matcher.rs
crates/mbe/src/lib.rs
crates/mbe/src/syntax_bridge.rs
crates/mbe/src/tests.rs
crates/mbe/src/tests/expand.rs
crates/mbe/src/tt_iter.rs
crates/parser/src/grammar.rs
crates/parser/src/lib.rs
crates/syntax/src/lib.rs
crates/syntax/src/parsing.rs

internal: make name consistent with usage

---

crates/hir_ty/src/display.rs
crates/ide/src/hover.rs

fix: path display error when start with `crate`

---

crates/hir_ty/src/lower.rs

cc https://github.com/rust-analyzer/rust-analyzer/issues/10084
bors r+

minor: include `ImplLoc` in panic context

---

crates/ide/src/runnables.rs

Closes #10184
changelog fix (first contribution) add multi-token mapping support to runnables

fix: add multi-token mapping support to runnables

---

crates/ide_assists/src/handlers/convert_comment_block.rs
crates/ide_assists/src/lib.rs
crates/ide_assists/src/tests/generated.rs
crates/ide_completion/src/completions/flyimport.rs
crates/ide_completion/src/completions/fn_param.rs
crates/parser/src/grammar.rs
crates/parser/src/grammar/expressions.rs
crates/parser/src/grammar/patterns.rs
crates/sourcegen/src/lib.rs
crates/syntax/test_data/parser/inline/ok/0110_use_path.rast
crates/syntax/test_data/parser/inline/ok/0110_use_path.rs
crates/syntax/test_data/parser/inline/ok/0115_tuple_field_attrs.rast
crates/syntax/test_data/parser/inline/ok/0115_tuple_field_attrs.rs

internal: prevent possible bugs when adding magical comments

---

editors/code/src/net.ts

internal: Add workaround for rename error reporting

---

crates/rust-analyzer/src/global_state.rs
crates/rust-analyzer/src/main_loop.rs
crates/rust-analyzer/src/reload.rs

fix: Detect even a second change to `Cargo.toml`

---

crates/ide_completion/src/completions/attribute.rs
crates/ide_completion/src/tests/attribute.rs

fix: do not complete builtin attributes for qualified paths

---

crates/ide/src/syntax_highlighting/highlight.rs
crates/ide/src/syntax_highlighting/html.rs
crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
crates/ide/src/syntax_highlighting/test_data/highlighting.html
crates/ide/src/syntax_highlighting/test_data/injection.html
crates/ide/src/syntax_highlighting/test_data/rainbow_highlighting.html
crates/ide/src/syntax_highlighting/tests.rs

fix: Don't highlight unsafe traits as unsafe in safe impls

---

crates/ide/src/call_hierarchy.rs
crates/ide/src/display/navigation_target.rs

internal: Improve call_hierarchy and incoming/outgoing_calls

---

crates/parser/src/grammar.rs

intenral: simplify parser

---

crates/ide_assists/src/handlers/replace_if_let_with_match.rs

ref: https://github.com/rust-analyzer/rust-analyzer/issues/10220

Narrow "if-let to match" assist available range

---

crates/ide/src/goto_definition.rs

minor: Add multi-token mapping test for goto_definition

---

crates/parser/src/grammar/generic_args.rs
crates/syntax/test_data/parser/err/0049_double_fish.rast
crates/syntax/test_data/parser/err/0049_double_fish.rs

internal: type argument parsing refactoring

---

crates/parser/src/grammar/generic_args.rs
crates/parser/src/grammar/paths.rs

minor: simplify generics parsing

---

crates/base_db/src/fixture.rs
crates/ide/src/syntax_highlighting/test_data/highlighting.html
crates/ide/src/syntax_highlighting/tests.rs
crates/ide_assists/src/handlers/convert_iter_for_each_to_for.rs

internal: Add a mirror function-like proc-macro expander for tests

---

crates/ide_assists/src/handlers/generate_function.rs

Generate function assist creates bad param names for const/static item args

---

crates/ide_diagnostics/src/handlers/unlinked_file.rs

fix: Fix incorrect mod.rs handling in unlinked_file fixes

---

crates/hir_expand/src/eager.rs

minor: Include macro path in eager macro resolve error

---

crates/hir_expand/src/hygiene.rs

internal: Avoid some `Arc` cloning

---

crates/hir/src/lib.rs
crates/ide_diagnostics/src/handlers/missing_ok_or_some_in_tail_expr.rs

fix: Fix diagnostics in unnamed consts

---

editors/code/package.json

minor: Update `semanticTokenModifiers` in package.json

---

crates/parser/src/grammar/expressions.rs
crates/parser/src/parser.rs

simplify attribute parsing

---

crates/hir_def/src/generics.rs
crates/hir_def/src/item_tree/lower.rs

Helps with #10305
I made the implementations of `HasChildSource<_>` and `ChildBySource` for `GenericDefId` use their own logic instead of relying on `GenericParams::new`. This in turn means that `GenericParams::new` is unused and can be removed. `SourceMap` becomes also unused because all the rest of the code does is insert into it, so it can be removed too. 
This also helps avoid creating a completly new `GenericParams` when `GenericDefId::child_source` and `GenericDefId::child_by_source_to` are called, and also creating a `SourceMap` in `item_tree::lower::Ctx::lower_generic_params`.

Remove `GenericParams::new`

---

crates/hir/src/semantics.rs

minor: Cleanup descend_into_macros_impl

---

crates/hir/src/semantics.rs

A lot of descends don't actually descend in which case we don't wanna allocate
bors r+

minor: Use SmallVec<[_; 1]> in `descend_into_macros_impl`

---

crates/proc_macro_srv/src/abis/abi_1_56/rustc_server.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10235
bors r+

fix: fix proc macro crash on nightly

---

crates/hir_def/src/generics.rs
crates/hir_def/src/item_tree.rs
crates/hir_def/src/item_tree/lower.rs
crates/hir_def/src/item_tree/pretty.rs
crates/hir_def/src/item_tree/tests.rs
crates/hir_ty/src/tests/regression.rs

Move `GenericParams`'s handling of `impl Trait` into `fn_data_query`

---

crates/ide_assists/src/handlers/inline_call.rs
crates/ide_db/src/helpers/node_ext.rs
crates/syntax/src/ast/edit_in_place.rs

fix: Fix inline_call breaking RecordExprField shorthands

---

crates/ide_assists/src/handlers/convert_bool_then.rs

fix: Parenthesize expressions in `if_to_bool_then` assist where required

---

editors/code/src/main.ts

fix: overwrite files when calling `patchelf`

---

crates/ide_diagnostics/src/handlers/remove_this_semicolon.rs

fix: remove semicolon diagnostics only highlights the semi

---

crates/syntax/src/ast/generated/nodes.rs
crates/syntax/src/tests/sourcegen_ast.rs

minor: regen

---

crates/ide_assists/src/handlers/replace_if_let_with_match.rs
crates/syntax/src/ast/node_ext.rs

internal: remove deprecated method

---

crates/ide/src/rename.rs
crates/ide_db/src/rename.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10324
bors r+

fix: Fix rename trying to edit the same range multiple times for certain macro inputs

---

crates/mbe/src/expander/matcher.rs
crates/mbe/src/lib.rs
crates/mbe/src/parser.rs

internal: cleanup mbe a bit

---

crates/ide_db/src/helpers/insert_use.rs
crates/ide_db/src/helpers/insert_use/tests.rs
crates/ide_db/src/helpers/merge_imports.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6800
bors r+

fix: fix insert_use incorrectly merging glob imports

---

Cargo.lock
crates/proc_macro_api/Cargo.toml
crates/proc_macro_srv/Cargo.toml

minor: Bump `object` avoid a duplicate dependency

---

crates/ide/src/doc_links/intra_doc_links.rs
crates/ide_assists/src/handlers/expand_glob_import.rs
crates/ide_db/src/tests/sourcegen_lints.rs
crates/project_model/src/sysroot.rs
crates/rust-analyzer/tests/slow-tests/support.rs

minor: Use array `into_iter` in more places

---

crates/ide/src/doc_links.rs

Should fix https://github.com/rust-analyzer/rust-analyzer/issues/10655
bors r+

fix: Enable markdown tables

---

crates/hir/src/semantics.rs

Saves ~45ms when highlighting `rust-analyzer/src/config.rs` for me
bors r+

internal: Cache ast::MacroCalls to their expansions in Semantics::descend_into_macros_impl

---

crates/hir/src/semantics.rs

Turns out when highlighting we currently populate the Dynmaps of pretty much every item in a file, who would've known that would be so costly...
Shaves off 250 ms for the integrated benchmark on `rust-analyzer/src/config.rs`.
We are still looking at a hefty `154ms - descend_into_macros (2190 calls)` but I feel like this is slowly nearing towards just call overhead for the setup where we can't really do much filtering.
bors r+

internal: Don't check items for macro calls if they have no attributes

---

docs/user/manual.adoc

minor: Show how to create `~/.local/bin`

---

crates/ide_completion/src/completions/unqualified_path.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/render.rs
crates/ide_completion/src/render/const_.rs
crates/ide_completion/src/render/macro_.rs
crates/ide_completion/src/render/type_alias.rs

minor: Add some completion profile spans

---

crates/hir_def/src/item_scope.rs

Brings down `5ms - find_path_prefixed (46 calls)` to `1ms - find_path_prefixed (46 calls)` for me on the `integrated_completion_benchmark`.
Still `O(n)` but this should considerably cut down lookups nevertheless(as shown by the timings already).
bors r+

internal: Do not search through all three namespaces in `ItemScope::name_of`

---

crates/hir_ty/src/db.rs
crates/hir_ty/src/method_resolution.rs
crates/hir_ty/src/tests/method_resolution.rs

Fix: Lookup impls in local def maps

---

crates/ide/src/prime_caches.rs

Before this PR, we used to index every crate in the `CrateGraph`, which includes every test, benchmark and example of all packages everywhere. The point of indexing is to speed up future queries, so indexing lots of tiny crates users are unlikely to open isn't really helpful.
This PR instead makes us index only the transitive dependencies of all workspace crates.
This reduces the number of crates we index in the rust-analyzer repo from 617 to 177 (!). Time is not impacted by that much, because most of the skipped crates are tiny.
bors r+

feat: index fewer crates on startup/reload

---

crates/ide/src/annotations.rs
crates/ide/src/runnables.rs
crates/ide_db/src/defs.rs
crates/ide_db/src/helpers.rs

internal: Replace some more ide usages of ModuleDef with Definition

---

crates/ide_completion/src/completions/flyimport.rs
crates/ide_completion/src/context.rs
crates/ide_completion/src/patterns.rs
crates/ide_completion/src/tests/flyimport.rs

Fix: trigger flyimport on enum variants

---

crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
crates/syntax/src/ast/make.rs

fix: add generic parameters in convert to manual impl assist

---

crates/profile/src/stop_watch.rs

https://github.com/rr-debugger/rr does not support the perf-specific ioctls, so add a way to avoid them.
bors r+

internal: Allow disabling perf counters access via `RA_DISABLE_PERF`

---

crates/hir/src/semantics.rs
crates/ide/src/highlight_related.rs
crates/ide/src/references.rs
crates/ide/src/runnables.rs

internal: Do not use reference search in `runnables::related_tests`

---

crates/ide/src/hover.rs
crates/ide/src/hover/tests.rs

ide: dedupe or merge hover actions

---

crates/hir_def/src/path.rs
crates/hir_def/src/path/lower.rs
crates/hir_ty/src/display.rs

Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8157
bors r+

feat: Format `Fn` traits using parentheses

---

crates/hir/src/display.rs
crates/ide/src/hover/tests.rs

ide: hover omits unnamed where preds

---

crates/hir_def/src/body/lower.rs
crates/hir_def/src/body/scope.rs
crates/hir_def/src/expr.rs
crates/hir_def/src/path.rs
crates/hir_def/src/path/lower.rs
crates/hir_ty/src/diagnostics/expr.rs
crates/hir_ty/src/infer/expr.rs
crates/hir_ty/src/infer/pat.rs

Shaves off ~15mb from self analysis

internal: Replace some `Vec` occurences with `Box` 
