rust-lang/rust-analyzer

- crates/ide_assists/src/handlers/unmerge_use.rs
> fix: Don't keep a trailing `self` token in import paths after `unmerge_use`

- editors/code/src/net.ts
I believe this should fix #9280. Testing is needed but I wanted to quickly push a hotfix.
> fix: Code: use `Uri.toString()` for URLs

- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/html.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
- crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
- crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
- crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/test_data/injection.html
- crates/ide/src/syntax_highlighting/test_data/rainbow_highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/syntax/src/ast/node_ext.rs
> fix: Highlight unsafe trait refs as unsafe only in impl blocks and definitions

- editors/code/src/main.ts
- editors/code/src/net.ts
- editors/code/src/toolchain.ts
#8951 was a major change in the VS Code extension and caused quite a few problems. This PR is a catch-all for bugs and improvements in the new code.
This should fix:
- #9284
- [this unreported bug](https://github.com/rust-analyzer/rust-analyzer/pull/8951/files#r651570446)
- ...and one or two uncaught exceptions I just found
The original lack of testing was my own fault, but this area of the VS Code API is also tricky for a couple reasons:
- The [FileSystem](https://github.com/rust-analyzer/rust-analyzer/pull/8951/files#r651570446) API does not list or warn about any exceptions, but [FileSystemProvider](https://github.com/rust-analyzer/rust-analyzer/pull/8951/files#r651570446) (which `FileSystem` is a wrapper of, AFAICT) does.
- At first glance, …
> fix: Code: clean-up #8951

- PRIVACY.md
- README.md
- docs/user/manual.adoc
- editors/code/package.json
Most LSP extensions seem to do the same thing, and this is causing some
confusion for users who don't notice the update prompt before Code hides
it.
> fix: Code: update the LSP server without asking

- docs/user/.gitignore
- docs/user/manual.adoc
`rust-analyzer` can be installed via [Homebrew](https://brew.sh) (AKA`brew`) on macOS. I've added instructions on how to do so to the documentation. Additionally, I added a `.gitignore` rule to ignore the HTML documentation produced by  `asciidoctor manual.adoc` so that it is not accidentally checked into `git`.
> minor: Document installation via Homebrew

- crates/rust-analyzer/src/config.rs
- editors/code/package.json
I feel like `crate` and `self` work better than `by_crate` and `by_self`. The only reason for the current names were that `Self` doesn't work for the variant name on the rust side so I forgot about setting proper config names on serde layer.
> minor: Give `ImportPrefix` variants better config names

- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/completions/keyword.rs
> fix: Don't complete keywords in attributes inside expressions

- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/utils.rs
- crates/ide_completion/src/completions/trait_impl.rs
- crates/ide_db/src/lib.rs
- crates/ide_db/src/path_transform.rs
This PR does a couple of things:
- moves path_transform from ide_assists to ide_db to be shared by both assists and completions
- when completing a const or a function for a trait, it will "inline" any generics in those associated items instead 
of leaving the generic's name. For example:
```rust
trait Foo<T> {
const BAR: T;
fn foo() -> T;
}
struct Bar;
impl Foo<u32> for Bar {
// autocompletes to this
fn foo() -> u32;
// and not this (old)
fn foo() -> T;
// also works for associated consts and where clauses
const BAR: u32 = /* */
}
```
Currently this does not work for const generics, because `PathTransform` does not seem to account for them. If this should work on const generics too, `PathTransform` will need to be changed. However, it is uncommon to implement a trait only for a single …
> Inline generics in const and function trait completions

- crates/ide_assists/src/handlers/auto_import.rs
- crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/syntax/src/ast/node_ext.rs
> feat: Don't insert imports outside of cfg attributed items

- crates/hir_ty/src/chalk_db.rs
- crates/hir_ty/src/test_db.rs
- crates/hir_ty/src/tests.rs
- crates/hir_ty/src/tests/coercion.rs
- crates/hir_ty/src/tests/display_source_code.rs
- crates/hir_ty/src/tests/macros.rs
- crates/hir_ty/src/tests/method_resolution.rs
- crates/hir_ty/src/tests/patterns.rs
- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/tests/simple.rs
- crates/hir_ty/src/tests/traits.rs
- crates/test_utils/src/lib.rs
Notable changes:
- unify `check_types` and `check_mismatches` into `check`, which supports both kinds of annotations (`check_types` still exists because I didn't want to change all the annotations, but uses the same implementation)
- because of that, `check_types` now fails on any type mismatches; also annotations always have to hit the exact range
- there's also `check_no_mismatches` for when we explicitly just want to check that there are no type mismatches without giving any annotations (`check` will fail without annotations)
- test annotations can now be overlapping (they point to the nearest line that has actual code in that range):
```
// ^^^^ annotation
//    ^^^^^^^^^ another annotation
```
> Refactor / clean up hir_ty tests

- docs/dev/debugging.md
add note about passing cfg(debug_assertions) to rustc on build. The server will not spin on start  without this arcane hack
> add note about passing cfg(debug_assertions)

- crates/project_model/src/sysroot.rs
Removes `rtstartup`, since that's not a Cargo crate (its files are compiled into object files and linked alongside the stdlib).
Adds  `std_detect`.
Part of https://github.com/rust-analyzer/rust-analyzer/issues/9352 (doesn't fix it since std_detect is full of `cfg_if!`)
bors r+
> fix: Update sysroot crates

- crates/cfg/src/lib.rs
- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/lib.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
If you are opening libcore from rust-lang/rust as opposed to e.g.
goto definition from some other crate which would use the sysroot
instance of libcore, a `#![cfg(not(test))]` would previously have made
all the code excluded from the module tree, breaking the editor
experience.
Core does not need to ever be edited with `#[cfg(test)]` enabled,
as the tests are in another crate.
This PR puts in a slight hack that checks for the crate name "core" and
turns off `#[cfg(test)]` for that crate.
Fixes #9203 
Fixes #9226
> Add a config setting to disable the 'test' cfg in specified crates

- crates/ide_assists/src/handlers/extract_function.rs
> Fix extract_function with await

- crates/ide/src/hover.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This also implements deprecation support for config options as this renames `hoverActions_linksInHover` to `hover_linksInHover`.
Fixes #9232
> feat: Make documentation on hover configurable

- crates/rust-analyzer/src/bin/main.rs
- docs/dev/README.md
This adds a check for RA_LOG_FILE, and logs to that if defined. It currently overrides flags.log_file. If this is undesirable, I will add a check.
> output to log file if RA_LOG_FILE is defined in environment

- crates/hir/src/lib.rs
- crates/ide_db/src/defs.rs
> internal: remove one more accidentally quadratic code-path

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
> feat: Add `public` semantic token modifier for public items

- crates/ide/src/goto_declaration.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
This is just a simple implementation that falls back to `goto_definition` for everything but modules where it goes to the actual module declaration if possible.
> feat: Implement goto_declaration support

- crates/ide/src/highlight_related.rs
> feat: Highlight loop break points

- crates/ide_completion/src/completions/attribute.rs
> minor: Complete `macro_use` attribute on modules

- crates/ide/src/highlight_related.rs
- crates/ide_assists/src/handlers/wrap_return_type_in_result.rs
- crates/ide_db/src/helpers.rs
- crates/syntax/src/ast/node_ext.rs
Deduplicates the duplication introduced in #9375 and #9396 while also fixing a few bugs in both the assist and related highlighting.
> internal: Deduplicate ast expression walking logic

- crates/ide/src/highlight_related.rs
- crates/ide/src/references.rs
- crates/ide/src/rename.rs
- crates/ide_db/src/search.rs
> internal: Include `self` in usage search for modules in their definition source

- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests.rs
These import the preceding segment, but only in type namespace. Previously we've imported the name in all namespaces.
bors r+
> fix: Handle `::{self}` imports

- crates/ide/src/annotations.rs
- crates/ide/src/hover.rs
- crates/ide/src/runnables.rs
> fix: Don't add test runnables for outline modules in the wrong file

- crates/ide/src/runnables.rs
Expected this to fail as thats behaving incorrectly on current nightly but I think I fixed this accidentally with https://github.com/rust-analyzer/rust-analyzer/pull/9435
bors r+
> minor: Add test for macro expanded test module in runnables

- crates/base_db/src/input.rs
This currently seems [incorrect](https://github.com/rust-analyzer/rust-analyzer/pull/8363/files) and doesn't seem that useful, so maybe we can remove it?
> Don't implement `Eq` for `CrateGraph`

- crates/hir_def/src/nameres/tests/macros.rs
This is a lot simpler to understand and debug than the `plain_macros_are_legacy_textual_scoped` test.
bors r+
> internal: Add a simpler legacy macro scoping test

- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/item_tree/lower.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8930
bors r+
> fix: Fix nested macro in block defining items

- crates/ide_diagnostics/src/handlers/unlinked_file.rs
#9255 accidentally turned it into an error
bors r+
> fix: Make unlinked_file diagnostic a hint again

- crates/ide/src/lib.rs
- crates/ide/src/view_crate_graph.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
Works like "View Crate Graph", but also includes crates.io and sysroot dependencies. The resulting graph might be enormous.
Closes https://github.com/rust-analyzer/rust-analyzer/issues/8867
bors r+
> feat: Add "View Crate Graph (Full)"

- crates/ide_assists/src/handlers/replace_if_let_with_match.rs
- crates/ide_assists/src/utils.rs
Now instead of only working on `if let ... {} else {}` if expressions it now works on all of them where the condition expression is the same text-wise.
This includes if let expressions without an else block, in which case a simple `_ => ()` will be generated in the resulting match but also in more complex cases where multiple `if let` expressions are chained.
bors r+
> feat: Empower `replace_if_let_with_match`

- crates/ide_assists/src/handlers/replace_if_let_with_match.rs
- crates/syntax/src/ast/make.rs
Transforms bare `if cond {}` into `_ if cond` guard patterns in the match as long as at least one `if let` is in the if chain, otherwise the assist wont be applicable.
bors r+
> feat: Handle non-let if expressions in replace_if_let_with_match

- crates/project_model/src/sysroot.rs
This fixes missing trait implementation on the proc_macro types.
bors r+
> fix: sysroot: add proc_macro -> std dependency edge

- crates/ide/src/hover.rs
- crates/ide_db/src/defs.rs
This is what happens when you forget to write a test
bors r+
> fix: Fix incorrect guard for NameRefClass attribute resolution

- crates/ide/src/runnables.rs
We are somehow hitting this when looking at `crates\ide_db\src\lib.rs` and I don't see how.
bors r+
> minor: Print runnable kind on assertion failure for better debuggability

- crates/project_model/src/sysroot.rs
libstd doesn't actually depend on `proc_macro`. cc https://github.com/rust-analyzer/rust-analyzer/pull/9456#issuecomment-873005974
bors r+
> fix: Remove incorrect std dep

- crates/ide/src/hover.rs
- crates/ide_assists/src/handlers/replace_if_let_with_match.rs
- crates/ide_db/src/defs.rs
- crates/syntax/src/ast/node_ext.rs
Now it works on pretty much on all 2-arm matches where only up to 1 arm binds a name instead of requiring either a sad or wildcard pattern to be present.
bors r+
> feat: `replace_match_with_if_let` works on more 2-arm matches

- crates/ide/src/join_lines.rs
> feat: join lines joins two ifs into `else if`

- crates/ide_assists/src/handlers/auto_import.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9113
bors r+
> fix: Don't show one import per namespace each in `auto_import`

- crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_db/src/helpers/insert_use.rs
Also prevents the assist from triggering on associated items.
Fixes #9472.
This PR gets rid of a lot of tests that only really test the `insert_use` infra which already has its own tests, so these tests are of no use.
bors r+
> fix: `replace_qualified_name_with_use` inserts qualified import paths

- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/render/const_.rs
- crates/ide_completion/src/render/function.rs
- crates/ide_completion/src/render/type_alias.rs
- crates/ide_completion/src/tests.rs
- crates/ide_completion/src/tests/item_list.rs
- crates/ide_completion/src/tests/type_pos.rs
Fixes: #7456
The thing is however, due to the trait being already imported, the path to the trait is just the name of the trait itself.
I also updated the test concerning the labels.
> show imported trait on autocompletion of associated items

- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/tests/type_pos.rs
based on #9478 discussions: showing 'as' before already imported traits and 'use' on auto-import cased
> feat: show 'as' or 'use' before label traits

- crates/ide_assists/src/handlers/inline_call.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
- crates/syntax/src/ted.rs
- crates/test_utils/src/minicore.rs
> fix: Wrap inlined closures in parens when inlined in an expression in `inline_call`

- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/visibility.rs
fixes https://github.com/rust-analyzer/rust-analyzer/issues/9481
bors r+
> fix: Fix cycle in visibility computation with modules from the same block

- crates/rust-analyzer/src/bin/logger.rs
fixes #9432
Not quite sure if that's what you want, but storing the log message in buffers eliminated the tiny write syscalls for me.
I just changed the Logger struct.
> fix: make the logs line buffered

- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/tests/item_list.rs
- crates/ide_completion/src/tests/items.rs
- crates/ide_completion/src/tests/predicate.rs
- crates/ide_completion/src/tests/type_pos.rs
- crates/ide_completion/src/tests/use_tree.rs
> internal: Complete `crate`, `super` and `self` in non-UseTree paths

- crates/ide_completion/src/item.rs
> fix: Don't add the trait name to the insert text in completions

- crates/flycheck/src/lib.rs
- crates/proc_macro_api/src/process.rs
- crates/proc_macro_srv/src/proc_macro/bridge/server.rs
- crates/vfs-notify/src/lib.rs
Fixes: [#9385](https://github.com/rust-analyzer/rust-analyzer/issues/9385)
The thread name is shown in debugger as well as panic messages and this
patch makes it easier to follow a thread instead of looking through
full backtrace, by naming all spawned threads according to their
functioning.
> Explicitly name all spawned threads

- crates/flycheck/src/lib.rs
- crates/proc_macro_api/src/process.rs
- crates/proc_macro_srv/src/proc_macro/bridge/server.rs
- crates/vfs-notify/src/lib.rs
Threads on Linux have an upper limit of 16 characters, hence dropping `Thread` from their names.
> Shorten thread names

- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/interner.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/tls.rs
... instead of using `AliasTy`. Chalk turns the alias type into the
placeholder during unification anyway, which confuses our method
resolution logic.
Fixes #9530.
> Represent opaque types with TyKind::OpaqueType

- Cargo.lock
- crates/flycheck/Cargo.toml
- crates/proc_macro_srv/Cargo.toml
- crates/proc_macro_test/Cargo.toml
- crates/project_model/Cargo.toml
- crates/project_model/src/build_data.rs
Removes the following dependent crates:
* semver-parser
* pest
* ucd-trie
Removes project_model's dependency on itertools
> cargo_metadata 0.14

- crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
> fix: `replace_qualified_name_with_use` keeps qualifier for import

- crates/ide_assists/src/handlers/replace_if_let_with_match.rs
- crates/ide_assists/src/handlers/replace_let_with_if_let.rs
- crates/ide_assists/src/tests.rs
Turns out we have two assists for replacing something with `if let` constructs, so having the cursor on a `let` keyword inside a match gave you two identical assist labels which is rather confusing.
bors r+
> minor: Disambiguate replace with if let assist labels

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/tests/coercion.rs
- crates/ide_assists/src/handlers/add_explicit_type.rs
or so I'd like to say but there is one odd case here where it doesn't work(see [review](https://github.com/rust-analyzer/rust-analyzer/pull/9552#discussion_r667351856))
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6107
> internal: `add_explicit_type` respects coercions

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide_assists/src/handlers/add_explicit_type.rs
- crates/ide_assists/src/handlers/early_return.rs
- crates/ide_assists/src/handlers/inline_call.rs
- crates/syntax/src/ast/make.rs
> fix: Respect coercions in `inline_call`

- crates/hir/src/lib.rs
- crates/ide/src/annotations.rs
- crates/ide/src/hover.rs
- crates/ide/src/runnables.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
Fixes #8964
Before:
After:
Basically when a macro emits more than one test we name the test functions/modules name in the runnable instead to not emit a bunch of equally named `Run Test` annotations which don't really tell much.
Note that the `Run fibonacci_test Tests` line is below the attributes due to the fact that the function name span is being reused for the generated module in rstest's expansion.
> feat: Emit test names in `Run test` runnables if they come from a macro expansion

- crates/ide_completion/src/completions/postfix.rs
- crates/ide_db/src/helpers.rs
adds #9561
used ```ele``` as identifier for each element in the iteration
> feat: add 'for' postfix completion

- crates/ide/src/doc_links.rs
- crates/ide/src/fixture.rs
- crates/ide/src/goto_declaration.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/goto_implementation.rs
- crates/ide/src/hover.rs
- crates/ide/src/references.rs
- crates/ide/src/rename.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide_assists/src/handlers/extract_function.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/search.rs
Closes #7524
Inlines all the calls to reference related name classification as well as emits both goto definition targets for field shorthands.
> internal: Explicitly check for reference locals or fields in Name classification

- crates/proc_macro_api/src/lib.rs
- crates/proc_macro_api/src/process.rs
- crates/stdx/src/lib.rs
Communication with the proc macro server process has always happened one request at a time, so the additional thread isn't really needed (it just forwarded each request, and sent back the response). This removes some indirection that was a bit hard to understand (a channel was allocated and sent over another channel to return the response).
Hope I'm not missing anything here
> internal: remove proc macro management thread

- crates/project_model/src/build_data.rs
Set `CARGO_CRATE_NAME` to the package name, with `-` replaced by `_`. This is wrong, but better than not setting the variable at all.
Also set `CARGO_PKG_HOMEPAGE` since it's easy.
bors r+
> fix: Set more `CARGO_` env vars

- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- docs/dev/style.md
> internal: remove erroneous default impl

- crates/hir/src/lib.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/ide_db/src/defs.rs
> internal: get rid of a call to slow O(N) visibility_of function

- editors/code/src/net.ts
> Rename the old server before update

- crates/ide/src/runnables.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
This shows a runnable inside outline test modules at the top of its file:
> Show test mod runnable in outline modules

- crates/ide_assists/src/handlers/remove_dbg.rs
Instead of inspecting the input tokentree manually, parse the input as `,` delimited expressions instead and act on that. This simplifies the assist quite a bit.
Fixes #8455
> Parse input expressions for dbg! invocations in remove_dbg

- docs/user/manual.adoc
Neovim 0.5 has been released recently (see http://neovim.io/news/2021/07), hence the "(not yet released)" hint is no longer needed.
> Remove outdated "(not yet released)" hint

- crates/paths/src/lib.rs
> minor: Fix `AbsPath::ends_with`

- crates/hir_def/src/data.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/nameres/collector.rs
With per-block `ItemTree`s, the file ID will not be enough to identify an `ItemTree`.
bors r+
> internal: Add `TreeId` to identify `ItemTree`s

- Cargo.lock
- crates/cfg/src/lib.rs
- crates/project_model/Cargo.toml
- crates/project_model/src/lib.rs
- crates/project_model/src/tests.rs
- crates/project_model/test_data/hello-world-metadata.json
> internal: add simple smoke test for project model

- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/tests/coercion.rs
> fix: Determine expected parameters from expected return in calls

- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/tests/coercion.rs
This reverts commit 8c8c6fb73da613b915e4b18decd74f06d46ab76a, reversing
changes made to ec7b4cbf8f7d6d88ae5280b72a93a7e5d0adb7c4.
bors r+
> Revert #9655 because it breaks some type inference

- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/tests/item_list.rs
This pr hides keyword suggestions in non trivial paths:
Previously rust analyzer suggested a lot of keywords even when completing non trivial paths:
This had 2 problems:
1. Suggesting a keyword in this position doesn't make sense.
2. There are a lot of keywords, so they make it a lot harder to find the things you're actually looking for (note the scrollbar and that `instructions`, `registers` and `structures` are not visible).
> hide keyword suggestions in non trivial paths

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/hir_ty/src/tests/macros.rs
- crates/hir_ty/src/tests/method_resolution.rs
- crates/hir_ty/src/tests/traits.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9650
Also fixes a bunch of incorrect tests that were importing private items.
bors r+
> fix: only import public items from other crates

- Cargo.lock
- crates/hir_def/Cargo.toml
- crates/hir_def/src/body.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/mod_resolution.rs
- crates/hir_expand/Cargo.toml
- crates/hir_expand/src/db.rs
- crates/hir_ty/Cargo.toml
- crates/hir_ty/src/autoderef.rs
- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_completion/src/lib.rs
- crates/ide_db/Cargo.toml
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_db/src/items_locator.rs
- crates/limit/Cargo.toml
- crates/limit/src/lib.rs
Partially fixes #9286.
This introduces a new `Limits` structure which is passed as an input
to `SourceDatabase`. This makes limits accessible almost everywhere in
the code, since most places have a database in scope.
One downside of this approach is that whenever you query limits, you
essentially do an `Arc::clone` which is less than ideal.
Let me know if I missed anything, or would like me to take a different approach!
> Add first-class limits.

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
I saw reference to globs in #7755, but it doesn't look like they're
actually supported, and I had to dig through the source to discover
that the folders are relative to the workspace root. Further digging
was required to get VS Code from hanging for long periods trying to
watch giant Bazel folders that had already been excluded from Rust
Analyzer. Hopefully this tweak will save others the confusion :-)
> minor update to excludeDirs doc

- crates/ide/src/highlight_related.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/generated_config.adoc
- editors/code/package.json
- editors/code/src/config.ts
Adds basic configuration that allows you to control when the highlight related feature is activated. You can control this for references, break points, exit points, and yield points.
Resolves #9618
> Add Configuration for Highlight Related Feature

- crates/hir/src/attrs.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/attr.rs
- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/context.rs
This adds `CompletionContext::is_visible` as a convenience method that checks visibility, presence of `doc(hidden)`, and whether the completed item is in the same crate as the completion site or not. We only complete `doc(hidden)` items from the same crate.
This doesn't yet work for *all* completions: `qualified_path` completions use `Module::scope` and `ScopeDef`, which doesn't work with this.
Part of https://github.com/rust-analyzer/rust-analyzer/issues/7718
> Respect `#[doc(hidden)]` in dot-completion

- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/completions/record.rs
- crates/ide_completion/src/completions/snippet.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/tests.rs
- crates/ide_completion/src/tests/expression.rs
- crates/ide_completion/src/tests/item.rs
- crates/ide_completion/src/tests/item_list.rs
- crates/ide_completion/src/tests/pattern.rs
- crates/ide_completion/src/tests/predicate.rs
- crates/ide_completion/src/tests/type_pos.rs
> internal: Move out expression based `unqualified_path` completion tests

- crates/base_db/src/fixture.rs
- crates/ide/src/references.rs
- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/context.rs
- crates/test_utils/src/fixture.rs
This checks if a private item's location is editable (local source root), and completes them anyways if that's the case.
In order to test this, the `new_source_root` fixture command has been changed to take a `local` or `library` value, and to apply to all *following* files instead of the preceding ones (which would be hard to understand).
bors r+
> Complete editable private items

- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide_assists/src/handlers/fill_match_arms.rs
- crates/ide_db/src/helpers.rs
Enables goto def, syntax highlighting and hover for `Foo` in `#[derive(Foo)]`.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/4413
bors r+
> feat: Resolve derive attribute input macro paths in ide layer

- docs/dev/guide.md
Right thing might be to update the spelling in the code to
follow American instead of English spelling, that is
using only canceled. But they should at least be aligned.
> Use same cancelled spelling in doc and code.

- docs/dev/guide.md
- docs/dev/lsp-extensions.md
- docs/dev/style.md
- docs/dev/syntax.md
I took some time to clean up the dev docs a bit since I spent the whole week reading them. I am not a native speaker, so if you find something wrong please tell me and I'll fix it 😁
> docs: Fix several typos and grammar mistakes

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
> minor: simplify

- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/ide_diagnostics/src/handlers/unresolved_macro_call.rs
This stops prepending `self::` to single-ident macro paths, resolving even legacy-scoped macros using the fixed-point algorithm. This is not correct, but a lot easier than fixing this properly (which involves pushing a new scope for every macro definition and invocation).
This allows resolution of macros from the prelude, fixing https://github.com/rust-analyzer/rust-analyzer/issues/9687.
> fix: Remove the legacy macro scoping hack

- crates/hir/src/lib.rs
- crates/ide_completion/src/completions/attribute/derive.rs
- crates/ide_completion/src/completions/pattern.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/context.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/2003
This continues https://github.com/rust-analyzer/rust-analyzer/pull/9681 and makes most other completion sources respect `#[doc(hidden)]`. After this, only flyimport is missing support for this.
bors r+
> feat: Make most completions respect `#[doc(hidden)]`

- crates/hir/src/from_id.rs
- crates/hir/src/lib.rs
- crates/ide_assists/src/handlers/qualify_path.rs
- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_db/src/items_locator.rs
Resolves a FIXME and simplifies downstream code
bors r+
> internal: Stop reexporting `hir_def`'s `ItemInNs` from HIR

- crates/vfs-notify/Cargo.toml
It looks like the `INotifyWatcher::new` method was removed sometime after `5.0.0-pre.3` and then added back in `5.0.0-pre.11`. Without the `=`, cargo can resolve some version from `5.0.0-pre.4` -> `5.0.0-pre.10` which will not compile.
> Bump notify to 5.0.0-pre.11

- crates/hir/src/lib.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/context.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7718 (we still don't respect `#[doc(hidden)]` on reexports, but that is tracked by https://github.com/rust-analyzer/rust-analyzer/issues/9197)
bors r+
> feat: Make flyimport respect `#[doc(hidden)]`

- Cargo.lock
- crates/ide_assists/Cargo.toml
- crates/ide_assists/src/handlers/extract_function.rs
- crates/syntax/src/ast/node_ext.rs
This also prevents it from looking into local items unnecessarily(which might even cause problems in some cases)
bors r+
> internal: Use more strictly typed syntax nodes for analysis in extract_function assist

- crates/ide_assists/src/handlers/replace_string_with_char.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
Adds the counterpart for the `replace_string_with_char` assist and fixes the assist not escaping the `'` in the string `"'"` when transforming that to a char.
bors r+
> feat: Add `replace_char_with_string` assist

- Cargo.lock
- crates/proc_macro_api/Cargo.toml
- crates/proc_macro_srv/Cargo.toml
- crates/syntax/Cargo.toml
Upgrade `rowan` and avoid the duplicate `object` dependency.
> minor: Bump deps

- crates/ide/src/inlay_hints.rs
The current type hints do not go well with `bindings_after_at` which is likely to land with 1.56(https://github.com/rust-lang/rust/pull/85305 🎉very excited for this), hence annotate the names of ident patterns instead of the entire pattern.
This changes where the typehints go for ident patterns that use @ bindings, some example comparisons:
Before:
After:
This change has no visible effect on patterns without `@` bindings.
> fix: Annotate type hints for pattern name ranges instead of the pattern itself

- crates/ide_assists/src/handlers/generate_function.rs
- crates/ide_assists/src/handlers/generate_getter.rs
- crates/ide_assists/src/utils.rs
Fixes #9713
Although that's still not relying on sematic info.
> fix: Favor `deref`fed types in "Generate function" assist

- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/hir_ty/src/diagnostics/match_check.rs
- crates/ide/src/highlight_related.rs
- crates/ide_completion/src/context.rs
- crates/ide_db/src/helpers.rs
- crates/ide_diagnostics/src/handlers/missing_ok_or_some_in_tail_expr.rs
- crates/syntax/src/ast/expr_ext.rs
Fixes #8512
Also fixes a bug in for_each_tail_expr not visiting `else if` chains
> fix: Wrap inner tail expressions in MissingOkOrSomeInTailExpr

- editors/code/package.json
By changing the scope of this configuration to `machine-overridible`, this setting becomes fully local for the VS Code instance the user is running.
Having this setting excluded from syncing should help avoid inconveniences for users who have VS Code installed on two different operating systems, where the paths to the language server binary would very likely mismatch.
> Exclude `rust-analyzer.server.path` from VS Code's sync feature

- docs/dev/syntax.md
Being new to Rust I wasn't familiar with this acronym and found it hard to guess (the context of syntax trees biased me to reading it as a D-something Syntax Tree and trying to guess what the D was), hard to google (in retrospect googling "rust dst" does the job, but I thought it was an abstract structure thing, not Rust-specific), and hard to Github-search, because `dst` is commonly short for “destination” in code.
Alternatively `<abbr title="dynamically sized type">DST</abbr>` would be about as helpful.
> Link “DST” to its definition

- crates/project_model/src/project_json.rs
- crates/project_model/src/tests.rs
- crates/project_model/src/workspace.rs
- crates/project_model/test_data/hello-world-project.json
- crates/project_model/test_data/is-proc-macro-project.json
- docs/user/manual.adoc
This adds the `is_proc_macro` flag in `rust-project.json`. By default, this is `false` and not required, so existing projects won't break/have the same behavior as before this change. If the flag is true, a dependency to the `proc_macro` sysroot crate is added (if it exists), so that rust-analyzer can resolve those imports.
This fixes #9726 .
I've also added some tests in the second commit. The first is a smoke test for a basic, minimal `rust-project.json` file. The second is a more targeted test for the flag. Both tests depend on the fake sysroot (a bunch of directories in the correct layout with empty `lib.rs` files), and also on `env!("CARGO_MANIFEST_DIR")` being an absolute path. I'm not sure if the later assumption is valid on all platforms. I wanted to at least try and add tests, …
> feature: Declare proc-macro dependent crates in `rust-project.json`

- crates/rust-analyzer/src/cli.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
This [commit](https://github.com/rust-analyzer/rust-analyzer/commit/b24f816c0d8aaa37fbc0b33f90dd67afbf28adaa) which restricted the visibility of `LoadCargoConfig`, `fn load_workspace_at` & `fn load_workspace` unfortunately effectively rendered every crate/tool that uses rust-analyzer as a library dead in the water.
On of such tools is [cargo-modules](https://github.com/regexident/cargo-modules), a tool for generating tree/graph visualizations of one's Rust project and is powered by rust-analyzer as a library.
For more context see the PRs that introduced those types/functions and made them `pub`:
- https://github.com/rust-analyzer/rust-analyzer/pull/7595
- https://github.com/rust-analyzer/rust-analyzer/pull/7690
If kept as is rust-analyzer would effectively no longer be usable as a …
> Make `LoadCargoConfig`, `fn load_workspace_at` & `fn load_workspace` public again

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide/src/hover.rs
This applies to both the ranged hover request as well as the normal hover type fallback.
We unfortunately have to leave out syntax highlighting here as otherwise the `Type` and `Coerced` words in the hover will get colored.
Note that this does not show all the coercions yet(and almost no pattern coercions) as not all coercion adjustments are implemented yet.
Closes https://github.com/rust-analyzer/rust-analyzer/issues/2677
> feat: Show coerced types on type hover

- crates/ide_completion/src/completions/flyimport.rs
The problem was that the candidate node is whats being used for the scope, so using an inline module will yield the surrounding scope of the module instead of the scope of the module itself.
Also seems to fix the problem in this comment https://github.com/rust-analyzer/rust-analyzer/issues/9760#issuecomment-891125674, though I could not recreate that in a test for some reason.
Fixes #9760
> fix: Don't use the module as the candidate node in fuzzy path flyimport

- Cargo.lock
- crates/vfs-notify/Cargo.toml
- crates/vfs-notify/src/lib.rs
> Downgrade notify and use `RecommendedWatcher`

- editors/code/src/main.ts
@yoshuawuyts and I ran into an issue where my rust-analyzer binary path was set in my extension config (which I didn't realize), but the path set in the config was invalid (it simply wasn't on my path). Having an error message that hinted that the binary's path was explicitly set in the config would have considerably shortened the debug time. 
Thanks!
> Give better error message when the rust-analyzer binary path was set in the user's config but the binary is invalid

- crates/hir_expand/src/lib.rs
- crates/ide_diagnostics/src/handlers/inactive_code.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9753
`HirFileId::expansion_info` can return `None` for builtin macros or if there's an error in the macro call or definition, so add a `HirFileId::is_macro` method that checks the right thing.
bors r+
> fix: Fix detection of macro file in inactive-code diag

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide_assists/src/handlers/extract_function.rs
- crates/test_utils/src/minicore.rs
> fix: extract_function does not move locals defined outside of loops

- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/completions/record.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/struct_literal.rs
- crates/ide_completion/src/tests/expression.rs
This PR adds a new completion for struct literal.
It Implements the feature discussed in the issue #9610.
This PR introduce a repetition in the source files `crates/ide_completion/render/pattern.rs` and `crates/ide_completion/render/struct_literal.rs` that may be fix in another PR.
> feature: Add completion for struct literals in which all fields are visible.

- crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt
- crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
rustc renders the diagnostic text for suggestions by including the suggested replacement at the end (`` help: a function with a similar name exists: `boo` ``), but the emitted JSON diagnostic does not include this in the message. This causes our diagnostics to lack some useful info, so this PR fixes that by appending any suggested replacements to the message.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9797
Before:
After:
bors r+
> feat: Include suggested replacement in diagnostics

- crates/proc_macro_srv/src/abis/abi_1_56/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/buffer.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/client.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/closure.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/handle.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/rpc.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/scoped_cell.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/bridge/server.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/diagnostic.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_56/proc_macro/quote.rs
- crates/proc_macro_srv/src/abis/abi_1_56/rustc_server.rs
- crates/proc_macro_srv/src/abis/mod.rs
I've copied the latest proc macro source from Rust nightly and modified it to compile on `stable`. This fixes #9795 . Almost everything here is uninteresting copy and paste, the interesting stuff is in `crates/proc_macro_srv/src/abis/mod.rs`. I've left the 1.55 ABI implementation in for now. We did discuss only supporting one nightly ABI so we may want to remove 1.55. That will break code which is pinned to older nightly releases but that seems acceptable to me, what do people think?
> Add proc_macro crate for the 1.56 ABI

- crates/hir_def/src/lang_item.rs
- crates/ide_completion/src/completions/flyimport.rs
Examples for lang enum variants are the `Option` variants.
Assoc trait functions aren't being seen since they aren't declared in the direct module scope.
> fix: Look for enum variants and trait assoc functions when looking for lang items

- crates/hir_ty/src/traits.rs
This makes the experience better for people using `tonic`, see https://github.com/rust-analyzer/rust-analyzer/issues/7817.
> fix: Increase chalk overflow depth

- crates/ide/src/hover.rs
- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_assists/src/tests/generated.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
- crates/syntax/src/ast/make.rs
- crates/test_utils/src/minicore.rs
This patch makes it so when you convert `#[derive(Debug)]` to a manual impl, a default body is provided that's equivalent to the original output of `#[derive(Debug)]`. This should make it drastically easier to write custom `Debug` impls, especially when all you want to do is quickly omit a single field which is `!Debug`.
This is implemented for enums, record structs, tuple structs, empty structs - and it sets us up to implement variations on this in the future for other traits (like `PartialEq` and `Hash`).
Thanks!
This is the difference in codegen for record structs with this patch:
```diff
struct Foo {
bar: String,
}
impl fmt::Debug for Foo {
fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
-        todo!();
+        f.debug_struct("Foo").field("bar", &self.bar).finish()
}
} …
```
> Generate default impl when converting `#[derive(Debug)]` to manual impl

- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/test_utils/src/minicore.rs
Similar to https://github.com/rust-analyzer/rust-analyzer/pull/9814, but for `#[derive(Default)]`. Thanks!
I've added the tests inside `handlers/replace_derive_with_manual_impl.rs` again, but I'm planning a follow-up PR to extract these to `utils/` so we can share them between assists - and maybe even add another assist just for the purpose of testing these impls (e.g. `generate_default_trait_body`).
The step after _that_ is likely to fill out the remaining traits, so we can make it so whenever RA auto-completes a trait which also can be derived, we provide a default function body.
> Generate default impl when converting #[derive(Default)] to manual impl

- crates/ide_assists/src/handlers/generate_function.rs
- crates/ide_assists/src/lib.rs
- crates/syntax/src/ast/make.rs
Needs a bit of refactoring. Tests also should be added.
> Generate method from call

- crates/hir/src/has_source.rs
- crates/ide_assists/src/handlers/add_missing_impl_members.rs
- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_assists/src/utils.rs
- crates/ide_assists/src/utils/gen_trait_body.rs
- crates/ide_assists/src/utils/gen_trait_fn_body.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
Enable more assists to benefit from trait body generation. Follow-up to #9825 and #9814.
__edit:__ I'd like to move the existing tests to this new file too, but I'll do that in a follow-up PR.
> Enable more assists to generate default trait body impls

- crates/ide_completion/src/completions/record.rs
- crates/ide_completion/src/patterns.rs
- crates/ide_completion/src/tests/record.rs
cc https://github.com/rust-analyzer/rust-analyzer/issues/9839
bors r+
> fix: Do not drop `..Default::default()` completion when typing `..`

- crates/rust-analyzer/src/handlers.rs
- editors/code/.vscodeignore
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/ctx.ts
This PR removes the need for having `graphviz` installed on the user system by using the `d3-graphviz` npm package.
The responsibility of rendering the svg output is moved to the extension while the rust side only handles the generation of the dot file.
This change also brings the following additional features:
- Allow zooming the view
- Ctrl+click to reset the zoom 
- Adjust the color scheme to dark themes
- Works on any platform without installing graphviz locally
---
I’m not sure if this fits what you had in mind for the crates graph feature but I decided to submit it anyway to see if this is useful to anyone else. 
A potential downside might be that it increases the extension size ( haven’t checked) but this feature already required the installation of graphviz on the user side, so …
> Remove dependency on the system graphviz when rendering crate graph

- crates/vfs/src/lib.rs
- crates/vfs/src/loader.rs
This PR cleans up some of the iteration idioms used in the `vfs` crate. Most of the changes simply converted `for` loops into their `std::iter::Iterator`-method counterpart. Other changes required some inversion of logic to accommodate for better short-circuiting. Overall, there should be no behavioral changes. If there are any stylistic issues, I will gladly adhere to them and adjust the PR accordingly. Thanks!
> Refactor: quick clean-up of iteration idioms in the `vfs` crate

- crates/ide_assists/src/handlers/generate_function.rs
When showing the user the `generate_function` assist, use the term "method" when generating a method instead of the term "function" (which is correct but maybe not the most appropriate in that context).
> Use term "method" on label for generating method impl

- crates/hir/src/display.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/item_tree/tests.rs
- crates/hir_def/src/type_ref.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/chalk_db.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/coercion.rs
- crates/hir_ty/src/tests/display_source_code.rs
- crates/hir_ty/src/tests/method_resolution.rs
- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/utils.rs
- crates/ide/src/hover.rs
- crates/ide/src/inlay_hints.rs
- crates/ide_assists/src/handlers/generate_function.rs
This should close #8984 
`hir_ty`:
- Type parameters, associated types and `impl Trait` are `Sized` by deafault except `Self` in a trait.
- Implicit `Sized` bound is added to end of predicate list. It does not check if such bound is present already. Also it does not track the bound is implicit.
- Allowed ambiguous unsize coercion if Chalk returns definite guidance.
- Allowed ambiguous autoderef if Chalk returns definite guidance.
`hir_def`:
- `ItemTree` pretty printing shows `?Sized` bounds.
`HirDisplay`:
- `impl Trait` with weird bounds rendered correctly.
- `Sized`/`?Sized` bounds are not shown if they are default.
`./target/rust-analyzer-baseline_8a843113 -q analysis-stats --memory-usage .`
```
Database loaded:     1.63s, 287minstr, 91mb
crates: 38, mods: 741, decls: 15914, fns: 11835 …
```
> Implicit `Sized` bounds

- crates/project_model/src/workspace.rs
Even crates that don't set `proc-macro = true` are allowed to depend on `proc_macro` (just none of the APIs work when called outside of a proc macro).
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9857
bors r+
> fix: Always add implicit `proc_macro` dependency

- Cargo.lock
- crates/hir_def/src/body/lower.rs
- crates/hir_def/src/body/scope.rs
- crates/hir_def/src/expr.rs
- crates/hir_ty/src/infer/expr.rs
- crates/ide_assists/src/handlers/move_guard.rs
- crates/parser/src/grammar/expressions/atom.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/test_data/parser/inline/ok/0118_match_guard.rast
- crates/syntax/test_data/parser/inline/ok/0118_match_guard.rs
Adds support for parsing and computing bindings for `if let` match guards (https://github.com/rust-lang/rust/issues/51114). Type inference support is still missing, but shouldn't be hard to add in a follow-up PR.
Closes https://github.com/rust-analyzer/rust-analyzer/issues/9876
bors r+
> feat: Support `if let` match guards

- editors/code/src/toolchain.ts
Fixes #9872
It looks like `compile` expects to be called like `RegExp.compile("foo", "m")`, so calling `.compile()` on an existing regex replaces it with an empty one.
> fix: Don't call deprecated `compile` regex method

- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/ide_assists/src/handlers/generate_function.rs
- crates/ide_assists/src/utils.rs
Fixes the crash in the comment here https://github.com/rust-analyzer/rust-analyzer/issues/9382#issuecomment-896101298
Couldn't make out a repro test for this unfortunately
still not idea about the original issue
> fix: Don't use uncached syntax nodes in `generate_function` for sema lookups

- Cargo.lock
- crates/vfs-notify/Cargo.toml
- crates/vfs-notify/src/lib.rs
This reverts commit 5b0c86af7d1683983a35f232baa7c98cfa3c382d.
The pre-5.0.12 release of notify fixed this issue.
@lnicola Could you verify that this now works on NetBSD?
> Revert "Downgrade notify and use RecommendedWatcher"

- crates/ide_assists/src/handlers/generate_enum_is_method.rs
- crates/ide_assists/src/tests/generated.rs
While authoring https://github.com/rust-lang/rust/pull/88154 I realized that the codegen for the `enum_generate_is_method` assist currently generates invalid paths, and used snake case instead of spaces for the docs description. This fixes both issues. Thanks!
> Fix codegen for is_method documentation

- crates/ide_assists/src/handlers/destructure_tuple_binding.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
Part of #8673. This PR only handles tuples, not TupleStruct and RecordStruct.
Code Assist to destructure a tuple into its items:
* Should work in nearly all pattern positions, like let assignment, function parameters, match arms, for loops, and nested variables (`if let Some($0t) = Some((1,2))`)  
-> everywhere `IdentPat` is allowed
* Exception: If there's a sub-pattern (`@`):
```rust
if let t @ (1..=3, 1..=3) = ... {}
//     ^
```
-> `t` must be a `Name`; `TuplePat` (`(_0, _1)`) isn't allowed
* inside subpattern is ok:
```rust
let t @ (a, _) = ((1,2), 3);
//       ^
```
->
```rust
let t @ ((_0, _1), _) = ((1,2), 3);
```
* Assist triggers only at tuple declaration, not tuple usage.  
(might be useful especially when it creates a sub-pattern (after `@`) and only changes the usage under …
> feature: Destructure Tuple Assist

- crates/hir/src/semantics.rs
- crates/hir_def/src/builtin_attr.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_attr.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/runnables.rs
This causes runnables to work for paths that actually resolve to the `test` attribute now.
Prior to this we replaced items annotated with builtin attributes by the attribute input instead of the item in our dummy expansion which is why the fully written path didn't work as we actually discarded the item while `test` was just ignored.
Fixes #9935
> fix: Do not replace items annotated with builtin attrs with the attr input

- crates/hir_expand/src/builtin_attr.rs
- crates/hir_expand/src/db.rs
`tt` and `item` here were the same, I misunderstood what the main input for attributes was in #9943
bors r+
> minor: Don't ask for the builtin attribute input twice

- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/coercion.rs
> Handle coercion on binary operator RHS

- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/tests/regression.rs
Chalk can introduce new type variables when doing lazy normalization, so we have to do the proper 'fudging' after all.
> minor: Fix panic caused by #9966

- crates/hir/src/semantics.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/ide_completion/src/completions/trait_impl.rs
- crates/paths/src/lib.rs
> minor: Fix typos “a”→“an”

- crates/ide_assists/src/handlers/generate_function.rs
Separated code generation from finding position for generated code. This will be ground work for introducing static associated function generation.
> refactor : function generation assists

- crates/ide/src/references.rs
> minor: Fix another “a”/“an” typo

- crates/hir_ty/src/diagnostics/decl_check/case_conv.rs
- crates/hir_ty/src/diagnostics/match_check/usefulness.rs
Follow-up to #9985
you guys are merging these fast 😅
> Fix two more “a”/“an” typos

- crates/hir_def/src/path/lower.rs
- crates/ide/src/inlay_hints.rs
- crates/mbe/src/expander.rs
- crates/parser/src/parser.rs
Follow-up to #9987
you guys are still merging these fast :sweat_smile:
_this time I thought – for sure – that I’d get this commit into #9987 before it’s merged…_
> Fix two more “a”/“an” typos (this time the other way)

- crates/ide/src/highlight_related.rs
- crates/ide/src/references.rs
> feat: Highlight declarations and references for both defs in field shorthands

- crates/ide_assists/src/handlers/generate_function.rs
Adds feature: #9948
Will soon send a GIF for the changelog.
> add static method generation assist

- crates/rust-analyzer/src/handlers.rs
- docs/dev/style.md
> internal: use idiomatic form of assertions

- crates/ide/src/join_lines.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Closes https://github.com/rust-analyzer/rust-analyzer/issues/9967.
> feat: join lines merges assignments

- crates/ide_assists/src/handlers/convert_iter_for_each_to_for.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/edit_in_place.rs
Introduce `edit_in_place::Indent` that uses mutable tree API and intended to replace `edit::AstNodeEdit`.
Closes #9903
> internal: introduce in-place indenting API

- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/keys.rs
- crates/hir_def/src/nameres/collector.rs
- crates/ide/src/expand_macro.rs
Expands the derive attribtue under the cursor.
This probably does not work with items that have attributes ***and*** derives since we don't descend the cursor token into macro invocations first, for obvious reasons(we could do this to check for derives first to fix this).
(Note that we do not expand built-ins to what rustc usually expands as we only really need the impl for analysis)
Closes https://github.com/rust-analyzer/rust-analyzer/issues/4005
> feat: Expand derive macros under cursor in `Expand Macro Recursively`

- editors/code/package.json
ref: https://github.com/rust-analyzer/rust-analyzer/pull/10061
Currently, target version is not specified so it's esnext.
https://esbuild.github.io/api/#target
VSCode uses node 14 since version 1.56.
https://github.com/rust-analyzer/rust-analyzer/issues/3167#issuecomment-907058367
> Set esbuild target as node14

- Cargo.lock
- crates/paths/Cargo.toml
- crates/paths/src/lib.rs
- crates/proc_macro_api/src/lib.rs
- crates/proc_macro_api/src/msg.rs
- crates/proc_macro_api/src/process.rs
- crates/proc_macro_api/src/rpc.rs
- crates/proc_macro_api/src/rpc/flat.rs
- crates/proc_macro_srv/src/cli.rs
- crates/proc_macro_srv/src/lib.rs
- crates/proc_macro_srv/src/tests/utils.rs
- crates/syntax/Cargo.toml
- crates/tt/Cargo.toml
I wanted to *quickly* remove `smol_str = {features = "serde"}`, and figured out that the simplest way to do that is to replace our straightforward proc macro serialization with something significantly more obscure.
> internal: improve compile times a bit

- crates/ide_db/src/lib.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/10065
> internal: Use `ManuallyDrop` in `RootDatabase` to improve build times

- crates/hir/src/semantics.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/highlight_related.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/search.rs
- crates/mbe/src/tests/expand.rs
- crates/mbe/src/token_map.rs
With this we can now resolve usages of identifiers inside (proc-)macros even if they are used for different purposes multiple times inside the expansion.
Example here being with the cursor being on the `no_send_sync_value` function causing us to still highlight the identifier in the attribute invocation correctly as we now resolve its usages in there. Prior we only saw the first usage of the identifier which is for a definition only, as such we bailed and didn't highlight it. 
Note that this has to be explicitly switched over for most IDE features now as pretty much everything expects a single node/token as a result from descending.
> Downmap tokens to all token descendants instead of just the first

- .github/workflows/release.yaml
Ubuntu 16.04 is EOL since April, let's upgrade to 18.04.
bors r+
> internal: Use Ubuntu 18.04 on CI

- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/main_loop.rs
> internal: don't shut up the compiler when it says the code's buggy

- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/lib.rs
- crates/project_model/src/tests.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/config.rs
This is to allow for efficiently disabling `#[cfg(test)]` on all crates (by passing `unset_test_crates: UnsetTestCrates::All`) without having to first load the crate graph, when using rust-analyzer as a library.
(FYI: The change doesn't seem to be covered by any existing tests.)
> Extend `CargoConfig.unset_test_crates` 

- crates/ide_diagnostics/src/handlers/missing_fields.rs
This PR tweaks the fill struct fields assist to use the struct init shorthand when a local variable with a matching name and type is in scope.
For example:
```rust
struct Foo {
a: usize,
b: i32,
c: char,
}
fn main() {
let a = 1;
let b = 2;
let c = 3;
let foo = Foo { <|> };
}
```
Before we would insert
```rust
Foo {
a: (),
b: (),
c: (),
}
```
now we would insert
```rust
Foo {
a,
b,
c: ()
}
```
> Use struct init shorthand when applicable in fill struct fields assist

- crates/ide_diagnostics/src/handlers/replace_filter_map_next_with_find_map.rs
`find_map` misspelt as `wind_map` in test identifier.
> Fix minor mispelling

- crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ide_assists/src/tests/generated.rs
Improves the struct generated by `extract_struct_from_enum_variant`.
Summary of changes:
- Indent the generated struct and enum to the same indent level
- Preserve comments & attributes from the enum variant (something I missed when doing the same thing for the variant fields)
- Use enum's visibility for fields without any visibility, instead of filling it in with `pub`
> feat: Improve `extract_struct_from_enum_variant` output

- Cargo.lock
- crates/cfg/Cargo.toml
- crates/cfg/src/cfg_expr.rs
- crates/cfg/src/dnf.rs
- crates/cfg/src/tests.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10073
The DNF construction code created expressions that were combined in a way that made us "forget" to make their contents valid DNF again. This PR fixes that by flattening nested `any(any())` and `all(all())` predicates. There was also a typo that led to a redundant call to `make_nnf` instead of the correct recursive call to `make_dnf` (but this didn't seem to break/fix anything).
This also adds some light property testing, though I'm not really sure this is the best way to do it.
> fix: fix "disjunction in conjunction" panic

- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/9992 (method resolution of these methods still does not work)
bors r+
> fix: Allow inherent impls for arrays

- crates/hir_def/src/nameres/path_resolution.rs
Should help with debugging https://github.com/rust-analyzer/rust-analyzer/issues/10084 and similar issues.
Might have a perf impact since the string is created on every function call.
> internal: Augment panic context when resolving path

- crates/hir_ty/src/infer/pat.rs
- crates/ide/src/hover.rs
Basically this just shows the type of the inner expression of the `?` expression as well as the type of the expression that the `?` returns from:
Unless both of these types are `core::result::Result` in which case we show the error types only.
If both types are `core::option::Option` with different type params we do not show this special hover either as it would be pointless(instead fallback to default type hover)
Very much open to changes to the hover text here(I suppose we also want to show the actual type of the `?` expression, that is its output type?).
Fixes #9931
> feat: Show try operator propogated types on ranged hover 

- crates/ide/src/annotations.rs
- crates/ide/src/call_hierarchy.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/ide/src/runnables.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/handlers.rs
Part of https://github.com/rust-analyzer/rust-analyzer/issues/10070
I was hoping that this would fix "find references" on salsa queries, but salsa emits multiple defs sharing the same span (the trait method, and an impl of that trait).
> fix: make "find references" multi-token mapping aware

- crates/ide/src/highlight_related.rs
- crates/ide_db/src/search.rs
> fix: Use correct search scopes for macros

- crates/hir/src/semantics.rs
(with `#[test]` expansion enabled)
The problem was pretty simple, since we go through the ancestors we first try to expand the macro call node we are in since in attributed items these are valid syntaxnodes instead of TokenTrees, we then fail the expansion since the expansion only exists in the attribute expanded file and therefor skip the attribute expansion due to returning immediately. So instead of breaking out we just continue looking up the ancestors.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10115
bors r+
> fix: When descending tokens don't bail on failed macro call expansions

- docs/dev/README.md
Currently, we're using `tracing` for logging, but the doc is lagging, so update it.
#9274
> docs(logging): use `tracing` for logging

- crates/base_db/src/input.rs
- crates/flycheck/src/lib.rs
- crates/hir/src/has_source.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/eager.rs
- crates/hir_ty/src/chalk_db.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/diagnostics/decl_check.rs
- crates/hir_ty/src/diagnostics/match_check/deconstruct_pat.rs
- crates/hir_ty/src/diagnostics/match_check/usefulness.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/closure.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/pat.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/traits.rs
- crates/hir_ty/src/walk.rs
- crates/mbe/src/tests.rs
> minor: fix some clippy lints

- crates/ide_assists/src/handlers/replace_for_loop_with_for_each.rs
Previously, the assist would turn this:
```rust
for x in 0..92 {
...
}
```
into the syntactically incorrect code below:
```rust
0..92.for_each(|x| ...)
```
This fixes the assist by parenthesizing range expressions.
> Fix replacing for loops over ranges with for_each.

- Cargo.lock
- crates/profile/Cargo.toml
- crates/stdx/Cargo.toml
> minor: Update dependency minor versions

- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/style.md
> fix: don't panic if the client sends invalid request

- crates/ide_assists/src/handlers/extract_function.rs
- crates/ide_assists/src/handlers/generate_function.rs
- crates/ide_assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
> fix: use placeholder as default type in `Generate function` and `Extract into function`.

- docs/user/manual.adoc
I *think* people might try to debug ra by using only the troubleshooting
section. Might make sense to point them to dev docs then!
bors r+
🤖
> docs: make dev docs more discoverable

- crates/hir_def/src/nameres.rs
- crates/ide_db/src/symbol_index.rs
This PR replaces the old name `CrateDefMap` in comments with the new name `DefMap`. The renaming was done in [57a82fb0](https://github.com/rust-analyzer/rust-analyzer/commit/57a82fb0) (Jan 2021).
I didn't touch the working code ([CrateDefMapQueryQuery][QQ]). Thank you.
[QQ]: https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide_db/src/apply_change.rs#L126
> Minor: replace old name `CrateDefMap` in comments

- Cargo.lock
- crates/hir_def/src/attr.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/Cargo.toml
- crates/hir_expand/src/builtin_derive.rs
- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests.rs
- crates/parser/src/lib.rs
internal: remove accidental code re-use
FragmentKind played two roles:
* entry point to the parser
* syntactic category of a macro call
These are different use-cases, and warrant different types. For example,
macro can't expand to visibility, but we have such fragment today.
This PR introduces `ExpandsTo` enum to separate this two use-cases.
I suspect we might further split `FragmentKind` into `$x:specifier` enum
specific to MBE, and a general parser entry point, but that's for
another PR!
bors r+
🤖
> internal: remove accidental code re-use

- crates/hir_def/src/body/lower.rs
- crates/ide_completion/src/completions/dot.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8158
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10039
This issue was not caused by us not being able to expand the macro (we can do that just fine). Instead, body lowering deliberately aborted lowering of a statement macro expansion when the expansion causes errors, citing some hygiene-related issue with recovery (@edwin0cheng if you remember what exactly the issue was I'd be happy to take a look).
Simply removing that code path doesn't cause any tests to fail, and makes completions in macros work better ("completion after `.`" is not the only thing that now works better, we also get better highlighting in incomplete macro calls).
Just to be sure, lets merge this after tomorrow's release.
> feat: enable completions inside macros after `.`

- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/tests/attribute.rs
Currently ra emits `#![recursion_limit = 128]`, but this should rather be `#![recursion_limit = "128"]`
> feat: Complete `#![recursion_limit = "N"]` instead of `#![recursion_limit = N]`

- docs/user/manual.adoc
When using `rust-project.json` to specify the project workspace, flychecks are disabled. It is not mentioned that they can be re-enabled by specifying a custom checking command using the `checkOnSave.overrideCommand` configuration. This additional section makes it clear that using `rust-project.json` disables flychecks and how to enable them either using `cargo check` (as an example) or (more likely) a custom command which emits json error messages.
Further information can be found at this forum thread:
https://users.rust-lang.org/t/rust-analyzer-doesnt-show-cargo-check-compilation-errors-warnings-when-using-rust-project-json/64412
> Add section on configuring compilation errors when using `rust-project.json`

- crates/ide_completion/src/render.rs
Adds support for valid Rust completion of raw identifiers.
Previously, code completion of fields made via raw identifiers would not re-insert those raw identifiers, resulting in invalid Rust code. Now, code completion of fields made via raw identifiers do re-insert those raw identifiers, resulting in valid Rust code.
The same is true for all code completion instances for fields and compatible Rust identifiers.
> feat: Add completion for raw identifiers

- docs/dev/README.md
Currently, the correct configuration of sysroot is `rust-analyzer.cargo.noSysroot (default: false)`.
> minor: docs: fix unknown configuration setting

- Cargo.lock
- crates/hir_ty/Cargo.toml
- crates/rust-analyzer/Cargo.toml
I've updated tracing-tree to 0.1.10, which does not pull in syn and proc-macro2 (thanks for [the PR](https://github.com/davidbarsky/tracing-tree/pull/32), @matklad!).
It took a little bit more work than I expected to land https://github.com/davidbarsky/tracing-tree/issues/33, but I should get that done this week. However, I didn't want to keep y'all waiting, so here's _some_ of the changes that should hopefully improve your compile times.
> update to tracing-tree 0.1.10, which does not pull in syn

- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
My second attempt at fixing #9992 , previous attempt was here: #10017 , but the logic was broken.
I know that this is not an ideal solution.... that would require, IIUC, a pretty big overhaul of the const generics handling in `rust-analyzer`. But, given that some of the array methods were/are being stabilized (e.g. https://github.com/rust-lang/rust/pull/87174 ), I think it'll be very beneficial to `rust-analyzer` users to have some preliminary support for them. (I know it's something I've been running into quite a lot lately :) )
As far as my limited understanding of this project's architecture goes, I think this isn't the worst hack in the world, and shouldn't be too much of a hassle to undo if/when const generics become better supported. If the maintainers deem this approach viable, …
> Fix resolution for inherent array methods

- editors/code/src/tasks.ts
This fixes #9093 ​introduced by #8995.
A filter was present on the function that adds the execution definition to Cargo tasks. This would mean Cargo tasks defined in workspaces (i.e. `.code-workspace` files) would not be given an execution, leading to a `There is no task provider registered for tasks of type "cargo".` error as descibed in #9093. I have made a minimum reproduction setup [here](https://github.com/oeed/ra-workspace).
This PR essentially removes that check. The `if (scope) { ... }` is to handle the case where `task.scope === undefined` using a deprecated constructor. I'm not sure if that is ever likely to occur and can remove if not needed.
There is some discussion about whether it's necessary to filter the tasks before building them. From my understanding, it shouldn't be …
> fix: Remove incorrectly filtering VS Code cargo task execution resolution by scope

- editors/code/language-configuration.json
The new bracket pair colorization feature of vscode colorizes all brackets no matter the language. In the context of rust colorizing the '<' and  '>' brackets doesn't make sense most of the time, especially in match statements with math like the following screenshot.
Currently this configuration is only possible on a language server level which is why this PR is necessary.
See https://github.com/microsoft/vscode/issues/132175 and https://github.com/microsoft/vscode/issues/132476 for more information on the issue in vscode
> configure colorizedBracketPairs

- crates/hir_def/src/nameres/collector.rs
This addresses the regression mentioned in https://github.com/rust-analyzer/rust-analyzer/issues/8961#issuecomment-916332702
(no test because https://github.com/rust-analyzer/rust-analyzer/issues/10192 makes that rather hard, but I've checked that the analysis-stats are back to normal)
bors r+
> fix: fix type mismatches with `panic!()` on Rust 1.55.0

- crates/project_model/src/cargo_workspace.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/reload.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/9070
Fixes diagnostics not showing up in path dependencies.
> fix: Treat path dependencies like workspace members

- Cargo.lock
- crates/base_db/Cargo.toml
- crates/hir/Cargo.toml
- crates/hir_expand/Cargo.toml
- crates/hir_ty/Cargo.toml
- crates/ide_completion/Cargo.toml
- crates/mbe/Cargo.toml
- crates/proc_macro_api/Cargo.toml
- crates/proc_macro_srv/Cargo.toml
- crates/rust-analyzer/Cargo.toml
- crates/syntax/Cargo.toml
- crates/vfs-notify/Cargo.toml
cargo check --all-targets compiles cleanly without these dependencies for me.
> internal: Remove unused dependencies

- crates/stdx/src/lib.rs
It's important that module interface doesn't depend on features. Better
hide features in bodies.
bors r+
🤖
> minor: improve readability

- crates/hir/src/lib.rs
- crates/hir_ty/src/method_resolution.rs
- xtask/src/install.rs
> minor: make code clearer with ControlFlow

- crates/hir/src/display.rs
- crates/hir_ty/src/lower.rs
- crates/ide/src/hover.rs
Closes  #9949
This adds implicit `: Sized` bound to type parameters at lowering step.
Hovering on type parameter does not show it's `: Sized` bound be it set explicitly or implicitly. This is because it doesn't track that the bound was set implicitly.
```rust
./target/rust-analyzer-baseline-3dae94bf -q analysis-stats --memory-usage .
Database loaded:     4.51s, 311minstr, 110mb (metadata 1.08s, 22minstr, 743kb; build 3.20s, 8730kinstr, -237kb)
crates: 38, mods: 770, decls: 17173, fns: 12835
Item Collection:     29.63s, 85ginstr, 372mb
exprs: 353460, ??ty: 364 (0%), ?ty: 232 (0%), !ty: 144
Inference:           118.25s, 284ginstr, 601mb
Total:               147.88s, 370ginstr, 973mb
./target/rust-analyzer-hover-ty-param-dfb15292 -q analysis-stats --memory-usage .
Database loaded:     4.53s, …
```
> fix: Type param hover shows correct sized bounds.

- crates/hir/src/lib.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/regression.rs
Should fix #10090, fix #10046, and fix #10179.
This is only a workaround, but the proper fix requires some bigger
refactoring (also related to fixing #10058), and this at least prevents
the crash.
> fix: Avoid type inference panic on bitslice methods

- crates/ide/src/references.rs
Defs and refs of locals only ever life in one file, this isn't true for fields though.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10201
bors r+
> Use correct file syntax node for `decl_access` computation in `find_all_refs`

- docs/user/manual.adoc
- xtask/src/release.rs
A single warning on the first line should™ be enough. Currently we put that warning on every section, while also breaking the table of contents in the process:
Fixes #9657
> minor: Don't spam the manual with warnings

- crates/base_db/src/fixture.rs
- crates/hir/src/semantics.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/tests.rs
- crates/ide_completion/src/tests/proc_macros.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
> feat: Speculatively expand attributes in completions

- crates/hir/src/semantics.rs
- crates/ide/src/fixture.rs
- crates/ide/src/goto_definition.rs
Second attempt(now with a test 🎉).
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10115
> fix: fix expansion order for fn-like macros and attributes in token descending

- crates/hir/src/semantics.rs
- crates/ide/src/inlay_hints.rs
Note the lack of chaining hints, this is currently due to macro expansion lacking the input whitespace. We might be able to recover this from the input somehow in the future.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10043
bors r+
> feat: Make inlay hints work in attributed items

- crates/ide/src/hover.rs
Addresses issue #10106.
In-progress - I'm trying to figure out why `hover_deref_expr_with_coercion` is failing.
> feat: Show the type of what is being dereferenced in a deref expression.

- crates/ide_assists/src/handlers/inline_local_variable.rs
> fix: Do not wrap inlined local in parens when at block tail position

- crates/hir/src/semantics.rs
- crates/ide/src/inlay_hints.rs
Reverts #10231 as the implementation there is actually wrong
bors r+
> internal: Revert attributed items inlay hints

- crates/ide/src/hover.rs
implement #10070 in [`hover`](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/hover.rs)
> fix: add multi-token mapping support to hovers

- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render/macro_.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9904
> fix: correctly complete macro call if cursor at `!`

- crates/flycheck/src/lib.rs
- crates/hir/src/source_analyzer.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render/enum_variant.rs
- crates/ide_db/src/call_info.rs
- crates/ide_ssr/src/lib.rs
- crates/ide_ssr/src/matching.rs
- crates/ide_ssr/src/parsing.rs
- crates/proc_macro_api/src/process.rs
- crates/vfs-notify/src/lib.rs
> internal: remove dead code

- docs/user/manual.adoc
Remove unwanted `:` and fix the naming of the boolean type.
> Fix typescript syntax errors

- crates/hir_ty/src/autoderef.rs
There's a minor typo in a comment in autoderef.rs, although the meaning is clear if your pronounce the words out loud
> Fix a comment typo in autoderef.rs

- crates/ide_assists/src/handlers/convert_while_to_loop.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
Implements an assist to turn a `while` loop into a `loop` loop, as requested in #10214. 
I'm not sure sure what the guidelines are regarding naming assists convert_x_to_y vs replace_x_with_y.
This is my first commit to rust-analyzer :D Thank you @matklad for your awesome Explaining rust-analyzer series <3
Closes #10214
> assists: turn while into loop

- crates/rust-analyzer/src/handlers.rs
Fixes #10219 panic when entering `:` in `$0` places:
```rust
fn main() {
"⊞$0";
}
```
```rust
struct S {
д$0 u8
}
```
> fix: Don't seek outside of character boundaries in completion handler

- crates/ide_assists/src/handlers/generate_function.rs
- crates/syntax/src/token_text.rs
- Improve fn name computation (close #10176).
- Handle tuple indexing expressions in argument position (should close  #10241)
> fix: fix names generation in `Generate function`

- crates/ide/src/goto_definition.rs
Implement #10070 in  [`goto_definition`](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/ide/src/goto_definition.rs)
> fix: make `goto_definition` multi-token mapping aware

- crates/parser/src/grammar/generic_args.rs
- crates/syntax/test_data/parser/err/0049_double_fish.rast
> fix: don't allow two turbo-fishes in generic arguments

- Cargo.lock
- crates/hir_expand/src/db.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tests.rs
- crates/syntax/Cargo.toml
- crates/syntax/src/lib.rs
- crates/syntax/src/syntax_node.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10246
cc https://github.com/rust-analyzer/rowan/pull/114, follow up to https://github.com/rust-analyzer/rust-analyzer/pull/10025
> fix: Only strip derive attributes when preparing macro input

- crates/hir_expand/src/builtin_macro.rs
- crates/mbe/src/syntax_bridge.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8158
> fix: Don't bail on parse errors in macro input for builtin expansion

- crates/ide_assists/src/handlers/add_missing_match_arms.rs
- crates/ide_assists/src/handlers/add_return_type.rs
- crates/ide_assists/src/handlers/introduce_named_generic.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
Trying to make our assist names a bit more uniform
`fill_match_arms` -> `add_missing_match_arms`
`infer_function_return_type` -> `add_return_type`
`replace_impl_trait_with_generic` -> `introduce_named_generic`
bors r+
> minor: Rename some assists

- crates/hir/src/semantics.rs
- crates/hir_def/src/attr.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
- crates/syntax/src/tests/sourcegen_ast.rs
Generate a `DynTrait` node per ast trait that implements the trait itself as well as conversions via the `AstNode` trait. This is a trick already employed in `hir_def::attr` with `AttrsOwner` where it was manually implemented for.
This basically gives us stack trait objects for these(only useful for `hir_def::attr` currently) as well as simple conversions of `SyntaxNode` to a trait, in cases where only a result of a function call of such a trait is of interest.
It doesn't have many uses yet but as its autogenerated it doesn't add any maintenance costs. 
bors r+
> internal: Generate ast nodes for each ast trait

- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide/src/lib.rs
- crates/ide_db/src/defs.rs
This is part of #10181 but since it is blocked and `hover.rs` is moving quickly so will cause conflicts, I submitted this PR.
This PR extract some parts of `hover` to `find_definition` (maybe this need to be moved to some other file?) and `hover_for_definition`, with those functions I will be able to calculate definition of every token, and calculate hover (and probably other queries) for each definition only once.
> internal: definition based hover functions

- .gitattributes
When doing a git grep (of rust-analyzer or of rust-lang/rust with
--recurse-submodules), if the grep happens to match within the large
benchmark data files, the resulting long single lines can cause a text
pager or editor to slow down and distract from more useful matches.
These test data files aren't formatted for human consumption, so mark
them as binary, which causes git grep to instead just state that they
match without printing the matching "line".
> Mark large benchmark data files as binary to filter greps

- docs/user/manual.adoc
Asciidoc uses the first line of a doc as the title, so you can't put
comments before the heading.
---
I had an old copy of the Manual page open and I noticed that the "User Manual" heading (and page title) had disappeared in the live version:
With this change (and how it was a few days ago):
> Fix title of User Manual page

- Cargo.lock
- crates/hir_def/src/attr.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/ide_db/Cargo.toml
- crates/ide_db/src/defs.rs
- crates/syntax/src/ast/node_ext.rs
> internal: Cleanup hover a bit

- crates/hir_def/src/attr.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/hover.rs
- crates/mbe/src/syntax_bridge.rs
cc https://github.com/rust-analyzer/rust-analyzer/issues/10271
> feat: Hover/GotoDef works in macro invocations and on doc attribute strings

- editors/code/src/commands.ts
> fix: Change the global setting when toggling inlay hints

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
https://github.com/rust-analyzer/rust-analyzer.github.io/pull/147#issuecomment-926600543
> Fix link to "Auto Import"

- crates/rust-analyzer/src/bin/main.rs
Trying to figure out why we aren't getting backtraces for windows builds from CI, this let's one set the backtraces to `FULL`
Might be cc https://github.com/rust-lang/rust/issues/87481
bors r+
> minor: Allow overwriting RUST_BACKTRACE for the server manually

- crates/ide_diagnostics/src/handlers/missing_fields.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
Most commonly a field of a struct can be initialized with its default value than an empty tuple.
> RfC: Use `todo!()` instead of `()` for missing fields

- crates/rust-analyzer/src/handlers.rs
This mean if you misconfigure to
```json
{
"rust-analyzer.rustfmt.overrideCommand": [
"./nonono"
]
}
```
The error message is
```
[Error - 17:54:33] Request textDocument/formatting failed.
Message: Failed to spawn "./nonono"
Code: -32603 
```
instead of
```
[Error - 17:56:12] Request textDocument/formatting failed.
Message: No such file or directory (os error 2)
Code: -32603 
```
I'm not sure how to test this, or if it needs a test.
> Give rustfmt spawn error context.

- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/ide_diagnostics/src/handlers/macro_error.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8459
bors r+
> fix: Fix item-level macro errors (eg. `compile_error!`)

- crates/parser/src/grammar/expressions.rs
> minor: link my own pratt parsing article :-)

- crates/syntax/src/validation.rs
> minor: align code with code-style

- crates/ide_assists/src/assist_context.rs
- crates/ide_assists/src/handlers/move_to_mod_rs.rs
- crates/ide_assists/src/handlers/promote_mod_file.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests.rs
- crates/ide_assists/src/tests/generated.rs
Close part of #10143.
This PR adds a assist to promote module to directory, which means make a .rs file module into a directory style module with the same name.
> assists: Promote module to folder

- crates/syntax/src/lib.rs
- crates/syntax/src/syntax_node.rs
- crates/syntax/src/validation.rs
Originally we tried to maintain the invariant that `{}` always match.
That is, that in the parse tree the pair of corresponding `{}` is always
first and last tokens of some nodes.
We had the code to validate that, but apparently it's been broken for
**years** since we introduced tokens/nodes split. Fixing it now makes
some tests fail.
It's unclear if we want to keep this invariant: there's a strong
motivation for breaking it in the following case:
```
use std::{ // unclosed paren
fn main() {
}
} // don't actually want to pair up this with the one from `use`
```
So let's fix the code, but disable it for the time being
bors r+
🤖
> internal: fix and force-disable block validation ;-(

- crates/base_db/src/fixture.rs
- crates/ide_assists/src/handlers/inline_call.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/search.rs
> feat: Implement inline callers assist

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> feat: Enable attribute proc macros by default

- crates/hir_expand/src/builtin_macro.rs
- crates/hir_expand/src/lib.rs
- crates/proc_macro_srv/src/abis/abi_1_47/rustc_server.rs
- crates/proc_macro_srv/src/abis/abi_1_55/rustc_server.rs
- crates/proc_macro_srv/src/abis/abi_1_56/rustc_server.rs
- crates/tt/src/lib.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10365
Unlike rustc, we don't insert newlines, but that should be fine.
bors r+
> fix: Make `stringify!` insert/collapse whitespace when needed

- crates/proc_macro_srv/src/abis/abi_1_56/rustc_server.rs
This closes https://github.com/rust-analyzer/rust-analyzer/issues/10368 – some APIs are still missing, but they are either for unstable features or require https://github.com/rust-analyzer/rust-analyzer/issues/9403
bors r+
> fix: Implement most proc_macro span handling methods

- crates/ide_assists/src/handlers/move_from_mod_rs.rs
- crates/ide_assists/src/handlers/move_to_mod_rs.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_assists/src/utils.rs
- crates/vfs/src/vfs_path.rs
This is the reverse operation of #10211.
Close #10143.
> feat: Convert a/mod.rs into a.rs

- crates/hir/src/lib.rs
- crates/ide_completion/src/completions/dot.rs
> fix: `into_iterator` not completed on `Vec<{unknown}>`

- crates/base_db/src/fixture.rs
- crates/base_db/src/input.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/path_resolution.rs
- crates/hir_def/src/nameres/tests.rs
- crates/project_model/src/project_json.rs
- crates/project_model/src/sysroot.rs
- crates/project_model/src/tests.rs
- crates/project_model/src/workspace.rs
- crates/test_utils/src/fixture.rs
This implements support for dependencies that are not added to the extern prelude of a crate, and add the `test` crate from the sysroot as such a dependency.
This does mean we now index `test` on startup, but I didn't notice much of a difference (and also, r-a can be used while it is still indexing).
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6714
bors r+
> Make `extern crate test;` work

- editors/code/src/main.ts
This PR copy onEnterRules configurations [from vscode-rust](https://github.com/rust-lang/vscode-rust/blob/master/src/extension.ts#L287) based on discussion in #6254 
I understand that the ideal way is to use parser data for this, and probably all other things that language-config do. But since it can't be enabled (or at least it isn't enabled) by default in vscode, I think this is needed (until onEnter becomes official LSP and get vscode support).
People can still configure shortcut and use the parser based onEnter, so it wouldn't harm anyone.
> feat: Add vscode native onEnterRules

- crates/hir_def/src/generics.rs
- crates/hir_ty/src/tests/regression.rs
> fix: use the right `HirFileId` when expanding macros in fn parameters

- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/tests/item.rs
- crates/ide_completion/src/tests/item_list.rs
- crates/ide_completion/src/tests/type_pos.rs
I've gotten used to typing `pc` in front of items to get `pub(crate)`, but recently I needed `pub(super)`. So I tried typing `ps` and it didn't work. Now it should!
> Add pub(super) along with pub(crate) and pub as a completion keyword

- crates/hir/src/lib.rs
This fixes #10396 panic introduced in #10373
> minor: don't drop binders when doing autoderef

- crates/ide_assists/src/utils.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10393
bors r+
> minor: Test runnables check for test prefix and suffix in attributes only

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
- crates/ide/src/syntax_highlighting/test_data/highlight_default_library.html
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/ide_db/src/helpers/famous_defs.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
Fixes #8999, fixes #2155
`builtInCrates` could be an alternate name to `defaultLibrary`, which one is better?
> P.S. I'm participating in [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/). If this PR is up to standard and merged, I'd appreciate if the `hacktoberfest-accepted` label could be added. Thanks!
> Give defaultLibrary semantic token modifier to items from standard library

- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/patterns.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10367
bors r+
> fix: Don't show flyimport completions in use renames

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/inject.rs
- crates/ide/src/syntax_highlighting/injector.rs
Gets rid of all the unseemly unwraps 
bors r+
> internal: Restructure syntax element highlighting into node and token branches

- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_crate_root.html
- crates/ide/src/syntax_highlighting/test_data/highlight_default_library.html
- crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/rust-analyzer/src/semantic_tokens.rs
- crates/rust-analyzer/src/to_proto.rs
Resolves #9073
I managed to implement crate root highlighting for crates mentioned specifically by name (e.g. `serde` in `use serde::Serialize;`), but not for crates referred to with `crate` or `super`. How could I implement this?
> P.S. I'm participating in [Hacktoberfest 2021](https://hacktoberfest.digitalocean.com/). If this PR is up to standard and merged, I'd appreciate if the `hacktoberfest-accepted` label could be added. Thanks!
> feat: Add semantic token modifier for crate root

- crates/hir_def/src/nameres/collector.rs
> internal: Add some profiling calls to name resolution

- crates/ide/src/typing/on_enter.rs
I found myself search for this, so building off of #3013 and #3308, I
hope this note is useful.
> docs: add note about `vscode-vim` in `on_enter`

- crates/ide/src/expand_macro.rs
Before, we were only adding whitespace between a lifetime and the following ident, which produced invalid code for mutable references.
Before this PR:
```rust
macro_rules! foo {
() => {
pub struct Foo<'a> {
foo: &'a mut str,
}
};
}
foo!(); // <- expand macro here
```
expanded to
```rust
pub struct Foo< 'a>{
foo: & 'amut str,
}
```
with this PR, it expands to
```rust
pub struct Foo< 'a>{
foo: & 'a mut str,
}
```
> Add whitespace between lifetime and mut keyword in "expand macro" command

- crates/ide/src/highlight_related.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/ide_assists/src/handlers/extract_function.rs
- crates/ide_db/src/search.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/to_proto.rs
> internal: use naming that matches intended use-case

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/main.ts
> minor: Bump npm non-dev deps

- crates/ide_assists/src/handlers/extract_variable.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6866
bors r+
> fix: Fix extract_variable not allowing to extract macro calls

- crates/ide_assists/src/handlers/extract_function.rs
- crates/syntax/src/ast/make.rs
> fix: await insertion with try_expr during extract_function

- crates/ide/src/inlay_hints.rs
- crates/test_utils/src/minicore.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/3022
bors r+
> feat: Hide type inlay hints for constructors

- editors/code/package.json
...and add `rust-project.json`.
More or less fixes #7268
> fix: Limit depth to 1 when searching for `Cargo.toml`

- crates/project_model/src/sysroot.rs
This changed in 1.47 (about a year ago), so it should be pretty safe to remove.
bors r+
> internal: remove support for pre-1.47 sysroots

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/utils.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10386
(the salsa bug persists, but this lets us avoid it by fixing the underlying bug)
This reimplements the rustc logic in https://github.com/rust-lang/rust/blob/b27661eb33c74cb514dba059b47d86b6582ac1c2/compiler/rustc_typeck/src/collect.rs#L556: When resolving an associated type `T::Item`, we've previously lowered all predicates that could affect `T`, but we actually have to look only at those predicates whose traits define an associated type of the right name.
> fix: Avoid cycle when lowering predicates for associated item lookup

- crates/project_model/src/workspace.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10455
bors r+
> fix: Only add `proc_macro` to prelude in proc-macro crates

- Cargo.lock
- crates/ide/src/lib.rs
- crates/ide_completion/Cargo.toml
- crates/ide_completion/src/completions/postfix.rs
- crates/ide_completion/src/completions/snippet.rs
- crates/ide_completion/src/config.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/enum_variant.rs
- crates/ide_completion/src/render/function.rs
- crates/ide_completion/src/render/macro_.rs
- crates/ide_completion/src/snippet.rs
- crates/ide_completion/src/tests.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/dev/lsp-extensions.md
- docs/user/generated_config.adoc
- editors/code/package.json
Allows us to address the following issues:
- `.arc / .rc / .pin, similar to .box?` https://github.com/rust-analyzer/rust-analyzer/issues/7033
- `Add unsafe snippet` https://github.com/rust-analyzer/rust-analyzer/issues/10392, would allow users to have this without the diagnostic)
- `.ok() postfix snippet is annoying` https://github.com/rust-analyzer/rust-analyzer/issues/9636, allows us to get rid of the `ok` postfix and similar ones
- `Postfix vec completion` https://github.com/rust-analyzer/rust-analyzer/issues/7773
cc https://github.com/rust-analyzer/rust-analyzer/issues/772
Zulipd discussion: https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Custom.20Postfix.20snippets
> feat: Implement custom user snippets

- crates/hir_def/src/body/lower.rs
- crates/parser/src/grammar/patterns.rs
- crates/syntax/Cargo.toml
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/test_data/parser/inline/ok/0008_path_part.rast
- crates/syntax/test_data/parser/inline/ok/0102_record_pat_field_list.rast
- crates/syntax/test_data/parser/inline/ok/0102_record_pat_field_list.rs
Try to fix https://github.com/rust-analyzer/rust-analyzer/issues/8610  
Related pr in ungrammer: https://github.com/rust-analyzer/ungrammar/pull/41
> Parse outer attributes on StructPatternEtCetera

- .github/workflows/release.yaml
For `-gnu` triples, use 20.04, the current LTS. This upgrades the
required version of glibc. For musl, just use `latest` as, presumably,
we don't care about glibc version in that case.
Hopefully, this unbreaks nightly publishing!
bors r+
🤖
> feat: upgrade ubuntu builders

- xtask/src/install.rs
Arguably it’s nicer to just use `.into_iter()` instead of iterating over references which are immediately dereferenced.
I also changed the use of `String::from` to `.to_string()` because the latter has around twenty times more usages in rust-analyzer.
> minor: Use `.into_iter()` method on array to avoid dereference

- crates/rust-analyzer/src/global_state.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/reload.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10027
It feels wrong using the database in this part of the code, but this was the only way to figure out whether a file belongs to a proc-macro that I could think of.
> internal: Set server status to warning when proc-macro sources change

- crates/proc_macro_srv/src/abis/abi_1_55/rustc_server.rs
- crates/proc_macro_srv/src/abis/abi_1_56/rustc_server.rs
this apparently fixes RTIC 0.6's 
```rust
#[rtic::app]
mod app {}
```
> implement Literal::from_str

- crates/hir/src/semantics.rs
- crates/hir_expand/src/lib.rs
- crates/ide_assists/src/handlers/auto_import.rs
- crates/ide_assists/src/handlers/extract_function.rs
- crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
- crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ide_assists/src/tests.rs
- crates/ide_completion/src/completions/attribute/derive.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/completions/postfix.rs
- crates/ide_completion/src/completions/snippet.rs
- crates/ide_completion/src/lib.rs
- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
Fixes trying to insert imports into macro expanded files which then do text edits on very wrong text ranges.
> internal: Add `Semantics::original_ast_node` for upmapping nodes out of macro files

- crates/hir/src/semantics.rs
- crates/hir_expand/src/lib.rs
There is no need to descend everything if all we are interested in is the first mapping.
This bring `descend_into_macros` timing in highlighting in `rust-analyzer/src/config.rs` from `154ms - descend_into_macros (2190 calls)` to `24ms - descend_into_macros (2190 calls)` since we use the single variant there(will regress once we want to highlight multiple namespaces again though).
bors r+
> internal: Short-circuit `descend_into_macros_single`

- Cargo.lock
- crates/cfg/src/lib.rs
- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/completions/attribute/cfg.rs
- crates/ide_completion/src/completions/attribute/derive.rs
- crates/ide_completion/src/completions/fn_param.rs
- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/completions/trait_impl.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/const_.rs
- crates/ide_completion/src/render/function.rs
- crates/ide_completion/src/render/macro_.rs
- crates/ide_completion/src/render/pattern.rs
- crates/ide_completion/src/render/struct_literal.rs
- crates/ide_completion/src/render/type_alias.rs
- crates/syntax/Cargo.toml
This replaces a bunch of String clones with SmolStr clones, though also makes a few parts a bit more expensive(mainly things involving `format!`ted strings as labels).
> internal: Make CompletionItem `label` and `lookup` fields `SmolStr`s

- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render/pattern.rs
- crates/ide_completion/src/tests/pattern.rs
> fix: Don't ascribe types in pattern completion for param patterns twice

- .github/workflows/ci.yaml
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/tsconfig.json
We don't follow it and I found that turning it on will have little benefit.
I'm not sure if we should also type-check when building in launch.json.
> internal: Type-check TS on CI and also turn off the strict setting `useUnknownInCatchVariables`

- crates/rust-analyzer/src/main_loop.rs
Currenty r.a. only shows this:
even if another command was specified
There might be a better way to do this, I tried.
> fix: show the right check-command

- crates/parser/src/grammar.rs
- crates/parser/src/grammar/items.rs
- crates/parser/src/grammar/items/adt.rs
- crates/syntax/test_data/parser/inline/ok/0196_pub_tuple_field.rast
- crates/syntax/test_data/parser/inline/ok/0196_pub_tuple_field.rs
The current implementation will throw a parser error for tuple structs
that contain a pub tuple field. For example,
```rust
struct Foo(pub (u32, u32));
```
is valid Rust, but rust-analyzer will throw a parser error.  This is
because the parens after `pub` is treated as a visibility context.
Allowing a tuple type to follow `pub` in the special case when we are
defining fields in a tuple struct can fix the issue.
I guess this is a really minor case because there's not much reason
for having a tuple type within a struct tuple, but it is valid rust syntax...
> Handle pub tuple fields in tuple structs

- crates/hir_expand/src/lib.rs
- crates/ide/src/runnables.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10744
- This logic is currently not required as we do not expand test/bench anymore for the time being
- The implementation of this was flawed to begin with as it just skipped out of macro expansions instead of ascending the trees inside expansions
bors r+
> fix: Remove faulty logic for ascending test attributes for runnables

- docs/dev/lsp-extensions.md
`bool` is Rust, whereas `boolean` is the type name in TypeScript.
> Fix type names in typescript sample code

- crates/flycheck/src/lib.rs
Cargo will always output something on success:
```
$ cargo check --message-format=json
{"reason":"compiler-artifact", ... snipped ... }
{"reason":"build-finished","success":true}
```
However, rustc does not output anything on success:
```
$ rustc --error-format=json main.rs
$ echo $?
0
```
Restore the behaviour prior to #10517, where an exit code of 0 is
considered good even if nothing is written to stdout.
This enables custom overrideCommand values that use rustc rather than
cargo.
> Allow the check command to terminate without output

- docs/user/manual.adoc
Mention the dev-util/rust-analyzer package for building from source.
> minor: Update docs: include Gentoo source build

- crates/ide/src/inlay_hints.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
- editors/code/src/config.ts
This PR adds a config to *disable* the functionality in #10441 - _and makes that functionality disabled by default._
I actually *really* like inlay hints always showing up, and it helps a lot as a teaching tool too, and also it's quite reassuring to know that r-a indeed understands the code I've written. This PR adds the option `rust-analyzer.inlayHints.hideNamedConstructorHints` (i can also invert this to be `rust-analyzer.inlayHints.showNamedConstructorHints`, just let me know.)
> inlay hints: add the option to always show constructor inlay hints

- crates/ide_assists/src/handlers/add_missing_match_arms.rs
> internal: make `add_missing_match_arms` applicable at the end of the match

- crates/hir/src/db.rs
- crates/hir/src/semantics.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_derive_macro.rs
- crates/hir_expand/src/builtin_fn_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/eager.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/ide_db/src/apply_change.rs
We potentially want to intern macro definitions so the names would probably collide
bors r+
> minor: Rename intern_macro -> intern_macro_call

- crates/hir_expand/src/lib.rs
- crates/ide/src/runnables.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10768
bors r+
> fix: Reimplement mapping out of test/bench attributes for runnables

- crates/proc_macro_srv/src/abis/abi_1_58/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/buffer.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/client.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/closure.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/handle.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/rpc.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/scoped_cell.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/bridge/server.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/diagnostic.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_58/proc_macro/quote.rs
- crates/proc_macro_srv/src/abis/abi_1_58/rustc_server.rs
- crates/proc_macro_srv/src/abis/mod.rs
This fixes #10766.
I do have some concerns here. The proc macro server API has added three methods to `TokenStream` which I don't really know how to implement in `RustcServer`. Namely `expand_expr`, `before`, and `after`. You'll see that these are currently `unimplemented!` in `crates/proc_macro_server/src/abis/abi_1_58/rustc_server.rs`. I don't have the expertise to fill in the blanks here, it may be necessary to pull in someone who knows a bit more about the proc macro crate.
I think this will only be a problem when actually attempting to expand a macro, so this is probably strictly better than not including the updated ABI at all.
> Add proc macro ABI for rustc 1.58

- crates/hir_def/src/builtin_attr.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_attr_macro.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/runnables.rs
This way we skip any path resolving to the test and bench attributes instead of just the lone identifiers(which could very well point to non-builtin attributes).
bors r+
> internal: Skip test/bench attr expansion in resolution instead of collection

- crates/hir_def/src/body/scope.rs
`scopes.set_scope(*expr, scope)` is duplicate, because we always call it in `compute_expr_scopes`  https://github.com/rust-analyzer/rust-analyzer/blob/add6cccd4c923fbb5c83cc27b06aa84b2cbc9557/crates/hir_def/src/body/scope.rs#L175-L180
> minor: remove duplicate calls

- crates/hir_def/src/attr.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/macro_expansion_tests/builtin_derive_macro.rs
- crates/hir_def/src/macro_expansion_tests/proc_macros.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/hir_expand/src/builtin_attr_macro.rs
- crates/hir_ty/src/tests/macros.rs
- crates/ide/src/expand_macro.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
Prior we only checked if an attribute is the exact `derive` identifier and nothing else to collect derive attributes. That means when we encounter the following:
```rs
#[::core::macros::builtin::derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ModPath {
pub kind: PathKind,
segments: Vec<Name>,
}
```
We won't actually expand the derive attributes, but instead we just expand the `derive` attribute with our dummy identity expander.
The changes here make it so we actually lookup the attribute path, check if it is the derive attribute and then collect the derives.
> internal: Check for derive attributes by item path, not `derive` identifier

- crates/proc_macro_srv/src/abis/mod.rs
If I'm reading this right, we used to pick `Abi1_55` for `1.54` and `Abi_1_58` for `1.57`.
CC @alexjg (just in case I'm misinterpreting the code), CC #10772.
bors r+
> fix: Fix proc macro ABI version checks

- crates/hir/src/attrs.rs
I keep hitting this constantly in my project, and I haven't dug very deep into the root cause. But seeing as the project otherwise compiles it appears to be something unsupported is being incorrectly parsed in rust-analyzer which for other cases is handled by returning `None`.
> Remove unwrap in doc path resolution

- crates/hir/src/lib.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
Continuation from #10785 - does the same thing, but for `static`'s as well.
> ide: display static values in hover

- crates/ide/src/hover.rs
- crates/ide/src/hover/tests.rs
I've found myself wanting this...  adds to the hover quick go-to for a function's return type:
This is particularly useful when you are hovering over a function in a long chain, like:
```rust
foo.bar().b$0az().some_trait_fn();
```
where `baz`'s return type is not immediately obvious, but the chain is not long enough to trigger chain inlay hints... 
i guess I could just select `foo.bar().baz()` too to get the types too...
> ide: show go to for function hover return type

- crates/ide/src/inlay_hints.rs
> fix: inlay param hint hiding heurstic is case unsensitive

- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/diagnostics.rs
- crates/ide_diagnostics/src/handlers/invalid_derive_target.rs
- crates/ide_diagnostics/src/handlers/malformed_derive.rs
- crates/ide_diagnostics/src/lib.rs
Doesn't yet diagnose incorrect syntax between the `(`, `)` braces as we discard those problems currently.
bors r+
> fix: Diagnose invalid derive attribute input

- crates/rust-analyzer/src/main_loop.rs
just realized this is a lot cleaner and actually shows something on a custom command,
also debugged it this time.
> fix: show custom check-command

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Even if it doesn't prevent the rest of the features from working, cache priming tends to be quite CPU-intensive and can make people think that the load times are worse than they actually are.
It's also less useful in Code and `rust-tools` because the inlay hints and semantic highlighting trigger quite a bit of computation assuming you have a file open in the editor.
> feat: Add toggle to disable cache priming

- crates/hir_ty/src/display.rs
This makes it so formatting `Fn` traits properly handles:
1. An `Fn` trait with only a single argument -> removes the trailing comma.
2. An `Fn` trait which returns nothing (an empty tuple) -> don't show `-> ()` as the return type.
before:
after:
> fix: better `Fn` traits formatting

- docs/dev/architecture.md
> doc: document absence of stability guarantees

- crates/ide_assists/src/handlers/merge_imports.rs
- crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
- crates/ide_assists/src/handlers/split_import.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
- crates/ide_db/src/helpers/merge_imports.rs
- crates/syntax/src/ast/edit.rs
- crates/syntax/src/ast/edit_in_place.rs
Use mutable syntax trees in `merge_imports`, `split_imports`. This tries to resolve #9013. But I haven't much managed to simplify code of merging.
Also resolve #9361. It reuses a use tree under the cursor so that comments+indentation are preserved. Merged trees are just appended to the end.
This touches bunch of tests. I removed the sorting of use trees as it needs a proper implementation that takes into account comments and line wrapping. I think it is rustfmt's job or at least until we get a close implementation.
> fix: don't discard formatting of `use` lines

- crates/hir_def/src/macro_expansion_tests/mbe.rs
- crates/hir_expand/src/lib.rs
- crates/mbe/src/lib.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9371
bors r+
> fix: Fix mbe::Shift::new not accounting for non-ident token ids

- crates/ide_db/src/helpers.rs
- crates/ide_db/src/helpers/generated_lints.rs
- crates/ide_db/src/tests/sourcegen_lints.rs
- crates/rust-analyzer/src/diagnostics/to_proto.rs
this change makes it possible to specify
```json
{
"rust-analyzer.diagnostics.warningsAsInfo": ["unused"],
}
```
to make all lints in the `unused` group show as info, etc.
> Make lint groups work correctly with `warningsAsInfo` and `warningsAsHint`

- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/completions/record.rs
- crates/ide_completion/src/render/struct_literal.rs
* Alter `add_struct_literal` method signature to take an optional module path
* Update `render_literal` method to use a qualified  
Relates to issue #10771 
Side note: This is my first contribution. Any feedback is welcome!
> fix: qualify struct name in struct constructor completion

- crates/project_model/src/cargo_workspace.rs
well, `Command` implements a sensible `Debug` which *roughly* does what we want to do. Unfortunately it's got a bit of a quote situation,
So it'd output something like `"cargo" "metadata"  "--format-version" "1" "--features" "foo,bar,baz"`. 
Which although is a bit verbose with the quotes, it's at the very least, not entirely incorrect/misleading.
fixes #10797
> project_model: print full cargo command if cargo metadata fails to run

- crates/hir_def/src/body/tests/block.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/7717
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8911
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8614
`ItemTree`s are now flat lists of items, so they should probably be renamed at some point.
> internal: build per-block `ItemTree`s

- crates/hir/src/source_analyzer.rs
- crates/ide/src/syntax_highlighting/test_data/highlighting.html
- crates/ide/src/syntax_highlighting/tests.rs
> hir: resolve assoc trait type in path

- .github/workflows/ci.yaml
- editors/code/package.json
It looks like `--noEmit` broke our unit tests:
r? @ChayimFriedman2
I suppose we might still:
- compile stuff twice
- not detect failing tests on CI (since we didn't notice this)
> internal: Try to fix Code tests

- crates/ide/src/syntax_highlighting/highlight.rs
fixes #10708 
this is a bit hacky, but it "works". 
i'm not sure how to even write a test for this though, but i've confirmed it works via manual testing...
> ide: hack to make self not unresolved reference in async trait wrapped impl's

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/tests/unit/index.ts
- editors/code/tests/unit/launch_config.test.ts
- editors/code/tests/unit/runnable_env.test.ts
> internal: Replace `mocha` with a custom test runner

- editors/code/.vscodeignore
- editors/code/LICENSE
Newer `vsce` versions error out if a `LICENSE` file is missing, even if the license is specified in `package.json`. Concatenate the two licenses we use and add a file with that to make a future `vsce` upgrade easier.
> minor: Add LICENSE file to make vsce happy

- crates/rust-analyzer/src/diagnostics.rs
- crates/rust-analyzer/src/diagnostics/test_data/clippy_pass_by_ref.txt
- crates/rust-analyzer/src/diagnostics/test_data/handles_macro_location.txt
- crates/rust-analyzer/src/diagnostics/test_data/macro_compiler_error.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_incompatible_type_for_trait.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_mismatched_type.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_hint.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_unused_variable_as_info.txt
- crates/rust-analyzer/src/diagnostics/test_data/rustc_wrong_number_of_parameters.txt
- crates/rust-analyzer/src/diagnostics/test_data/snap_multi_line_fix.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/main_loop.rs
Resolves https://github.com/rust-analyzer/rust-analyzer/issues/10705.
**Cause:**
- For a cargo check diagnostic with multiple spans, only a single quick fix action would be created at the location of `spans[0]`. Additionally, the hover window details would only show the location of `spans[0]` next to the message.
**Fix:**
- Allow cargo check quick fix actions to be triggerable from multiple selection ranges. Specifically, if the selection intersects with any of the replacement spans, the quick fix action is shown.
- No change in behavior for the hover window details. It's pretty minor and I think showing multiple locations next to the message may be more confusing anyways.
> Handle multiple cargo check quick fix spans

- crates/ide/src/syntax_highlighting/highlight.rs
cc https://github.com/rust-analyzer/rust-analyzer/issues/10935
bors r+
> fix: Add highlighting hack back for unresolved attributes

- crates/hir/src/attrs.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/import_map.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/item_tree/tests.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/resolver.rs
- crates/hir_ty/src/chalk_db.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/diagnostics/decl_check.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tls.rs
- crates/hir_ty/src/utils.rs
- crates/ide_db/src/symbol_index.rs
- crates/ide_diagnostics/src/handlers/incorrect_case.rs
- Removes knowledge of what's in an extern block from `ItemTree`.
- Treats extern blocks as `AssocContainerId` and renames the latter to `ItemContainerId`.
- Threads the container through name resolution (which is a bit messy).
- Considers statics to be associated items, since they can be in an extern block. (it might be better to further distinguish potentially-associated-items from potentially-in-an-extern-block-items, but currently I don't expect much of a benefit)
- Adds a test for the incorrect-case diagnostic demonstrating the impact of this change.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/8913
bors r+
> fix: fix handling of macros in `extern` blocks

- crates/hir_def/src/macro_expansion_tests/builtin_fn_macro.rs
- crates/hir_expand/src/builtin_fn_macro.rs
Adds another hack on top of https://github.com/rust-analyzer/rust-analyzer/pull/10623 to fix `concat!`.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10721
bors r+
> fix: fix `concat!` with captured expression

- crates/ide/src/prime_caches.rs
This reduces the number of primed crates on `self` from 177 to 105.
```text
86521 me   20   0 2939M  562M 14320 S  0.0  0.9  0:07.10   37 rust-analyzer
99947 me   20   0 2935M  549M 14424 S  0.0  0.9  0:07.10   37 rust-analyzer
```
The RAM usage seems to vary a lot, so I'm not sure the improvement shown above is real.
We also drop the topological sorting, although it might still make sense to do the dependencies before the workspace crates. But since it's only used to make the progress reporting a bit more fine, it probably doesn't matter too much.
> internal: Only prime direct dependencies of the workspace crates

- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/tests/flyimport.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_db/src/items_locator.rs
And raise the fuzzy trigger from 2 to 3 chars. This way we keep the ability of flyimporting short names like `Rc`.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6917
bors r+
> fix: Show case-insensitive exact matches instead of fuzzy flyimport for short paths

- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/tests/attribute.rs
- crates/ide_db/src/helpers.rs
Fixes #10682
Uses keywords and nested `TokenTree`s as a heuristic to figure out when to stop parsing in case the attribute is unclosed which should work pretty well as attributes are usually followed by either of those.
bors r+
> fix: Fix lint completions not working for unclosed attributes

- crates/ide/src/lib.rs
Unless I'm missing something, `assists_with_fixes` seems to be always used and ends up in the same code path.
> minor: Remove dead assists-related function

- crates/ide_assists/src/handlers/generate_documentation_template.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
Closes #10878, #1915 and #4767
Full description is in #10878, better read [the tests](https://github.com/rust-analyzer/rust-analyzer/pull/10951/files#diff-7a64e2efb66b2625443340fcbc96d531baff12c17cc0aaf51885ea94f67de254R424) to understand what this feature does.
Comments appreciated :smile:
> feat: assist to generate documentation templates

- crates/hir/src/semantics.rs
- crates/ide/src/expand_macro.rs
- crates/ide_assists/src/handlers/add_missing_impl_members.rs
- crates/ide_assists/src/handlers/convert_iter_for_each_to_for.rs
- crates/ide_assists/src/handlers/generate_is_empty_from_len.rs
- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_assists/src/utils.rs
- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_db/src/helpers.rs
- crates/ide_db/src/helpers/insert_whitespace_into_node.rs
- crates/ide_db/src/helpers/render_macro_node.rs
- crates/ide_ssr/src/resolving.rs
This is obviously only a temporary hack which still produces ugly looking items, but as long as the syntax is valid one can at least have rustfmt fix the formatting again. 
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/6588
bors r+
> fix: insert whitespaces into assoc items for assist when macro generated

- crates/ide_assists/src/handlers/number_representation.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
- crates/syntax/src/ast/token_ext.rs
Reimplemented assists from this PR https://github.com/rust-analyzer/rust-analyzer/pull/3683 with current APIs.
I've decided not to add options about size of the groups so behaviour is similar to clippy's. 
Minimal number length is also taken from clippy.
> Add number representation assists

- .github/workflows/release.yaml
The GHA image no longer contains XCode 12.2, let's use the default version for now.
bors r+
> internal: Use default XCode version

- .github/workflows/release.yaml
This reduces duplication by using `matrix` and paves the way for https://github.com/rust-analyzer/rust-analyzer/issues/10483. The `musl` builder is unchanged because it uses a container.
~~We also get rid of the MacOS 11 SDK thing, which is from when most MacOS builders were on 10.~~ Or not, the default is still 10.15.
> internal: Refactor release workflow to reduce duplication

- .github/workflows/release.yaml
Since GitHub (and also us, explicitly) switched the `macos-latest` runners to 11, let's try to bring back support for 10.15.
> minor: Set `MACOSX_DEPLOYMENT_TARGET` to 10.15 to improve compat

- crates/ide_assists/src/handlers/move_guard.rs
As I mentioned in #11017, there is a little issue in the implementation for if branch. This code
```rust
let y = match 92 {
x => {
if x == 0 {$0
false
}
}
_ => true,
};
```
will be transformed to
```rust
let y = match 92 {
x if x == 0 => false
_ => true,
};
```
a comma is missing after the false. I moved the fix from the code handling else branch to above.
> Add comma for "move if to guard"

- crates/hir_def/src/data.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/ide_diagnostics/src/handlers/mismatched_arg_count.rs
Adds basic support for `#[rustc_legacy_const_generics]`.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10009
Full support would involve actually checking call arguments against the right expected types.
bors r+
> fix: fix incorrect mismatched argument count diagnostic with `std::arch` functions

- .github/workflows/release.yaml
- editors/code/.gitignore
- editors/code/src/main.ts
- xtask/src/dist.rs
Closes #10483
CC #10371
Some notes:
- we still build a plain VSIX, just in case
- we build the extension on every platform to make the release workflow arguably cleaner
- the Windows VSIX includes the PDB (but let's leave  #10371 open until we change the Windows stand-alone release to a ZIP file)
- `npm` doesn't run if started from `xtask`, possibly something related to path mapping; I moved the `npm` calls outside, but..
- the `Patch` thingy doesn't work any more, so you'll end up with a dirty `package.json` of you run `cargo xtask --client-patch-version`; I don't think we should block on this
- there's an untested Alpine build; for better or worse, we publish `musl` builds as `alpine`
- I tested this as much as I could, but not the publishing and nightly updates
- you can find some …
> feat: Publish platform-specific Code VSIXes

- crates/ide_assists/src/handlers/generate_getter.rs
- crates/ide_assists/src/utils.rs
This changes the generate getter assist to not say "a reference to" in the documentation stub if the type is `Copy`, as the getter does not return a reference.
To determine whether the type is `Copy`, I have added an `is_copy` method to `ReferenceConversion`.
> fix: Don't say "a reference to" for `Copy` types in the generate getter assist

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/item_tree/tests.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/lower.rs
- crates/ide_completion/src/render/builder_ext.rs
- crates/ide_completion/src/render/function.rs
This prevents us reparsing source files for completions, sometimes slowing them down massively if the source file is not cached at the expense of a slightly bigger memory usage.
related info https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Completion.20performance
> internal: Store function param names in ItemTree

- crates/hir_ty/src/traits.rs
> Bump default CHALK_SOLVER_MAX_SIZE to 150

- .github/workflows/release.yaml
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/ast_inspector.ts
- editors/code/src/lsp_ext.ts
> feat: Build and publish pre-release Code extension versions

- xtask/src/dist.rs
bors r+
The Marketplace doesn't allow us to publish extensions using these, even as pre-release versions.
> internal: Disable unstable APIs for nightly releases

- xtask/src/dist.rs
Otherwise the Marketplace shows `(nightly)` for the stable version.
bors r+
> Code: Use the same `displayName` for pre-release versions

- .github/actions/github-release/main.js
- .github/actions/github-release/package.json
- .github/workflows/ci.yaml
- .github/workflows/metrics.yaml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
Upgrade `@actions/github` to get `listReleaseAssets` and retry individual uploads in addition to the whole thing.
Also disables `ci`, `metrics` and `rustdoc` on forks to save some CPU time.
CC #11056
> internal: Improve GitHub release action

- crates/hir/src/lib.rs
- crates/hir_ty/src/consteval.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/hover/tests.rs
> show values of constants in hover

- crates/mbe/src/lib.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/to_parser_input.rs
- crates/mbe/src/tt_iter.rs
- crates/parser/src/event.rs
- crates/parser/src/input.rs
- crates/parser/src/lexed_str.rs
- crates/parser/src/lib.rs
- crates/parser/src/output.rs
- crates/parser/src/parser.rs
- crates/parser/src/tree_traversal.rs
- crates/syntax/src/parsing.rs
- crates/syntax/src/parsing/reparsing.rs
- crates/syntax/src/parsing/text_tree_sink.rs
- crates/syntax/src/syntax_node.rs
The general theme of this is to make parser a better independent
library.
The specific thing we do here is replacing callback based TreeSink with
a data structure. That is, rather than calling user-provided tree
construction methods, the parser now spits out a very bare-bones tree,
effectively a log of a DFS traversal.
This makes the parser usable without any *specifc* tree sink, and allows
us to, eg, move tests into this crate.
Now, it's also true that this is a distinction without a difference, as
the old and the new interface are equivalent in expressiveness. Still,
this new thing seems somewhat simpler. But yeah, I admit I don't have a
suuper strong motivation here, just a hunch that this is better.
cc #10765
> internal: replace TreeSink with a data structure 

- editors/code/README.md
See https://github.com/rust-analyzer/rust-analyzer.github.io/pull/156 and https://github.com/rust-analyzer/rust-analyzer/pull/8237
> Remove note about alpha status from vscode extension descritpion

- crates/hir_expand/src/ast_id_map.rs
- crates/ide_db/src/test_data/test_symbol_index_collection.txt
- crates/syntax/src/ptr.rs
Since https://github.com/rust-analyzer/rowan/pull/122 was merged into rowan, this could be how rust-analyzer migrates.
> minor: Migrate to new rowan

- crates/ide_assists/src/handlers/add_turbo_fish.rs
This fixes #11135 (changelog: bug).
I've only started using Rust a few days ago but saw this issue on the top of the list when I looked at this repo. I based myself on [this blog post](https://techblog.tonsser.com/posts/what-is-rusts-turbofish) to understand what a "turbo fish" is so let me know if I missed anything.
> Turbo fish assist supports multiple type arguments

- crates/mbe/src/syntax_bridge.rs
- crates/stdx/src/lib.rs
- crates/stdx/src/non_empty_vec.rs
There are some places in the ide crates where this can be used as well if memory serves right.
bors r+
> internal: Use basic `NonEmptyVec` in mbe::syntax_bridge

- crates/ide_assists/src/handlers/add_turbo_fish.rs
- crates/ide_assists/src/handlers/destructure_tuple_binding.rs
- crates/ide_assists/src/handlers/extract_module.rs
- crates/ide_assists/src/handlers/generate_function.rs
- crates/rust-analyzer/src/handlers.rs
- avoid `fold` with a `Vec` seed which could have been a `for_each`
- we can't drop the dependency, but avoid `Itertools::collect_vec`
bors r+
> minor: style nits

- crates/hir_ty/src/display.rs
- crates/ide_assists/src/handlers/add_explicit_type.rs
Sometimes when writing something like `let foo = Arc::new(Mutex::new(CrazyGenerics::new(HashMap::new())))`, I want/have to specify an explicit type for the expression.
Using turbofish isn't very readable and not always appreciated by guidelines, so `let foo: T` has to be filled.
To ease that, the PR enables the `add_explicit_type` assist on types that contain unknown types and some generics.
Fully unresolved types, arrays with unknown types and other known cases behave the same.
`_` placeholder was chosen to replace an unknown type:
```rust
let foo = HashMap::new();
// after assist usage, turns into
let foo: HashMap<_, _> = HashMap::new();
```
> Allow adding partially resolved types

- crates/ide_assists/src/handlers/replace_if_let_with_match.rs
If the assist encounters an unsafe block in one of the match arms, the assist generated intermediate code like the following:
```rust
if let Foo(_) = foo {
<then branch>
} else unsafe { ... }
```
Which was then parsed back and the unsafe branch got completely removed, removing in invalid code output:
```rust
if let Foo(_) = foo {
<then branch>
} else
```
This PR fixes this issue.
However, I'm sure there is a better, more general solution here, but I lack familiarity with rust-analyzer. `make::expr_if` looks like it expects a `BlockExpr` that, when printed, is wrapped in braces correctly, but I'm sure changing the display impl for an `unsafe` `BlockExpr` would have caused problems. I could have changed `make::expr_if` instead to special case unsafe blocks, but that would have meant some …
> Fix replace_match_with_if_let removing unsafe blocks

- crates/hir_def/src/macro_expansion_tests/mbe/matching.rs
This test kills the following mutant:
diff --git a/crates/mbe/src/tt_iter.rs b/crates/mbe/src/tt_iter.rs
index 9d2b1da9a..055d9a733 100644
--- a/crates/mbe/src/tt_iter.rs
+++ b/crates/mbe/src/tt_iter.rs
@@ -134,7 +134,7 @@ impl<'a> TtIter<'a> {
self.inner = self.inner.as_slice()[res.len()..].iter();
let res = match res.len() {
1 => Some(res[0].cloned()),
-            0 => None,
+            // 0 => None,
_ => Some(tt::TokenTree::Subtree(tt::Subtree {
delimiter: None,
token_trees: res.into_iter().map(|it| it.cloned()).collect(),
bors r+
🤖
> minor: add missing test

- crates/ide_assists/src/handlers/move_guard.rs
- crates/ide_assists/src/tests/generated.rs
The idea is to first parse the if else chain into a vector of `(Condition, BlockExpr)`s until we reach an iflet branch, an else branch, or the end (the tail). Then add the match arms with guard for the vector, and add the tail with no if guard.
Because the whole original match arm is replaced and the generated code doesn't have redundent commas, I removed redundent commas in some test cases.
Closes #11033.
> Support "move if to guard" for if else chains

- crates/ide_assists/src/handlers/extract_function.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10277
I have based this investigation based on my understanding of [the Borrowing chapter](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html) but I wasn't able to debug the test runs or see it in action in an IDE. I'll try to figure out how to do that for future PRs but for now, the tests seem to confirm my understanding. I'll lay out my hypothesis below.
Here we define the parameters for the to-be-generated function: 
https://github.com/rust-analyzer/rust-analyzer/blob/7409880a07803c34590ad162d7854061145c6eae/crates/ide_assists/src/handlers/extract_function.rs#L882
Three values in particular are important here: `requires_mut`, `is_copy` and `move_local`. These will in turn be used here to determine the kind of …
> Correctly pass through mutable parameter references when extracting a function

- crates/hir/src/lib.rs
- crates/hir_ty/src/consteval.rs
- crates/hir_ty/src/infer/expr.rs
- crates/ide/src/hover/tests.rs
- crates/ide_assists/src/handlers/add_explicit_type.rs
> Evaluate constants in array repeat expression

- crates/ide_completion/src/completions/fn_param.rs
- crates/ide_completion/src/tests/fn_param.rs
- insert commas around when necessary
- only suggest `self` completions when param list is empty
- stop suggesting completions for identifiers which are already on the param list
Closes #11085
> fix(completions): improve fn_param

- crates/ide_assists/src/handlers/add_missing_impl_members.rs
- crates/ide_db/src/helpers/insert_whitespace_into_node.rs
> Always put a space after dyn in macro pretty-printing

- crates/ide_assists/src/handlers/extract_variable.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10034
This will parse the field expression and look at whether it is marked `&` or `&mut` and include a modifier if appropriate. The original issue only mentions `&mut params` but I've found that this issue also occurs for `&mut locals` as well as `&params` and `&locals` so I've also added tests for them.
I'd definitely be interested in hearing where I can make my code more idiomatic for Rust.
> Correctly pass through reference modifiers when extracting a variable

- crates/ide/src/expand_macro.rs
- crates/ide_db/src/helpers/insert_whitespace_into_node.rs
… regardless of whether the next symbol is punctuation or not.
Followup to #11200.
> Always put a space after impl in macro pretty-printing

- crates/hir_def/src/attr.rs
Currently this code produces an empty derive path for every `,`, which makes the IDE layer resolve derive paths to the wrong derive macro in the list. Skip `,`s to fix that. (nameres just ignored them, so it didn't cause problems there)
bors r+
> fix: Fix parsing of `#[derive]` paths

- crates/hir_def/src/db.rs
- crates/project_model/src/tests.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/reload.rs
- docs/user/generated_config.adoc
- editors/code/package.json
With this one can specify proc-macros from crates to expand into their input as a (temporary) workaround for the current completion problems with some of the bigger attribute proc-macros like `async_trait`.
This could've been done by just not expanding these macros, but that would require fiddling with nameres. I felt like this approach was simpler to pull off while also keeping the behaviour of the attributes/proc-macro in that they still expand instead of being dead syntax to us.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11052
Usage(`async_trait` as example):
```jsonc
"rust-analyzer.procMacro.dummies": {
"async-trait": [ // crate name(as per its cargo.toml definition, not the dependency name)
"async_trait" // exported proc-macro name
]
},
```
> feat: Add config to replace specific proc-macros with dummy expanders

- crates/ide/src/expand_macro.rs
- crates/ide_assists/src/handlers/add_missing_impl_members.rs
> minor: Move pretty-printing test out of assist

- crates/ide_completion/src/context.rs
- crates/ide_completion/src/render.rs
The original code fails to detect there's a ref in scenarios such as `&mut s` and `& s` because `WHITESPACE` and `IDENT` got reversed.
Closes #11199.
> fix: Correct has_ref detection, avoiding duplicate &mut insertion on parameter completion

- crates/ide_assists/src/handlers/add_turbo_fish.rs
Fixes #11219
The issue talks about three different types of params: type, const & lifetime. I wasn't entirely sure which ones are intended to be included here so I've gone for the type & const params (i.e. exclude lifetime).
I've added a test case for both a lifetime param and a const param. I'm still making my way through the rust book (chapter 7, yay) so I'm not too sure yet what these are but my testing shows that this approach generates code that compiles.
> Turbo fish assist: don't include lifetime parameters

- crates/hir/src/lib.rs
- crates/hir_expand/src/name.rs
- crates/hir_ty/src/method_resolution.rs
- crates/ide/src/lib.rs
- crates/ide_diagnostics/src/handlers/missing_fields.rs
- crates/ide_diagnostics/src/lib.rs
- crates/ide_diagnostics/src/tests.rs
- crates/rust-analyzer/src/config.rs
- crates/syntax/src/ast/make.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Use `Default::default()` in struct fields when we ask to fill it instead of putting `todo!()` for every fields
before:
```rust
pub enum Other {
One,
Two,
}
pub struct Test {
text: String,
num: usize,
other: Other,
}
fn t_test() {
let test = Test {<|>};
}
``` 
after: 
```rust
pub enum Other {
One,
Two,
}
pub struct Test {
text: String,
num: usize,
other: Other,
}
fn t_test() {
let test = Test {
text: String::new(),
num: 0,
other: todo!(),
};
}
```
> feat: add config to use reasonable default expression instead of todo! when filling missing fields

- crates/ide_assists/src/handlers/add_missing_impl_members.rs
- crates/ide_db/src/path_transform.rs
- crates/syntax/src/ast/make.rs
Fixes #11045 
The path transform now detects if a type parameter that is being substituted has an associated type. In that case it is necessary (or safe in general case) to fully qualify the substitution with a trait which the associated type belongs to.
This PR also fixes the previous wrong behavior of the substitution that could create an invalid tree `PATH_TYPE -> PATH_TYPE -> ...`.
> Fix generic type substitution in impl trait with assoc type

- crates/hir/src/semantics/source_to_def.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/keys.rs
We already store a `DynMap` per `(Container, HirFileId)` pair, so the `InFile` keys are already guruanteed to always be of the same file id
bors r+
> internal: Remove `InFile` wrapping from `DynMap` keys

- crates/hir_def/src/attr.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/tests.rs
Fixes another regression caused by https://github.com/rust-analyzer/rust-analyzer/pull/11225
bors r+
> fix: Fix outline modules spilling inner doc injections into their parent

- crates/hir_expand/src/lib.rs
- crates/proc_macro_srv/src/abis/abi_1_56/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_58/mod.rs
- crates/syntax/src/ast/generated/nodes.rs
- crates/syntax/src/ast/node_ext.rs
- crates/syntax/src/tests/sourcegen_ast.rs
Some procedural macros tend to get very large invocations, for example RTIC's, leading to issues like https://github.com/rtic-rs/cortex-m-rtic/issues/582, where almost the entire screen is underlined while editing incomplete code in the macro.
This PR shrinks the spans of errors from attribute macros and derives to point only at the attribute, which also matches rustc more closely.
bors r+
> fix: shrink the span of errors from attribute macros and derives

- crates/hir_ty/src/display.rs
Helps a little bit with https://github.com/rust-analyzer/rust-analyzer/issues/11240
bors r+
> Print a single ellipsis for any number of omitted types

- docs/user/manual.adoc
Since Kate 21.12 rust-analyzer is the default. See this Kate MR: https://invent.kde.org/utilities/kate/-/merge_requests/495
> Kate uses rust-analyzer by default now

- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/tests/attribute.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11254 due to the comment being lowered to an attribute
bors r+
> fix: Don't complete attributes with existing expressions

- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
- crates/ide/src/lib.rs
- crates/ide/src/navigation_target.rs
- crates/ide_db/src/items_locator.rs
- crates/ide_db/src/lib.rs
- crates/ide_db/src/symbol_index.rs
The boundary was broken in https://github.com/rust-analyzer/rust-analyzer/pull/10872 by reexporting a bunch of `hir_def`-internal types.
This PR moves symbol collection to `hir` and removes those reexports again.
bors r+
> internal: Mostly restore `hir` API boundary

- crates/hir/src/lib.rs
- crates/hir/src/symbols.rs
- crates/ide_db/src/symbol_index.rs
- crates/ide_db/src/test_data/test_symbol_index_collection.txt
followup to https://github.com/rust-analyzer/rust-analyzer/pull/11266
bors r+
> internal: Remove `ModuleId` from `hir` reexports

- crates/hir/src/lib.rs
It's not used outside of it
bors r+
> internal: Unexport `MacroDefId` from `hir`

- crates/ide_assists/src/handlers/merge_match_arms.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/9337
> Merge match assist: take arm types into consideration 

- crates/ide_completion/src/context.rs
- crates/ide_completion/src/item.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10245
bors r+
> internal: Decrease PartialOrd and PartialEq trait methods completion relevance

- crates/ide_assists/src/handlers/expand_glob_import.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/rust-analyzer/src/main_loop.rs
> fix: rust-analyzer spamming overly error message when workspace not being loaded

- crates/ide/src/status.rs
While investigating https://github.com/rust-analyzer/rust-analyzer/issues/11300 I noticed that we only output the first crate, which masks the reason for that issue – the file in question is the root of multiple crates, and one is missing dependencies.
This PR makes "Rust Analyzer: Status" include *every* crate a file is part of.
bors r+
> fix: status: output all crates a file belongs to

- crates/ide_db/src/helpers/insert_use.rs
- crates/ide_db/src/helpers/insert_use/tests.rs
Fixes #8607.
This commit changes the auto-import functionality and causes it to add imports after any leading comments, which are commonly license headers. This does not affect comments on items as they're considered part of the item itself and not separate.
> fix: insert auto-imports after header comments

- crates/hir_expand/src/builtin_fn_macro.rs
- crates/hir_expand/src/eager.rs
This isn't needed since `tt::Subtree` already implements `Default`, and an empty expansion is the appropriate default here.
bors r+
> internal: Remove redundant `Option` from eager macro fns

- crates/hir/src/semantics.rs
- crates/hir_def/src/attr.rs
Reduces the panic in https://github.com/rust-analyzer/rust-analyzer/issues/11298 to an early return, that means we won't resolve these cases again for now, but this is better than constantly panicking in highlighting and hovering.
bors r+
> fix: don't panic in semantics due to `cfg_attr` disrupting offsets

- Cargo.lock
- crates/ide/Cargo.toml
- crates/ide/src/lib.rs
- crates/ide/src/prime_caches.rs
- crates/ide/src/prime_caches/topologic_sort.rs
- crates/rust-analyzer/Cargo.toml
- crates/rust-analyzer/src/cli/load_cargo.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/user/generated_config.adoc
- editors/code/package.json
cache priming goes brrrr... the successor to #10149
---
this PR implements a parallel cache priming strategy that uses a topological work queue to feed a pool of worker threads the crates to index in parallel.
> ide: parallel prime caches

- docs/dev/style.md
An example of preferring `<`/`<=` over `>`/`>=` was using `>`.
> minor: fix a typo in the style guide

- crates/rust-analyzer/tests/slow-tests/tidy.rs
git 2.35 introduces a [change in behavior](https://github.com/git/git/blob/89bece5c8c96f0b962cfc89e63f82d603fd60bed/Documentation/RelNotes/2.35.0.txt#L330-L333) that breaks this check.
bors r+
> fix: Fix merge commit check for git 2.35

- crates/proc_macro_api/src/lib.rs
- crates/proc_macro_api/src/msg.rs
- crates/proc_macro_srv/src/lib.rs
> Set current working directory for procedural macros

- editors/code/src/client.ts
Set `"supportHtml": true` to support rendering `<code>` blocks in hovers.
e.g.  https://github.com/rust-lang/rust/blob/1bd4fdc943513e1004f498bbf289279c9784fc6f/library/std/src/fs.rs#L109
> Support <code> blocks from Rust docs in vscode hover

- crates/base_db/src/lib.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/tests.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/nameres.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/name.rs
Resolves #8640
@matklad thanks, for the instructions, they were very helpful :)
> feat: Support `#![recursion_limit]` attribute

- crates/proc_macro_srv/src/dylib.rs
We use `ra_ap_proc_macro_srv` library in IntelliJ Rust in order to expand proc macros. We need a way to disable [DLL copying to a temp dir on Windows](https://github.com/rust-analyzer/rust-analyzer/blob/master/crates/proc_macro_srv/src/dylib.rs#L166) behavior because it causes issues like https://github.com/intellij-rust/intellij-rust/issues/7709. Unlike RA, file locking is not an issue for IntelliJ Rust because we copy DLLs to a temp dir before calling the expander.
> Add a way to disable dll copying for users of proc_macro_srv library

- crates/limit/src/lib.rs
Not a big deal, but generally loops should use `_weak` version of `compare_exchange`.
> minor: Use `compare_exchange_weak` in `limit::Limit::check`

- crates/proc_macro_srv/src/lib.rs
> Rollback env vars changed by a proc macro

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/goto_definition.rs
- crates/syntax/src/ast.rs
- crates/syntax/src/ast/node_ext.rs
- crates/syntax/src/ast/traits.rs
Proper fix for https://github.com/rust-analyzer/rust-analyzer/issues/11298
bors r+
> fix: Fix `cfg_attr` invalidating derive identifier IDE functionalities

- crates/ide_db/src/line_index.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_utils.rs
Intended as a fix, or at least a sticking plaster, for #11081.
I have arranged that [offset()](https://github.com/rust-analyzer/rust-analyzer/blob/1ba9a924d7b161c52e605e157ee16d582e4a8684/crates/ide_db/src/line_index.rs#L105-L107) returns `Option<TextSize>` instead of going out of bounds; other changes are the result of following the compiler after doing this.
Perhaps there's still an issue here - I suppose the server and client have gotten out of sync and that probably shouldn't happen in the first place?  I see that https://github.com/rust-analyzer/rust-analyzer/issues/10138#issuecomment-913727554 suggests what sounds like a more substantial fix which I think might be aimed in this direction.  So perhaps that one should be left open to cover such things?
Meanwhile, I hope that …
> fix: don't panic on seeing an unexpected offset

- Cargo.toml
- crates/ide_assists/src/handlers/extract_function.rs
- crates/ide_assists/src/tests/generated.rs
- crates/syntax/src/ast/make.rs
Fixes #9011
The difficulty I came across is that the original assist works from the concept of a `ast::StmtList`, a node, but that does not allow me to (easily) represent comments, which are tokens. To combat this, I do a whole bunch of roundtrips: from the `ast::StmtList` I retrieve the `NodeOrToken`s it encompasses. 
I then cast all `Node` ones back to a `Stmt` so I can apply indentation to it, after which it is again parsed as a `NodeOrToken`.
Lastly, I add a new `make::` api that accepts `NodeOrToken` rather than `StmtList` so we can write the comment tokens.
> Extract function also extracts comments

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/utils.rs
- crates/ide_completion/src/completions/qualified_path.rs
In code like this:
```rust
impl<T> Option<T> {
fn as_deref(&self) -> T::Target where T: Deref {}
}
```
when trying to resolve the associated type `T::Target`, we were only
looking at the bounds on the impl (where the type parameter is defined),
but the method can add additional bounds that can also be used to refer
to associated types. Hence, when resolving such an associated type, it's
not enough to just know the type parameter T, we also need to know
exactly where we are currently.
This fixes #11364 (beta apparently switched some bounds around).
> Fix assoc type shorthand from method bounds

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir_def/src/path.rs
- crates/hir_ty/src/infer.rs
- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/completions/attribute.rs
- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/flyimport.rs
- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/completions/pattern.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/completions/snippet.rs
- crates/ide_completion/src/completions/unqualified_path.rs
- crates/ide_completion/src/completions/use_.rs
- crates/ide_completion/src/completions/vis.rs
- crates/ide_completion/src/context.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/tests/attribute.rs
- crates/ide_completion/src/tests/fn_param.rs
- crates/ide_completion/src/tests/pattern.rs
- crates/ide_completion/src/tests/use_tree.rs
- crates/ide_completion/src/tests/visibility.rs
- crates/ide_db/src/search.rs
- crates/syntax/src/ast/node_ext.rs
Currently our completion infra is split into several modules, each trying to do completions for something specific. This "something" is rather unstructured as it stands now, we have a module for `flyimporting path` completions, `unqualified` and `qualified path` completions, modules for `pattern position` completions that only try to complete extra things for patterns that aren't done in the path modules, `attribute` completions that again only try to add builtin attribute completions without adding the normal path completions and a bunch of other special "entity" completions like lifetimes, method call/field access, function param cloning, ... which serve a more specific purpose than the previous listed ones.
As is evident, the former mentioned ones have some decent overlap which …
> internal: Refactor completion module split

- crates/hir_expand/src/builtin_fn_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/proc_macro.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/tt_iter.rs
Also fixes https://github.com/rust-analyzer/rust-analyzer/issues/10051, as we no longer emit an empty diagnostic in some expansion cases which seems to trip up vscode for some reason. Using `compile_error!("")` will still trigger the vscode bug.
bors r+
> internal: Shrink `mbe::ExpandError` and `mbe::ParseError`

- crates/ide_completion/src/completions/trait_impl.rs
Fixes #11301
If the user has typed, say, `fn de` while implementing `Default`, or `type Ta` when implementing `Deref`, then the resulting completion suggestion will replace the entire "line", which, on its own, is fine.
However, the use of `ctx.source_range()` in this code was meant that `source_range` field of the `CompletionItem` covers only the identifier and not the preceding keyword.
Over in `rust_analyzer::to_proto::completion_item`, this caused the LSP completion response to be broken up into a text edit that replaces `de` with `fn default() -> Self {` and then an entry in `additional_text_edits` to remove the extra `fn`.
I'm pretty sure that using the field like that is (slightly) out of [spec](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/# …
> fix: Include `fn`/`type`/`const` keyword in trait impl completion item source ranges

- Cargo.lock
- crates/ide/Cargo.toml
- crates/ide/src/doc_links.rs
- crates/ide/src/doc_links/tests.rs
Stumbled across this accidentally while familiarizing myself with the code base.
Update `pulldown-cmark-to-cmark` Fix for #11008
> fix: Update dependency, fix Markdown references

- editors/code/package-lock.json
- editors/code/package.json
Again me getting familiar with the code base :D
I noticed npm warning about two vulnerabilities
```
markdown-it  <12.3.2
Severity: moderate
Uncontrolled Resource Consumption in markdown-it - https://github.com/advisories/GHSA-6vfc-qv3f-vr6c
fix available via `npm audit fix`
node_modules/markdown-it
vsce  1.26.0 - 2.6.3
Depends on vulnerable versions of markdown-it
node_modules/vsce
simple-get  3.0.0 - 3.1.0
Severity: high
Exposure of Sensitive Information in simple-get - https://github.com/advisories/GHSA-wpg7-2c88-r8xv
fix available via `npm audit fix`
node_modules/simple-get
```
So I thought why not run `npm audit fix`
> fix two vulneabilities (moderate: 1, high: 1) by running npm audit

- editors/code/.eslintrc.js
- editors/code/tsconfig.eslint.json
Allows the language server for eslint to work inside VS Code.
Before change:
After change:
> Fix eslint language server not working

- crates/ide/src/rename.rs
- crates/ide_db/src/rename.rs
> fix: renaming modules does not change references by super

- crates/ide_completion/src/render/function.rs
this change renders in the autocomplete detail, whether a function is async/const/unsafe.
i found myself wanting to know this information at a glance, so now it renders here:
> [ide_completion] render if a function is async/const/unsafe in completion details

- Cargo.lock
- crates/base_db/src/fixture.rs
- crates/hir_def/src/macro_expansion_tests.rs
- crates/hir_def/src/macro_expansion_tests/proc_macros.rs
- crates/hir_expand/Cargo.toml
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/fixup.rs
- crates/hir_expand/src/hygiene.rs
- crates/hir_expand/src/lib.rs
- crates/ide_completion/src/tests/attribute.rs
- crates/mbe/src/lib.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/token_map.rs
- crates/tt/src/lib.rs
This implements the "fix up syntax nodes" workaround mentioned in #11014. It isn't much more than a proof of concept; I have only implemented a few cases, but it already helps quite a bit.
Some notes:
- I'm not super happy about how much the fixup procedure needs to interact with the syntax node -> token tree conversion code (e.g. needing to share the token map). This could maybe be simplified with some refactoring of that code.
- It would maybe be nice to have the fixup procedure reuse or share information with the parser, though I'm not really sure how much that would actually help.
> feat: Fix up syntax errors in attribute macro inputs to make completion work more often

- docs/dev/lsp-extensions.md
Fix #11429 by extending the documentation of SsrParms with the
mandatory field 'selections'.  Copy its description from lsp_ext.rs.
> fix: documentation of SsrParams

- crates/ide/src/rename.rs
- crates/ide_db/src/rename.rs
> fix(rename): Use text range of a mod name after macro expansion

- crates/ide/src/hover/render.rs
Adds the return type of keywords to tool-tips where it makes sense. This applies to: `if`, `else`, `match`, `loop`, `unsafe` and `await`. Thanks to @Veykril for sharing the idea of putting return type highlighting on other keywords!
Closes #11359
> feat: Add type hint for keyword expression hovers

- crates/ide_assists/src/handlers/merge_imports.rs
- crates/ide_db/src/helpers/merge_imports.rs
> fix: Fix cases where `Merge Imports` would drop imports.

- crates/ide/src/hover.rs
> fix: keyword hover works on non-keyword tokens if expanded to keyword

- crates/mbe/src/expander/matcher.rs
It's a micro optimization. I don't know if it's really necessary (less alloc is always better).
> Impr mbe: remove unecessary temporary vec

- crates/rust-analyzer/src/caps.rs
Commit 27c4be6b4f68 wasn't really complex, but I still managed to make a mistake there, which this PR fixes.  Sorry.
> Fix a typo in server_capabilities.experimental

- crates/hir_def/src/lib.rs
- crates/hir_expand/src/lib.rs
This is stored in `MacroCallLoc` which is returned from a query, so cloning should be made cheap.
bors r+
> internal: Wrap MacroCallKind::Attr attr_args field in an Arc

- docs/user/manual.adoc
Semantic tokens highlighting is added in coc.nvim now.
> chore(manual): update coc-rust-analyzer manual

- crates/project_model/src/cargo_workspace.rs
- crates/rust-analyzer/src/cargo_target_spec.rs
When using `F1`->`Rust Analyzer: Run` action on an `example`, pass its `required-features` to `cargo run`. This allows to run examples that were otherwise impossible to run with RA.
> Pass required features to cargo when using run action

- crates/ide/src/runnables.rs
Before the doc_test would be outputted like this:
```zsh
"Foo<T, U>::t"
```
However, this would cause problems with shell redirection. I've changed it
so when generics are involved we simply wrap the expression under quotes as so:
```zsh
"\"Foo<T, U>::t\""
```
Note:
At the cost of adding this, I had to allocate a new string via
`format!{}`. However, I argue this is alright as this for just for
outputting the name of the doc test.
The following tests have been changed:
```
runnables::tests::doc_test_type_params
runnables::tests::test_doc_runnables_impl_mod
runnables::tests::test_runnables_doc_test_in_impl
```
Closes  https://github.com/rust-analyzer/rust-analyzer/issues/11489
> Correctly fix formatting doc tests with generics

- docs/user/manual.adoc
This closes #11226. The content seemed to make more sense in the
installation section as opposed to the Troubleshooting section.
> doc: state that only the latest stable toolchain is supported

- crates/ide_assists/src/handlers/replace_qualified_name_with_use.rs
Fixes #11505. also removed an unnecessary `clone_for_update` call.
> fix(assist): Drop generic args in path before insert use in `replace_qualified_name_with_use`

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/semantics/source_to_def.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/dyn_map.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/keys.rs
- crates/hir_def/src/lib.rs
- crates/hir_def/src/nameres/attr_resolution.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_expand/src/builtin_attr_macro.rs
- crates/hir_expand/src/db.rs
- crates/hir_expand/src/lib.rs
- crates/ide/src/expand_macro.rs
- crates/ide/src/hover/tests.rs
- crates/ide/src/references.rs
- crates/ide/src/syntax_highlighting.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide_assists/src/handlers/auto_import.rs
- crates/ide_assists/src/handlers/replace_derive_with_manual_impl.rs
- crates/ide_assists/src/tests/generated.rs
- crates/ide_completion/src/completions/trait_impl.rs
- crates/ide_completion/src/tests/attribute.rs
- crates/ide_db/src/defs.rs
- crates/ide_db/src/helpers.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/syntax/src/ast/node_ext.rs
- docs/dev/architecture.md
Quoting my comment:
> We generate a very specific expansion here, as we do not actually expand the `#[derive]` attribute
> itself in name res, but we do want to expand it to something for the IDE layer, so that the input
> derive attributes can be downmapped, and resolved as proper paths.
> This is basically a hack, that simplifies the hacks we need in a lot of ide layer places to
> somewhat inconsistently resolve derive attributes.
> 
> As such, we expand `#[derive(Foo, bar::Bar)]` into
> ```
>  #[Foo]
>  #[bar::Bar]
>  ();
> ```
> which allows fallback path resolution in hir::Semantics to properly identify our derives.
> Since we do not expand the attribute in nameres though, we keep the original item.
> 
> The ideal expansion here would be for the `#[derive]` to re-emit the annotated …
> feat: Expand the derive attribute into a pseudo expansion

- crates/ide_assists/src/handlers/extract_module.rs
Should fix #11007 and #11443
Makes following changes:
- Removes visiblity modifiers from trait items
- Respect user given visibility
- Updated tests for the same
> fix: visibility in impl items and pub(crate) to pub in extract_module

- crates/ide_assists/src/handlers/extract_struct_from_enum_variant.rs
Fixes #11452.
This PR updates extract_struct_from_enum_variant. Extracting a struct `A` form an enum like
```rust
enum X<'a, 'b> {
A { a: &'a () },
B { b: &'b () },
}
```
will now be correctly generated as
```rust
struct A<'a> { a: &'a () }
enum X<'a, 'b> {
A(A<'a>),
B { b: &'b () },
}
```
instead of the previous
```rust
struct A<'a, 'b>{ a: &'a () } // <- should not have 'b
enum X<'a, 'b> {
A(A<'a, 'b>),
B { b: &'b () },
}
```
This also works for generic type parameters and const generics.
Bounds are also copied, however I have not yet implemented a filter for unneeded bounds. Extracting `B` from the following enum
```rust
enum X<'a, 'b: 'a> {
A { a: &'a () },
B { b: &'b () },
}
```
will be generated as 
```rust
struct B<'b: 'a> { b: &'b () } // <- should be `struct B<'b> { b: &'b () }` …
```
> Extract struct from enum variant filters generics

- crates/hir/src/lib.rs
- crates/ide/src/references.rs
cc https://github.com/rust-analyzer/rust-analyzer/issues/11528
bors r+
> internal: Resolve functions as proc-macros via `FileAstId`

- crates/hir/src/lib.rs
would like to have this on `hir::Type` for a small project i am working on, unless there is another way to check if `hir::Type` is a slice primitive?
> add `is_slice` method to `hir::Type`

- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/ide_db/src/defs.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10253#issuecomment-920962927
(the same issue probably exists for method calls, but I think fixing that might be trickier)
Visibility checks were introduced in https://github.com/rust-analyzer/rust-analyzer/issues/7841 for autoderef to work properly, so now we just record the first field we find unconditionally, and then overwrite it if autoderef manages to find another field in a later cycle.
> fix: Resolve private fields in type inference

- crates/rust-analyzer/src/cli/analysis_stats.rs
- crates/rust-analyzer/src/cli/flags.rs
- xtask/src/flags.rs
For easy diffing, to find changes in unknown types / type mismatches.
> Add CSV output to analysis-stats

- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir_ty/src/autoderef.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/coerce.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests.rs
- crates/hir_ty/src/tests/coercion.rs
- crates/hir_ty/src/tests/method_resolution.rs
- crates/hir_ty/src/tests/traits.rs
- crates/hir_ty/src/traits.rs
- crates/ide_assists/src/handlers/convert_iter_for_each_to_for.rs
- crates/ide_assists/src/handlers/destructure_tuple_binding.rs
- crates/ide_assists/src/handlers/generate_is_empty_from_len.rs
- crates/ide_completion/src/completions/dot.rs
- crates/ide_completion/src/completions/pattern.rs
- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_db/src/helpers/import_assets.rs
- crates/ide_ssr/src/resolving.rs
- don't return the receiver type from method resolution; instead just
return the autorefs/autoderefs that happened and repeat them. This
ensures all the effects like trait obligations and whatever we learned
about type variables from derefing them are actually applied. Also, it
allows us to get rid of `decanonicalize_ty`, which was just wrong in
principle.
- Autoderef itself now directly works with an inference table. Sadly
this has the effect of making it harder to use as an iterator, often
requiring manual `while let` loops. (rustc works around this by using
inner mutability in the inference context, so that things like unifying
types don't require a unique reference.)
- We now record the adjustments (autoref/deref) for method receivers
and index expressions, which we didn't before.
- …
> Refactor autoderef/method resolution

- crates/hir_ty/src/display.rs
- crates/ide/src/hover/tests.rs
We used to print it as `{extern_crate}`, this PR resolves it to the crate's name, or falls back to `$crate` if the crate has no name.
bors r+
> fix: properly display `$crate` in hovers

- crates/hir_expand/src/builtin_fn_macro.rs
- crates/hir_expand/src/name.rs
should fix https://github.com/rust-analyzer/rust-analyzer/issues/11551
bors r+
> fix: fix type mismatches with `unreachable!` macro in Rust 1.59

- crates/hir/src/lib.rs
- crates/ide/src/hover/render.rs
- crates/ide/src/navigation_target.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide_assists/src/handlers/extract_function.rs
- crates/ide_db/src/defs.rs
> minor: Make hir::Local::name infallible

- xtask/src/metrics.rs
Closes #9997
This doesn't seem to affect the metrics, but I'm not sure since somehow I get different values than what shows up on CI.
With `stable`:
```
exprs: 94151, ??ty: 96 (0%), ?ty: 25 (0%), !ty: 6
```
CI shows 16.
Also, https://github.com/rust-analyzer/rust-analyzer/pull/7250 strikes again, I can never tell what those numbers are.
r? @jonas-schievink
> internal: Update `url` to make `webrender` build when computing metrics

- crates/hir_ty/src/infer/expr.rs
They're not true anymore after #11375.
> minor: Remove misleading comments

- crates/syntax/src/ast/expr_ext.rs
> fix: Fix `if` in #11561

- crates/text_edit/src/lib.rs
This is mainly me learning some rust, and only anecdotally about addressing some `fixme`s. Feel free to nope :)
There is a follow up PR in the pipeline which tackles the other two `fixme`s but it's a bit more invasive. So I wanted to get this out of the way
> refactorings and FIXME fixes in text edit

- crates/hir_expand/src/builtin_fn_macro.rs
So that we won't have a strange bug when edition 2024 will land.
rustc [also does that](https://github.com/rust-lang/rust/blob/427cf81206d3b6cf41c86c1b9ce113a33f1ce860/compiler/rustc_builtin_macros/src/edition_panic.rs#L84).
> minor: Future-proof against a next edition by using `>=` and not `==`

- crates/ide/src/typing/on_enter.rs
> minor: Add scary warning to `onEnter`

- .github/workflows/release.yaml
> Build release binaries on Ubuntu 18.04

- crates/hir_def/src/item_tree/lower.rs
> fix: Add `abort` to safe intrinsics list

- crates/hir/src/display.rs
- crates/ide/src/hover/tests.rs
The current behavior is to ignore the ellipsis.
> show variadic args in hover function signature

- crates/hir_ty/src/infer/unify.rs
Fixes #11601. 
I observed that removing the `rollback` line in https://github.com/rust-analyzer/rust-analyzer/commit/6fc3d3aa4cbf637d748c60cfdbb98b5f6a040576 fixes the issue.  
Looking at the stacktrace, I believe not restoring `type_variable_table` causes `type_variable_table` and `var_unification_table` to go out of sync, then when `hir_ty::infer::unify::InferenceTable::new_var` tries to extend `type_variable_table` to be the same length as `var_unification_table`, problems will arise.
However, I cannot pinpoint exactly how or where the vector capacity overflow happens, so my understanding might not be correct after all.
> fix: Add type variable table to InferenceTableSnapshot

- Cargo.lock
- crates/text_edit/Cargo.toml
- crates/text_edit/src/lib.rs
Some more changes to text_edit. Basic idea is to make `Indel` implement `PartialOrd` to take advantage of some sweet sweet iteration, most notably itertool's `merge`.
> Small refactor text edit 2nd

- assets/logo-wide.svg
Currently the black text in the logo in the README just has a white stroke so it’s readable in dark mode. This PR adds automatic detection of whether the user is using system dark mode, and if they are changes the text colour to white and removes the stroke.
Before:
After (now in Chrome because this doesn’t seem to work in Safari):
> Automatically change text color in logo based on dark mode

- xtask/src/dist.rs
cc https://github.com/rust-analyzer/rust-analyzer/pull/11445
bors r+
> fix: client distribution string replacement looking for wrong key

- crates/rust-analyzer/src/to_proto.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/2797#issuecomment-1061594139.
I originally thought that other extensions don't include the colons, but the TypeScript one seems to do.
> Add back colons around inlay hints

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/generics.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/resolver.rs
- crates/hir_ty/src/chalk_ext.rs
- crates/hir_ty/src/display.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/utils.rs
fix #11659 
This is a band-aid until proper const generic support.
> Insert dummy values for const generics in subst

- crates/base_db/src/fixture.rs
- crates/base_db/src/input.rs
- crates/hir_def/src/attr.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
- crates/hir_expand/src/name.rs
- crates/ide/src/goto_definition.rs
- crates/ide/src/lib.rs
- crates/ide/src/references.rs
- crates/ide/src/shuffle_crate_graph.rs
- crates/project_model/src/tests.rs
- crates/project_model/src/workspace.rs
> fix: Properly handle proc-macro crate types for nameres

- crates/ide_assists/src/handlers/extract_module.rs
Should close: #11508 
From issue:
Concern 1: Seems to be fixed in latest `rust-analyzer` build
Concern 2 and 3: Should be fixed by this PR
Concern 4: Got fixed in #11472 
Points to note:
- Here I have seperated use items and other items, this is becuase the new `impl` block which we will be creating cannot contain use items as immediate children. As they are the only one item that can be generated by our assist, so seperating them helps in handling their inclusion in new `impl` block inside new `module`
- There's also a new method added which helps in removing remaning left over indentation after removing `impl` or other `item`
> fix: extract_module selection inside impl

- crates/parser/src/grammar/items.rs
- crates/parser/test_data/parser/inline/ok/0012_type_item_where_clause.rs
- crates/parser/test_data/parser/inline/ok/0199_type_item_where_clause_deprecated.rast
- crates/parser/test_data/parser/inline/ok/0199_type_item_where_clause_deprecated.rs
A recent Rust nightly changed it: https://github.com/rust-lang/rust/issues/89122
This allows both the old and new location.
Fixes #11651
> Add support for new `where` clause location in associated types.

- crates/ide_completion/src/completions/qualified_path.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/builder_ext.rs
- crates/ide_completion/src/render/compound.rs
- crates/ide_completion/src/render/enum_variant.rs
- crates/ide_completion/src/render/struct_literal.rs
- crates/ide_completion/src/tests/expression.rs
- crates/ide_completion/src/tests/pattern.rs
- crates/ide_completion/src/tests/record.rs
- crates/ide_completion/src/tests/use_tree.rs
This addresses several related inconsistencies:
- tuple structs use tab stops instead of placeholders
- tuple structs display in the completion menu as `Struct {…}` instead of `Struct(…)`
- enum variants don't receive field completions at all
- enum variants display differently from structs in the completion menu
Also, structs now display their type in the completion detail rather than the raw snippet text to be inserted.
As far as what's user-visible, that looks like this:
| | Menu | Completion | Detail |
|-|-|-|-|
| Record struct (old) | `Struct {…}` | `Struct { x: ${1:()}, y: ${2:()} }$0` | `Struct { x: ${1:()}, y: ${2:()} }$0` |
| Record struct (new) | `Struct {…}` | `Struct { x: ${1:()}, y: ${2:()} }$0` | `Struct { x: i32, y: i32 }` |
| Tuple struct (old) | `Struct {…}`  | …
> feat: Enum variant field completion, enum variant / struct consistency

- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/completions/record.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/union_literal.rs
- crates/ide_completion/src/tests/record.rs
Adds a `Union {…}` completion in contexts where a union is expected, expanding to a choice of available fields (if snippets are supported):
Also, adds support for listing possible fields in an empty union literal.
Closes #11568.
> feat: Suggest union literals, suggest union fields within an empty union literal

- editors/code/src/main.ts
Problem: NixOS started using quotes around it's id field in /etc/os-release
Solution: Parially parsing os-release, and detecting, whether `nixos` appears anywhere in "ID=" field\
See https://github.com/rust-analyzer/rust-analyzer/issues/11695
Closes #11695
> editors/code: fix nixos detection

- editors/code/src/main.ts
Assuming ID=linux by default.
Also removed toLowerCase — it really shouldn't be needed.
Fixes #11709
>  editors/code: fix crash due to missing ID= field

- crates/ide_completion/src/context.rs
- crates/ide_completion/src/patterns.rs
- crates/ide_completion/src/tests/item.rs
- crates/ide_completion/src/tests/pattern.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11205
bors r+
> fix: Fix completions not always working in for-loop patterns

- docs/user/manual.adoc
Related to #6405, #6883 but not sure if they should be closed or not as this is just a documentation update.
This functionality was changed as of #11445 and now can be customized using native VSCode settings instead of `rust-analyzer`-specific ones.
> Update manual for inlay hint customization

- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/regression.rs
fix https://github.com/rust-analyzer/rust-analyzer/pull/11688#issuecomment-1066824954
> Fix const generic panic

- crates/rust-analyzer/src/to_proto.rs
CC https://github.com/rust-analyzer/rust-analyzer/pull/11445#discussion_r826863321
> fix: Mark chaining hints as types

- xtask/src/metrics.rs
Doesn't seem like you can inspect the error kind, so discarding the result it is
bors r+
> minor: unblock metrics

- crates/ide_assists/src/handlers/convert_to_guarded_return.rs
- crates/ide_assists/src/handlers/convert_while_to_loop.rs
- crates/ide_assists/src/handlers/extract_function.rs
- crates/syntax/src/ast/make.rs
Adds a label / lifetime parameter to `ide_assists::handlers::extract_function::FlowKind::{Break, Continue}`, adds support for emitting labels to `syntax::ast::make::{expr_break, expr_continue}`, and implements the required machinery to let `extract_function` make use of them.
This does modify the external API of the `syntax` crate, but the changes there are simple, not used outside `ide_assists`, and, well, we should probably support emitting `break` and `continue` labels through `syntax` anyways, they're part of the language spec.
Closes #11413.
> fix: "Extract to function" assist preserves `break` and `continue` labels

- crates/ide_assists/src/handlers/generate_new.rs
- crates/ide_assists/src/tests/generated.rs
> Emit `#[must_use]` in `Generate new` assist

- crates/ide_assists/src/handlers/generate_getter.rs
- crates/ide_assists/src/tests/generated.rs
Inserts `#[must_use]` for the generated getter methods.
From discussion in https://github.com/rust-analyzer/rust-analyzer/issues/11736 and https://github.com/rust-analyzer/rust-analyzer/pull/11738
> Insert #[must_use] in generate_getter

- crates/hir/src/lib.rs
- crates/hir_def/src/db.rs
- crates/hir_def/src/visibility.rs
- crates/hir_ty/src/builder.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/path.rs
- crates/hir_ty/src/infer/unify.rs
- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
- crates/hir_ty/src/tests/traits.rs
This fixes our type inference problems with `DynMap`; the problem there were the projection types in
```rust
impl<P: Policy> KeyMap<Key<P::K, P::V, P>>
```
which messed up the naive type equality check we did. It also actually simplifies the logic though, IMO. I also added a fix for associated const resolution that I noticed (visibility not being taken into account).
> fix: Properly unify receivers during method resolution

- crates/ide_completion/src/completions/pattern.rs
- crates/ide_completion/src/tests/pattern.rs
followup to https://github.com/rust-analyzer/rust-analyzer/pull/11713
bors r+
> feat: Complete assoc const patterns on builtin types

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_ty/src/lib.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/to_proto.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Disabled by default.
Closes https://github.com/rust-analyzer/rust-analyzer/issues/11275
> feat: Visualize compiler inserted reborrows via inlay hints

- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/body.rs
- crates/hir_def/src/body/lower.rs
- crates/hir_ty/src/diagnostics.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide/src/syntax_highlighting/html.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_assoc_functions.html
- crates/ide/src/syntax_highlighting/test_data/highlight_attributes.html
- crates/ide/src/syntax_highlighting/test_data/highlight_crate_root.html
- crates/ide/src/syntax_highlighting/test_data/highlight_default_library.html
- crates/ide/src/syntax_highlighting/test_data/highlight_doctest.html
- crates/ide/src/syntax_highlighting/test_data/highlight_extern_crate.html
- crates/ide/src/syntax_highlighting/test_data/highlight_general.html
- crates/ide/src/syntax_highlighting/test_data/highlight_injection.html
- crates/ide/src/syntax_highlighting/test_data/highlight_keywords.html
- crates/ide/src/syntax_highlighting/test_data/highlight_lifetimes.html
- crates/ide/src/syntax_highlighting/test_data/highlight_macros.html
- crates/ide/src/syntax_highlighting/test_data/highlight_operators.html
- crates/ide/src/syntax_highlighting/test_data/highlight_rainbow.html
- crates/ide/src/syntax_highlighting/test_data/highlight_strings.html
- crates/ide/src/syntax_highlighting/test_data/highlight_unsafe.html
- crates/ide/src/syntax_highlighting/tests.rs
- crates/ide_db/src/syntax_helpers/node_ext.rs
as long as they aren't inside an unsafe block inside the macro that is.
> feat: Tag macro calls as unsafe if they expand to unsafe expressions

- crates/ide_assists/src/handlers/inline_type_alias.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
- crates/syntax/src/ast/node_ext.rs
I'm working towards implementing #10881, but I'd like to get this in first with earlier feedback.
Is `inline_type_alias` a good enough name? I guess the follow up assist would be called `inline_type_alias_into_all_users` based on that.
> feat: Add an assist for inlining type aliases

- crates/base_db/src/input.rs
- crates/cfg/src/cfg_expr.rs
- crates/cfg/src/dnf.rs
- crates/cfg/src/lib.rs
- crates/hir_def/src/type_ref.rs
- crates/hir_expand/src/mod_path.rs
- crates/hir_ty/src/consteval.rs
- crates/hir_ty/src/diagnostics/decl_check.rs
- crates/hir_ty/src/tls.rs
- crates/ide/src/runnables.rs
- crates/ide/src/syntax_highlighting/tags.rs
- crates/proc_macro_api/src/lib.rs
- crates/profile/src/memory_usage.rs
The final executable is somehow larger (36 239 296 vs 36 238 336 bytes), but this saves us a bit of `text` and `data`:
```
text	   data	    bss	    dec	    hex	filename
23719199	1126625	   4377	24850201	17b2f19	rust-analyzer-baseline
23716027	1126377	   4377	24846781	17b21bd	rust-analyzer-pr
```
> Replace write! with direct `Formatter` calls

- crates/ide_assists/src/handlers/add_missing_match_arms.rs
Fix #11783 
This adds similar logic to non_exhaustive as is currently on doc(hidden)
> fix: fill_match_arms doesn't add wildcard pat for local enums

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This is inconsistent with the other configuration keys unfortunately, but this is an issue of how we structured them here in general.
I feel like we'll have to do a proper pass over all the configs, check them for consistency and then write down some documentation of how our configs should be laid out, then apply fixes to the inconsistencies all at once which will entail breaking some user configurations unfortunately since we won't be able to do proper fallback handling for some of these.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11778
bors r+
> fix: Fix lifetime elision hint configuration key

- crates/proc_macro_srv/src/abis/abi_1_57/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/buffer.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/client.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/closure.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/handle.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/rpc.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/scoped_cell.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/bridge/server.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/diagnostic.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/mod.rs
- crates/proc_macro_srv/src/abis/abi_1_57/proc_macro/quote.rs
- crates/proc_macro_srv/src/abis/abi_1_57/rustc_server.rs
- crates/proc_macro_srv/src/abis/mod.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/10570
cc https://github.com/rust-analyzer/rust-analyzer/pull/10769#issuecomment-1076251859
bors r+
> fix: fix "unwrap on a `None` value" in proc macros built with Rust 1.57.0

- crates/hir/src/symbols.rs
- crates/hir_def/src/child_by_source.rs
- crates/hir_def/src/item_scope.rs
- crates/hir_def/src/nameres/collector.rs
- crates/hir_def/src/nameres/tests/macros.rs
https://github.com/rust-analyzer/rust-analyzer/pull/11663 introduced a regression tracked in https://github.com/rust-analyzer/rust-analyzer/issues/11781, this fixes it.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11781
bors r+
> fix: fix `#[macro_use]` no longer importing non-`macro_rules!` macros

- crates/proc_macro_srv/src/abis/abi_1_47/rustc_server.rs
- crates/proc_macro_srv/src/abis/abi_1_54/rustc_server.rs
- crates/proc_macro_srv/src/abis/abi_1_56/rustc_server.rs
- crates/proc_macro_srv/src/abis/abi_1_57/rustc_server.rs
- crates/proc_macro_srv/src/abis/abi_1_58/rustc_server.rs
Some proc macros, notably rocket, `.unwrap()` the result of `Span::join` (and correctly so, it should never be `None`). We don't have a proper implementation of that API, so we always returned `None`. This changes our stub impl to return the first span instead.
Does not fully fix rocket's macros, they need other stuff to work too.
bors r+
> fix: avoid returning `None` from `Span::join` to fix some proc macros

- crates/proc_macro_srv/src/abis/abi_1_58/rustc_server.rs
Helps with the rocket 0.4 macros, at least on some Rust versions.
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11264
bors r+
> fix: add stubs to make proc macros work that use the `SourceFile` API

- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/tests/simple.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11804
Should fix https://github.com/rust-analyzer/rust-analyzer/issues/11798#issuecomment-1076880521
> fix: Fix async block type inference using containing function return type

- crates/hir/src/lib.rs
- crates/hir_ty/src/consteval.rs
- crates/hir_ty/src/consteval/tests.rs
- crates/hir_ty/src/db.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/tests/simple.rs
- crates/ide/src/hover/tests.rs
This PR enables evaluating things like this:
```rust
const X: usize = 2;
const Y: usize = 3 + X; // = 5
```
My target was nalgebra's `U5`, `U22`, ... which are defined as `type U5 = Const<{ SomeType5::SOME_ASSOC_CONST }>` but I didn't find out how to find the `ConstId` of the implementation of the trait, not the trait itself (possibly related to #4558 ? We can find associated type alias, so maybe this is doable already) So it doesn't help for nalgebra currently, but it is useful anyway.
> Support constants in const eval

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Now that we diagnose type mismatches, we have another diagnostic that can potentially produce false positives, so let's disable experimental diagnostics by default.
> feat: disable experimental diagnostics by default

- crates/ide_completion/src/render.rs
- crates/ide_completion/src/render/function.rs
I.e. don't suggest `Foo::&foo()`.
CC #8058.
> fix: Disable ref_match for qualified paths as well

- docs/dev/style.md
Was going through the documentation itself and found this typo just waiting to be fixed
> Fix typo in the style documentation

- crates/hir/src/lib.rs
- crates/hir_ty/src/diagnostics/expr.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
This means we only need to handle legacy const generics in one place, and it fits there especially since there will be more diagnostics coming.
> internal: Move mismatched arg count diagnostic to inference

- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/regression.rs
fix #11835
If I change `dyn` to `impl` in the test, it will infer the type as `IntoIterator::Item<impl Iterator<Item = [Ar<u8, 7>; 9]> + ?Sized>` instead of `[Ar<u8, 7>; 9]`. Maybe it needs some action?
> Fix another const generic panic

- crates/ide_assists/src/handlers/auto_import.rs
- docs/user/manual.adoc
---
6b38c2d75 docs(auto_import): change by_self -> self and by_crate -> crate
Keep things consistent with the package.json , which uses `self` and
`crate` instead of `by_self` and `by_crate`. Both names are in fact
allowed as aliases, but we should be consistent so that people reading
the docs and using a schema do not see red squiggles.
<br/>
> docs(auto_import): change by_self -> self and by_crate -> crate

- crates/hir_expand/src/builtin_fn_macro.rs
When last expression in a function body is noreturn asm, then analyzer
complains about the type mismatch by highlighting entire body. This
fixes it by introducing loop {} in the expanded code.
Fixes: [#11820](https://github.com/rust-analyzer/rust-analyzer/issues/11820)
> Type mismatch when last expression is noreturn asm

- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/lsp_ext.rs
- crates/rust-analyzer/src/main_loop.rs
- docs/dev/lsp-extensions.md
- editors/code/package.json
- editors/code/src/commands.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
I saw a file sync bug the other day but didn't know how to further debug it. This command might give a clue as to what's wrong and help debug issues like https://github.com/rust-analyzer/rust-analyzer/issues/4829.
bors r+
> internal: Add "view file text" command to debug sync issues

- crates/ide_assists/src/handlers/generate_enum_is_method.rs
- crates/ide_assists/src/handlers/generate_enum_projection_method.rs
Fixes #11636 
In `generate_enum_projection_method.rs`, the changes to the function are from `cargo fmt`, I made the same change as I did in `generate_enum_is_method.rs`.
> create generate is, as, try_into group

- crates/syntax/Cargo.toml
- crates/syntax/rust.ungram
- crates/syntax/src/tests/sourcegen_ast.rs
This makes updating the grammar a lot simpler for us. Though removing it from ungrammar can't be done without bumping it to 2.0 so I'll leave it in there for the time being.
cc https://github.com/rust-analyzer/ungrammar/pull/47
> internal: Move `rust.ungram` into `rust-analyzer/crates/syntax`

- crates/hir_ty/src/tests/simple.rs
- crates/parser/src/grammar/types.rs
We were missing the init expression in case of `let x: = 2`, which breaks type inference of that variable (previously x were `{unknown}`, now it is `i32`).
> Recover from missing type annotation

- crates/ide_completion/src/completions/postfix.rs
- crates/ide_completion/src/completions/record.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/render.rs
Fixes #11850
Adds a parameter for postfix suggestions in `CompletionRelevance`, and basing on it, decreases relevance score of such items in completion list
> Lower postfix suggestions in completions list

- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/utils.rs
TIL that Chalk expects the arguments to a generic associated type to come *before* the ones for the parent trait, not *after* as we have been doing with all other nested generics. Fixing this requires a larger refactoring, so for now this just papers over the problem by completely ignoring parameters of associated types.
Fixes #11769.
> fix: Paper over GAT panic

- crates/hir_ty/src/db.rs
- crates/hir_ty/src/method_resolution.rs
- crates/hir_ty/src/tests/method_resolution.rs
rustc has removed the use of lang items to mark the primitive impls, so just look through the crate graph for them (this should be fine performance-wise since we cache the crates that contain these impls).
Fixes #11876.
> fix: Don't rely on lang items to find primitive impls

- crates/ide_assists/src/handlers/merge_imports.rs
- crates/ide_db/src/imports/insert_use/tests.rs
- crates/ide_db/src/imports/merge_imports.rs
- crates/syntax/src/ast/edit_in_place.rs
Close  #11703 
`ast::UseTree::split_prefix` handles globs now.
Removed an extra branch for globs in `ide_db::imports::merge_imports::recursive_merge` (superseeded by split_prefix).
> fix: splitting path of a glob import wrongly adds `self`

- crates/hir_def/src/item_tree/lower.rs
- crates/ide_completion/src/completions.rs
- crates/ide_completion/src/item.rs
- crates/ide_completion/src/lib.rs
- crates/ide_completion/src/patterns.rs
- crates/ide_completion/src/render.rs
- crates/ide_completion/src/tests/type_pos.rs
- crates/rust-analyzer/src/to_proto.rs
fix #11855
It doesn't work for return types and consts (so their tests are failing) because I can't find their body node in the original file. (Are these original and fake file documented somewhere?)
Also it currently needs to type first character of the type (or manual ctrl+space) to open the auto complete panel, is it possible to open it automatically on typing `:` and `->`?
> Suggest infered type in auto complete

- crates/ide_completion/src/completions/postfix.rs
- crates/ide_completion/src/render.rs
Follow up to #11857, add a test and cov-marks
bors r+
🤖
> add test for postfix completion relevance

- crates/rust-analyzer/src/diagnostics/test_data/reasonable_line_numbers_from_empty_file.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
Previously, when line numbers of Rust spans were converted to LSP ranges, they could underflow resulting in very large line numbers. As an underflow is always wrong, prevent it and use 0 instead.
This was noticed when opening an empty file in `src/bin/` of a library crate. In this case rustc produces a span with `"line_start": 0, "line_end": 0` resulting in the underflow.
> fix: Prevent underflow in range conversion 

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/generated_config.adoc
- editors/code/package.json
Playing around with [helix](https://helix-editor.com) I realized that the global worksapce symbol search works different compared to vs-code.
Helix requires all possible symbols in one query and does no subsequent refinement searched.
This PR adds a configuration option to override the default search limit with the default being the currently hardocded value.
Helix users can increment this limit for their instance with a config like
```toml
[[language]]
name = "rust"
language-server = { command = "rust-analyzer" }
[language.config]
workspace = { symbol = { search = { limit = 65536 }}}
```
Other editors are not affected by this change.
> Allow clients to configure the global workspace search limit

- crates/ide_assists/src/handlers/unnecessary_async.rs
- crates/ide_assists/src/lib.rs
- crates/ide_assists/src/tests/generated.rs
This should fix #11392 
This PR adds a quickfix on functions marked with `async` that suggests, if and only if no `await` expression in find in the body of the function (it relies on `SyntaxNode::descendants()` to recursively traverse blocks), to remove the `async` keyword.
The lint is made so that it triggers only if the cursor is not in the body of the function, so that it does not pollute the quickfix list.
It does not trigger a diagnostic. I don't know if this repository is the place to implement those (`clippy`?). If it is, I would very much like pointers on where to start looking.
If there are test cases I haven't thought about, please do suggest.
> feat: assist to remove unneeded `async`s

- crates/ide_db/src/imports/insert_use.rs
- crates/ide_db/src/imports/insert_use/tests.rs
The logic for importing with and without `group_imports` differed
significantly when no previous group existed. This lead to the problem
of using the wrong position when importing inside a module (#11585) or
when inner attributes are involved.
The existing code for grouped imports is better and takes these things
into account.
This PR changes the flow to use the pre-existing code for adding a new
import group even for the non-grouped import settings.
Some coverage markers are updated and the `group` is removed, since they
are now invoked in both cases (grouping and no grouping).
Tests are updated and two tests (empty module and inner attribute) are
added.
Fixes #11585
> Fix: Select correct insert position for disabled group import

- crates/ide_completion/src/render/function.rs
Addresses #11892 
Changes function argument completion to cover a case like this:
```rust
struct Foo { bar: i32 }
fn qux(Foo { bar }: Foo) {
println!("{bar}");
}
```
When completing the function call for `qux`, instead of expanding to `qux(_)`, it will now expand to `qux(foo)` (based on the snake-cased version of the name of the ADT)
Non ADTs are unaffected
> complete pattern args based on type name

- crates/hir_ty/src/diagnostics/match_check.rs
- crates/ide_diagnostics/src/handlers/missing_match_arms.rs
Match checking does not expect patterns of `TyKind::FnDef` type.
It seems that in _rustc_ match checking is ruled out due to such type errors at the typecheck stage.
Spotted in #11319
> fix: Skip match check on patterns of unexpected TyKind::FnDef

- crates/flycheck/src/lib.rs
I have commented on this [S-unactionable issue](https://github.com/rust-analyzer/rust-analyzer/issues/6589) that the Flycheck error message should maybe provide a hint about what tool it actually runs. Searching on some places on the Internet I've found multiple people, including myself, losing copious amounts of time on the same issue. So I've decided to make this very small PR :-)
From an user experience standpoint, the current error message is unhelpful to the end user, because the end user does not know exactly what it needs to check/fix (outdated, broken, or missing `cargo clippy`). In my own case, `cargo clippy` was actually missing altogether (developing off `rust:1.59.0-bullseye` official Docker image).
Thanks in advance!
> Better error message on Flycheck Error message (from: unactionable error message if we are using `clippy` as the checker)

- crates/hir/src/source_analyzer.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_general.html
- crates/ide/src/syntax_highlighting/tests.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/10707
bors r+
> fix: Fix path qualifiers not resolving generic type params when shadowed by trait

- crates/hir/src/source_analyzer.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/ide/src/syntax_highlighting/test_data/highlight_general.html
- crates/ide/src/syntax_highlighting/tests.rs
While we don't support const args in type inference yet, we can at least
make use of the fallback path resolution to resolve paths in const args
in the IDE layer to enable some features for them.
bors r+
> fix: Attempt to resolve paths in const arguments heuristically in IDE layer

- Cargo.lock
- crates/hir_def/Cargo.toml
- crates/hir_def/src/data.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
Previously we didn't do this because it didn't pull its weight, but now we actually do some bitops
bors r+
> internal: Use bitflags for `FnFlags`

- crates/hir/src/display.rs
- crates/hir_ty/src/display.rs
Saves slightly over 3 KB of `text`, but comparing the total with that from two weeks ago in #11776, this is a losing battle (we're 951 KB larger).
```
text	   data	    bss	    dec	    hex	filename
24693512	1542704	   4424	26240640	1906680	rust-analyzer-baseline
24690216	1542112	   4424	26236752	1905750	rust-analyzer-pr
```
> internal: Add and use `HirFormatter::write_{str,char}`

- crates/hir/src/display.rs
- crates/hir/src/lib.rs
- crates/hir_def/src/data.rs
- crates/hir_def/src/item_tree.rs
- crates/hir_def/src/item_tree/lower.rs
- crates/hir_def/src/item_tree/tests.rs
- crates/hir_ty/src/diagnostics/unsafe_check.rs
- crates/hir_ty/src/infer.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/utils.rs
- crates/ide/src/syntax_highlighting/highlight.rs
- crates/ide_completion/src/render/function.rs
Resolves some FIXMEs.
I've also renamed some FnFlags to be more explicit about what they represent (presence of keywords, not necessarily presence of semantics)
bors r+
> internal: move function unsafety determination out of the ItemTree

- crates/hir_ty/src/builder.rs
- crates/hir_ty/src/consteval.rs
- crates/hir_ty/src/infer/expr.rs
- crates/hir_ty/src/lib.rs
- crates/hir_ty/src/lower.rs
- crates/ide_diagnostics/src/handlers/type_mismatch.rs
fix #11913 
We should emit type_mismatch in const generics, probably after #7434. Currently they will lead to a misleading, time of use type error (like the added test).
> Consider types of const generics

- crates/hir_ty/src/lower.rs
- crates/hir_ty/src/tests/regression.rs
- `T: ~const Drop` has a special meaning in Rust 1.61 that we don't implement. (So ideally, we'd only ignore `~const Drop`, but this should be fine for now.)
- `Destruct` impls are built-in in 1.62 (current nightlies), so until the builtin impls are supported by Chalk, we ignore them as well. Since `Destruct` is implemented for everything in non-const contexts IIUC, this should also work fine.
Fixes #11932.
> Ignore `Drop` and `Destruct` bounds for now

- crates/hir/src/semantics/source_to_def.rs
- crates/ide_assists/src/handlers/inline_local_variable.rs
Fixes https://github.com/rust-analyzer/rust-analyzer/issues/11941
> fix: Don't create `hir::Local`s from const path patterns

- crates/hir_ty/src/tests/regression.rs
- crates/hir_ty/src/utils.rs
Signed-off-by: Alex Chi <iskyzh@gmail.com>
This is still a workaround on GAT panic, and didn't solve the full problem. But at least we won't panic now. False positive is better than panicking and letting VSCode constantly pop out the warning 🤣
This PR is simple -- only apply the https://github.com/rust-analyzer/rust-analyzer/pull/11878 fix on const generics. For normal GATs, just follow the previous approach.
This PR fixes https://github.com/rust-analyzer/rust-analyzer/issues/11939, I've added it as a test case.
This PR didn't fully fix / https://github.com/rust-analyzer/rust-analyzer/issues/11923. But at least it won't panic now -- will only give a type mismatch error.
Not sure if it fixes / https://github.com/rust-analyzer/rust-analyzer/issues/11921, I'll test it later.
cc @flodiebold …
> fix panic on GAT

- crates/hir_expand/src/db.rs
- crates/project_model/src/workspace.rs
- crates/rust-analyzer/src/main_loop.rs
Something very fishy is going on with the `rustc_workspace` handling, which caused this bug to only manifest in the `std` library but not other library crate... So there is either a bug there or just the fact that we seem to add duplicate dependencies (I think this is what we are doing with this right?) might be tripping something up somewhere.
cc https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Rust-analyzer.20use.20inside.20stdlib
bors r+
> internal: Show more project building errors to the user

- crates/ide/src/rename.rs
- crates/ide_assists/src/tests.rs
- crates/ide_db/src/rename.rs
- crates/ide_db/src/source_change.rs
- crates/rust-analyzer/src/to_proto.rs
fix: #10992
Added `FileSystemEdit::MoveDir` variant for move dirs. Original implemented as recursively move child mod files but had many issues like
1. left empty dir after rename file
2. only affect rust file
3. not performant
so changed to current version
> fix(ide): move moudle directory when rename

- crates/project_model/src/build_scripts.rs
- crates/project_model/src/cargo_workspace.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
I have tested this locally and it fixed #9201 with some small changes on the compiler side with suggestions from https://github.com/rust-analyzer/rust-analyzer/issues/9201#issuecomment-1019554086.
I have also added an environment variable `IS_RA_BUILDSCRIPT_CHECK` for crates to detect that it is a check for buildscripts, and allows defaulting to bogus values for expected environment variables.
> feat: allow customizing the command for running build scripts

- crates/hir_def/src/item_tree/pretty.rs
- crates/hir_def/src/item_tree/tests.rs
Expand `FnFlags` into what they actually mean and omit `AttrId`s, since those are sequential numbers in the item tree
> internal: Improve ItemTree pretty print output

- crates/ide/src/typing.rs
This does have a false positive to keep in mind, it will add a trailing `;` in the following snippet too, which is probably not desired:
```rust
fn is_zero(i: i32) -> bool {
i $0 0
}
```
However, that function is unlikely to be written from the "inside out" like that, so it might be acceptable. Typically `=` is only inserted last when the author realizes that an existing expression should be assigned to some variable.
> feat: Add trailing `;` when typing `=` in assignment

- crates/hir_def/src/builtin_type.rs
- crates/hir_def/src/resolver.rs
- crates/hir_ty/src/tests/method_resolution.rs
Closes https://github.com/rust-analyzer/rust-analyzer/issues/6082
> fix: resolve `uN::method` even when `use std::uN;` is present

- crates/ide_completion/src/completions/keyword.rs
- crates/ide_completion/src/tests/expression.rs
fixes https://github.com/rust-lang/rust-analyzer/issues/11576
> fix: enable ADT keyword completions in block expressions

- crates/hir/src/semantics.rs
- crates/ide/src/references.rs
- crates/ide/src/runnables.rs
cc https://github.com/rust-lang/rust-analyzer/issues/11668
> fix: Do reference search on all downmapped tokens with the same kind only

- crates/rust-analyzer/src/global_state.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/11357
> fix: Fix source root panic in global state when checking out older git revs

- docs/user/manual.adoc
- editors/code/src/commands.ts
- editors/code/src/config.ts
> fix: Remove old inlay hints settings

- crates/hir/src/lib.rs
- crates/ide_assists/src/handlers/extract_function.rs
- crates/ide_completion/src/render/function.rs
- crates/ide_completion/src/tests/expression.rs
Fix: completion detail shows `{unknown}` for `impl Trait` in return position.
Fix #11438 : completion detail shows `{unknown}` for return types in async functions.
Add `hir::Function::async_ret_type` method
> fix: completion detail shows `{unknown}` for async functions and for RPITs

- crates/parser/src/grammar/generic_args.rs
- crates/parser/test_data/parser/inline/ok/0200_assoc_const_eq.rast
- crates/parser/test_data/parser/inline/ok/0200_assoc_const_eq.rs
- crates/syntax/rust.ungram
- crates/syntax/src/ast/generated/nodes.rs
This pr fixes #11965.  The parser now allows eq constraints on associated constants.  
I've added tests for `HasCount<Count = {N}>` and `HasCount<Count = 0>`
> fix: support `associated_const_equality` in parser

- crates/ide_completion/src/context.rs
- crates/ide_completion/src/tests/attribute.rs
fixes #12019 
The immediate reason is that when we are doing derive completion, [`ctx.existing_derives`](https://github.com/rust-lang/rust-analyzer/blob/d1f6b4e2a0ab1a1343ab4a381c89b186a76fd001/crates/ide_completion/src/completions/attribute/derive.rs#L82) is empty, this is because we expand the macro when looking for the ancestors of the token to be completed. Take the following code as an example, we find the first `SyntaxNode` with kind `Attr` based on the ancestors of the token, but the parent of `Attr` is not a `Struct` as we [expect](https://github.com/rust-lang/rust-analyzer/blob/d1f6b4e2a0ab1a1343ab4a381c89b186a76fd001/crates/hir/src/semantics.rs#L518).  
```rust
#[derive(PartialEq, Eq, Or$0)]
struct S;
```
The ancestors of the token to be completed above.
```
NAME_REF@24..26 …
```
> derive completions take existing derives into count

- editors/code/package.json
- editors/code/src/commands.ts
Closes #12036
CC https://github.com/rust-lang/rust-analyzer/issues/12027#issuecomment-1102990324
The key was left there by mistake in #12006.
Setting the configuration scope only works if you already have it created, which is fine, but unfortunately not quite discoverable.
> fix: Remove `rust-analyzer.inlayHints.enable` and set language scope

- crates/hir_def/src/db.rs
- crates/hir_def/src/find_path.rs
We already did this if `#![no_std]` was present, this PR makes it work with `#![cfg_attr(not(test), no_std)]` too, which is very common in libraries.
Fixes https://github.com/rust-lang/rust-analyzer/issues/12035
cc https://github.com/rust-lang/rust-analyzer/issues/10718
> feat: prefer core/alloc over std in auto-imports if `#[no_std]` is conditional

- crates/project_model/src/workspace.rs
I believe this fixes #12043, but I'm not sufficiently setup/familiar with working on rust-analyzer to test it locally. :/
This section of code is iterating on `rustc_workspace.packages()` but then indexes `cargo[pkg]`, which is likely the source of the bug.
> fix: index the correct CargoWorkspace with rustc_private

- crates/ide_completion/src/completions/fn_param.rs
- crates/ide_completion/src/render/function.rs
- crates/ide_completion/src/tests/fn_param.rs
fix https://github.com/rust-lang/rust-analyzer/issues/12016 and handles some extra cases.
> fix: Improve parameter completion

- docs/dev/README.md
Just noticed the docs links broken. The current doc link was broken. replaced with the updated version as found on the front page. Should the rest of the links be updated?
> [Documentation]: Update developer documentation link.

- crates/hir_expand/src/lib.rs
- crates/ide_assists/src/handlers/generate_function.rs
- crates/ide_assists/src/handlers/inline_call.rs
- crates/ide_db/src/search.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12050
> fix: Fix `ide_db::search` not searching bodies of attributed items

- crates/rust-analyzer/src/dispatch.rs
Clarify that the server is a whole is OK, and that it's only a single
requests that's dead
> minor: clarify error message

- crates/ide_completion/src/item.rs
- crates/ide_completion/src/render.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12068
> Reduce priority of flyimport completions

- crates/ide_completion/src/completions/snippet.rs
This PR changes the `macro_rules!` snippet to use spaces instead of tabs. 
The other snippets like [this one][test-snippet] already use spaces.
The snippet was introduced in 5575588 where no reason is provided to use tabs.
[test-snippet]: https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide_completion/src/completions/snippet.rs#L70=
> Change tabs to spacs in macro_rules snippet

- crates/ide/src/signature_help.rs
> fix: `signature_help`: use corresponding param list for methods

- crates/ide_completion/src/completions/fn_param.rs
- crates/ide_completion/src/render/function.rs
- crates/ide_completion/src/tests/fn_param.rs
> fix: fn_param completion lookup

- crates/ide/src/runnables.rs
Closes #11725
#11490 was a little misguided. Quoting the test name should be a client concern, since it's the client that actually runs `cargo`.
> Revert #11490

- crates/ide_completion/src/completions/snippet.rs
- crates/ide_completion/src/tests/expression.rs
fixes https://github.com/rust-lang/rust-analyzer/issues/12092
> fix: show `macro_rules` snippet in blocks

- .github/workflows/ci.yaml
- .github/workflows/metrics.yaml
- .github/workflows/publish.yml
- .github/workflows/release.yaml
- .github/workflows/rustdoc.yaml
The v2 implementation uses Node 12, which is end-of-life on April 30, 2022. See https://nodejs.org/en/about/releases/. Update to v3, which is based on Node 16 whose support lasts until April 30, 2024.
They made this a major version change (v2 to v3) because old GitHub Enterprise versions aren't necessarily compatible with Node 16, but for github.com-supplied runners (SaaS) there is no practical difference.
> Update GitHub Actions actions/checkout@v2 to v3

- crates/ide-completion/src/completions/record.rs
> feat: provide Self in record literal completion

- crates/parser/src/lexed_str.rs
Makes it easier to produce multiple tokens from a single rustc token, if that's how we want to approach https://github.com/rust-analyzer/rust-analyzer/issues/1109
> internal: Add a `Converter` type for token conversion

- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/tests/traits.rs
Collect obligations from RPITs (Return Position `impl Trait`) of a function which is being inferred.
This allows inferring {unknown}s from RPIT bounds.
Closes #8403
> infer from RPIT bounds of _this_ function

- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_fields.rs
- crates/syntax/src/ast/make.rs
Instead of filling a boolean field with `bool::default()` it's not `false` and same for `Option` instead of using `Option::default()` it will be `None`
> improve the default constructor mode when filling fields

- crates/hir-def/src/attr.rs
- crates/hir/src/lib.rs
- crates/ide/src/doc_links.rs
- crates/ide/src/hover/tests.rs
fix: #12033
I did some debugging and found the cause looks like to be some doc links' `LinkType` are kept as `Shortcut` which don't make sense for url links.
This PR should resolve both problems in the origin issue, but aside this PR, more work are needed for doc_links.
about `LinkType`: https://github.com/raphlinus/pulldown-cmark/blob/f29bd1e228913690e5092c9594e4e607423ff0aa/src/lib.rs#L191-L210
> fix: doc url link type

- crates/hir-def/src/body/lower.rs
- crates/ide/src/hover/tests.rs
- crates/rust-analyzer/src/lib.rs
- crates/syntax/src/ast/expr_ext.rs
- crates/syntax/src/ast/generated/tokens.rs
- crates/syntax/src/ast/token_ext.rs
- crates/syntax/src/tests/sourcegen_ast.rs
- crates/syntax/src/validation.rs
> feat: Lower values of char and byte literals

- crates/hir-def/src/macro_expansion_tests/mbe/meta_syntax.rs
- crates/hir-def/src/macro_expansion_tests/mbe/tt_conversion.rs
- crates/mbe/src/syntax_bridge.rs
- crates/mbe/src/tt_iter.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12170
The parser tells us to consume up to 3 tokens, but on the MBE side all float literals are a single `tt::Literal`, so make sure to only consume a single MBE leaf.
> fix: fix macro expansion with float tokens

- crates/hir-def/src/macro_expansion_tests/mbe/tt_conversion.rs
- crates/mbe/src/syntax_bridge.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12170 (num-traits no longer causes a panic)
> fix: Fix panic when a macro passes a float token to another macro

- crates/parser/src/grammar.rs
- crates/parser/test_data/parser/inline/ok/0011_field_expr.rast
`NameRef`s should only contain integers and identifiers
cc https://github.com/rust-lang/rust-analyzer/pull/12149
> fix: Remap float parts as integers when parsed as indices

- crates/hir-def/src/builtin_attr.rs
- crates/ide-completion/src/render.rs
This should be merged along with rust-lang/rust#95960.
Because the attribute still exists in rustc, I've left the definition here. With that said, any use of it is an error, so I've removed any handling of `#[rustc_deprecated]`.
> Remove handling of `#[rustc_deprecated]`

- crates/hir/src/lib.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/tests/type_pos.rs
- crates/ide-db/src/defs.rs
- crates/ide/src/goto_definition.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12166
> fix: Resolve assoc. types of supertraits in the IDE layer

- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/tests/type_pos.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12165
> fix: Don't show assoc. type binding completions when invalid

- crates/ide/src/signature_help.rs
Closes  #12200 
Regressed from #12082
> fix: don't panic at fully qualified call syntax in signature help

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
The description said the same thing twice: "trailing colons for parameter hints, and trailing colons for parameter hints".
I'm assuming one of those is supposed to be about the leading colon for type hints.
Also, I wasn't sure how to regenerate the generated file(s?) so I just manually updated them. Hopefully that isn't a problem. If how to do that is in the documentation somewhere I'd love to know.
> Fix a typo in the `inlayHints.renderColons` option description

- editors/code/package.json
The semantic token type for character literals is called `character`:
https://github.com/rust-lang/rust-analyzer/blob/94fa8a6534cf93276ad7e205026402f24d41a0b2/crates/rust-analyzer/src/semantic_tokens.rs#L51
and yet the definition in `package.json` uses `char`. In practice this means trying to highlight `char` doesn’t have any effect, while `character` doesn’t have any hover documentation and doesn’t appear in autocomplete. The definition also defines the fallback semantic token type as `type`; luckily since it currently references the non-existent `char` this doesn’t have any effect, since it doesn’t really make sense to highlight character literals as types.
This PR fixes the definition in `package.json` to correctly reference `character`, and also defines the fallback type as `number`. …
> Fix `character` semantic token type definition

- editors/code/package-lock.json
- editors/code/package.json
- editors/code/src/client.ts
- editors/code/src/config.ts
- editors/code/tests/runTests.ts
- editors/code/tests/unit/index.ts
- editors/code/tests/unit/settings.test.ts
Currently support a subset of [variables provided by VSCode](https://code.visualstudio.com/docs/editor/variables-reference) in `server.extraEnv` section of Rust-Analyzer settings:
* `workspaceFolder`
* `workspaceFolderBasename`
* `cwd`
* `execPath`
* `pathSeparator`
Also, this PR adds support for general environment variables resolution. You can declare environment variables and reference them from other variables like this:
```JSON
"rust-analyzer.server.extraEnv": {
"RUSTFLAGS": "-L${env:OPEN_XR_SDK_PATH}",
"OPEN_XR_SDK_PATH": "${workspaceFolder}\\..\\OpenXR-SDK\\build\\src\\loader\\Release"
},
```
The order of variable declaration doesn't matter, you can reference variables before defining them. If the variable is not present in `extraEnv` section, VSCode will search for them in your …
> feat: Support variable substitution in VSCode settings

- crates/ide/src/annotations.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/to_proto.rs
cc https://github.com/rust-lang/rust-analyzer/issues/12221
> internal: Remove redundant offset data in annotations

- crates/rust-analyzer/src/diagnostics/test_data/rustc_range_map_lsp_position.txt
- crates/rust-analyzer/src/diagnostics/to_proto.rs
- crates/rust-analyzer/src/main_loop.rs
> fix cargo check diagnostics are mapped incorrectly with non-BMP codepoints

- crates/ide-db/src/syntax_helpers/insert_whitespace_into_node.rs
> ide: insert whitespace between 'mut' and 'self' in macro expansion

- crates/hir-ty/src/diagnostics/match_check.rs
- crates/hir-ty/src/infer.rs
- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/lib.rs
- crates/hir/src/lib.rs
- crates/hir/src/semantics.rs
- crates/hir/src/source_analyzer.rs
- crates/ide/src/inlay_hints.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/to_proto.rs
- crates/syntax/src/ast/expr_ext.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> feat: Add binding mode inlay hints

- crates/hir/src/lib.rs
- crates/ide-assists/src/handlers/generate_documentation_template.rs
- crates/ide-assists/src/handlers/generate_getter.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-assists/src/utils.rs
The assist can now turn this:
```rust
pub struct S;
impl S {
pub fn data_mut$0(&mut self) -> &mut [u8] { &mut [] }
}
```
into
```rust
pub struct S;
impl S {
/// Returns a mutable reference to the data.
///
/// # Examples
///
/// ```
/// use test::S;
///
/// let mut s = ;
/// assert_eq!(s.data_mut(), );
/// assert_eq!(s, );
/// ```
pub fn data_mut(&mut self) -> &mut [u8] { &mut [] }
}
```
And similarly for by-value or immutable getters, and for setters. Previously the intro line would be empty.
This PR also removes the documentation generation function from the "Generate getter/setter" assist, since that is better handled by applying the 2 assists in sequence. cc https://github.com/rust-lang/rust-analyzer/issues/12273
> feat: Handle getters and setters in documentation template assist

- crates/ide-assists/src/handlers/generate_setter.rs
- crates/ide-assists/src/tests/generated.rs
Followup to https://github.com/rust-lang/rust-analyzer/pull/12274
> fix: Don't generate documentation in `generate_setter`

- crates/ide-assists/src/handlers/generate_deref.rs
- crates/ide-assists/src/tests.rs
- crates/ide-assists/src/tests/generated.rs
- crates/ide-db/src/famous_defs.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12265
Fixes https://github.com/rust-lang/rust-analyzer/issues/12266
The assist will now generate a `DerefMut` impl if a `Deref` impl is already present.
> feat: Improve "Generate `Deref` impl" assist

- .editorconfig
- .git-blame-ignore-revs
- editors/code/.eslintrc.js
- editors/code/.prettierignore
- editors/code/.prettierrc.js
- editors/code/language-configuration.json
- editors/code/package-lock.json
- editors/code/package.json
- editors/code/ra_syntax_tree.tmGrammar.json
- editors/code/src/ast_inspector.ts
- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/config.ts
- editors/code/src/ctx.ts
- editors/code/src/debug.ts
- editors/code/src/lsp_ext.ts
- editors/code/src/main.ts
- editors/code/src/persistent_state.ts
- editors/code/src/run.ts
- editors/code/src/snippets.ts
- editors/code/src/tasks.ts
- editors/code/src/toolchain.ts
- editors/code/src/util.ts
- editors/code/tests/runTests.ts
- editors/code/tests/unit/index.ts
- editors/code/tests/unit/launch_config.test.ts
- editors/code/tests/unit/runnable_env.test.ts
- editors/code/tests/unit/settings.test.ts
- editors/code/tsconfig.eslint.json
- editors/code/tsconfig.json
1. Added [`.editorconfig` file](https://editorconfig.org) to dictate general hygienic stuff like character encoding, no trailing whitespace, new line symbols etc. for all files (e.g. Markdown). Install an editor plugin to get this rudimentary formatting assistance automatically. Prettier can read this file and, for example, use it for indentation style and size. 
2. Added a minimal prettier config file. All options are default except line width, which per [Veykril](https://github.com/Veykril) suggestion is set to 100 instead of 80, because [that's what `Rustfmt` uses](https://rust-lang.github.io/rustfmt/?version=v1.4.38&search=#max_width). 
3. Change `package.json` to use Prettier instead of `tsfmt` for code formatting. 
4. Performed initial formatting in a separate commit, per …
> Switch to Prettier for TypeScript Code formatting

- crates/ide-assists/src/handlers/convert_let_else_to_match.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
> Turn let-else statements into let and match

- editors/code/src/client.ts
- editors/code/src/commands.ts
- editors/code/src/main.ts
While VSCode [uses it's own implementation for URIs](https://github.com/microsoft/vscode-uri)
which notably doesn't have any limits of URI size, the renderer itself
relies on Web platform engine, that limits the length of the URLs and
bails out when the attribute length of an `href` inside `a` tag is too
long.
Command URIs have a form of `command:command-name?arguments`, where
`arguments` is a percent-encoded array of data we want to pass along to
the command function. For "Show References" this is a list of all file
URIs with locations of every reference, and it can get quite long.
This PR introduces another intermediary `linkToCommand` command. When
we render a command link, a reference to a command with all its arguments
is stored in a map, and instead a `linkToCommand` link is …
> "Show implementations" link display error fix

- crates/ide-assists/src/handlers/generate_documentation_template.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
- Split into 2 assists: one generates basic docs structure, but no example, one generates an example
- Fix section ordering (the example comes last)
- Allow generating docs for private functions
- Expand `len` to `length` when generating an intro sentence
> feat: Improve docs generation assist

- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
> Removed duplicate 'to' in `cachePriming.numThreads` option description

- crates/ide/src/inlay_hints.rs
> Hide closure ret hints if ret type is specified

- crates/ide/src/inlay_hints.rs
- crates/ide/src/static_index.rs
- crates/rust-analyzer/src/config.rs
- docs/user/generated_config.adoc
- editors/code/package.json
This PR adds an option to hide the inlay hints for `let IDENT_PAT = CLOSURE_EXPR;`, which is a somewhat common coding pattern. Currently the inlay hints for the assigned variable and the closure expression itself are both displayed, making it rather repetitive.
In order to be consistent with closure return type hints, only closures with block bodies will be hid by this option.
Personally I'd feel comfortable making it always enabled (or at least when closure return type hints are enabled), but considering the precedent set in #10761, I introduced an off-by-default option for this.
changelog feature: option to hide type inlay hints for `let` statements that initialize to a closure
> feat: hide type inlay hints for initializations of closures

- editors/code/src/tasks.ts
We've had a couple of common presets in `Tasks: Run Task -> cargo -> cargo [check,build,test,...]` before. This PR adds `cargo clippy` to that list, which makes for a convenient way of occasionally running Clippy on your code without having to reconfigure the Check on Save command to clippy.
These presets all use the `cargo` task type that we provide, so diagnostics will show up in the editor. However, they don't go through the server-side parsing logic, so it's not possible to apply suggestions, and diagnostics are fairly "low-fidelity". It would be cool if we could somehow pass Cargo's JSON output through the LSP server and render it properly, for arbitrary tasks.
cc https://github.com/rust-lang/rust-analyzer/issues/12323
> feat: Add "cargo clippy" task preset

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/body/scope.rs
- crates/hir-def/src/expr.rs
- crates/hir-ty/src/infer/expr.rs
They're never really called "Lambda"s in Rust, so let's call them "Closures" consistently.
> internal: Rename `Expr::Lambda` to `Expr::Closure`

- crates/hir-ty/src/traits.rs
TBC:
- #12279: ok above 480
- ~~#12182~~
- ~~#12095~~
- #11902: ok above 350
- ~~#11668~~
- #11370: ok above 450
- #9754: probably ok above 250 (!), and the code in cause and branch are gone
Closes #12279
Closes #11902
Closes #11370
Closes #9754
> Increase defalt chalk overflow depth to match max solver size

- crates/ide-assists/src/handlers/generate_enum_variant.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/lib.rs
- crates/ide-assists/src/tests/generated.rs
So, this is kind of a weird PR!
I'm a complete newcomer to the `rust-analyzer` codebase, and so I browsed the "good first issue" tag, and found #11635. Then I found two separate folks had taken stabs at it, most recently @maartenflippo — and there had been a review 3 days ago, but no activity in a little while, and the PR needed to be rebased since the crates were renamed from `snake_case` to `kebab-case`.
So to get acquainted with the codebase I typed this PR by hand, looking at the diff in #11995, and I also added a doc-test (that passes).
I haven't taken into account the comments @Veykril left in #11995, but I don't want to steal any of @maartenflippo's thunder! Closing this PR is perfectly fine. Or Maarten could use it as a "restart point"? Or I could finish it up, whichever feels …
> Generate enum variant assist

- Cargo.lock
- crates/vfs-notify/Cargo.toml
notify-5.0.0-pre.14 does not build on these systems; this was fixed in
https://github.com/notify-rs/notify/commit/41a74f0e98a1af386749ad3be4a197865054f17f , which landed in pre.15.
> Fix build on OpenBSD (and probably other BSDs too)

- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/tests/patterns.rs
This should fix the following issue:  https://github.com/rust-lang/rust-analyzer/issues/12331
* Replaced the `err_ty` in `infer_pat()` with a new type variable.
* Had to change the iterator code a bit, to get around multiple mutable borrows of `self` in `infer_pat()`.
Also added a test 
* Also added a test
> Fix inference when pattern matching a tuple field with a wildcard

- crates/hir/src/semantics.rs
- crates/ide/src/hover.rs
- crates/ide/src/references.rs
- crates/syntax/src/ast/node_ext.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/11668
> fix: When reference searching macro inputs, don't search everything that was downmapped

- .github/workflows/release.yaml
CC https://github.com/microsoft/vscode/issues/149518#issuecomment-1134782535
> internal: Try to publish the universal VSIX before the other ones

- editors/code/package.json
- editors/code/src/config.ts
fixes #12363 by bringing the types more inline with the reality, and making `Env` not a lie.
> vscode: fix extraEnv handling numeric values

- crates/ide/src/lib.rs
- crates/ide/src/typing.rs
- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/generated_config.adoc
- editors/code/package.json
cc https://github.com/rust-lang/rust-analyzer/issues/12379
> internal: Make autoclosing angle brackets configurable, disabled by default

- crates/rust-analyzer/src/config.rs
- crates/rust-analyzer/tests/slow-tests/main.rs
There's a small issue because if all projects are excluded, this: https://github.com/rust-lang/rust-analyzer/blob/01d412f4d7bd7ef21a7e8f0461e9ba3439e3c4bf/crates/rust-analyzer/src/main_loop.rs#L114 will be shown.
I thought about not showing it if `files.excludeDirs` is set, but that is not necessarily correct.
Fixes #7755
> make `files.excludeDirs` work

- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/expr.rs
- crates/ide/src/hover/tests.rs
- crates/syntax/src/ast/token_ext.rs
> fix: f32 and f64 representation during lowering

- crates/hir-ty/src/infer/pat.rs
- crates/hir-ty/src/tests/regression.rs
The following code causes integer overflow during type inference for (malformed) tuple struct patterns.
```rust
struct S(usize);
let S(.., a, b) = S(1);
```
It has been panicking only in debug builds, and working in a way in release builds but it was inconsistent with type inference for tuple patterns:
```rust
struct S(usize);
let S(.., a, b) = S(1); // a -> unknown, b -> usize
let (.., a, b) = (1,);  // a -> usize, b -> unknown
```
With this PR, the overflow no longer happens by utilizing `saturating_sub()` like in other places and type inference for tuple struct patterns is in line with that for tuple patterns.
> fix overflow during type inference for tuple struct patterns

- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/tests.rs
- crates/ide-completion/src/tests/fn_param.rs
- crates/ide-completion/src/tests/visibility.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/caps.rs
- crates/rust-analyzer/src/handlers.rs
- crates/rust-analyzer/src/integrated_benchmarks.rs
close #12390
This PR add `(` to trigger_characters as discussed in original issue.
Some questions:
1. Is lsp's `ctx.trigger_character` from `params.context` is the same as `ctx.original_token` inside actually completions? 
1. If not what's the difference?
2. if they are the same, it's unnecessary to pass it down from handler at all.
3.  if they are the same, maybe we could parse it from fixture directly instead of using the `check_with_trigger_character` I added.
2. Some completion fixtures written as `($0)` ( https://github.com/rust-lang/rust-analyzer/blob/master/crates/ide-completion/src/tests/fn_param.rs#L105 as an example), If I understand correctly they are not invoked outside tests at all?
1. using `ctx.original_token` directly would break these tests as well as parsing …
> fix: Retrigger visibility completion after parentheses

- crates/hir/src/has_source.rs
- crates/ide-db/src/rename.rs
- crates/ide/src/rename.rs
Fixes a bug where rust-analyzer would emit `WorkspaceEdit`s with paths to dirs instead of files for the following project layout. 
lib.rs
```rust
mod foo;
```
foo.rs
```rust
mod bar {
struct Bar;
}
```
Also fixes emitted paths for modules with mod.rs.
The bug resulted in panic in helix editor when attempting to rename a module.
> fix(ide-db): correct single-file module rename

- crates/ide-completion/src/completions/item_list.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/completions/snippet.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/lib.rs
- crates/ide-completion/src/tests.rs
- crates/ide-completion/src/tests/fn_param.rs
- crates/ide-completion/src/tests/item.rs
- crates/ide-completion/src/tests/visibility.rs
- crates/ide/src/lib.rs
- crates/rust-analyzer/src/handlers.rs
Now we are unfortunately approaching the more complex cases for filtering completions where we have to deal with parser recovered nodes properly ...
> internal: More precise completion filtering with existing item qualifiers

- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/from_proto.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/main_loop.rs
- crates/rust-analyzer/src/task_pool.rs
With this PR we now retry requests if they get cancelled due to document changes.
This fixes the completions problem we have where completions seem to randomly disappear, see https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/Completions.20not.20always.20appearing 
Fixes https://github.com/rust-lang/rust-analyzer/issues/10187
Fixes https://github.com/rust-lang/rust-analyzer/issues/7560
Fixes https://github.com/rust-lang/rust-analyzer/issues/12153
> fix: Fix completions disappearing when typing two keys in quick succession

- crates/rust-analyzer/src/diagnostics/to_proto.rs
Use " " as message if it is empty
[discussion on zulip](https://rust-lang.zulipchat.com/#narrow/stream/185405-t-compiler.2Frust-analyzer/topic/empty.20diagnostic.20message)
> fix(diagnostic): Don't remove diagnostic with empty message

- crates/ide-assists/src/handlers/extract_module.rs
- Should solve #11766 
- While adding a test case for this issue, I observed another issue:
For this test case:
```rust
mod x {
pub struct Foo;
pub struct Bar;
}
use x::{Bar, Foo};
$0type A = (Foo, Bar);$0
```
extract module should yield this:
```rust
mod x {
pub struct Foo;
pub struct Bar;
}
use x::{};
mod modname {
use super::x::Bar;
use super::x::Foo;
pub(crate) type A = (Foo, Bar);
}
```
instead it gave:
```rust
mod x {
pub struct Foo;
pub struct Bar;
}
use x::{};
mod modname {
use x::Bar;
use x::Foo;
pub(crate) type A = (Foo, Bar);
}
```
So fixed this problem with second commit
> fix(extract_module) resolving import panics and improve import resolution

- crates/rust-analyzer/src/bin/main.rs
Linux effectively has a 15 byte limit, which resulted in `rust-analyzer s` and `rust-analyzer p`. That's still unambiguous, but probably not obvious.
> internal: Shorten main thread names

- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/hir-def/src/macro_expansion_tests/mbe/meta_syntax.rs
- crates/mbe/src/parser.rs
The implementation mirrors what `rustc` currently does [1]. Part of #11952.
\[1]: https://github.com/rust-lang/rust/blob/0595ea1d12cf745e0a672d05341429ecb0917e66/compiler/rustc_expand/src/mbe/quoted.rs#L230-L241
> feat: Support `$$` in macros.

- crates/ide-assists/src/handlers/merge_imports.rs
- crates/ide-db/src/imports/merge_imports.rs
The selected imports have to have a common prefix in paths.
Select imports or use trees to merge:
```rust
$0use std::fmt::Display;
use std::fmt::Debug;
use std::fmt::Write;$0
```
Apply `Merge imports`:
```rust
use std::fmt::{Display, Debug, Write};
```
Closes #12426
> feature: `Merge imports` assist can merge multiple selected imports.

- crates/ide-assists/src/handlers/auto_import.rs
Fixes #10337.
Basically we sort the imports according to how "far away" the imported item is from where we want to import it to. This change makes it so that imports from the current crate are sorted before any third-party crates. Additionally, we make an exception for builtin crates (`std`, `core`, etc.) so that they are sorted before any third-party crates.
There are probably other heuristics that should be added to improve the experience (such as preferring imports that are common elsewhere in the same crate, and ranking crates depending on the dependency graph). However, I think this is a first good step. 
PS. This is my first time contributing here, so please be gentle if I have missed something obvious :-)
> Order auto-imports by relevance

- crates/rust-analyzer/src/task_pool.rs
> Increase worker thread stack and name them

- editors/code/src/ctx.ts
Fixes https://github.com/rust-lang/rust-analyzer/issues/12469
> fix: Cleanup output channels when restarting server

- editors/code/src/client.ts
- editors/code/src/ctx.ts
- editors/code/src/main.ts
cc https://github.com/rust-lang/rust-analyzer/pull/12470
> internal: Keep output channels across restarts

- crates/proc-macro-srv/src/abis/abi_1_63/mod.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/buffer.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/client.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/closure.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/handle.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/mod.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/rpc.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/scoped_cell.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/selfless_reify.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/server.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/diagnostic.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/mod.rs
- crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/quote.rs
- crates/proc-macro-srv/src/abis/abi_1_63/rustc_server.rs
- crates/proc-macro-srv/src/abis/mod.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12489
This bumps the MSRV to 1.61 due to usage of function pointers and `impl Trait` in const functions.
<details>
<summary>Diff from upstream proc_macro as of rust-lang/rust@e45d9973b2665897a768312e971b82cc62633103 (misses lib.rs as it got renamed to mod.rs)</summary>
```diff
diff -u --recursive ../rust/library/proc_macro/src/bridge/client.rs crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/client.rs
--- ../rust/library/proc_macro/src/bridge/client.rs     2022-06-08 13:14:57.763123238 +0000
+++ crates/proc-macro-srv/src/abis/abi_1_63/proc_macro/bridge/client.rs 2022-06-08 13:33:23.378430287 +0000
@@ -430,27 +430,27 @@
buf
}
-impl Client<crate::TokenStream, crate::TokenStream> {
-    pub const fn expand1(f: impl …
```
> feat: Add proc macro ABI for rustc 1.63

- crates/ide/src/inlay_hints.rs
> minor: hide param inlay hint when argument is fn-like macro with similar name

- crates/ide-completion/src/render/literal.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/pattern.rs
- crates/ide-completion/src/tests/use_tree.rs
> fix: avoid adding enum parens in use path

- crates/ide-assists/src/handlers/inline_local_variable.rs
wrap reference for RefExpr initializer to fix #12453
> feat: fix inline variable produce mismatched type

- crates/rust-analyzer/build.rs
- crates/rust-analyzer/src/bin/main.rs
- crates/rust-analyzer/src/cli/lsif.rs
- crates/rust-analyzer/src/dispatch.rs
- crates/rust-analyzer/src/lib.rs
- crates/rust-analyzer/src/lsp_utils.rs
- crates/rust-analyzer/src/version.rs
- xtask/src/dist.rs
Inspired by how cargo handles it
Fixes https://github.com/rust-lang/rust-analyzer/issues/12280
> Bring the version command output in line with other rust tools

- docs/dev/style.md
Fix type `Ues` -> `Use` in `style.md`
> minor: Fix typo in style guide

- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/reload.rs
With this all proc-macros should resolve in rustc now when setting up the build script running command properly.
> fix: Pass the build data to rustc_private crates

- editors/code/package.json
Fixes a small typo in `package.json`.
> fix typo in package.json

- crates/ide-db/src/imports/insert_use.rs
- crates/ide-db/src/imports/insert_use/tests.rs
The current `insert_use` logic adds the first `use` item near the beginning of the file, only skipping past comments and whitespace. However, it does not skip leading [shebang lines](https://en.wikipedia.org/wiki/Shebang_\(Unix\)). This can produce a syntax error, as shebangs are only accepted (ignored) on the first line of the file.
```rust
#!/usr/bin/env rust
fn main() {}
```
```rust
use foo::bar::Baz;
#!/usr/bin/env rust
fn main() {}
```
Rust analyzer's grammar is already shebang-aware, so this PR just adds that to the array of SyntaxKinds that are skipped past when looking for an insertion location, and adds a corresponding test case.
> fix: inserted imports must come after a shebang if present

- crates/hir/src/source_analyzer.rs
- crates/ide-completion/src/tests/expression.rs
- crates/ide-completion/src/tests/type_pos.rs
fixes #11959 
> We get a Bar completion for the following snippet which is wrong as the item is not visible in that position.
> ``` rust
> fn foo() -> $0 {
>    struct Bar;
> }
> ```
I investigated the problem and found that the scope of the cursor offset, also `CompletionContext.scope` is the body of the function
> fix: local items should not be completed in parent signature

- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/completions/field.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/completions/item_list/trait_impl.rs
- crates/ide-completion/src/completions/keyword.rs
- crates/ide-completion/src/completions/postfix.rs
- crates/ide-completion/src/completions/record.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/completions/use_.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/patterns.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-completion/src/tests/record.rs
This gets rid of the remaining `ImmediateLocation` bits
> internal: More completions refactoring

- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/tests/pattern.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12592
> fix: Don't trigger pattern completions when typing a wildcard pattern

- crates/ide-completion/src/completions.rs
- crates/ide-completion/src/completions/attribute.rs
- crates/ide-completion/src/completions/attribute/derive.rs
- crates/ide-completion/src/completions/dot.rs
- crates/ide-completion/src/completions/expr.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/completions/item_list.rs
- crates/ide-completion/src/completions/pattern.rs
- crates/ide-completion/src/completions/record.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/completions/use_.rs
- crates/ide-completion/src/completions/vis.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/context/analysis.rs
- crates/ide-completion/src/item.rs
- crates/ide-completion/src/render.rs
- crates/ide-completion/src/render/function.rs
- crates/ide-completion/src/render/literal.rs
- crates/ide-completion/src/render/macro_.rs
- crates/ide-completion/src/tests/pattern.rs
- crates/rust-analyzer/src/to_proto.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/8058
> fix: Fix auto-ref completions inserting into wrong locations

- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
Don't analyze dependencies with `test`; this should fix various cases where crates use `cfg(not(test))` and so we didn't find things.
"Local" here currently means anything that's not from the registry, so anything inside the workspace, but also path dependencies. So this isn't perfect, and users might still need to use `rust-analyzer.cargo.unsetTest` for these in some cases.
> fix: Only apply `cfg(test)` for local crates

- crates/ide/src/doc_links.rs
- crates/ide/src/hover/tests.rs
fixes #12601
Looked like autolink/inline mismatch happened because end_link_type was parsed from the Text/Code events.
I changed it to be determined from the Start event, which should hopefully remain accurate while staying true to the cases where link type may need to be changed, according to the comment 
```
// normally link's type is determined by the type of link tag in the end event,
// however in some cases we want to change the link type, for example,
// `Shortcut` type doesn't make sense for url links
```
Hopefully this is the desired behavior?
> fix: doc_links link type - Determine link type at start (fixes #12601)

- Cargo.lock
- crates/hir-def/src/nameres/collector.rs
- crates/hir-expand/Cargo.toml
- crates/hir-expand/src/proc_macro.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/macro_error.rs
- crates/ide-diagnostics/src/handlers/unresolved_macro_call.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
Distinguish between
- there is no build data (for some reason?)
- there is build data, but the cargo package didn't build a proc macro dylib
- there is a proc macro dylib, but it didn't contain the proc macro we expected
- the name did not resolve to any macro (this is now an
unresolved_macro_call even for attributes)
I changed the handling of disabled attribute macro expansion to
immediately ignore the macro and report an unresolved_proc_macro,
because otherwise they would now result in loud unresolved_macro_call
errors. I hope this doesn't break anything.
Also try to improve error ranges for unresolved_macro_call / macro_error
by reusing the code for unresolved_proc_macro. It's not perfect but
probably better than before.
> fix: Improve proc macro errors a bit

- crates/flycheck/src/lib.rs
- crates/project-model/src/build_scripts.rs
- crates/stdx/src/lib.rs
- crates/stdx/src/process.rs
cc https://github.com/rust-lang/rust-analyzer/pull/10517/files#r895241975
> internal: Bring back JodChild into flychecking for cancellation

- crates/hir/src/source_analyzer.rs
- crates/ide-completion/src/context.rs
- crates/ide-completion/src/tests/special.rs
This doesn't fix the issue with completions not working correctly in attribute macros when completions for an empty token are requested though.
> fix: Fix completions for locals not working properly inside macro calls

- crates/hir-def/src/body.rs
- crates/hir-def/src/body/lower.rs
- crates/hir-def/src/nameres/collector.rs
- crates/hir-def/src/nameres/diagnostics.rs
- crates/hir-expand/src/lib.rs
- crates/hir-expand/src/proc_macro.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/unresolved_proc_macro.rs
- crates/project-model/src/tests.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/reload.rs
They didn't have a krate before, resulting in the generic "proc macro not found" error.
Also improve error messages a bit more.
> fix: Report proc macro errors in expressions correctly as well

- crates/hir-ty/src/diagnostics/expr.rs
- crates/hir-ty/src/diagnostics/match_check.rs
- crates/hir-ty/src/diagnostics/match_check/deconstruct_pat.rs
- crates/hir/src/diagnostics.rs
- crates/hir/src/lib.rs
- crates/ide-diagnostics/src/handlers/missing_match_arms.rs
Shamelessly copied from rustc. Thus reporting format is same.
This extends public api  `hir::diagnostics::MissingMatchArms` with `uncovered_patterns: String` field. It does not expose data for implementing a quick fix yet.
-----
Worth to note: current implementation does not give a comprehensive list of missing patterns. Also mentioned in [paper](http://moscova.inria.fr/~maranget/papers/warn/warn.pdf):
> One may think that algorithm I should make an additional effort to provide more
> non-matching values, by systematically computing recursive calls on specialized
> matrices when possible, and by returning a list of all pattern vectors returned by
> recursive calls. We can first observe that it is not possible in general to supply the
> users with all non-matching values, since the …
> feat: Show witnesses of non-exhaustiveness in `missing-match-arm` diagnostic

- editors/code/src/toolchain.ts
Just like `test`.
Fixes #12645.
I don't know how to test that.
> Ignore the `bin` artifact for `bench` targets

- crates/flycheck/src/lib.rs
> fix: Fix flycheck sending cancel progress with no running process

- crates/ide-db/src/syntax_helpers/insert_whitespace_into_node.rs
- crates/ide/src/expand_macro.rs
Fixes #12591 
The `=>` token in the macro_rules! should be parsed as one fat arrow, but it ["requires a lot of changes in r-a"](https://github.com/rust-analyzer/ungrammar/commit/143cc528b11290bf2463de1fb5a97a15f9b2ed44), so I left it for the larger refactoring in the future and put a FIXME note.
> fix: improve whitespace insertion in pretty printer

- crates/hir-def/src/data.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12669
> fix: Fix attribute macros on assoc items being discarded with disabled proc macros

- crates/hir-ty/src/infer/expr.rs
- crates/hir-ty/src/tests/coercion.rs
- crates/hir-ty/src/tests/simple.rs
This is a follow-up PR on #12428. I'm not sure if this is everything I overlooked, so if there are more things that are not right, we may want to revert #12428.
This should also fix the increase of the type mismatches and the unknown types in diesel in the [metrics](https://rust-analyzer.github.io/metrics/?start=2022-06-23&end=2022-07-01) introduced by #12428.
The regressions are:
- some coercions don't work in the ordinary (i.e. non-destructuring) assignments
In order for coercions on ADT fields instantiations to work, lhs type has to be known before inferring rhs. #12428 changed the inference order, making rhs inferred before lhs, breaking the coercion, so I restored the original inference mechanism for the ordinary assignments.
Note that this kind of coercion doesn't happen in …
> fix regressions on assignment expressions

- crates/ide-assists/src/handlers/extract_function.rs
This change fixes #10037, in more or less the most naive fashion
possible.
We continue to start with the hardcoded default of "fun_name", and now append a
counter to the end of it if that name is already in scope.
In the future, we can probably apply more heuristics here to wind up with more
useful names by default, but for now this resolves the immediate problem.
> fix: Extract Function produces duplicate fn names

- editors/code/src/commands.ts
Related to #12699, but doesn't fix it because we still register the providers multiple times.
> internal: use different schemes for the custom views

- Cargo.lock
- crates/hir-expand/Cargo.toml
- crates/hir-expand/src/mod_path.rs
Saves like a megabyte on r-a itself.
> internal: Use `SmallVec` to slightly shrink `ModPath` size

- crates/hir-def/src/generics.rs
- crates/hir/src/lib.rs
- crates/ide-completion/src/completions/type.rs
- crates/ide-completion/src/tests/type_pos.rs
- crates/rust-analyzer/tests/slow-tests/tidy.rs
- Fix #12140
- Also fix tidy check does not work for marks in multiline
> Complete type param/associated type in trait generic arg per arg index

- .github/workflows/publish.yml
Attempting to publish for example ra_ap_text-edit when ra_ap_text_edit
has already been published is rejected by crates.io.
> publish workflow: Fix names for existing crates

- crates/ide-assists/src/handlers/extract_variable.rs
- crates/ide-assists/src/utils/suggest_name.rs
When extracting a field expression, if RA was unable to resolve the type of the
field, we would previously fall back to using "var_name" as the variable name.
Now, when the `Expr` being extracted matches a `FieldExpr`, we can use the
`NameRef`'s ident token as a fallback option.
fixes #10035
> fix: Improve suggested names for extracted variables

- crates/hir-def/src/macro_expansion_tests/mbe.rs
- crates/hir-def/src/macro_expansion_tests/mbe/meta_syntax.rs
- crates/mbe/src/benchmark.rs
- crates/mbe/src/expander/matcher.rs
- crates/mbe/src/expander/transcriber.rs
- crates/mbe/src/parser.rs
- crates/mbe/src/tt_iter.rs
Part of https://github.com/rust-lang/rust-analyzer/issues/11952
Fixes https://github.com/rust-lang/rust-analyzer/issues/12675
> feat: Implement `ignore`  and `index` metavar expression

- crates/ide-assists/src/handlers/auto_import.rs
- crates/ide-completion/src/completions/flyimport.rs
- crates/ide-completion/src/snippet.rs
- crates/project-model/src/workspace.rs
- crates/rust-analyzer/src/handlers.rs
- docs/user/manual.adoc
The config keys were drastically reorganized by #12010, but the docs don't reflect the updates, causing inconsistency and confusion.  I checked for such obsolete configuration keys and updated to the new one.  For reproducibility, I attach a small shell script that I used to examine the old keys.  Now the script only detects `cargoExtraArgs` and `overrideCargo`, which originates from other type definition in the code but not from the configuration.
<details><summary>script</summary>
```bash
echo "allowMergingIntoGlobImports
exprFillDefault
importEnforceGranularity
importGranularity
importMergeBehavior
importMergeBehaviour
importGroup
importPrefix
warmup
loadOutDirsFromCheck
runBuildScripts
runBuildScriptsCommand
useRustcWrapperForBuildScripts
enableExperimental
procAttrMacros
breakPoints …
```
> Fix obsolete config keys

- crates/ide-diagnostics/src/handlers/type_mismatch.rs
close https://github.com/rust-lang/rust-analyzer/issues/11383
When type mismatch is `&str` -> `String` try to fix it.
> Add str_ref_to_string fix

- crates/hir-expand/src/lib.rs
- crates/ide-assists/src/handlers/generate_function.rs
- crates/ide-assists/src/handlers/inline_call.rs
- crates/ide-db/src/search.rs
- crates/ide-diagnostics/src/handlers/unresolved_proc_macro.rs
Fixes https://github.com/rust-lang/rust-analyzer/issues/12657
> fix: Fix unresolved proc macro diagnostics pointing to macro expansions
